### ISSUE TITLE
Row-Level Security Azure SQL DW

### ISSUE THREAD

**Issue by hau-mal** [MicrosoftDocs/architecture-center#1003]
Azure SQL Data Warehouse supports row-level-security: 
see https://docs.microsoft.com/en-us/sql/relational-databases/security/row-level-security?view=sql-server-2017 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba35cbb-4160-0b5d-6829-103b25ad6ce9
* Version Independent ID: fa12ea8e-401a-9567-7b35-ffff532a99b6
* Content: [Choosing a batch processing technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing)
* Content Source: [docs/data-guide/technology-choices/batch-processing.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/technology-choices/batch-processing.md)
* Service: **guidance**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @hau-mal Thank you for reporting this issue! We will investigate and make any necessary changes.
