### ISSUE TITLE
Time-Series Store /Log Store

### ISSUE THREAD

**Issue by hau-mal** [MicrosoftDocs/architecture-center#1004]
Pls. Consider a Times-Series and Log Store like Kusto aka Azure Data Explorer in the BigData Architecture and the "Technology choices"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953d7d0d-651f-a566-1d28-6946c824e1ae
* Version Independent ID: 8f5b4264-dcc9-ad28-36fe-45463d15f52a
* Content: [Big data architectures](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/)
* Content Source: [docs/data-guide/big-data/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/big-data/index.md)
* Service: **guidance**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @hau-mal Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
Thank you for submitting this. We've taken this item to our internal backlog for consideration!
