### ISSUE TITLE
Many 'Conflicts' and deplyment errors for virtual NIC creation

### ISSUE THREAD

**Issue by CloudLassoUK** [MicrosoftDocs/architecture-center#1013]
Love the concept, however, as I am deploying it now there are many 'conflict' errors when the templates are submitted to create the NICs.  Could this be a timing issue?  I've been working with the repositories for a couple of months, and Azure for years, so I am confident that I am deploying it correctly.  Just a heads up.  I'll re-run it if I am able and see if the NICs complete once the networks have completed.

I've cleaned up an error message below.  As I mentioned, there are several similar errors, all of which seem to be NICs.

"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details.

 \\\\\\\"Resource /subscriptions/MyGUID/resourceGroups/ra-aad-ntier-rg/providers/Microsoft.Network/virtualNetworks/ra-aad-ntier-vnet/subnets/web referenced by resource /subscriptions/31dc635d-99a8-40ad-b1f3-be54f9fa58f9/resourceGroups/ra-aad-onpremise-rg/providers/Microsoft.Network/networkInterfaces/ra-aad-ntier-web-vm2-nic1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9383c21-9143-1559-c1a8-e6f6dc830159
* Version Independent ID: 37c6c659-a6bc-633e-2b3f-337deb01c215
* Content: [Integrate on-premises AD domains with Azure Active Directory](https://docs.microsoft.com/en-gb/azure/architecture/reference-architectures/identity/azure-ad)
* Content Source: [docs/reference-architectures/identity/azure-ad.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/azure-ad.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @CloudLassoUK Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
Should be fixed by issue corrected in early June 2019
