### ISSUE TITLE
The reason of 15 letters restriction for Windows VM hostname

### ISSUE THREAD

**Issue by v-maroge** [MicrosoftDocs/architecture-center#1045]
"The restrictions above are for the host name."
Is the specific reason for why Windows VM hostname is limited to 15 characters is because of NetBIOS consideration? If I do name resolution only using hostnames, will it still be recognized even if it's larger than 16 characters just as it does for Windows computers? What are other concerns for making host names longer than 15 characters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @v-maroge Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
This is accurate per Microsoft support: https://support.microsoft.com/en-us/help/909264/naming-conventions-in-active-directory-for-computers-domains-sites-and #please-close. Thanks so much for the question and apologies for the (extensive) delay in getting to this!
