### ISSUE TITLE
Content is out of date

### ISSUE THREAD

**Issue by jzoran05** [MicrosoftDocs/architecture-center#1069]
There is number of new Azure services added (e.g. Digital Twins, Virtual Assistants) - it would be great to keep this page up to date...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure and AWS services compared - multicloud](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#networking-and-content-delivery)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @jzoran05 Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by doodlemania2** [comment]
Merged in. Thank you! #please-close
