### ISSUE TITLE
Does the diagrams under "Departments and Accounts" need updating?

### ISSUE THREAD

**Issue by RoyKimYYZ** [MicrosoftDocs/architecture-center#1102]
Does the diagrams under "Departments and Accounts" need updating with Management groups as a layer between Account Management and Subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc23836-c10c-5c47-818b-42c53916b269
* Version Independent ID: b5ef4736-1df9-e3d9-eafb-7782cc0d5fea
* Content: [Best practices for enterprises moving to Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/appendix/azure-scaffold?toc=/azure/governance/toc.json)
* Content Source: [docs/cloud-adoption/appendix/azure-scaffold.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/appendix/azure-scaffold.md)
* Service: **guidance**
* GitHub Login: @rdendtler
* Microsoft Alias: **rodend**

**Comment by rdendtler** [comment]
Management groups can be used in that way, however, they don't have to relate to the hierarchy.  Management Groups can span across the "traditional" hierarchy, so I'm not sure it would be the right place to show it.  However, I'll look and see if I can incorporate the idea in the image without denoting it as a dependent hierarchy.

**Comment by RoyKimYYZ** [comment]
When you say mgt group span the hierarchy, it can also be a parent of an an account?

 I am aware that mgt group can be a parent of another mgt group.

Also there is a tenant root mgt group which fixed.


Sent from my iPhone

On Dec 19, 2018, at 11:43 AM, Rob Dendtler <notifications@github.com<mailto:notifications@github.com>> wrote:


Management groups can be used in that way, however, they don't have to relate to the hierarchy. Management Groups can span across the "traditional" hierarchy, so I'm not sure it would be the right place to show it. However, I'll look and see if I can incorporate the idea in the image without denoting it as a dependent hierarchy.

**Comment by doodlemania2** [comment]
Hello there! These graphics are currently accurate, but can be refactored to be more clear. We've taken this into our internal backlog for review. May also apply to CAF. Thanks for raising this and apologies for the long delay here.
