### ISSUE TITLE
Does Azure AD B2C support Role Store?

### ISSUE THREAD

**Issue by JipingWang** [MicrosoftDocs/architecture-center#1124]
I see AWS Cognito has role management, you just to add
    services.AddCognitoIdentity();
what's the equivalent to AWS service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @JipingWang Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
@JipingWang are you referring to this newly released preview: https://azure.microsoft.com/en-us/updates/b2c-admin-roles-preview/

**Comment by mike-urnun-msft** [comment]
Hey @JipingWang We will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
