### ISSUE TITLE
"We recommend you do not assign operations masters roles to the domain controllers deployed in Azure"

### ISSUE THREAD

**Issue by cuixi1222** [MicrosoftDocs/architecture-center#1153]
would you elaborate the reason for the recommendation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @cuixi1222 Thank you for your feedback! We will review and update as appropriate.

**Comment by Justinha** [comment]
It's just so the roles remain available. If you place the Azure DCs in an availability set, then Azure may take one of the DCs offline, and you can't control which one is taken offline. So you could end up with a role holder being offline for a time. That might not cause any trouble but to have full control over their availability, you could just leave the role holders on premises.

**Comment by doodlemania2** [comment]
@Justinha is correct on this. Gonna go ahead and #please-close but if you have additional questions, definitely let us know!
