### ISSUE TITLE
VNET Gateways required?

### ISSUE THREAD

**Issue by CloudCrusader** [MicrosoftDocs/architecture-center#1162]
why are the VNET gateways required for this to work? Would it not be more easy and cost efficient to use VNET Peering instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Multi-region N-tier application for high availability - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/n-tier/multi-region-sql-server.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @CloudCrusader Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
Closed by https://github.com/MicrosoftDocs/architecture-center/commit/35d4a7104f810c9aec9591f62aa5c40f63c56078 #please-close
