### ISSUE TITLE
Links to deprecated articles

### ISSUE THREAD

**Issue by jacobestell** [MicrosoftDocs/architecture-center#1180]
Links to Data Partitioning Guidance, Data Consistency Primer, CQRS Journey, Introduction to Command Query Segregation are all flagged as no longer updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43af0b36-1389-2302-9c67-5e6560c9814b
* Version Independent ID: 235ef144-78ca-1fbc-e3f8-e69afcc04ff5
* Content: [Command and Query Responsibility Segregation (CQRS) pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @jacobestell Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by doodlemania2** [comment]
Thank you for reporting. We're working to bring this content up to date and move it into our Architecture Center very soon!
