### ISSUE TITLE
out of date 

### ISSUE THREAD

**Issue by stephenspann27** [MicrosoftDocs/architecture-center#1184]
Commercial PaaS-IaaS-DBaaS framework category needs to have "AWS outposts" added

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @stephenspann27 Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by doodlemania2** [comment]
Merged in today. Thank you! #please-close
