### ISSUE TITLE
Entity Managed Disk is not in the Article

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/architecture-center#1185]
Length: 1-80
Casing: Case insensitive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @weyCC81 Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by nkrueger-epic** [comment]
Could you also make sure to include the scope of managed disks? I can't find it documented anywhere. I think managed disk names just need to be unique to the resource group.

**Comment by weyCC81** [comment]
Hi @nkrueger-epic, yes that is actually true otherwise you get the following message "There is already a resource with the same name and type within the current resource group."

**Comment by nkrueger-epic** [comment]
@weyCC81 good to know, thanks. I never tried to cause a conflict and see what happens.

**Comment by qub1n** [comment]
@weyCC81 
Would you please so kind and specify maxim length of Managed disk name? Or generally overall naming limitations for manage disk.
