### ISSUE TITLE
Event hub

### ISSUE THREAD

**Issue by rashmipankaj** [MicrosoftDocs/architecture-center#1195]
Event hubs doesn’t fall in this category?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e8312a-a2b2-c683-2bc5-ebadf37cfbfe
* Version Independent ID: 23ab5226-f35d-cb04-109d-a4e651785f8d
* Content: [Publisher-Subscriber pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/publisher-subscriber)
* Content Source: [docs/patterns/publisher-subscriber.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/publisher-subscriber.md)
* Service: **guidance**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @rashmipankaj Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
Thanks for the feedback. We feel that Event Hubs is really more of an ingest mechanism, not really a good candidate for pub/sub style design patters. Please let us know if you have additional questions. #please-close
