### ISSUE TITLE
Slightly outdated description for AzCopy

### ISSUE THREAD

**Issue by yangsiyu007** [MicrosoftDocs/architecture-center#1200]
The paragraph "AzCopy. Use AzCopy from a Windows or Linux command-line to easily copy data to and from Azure Blob, File, and Table storage with optimal performance..." should probably be updated since the new version of AzCopy is cross-platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e037b-a226-62cf-6e2b-2af8783b7add
* Version Independent ID: c666597e-52ae-ee51-474a-c4dd3a63941b
* Content: [Choosing a data transfer technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer)
* Content Source: [docs/data-guide/scenarios/data-transfer.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/scenarios/data-transfer.md)
* Service: **guidance**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @yangsiyu007 Thank you for reporting this issue! We will review and make any necessary changes.
