### ISSUE TITLE
What's `AuthenticationValidated`?

### ISSUE THREAD

**Issue by InPermutation** [MicrosoftDocs/architecture-center#1250]
https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/authenticate#authentication-ticket  says "You can access the ticket inside the **AuthenticationValidated** or **TicketReceived** event." but there is no documentation for the `AuthenticationValidated` event. Is this a typo? It seems like I should use `TokenValidated` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcd84ea-bc3e-0449-83da-3295143988be
* Version Independent ID: a7e08b3a-46f8-6eb4-961a-35fda94353c0
* Content: [Authentication in multitenant applications](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/authenticate#authentication-events)
* Content Source: [docs/multitenant-identity/authenticate.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/authenticate.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by InPermutation** [comment]
Also mentioned by https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/claims which makes me think I'm looking in the wrong place entirely for events?

**Comment by KetanChawda-MSFT** [comment]
@InPermutation Thank you for providing the feedback. I have assigned this issue to content author to review and update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!

**Comment by johnnyreilly** [comment]
I'm also puzzled!
