### ISSUE TITLE
Is D365 a Spoke

### ISSUE THREAD

**Issue by stevep10** [MicrosoftDocs/architecture-center#1264]
Great article!
Be interested to find out how Dynamics 365 - Finance & Ops would exist in this Hub/Spoke model.
Keeping in mind that an environment may consist of both deployment types - 
Azure subscription (PAYG) D365 instance as well as the 
Microsoft managed private D365 instance

So maybe a reference architecture extending from above and representing other key services such as:
- D365
- Office365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d8a578-f9f1-53af-64d0-808f1fde6c9c
* Version Independent ID: 8a647cb7-2d10-53ed-5459-4356ef607e77
* Content: [Azure virtual datacenter: A network perspective](https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter)
* Content Source: [docs/vdc/networking-virtual-datacenter.md](https://github.com/mspnp/architecture-center/blob/master/docs/vdc/networking-virtual-datacenter.md)
* Service: **architecture-center**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by KetanChawda-MSFT** [comment]
@stevep10 Thank you for providing your feedback. We will review this and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson any thoughts on this?

**Comment by doodlemania2** [comment]
Thank you for this idea! Closing for now but we've added this item to our internal backlog for possible inclusion in an upcoming release.
