### ISSUE TITLE
Update with all other Azure Services with the context of its BCDR feature and recommendations 

### ISSUE THREAD

**Issue by sowsan** [MicrosoftDocs/architecture-center#1265]
This is a great document provides the foundation concept but it looks outdated as the e.g are talking about the cloud services (web roles). It will be great if there is a single document which shows all available azure services and its recommended DR solution. E.g for Azure storage GRS/R-GRS, App Service with Traffic Manager etc. There are many services like Application Insights, Azure Search etc. has no specific information available, at least I couldn't find them. It will be great to keep all in single document under the context of BCDR like the regions, compliance documentation we have for all azure services. This is going to very helpful when we design enterprise grade solution architecture on top of Azure. Thanks for your help !

https://docs.microsoft.com/en-us/azure/architecture/resiliency/disaster-recovery-azure-applications

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefa78da-afbb-5529-d707-b158d991cb16
* Version Independent ID: 64342775-2746-0e51-9aba-253074530f27
* Content: [Disaster recovery for Azure applications](https://docs.microsoft.com/en-us/azure/architecture/resiliency/disaster-recovery-azure-applications)
* Content Source: [docs/resiliency/disaster-recovery-azure-applications.md](https://github.com/mspnp/architecture-center/blob/master/docs/resiliency/disaster-recovery-azure-applications.md)
* Service: **architecture-center**
* GitHub Login: @adamglick
* Microsoft Alias: **pnp**

**Comment by sowsan** [comment]
An e.g for instance QnA maker they have a awesome documentation here https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/business-continuity-plan 

Looking for a central place to browse all other services for BCDR context

**Comment by mike-urnun-msft** [comment]
Hi @sowsan Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
Closing for now, but we've added this to our internal backlog for a future release of the solution. Great idea to bring them all together!
