### ISSUE TITLE
Multi-region deployments / WAF

### ISSUE THREAD

**Issue by fawohlsc** [MicrosoftDocs/architecture-center#1282]
Really awesome. Suggestion for making it even more awesome: Can you add multi-region deployments via Azure Traffic Manager and using Azure Application Gateway for WAF? Many thanks :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks)
* Content Source: [docs/reference-architectures/microservices/aks.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/microservices/aks.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @fawohlsc Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by dragon119** [comment]
@fawohlsc  Thank you for your suggestion. We'll publish next one with more features such as advanced networking, WAF, Service-mesh etc. Traffic manager and Federation may be included in the one after the next. Stay tuned!

**Comment by fawohlsc** [comment]
Perfect. Many thanks @dragon119 :-)

**Comment by doodlemania2** [comment]
Closing as this is being actively worked on in our internal backlog!
