### ISSUE TITLE
Make the diagrams clearer about direction of communication

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/architecture-center#1294]
It would be useful to make the diagrams clearer in the sense that the Ambassador is used for communication initiated from the Application to the Remote Service, and not the other way around. As the arrows in both directions are the same, the diagrams are ambiguous in this regard. Could we make the returning arrow lighter, or label the arrows with "request" and "response"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e99886-d5c7-ca7c-6943-ee31cfc39902
* Version Independent ID: 04021af5-10a9-b600-5f44-354d0c0e50c9
* Content: [Ambassador pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/ambassador)
* Content Source: [docs/patterns/ambassador.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/ambassador.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@algattik Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by MikeWasson** [comment]
@algattik Thanks for the feedback, I agree the diagram is ambiguous. I'll add labels.
