### ISSUE TITLE
Can the template consume complex objects or only simple types?

### ISSUE THREAD

**Issue by IanMercer** [MicrosoftDocs/architecture-center#1301]
From the examples it appears you always have to reference the terminal string values in the object (through indexes and dot operators all the way down) but it doesn't say that in the article. It might be worth mentioning this explicitly.

It would be great for example if, when you have the same structure in part of your parameter object, you could simply do something like: `"subnets": parameters('VNetSettings').subnets` instead of having to pick the object apart and redeclare it all over again in what is a very fragile and hard to maintain process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa870d42-1b00-d600-4fef-dd67219a1dc6
* Version Independent ID: 61fa68a5-a08b-7693-ebfd-18711ebd1bbb
* Content: [Use an object as a parameter in an Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/objects-as-parameters)
* Content Source: [docs/building-blocks/extending-templates/objects-as-parameters.md](https://github.com/mspnp/architecture-center/blob/master/docs/building-blocks/extending-templates/objects-as-parameters.md)
* Service: **architecture-center**
* GitHub Login: @petertay
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @IanMercer Thank you for your feedback! We will review and update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@IanMercer The document mention that 
>The values of our `VNetSettings` object are applied to the properties required by our virtual network resource using the `parameters()` function with both `the [] array indexer` and `the dot operator`. This approach works if you just want to statically apply the values of the parameter object to the resource. However, if you want to dynamically assign an array of property values during deployment you can use a copy loop. To use a [`copy loop`](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-multiple), you provide a JSON array of resource property values and the copy loop dynamically applies the values to the resource's properties.

you can also look at [this document](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-templates-parameters#objects-as-parameters) for reference.

**Comment by IanMercer** [comment]
Thanks, but none of these examples show that you can in fact apply a JSON object directly to a complex template property without having to destructure it and rebuild it field-by-field:

e.g. define a variable:
        "permissions" : {
            "keys": [ "encrypt", "decrypt", "create", "get", "sign" ],
            "secrets": [ "get", "set" ],
            "certificates": [ "get" ]
        }

and later consume it:
                "accessPolicies": [
                    {
                        "tenantId": "[subscription().tenantId]",
                        .....
                        "permissions": "[variables('permissions')]"
                    }
                ]

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
