### ISSUE TITLE
Improve SQL Server resiliency

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/architecture-center#1302]
Even with Active/Passive this would not be an automatic fail-over since you would have to change the secondary database to allow writes.  Consider changing the diagram to show the use of a SQL endpoint - this is more resilient as would failover to the secondary in the case of the SQL Server going down as well as the entire data centre

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @phatcher Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
