### ISSUE TITLE
Link for "Guidelines for Deploying Windows Server Active Directory on Azure Virtual Machines" is broken

### ISSUE THREAD

**Issue by lynnhtowle** [MicrosoftDocs/architecture-center#1319]
The link was extremely valuable to use as a reference when building DC's in Azure or in other virtual environments. It seems as if the page was removed from MSDN, and a similar page does not seem to exist on Microsoft Docs.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @lynnhtowle Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by PramodValavala-MSFT** [comment]
@lynnhtowle Thanks for reporting a broken link! Unfortunately, I believe that doc doesn't exist any more... officially at least.

I was able to find [a doc with the same title](https://github.com/toddkitta/azure-content/blob/master/articles/active-directory/active-directory-deploying-ws-ad-guidelines.md) in a github fork of an older Azure Doc Content repo I guess. Could you confirm if this is the same doc that you've referred to before?

**Comment by lynnhtowle** [comment]
"Officially" would be the operative word :) I think it was available up until the last few weeks.

The fork is similar to the other doc, but not exactly the same. That said, it does explain some of the main theories behind DC's in Azure, all in one doc, so it's very helpful to use as a reference.

**Comment by PramodValavala-MSFT** [comment]
@lynnhtowle Glad to hear that!

Here is a [comment](https://github.com/MicrosoftDocs/azure-docs/issues/7471#issuecomment-389996423) from another issue which talks about the doc's retirement.

We are assigning this issue to the content author for further investigation.

**Comment by doodlemania2** [comment]
Closed closed.
