### ISSUE TITLE
Missing App service / SQL

### ISSUE THREAD

**Issue by owingruters** [MicrosoftDocs/architecture-center#1320]
Hi,

I am missing quite some resourcetypes in the Naming rules and restrictions. Especially for App service and SQL. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#feedback)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@owingruters Thank you for providing your feedback. We will review this and provide an update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
