### ISSUE TITLE
Resource Group region matters

### ISSUE THREAD

**Issue by Teodelas** [MicrosoftDocs/architecture-center#1321]
Hi.  We should add a section on the importance / criticality of Resource Group region placement.  If the region a RG is assigned to is offline, none of the resources in that region can be updated (regardless of the region of the resource).  This could severely impact DR as customers would not be able to start, scale up, scale out, etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefa78da-afbb-5529-d707-b158d991cb16
* Version Independent ID: 64342775-2746-0e51-9aba-253074530f27
* Content: [Disaster recovery for Azure applications](https://docs.microsoft.com/en-us/azure/architecture/resiliency/disaster-recovery-azure-applications)
* Content Source: [docs/resiliency/disaster-recovery-azure-applications.md](https://github.com/mspnp/architecture-center/blob/master/docs/resiliency/disaster-recovery-azure-applications.md)
* Service: **architecture-center**
* GitHub Login: @adamglick
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @Teodelas Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.
