### ISSUE TITLE
Remove references to Azure ML Workbench

### ISSUE THREAD

**Issue by ezwiefel** [MicrosoftDocs/architecture-center#1327]
Remove AML Workbench and substitute AML Services - including the MLOps information, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8fb10e-3276-6086-794f-1418bef4b05e
* Version Independent ID: bf32a2b4-5999-b6ef-6cb6-f765ff1c550c
* Content: [Machine learning at scale](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/machine-learning-at-scale#feedback)
* Content Source: [docs/data-guide/big-data/machine-learning-at-scale.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/big-data/machine-learning-at-scale.md)
* Service: **architecture-center**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @ezwiefel Thank you for your feedback! We will review and update as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@ezwiefel Since this doc update requires updated artwork, we have assigned this issue to the content author to review and update accordingly.

**Comment by MikeWasson** [comment]
@ezwiefel Thanks for the feedback. Looking at the diagram, I feel it's problematic in general because it implies a recommended architecture but doesn't refer to any specific ML reference architectures. In other words I don't feel it adds much to the article. I'm going to remove the image for now.
