### ISSUE TITLE
Key/Value vs Object storage

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/architecture-center#1342]
Key/Value and Object storage are extremely similar, potentially the same.
It would be good if the doc could draw out the similarities and differences. They should be discussed together. A person looking for a key/value store, based strictly on this doc, wouldn't consider blob storage, and that's just not right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a2dd11-b2f0-7821-a877-fc09af4ac967
* Version Independent ID: f7537dfd-5472-f0d2-d344-db85fd65bf71
* Content: [Choose the right data store - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview#object-storage)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @jtuliani Thank you for your feedback! We will review and update as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@jtuliani I believe the `storing and retrieving large binary objects` phrase in the object storage description is a sufficient difference right?

@MikeWasson Thoughts?

**Comment by jtuliani** [comment]
@PramodValavala-MSFT I really don't think that covers it. Under Key-Value, it says only SOME key-value stores impose a size limit on the value. And at https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-comparison#keyvalue-stores it says the 'data size tends to be large'.

**Comment by PramodValavala-MSFT** [comment]
@jtuliani That's true. I guess based on the examples - the Key/Value data store is implying in-memory use cases i.e., Redis use cases & object data store is implying blob storage. They are indeed similar to a degree but vary in their implementation and use cases mostly.

I will be assigning this issue to the content author for further review and to update the doc accordingly.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
