### ISSUE TITLE
About Command line tools (Other:)

### ISSUE THREAD

**Issue by matakeda1** [MicrosoftDocs/architecture-center#1345]
In the following link of "Command line tools (Other:)", is this document has been updated by the newest information?
https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer#command-line-tools

And what is the "Optimized for big data"? Azure Data Lake Storage Gen2?
And what is the "Data Lake Store"? Azure Data Lake Storage Gen1?

Please check them. Thanks, Masaki.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e037b-a226-62cf-6e2b-2af8783b7add
* Version Independent ID: c666597e-52ae-ee51-474a-c4dd3a63941b
* Content: [Choosing a data transfer technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer#command-line-tools)
* Content Source: [docs/data-guide/scenarios/data-transfer.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/scenarios/data-transfer.md)
* Service: **architecture-center**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@matakeda1 Thank you for reporting this issue! We will investigate and make any necessary changes.

**Comment by JohnRusk** [comment]
Hi @KetanChawda-MSFT. I'm on the AzCopy V10 team, and was just about to log an issue about this when I saw that one was already logged. I'm not sure whether "optimized for big data" means "can transfer large data volumes" or " can transfer data to data lake".  In any case, AzCopy v10 can transfer large data volumes AND can transfer to Azure Data Lake Gen 2. So I think it should be shown as Optimized For Big Data.
