### ISSUE TITLE
Data Explorer

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/architecture-center#1346]
Where does https://azure.microsoft.com/en-us/services/data-explorer/ fit in? Surely it should be mentioned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a2dd11-b2f0-7821-a877-fc09af4ac967
* Version Independent ID: f7537dfd-5472-f0d2-d344-db85fd65bf71
* Content: [Choose the right data store - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @jtuliani Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
@jtuliani Should fall under Data Analytics so i've submitted a PR: MicrosoftDocs/architecture-center#1359

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by jtuliani** [comment]
Super thank you
