### ISSUE TITLE
Can we get a row for Azure App Services App in "Naming rules and restrictions"

### ISSUE THREAD

**Issue by VictorioBerra** [MicrosoftDocs/architecture-center#1348]
I think it should ride along with Function App. I would really like to see the Suggested Pattern and Example for an Azure App Services App, and or an Azure App Services Plan (serverfarm).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @VictorioBerra Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
@VictorioBerra I've added a row for WebApp in this PR: MicrosoftDocs/architecture-center#1360

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
