### ISSUE TITLE
Property names outdated

### ISSUE THREAD

**Issue by anas2204** [MicrosoftDocs/architecture-center#1350]
https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#policy-configuration-3
The property names for "RetryExponential" class seem to have changed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#policy-configuration-3)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @anas2204 Thank you for your feedback! We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@anas2204  Are you referring to the properties mentioned in this doc [https://docs.azure.cn/en-us/dotnet/api/microsoft.azure.servicebus.retryexponential?view=azure-dotnet#properties](https://docs.azure.cn/en-us/dotnet/api/microsoft.azure.servicebus.retryexponential?view=azure-dotnet#properties). Could you elaborate more on your ask.

**Comment by anas2204** [comment]
Ah, I meant the properties used in the constructor in this example - https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#examples-1

**Comment by DixitArora-MSFT** [comment]
@anas2204  There seems to be some change in the properties. So assigned this to content author to review and update as appropriate.

**Comment by MikeWasson** [comment]
@anas2204 Thanks - this code example uses the older [WindowsAzure.ServiceBus](https://www.nuget.org/packages/WindowsAzure.ServiceBus) package. I'll update the doc to show the newer [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus) package.
