### ISSUE TITLE
Comparison of HPC services needed

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/architecture-center#1352]
As a person new to the area, I need a comparison of HPC Pack, Azure Batch, and CycleCloud. Existing overviews of all 3 say basically the same thing: "helps you easily build and manage HPC clusters yada yada yada".

We need an overview that explains what they are, what the differences are, why 3 different options exist, and how you'd choose between them.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure](https://docs.microsoft.com/en-ie/azure/architecture/topics/high-performance-computing/#next-steps)
* Content Source: [docs/topics/high-performance-computing/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/topics/high-performance-computing/index.md)
* Service: **guidance**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @jtuliani Thank you for your feedback! We will review and update as appropriate.

**Comment by adamboeglin** [comment]
Thanks for the feedback!  I've added it to UserVoice to continue the discussion and prioritize it on our roadmap: https://azure-architecture.uservoice.com/forums/918625/suggestions/37226701
