### ISSUE TITLE
Slowly Changing Dimension join by SK, not by natural key

### ISSUE THREAD

**Issue by FernandoHidalgoSWBI** [MicrosoftDocs/architecture-center#1353]
According to Kimball best practices the fact table and the dimension table should join by a Surrogates key. The example shown in this page, and the use of Temporal Tables for SCD Type 2 seems to miss this point.
Wondering if I am missing something or MS has missed/ignore this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c337b22b-b387-5eea-9b16-656885eae759
* Version Independent ID: 6c1ad9b6-fdf4-f23a-20dc-118f262d0a8c
* Content: [Automated enterprise business intelligence (BI) - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-adf#feedback)
* Content Source: [docs/reference-architectures/data/enterprise-bi-adf.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/data/enterprise-bi-adf.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @FernandoHidalgoSWBI Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
