### ISSUE TITLE
Service Bus clarity

### ISSUE THREAD

**Issue by dmarlow** [MicrosoftDocs/architecture-center#1354]
Can someone explain how Time Buffer is used. It's not very clear.

Also, in the example for background, it has this:

Attempt 1: Delay ~1 sec. 
Attempt 2: Delay ~3 sec. 
Attempt 3: Delay ~6 msec.
Attempt 4: Delay ~13 msec.

is msec a typo here? If not, how is that computed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @dmarlow Thank you for your feedback! We will review and update as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@dmarlow This property seems to have been renamed to [TerminationTimeBuffer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.retryexponential.terminationtimebuffer?view=azure-dotnet#Microsoft_ServiceBus_RetryExponential_TerminationTimeBuffer) now and this property now dictates the maximum time for an operation.
Also, note that this property seems to be available only for [.NET Full](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.retryexponential?view=azure-dotnet) and not [.NET Core](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.retryexponential?view=azure-dotnet).

The `msec` does seem to be a typo. It should be `sec`. 😄

There seems to be quite a few details that need updating here. So, we are assigning this issue to the content author to further investigate and update accordingly.

**Comment by MikeWasson** [comment]
Finally getting to this. The confusion is there are actually two NuGet packages.

- [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus) is the newer package for .NET Standard. 
-  [WindowsAzure.ServiceBus](https://www.nuget.org/packages/WindowsAzure.ServiceBus) is is the older .Net Framework package.

As mentioned, `TerminationTimeBuffer` (not `TimeBuffer`) only exists in the older package. 

I have an update to this article ready to publish. Thanks for reporting this issue!
