### ISSUE TITLE
Please update to reference Azure Functions

### ISSUE THREAD

**Issue by aaronse** [MicrosoftDocs/architecture-center#1361]
Thank you for this doc, has lots of good general info regarding implementing background processing.

Please update to reference Azure Functions.  Please also update to replace references for depreciated Azure Scheduler to instead reference Scheduled Azure Functions and/or Azure Logic Apps Scheduler.

Thanks!

aaronse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a65e47-b024-0c7c-0ee9-21ff095abafd
* Version Independent ID: a764689a-168d-dcef-a297-c47f84ea2d12
* Content: [Background jobs guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#schedule-driven-triggers)
* Content Source: [docs/best-practices/background-jobs.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/background-jobs.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @aaronse Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!

**Comment by RudyCo** [comment]
Fully agree with @aaronse! This is a real world example of https://wiki.c2.com/?ProblemsWithDocumentation.
For instance, in the Azure Functions doc, Microsoft strongly advises to use them instead of WebJobs for the most common scenarii. There is no "single source of truth" and this leads to create ambiguity.
