### ISSUE TITLE
Error submitting the deployment request.

### ISSUE THREAD

**Issue by ntmsstudents** [MicrosoftDocs/architecture-center#1362]
Error submitting the deployment request.
Additional details from the underlying API that might be helpful: The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '7236b657-9bf1-4461-b016-9cb3bd37c03b'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5978df0f-98f5-f365-1912-48fc8c27566e
* Version Independent ID: 4f2b4216-1cc7-a267-eee4-d7716ce5ed03
* Content: [CI/CD pipeline for container-based workloads - Azure Example Scenarios](https://docs.microsoft.com/en-gb/azure/architecture/example-scenario/apps/devops-with-aks#feedback)
* Content Source: [docs/example-scenario/apps/devops-with-aks.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/apps/devops-with-aks.md)
* Service: **architecture-center**
* GitHub Login: @iainfoulds
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @ntmsstudents Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by mike-urnun-msft** [comment]
@ntmsstudents I've created a PR that fixes this issue: https://github.com/mspnp/solution-architectures/pull/6

In meantime, please refer to this comment on workaround: https://github.com/mspnp/solution-architectures/issues/5#issuecomment-473444558

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
