### ISSUE TITLE
Autoscaling documentation not complete

### ISSUE THREAD

**Issue by love2dishtech** [MicrosoftDocs/architecture-center#1363]
Autoscaling documentation and pointers to specific detailed sections are available for Service Fabric, VM Scale Sets, App Services, Azure Functions, Cloud Service etc However, additional information for Azure Kubernetes Service, Azure Container Service and Azure Container Instances should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e6cd92-676a-6d6f-2ea8-ebe9301f59a9
* Version Independent ID: edfbb571-5bcf-2339-2cce-5e6a22fd591c
* Content: [Autoscaling guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/auto-scaling#feedback)
* Content Source: [docs/best-practices/auto-scaling.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/auto-scaling.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@love2dishtech Thanks for your feedback. We will review this and update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
