### ISSUE TITLE
Link page not found

### ISSUE THREAD

**Issue by zoekdestep** [MicrosoftDocs/architecture-center#1373]
AML Studio link (first under AML Studio heading) gives a 404 - Page not found 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bdc71b-0a54-4cc4-1b79-f60e274e9a51
* Version Independent ID: 1783570c-3545-71c8-72d3-d5657f77c070
* Content: [Choosing a machine learning technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning?toc=%2Fen-us%2Fazure%2Fmachine-learning%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json#feedback)
* Content Source: [docs/data-guide/technology-choices/data-science-and-machine-learning.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/technology-choices/data-science-and-machine-learning.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @zoekdestep Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
Hi @zoekdestep Thanks again for reporting this issue! We have gone ahead and corrected the link; the changes should be live after the PR is approved and merged. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
