### ISSUE TITLE
how to change the value of a variable when debug python in visual studio?

### ISSUE THREAD

**Issue by wang-kangkang** [MicrosoftDocs/architecture-center#1374]
when i use visual studio 2019, if i debug a c++ program, i can change the value of variable; but if i debug a python program, changing the value of variable will throw an error:SyntaxError('invalid syntax',
how to change the value of a variable when debug python in visual studio?

**Comment by mike-urnun-msft** [comment]
Hi @wang-kangkang Since this channel is for driving improvements towards MS Docs, was there a specific doc that you were following?

**Comment by mike-urnun-msft** [comment]
@wang-kangkang Just following up on the previous comment above, let us know if there was a specific MS Doc that your feedback is applicable to, otherwise, we'll proceed to close this issue.

**Comment by wang-kangkang** [comment]
I found this function can be realize in another toolbar:tools->python->debug interaction(调试交互).
I really didn't read all  the documents, but I can channel the value in c++ program in immediate window, so I infer this window can change the value in python, but it doesn't work. I think it's a design flaw.
