### ISSUE TITLE
Typo in the last paragraph

### ISSUE THREAD

**Issue by averkinderen** [MicrosoftDocs/architecture-center#1375]
There is typo in the last paragraph: it's governance not goverance.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31205281-634d-58aa-d6f5-832502786a49
* Version Independent ID: aa764653-fc4d-0afe-b5da-b7773f3c35b9
* Content: [CAF: What is cloud resource governance? - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/getting-started/what-is-governance#feedback)
* Content Source: [docs/cloud-adoption/getting-started/what-is-governance.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/getting-started/what-is-governance.md)
* Service: **architecture-center**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @averkinderen Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by mike-urnun-msft** [comment]
Hi @averkinderen Thanks again for reporting these typos! I have gone ahead and corrected them; the changes should be live as soon as the PR is approved and merged. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
