### ISSUE TITLE
namespace of OperationTransientException

### ISSUE THREAD

**Issue by DriezL** [MicrosoftDocs/architecture-center#1379]
What's the namespace of OperationTransientException? Is this correct? Is it OperationCanceledException?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497c1436-d32c-1fb5-3209-22058fece4b2
* Version Independent ID: 4818d7be-c866-39bc-f2c3-d7af59d2cd4e
* Content: [Retry pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry)
* Content Source: [docs/patterns/retry.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/retry.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @DriezL Thank you for your feedback! We will review and update as appropriate.

**Comment by reddyrajanala** [comment]
I would recommend using Polly
https://github.com/App-vNext/Polly/wiki/Retry

**Comment by MikeWasson** [comment]
@DriezL I think this came from the old Transient Fault Handling Application Block library. In general it will depend on your specific code base. And to @reddyrajanala 's point, it's generally better to use a general purpose retry library. The code in this article is meant to illustrate the pattern.

**Comment by DriezL** [comment]
Thanks @reddyrajanala , @MikeWasson

**Comment by hungarianguy** [comment]
I still am not seeing the namespace for this. @mike-urnun-msft how was this issue addressed?  and there is no pull requests linked.
