### ISSUE TITLE
Visio diagram doesn't match

### ISSUE THREAD

**Issue by JazzyWagdaddy** [MicrosoftDocs/architecture-center#1380]
The Visio diagram that you download is similar to but doesn't match the diagram in the picture.  The Visio diagram you download is more complex.  Please have the graphic and Visio diagram match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#feedback)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @JazzyWagdaddy Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
@JazzyWagdaddy The Visio download has all 4 identity-related reference architectures. The one for "Extend AD DS to Azure" is on the tab named "AD DS"
