### ISSUE TITLE
Can you

### ISSUE THREAD

**Issue by MCKRUZ** [MicrosoftDocs/architecture-center#1381]
Include the visio file for the diagram above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d6aeb8-ec6a-4d27-2d10-1b404de450b7
* Version Independent ID: 65b165e4-a2e4-7f57-19eb-884fce7bf880
* Content: [Build an enterprise-grade conversational bot](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/conversational-bot)
* Content Source: [docs/reference-architectures/ai/conversational-bot.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/ai/conversational-bot.md)
* Service: **architecture-center**
* GitHub Login: @roalexan
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @MCKRUZ Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by roalexan** [comment]
Yes, I'll track it down.

**Comment by doodlemania2** [comment]
@roalexan did this get found?

**Comment by MikeWasson** [comment]
@doodlemania2 @roalexan - I have the file.
