### ISSUE TITLE
Add Management Groups

### ISSUE THREAD

**Issue by woutervanranst** [MicrosoftDocs/architecture-center#1382]
Suggestion to add the Management Groups layer to this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49c17e1-43a8-3103-f2c9-e95e4620bb75
* Version Independent ID: 2f9cbc64-0f9e-ff5b-c5fa-ffe091e53b81
* Content: [CAF: Resource access management in Azure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/getting-started/azure-resource-access)
* Content Source: [docs/cloud-adoption/getting-started/azure-resource-access.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/getting-started/azure-resource-access.md)
* Service: **architecture-center**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @woutervanranst Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by d83194** [comment]
I agree, adding in a mention of Management Group would be welcomed. Is there an ETA on this? Cheers

**Comment by doodlemania2** [comment]
Merged with CAF internal backlog! Thanks so much.
