### ISSUE TITLE
Overcoming VNet peering limits - Mention that NVAs are required

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/architecture-center#1387]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/architecture-center.de-de/issues/3
The user is making a suggestion on the original documentation

@marcelkmfst commented:
Hi,

under Overcoming VNet peering limits, the Spoke-Hub-Hub model is mentioned. I strongly recommend that you mention that NVAs for Routing are required deployed in the Spoke-Hub as transient routing is not supported. I had a customer who implemented that model based on this arcticle and now they recognized that NVAs are required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @CeciAc Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by Tblanchin** [comment]
"NVAs for Routing are required deployed in the Spoke-Hub as transient routing is not supported" => means Spoke-hub-hub topology is not supported ?
Is there an alternative solution ?

**Comment by doodlemania2** [comment]
This is accurate as a best practice. Spoke/Hub/Hub would add additional complexities that are not easy to troubleshoot if there's a routing problem with one of the NVAs. The Enterprise Pattern speaks to the use case of a single Hub region. If you are a multi-national with multiple Hubs, you would likely be leveraging a combination of Peering and ExpressRoute Premium at that point. Great questions. Please let us know if it needs additional clarity.
