### ISSUE TITLE
Link to  Data Consistency Primer

### ISSUE THREAD

**Issue by DivyeshTikmani** [MicrosoftDocs/architecture-center#1390]
Do we have updated link to Data Consistency Primer - on this page. Currently its directing to :
https://msdn.microsoft.com/library/dn589800.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e6978f-1eb7-78ca-d785-441aef93cb38
* Version Independent ID: ade4b845-ce0d-f1e3-d1d0-b531318d9857
* Content: [Compensating Transaction pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/compensating-transaction#feedback)
* Content Source: [docs/patterns/compensating-transaction.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/compensating-transaction.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @DivyeshTikmani Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by mike-urnun-msft** [comment]
Hey @DivyeshTikmani Could you elaborate on your feedback and clarify what was wrong with the existing links?

**Comment by DivyeshTikmani** [comment]
Hi,

There is nothing wrong as such. Page to which ot redirected said that its
an older version and so was just checking if we had a new link for it.

Regards,
Divyesh

**Comment by dragon119** [comment]
It's not updated yet but is in our backlog.
