### ISSUE TITLE
Request to add API Management to this page

### ISSUE THREAD

**Issue by v-maroge** [MicrosoftDocs/architecture-center#1398]
[Enter feedback here]

Hi,

It would be great if you can add APIM naming rules and restrictions to this page. 
thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#feedback)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @v-maroge Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
Hi @v-maroge Thanks again for helping us drive improvements towards MS Docs! We have made a change and added a row under [General table](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#general) for naming convention for APIM service name.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
