### ISSUE TITLE
This is an example why I hate MSDN

### ISSUE THREAD

**Issue by Lbaralageen** [MicrosoftDocs/architecture-center#1401]
20 pages of water and no even single example how to write and use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4ffec9b-27ef-0f8c-5fcf-58347950feaf
* Version Independent ID: 8dadd327-8781-e1ef-e2b3-f75f416524e6
* Content: [Materialized View pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view#feedback)
* Content Source: [docs/patterns/materialized-view.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/materialized-view.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @Lbaralageen Thank you for your feedback! We will review and update as appropriate.

**Comment by dragon119** [comment]
@Lbaralageen, this pattern doesn't require 'code'. It just pre-populate a table for a complex query to make it faster.

**Comment by mike-urnun-msft** [comment]
Hi @Lbaralageen We will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
