### ISSUE TITLE
New Unicode characters allowed for naming Virtual Machines?

### ISSUE THREAD

**Issue by danielestevez** [MicrosoftDocs/architecture-center#1404]
From the latest blog update for the portal (https://azure.microsoft.com/en-gb/blog/microsoft-azure-portal-april-update/#Use%20of%20non-ASCII%20characters%20for%20virtual%20machine%20names)

> "With this release, we allow more Unicode characters in the virtual machine name, which is used as both the Azure resource name and the guest hostname"

However this is not updated in this documentation for the virtual machine resource in Compute. Which are those new Unicode characters allowed? Are they the same as in resource group (Regex pattern: `^[-\w\._\(\)]+$)`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @danielestevez Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
@danielestevez Blog post that you have referenced above appears discuss this change as part of Portal update, and not necessarily a platform update.

@telmosampaio @MikeWasson thoughts?

**Comment by danielestevez** [comment]
It does talk about Portal. Fact is now you can use Unicode characters to deploy VMs through portal and i don't know which characters are valid now
I haven't tried this through CLI though

**Comment by doodlemania2** [comment]
Updated doc on different channel. Should be all fixed!
