### ISSUE TITLE
Sample code should be upgraded to newer core version (is now on core 1)

### ISSUE THREAD

**Issue by nslindtner** [MicrosoftDocs/architecture-center#1407]
As noted in header

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: a441af2b-1092-2165-917d-33adf9862d24
* Version Independent ID: c945159a-67e0-7c38-823f-58a58b322650
* Content: [Identity management for multitenant applications](https://docs.microsoft.com/da-dk/azure/architecture/multitenant-identity/#feedback)
* Content Source: [docs/multitenant-identity/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @nslindtner Thank you for your feedback! We will review and update as appropriate.

**Comment by MikeWasson** [comment]
Thanks @nslindtner. Closing as a dup of https://github.com/mspnp/multitenant-saas-guidance/issues/104
