### ISSUE TITLE
Traefik does not support routing to partitioned (stateful) services

### ISSUE THREAD

**Issue by clazarr** [MicrosoftDocs/architecture-center#1408]
In the API Gateway section where it discusses using Traefik as a gateway to services in a Service Fabric cluster or in advanced scenarios for interservice routing within the cluster, it should be noted that Traefik, unlike Azure API Management, does not have functionality to resolve the partition of a service that a request should be routed to for stateful services with &gt; 1 partition. More background can be found here: https://github.com/containous/traefik/issues/3224

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d154d16-2727-4327-628e-3ae9e075342f
* Version Independent ID: 59b36468-c9dc-89d9-607c-a2a16a5274b9
* Content: [Microservices architecture on Azure Service Fabric](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/service-fabric#feedback)
* Content Source: [docs/reference-architectures/microservices/service-fabric.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/microservices/service-fabric.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@clazarr Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
This issue is now called out in the doc - thanks.
