### ISSUE TITLE
Traffic Flow from Spok1 to SPoke2

### ISSUE THREAD

**Issue by DMoonesinghe** [MicrosoftDocs/architecture-center#1412]
In the diagram below spoke-connectivity, you have NVA.  With each Spoke1 & Spok2 each has a UDR to send traffic to the other VNet.

If VNet Peering doesn't allow transitive traffic.  How does this traffic flow from Spok1 to Spoke 2.  Is it through the internet?  That is not communicated in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @DMoonesinghe Thank you for your feedback! We will review and update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@DMoonesinghe You are correct, and [this is discussed in the peering section of the doc](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#vnet-peering). 

Getting the 2 spokes to communicate via a NVA in the HUB VNET is also an option, and [it is discussed here](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#add-connectivity-between-spokes).

**Comment by mike-urnun-msft** [comment]
@DMoonesinghe We will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
