### ISSUE TITLE
Provide guidance for generating certificate data for other platforms

### ISSUE THREAD

**Issue by ricardoserradas** [MicrosoftDocs/architecture-center#1416]
Hi,

It would be good to have guidance on how to generate certificate data for other platforms such as MacOS and Linux [here](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/key-vault#set-up-a-client-certificate).

Also, it would be nice to explain this script step by step if you want community to generate guidance for these platforms. I don't know, for example, what is required on each field of the output JSON.

Add:

I tested using PowerShell Core on MacOs and it seems not to have all the methods from PSPKI Module. If so, it would make simpler just to add an instruction to use PowerShell core.

Thanks
Ricardo S M Serradas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5df2491-1abe-0211-efbf-c1fb384862e9
* Version Independent ID: f7f0d2cf-3f4f-44dc-54aa-cd59221264d2
* Content: [Use Key Vault to protect application secrets](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/key-vault#feedback)
* Content Source: [docs/multitenant-identity/key-vault.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/key-vault.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @ricardoserradas Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
