### ISSUE TITLE
Fix some parameter issues on Setup-KeyVault.ps1 

### ISSUE THREAD

**Issue by ricardoserradas** [MicrosoftDocs/architecture-center#1417]
Hi,

I was following [this guidance](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/key-vault) and I could not use the script [scripts/Setup-KeyVault.ps1](scripts/Setup-KeyVault.ps1) because of two reasons:

- We need the `ResourceGroupName` to run the command below:

```powershell
Set-AzureRmKeyVaultAccessPolicy
```

- For people who have multiple Azure Subscriptions, we need to select it right after we logged in to Azure using `Login-AzureRMAccount`. That's why I added the `SubscriptionId` parameter to:
  - `SetAccessPolicy`
  - `CreateKeyVault`

I already created [this PR](https://github.com/mspnp/multitenant-saas-guidance/pull/108) to tweak the script and I'll create another one here to sync the guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5df2491-1abe-0211-efbf-c1fb384862e9
* Version Independent ID: f7f0d2cf-3f4f-44dc-54aa-cd59221264d2
* Content: [Use Key Vault to protect application secrets](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/key-vault)
* Content Source: [docs/multitenant-identity/key-vault.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/key-vault.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@ricardoserradas Great! Thanks for your contribution & helping us drive improvements towards MS Docs!

**Comment by mike-urnun-msft** [comment]
We will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
