### ISSUE TITLE
Azure Standard Loadbalancer Architecture Not included

### ISSUE THREAD

**Issue by montereyharris** [MicrosoftDocs/architecture-center#1459]
Azure Standard Loadbalancer Architecture Not included as an option even though it is the consensus best practice for current gen NVAs in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bab6a90-43a3-3d83-d680-26683a3d833d
* Version Independent ID: f8eea094-d297-93e6-06ac-7652d059734f
* Content: [Deploy highly available network virtual appliances - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha)
* Content Source: [docs/reference-architectures/dmz/nva-ha.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/dmz/nva-ha.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@montereyharris Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
