### ISSUE TITLE
Public peering update on documentation

### ISSUE THREAD

**Issue by raunakjhawar** [MicrosoftDocs/architecture-center#1461]
Given public peering is no longer an active offering in Azure for new installations and has been merged with Microsoft Peering, the documentation still call out 6 /30 subnets instead of 4 /30 or even relaxed 4 /23 subnets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Connect an on-premises network to Azure using ExpressRoute - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @raunakjhawar Thanks for your feedback! Could you provide us with the URL of the specific documentation that your feedback is applicable to?

**Comment by raunakjhawar** [comment]
HI Mike, I have found one reference here -[https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute]( https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute) Look for text which comtains 6 /30 subnet.
