### ISSUE TITLE
TokenCache is changed to sealed

### ISSUE THREAD

**Issue by cbfrank** [MicrosoftDocs/architecture-center#1489]
In latest version of ADAL library, TokenCache is changed to sealed while this document still uses inheritance to support distributed cache

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab204a8d-c451-ef99-6610-139a0dee61ac
* Version Independent ID: 23a69ae2-70bc-aab5-bbe1-e9699d57558b
* Content: [Cache access tokens in a multitenant application](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache#feedback)
* Content Source: [docs/multitenant-identity/token-cache.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/token-cache.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @cbfrank Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
