### ISSUE TITLE
Add anchor links to help go back and forth on the article

### ISSUE THREAD

**Issue by ricardoserradas** [MicrosoftDocs/architecture-center#1491]
As it might be useful to go back and forth while reading the article, it would be nice to add anchor links to intermediate headers to help us navigate through it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5df2491-1abe-0211-efbf-c1fb384862e9
* Version Independent ID: f7f0d2cf-3f4f-44dc-54aa-cd59221264d2
* Content: [Use Key Vault to protect application secrets](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/key-vault)
* Content Source: [docs/multitenant-identity/key-vault.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/key-vault.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @ricardoserradas Thank you for your feedback! We will review and update as appropriate.
