### ISSUE TITLE
Ports for AD

### ISSUE THREAD

**Issue by eshudnow** [MicrosoftDocs/architecture-center#1493]
Article mentions, "The Active Directory subnet NSG requires rules to permit incoming traffic from on-premises."  The article should be updated to mention that rules are required to permit outbound traffic to on-premises as well.  The ports need to be bi-directional, not one way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend your on-premises Active Directory domain to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@eshudnow Thanks for the feedback! We will investigate and get back to you.

**Comment by PramodValavala-MSFT** [comment]
@eshudnow Thanks for catching this! I have a raised a PR to include this information.

**Comment by PramodValavala-MSFT** [comment]
@eshudnow Thanks for contributing to MS Docs!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
