### ISSUE TITLE
System State Backup

### ISSUE THREAD

**Issue by ElanShudnow** [MicrosoftDocs/architecture-center#1494]
I would mention in the Manageability Section that it is recommended to use Azure MARS Backups installed within each Domain Controller to back up System State.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend your on-premises Active Directory domain to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@eshudnow Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@eshudnow I believe Azure MARS Backup would indeed be the ideal candidate but will leave it to the content author to review and update this information.

**Comment by doodlemania2** [comment]
We've got a pretty comprehensive update being worked on here and I've included this note in our backlog. Going to close for now but you should see some updates pretty soon!
