### ISSUE TITLE
Availability Sets? Why not Availability Zones?

### ISSUE THREAD

**Issue by ElanShudnow** [MicrosoftDocs/architecture-center#1515]
The page mentions, "Deploy at least two VMs running AD DS as domain controllers and add them to an availability set."  May make sense to talk a bit about Availability Zones.  Are they not recommended for Domain Controllers?  My guess is they are preferred over Availability Sets but the article hasn't been updated in a long time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend your on-premises Active Directory domain to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#feedback)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @eshudnow Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
As AZ's aren't yet available globally, our architecture has to fall back to most commonly available / repeatable pattern. That said, we've added this to our backlog to check and see if the AD team is ready for updated guidance on DS in AZs. Thanks so much! #please-close
