### ISSUE TITLE
Need to update based on ADLS Gen2 Functionality

### ISSUE THREAD

**Issue by salavala** [MicrosoftDocs/architecture-center#1518]
Page needs to be updated based on the ADLS Gen2 functionality. It actually offers GRS. Incorrectly stated. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4931350d-0c12-00b2-64a8-112f67aba3f2
* Version Independent ID: eed89d06-7676-30e1-b801-2f67a09856f0
* Content: [Choosing a data storage technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-storage#feedback)
* Content Source: [docs/data-guide/technology-choices/data-storage.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/technology-choices/data-storage.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@salavala Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
