### ISSUE TITLE
EA required for cost management?

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/architecture-center#1521]
Says an EA is required to use Azure Cost Management. However, it is actually now available for PAYG as well (in Preview). https://azure.microsoft.com/en-gb/blog/azure-cost-management-now-general-availability-for-enterprise-agreements-and-more/

However, it's not available for CSP and some other subscription types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a3a55c-e9ef-0dbe-bf8e-951361e1135d
* Version Independent ID: bcb1fcac-e717-ad59-6f98-f98ecb8afba1
* Content: [CAF: Cost Management tools in Azure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/cost-management/toolchain)
* Content Source: [docs/cloud-adoption/governance/cost-management/toolchain.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/governance/cost-management/toolchain.md)
* Service: **architecture-center**
* Sub-service: **enterprise-cloud-adoption**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @jtuliani Thank you for your feedback! We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@jtuliani I have assigned this to content author to review and update as appropriate.

**Comment by BrianBlanchard** [comment]
This will be addressed in our next release, in a few days. Thanks for flagging this discrepancy.
