### ISSUE TITLE
Link ANEO down

### ISSUE THREAD

**Issue by AlexandreJean** [MicrosoftDocs/architecture-center#1523]
hello,
The link to the customer story Aneo is not available.
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing/#feedback)
* Content Source: [docs/topics/high-performance-computing/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/topics/high-performance-computing/index.md)
* Service: **guidance**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @AlexandreJean Thank you for your feedback! We will review and update as appropriate.
