### ISSUE TITLE
Unable to deploy solution using templates or the portal, only valid when used powersell

### ISSUE THREAD

**Issue by Heloiseboanerges** [MicrosoftDocs/architecture-center#1524]
Hi, 
I've tried to deploy the solution, but was only able to complete the deployment using poweshell, https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-coexist-resource-manager 
When using the portal the error "another gateway exists..." appeared. 
It seems the restrictions were removed, but the error persists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec640d8-1064-c083-4313-5e8c23fbc2cf
* Version Independent ID: 5f7c63ca-7ab2-9129-4c34-191286e67af1
* Content: [Connect an on-premises network to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute-vpn-failover#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @Heloiseboanerges Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
