### ISSUE TITLE
Underscore character is not working in VM names

### ISSUE THREAD

**Issue by ahpstar** [MicrosoftDocs/architecture-center#1527]
I have a support case where the customer has underscore in VM names (xxx_xx_xxx), and he is getting a validation error.  I have reproduced the same error in my subscription. The documentation states that underscore is supported as long as not used at the beginning or end on VM names.  Is underscore character supported in VM naming convention? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#feedback)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @ahpstar Thank you for your feedback! We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@ahpstar In the documentation under compute, Underscore is not mentioned under Virtual Machines. 
Follow this and let me know if any questions. https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#compute

**Comment by ahpstar** [comment]
Hello DixitArora-MSFT,


Thank you for replying back and confirming it for the customer.

I will relay to the customer that _ is not a valid character for compute.

When reading the document from the link you sent (which is also the one I read prior to sending you a question), it states the following under naming rules and restrictions.


[cid:e6a62401-61a8-40cb-bee1-705168eae7bf]


It sounds as though underscore can be used as long as it is not the first or last character in any name, and hence the customer and I were testing it.  In actuality, it sounds like underscore is not a supported character for compute.


Thank you much for clarifying it for us.  Have a great day.


Andy Park

Azure Cloud Engineer, Azure CXP Team | Office: + 1 (703) 657-1689 | email: andpar@microsoft.com<mailto:andpar@microsoft.com>

Working hours: Mon – Fri 8:00 AM to 4:00 PM EST



If you need immediate attention for any of the ongoing case while I am out of the shift, please send a separate email with case ID to acebackup@microsoft.com<mailto:acebackup@microsoft.com>. A team member will take action to help you. 

[612628EE]

12012 Sunset Hills Rd, Reston, VA, USA | Privacy Statement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D248681&data=02%7C01%7CPark.Andy%40microsoft.com%7Cfc684aa212394d04ddcd08d6aecc81d6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636888590701412564&sdata=V%2FSPJlSTR3trP0avdsBnx7yZpThz%2F1t5D1HaLuzyFl4%3D&reserved=0> 


________________________________

**Comment by DixitArora-MSFT** [comment]
@ahpstar For now will proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by ahpstar** [comment]
Hello,

Thank you for the assistance again. Sure, it can be closed.
Just a  quick question though.
As mentioned in the previous email, it seems the document is not clear or at least inconsistent in regard to underscore use when it comes to naming VMs.
The following section in the document seems to state that underscore is supported when it is not used at the beginning or at the end of VM naming.
Under the compute section, it does not show underscore as a valid character.
That’s how the customer thought the underscore character can still be used and is supported as long as it is not at the beginning or end of the compute VM name.
I also interpreted it similar to how the customer read it. Would you consider looking into whether it would need clarity in regard to using underscore character for VM names?
Thank you for taking my inputs.

[cid:image002.png@01D4FE66.25601480]

Andy Park
Azure Cloud Engineer, Azure CXP Team | Office: + 1 (703) 657-1689 | email: andpar@microsoft.com<mailto:andpar@microsoft.com>
Working hours: Mon – Fri 8:00 AM to 4:00 PM EST

If you need immediate attention for any of the ongoing case while I am out of the shift, please send a separate email with case ID to acebackup@microsoft.com<mailto:acebackup@microsoft.com>. A team member will take action to help you. 
[612628EE]
12012 Sunset Hills Rd, Reston, VA, USA | Privacy Statement<http://go.microsoft.com/fwlink/?LinkId=248681>
