### ISSUE TITLE
Multiple Gateways on one vNet

### ISSUE THREAD

**Issue by sangling** [MicrosoftDocs/architecture-center#1529]
The doc states: "Create the ExpressRoute virtual network gateway and the VPN virtual network gateway in the same VNet. This means that they should share the same subnet named GatewaySubnet." However, when trying to deploy a second gateway I get the error "A virtual network can't be associated with more than one gateway."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec640d8-1064-c083-4313-5e8c23fbc2cf
* Version Independent ID: 5f7c63ca-7ab2-9129-4c34-191286e67af1
* Content: [Connect an on-premises network to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute-vpn-failover#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md](https://github.com/mspnp/architecture-center/blob/live/docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by sangling** [comment]
The confusion here seems to be that the Expressoute and VPN virtual network gateways are two connections on the same gateway. Ref: https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-coexist-resource-manager

**Comment by mike-urnun-msft** [comment]
Hi @sangling Thank you for your feedback! We will review and update as appropriate.

**Comment by lmqferreira** [comment]
The inconsistency is still there. "Create the ExpressRoute virtual network gateway connection and the VPN virtual network gateway connection in the same VNet with a Gateway object already in place. They will both share the same subnet named GatewaySubnet." is inconsistent with the diagram.
