### ISSUE TITLE
Is CQRS an architecture style, or just an architecture pattern?

### ISSUE THREAD

**Issue by stvngao** [MicrosoftDocs/architecture-center#1531]
This page mentions CQRS is an architecture style. But [another page](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice) says it is not an arch style, just a pattern. 

I agree that is just a pattern. My understanding CQRS is normally applied within several microservices, and CQRS normally doesn't decide the architecture of a system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46426ef-bb0f-b085-a645-7e3e6c05752d
* Version Independent ID: 13b0c53a-cd01-9894-f34f-8d223c8e5b2b
* Content: [CQRS architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/cqrs)
* Content Source: [docs/guide/architecture-styles/cqrs.md](https://github.com/mspnp/architecture-center/blob/live/docs/guide/architecture-styles/cqrs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@stvngao Yes, Your understanding is correct. CQRS is an architectural pattern.

@MikeWasson any thoughts here?

**Comment by KetanChawda-MSFT** [comment]
@stvngao  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
