### ISSUE TITLE
Excellent Document

### ISSUE THREAD

**Issue by murugsl** [MicrosoftDocs/architecture-center#1532]
Nicely laid out and just enough details. Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8080bec2-ff05-badc-ffb7-194922d03ce2
* Version Independent ID: cb2aa366-a5b6-b0dc-0e2f-84376ba7b7f3
* Content: [Design reliable Azure applications](https://docs.microsoft.com/en-us/azure/architecture/reliability/#feedback)
* Content Source: [docs/reliability/index.md](https://github.com/mspnp/architecture-center/blob/live/docs/reliability/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@murugsl Thank you so much for the positive feedback! I will let @MikeWasson know that he knocked it out of the park with this documentation. 

We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
