### ISSUE TITLE
HDInsight left out in documentation

### ISSUE THREAD

**Issue by isamllr** [MicrosoftDocs/architecture-center#1534]
If Databricks is listed here, HDInsight should be represented as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bdc71b-0a54-4cc4-1b79-f60e274e9a51
* Version Independent ID: 1783570c-3545-71c8-72d3-d5657f77c070
* Content: [Choosing a machine learning technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning?toc=%2Fen-us%2Fazure%2Fmachine-learning%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json)
* Content Source: [docs/data-guide/technology-choices/data-science-and-machine-learning.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/data-science-and-machine-learning.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @isamllr Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
@isamllr HDInsights appears to have been mentioned in [this section](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning?toc=%2Fen-us%2Fazure%2Fmachine-learning%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json#microsoft-machine-learning-server) and part of the same recommendation; as such, we've made a minor update in that sentence to highlight that ML Services is an available option when spinning up HDInsight clusters in Azure.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
