### ISSUE TITLE
Data Gateway

### ISSUE THREAD

**Issue by mattonmicrosoft** [MicrosoftDocs/architecture-center#1537]
Why is there no mention of the on-premises data gateway in this architecture? My thinking is this is a key piece of the architecture and allows cloud-based systems to be integrated with on-premises systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287bb9a4-a404-f75b-9bf5-ebd445245938
* Version Independent ID: 31d58fc1-cc2a-5458-ab0b-82b42d7697b2
* Content: [Basic enterprise integration using Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/basic-enterprise-integration#feedback)
* Content Source: [docs/reference-architectures/enterprise-integration/basic-enterprise-integration.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/enterprise-integration/basic-enterprise-integration.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MattFarm
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @mattonmicrosoft Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
