### ISSUE TITLE
Update architecture to use VNet Peering

### ISSUE THREAD

**Issue by AErmie** [MicrosoftDocs/architecture-center#1542]
This document should be updated to remove the recommendation to use VPN Gateways between VNets, to rather use VNet Peering. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Multi-region N-tier application for high availability - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server#feedback)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/multi-region-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @AErmie  Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.
