### ISSUE TITLE
Why do we need to enable forward traffic on spoke vnet of peering

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [MicrosoftDocs/architecture-center#1544]
In the peering section, it is said Configure all VNet peering connections to allow forwarded traffic.
What is the purpose of enabling this in the spoke side? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @Charmendar Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
This is a great question! We do that so the peers can talk to each other by way of routing via the hub. Without it, the packets would drop as they attempted to exit the spoke destined for the hub and vice-versa. Let us know if that still doesn't explain it well and we can look at re-wording!

**Comment by alv1981** [comment]
Hi, and in which cases is this option usually disabled?
