### ISSUE TITLE
Azure Notebooks

### ISSUE THREAD

**Issue by revodavid** [MicrosoftDocs/architecture-center#1548]
Would be good to include a reference to Azure Notebooks on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bdc71b-0a54-4cc4-1b79-f60e274e9a51
* Version Independent ID: 1783570c-3545-71c8-72d3-d5657f77c070
* Content: [Choosing a machine learning technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning?toc=%2Fen-us%2Fazure%2Fmachine-learning%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json)
* Content Source: [docs/data-guide/technology-choices/data-science-and-machine-learning.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/data-science-and-machine-learning.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@revodavid Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by amitpatelupw** [comment]
Okay

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
