### ISSUE TITLE
Please consider to add Japanese document for this

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/architecture-center#1549]
Please

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e9383c21-9143-1559-c1a8-e6f6dc830159
* Version Independent ID: 37c6c659-a6bc-633e-2b3f-337deb01c215
* Content: [Integrate on-premises AD domains with Azure AD - Azure Reference Architectures](https://docs.microsoft.com/ja-jp/azure/architecture/reference-architectures/identity/azure-ad)
* Content Source: [docs/reference-architectures/identity/azure-ad.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/azure-ad.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@KeiroKamioka0000 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by KeiroKamioka0000** [comment]
Thanks! and Closed!
