### ISSUE TITLE
Names on the Marketplace category are swapped

### ISSUE THREAD

**Issue by bluPhy** [MicrosoftDocs/architecture-center#1550]
In the Marketplace category the marketplace names as swapped, it should be:
AWS service -&gt; AWS Marketplace 	
Azure service -&gt; Azure Marketplace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@bluPhy Thanks for catching that! We have worked up a PR to fix that which should reflect in a couple of hours.
