### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by manknewl** [MicrosoftDocs/architecture-center#1551]
Columns are in the wrong order. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#azure-and-aws-for-multicloud-solutions)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@manknewl Thank you for your feedback! We will review and update as appropriate.

**Comment by MikeWasson** [comment]
I fixed this - thanks!

**Comment by manknewl** [comment]
Thanks Mike. I’m actually at Microsoft in the ISV OCP team in Canada
Manuel
