### ISSUE TITLE
Minor change

### ISSUE THREAD

**Issue by MS-Stamp** [MicrosoftDocs/architecture-center#1552]
"These evolutions happen across three disciplines:" - the bullet points and diagram show four disciplines rather than three.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5801b908-175f-2d5a-39fa-cedaf040cfd4
* Version Independent ID: acba8c9f-9026-94c0-64f2-27a610f616c9
* Content: [Large enterprise governance journey - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/journeys/large-enterprise/?lc=2057#feedback)
* Content Source: [docs/cloud-adoption/governance/journeys/large-enterprise/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/governance/journeys/large-enterprise/index.md)
* Service: **architecture-center**
* Sub-service: **enterprise-cloud-adoption**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@MS-Stamp Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@MS-Stamp Thank you for pointing it out. I have created a PR to fix the doc as suggested. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
