### ISSUE TITLE
AzureUSGovernment Subscription

### ISSUE THREAD

**Issue by colinweiner** [MicrosoftDocs/architecture-center#1554]
Stepping through deploying the solution on US Gov and after I set az cli to AuzreUSGovernment and run the azbb command to Deploy the simulated on-premises datacenter, I get a:

_**Switched**_ active cloud to 'AzureCloud'

For some reason, the template is reverting back to AzureCloud and not allowing me to deploy in Azure Gov.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implement a hub-spoke network topology - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services#deploy-the-solution)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @colinweiner Thank you for your feedback! We will review and update as appropriate.

**Comment by colinweiner** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-nps-extension

Its the first diagram

**Comment by TravisCragg-MSFT** [comment]
@colinweiner AZBB is for [Azure Building Blocks](http://azurepost.com/azure-building-blocks/). Azure Buildling Blocks defaults to Public Cloud, but you can specify the --Cloud parameter to use "AzureUSGovernment", so just specify the --cloud parameter.

**Comment by mike-urnun-msft** [comment]
@colinweiner We will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
