### ISSUE TITLE
Update to include C# in databricks & like for like pricing

### ISSUE THREAD

**Issue by joshmowork** [MicrosoftDocs/architecture-center#1555]
Databricks now supports C# https://github.com/dotnet/spark

Also is it possible to include a like for like pricing comparison for the different tools, this is a commonly raised point when choosing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957618b3-8d25-49c4-950c-0c044d68f443
* Version Independent ID: 2ab67665-066b-fb14-9763-a12693b19bec
* Content: [Choosing a stream processing technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing#feedback)
* Content Source: [docs/data-guide/technology-choices/stream-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/stream-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@joshmowork Thanks for the feedback! We are assigning this issue to the content author for review.

**Comment by MikeWasson** [comment]
@joshmowork Thanks, I'll adding dotnet support to the table. Pricing comparison is a lot trickier, for example Stream Analytics is charged by SUs, whereas Databricks is charged by a combination of VM time + database units (DUs)
