### ISSUE TITLE
Kafka Misspelled

### ISSUE THREAD

**Issue by ScoGroMSFT** [MicrosoftDocs/architecture-center#1556]
Kafka is misspelled in the sentence "Then it sends a notification message using Kakfa-enabled Event Hubs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1970e0cd-53ae-02f6-479b-9ca386a5220e
* Version Independent ID: 8a81baa3-61c2-a8f6-540c-9a239583b8d6
* Content: [Claim-Check pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check#feedback)
* Content Source: [docs/patterns/claim-check.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/claim-check.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @yorek
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@ScoGroMSFT  Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
Hi @ScoGroMSFT Thanks reporting this to us and helping us drive improvements towards MS Docs. I've gone ahead and created a PR for this issue, and the change should reflect soon. 

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
