### ISSUE TITLE
Triggered Webjobs Deployment

### ISSUE THREAD

**Issue by dalejmarshall** [MicrosoftDocs/architecture-center#1557]
The doc states "If you want the job to respond to an event-driven trigger, you should configure it as Run continuously. The script or program is stored in the folder named site/wwwroot/app_data/jobs/continuous."

Is this correct? When I used the portal to create a Triggered type WebJob with a manual trigger it was placed in site/wwwroot/app_data/jobs/triggered

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a65e47-b024-0c7c-0ee9-21ff095abafd
* Version Independent ID: a764689a-168d-dcef-a297-c47f84ea2d12
* Content: [Background jobs guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#feedback)
* Content Source: [docs/best-practices/background-jobs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/background-jobs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@dalejmarshall Thanks for reaching out! We will investigate on this issue and get back to you soon.

**Comment by DixitArora-MSFT** [comment]
@dalejmarshall Folow this [doc ](https://docs.microsoft.com/en-us/azure/app-service/webjobs-create#webjob-types)for types of Webjobs. 

Following are the location for the triggered and continous web job mentioned in the [doc ](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#azure-web-apps-and-webjobs)as well .

For triggered execution: site/wwwroot/app_data/jobs/triggered/{job name}

For continuous execution: site/wwwroot/app_data/jobs/continuous/{job name}

**Comment by DixitArora-MSFT** [comment]
@dalejmarshall For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
