### ISSUE TITLE
Why use grafana

### ISSUE THREAD

**Issue by gilherau** [MicrosoftDocs/architecture-center#1558]
Can you elaborate on why we're recommending to use grafana to visualize the metrics? Azure Monitor has built-in visualizations capabilities using Power BI and the Kusto Query language. Is there something special about the DataBricks telemetry that makes it unreadable in KQL?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e17f2434-814c-4ebc-c05d-501566aa3c0f
* Version Independent ID: 6cf80861-2ab6-0c28-8a68-4f641491a61a
* Content: [Use dashboards to visualize Azure Databricks metrics](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/dashboards#feedback)
* Content Source: [docs/databricks-monitoring/dashboards.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/dashboards.md)
* Service: **architecture-center**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @gilherau Thank you for your feedback! We will review and update as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@gilherau I believe this doc accompanies the [library](https://github.com/mspnp/spark-monitoring) that enables sending log data from Azure Databricks to Azure Monitor.

I believe opening an [issue](https://github.com/mspnp/spark-monitoring/issues) on that repository would yield a more insightful discussion.

We are assigning this issue to the content author for further review.

**Comment by MikeWasson** [comment]
Using the spark-monitoring library, the data lands in Log Analytics, so you can consume it via the portal dashboards, Kusto queries, etc. We provided a Grafana dashboard as an example.
