### ISSUE TITLE
Please consider to add about naming conversations for Fire Wall

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/architecture-center#1559]
Please consider to add the naming conversation for Azure Firewall's Network rule and application rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#networking)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@KeiroKamioka0000 Thanks for the feedback! We will review and get back to you.

**Comment by KeiroKamioka0000** [comment]
![image](https://user-images.githubusercontent.com/37641695/58062917-19531500-7b31-11e9-9a54-fbba9ae6abb7.png)
As additional information, current portal does not mention about maximum number of fonts can be used.

**Comment by KetanChawda-MSFT** [comment]
@KeiroKamioka0000 Thank you for providing details. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by KeiroKamioka0000** [comment]
@MikeWasson 
Hi, how this goes?
Can you confirm up limit are 80 or 64 words?
thanks.

**Comment by doodlemania2** [comment]
We've confirmed with PG that the limitation on these is that it must be unique to your tenant, must begin with a letter or number, end with a letter number or underscore and may contain only letters, numbers, underscores, periods or hyphens. There is no length limit. Additionally, for fun, Unicode is now supported :)
