### ISSUE TITLE
What do you mean by real-time?

### ISSUE THREAD

**Issue by chwonghk01** [MicrosoftDocs/architecture-center#1560]
It looks like the recommendation result is precomputed in batch and couldn't handle new users and new items to be recommended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9353bd7c-c25d-5a4d-17cd-df6d8038d2a3
* Version Independent ID: 21434ad8-78fc-03e3-0bd1-03cc706627c7
* Content: [Build a Real-time Recommendation API on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/real-time-recommendation#feedback)
* Content Source: [docs/reference-architectures/ai/real-time-recommendation.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/real-time-recommendation.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@chwonghk01 Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by jreynolds01** [comment]
@chwonghk01 You are correct. In this context, we mean real-time in terms of the latency of retrieving the recommendations for a user when they interact with the application that surfaces the recommendation. In this example, the recommendations would be updated in a batch process that would be scheduled according to the business problem. For a real-time scoring or real-time inferencing process we are working on another example. Details are available in our other [repository](https://github.com/microsoft/recommenders/blob/master/notebooks/05_operationalize/lightgbm_criteo_o16n.ipynb) if you want to take a look before related content is published on docs.microsoft.com

**Comment by MikeWasson** [comment]
@chwonghk01 I'll close this issue for now. Please re-open if you have any further questions.
