### ISSUE TITLE
Reference architecture

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/architecture-center#1561]
Hi, It could be very useful to have a link to Azure Solutions, where is e.g. DR covered with https://azure.microsoft.com/en-us/solutions/architecture/disaster-recovery-enterprise-scale-dr/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8080bec2-ff05-badc-ffb7-194922d03ce2
* Version Independent ID: cb2aa366-a5b6-b0dc-0e2f-84376ba7b7f3
* Content: [Design reliable Azure applications](https://docs.microsoft.com/en-us/azure/architecture/reliability/)
* Content Source: [docs/reliability/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reliability/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@jjindrich Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@jjindrich Thanks. We're looking at adding more DR guidance. The Azure solutions content is a bit too high level IMO.
