### ISSUE TITLE
it doesn't need any lock mechanism when you load cache?

### ISSUE THREAD

**Issue by khaNuri** [MicrosoftDocs/architecture-center#1562]
as a sample  
  // Avoid caching a null value.
    if (value != null)
.... update cache with long process forexample from SQL Server, and suppose it cost 3 secs.

Where it will be lock? Redis is a distrubuted cache. Many clients ask cache resource just same time. Every client try to update cache?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f58625-4e97-1fc6-197b-8b25341f5a4f
* Version Independent ID: bdabf990-9a18-ec7f-a948-3fc79dc255e0
* Content: [Cache-Aside pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/cache-aside#feedback)
* Content Source: [docs/patterns/cache-aside.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cache-aside.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@khaNuri Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by RobsonKarls** [comment]
I think you would have a lock in there if before fetching from redis you would check in a in memory cache if there is any data, but, here redis is the cache, i believe all the instances should have access to it.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
