### ISSUE TITLE
IProductsDomain

### ISSUE THREAD

**Issue by manisto** [MicrosoftDocs/architecture-center#1564]
The IProductsDomain interface mentioned near the bottom of the page seems a bit detached from the rest of the page. Where is the interface supposed to be used? Who will be calling it, and where will it be implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [Command and Query Responsibility Segregation (CQRS) pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs#feedback)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@manisto Thanks for reaching out! We will investigate on this issue and get back to you soon.

**Comment by DixitArora-MSFT** [comment]
@manisto I have assigned this to content author to review and update as appropriate.

**Comment by MikeWasson** [comment]
@manisto Thanks for the feedback. Here's what I think is going on:  `ProductsCommandHandler`  should have an `IProductsDomain`, not an `IRepository<Product>` , which would be a generic repository and would not have methods like `RateProduct` as shown.
