### ISSUE TITLE
Mention Front Door as an alternative to Traffic Manager?

### ISSUE THREAD

**Issue by sugarjig** [MicrosoftDocs/architecture-center#1565]
With the recent release of Front Door, would it make sense to mention it as an alternative to Traffic Manager? It seems to have all the necessary features to support this architecture, including routing, failover, and health probes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@sugarjig Thanks for reaching out! We will investigate on this issue and get back to you soon.

**Comment by DixitArora-MSFT** [comment]
@sugarjig Could you let us know the documentation that you are referring . This will help us in tacking the changes.

**Comment by DixitArora-MSFT** [comment]
@sugarjig Just following up again in case missed the previous communication.

**Comment by DixitArora-MSFT** [comment]
@sugarjig Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by sugarjig** [comment]
@DixitArora-MSFT I was referring to the new Azure Front Door service, documented at https://docs.microsoft.com/en-us/azure/frontdoor/front-door-overview.

**Comment by taromielnaz** [comment]
Yes, this is my question as well. They are so similar to each other
