### ISSUE TITLE
Azure AD P1 or P2

### ISSUE THREAD

**Issue by stridsbr** [MicrosoftDocs/architecture-center#1566]
in the note under roles using Azure AD App Roles it states:
"As noted earlier, customers with Azure AD Premium can also assign security groups to roles."
Does it require P1 or P2? Does it mean P1 when P2 isen't specifically mentioned because both are premium?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#feedback)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@stridsbr Thanks for reaching out! We will investigate on this issue and get back to you soon.

**Comment by DixitArora-MSFT** [comment]
@stridsbr It can be P1 or P2. Because both are premium so the feature is available in both.

**Comment by stridsbr** [comment]
This is what it's displaying on the overview
![image](https://user-images.githubusercontent.com/2290125/58418119-2c149f00-8087-11e9-9300-bf851a6a8973.png)

And when I try to add securitygroups for a role I have this message:
![image](https://user-images.githubusercontent.com/2290125/58418178-5d8d6a80-8087-11e9-83bb-d893dcf53390.png)

Is there something that is blocking the usage of groups in the Azure Ad? Like a policy or something?

Do I as a user have to have a premium license connected to my account to be able to configure it? Isen't the licence for all in the organization? I'm trying to understand what is wrong for me. :-(

**Comment by DixitArora-MSFT** [comment]
@stridsbr I have assigned this to content author to review and update as appropriate.

**Comment by shashishailaj** [comment]
@stridsbr Could you please send us an email to azcommunity[at]microsoft[dot]com mentioning your tenant name and Azure subscription ID ? We have reached out to PG internally but they would need some information to proceed further. I checked the same with a tenant where I attached P1 license only and it was working . I was able to assign the groups. I am not sure what was wrong in your case but I did not get the same error as you. Please get in touch with us if you still face the error and we will take this offline and will surely find other ways to help you . 

Thank you.

**Comment by stridsbr** [comment]
Hi @shashishailaj ,

Thanks for youre help. I have asked someone in internal IT to looka at it and they can do this. So it's probably that my account isen't "trusted". They will look into it.
