### ISSUE TITLE
CloudTrail and Cloudwatch equivalents?

### ISSUE THREAD

**Issue by jurajlisiak** [MicrosoftDocs/architecture-center#1567]
Are these services going to be added?

**Comment by mike-urnun-msft** [comment]
Hello @jurajlisiak Thank you for your feedback. Could you provide us with the URL of the documentation that your feedback is applicable to?

**Comment by DixitArora-MSFT** [comment]
@jurajlisiak Just following up again in case missed the previous communication.

**Comment by jurajlisiak** [comment]
https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services

**Comment by DixitArora-MSFT** [comment]
@jurajlisiak [AzureMonitor](https://docs.microsoft.com/en-us/azure/azure-monitor/) \ [Log Analytics](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-faq) in Azure is pretty similar to Cloud trail/Cloud watch in AWS. For now will proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion.
