### ISSUE TITLE
Script Fails

### ISSUE THREAD

**Issue by MezeiJ** [MicrosoftDocs/architecture-center#1568]
When I attempt to run the below command  with the location etc set - any ideas appreciated
azbb -s &lt;subscription_id&gt; -g ra-onprem-sp2016-rg -l &lt;location&gt; -p onprem.json --deploy
I get this error
      "contentVersion": "1.0.0.0",
      "uri": "https://raw.githubusercontent.com/mspnp/template-building-blocks/v2.1.0/templates/buildingBlocks/virtualNetworks/virtualNetworks.json"
    },
    "timestamp": "2019-05-24T15:42:29.234931+00:00"
  },
  "resourceGroup": "********************",
  "type": null
}
Deployment failed. Correlation ID: b5d1703f-767e-476b-95c8-29e5709236fc. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"InvalidTemplateDeployment\\\",\\r\\n    \\\"message\\\": \\\"The template deployment failed because of policy violation. Please see details for more information.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"RequestDisallowedByPolicy\\\",\\r\\n        \\\"target\\\": \\\"vmek7a2habde37cdiag1\\\",\\r\\n        \\\"message\\\": \\\"Resource 'vmek7a2habde37cdiag1' was disallowed by policy. Policy identifiers: '[{\\\\\\\"policyAssignment\\\\\\\":{\\\\\\\"name\\\\\\\":\\\\\\\"Ensure https traffic for the existing storage accounts\\\\\\\",\\\\\\\"id\\\\\\\":\\\\\\\"/providers/Microsoft.Management/managementGroups/HPiAzureSecurityPolicy/providers/Microsoft.Authorization/policyAssignments/a8a37bd066974aa08e7971ee\\\\\\\"},\\\\\\\"policyDefinition\\\\\\\":{\\\\\\\"name\\\\\\\":\\\\\\\"Ensure https traffic for the existing storage accounts\\\\\\\",\\\\\\\"id\\\\\\\":\\\\\\\"/providers/Microsoft.Management/managementGroups/HPiAzureSecurityPolicy/providers/Microsoft.Authorization/policyDefinitions/edd42c27-a5cf-458c-9484-5acdcd83b948\\\\\\\"}}]'.\\\",\\r\\n        \\\"additionalInfo\\\": [\\r\\n          {\\r\\n            \\\"type\\\": \\\"PolicyViolation\\\",\\r\\n            \\\"info\\\": {\\r\\n              \\\"policyDefinitionDisplayName\\\": \\\"Ensure https traffic for the existing storage accounts\\\",\\r\\n              \\\"evaluationDetails\\\": {\\r\\n                \\\"evaluatedExpressions\\\": [\\r\\n                  {\\r\\n                    \\\"result\\\": \\\"True\\\",\\r\\n                    \\\"expression\\\": \\\"type\\\",\\r\\n                    \\\"path\\\": \\\"type\\\",\\r\\n                    \\\"expressionValue\\\": \\\"Microsoft.Storage/storageAccounts\\\",\\r\\n                    \\\"targetValue\\\": \\\"Microsoft.Storage/storageAccounts\\\",\\r\\n                    \\\"operator\\\": \\\"Equals\\\"\\r\\n                  },\\r\\n                  {\\r\\n                    \\\"result\\\": \\\"False\\\",\\r\\n                    \\\"expression\\\": \\\"Microsoft.Storage/storageAccounts/supportsHttpsTrafficOnly\\\",\\r\\n                    \\\"path\\\": \\\"properties.supportsHttpsTrafficOnly\\\",\\r\\n                    \\\"targetValue\\\": \\\"true\\\",\\r\\n                    \\\"operator\\\": \\\"Equals\\\"\\r\\n                  }\\r\\n                ]\\r\\n              },\\r\\n              \\\"policyDefinitionId\\\": \\\"/providers/Microsoft.Management/managementGroups/HPiAzureSecurityPolicy/providers/Microsoft.Authorization/policyDefinitions/edd42c27-a5cf-458c-9484-5acdcd83b948\\\",\\r\\n              \\\"policyDefinitionName\\\": \\\"edd42c27-a5cf-458c-9484-5acdcd83b948\\\",\\r\\n              \\\"policyDefinitionEffect\\\": \\\"deny\\\",\\r\\n              \\\"policyAssignmentId\\\": \\\"/providers/Microsoft.Management/managementGroups/HPiAzureSecurityPolicy/providers/Microsoft.Authorization/policyAssignments/a8a37bd066974aa08e7971ee\\\",\\r\\n              \\\"policyAssignmentName\\\": \\\"a8a37bd066974aa08e7971ee\\\",\\r\\n              \\\"policyAssignmentDisplayName\\\": \\\"Ensure https traffic for the existing storage accounts\\\",\\r\\n              \\\"policyAssignmentScope\\\": \\\"/providers/Microsoft.Management/managementGroups/HPiAzureSecurityPolicy\\\",\\r\\n              \\\"policyAssignmentParameters\\\": {}\\r\\n            }\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d93eb87-54cb-cf38-dfae-0ebe7579d608
* Version Independent ID: c7ac665e-d194-ab07-c1bb-5d5a3049c5ec
* Content: [Run a highly available SharePoint Server 2016 farm in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/#feedback)
* Content Source: [docs/reference-architectures/sharepoint/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sharepoint/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @MezeiJ Thank you for your feedback! We will review and update as appropriate.

**Comment by MikeWasson** [comment]
Looks like it's failing because your organization has an Azure Policy in place that forces HTTPS for storage accounts.  Here is a fix:

1. Create a directory somewhere on the machine that has AZBB installed.
1. Create a file named 'virtualMachineSettings.json'
1. Put the following JSON in it

    ```json	
    {
        "diagnosticStorageAccounts": {
        "supportsHttpsTrafficOnly": true
         }
    }
    ```
1. Save the file
1. Add the following parameter to the azbb command: "-d <path_to_directory_from_step_1>"

**Comment by MikeWasson** [comment]
@MezeiJ Closing this issue now. Please re-open if you are still getting an error.
