### ISSUE TITLE
Availability of latest ebook version of Cloud_Application_Architecture_Guide

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1569]
The ebook from the link below is created 2017,
https://azure.microsoft.com/en-gb/campaigns/cloud-application-architecture-guide/

However, the web version from the link below is more recent and has updated content. 
https://docs.microsoft.com/en-us/azure/architecture/guide/

Is the latest ebook version of it available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@PingPongSet Thank you for your question. The links provided in the e-book, references to the Microsoft public documents which are updating time to time. The latest version of the e-book is not available yet. Looping in @MikeWasson to confirm.

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson Checking it , in case you missed last post. Can you please confirm on this.

**Comment by MikeWasson** [comment]
Yes, that's correct. Right now we have no plans to update the eBook.
