### ISSUE TITLE
Better to remove "term=infrastructure" parameter in the url link of Developers

### ISSUE THREAD

**Issue by 4416km** [MicrosoftDocs/architecture-center#1570]
https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/ready/technical-skills

There are some links to "Microsoft Learn" for various roles, Business users, Solution architects, etc.
I think it is better to remove "term=infrastructure" parameter for "Developers" link because it doesn't work in other languages.
For example, Japanese page is the following and the result of clicking "開発者" (means Developers) just shows empty result in Microsoft Learn. 
https://docs.microsoft.com/ja-jp/azure/architecture/cloud-adoption/ready/technical-skills

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d03bbb68-645d-6345-52d1-b4172acca29f
* Version Independent ID: b185e46f-694c-191c-ff8b-4570179173db
* Content: [Build technical skills - Microsoft Cloud Adoption Framework in Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/ready/technical-skills)
* Content Source: [docs/cloud-adoption/ready/technical-skills.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/ready/technical-skills.md)
* Service: **architecture-center**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@4416km Thanks for reaching out! We will investigate on this issue and get back to you soon.

**Comment by DixitArora-MSFT** [comment]
@4416km  I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by BrianBlanchard** [comment]
Thanks for the feedback. This appears to be a delay in translation of the learn modules. I'll confirm & update this issue accordingly.

The en-us version of the link shows the four modules we would expect to see related to this topic. https://docs.microsoft.com/en-us/learn/browse/?roles=developer&term=infrastructure 

Regardless of the translation, our next release will now add a second link for developers interested in learn modules that are broader than the topic of infrastructure readiness.

**Comment by MikeWasson** [comment]
Closing this issue based on the discussion - The changed mentioned above is now live.
