### ISSUE TITLE
Kappa diagram has wrong labels?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/architecture-center#1571]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/architecture-center.de-de/issues/5
The user's comment is about a diagram which is the same for both en-us and localized versions.

@tconrady commented 10 hours ago
The Kappa diagram shows the 'Speed layer' contains the 'Master data' and the 'Long-term store' contains the 'Real-time views'. Shouldn't it be the other way around?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953d7d0d-651f-a566-1d28-6946c824e1ae
* Version Independent ID: 8f5b4264-dcc9-ad28-36fe-45463d15f52a
* Content: [Big data architectures](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/#feedback)
* Content Source: [docs/data-guide/big-data/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/big-data/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@CeciAc Thanks for reaching out! We will investigate on this issue and get back to you soon.

**Comment by DixitArora-MSFT** [comment]
@CeciAc I have assigned this to content author to review and update as appropriate.

**Comment by MikeWasson** [comment]
Thanks - yes, the labels are switched. I will open a PR to fix this.
