### ISSUE TITLE
Service Fabric and AKS fork on decision tree decceptive

### ISSUE THREAD

**Issue by TangentDave** [MicrosoftDocs/architecture-center#1572]
By phrasing the last question as "Need .Net integration or Fully Support Microsoft Stack" with the Yes going to Service Fabric and the No going to AKS, does a major misrepresentation of .Net Core and AKS as a support managed service of Azure. The question implies the .Net Core and/or AKS are not Fully Supported. This question needs to be cleaned up significantly.

**Comment by DixitArora-MSFT** [comment]
Hello @TangentDave  Thank you for your feedback. Could you provide us with the URL of the documentation that your feedback is applicable to?

**Comment by DixitArora-MSFT** [comment]
@TangentDave Just following up again in case missed the previous communication.

**Comment by DixitArora-MSFT** [comment]
@TangentDave Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
