### ISSUE TITLE
Article needs to be updated - information is not up to date

### ISSUE THREAD

**Issue by OptionHenrik** [MicrosoftDocs/architecture-center#1573]
Please update article to accomodate Azure AD Domain Services. The section: "Integrate your on-premises domains with Azure AD" states challenges: "Identity services are limited to users and groups. There is no ability to authenticate service and computer accounts." ... this is no longer true as Azure AD Domain Services can authenticate services and computer accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6463b2-ccca-e0f5-ed8e-ed239541a5c7
* Version Independent ID: 3f497c55-e522-476c-8e63-37de63ff0603
* Content: [Integrate on-premises Active Directory with Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/#feedback)
* Content Source: [docs/reference-architectures/identity/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@OptionHenrik Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by KetanChawda-MSFT** [comment]
@OptionHenrik I have assigned the issue to the content author to evaluate and update as appropriate.
