### ISSUE TITLE
Correction on Peering Types and IP type addresses required for Private Peering

### ISSUE THREAD

**Issue by sbdoroff** [MicrosoftDocs/architecture-center#1575]
Hello,

I am requesting a quick correction on this documentation.

Under step 4 here (https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute#expressroute-circuit) it states:

Reserve two /30 subnets composed of valid public IP addresses for each type of peering you want to implement. These /30 subnets will be used to provide IP addresses for the routers used for the circuit. If you are implementing private, public, and Microsoft peering, you'll need 6 /30 subnets with valid public IP addresses.

Correction Request:
Private peering can use public OR private address per this tutorial (https://channel9.msdn.com/Blogs/Azure/Azure-ExpressRoute-How-to-set-up-Azure-private-peering-for-your-ExpressRoute-circuit) @ 2:38.  Could this be added to this document?

Public Peering is also deprecated and can no longer be created on new circuits.  Could this note be added here or public peering be removed as an option? (https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-routing-portal-resource-manager#public)

Best,

Steve Doroff
Support Escalation Engineer
Azure Networking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Connect an on-premises network to Azure using ExpressRoute - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute#expressroute-circuit)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @sbdoroff Thank you for your feedback! We will review and update as appropriate.
