### ISSUE TITLE
The heading "What is the virtual datacenter" is followed by "What is a virtual datacenter?".

### ISSUE THREAD

**Issue by MAGROULX** [MicrosoftDocs/architecture-center#1583]
Are these headings / paragraphs duplicates?

https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter#what-is-the-virtual-datacenter

https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter#what-is-a-virtual-datacenter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d8a578-f9f1-53af-64d0-808f1fde6c9c
* Version Independent ID: 8a647cb7-2d10-53ed-5459-4356ef607e77
* Content: [Azure virtual datacenter: A network perspective](https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter#references)
* Content Source: [docs/vdc/networking-virtual-datacenter.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/vdc/networking-virtual-datacenter.md)
* Service: **architecture-center**
* Sub-service: **enterprise-cloud-adoption**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by mike-urnun-msft** [comment]
Hi @MAGROULX Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
Corrected in recent update. Thank you for this!
