### ISSUE TITLE
scalability capabilities table is not accurate

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftDocs/architecture-center#1584]
Azure SQL database does support dynamic scalability and query scale out

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560fb3dc-3a89-aa28-f4c1-564f7920f5ca
* Version Independent ID: b5255403-369f-9324-fb16-02526b24dba6
* Content: [Online analytical processing (OLAP)](https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-analytical-processing#feedback)
* Content Source: [docs/data-guide/relational-data/online-analytical-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/relational-data/online-analytical-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @MTawfik86 Thank you for your feedback! We will review and update as appropriate.
