### ISSUE TITLE
Subscription groups?

### ISSUE THREAD

**Issue by jlorich** [MicrosoftDocs/architecture-center#1589]
The first image in this document still references subscription groups months after the first issue was raised. This should be management groups as subscription groups are not a concept and this is confusing to customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc23836-c10c-5c47-818b-42c53916b269
* Version Independent ID: b5ef4736-1df9-e3d9-eafb-7782cc0d5fea
* Content: [Best practices for enterprises moving to Azure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/appendix/azure-scaffold#feedback)
* Content Source: [docs/cloud-adoption/appendix/azure-scaffold.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/appendix/azure-scaffold.md)
* Service: **architecture-center**
* Sub-service: **enterprise-cloud-adoption**
* GitHub Login: @rdendtler
* Microsoft Alias: **rodend**

**Comment by mike-urnun-msft** [comment]
Hi @jlorich Thank you for your feedback! We will review and update as appropriate.

**Comment by rdendtler** [comment]
New Art was recently created. Will work to get a PR issued and the graphic updated.  Thank you for the feedback

**Comment by jlorich** [comment]
Awesome! I can't wait to see it.  Thanks!

**Comment by MikeWasson** [comment]
Looks like the PR went live - https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/appendix/azure-scaffold#need-for-governance
