### ISSUE TITLE
No mention of Event Grid

### ISSUE THREAD

**Issue by mikewiese** [MicrosoftDocs/architecture-center#1591]
Azure Event Grid has been around for a while. It would be nice if you could put up a comparison against the AWS equivalent if one exists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@mikewiese Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
@mikewiese Thanks - the closest comparison seems to be SNS, although the two services aren't identical. I'm adding an update to the doc.
