### ISSUE TITLE
Well thought introduction & comment on Domain model - knowledge graph approach similarity

### ISSUE THREAD

**Issue by heimohanninen** [MicrosoftDocs/architecture-center#1592]
Thanks for easy to read introduction. The process resambles knowledge graph design approach. In the knowledge graph approach, you focus is on business semantics "what is needed, what things means" - rather than what data data we have and where it is stored. That makes me think, that micro services approach would benefit from semantic data modeling and vice versa. As you design knowledge graph, you have to check with micro services tema that you can deliver aggregated in desired scope and structure   (method &lt;--&gt; SPARQL queries etc.) . Micro services would benefit from knowlegde graph approach, by letting graph query to integrate  scattered data (or some may say data via metadata). Your service would become decoupled completely from data structures, i.e. letting you easily change, extend the returned data set - simply by modifying your graph query, and not touching the micro services code at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e55d3a73-7618-45ba-b281-bb70dd258842
* Version Independent ID: 7f5cd352-0998-a214-8dfc-c19898cecd21
* Content: [Domain analysis for microservices](https://docs.microsoft.com/en-us/azure/architecture/microservices/model/domain-analysis#feedback)
* Content Source: [docs/microservices/model/domain-analysis.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/model/domain-analysis.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @heimohanninen,

Thanks for the kudos and sharing your feedback and thoughts on this matter. Surely, it'll benefit others visiting thread. 

We will now proceed to close this thread for now since this channel is more for fixing issues in the scope of the documentation and driving improvements towards it. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
