### ISSUE TITLE
Spoke connectivity is allowed using a VPN Gateway

### ISSUE THREAD

**Issue by carteixeira** [MicrosoftDocs/architecture-center#1593]
Considerations - Spoke connectivity options only mention the use of Azure Firewall or NVA, but you can also accomplish this using Virtual Network Gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?toc=%2fazure%2fvirtual-network%2ftoc.json#considerations)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@carteixeira Thanks for the feedback! To confirm, do you suggest using Virtual Network Gateway to connect the spoke VNETs directly instead of having traffic go through the hub?

If so, I believe the doc aims to convey how connectivity could be achieved between spokes keeping the hub-spoke topology intact.

**Comment by MikeWasson** [comment]
Yes - the idea is to ensure that all traffic flows through the hub

**Comment by carteixeira** [comment]
Yes, I am referring to Spoke talking to Spoke via Hub Gateway (Spoke1 >> Hub Gateway >> Spoke2), using UDR in both Spokes pointing traffic to the Virtual Network Gateway. I was able to validate this.
Just wanted to add VPN Gateway as one of the options to accomplish this.

**Comment by PramodValavala-MSFT** [comment]
@carteixeira Are you referring to have a multi-site VPN Gateway in the hub network connected to the spoke networks? In that case, this would require having VPN Gateways running in them as well I believe. And in azure this would be over kill considering VNET peering is much simpler (and cheaper).

But this is something that might help when trying to achieve a hub-spoke topology for a poly-cloud (with/without on-premise networks) implementation.

We are assigning this issue to the content author for further review.

**Comment by carteixeira** [comment]
No, I'm talking about using 1 VPN Gateway to route traffic between the spokes, just like when you have an NVA. See picture below:

![image](https://user-images.githubusercontent.com/20302679/59630152-44b62900-910a-11e9-847c-3afa4d4543cd.png)

**Comment by PramodValavala-MSFT** [comment]
@carteixeira I've checked with my team internally and while using VPN gateway is possible there are some things to consider

- NVAs have extra security capabilities by defining policies and rules when compared to VPN gateways
- Using VPN results in latency and constrained throughput while NVA's can offer high throughput and performance instead

**Comment by carteixeira** [comment]
I understand the implications, NVA is going to be a better choice but with higher cost, I'm just saying that if this option is available, if should be mentioned in the documentation, especially for customers that do not need or have the ability to manage/maintain/pay for an NVA.
VPN GW is a lower cost / less maintenance option.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!

**Comment by jackchenquest** [comment]
VPN GW is easier to setup and I had suggested the same solution in https://github.com/MicrosoftDocs/architecture-center/issues/765.
