### ISSUE TITLE
Discrepancy in text vs diagram for Azure Cosmos and SQL

### ISSUE THREAD

**Issue by vmathur2004** [MicrosoftDocs/architecture-center#1594]
The diagram indicates (or it appears to indicate) that data replication for Azure Cosmos DB needs to be configured as a user responsibility. Where as the text indicates that in case of a regional outage on the primary region triggering the fail over for Azure Cosmos will enable the geo-replicated instance in write mode on the secondary region. I feel the diagram needs to be updated to reflect the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region#feedback)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @vmathur2004 Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
Thanks for the feedback. The diagram just shows the data replication path, not user responsibility. Would it be more clear if the label was "geo-replication"?

**Comment by vmathur2004** [comment]
Geo-replication would be better - thanks

**Comment by MikeWasson** [comment]
Thanks - I have submitted an update.
