### ISSUE TITLE
Azure Front Door Service

### ISSUE THREAD

**Issue by JannieSA** [MicrosoftDocs/architecture-center#1595]
Compared to AWS CloudFront, is Azure Front Door not also an Azure Service alongside Azure Content Delivery Network?

Great website thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @JannieSA Thank you for your feedback! We will review and update as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@JannieSA You are right! Thanks for catching that! We have raised a PR to include this.

**Comment by PramodValavala-MSFT** [comment]
@JannieSA On further discussion, CDN functionality is just one feature that Azure Front Door provides. It is probably has more features similar to AWS Global Accelerator.

We are assigning this issue to the content author for further review.

**Comment by doodlemania2** [comment]
Merged in today. Thank you! #please-close

**Comment by JannieSA** [comment]
Please validate? I am not sure if Azure Front Door Service compares to AWS SiteWise (IoT SiteWise)

**Comment by doodlemania2** [comment]
agh - thank you @JannieSA this is fixed in https://github.com/MicrosoftDocs/architecture-center-pr/pull/218/

**Comment by doodlemania2** [comment]
Merged - thanks again!
