### ISSUE TITLE
This documentation should be moved to https://docs.microsoft.com/en-us/azure/azure-databricks/ 

### ISSUE THREAD

**Issue by isamllr** [MicrosoftDocs/architecture-center#1596]
This documentation should be moved to https://docs.microsoft.com/en-us/azure/azure-databricks/ - it's product specific and should not be part of general guidance / Data architectures

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3db4a7e-3958-b1dc-c1db-9761cf15f9cf
* Version Independent ID: 4d673510-6eae-464b-9d19-3d81e8160f5f
* Content: [Monitoring Azure Databricks with Azure Monitor](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/)
* Content Source: [docs/databricks-monitoring/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@isamllr Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by MikeWasson** [comment]
Thanks for the feedback - I'll look into adding this to the Databricks product docs TOC

**Comment by dcbrown16** [comment]
@MikeWasson - I still don't see these docs on the Databricks side, am I missing something?
The only logging approach I found was the diagnostic settings info, buried under Administration. It would be nice to have a higher hierarchy level for Monitoring covering both of these concepts.
https://docs.microsoft.com/en-us/azure/databricks/administration-guide/account-settings/azure-diagnostic-logs
