### ISSUE TITLE
Azure AWS Account Compare has wrong label

### ISSUE THREAD

**Issue by roberto-mardeni** [MicrosoftDocs/architecture-center#1597]
The image at docs/aws-professional/images/azure-aws-account-compare.png shows "Account" around "Subscription" perhaps it should say "Account/Enrollment" to avoid confusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d100d43f-d48a-3d97-1aea-7a5409fdccc8
* Version Independent ID: 568dcd88-b93c-1d41-44d0-8643dd057a33
* Content: [Azure for Amazon Web Services (AWS) Professionals - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/)
* Content Source: [docs/aws-professional/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@roberto-mardeni Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by MikeWasson** [comment]
@roberto-mardeni Do you have a reference for "enrollment"? I can't find anything in the AWS documentation that uses that term. Their tutorials and [glossary](https://docs.aws.amazon.com/general/latest/gr/glos-chap.html#A) all use "account" as far as I can tell.

**Comment by roberto-mardeni** [comment]
@MikeWasson I mean it in the other direction, an AWS Account can be referred to as an "Account/Enrollment" on the Azure side. Recently I had an interaction with an Enterprise customer that used this page as reference and when we mentioned Enrollment he was confused, which is the case when Enterprise Agreements are in place.

**Comment by MikeWasson** [comment]
Ah, got it! thanks

**Comment by MikeWasson** [comment]
@roberto-mardeni We are planning some documentation in Cloud Adoption Framework (CAF) that discusses subscriptions and accounts in more detail. We plan to revisit this AWS article once the CAF doc ships.

**Comment by doodlemania2** [comment]
Okay to close for now pending the CAF shipment.

**Comment by eyusubov** [comment]
@mikewasson is CAF documentation ready? any references please?

**Comment by doodlemania2** [comment]
@eyusubov we have https://docs.microsoft.com/en-us/azure/architecture/aws-professional/ and https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ available for you.
