### ISSUE TITLE
Tags are not exactly "alphanumeric" limited

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/architecture-center#1598]
It may be difficult to confirm without involving localization, but can we change at least the tag naming restrictions from "alphanumeric" to "Unicode" or something else more appropriate? I have tested that Japanese characters, even fairly unusual ones that we previously saw didn't count as "words" for the RG naming conventions, work fine in tags.
I'm pretty sure that it's just the (single-byte) versions of the specifically listed characters that are prohibited, and any other Unicode symbol I tried worked fine (♡🐶漢字かなカナ).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@dcbrown16 Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@dcbrown16 The following limitations apply to tags:

- Not all resource types support tags. To determine if you can apply a tag to a resource type, see [Tag support for Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/tag-support).
- Each resource or resource group can have a maximum of 15 tag name/value pairs. This limitation applies only to tags directly applied to the resource group or resource. A resource group can contain many resources that each have 15 tag name/value pairs. If you have more than 15 values that you need to associate with a resource, use a JSON string for the tag value. The JSON string can contain many values that are applied to a single tag name. This article shows an example of assigning a JSON string to the tag.
- The tag name is limited to 512 characters, and the tag value is limited to 256 characters. For storage accounts, the tag name is limited to 128 characters, and the tag value is limited to 256 characters.
Virtual Machines and Virtual Machine Scale Sets are limited to a total of 2048 characters for all tag names and values.
- Tags applied to the resource group are not inherited by the resources in that resource group.
- Tags can't be applied to classic resources such as Cloud Services.
- Tag names can't contain these characters: `<`, `>`,` %`,` &`,` \`,` ?`,` /`

**Comment by MikeWasson** [comment]
@KetanChawda-MSFT Thanks - is there an existing doc that describes these rules?

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson Yes, [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags) is the doc.

**Comment by dcbrown16** [comment]
@KetanChawda-MSFT yes I read that link, but my request still stands.
The link you provided doesn't say anything about a requirement that tags use strictly ALPHAnumeric characters, emphasis on alpha as in Roman letters vs Japanese, Chinese, or any of many other character sets. I'm asking that the page be revised to remove the wording "alphanumeric" and use a more precise descriptor that considers other languages and character sets.

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson Any thoughts here?
