### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by cmeeren** [MicrosoftDocs/architecture-center#1599]
The following sentences look like they have been "partially refactored, so to speak.

&gt; With each microservice responsible for its own data persistence. As a result, data consistency can be a challenge.

Perhaps it was meant to be this?

&gt; Each microservice is responsible for its own data persistence. As a result, data consistency can be a challenge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7e7bd-23f3-a39f-9015-b77f14bb43e5
* Version Independent ID: 0ac34e7e-315f-2452-bf0a-74e9b1068c38
* Content: [Microservices architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices#feedback)
* Content Source: [docs/guide/architecture-styles/microservices.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/microservices.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@cmeeren Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
Thanks for pointing this out. I have submitted a fix.
