### ISSUE TITLE
Document another issue of using "groupMembershipClaims": "SecurityGroup"

### ISSUE THREAD

**Issue by RobertoPrevato** [MicrosoftDocs/architecture-center#1600]
Hi,
Please document another drawback of using "groupMembershipClaims": "SecurityGroup":
* as users belong to more groups, access tokens grow in size more and more
* a practical example of why this can be a problem, is when using Cookie sign in scheme + OpenID Connect challenge scheme in ASP.NET Core applications:
- * the cookie grows more and more in size
- * users that belong to many groups in AAD, and use iOS devices (such as iPhones) lose access to the web application (blocking issue), because iOS will keep only the first 8K characters of HTTP request headers overall, and truncate the access token in the cookie

The solution in such scenario is to register an handler for `Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationEvents.OnSigningIn`, to discard all group claims that are not relevant for the application. This is ugly; application roles are a much better solution in this regard because as documented, they are returned exactly for the application for which access tokens are issued.

**Note:** I first saw this problem in 2017, and had to resolve it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#feedback)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @RobertoPrevato 
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by MikeWasson** [comment]
@RobertoPrevato Thanks for the feedback. According to [this doc](https://docs.microsoft.com/azure/active-directory/develop/access-tokens), Azure AD handles this case by including an "overage" claim after a certain limit. (I haven't personally tried this.)

**Comment by RobertoPrevato** [comment]
Hi @MikeWasson, thanks for the heads up. I wasn't aware of the "overage" claim, however the problem I described above with iOS devices, happens way before the documented limit of _(150 for SAML, 200 for JWT)_.

The problem I experienced back in 2017, was described for example here:
* [Issue 830 reported in ASP.NET](https://github.com/aspnet/Security/issues/830)
* [This blog post, under "Safari issue"](https://hajekj.net/2017/03/20/cookie-size-and-cookie-authentication-in-asp-net-core/)

I recently found Application Roles to be a better solution to control authorization of web applications, since they are returned exactly in claims, and can be used anyway together with AD Groups; and recommended to document this.

**Comment by MikeWasson** [comment]
@RobertoPrevato Thanks - I didn't forget this thread, I just haven't had time to revisit it. :smile_cat: I'm adding this consideration to the doc now.
