### ISSUE TITLE
data store for blobs or XML documents 

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1603]
Below is quoted from the article. 

Can you elaborate on this? Does it mean relational database cannot be used for blobs or XML documents ? or just BIG blobs or XML documents? 
What datastore can be used for small/large blobs or XML documents ?

"A mismatch between the choice of data store and the type of data, such as large blobs or XML documents in a relational database."

https://docs.microsoft.com/en-gb/azure/architecture/antipatterns/monolithic-persistence/

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9f59e5a-6a72-7483-4ca7-8bbb9b6b5e93
* Version Independent ID: d3f26f02-f1bc-cb65-f1b8-eeef1c3842f4
* Content: [Monolithic Persistence antipattern - Performance antipatterns for cloud apps](https://docs.microsoft.com/en-gb/azure/architecture/antipatterns/monolithic-persistence/)
* Content Source: [docs/antipatterns/monolithic-persistence/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/antipatterns/monolithic-persistence/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Most relational databases can store things like blobs and XML documents, and that may be fine for some workloads. But if you are storing a lot of very large blobs in an RDBMS it may create a bottleneck and then it's better to store these in a different data store, and then just keep a pointer to the blob in the relational data. As for which data store, you might use blob storage or a document database such as Cosmos DB (for JSON files).

**Comment by MikeWasson** [comment]
@PingPongSet I'll go ahead and close this issue unless you have further questions. Thanks!
