### ISSUE TITLE
Serverless vs Container

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1606]
Please can you elaborate on why it is below?  
"
It can be challenging to build a complex application using a serverless architecture.
"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93139ee2-ff91-ee5e-a056-8d6b597a81f3
* Version Independent ID: 8b4436e0-094c-9602-2ead-43bb3b2f98f1
* Content: [Choosing an Azure compute option for microservices](https://docs.microsoft.com/en-gb/azure/architecture/microservices/design/compute-options#next-steps)
* Content Source: [docs/microservices/design/compute-options.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/design/compute-options.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@PingPongSet Thank you for your feedback! We will review and provide an update as appropriate.
