### ISSUE TITLE
Serverless Microservices and Service meshes

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1607]
Does a microservices using serverless need a Service meshes?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f259ccea-882e-9496-27cf-af8d13edaae4
* Version Independent ID: a7bab5c8-7227-e836-a721-0c54f94a2d8c
* Content: [Interservice communication in microservices](https://docs.microsoft.com/en-gb/azure/architecture/microservices/design/interservice-communication#next-steps)
* Content Source: [docs/microservices/design/interservice-communication.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/design/interservice-communication.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Service mess is more of a container orchestrator concept. This article doesn't really address serverless architectures -- we're hoping to provide more guidance on serverless microservices architectures in the future. In the meantime, I'll try to clarify this point in the article. Thanks!
