### ISSUE TITLE
API communication vs in process communication 

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1608]
Why do Scheduler Service and Drone Service communicate via API? 

Are they located at different microservices? 
https://docs.microsoft.com/en-gb/azure/architecture/microservices/design/api-design#mapping-rest-to-ddd-patterns

I thought both belong to Shipping bounded context (Shipping microservice).

https://docs.microsoft.com/en-gb/azure/architecture/microservices/model/domain-analysis#define-bounded-contexts

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac798d-5822-eaa5-6e51-3a8573022d69
* Version Independent ID: 80f47a71-b119-0c0a-7c21-e7d3d16358ec
* Content: [API design](https://docs.microsoft.com/en-gb/azure/architecture/microservices/design/api-design#mapping-rest-to-ddd-patterns)
* Content Source: [docs/microservices/design/api-design.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/design/api-design.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@PingPongSet Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
In this case Scheduler service and Drone service are separate microservices. This is related to your other question in #1611. Let me know if you have any other questions about this.
