### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/architecture-center#1609]
What is meant by this sentence? I believe it contains a typo:

Validate that on-premises security and traffic management mechanisms are treat connected cloud networks as untrusted. 

Please address.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5801b908-175f-2d5a-39fa-cedaf040cfd4
* Version Independent ID: acba8c9f-9026-94c0-64f2-27a610f616c9
* Content: [Large enterprise governance journey - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/journeys/large-enterprise/index)
* Content Source: [docs/cloud-adoption/governance/journeys/large-enterprise/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/governance/journeys/large-enterprise/index.md)
* Service: **architecture-center**
* Sub-service: **enterprise-cloud-adoption**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@SeaDude Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
Thank you for the typo find! Merged into internal CAF backlog.
