### ISSUE TITLE
Multiple data store with Delivery history

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1610]
How does it work when both Cosmos DB and Azure Data Lake Store are used for query and data insertion?

For example, how to tell which store for query, and which store for data insertion?

Is there other challenges raised?

"Therefore, the Delivery History service also stores a subset of the historical data in Cosmos DB for quicker lookup."

https://docs.microsoft.com/en-gb/azure/architecture/microservices/design/data-considerations#example-choosing-data-stores-for-the-drone-delivery-application

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb25545c-958f-99b0-b321-74e556ad4557
* Version Independent ID: ebe36da6-a15f-f981-787d-8aa4307451a2
* Content: [Data considerations for microservices](https://docs.microsoft.com/en-gb/azure/architecture/microservices/design/data-considerations#example-choosing-data-stores-for-the-drone-delivery-application)
* Content Source: [docs/microservices/design/data-considerations.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/design/data-considerations.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@PingPongSet Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@PingPongSet this is logic that would need to be built into the service.
