### ISSUE TITLE
Bounded Context, Microservice, Domain Services

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1611]
I am confused. Is each of these a separate microservice: Delivery, Package, Supervisor, Scheduler? based on below

"Delivery and Package are obvious candidates for microservices. The Scheduler and Supervisor coordinate the activities performed by other microservices, so it makes sense to implement these domain services as microservices."

Furthermore, is each of these rectangles on the diagram below a separate microservice?
https://docs.microsoft.com/en-gb/azure/architecture/microservices/images/drone-delivery.png

Why is the Shipping bounded context on the diagram below not a microservice?
https://docs.microsoft.com/en-gb/azure/architecture/microservices/images/bounded-contexts.png

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0c8e3-8abb-aa09-c746-ae94113f3c14
* Version Independent ID: 5b56b900-3c15-4392-dd73-85e496954dc7
* Content: [Identifying microservice boundaries](https://docs.microsoft.com/en-gb/azure/architecture/microservices/model/microservice-boundaries)
* Content Source: [docs/microservices/model/microservice-boundaries.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/model/microservice-boundaries.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Hi @PingPongSet, I think [this section](https://docs.microsoft.com/en-gb/azure/architecture/microservices/model/microservice-boundaries#from-domain-model-to-microservices) of the article answers your question. Our guideline is to start with a bounded context and then consider whether you need to further divide into smaller services. Let me know if you have further questions.
