### ISSUE TITLE
Two trivial edits

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/architecture-center#1615]
Greetings,

"Edit 1" : 
Section "Web-Queue-Worker", second paragraph, sentence four:
"But with a complex domains, [...]"
&gt;&gt; should be either "with complex domains" or "with a complex domain"

"Edit 2" :
Section "Big Data, Big Compute", sentence two:
"[...] performing paralleling processing across the entire set [...]"
&gt;&gt; should be "parallel processing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f10a0039-c955-2af1-6b11-ff611a171740
* Version Independent ID: 12c1ecc1-7db6-2d4b-52f3-d4e99c4c5d44
* Content: [Architecture styles - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/#feedback)
* Content Source: [docs/guide/architecture-styles/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @a-zaf Thanks for pointing these out and sharing your feedback! We'll review and update as appropriate.

**Comment by doodlemania2** [comment]
Thank you @a-zaf - we've got these staged! In the future, if you like, you are more than welcome to open a PR directly on docs when you find errors and we can get them patched up quick! :)
