### ISSUE TITLE
How does this differ from a codebehind or C in MVCS?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/architecture-center#1623]
MVCS = Model View Controller Service, where the Service resides between the model and the controller to provide both a scaling point and orchestrator.
 .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064550fc-3915-2d6f-5ed1-9ee8f022a418
* Version Independent ID: ae425b05-6281-325f-28b9-e0de00877589
* Content: [Backends for Frontends pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/backends-for-frontends)
* Content Source: [docs/patterns/backends-for-frontends.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/backends-for-frontends.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @StingyJack Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by dragon119** [comment]
@StingyJack , These two patterns address different problems. MVC is to decouple the presentation from the backend data while BFF is to provide most relevant API for each type of consumers (PC, mobile, etc.)

**Comment by StingyJack** [comment]
CodeBehinds specifically and Controllers (both ASP.net MVC and the standard kind) are layers of indirection used to serve a UI that will interact with services or data to provide the UI with what it needs. 

Controllers _could_ be used to serve non UI clients as well.  Codebehinds are entirely specific to a UI. There is no mention of API on the page.

I dont see what makes this pattern any different from other well established and fairly common patterns other than a silly name with a sillier acronym.

**Comment by DixitArora-MSFT** [comment]
@StingyJack Just following up if there are any further questions. 
@dragon119 Thanks for your inputs.

**Comment by StingyJack** [comment]
@dixitarora-msft - my original question/point has not been addressed.

This article is incomplete if it does not mention these other examples. If the intention is to not mention them, that would be disingenuous (to MSFT especially) and sillier than this patterns acronym.

**Comment by dragon119** [comment]
@StingyJack, backends for frontends is actually a well-known pattern. If you search for that term, you'll see it.

**Comment by DixitArora-MSFT** [comment]
@StingyJack I have assigned this to content author to review and update as appropriate.

**Comment by MikeWasson** [comment]
I'll chime in...

> Controllers could be used to serve non UI clients as well

I think this is conflating "controllers" as a specific programming construct in some frameworks (e.g. ASP.NET) with controllers in the MVC design pattern. In the original MVC pattern, the controller is specifically a link between the user and the system. It's true that you can use (ASP.NET) controllers to implement web APIs and therefore to implement the backends-for-frontends pattern, but that's an implementation detail. But the two design patterns have different intents.

**Comment by MikeWasson** [comment]
I'm going to go ahead and close this issue now. Hopefully this thread clarifies why BFF is a "real" pattern, unfortunate acronym aside 😸
