### ISSUE TITLE
AWS Systems Manager

### ISSUE THREAD

**Issue by tedsmitt** [MicrosoftDocs/architecture-center#1625]
I would argue that AWS Systems Manager is a lot similar to Azure Automation. Granted it can be used to monitor compliance/remediate issues. However, it also has a large focus on automating repetitive tasks as well as patching and managing EC2 instances.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @tedsmitt Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@JasRobe Any inputs in this ?

**Comment by doodlemania2** [comment]
This is an interesting, but not quite complete comparison. We'll close this for now, but if you think we're missing the mark, please definitely let us know and we'll be happy to rethink!
