### ISSUE TITLE
Reading from Cosmos Db

### ISSUE THREAD

**Issue by laneyvb** [MicrosoftDocs/architecture-center#1627]
The architecture diagram at the top shows data flowing from cosmos via the hot path to stream analytics .   The example architecture and other documentation  only covers writing to Cosmos from IoTHub via functions.    I think that arrow should be removed from the diagram, if it's not a mistake and is possible info on how to read from Cosmos into stream analytics would be a useful addition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa3f2c8a-9d2a-579b-6cb7-4e81fb561067
* Version Independent ID: 0d48338a-52aa-f518-82c3-e5ac281bd8f5
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot/#feedback)
* Content Source: [docs/reference-architectures/iot/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@laneyvb Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@laneyvb - Thanks, I agree this doesn't make much sense as shown. I think the arrow should be reversed, you can have Stream Analytics write to Cosmos DB as part of the hot/warm path.
