### ISSUE TITLE
Article should be updated

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/architecture-center#1628]
Very well written article. Thanks for the details shared. However, will be great to see this article updated with the below info which will be very useful for readers/users:
1. Provide VHD files for so that we could edit and reuse
2. Update terminology on OMS with new terminology
3. Provide guidance on what is required for a managed services team to operate for a different Azure subscription (Example: A managed services provider managing a customer virtual DC environment")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d8a578-f9f1-53af-64d0-808f1fde6c9c
* Version Independent ID: 8a647cb7-2d10-53ed-5459-4356ef607e77
* Content: [Azure virtual datacenter: A network perspective](https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter)
* Content Source: [docs/vdc/networking-virtual-datacenter.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/vdc/networking-virtual-datacenter.md)
* Service: **architecture-center**
* Sub-service: **enterprise-cloud-adoption**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by DixitArora-MSFT** [comment]
Hi @knssub Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
Tagging @BrianBlanchard

**Comment by BrianBlanchard** [comment]
Adding @tracsman for thoughts on this potential improvement.

**Comment by doodlemania2** [comment]
Thanks so much for this report. We've taken the feedback into the internal planning docs for an update to VDC soon!
