### ISSUE TITLE
Use Polly

### ISSUE THREAD

**Issue by reddyrajanala** [MicrosoftDocs/architecture-center#1629]
I highly recommend Polly
https://github.com/App-vNext/Polly/wiki

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497c1436-d32c-1fb5-3209-22058fece4b2
* Version Independent ID: 4818d7be-c866-39bc-f2c3-d7af59d2cd4e
* Content: [Retry pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry)
* Content Source: [docs/patterns/retry.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/retry.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @reddyrajanala - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
@reddyrajanala Thanks - I agree that generally you should not roll your own retry logic. The purpose of the code snippet is to demonstrate the pattern, but we should include some additional pointers to things like Polly and Resiliency4j. Also for Azure specifically, most of the client SDKs have built-in retry logic.
