### ISSUE TITLE
Capping issue with elements in "OLTP"

### ISSUE THREAD

**Issue by mikepope** [MicrosoftDocs/architecture-center#1630]
You're capping "Online Transaction Processing" two ways--using sentence capping in the title (perhaps part of an overall push for sentence-capping titles?), and using heading caps in the intro para. I only noticed this because we're trying to figure out what the appropriate capping is for this term. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af4555db-76bc-15c1-6b17-ddf5be651b70
* Version Independent ID: 3ec33db3-f67d-6786-aeb3-9737896088bf
* Content: [Online transaction processing (OLTP)](https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-transaction-processing#feedback)
* Content Source: [docs/data-guide/relational-data/online-transaction-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/relational-data/online-transaction-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @mikepope Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@mikepope I can't think of any reason for this to be capitalized, as it's a general industry term not something like a brand name. FWIW Wikipedia [agrees](https://en.wikipedia.org/wiki/Online_transaction_processing) 😺
