### ISSUE TITLE
Add heirloom computing to the list of options

### ISSUE THREAD

**Issue by swissgrammie** [MicrosoftDocs/architecture-center#1631]
Heirloom provides compiler and runtimes to migrate application code and data to the cloud, we are already a microsoft partner and have replatformed customer application to automatically integrate native cloud features such as dynamic horizontal scaling and serverless functions as a service. I would be happy to help you update your documents to reflect our capabilities.

**Comment by mike-urnun-msft** [comment]
@swissgrammie Thank you for sharing your feedback! Could you provide us with the URL of the specific documentation that your feedback is applicable to?

We would love for you to contribute towards MS Docs; you can start here and review the process: [Contribution Guide](https://review.docs.microsoft.com/en-us/help/contribute/?branch=master)

**Comment by mike-urnun-msft** [comment]
@swissgrammie Since we haven't heard back, we will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
