### ISSUE TITLE
Correct wrong content

### ISSUE THREAD

**Issue by cengxiye** [MicrosoftDocs/architecture-center#1632]
Step 2: Manage hybrid identity 
"In Connect to Azure AD, they specify the credentials for connecting to the Azure AD (in the form CONTOSO\admin or contoso.com\admin)."
It seems not right, the picture shows that the form should be xxxxxx@contosomigration.onmicrosoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c99f2c-3d30-6c23-7559-de463464e52a
* Version Independent ID: bc59e60a-7a1d-b31a-a173-8fb1dbde0a61
* Content: [Deploy a migration infrastructure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure#step-2-manage-hybrid-identity)
* Content Source: [docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure.md)
* Service: **azure-migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by KetanChawda-MSFT** [comment]
@cengxiye Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by BrianBlanchard** [comment]
Thanks for catching this error. The update will be pushed out in our next release.
