### ISSUE TITLE
NSG and ASG

### ISSUE THREAD

**Issue by cengxiye** [MicrosoftDocs/architecture-center#1633]
Can experts also check the table of this chapter?
https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure#work-with-nsgs

It's not easy to understand where the NSG fits, and also the meaning of those rules, for example rule AllowWebToApp looks like allow FE tier to App tier, the source is APP1-FE, but the destination tier is APP1-DB (database tier), I am confused with that.

I went through this documentation several times, and I find it's very useful, but it get me confused some time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c99f2c-3d30-6c23-7559-de463464e52a
* Version Independent ID: bc59e60a-7a1d-b31a-a173-8fb1dbde0a61
* Content: [Deploy a migration infrastructure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure#work-with-nsgs)
* Content Source: [docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure.md)
* Service: **azure-migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
Another great catch. The table has been updated & will go live in our next release. Thank you
