### ISSUE TITLE
Step2 Source server type is wrong

### ISSUE THREAD

**Issue by cengxiye** [MicrosoftDocs/architecture-center#1634]
For Source server type, Contoso selects SQL Server on Azure Virtual Machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99fa4eb8-fc61-25c9-1e8d-f52a0eac1381
* Version Independent ID: 7958b3aa-d184-5f73-7364-6f99913614a9
* Content: [Assess on-premises workloads for migration to Azure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-assessment)
* Content Source: [docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-assessment.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-assessment.md)
* Service: **site-recovery**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by KetanChawda-MSFT** [comment]
@cengxiye Thank you for your feedback! Can you please provide more details around this issue for better clarity.

**Comment by KetanChawda-MSFT** [comment]
@cengxiye Just realize what you are mentioning. I will create a PR to fix this. It should be "For Source server type, Contoso selects SQL Server and for Target server type, Contoso selects SQL Server on Azure Virtual Machines.

**Comment by KetanChawda-MSFT** [comment]
@cengxiye Thank for the catch! We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
