### ISSUE TITLE
Perpetuates some myths about REST

### ISSUE THREAD

**Issue by lukepuplett** [MicrosoftDocs/architecture-center#1635]
I'm sorry to pick on this page, since I cannot remember ever seeing a good introduction to REST, but since its coming from Microsoft I think its important to pick on authority. I think it perpetuates some myths about REST and should instead start with HATEOAS and the state machine and then explain that to make this work requires the creation of rules around processing the JSON, XML or XHTML.

Consider that most people won't read the whole page, so the most accurate information needs to be at the top.

The whole industry seems to have misunderstood REST. Roy Fielding, in his famous dissertation, says that almost all of the design effort should be concentrated on the specification of the media-type. Consider this web page and how I'm able to see and then fill this form in and use this site; it's possible because of the effort placed in specifying HTML and how HTML, browsers and HTTP must work together. For example, what to do when a browser sees a Form tag and how to construct the Post and the body. Once these rules are in place and agents all obey the rules, the web just works. This is the same for REST.

REST is not about friendly URLs with pluralised nouns and database identifiers on the ends and using verbs like database updates, just as the web doesn't care for the URLs that make the site work. The web doesn't even use PUT or DELETE and yet we're quite able to update and delete stuff.

It's about the information in the hypertext document that offers the next legal operations and allows a client to formulate the next request flawlessly; i.e. if the client forms a bad request then there's something wrong with the hypertext control that led to it.

Sometimes there may be a set of client-server interactions and state transfers in order to build up the final, correct HTTP request to do something, just like on the web it might take a few clicks to find a book, add it to your cart and pay for it. Modelling those steps as a single step would not make for a good API since the client would not know the URL to post to, nor the ISBN number or the credit card database ID to send, moreover, the order URL might have changed due to a new release of the API.

Read this https://medium.com/lukepuplett/websites-and-restful-apis-are-nothing-but-a-builder-pattern-b8f7615ca2a5 and look at this https://github.com/lukepuplett/surfdude-csharp

Like a website, a REST API must be used from the root of the API because the links and forms may have changed since you last used it. Like a website, the URLs are just a means to an end, the friendliness of them is just to help programmers.

On versioning, when you have a proper RESTful API that you drive from the root, versioning questions disappear. It becomes obvious that breaking changes mean offering and introducing a new link and therefore a new branch to take in the interaction journey that clients opt into, a bit like radical redesigns of web pages often offer the user a link to "try out" the new UX.

Basically, change the focus of this article. If talking about REST then it has to be HATEOAS else its not REST. Talk about this and explain that its totally cool to not use REST but a simple unlinked CRUD-over-HTTP design. REST is best when your API users are far away. Explain that when the same coder or team is writing the client _and_ the API then REST could be overkill.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad651d6a-f8d8-2050-e7a7-adbae7326112
* Version Independent ID: 4fddd724-cabd-8623-7692-857088c1dccb
* Content: [API design guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design)
* Content Source: [docs/best-practices/api-design.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/api-design.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by lukepuplett** [comment]
It's not a terrible article, on the contrary but in general the HATEOAS information comes too late in the page, and there are some specific things that betray the author's understanding.

Under "Organise the API around resources"

> https://adventure-works.com/create-order // Avoid

This is a myth. If when I hit the green Comment button on this GitHub page, the URL to which it posts in the form control behind this page has a verb in it, do I care? No. There's no such thing as a RESTful URL. This can be very strange for people since the myths are ingrained over years and "social proof" makes it hard to go against this. Now, a verb in a URL may be a warning sign that a developer is going to use a safe HTTP verb like GET to mutate state, but that's all. If you ever get stuck on this, consider that an API is for a computer to talk to another computer, and they can't read English from URLs :)

Under "Filter and paginate data"

> Give all optional parameters in query strings meaningful defaults

When you think about it, this doesn't make sense. A REST API is entirely navigated via other links leading to other resources. Why would the client ever drop a parameter from a link? I understand the idea from the implementation side, but you'd only be doing this if you weren't using links for everything, i.e. you are expecting the client to hack the URLs.

Under "Query string versioning"

> This approach has the semantic advantage that the same resource is always retrieved from the same URI

Its not the same URI if the query string has changed. Its important that people understand that the URL is the resource identifier in its entirety. So there's no orders resource and then the paging controls are just query parameters like arguments, no, each page of orders is its own resource and page 1 and 2 could have completely different URLs.

**Comment by PramodValavala-MSFT** [comment]
@lukepuplett Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by lukepuplett** [comment]
I've updated the README here which I hope will help "the penny drop" with regard to a REST API (as opposed to a CRUD-over-HTTP API)

https://github.com/lukepuplett/surfdude-csharp/blob/master/README.md

**Comment by MikeWasson** [comment]
Thanks for the feedback and discussion. This article is intended to balance pragmatism and theory - the title "API design" rather than "REST API design" was meant to hint at this.

I completely agree the definition of REST includes HATEOAS (I've read the dissertation too) but in practice a lot of web APIs are not fully RESTful, and I think that starting with HATEOAS as a minimum requirement can lead people to throw up their hands and then ignore a bunch of other best practices. To that end, I like the Richardson maturity model. I tried to make this explicit in the article.

Regarding the URI example, the point isn't the name of the URL but the idea that URLs should identify resources rather than actions. This comment exactly captures the intent:

> Now, a verb in a URL may be a warning sign that a developer is going to use a safe HTTP verb like GET to mutate state, but that's all.

... so probably that section of the doc could be clearer.

**Comment by lukepuplett** [comment]
Hi Mike, I take your points.

I think the reason why almost no REST API is actually RESTful, is because a) no one has ever seen a good example, and b) every tutorial perpetuates folklore because of (a).

I was one of those guys that used to think I was building REST APIs by having nounified URLs, single resources and collections, using verbs perfectly but all the while having no _useful_ links and needing some "side band" form of documentation, usually Swagger.

Here are the things that really altered my understanding.

- When Roy Fielding says that most effort goes into specifying the media-type, he didn't mean the deserialization into data, he meant how the data communicated instructions for driving the API. E.g. reading and writing HTML is easy, rendering websites that work is the hard part.

- URLs are a means to an end, just like when building a website. On the web, ugly, long redirect URLs and strange paths and strange query params are the norm because we tend to just use the URL to "make the site work". Other than embedding keywords for SEO and some nice to have UX, we were taught that the URL doesn't much matter. With REST, we always begin tutorials by hammering on about a good URL structure, which is wrong. We don't teach web design by harping on about friendly URLs on page one, rather, we teach the media-type HTML, links, making a landing page, and then navigation around the functional hubs of hyperlinks and forms.

- APIs must start with a homepage. This is a massive mental game changer. If you think about websites, the idea of not having a homepage, a way to reach every feature from the `~/` route is insane, but in REST APIs we never mention it which is equally as insane.

- Interacting with a REST API is the same as a website. Its a journey from the root to a functional hub, perform some action and return to the hub. Its forward-only.

- Like HTML, a REST API can't really be used to mutate state without some kind of `form`. Most examples show a simple link with a verb in it and nothing else. But how does the user-agent know what data to POST? What are the legal parameters? The answer is usually that the developer can dereference the target URL and look at what shape of data is already in the "collection resource" and then guess and then hope the errors are useful. That's ridiculous. It reinforces the circular myth that URLs must be intuitive and guessable to help developers, and that we must "POST into collections" or that there's some other form of documentation alongside. Website have none of this, because the architects of HTML realised the need for forms and combo boxes. REST APIs must have these devices else they can't "achieve" HATEOAS, which takes us back to the importance of the media-type.

- Some "steps" in an API design may exist simply to collecting, narrow and present new options in another form control.

Given the above, if Microsoft hired me to write all their REST APIs for Azure, there'd be no documentation, and yet I'd also make it _impossible_ to use it incorrectly. Just as there is no documentation for GitHub.com and yet, so long as you use the hypermedia controls provided, its also impossible to use incorrectly and cause a 400.

You're a smart guy, so I will no labour any more on this. I'll let you decide if you think the document could better serve its audience and the world of machine-machine interaction.

Thanks for listening and facilitating open discussion.

Luke

**Comment by doodlemania2** [comment]
@lukepuplett would you be willing to offer a PR referencing this issue that adjusts the article based on this excellent discussion?

**Comment by lukepuplett** [comment]
Hey Derek, funny you ask! I wondered this myself. I looked yesterday at how to PR on GitHub, I think I have to fork it and... well anyway I'll figure it out. But yeah, I'll see what I can do.

**Comment by doodlemania2** [comment]
That's it Luke, just do a fork and edit there. Then, create a pull request from your fork and it will show up on our side as a pull request to master that we can review and then put in. In your pull request description, add these words: #closes and then URL to this issue (the whole thing) 👍

**Comment by MikeWasson** [comment]
I've been thinking more about this discussion thread - What I think might work is to move the discussion of HATEOAS forward in the doc, framed as: "Consider building HATEOAS into your API because it gives you such-and-such advantages" (e.g., easier versioning, decoupling client from hacking URLs). Because I think that most people are not doing this, but at least should consider it up front.

**Comment by lukepuplett** [comment]
How about approach the common pragmatic approaches to web APIs, which in my opinion are;

- RPC-over-HTTP, which is like an Azure Function HTTP trigger, sending a message to make a remote machine do something.

- CRUD-over-HTTP, which is your garden-variety "REST" API with "designed" resource names, collections that are like tables and verbs that map to CRUD operations. These have a strong coupling to their clients, which may use [Refit](https://github.com/reactiveui/refit). Here, the URL design is important because you're expecting the client developer to assume conventions.

- REST, very rare APIs driven entirely by hypertext and more suited for large applications that are facing the public web, or out to a large company intranet, or where developer UX/productivity is important and the consumers are unknown but the API must be free to evolve without breaking clients.

I'd probably call out that the term REST is used casually and that some people use other names like Hypertext API or HATEOAS to refer to those that strictly follow Dr Fielding's [constraints](https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven).



Not sure whether to cover GraphQL. It appears to be a standardized, or well-known media-type specification for querying data, rather than a style of API.

A GraphQL query could potentially be part of a REST API so long as the client was able to form and enact the query using only information in the media-type specification and the hypertext of a previously obtained resource representation.

**Comment by lukepuplett** [comment]
Hey - just to set some expectations, my contract ends Aug 30 so I'm delaying working on a revision to this document until I have a lot more time on my hands next month :)

**Comment by lukepuplett** [comment]
My contract was renewed (unexpected) but I've been working on this. In the spirit of early feedback I have a gist https://gist.github.com/lukepuplett/42f95171ff090de0c0971e9c4c69e532

APIs are super important, as much as a GUI, and the article is API _design_ so I'm discussing much more of the "design" side of things, and then you can see my thoughts become more sketchy as it goes down. Once this "before you start coding" stuff is covered and the _styles_ of API introduced, it'll then incorporate the original document much more.

Mostly I want to give you the opportunity to stop me before I run ahead and waste my time :)

**Comment by doodlemania2** [comment]
Thank you so much @lukepuplett for taking the time to work with us on your thoughts. Feel free to follow up additionally offline as discussed. We're going to close for now as we don't have an exact action we can take other than continuing to research. Cheers!
