### ISSUE TITLE
typo "mange" instead of "manage"

### ISSUE THREAD

**Issue by OlivierJM** [MicrosoftDocs/architecture-center#1637]
There is a typo under Architecture section 
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp#architecture

on the 7th point it is spelled  wrongly
7. Developers monitor and <del>mange</del> manage health, performance, and usage information.

**Comment by PramodValavala-MSFT** [comment]
@OlivierJM Thanks for contributing to MS Docs!
