### ISSUE TITLE
Typo -"mange"

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/architecture-center#1640]
Developers monitor and mange health, performance, and usage information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8865190-b9ac-ae5e-2590-30237ed43697
* Version Independent ID: 45d8bb8c-10f1-de72-6644-a20ba60a32af
* Content: [Design a CI/CD pipeline using Azure DevOps - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp#feedback)
* Content Source: [docs/example-scenario/apps/devops-dotnet-webapp.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/devops-dotnet-webapp.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @christianreddington
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Good catch, thanks! 😺
