### ISSUE TITLE
Azure Building Blocks should not be used

### ISSUE THREAD

**Issue by alex-frankel** [MicrosoftDocs/architecture-center#1641]
azbb is a dead project per my understanding. Can this be updated to use a different deployment method like ARM, CLI or PS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142dd377-b9db-b526-d4f2-51310cf6a926
* Version Independent ID: 954769a7-e6cf-ed89-e9cc-5c2e63f9890e
* Content: [Windows N-tier application with SQL Server - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/n-tier-sql-server#feedback)
* Content Source: [docs/reference-architectures/n-tier/n-tier-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/n-tier-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@alex-frankel Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by MikeWasson** [comment]
@alex-frankel We're actually updating azbb and working on a refresh of this reference architecture.
