### ISSUE TITLE
Firewall rules do not allow SSH

### ISSUE THREAD

**Issue by fawohlsc** [MicrosoftDocs/architecture-center#1642]
hub-firewall.json only allows RDP via 3389, but not SSH via port 22. Following checking connectivity via Linux VMs will fail in "Add connectivity between spokes" chapter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@fawohlsc Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@fawohlsc Thanks for catching that! Looks like the templates were tailored for windows. For reference, the template would need to look something like in [this commit](https://github.com/PramodValavala-MSFT/reference-architectures/blob/58191fabb9312e684135a2b8a9e2452278972545/hybrid-networking/hub-spoke/hub-firewall.json).

We are assigning this issue to the content author for further review.

**Comment by PramodValavala-MSFT** [comment]
@fawohlsc The templates have been fixed to include SSH ports.

**Comment by fawohlsc** [comment]
Thanks @PramodValavala-MSFT - good job :-)
