### ISSUE TITLE
Verify connectivity in chapter "Add connectivity between spokes" fails...

### ISSUE THREAD

**Issue by fawohlsc** [MicrosoftDocs/architecture-center#1643]
... since Azure Firewall blocks ping 10.2.0.68

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@fawohlsc Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@fawohlsc You can add `ICMP` as a protocol in the firewall rules to get this to work. For reference, the template would need to look something like in [this commit](https://github.com/PramodValavala-MSFT/reference-architectures/blob/268ec03f1101054962b30d773024854e9c732ff3/hybrid-networking/hub-spoke/hub-firewall.json).

We are assigning this issue to the content author for further review.

**Comment by PramodValavala-MSFT** [comment]
@fawohlsc The doc has been updated to use `nc` ([netcat](http://netcat.sourceforge.net/)) instead of `ping` removing the need to allow ICMP and simply utilize the SSH port itself to check for connectivity.

**Comment by fawohlsc** [comment]
THanks @PramodValavala-MSFT  :-)
