### ISSUE TITLE
"Plan" button at the bottom links to Strategy page

### ISSUE THREAD

**Issue by adamboeglin** [MicrosoftDocs/architecture-center#1649]
The "Plan" button at the bottom links to Strategy page.  This should probably link to the overview of the "Plan" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218b42ff-1cf2-c31c-1a1a-59625eb9e09e
* Version Independent ID: ab742d17-9eba-2daa-c4fc-50b17a1e0eba
* Content: [Getting started with a cloud migration journey - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/getting-started/migrate)
* Content Source: [docs/cloud-adoption/getting-started/migrate.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/getting-started/migrate.md)
* Service: **architecture-center**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@adamboeglin Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@BrianBlanchard need your assistance here.
