### ISSUE TITLE
Send application logs using Log4j is giving error

### ISSUE THREAD

**Issue by Aishwaryadinde18** [MicrosoftDocs/architecture-center#1652]
Getting this error while running Log3j command:
import com.microsoft.pnp.logging.Log4jConfiguration
getClass.getResourceAsStream("{file name}/log4j.properties"){
      stream => {
        Log4jConfiguration.configure(stream)
      }
}
Internal error, sorry. Attach your notebook to a different cluster or restart the current cluster.
java.lang.RuntimeException: abort: DriverClient destroyed
	at com.databricks.backend.daemon.driver.DriverClient.$anonfun$poll$3(DriverClient.scala:295)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)

Do I need to Create new a log4j.properties configuration file my application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @Aishwaryadinde18 Thank you for your feedback! We will review and update as appropriate.

**Comment by atoakley** [comment]
Answered in mspnp/spark-monitoring#43
