### ISSUE TITLE
Diagram captions are not visible in dark theme

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/architecture-center#1653]
Hi team,

Please check the issue raised here: https://github.com/MicrosoftDocs/architecture-center.es-es/issues/39

Thanks!

**Comment by DixitArora-MSFT** [comment]
Hi @lichasu Thank you for your feedback! We will review and update as appropriate.

**Comment by MikeWasson** [comment]
This was resolved. For reference, this issue refers to the diagram in [this article](https://docs.microsoft.com/es-es/azure/architecture/example-scenario/apps/devops-dotnet-webapp)
