### ISSUE TITLE
Azure Reference Architecture - Windows N-tier application on Azure with SQL Server- deployment error

### ISSUE THREAD

**Issue by myaesubi** [MicrosoftDocs/architecture-center#1655]
Hi,
I'm working through setup of n-tier app reference architecture at the following Docs address:

https://docs.microsoft.com/en-ca/azure/architecture/reference-architectures/n-tier/n-tier-sql-server

following through the steps of documentation and initiating the deployment after a series of resources are created it throws out an internal error on DSC which is not internal to the VM setup..

`Deployment failed. Correlation ID: c3d1da83-9522-4f1d-ad89-d368511734b9. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'AOSetup'. Error message: \\\"DSC Configuration 'SQLServerDBDsc' completed with error(s). Following are the first few: The system cannot find the path specified. The related file/directory is: F:\\\\Backup.  The related ResourceID is [File]BackupDirectory. The SendConfigurationApply function did not succeed.\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

Appreciate the help.
Thanks,
Mohammad
`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142dd377-b9db-b526-d4f2-51310cf6a926
* Version Independent ID: 954769a7-e6cf-ed89-e9cc-5c2e63f9890e
* Content: [Windows N-tier application with SQL Server - Azure Reference Architectures](https://docs.microsoft.com/en-ca/azure/architecture/reference-architectures/n-tier/n-tier-sql-server)
* Content Source: [docs/reference-architectures/n-tier/n-tier-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/n-tier-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@myaesubi Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@myaesubi Thanks, we're working on a fix for this.

**Comment by MikeWasson** [comment]
We released an update to the deployment that should fix this issue.
