### ISSUE TITLE
Resources dependent on another resource with false condition

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/architecture-center#1656]
What happens when a specific resource is not deployed (`condition`: `false`), but it is specified as dependency for other resources?
Example:

```
A
B depends on A
C depends on B
```

If `A` has its condition set to `false`, what will happen to the dependent resources (`B` and, indirectly, `C`)? will there be an error or will they simply not be deployed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ada6b9c1-42f6-5012-9201-04fd463efdfd
* Version Independent ID: 16abf6b9-c81a-a6f7-d0fd-b22ef3a4a744
* Content: [Conditionally deploy a resource in an Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/conditional-deploy)
* Content Source: [docs/building-blocks/extending-templates/conditional-deploy.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/building-blocks/extending-templates/conditional-deploy.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @petertay
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@fleed Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@fleed For B is A is necessary resource so all the child/dependent resource will fail too. Checkout [this](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-define-dependencies) document for resource dependency.

**Comment by fleed** [comment]
thank you @KetanChawda-MSFT . That means: I should take care of having consistent conditions, so that A and all dependent resources are "ignored", shouldn't I?

**Comment by KetanChawda-MSFT** [comment]
@fleed For a given resource, there can be other resources that must exist before the resource is deployed. For example, a SQL server must exist before attempting to deploy a SQL database. You define this relationship by marking one resource as dependent on the other resource. You define a dependency with the dependsOn element, or by using the reference function.

Resource Manager evaluates the dependencies between resources, and deploys them in their dependent order. When resources aren't dependent on each other, Resource Manager deploys them in parallel. You only need to define dependencies for resources that are deployed in the same template.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
