### ISSUE TITLE
Storage File name conventions 

### ISSUE THREAD

**Issue by sheldoncxd** [MicrosoftDocs/architecture-center#1659]
Per the doc, valid characters for Storage File name is Alphanumeric. But at least I can create a file which name contains hyphen and space. Could you please double check the name convention?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#feedback)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@sheldoncxd Thank you for your feedback!

If you are talking about Storage File Share name, It can contain only lowercase letters, numbers, and hyphens, and must begin and end with a letter or a number. The name cannot contain two consecutive hyphens and File share names must be from 3 through 63 characters long.

I will create a PR to update the document.
