### ISSUE TITLE
Log analytics workspace 

### ISSUE THREAD

**Issue by csmurthy** [MicrosoftDocs/architecture-center#1661]
<snip>
Prerequisites

Configure your Azure Databricks cluster to use the monitoring library, as described in the GitHub readme.

Deploy the Azure Log Analytics workspace
<snip>

The prerequisites need log analytics workspace to be created and configured.
In this document under "Deploy the Azure Log Analytics workspace" section , there are steps to 
deploy the Log Analytics workspace. Do we need two different workspaces?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e17f2434-814c-4ebc-c05d-501566aa3c0f
* Version Independent ID: 6cf80861-2ab6-0c28-8a68-4f641491a61a
* Content: [Use dashboards to visualize Azure Databricks metrics](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/dashboards#prerequisites)
* Content Source: [docs/databricks-monitoring/dashboards.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/dashboards.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by atoakley** [comment]
@csmurthy You only need a single Log Analytics workspace.  You could configure different clusters to go to different Log Analytics workspaces if you would like, but you technically only need one.  If you have already deployed your Log Analytics workspace, you will have to put the queries in manually, which is not ideal.

I think the easiest way to deploy this is to use the template on this page to deploy Log Analytics so you get your queries, then follow the steps to configure Databricks for monitoring.  That way you will have your Log Analytics workspace ID and key for the Databricks init script.

**Comment by csmurthy** [comment]
Thanks Andrew. The documentation is little confusing because by the time someone reading this document  they might have already configured Log Analytics workspace.
