### ISSUE TITLE
Rewrite Always-Once Semantics Reference

### ISSUE THREAD

**Issue by stevekmicrosoft** [MicrosoftDocs/architecture-center#1663]
"Always-Once Semantics" is a either a little used term or not documented anywhere (including the Azure architect exam study materials). I recommend explaining the intent of this term or removing the reference to "always-once semantics."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f10a0039-c955-2af1-6b11-ff611a171740
* Version Independent ID: 12c1ecc1-7db6-2d4b-52f3-d4e99c4c5d44
* Content: [Architecture styles - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/)
* Content Source: [docs/guide/architecture-styles/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @stevekmicrosoft - Thanks for your feedback. Probably should have meant "At-least-once Semantics" @MikeWasson can confirm

**Comment by stevekmicrosoft** [comment]
> Hi @stevekmicrosoft - Thanks for your feedback. Probably meant "At-least-once Semantics" @MikeWasson can confirm

I agree. I think the common terms are: at-most-once, at-least-once, and exactly-once

**Comment by MikeWasson** [comment]
@stevekmicrosoft Yes - thanks for catching this. I'll clarify this sentence, I think the underlying issue is dealing with possible duplicate messages.

**Comment by mike-urnun-msft** [comment]
Hi @stevekmicrosoft - Since @MikeWasson has created a PR that addresses this issue, we will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
