### ISSUE TITLE
Establish a modern perimeter

### ISSUE THREAD

**Issue by annathan** [MicrosoftDocs/architecture-center#1667]
The hyperlinks don't direct anywhere. ie: https://docs.microsoft.com/en-us/azure/architecture/security/governance.md#enterprise-segmentation-strategy delivers a 404 response

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55000863-6c61-319b-7d0d-5366c403e5e2
* Version Independent ID: 7bb9bb22-f939-6176-236f-79399b6ab2b4
* Content: [Security in Azure](https://docs.microsoft.com/en-us/azure/architecture/security/overview#feedback)
* Content Source: [docs/security/overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/security/overview.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @annathan Thank you for your feedback! We will review and update as appropriate.

**Comment by MikeWasson** [comment]
Thanks @annathan, these links have been corrected.
