### ISSUE TITLE
About Set up autoscaling

### ISSUE THREAD

**Issue by cengxiye** [MicrosoftDocs/architecture-center#1669]
https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-refactor-linux-app-service-mysql#set-up-autoscaling
3. They configure the same setting on APP-SRV-CUS to ensure that the same behavior applies if the app fails over to the secondary region. The only difference is that they set the instance limit to 1 since this is for failovers only.
##Correct me if I am wrong, I assume it should be##
3. They configure the same setting on APP-SRV-CUS to ensure that the same behavior applies if the app fails over to the secondary region. The only difference is that they set the default instance to 1 since this is for failovers only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd12ea5-4d78-d0ed-01fd-baae3c9d9b7f
* Version Independent ID: 1b2221be-3378-7594-9dd9-eb5e69b12613
* Content: [Refactor a Linux service desk app to Azure App Service and Azure Database for MySQL - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-refactor-linux-app-service-mysql#set-up-autoscaling)
* Content Source: [docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-refactor-linux-app-service-mysql.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-refactor-linux-app-service-mysql.md)
* Service: **site-recovery**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by DixitArora-MSFT** [comment]
Hi @cengxiye Thank for reaching out. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@cengxiye I have created the PR for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
