### ISSUE TITLE
Best Practices- missing links

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#1673]
Some of the Identity Best Practices do not have links to the supporting documentation, please add them.

Actually, having the separate Implementing Identity Best Practices section with the links at the end of the document in a little bit confusing, it would be a little bit easier to follow the text if those links were included in the specific section, maybe as a link to Implementation Guidance/Instructions or something similar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def43e94-5049-5848-e385-dda52e7bd3dc
* Version Independent ID: 32cea313-ec24-f5b2-02bf-3cbe5a355a13
* Content: [Identity and Access Management in Azure](https://docs.microsoft.com/en-us/azure/architecture/security/identity#implementing-identity-best-practices-in-azure)
* Content Source: [docs/security/identity.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/security/identity.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @DeanGross - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by absheik** [comment]
AB#160264 - Thanks for reporting - this issue is under review

**Comment by david-stanford** [comment]
Thank you for this feedback, I've cleaned up the article and it will be updated in the next publish.
