### ISSUE TITLE
link from CQRS

### ISSUE THREAD

**Issue by tao-sj** [MicrosoftDocs/architecture-center#1674]
[Enter feedback here]

Good information. A minor comment in last section:

```For a comparison of CQRS with other architectural styles, see Architecture styles.```
There's no comparison of CQRS in "Architecture styles", maybe want to link to "https://docs.microsoft.com/en-us/azure/architecture/patterns/ " ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [Command and Query Responsibility Segregation (CQRS) pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @tao-sj - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
@tao-sj - Thanks, we originally had CQRS as one of the styles but we demoted it 😸 ... as it's really more of a design pattern.
