### ISSUE TITLE
Vnet peering transitivity is allowed

### ISSUE THREAD

**Issue by AvanadeAndrej** [MicrosoftDocs/architecture-center#1678]
Feature was released in April. I've done it in my labs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@AvanadeAndrej Thanks for sharing your observation. Just following to check Is there any other questions you have related to this .

**Comment by AvanadeAndrej** [comment]
Nope. Just letting you know your documentation is outdated as I've seen it work

Regards,

Andrej Rosic

Sr Consultant | Apps & Infrastructure
O: 312.373.5844
M: 773.396.7226

________________________________

**Comment by DixitArora-MSFT** [comment]
@AvanadeAndrej Thanks for the update. I will create the internal work item for this. For now I will proceed with closure of this and if there are any further questions, please tag me in your reply and we will reengage.
