### ISSUE TITLE
VNET Gateway, Connection and Local Network Gateway

### ISSUE THREAD

**Issue by hisasima** [MicrosoftDocs/architecture-center#1679]
I wanted to check about naming rule of Networking resource which includes VNET Gateway, Connection and Local Network Gateway. But I could not find those resources in this page. I hope the limitations of those resources will be written in this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @hisasima Thanks for the feedback. We will investigate and update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
