### ISSUE TITLE
Azure Functions v2 instead of Web Jobs

### ISSUE THREAD

**Issue by thara0402** [MicrosoftDocs/architecture-center#1680]
Background jobs
https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/background-jobs.md

I think this article should be updated to use Azure Functions v2 in the example. 
As of today, Azure Functions v2(Durable Functions) is a recommended solution for Background jobs in Azure.

**Comment by DixitArora-MSFT** [comment]
Hi @thara0402  Thanks for reaching out. We are actively investigating and will get back to you shortly

**Comment by MikeWasson** [comment]
Agree! Closing as a dup of #1361
