### ISSUE TITLE
Is there no PDF available for Cloud Adoption Framework only?

### ISSUE THREAD

**Issue by smoms** [MicrosoftDocs/architecture-center#1681]
Is there no PDF available for Cloud Adoption Framework only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218b42ff-1cf2-c31c-1a1a-59625eb9e09e
* Version Independent ID: ab742d17-9eba-2daa-c4fc-50b17a1e0eba
* Content: [Getting started with a cloud migration journey - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/getting-started/migrate)
* Content Source: [docs/cloud-adoption/getting-started/migrate.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/getting-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by doodlemania2** [comment]
unfortunately, that's not an option at this time, but it is something we are working on!
