### ISSUE TITLE
Information on using Azure Devops with R

### ISSUE THREAD

**Issue by brshallo** [MicrosoftDocs/architecture-center#1683]
Would like to see some notes + guides specific to using Azure Devops + R.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2808e74b-c325-7b50-093a-b777473864b5
* Version Independent ID: e1f632cb-92ef-958e-5bf4-d250108e1c8d
* Content: [R developer's guide to Azure - R programming](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/r-developers-guide#feedback)
* Content Source: [docs/data-guide/technology-choices/r-developers-guide.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/r-developers-guide.md)
* Service: **machine-learning**
* GitHub Login: @AnalyticJeremy
* Microsoft Alias: **jepeach**

**Comment by mike-urnun-msft** [comment]
Hi @brshallo - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by AnalyticJeremy** [comment]
Hi, @brshallo. Can you elaborate a little bit on what you're looking for?

For example, do you have some R code that you would like to manage within Azure DevOps?  Do you have R models that you would like to deploy with CI/CD pipelines?

Or are you looking to control Azure DevOps with R?  Would you like to write an R script that calls the DevsOp API to kick off a new build?

**Comment by brshallo** [comment]
@AnalyticJeremy in the immediate term, we are moving some internally developed R packages to Azure Devops.   We would like to use Azure Devops to manage tests as well as documentation + vignette building for these packages.  (Our team is just getting access, and I expect in the long-term we will use Azure Devops for a much broader set of use cases).

I found some Azure Devops + R tutorials on @robertdj blog, e.g. [test r in azure devops](http://www.dahl-jacobsen.dk/data/2019/03/20/test-r-in-azure-devops/) and found this thread on [Rstudio Community's page](https://community.rstudio.com/t/creating-an-azure-pipelines-yml-for-azure-devops-testing-packages-shiny-scripts/32471).  Though could not find documentation on R + Azure Devops specifically on Microsoft's site, even on simple things like how to point my colleagues to install packages from a repo on Azure Devops -- instigating this tweet: https://twitter.com/brshallo/status/1156260156503707648 .

Given Microsoft's strong support of R, I was expecting to find more materials/getting started guides specific to Azure Devops + R (hence my post/issue on the docs page).

**Comment by AnalyticJeremy** [comment]
Thank you for pointing out this gap in our documentation.  I will talk with some of our R developers and see if we can get this article in the pipeline.

**Comment by asbates** [comment]
I am in the same boat so I second this.

But can I add an additional request? It would be nice to have some documentation geared towards IT/software personnel. As in, what is different about R packages vs. other programming languages? For example, vignettes and/or data are often included in R packages (not sure if this is true for other languages). Essentially, something to bridge the gap between IT/software people who might not know anything about R and R users.

**Comment by AnalyticJeremy** [comment]
@brshallo This item is still in the backlog.  In the meantime, it might help to check out this timely blog post from @revodavid 
https://blog.revolutionanalytics.com/2019/09/devops-and-r.html

**Comment by AnalyticJeremy** [comment]
@asbates Can you elaborate a bit on your request?  Are you looking for general information on how R packages work?  Or are you looking for information specific to how R packages can be included in a DevOps pipeline?

**Comment by asbates** [comment]
@AnalyticJeremy I'm looking for information specific to R packages in a DevOps pipeline. Essentially, what @brshallo is looking for: building R packages including running tests and building documentation + vignettes.

In addition to that I was hoping to have a quick summary of how to set this up, what sort of system setup is required, etc., but geared towards IT personnel. I think generally, IT may not know much about R. But they will likely be needed to help with setup and if they don't even know what R is, this will probably be difficult.

If this is a bit off-topic I can file a separate issue. Or if you don't think this will be necessary that's fine too. But I wanted to ask just in case.

**Comment by athosfolk** [comment]
My requirement is similar but simpler. I would just like to Connect RStudio version control to an Azure Devops repository.

**Comment by chriseshleman** [comment]
@athosfolk 's comment is headed in the right direction IMHO

**Comment by absheik** [comment]
AB#160263 - Thanks for reporting - this issue is under review

**Comment by absheik** [comment]
We have taken this up as a backlog item.  Closing the issue as it needs creation of a separate article to link to this content which will be addressed by our backlog item

**Comment by LindsayDChristian** [comment]
> My requirement is similar but simpler. I would just like to Connect RStudio version control to an Azure Devops repository.

Hello,
Is there any information to answer @athosfolk's inquiry?

I am also searching on how to Connect RStudio's version control to an Azure DevOps repository.

**Comment by AnalyticJeremy** [comment]
I am not familiar with the version control functionality in the RStudio products.  However, I found that they posted an article that might be helpful:
https://support.rstudio.com/hc/en-us/articles/360045105794-How-to-setup-Git-backed-content-deployment-from-a-private-repository-in-RStudio-Connect

Azure DevOps uses Azure AD for user credentials.  Many third-party services don't support this.  Therefore, Azure DevOps supports "Personal Access Tokens" that allow you to give a third-party service access to your DevOps git repos.
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page

Do either of these articles help answer your question, @LindsayDChristian?  Or did I misunderstand your request?

**Comment by LindsayDChristian** [comment]
Thank you @AnalyticJeremy - those links are helpful for deploying apps. The functionality I was hoping DevOps would have is a similar simple version control as follows:

**Initial Setup**
1. Assuming the use of Windows PC, Git for Windows is required. [_is there a similar program used for DevOps e.g. SubVersion?_]
2. In RStudio. Go to Tools > Global Options… > Git/SVN. Then specify “Git executable” as C:/Program Files/Git/bin/git.exe. Click OK. 
3. In RStudio, go to File > New Project… > Version Control > Git.  Enter the link to the GitHub repository: https://github.com/<_path to repository_>.git (The link can be copied from the “Code” button of GitHub repository). Click “Create project”. This will clone the repository to the local machine. It may ask for sign in with GitHub credentials as well. 

**Pulling a repository:**
Pulling a respository is synchronising the scripts on your machine with the latest version. 

Locate “Git” pane next to “Environment”, “History”. and “Connections”.
Click “Pull” button.
IMPORTANT: Check if it pulled without any error message.

**Making changes -  save, commit, and PUSH**
Save files after you make some changes.
“Git” pane will show the files that have been amended (unless excluded by .gitignore^).
Check “Staged” checkboxes next to the files you want to commit.
Click “Commit”.
Check changes you want to send to the repository. Put commit message (For example, “revised this function”. It could be “regular commit”, “miscellaneous”, etc. Date/time and author will be included so unnecessary.).
Click “Commit”.
IMPORTANT: again, check if it committed the changes without any error message.
Click “Push”.
IMPORTANT: once again, check if it pushed your commit without any error message.

^Should you want to exclude any file to be shared in the repository, you need to add it to .gitignore file.

From the links you have shared and my searching to date it seems DevOps does not appear to have a similar functionality?

**Comment by AnalyticJeremy** [comment]
Thank you for the additional details, @LindsayDChristian.  I think I have some good news for you!

[Azure DevOps uses Git](https://docs.microsoft.com/en-us/azure/devops/user-guide/code-with-git?view=azure-devops) for its source control repositories.  So the RStudio instructions you posted will generally work the same.  You will still need to install Git for Windows on your PC (as described in your instructions).  And you will still PULL and PUSH to the Azure DevOps Git Repo with RStudio.

The main difference is that instead of using a GitHub URL in Step 3, you will use an Azure DevOps URL.  In Azure DevOps, open your project and click "Repos" from the panel on the right of the screen.  This will take you to your repo.  In the upper right corner, there's a button that says "Clone".  If you click that button, it will show you the Git URL that you need to enter into RStudio.

The URL should look something like:  https://&lt;your org name&gt;@dev.azure.com/&lt;your org name&gt;/&lt;your project name&gt;/_git/&lt;your repo name&gt;

Does this help?

**Comment by MannytheAnalyst** [comment]
> @asbates Can you elaborate a bit on your request? Are you looking for general information on how R packages work? Or are you looking for information specific to how R packages can be included in a DevOps pipeline?

For me is how can I work as a R user easily use Azure Devops repos

**Comment by AnalyticJeremy** [comment]
> For me is how can I work as a R user easily use Azure Devops repos

@MannytheAnalyst , are you using R Studio?

**Comment by asadow** [comment]
Were the guides/docs made in relation to the OP's question? Where can I find them?
