### ISSUE TITLE
Downloadable Guide vs. Web Guide

### ISSUE THREAD

**Issue by stevekmicrosoft** [MicrosoftDocs/architecture-center#1684]
The content in the downloadable Guide appears to have dated content. For example the downloadable guide  lists Azure Container Service as an available compute option (now deprecated). Conversely, the downloadable guide does not list Azure Kubernetes Service . Recommending syncing the guide or remove the download link. See  PDF page 48  (book page 38).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d64006-a818-b7fe-7245-bcdba08434cc
* Version Independent ID: 13ac8881-39c6-b3c1-cfe8-58ff4c9c19cd
* Content: [Overview of Azure compute options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-overview)
* Content Source: [docs/guide/technology-choices/compute-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
@stevekmicrosoft Are you referring to the e-book linked from [here](https://docs.microsoft.com/azure/architecture/guide)? I agree that's outdated. Currently we aren't planning an update to the e-book version. I'll remove the download link.
