### ISSUE TITLE
Sync Admin Accounts

### ISSUE THREAD

**Issue by crmhh** [MicrosoftDocs/architecture-center#1685]
Hi,
please provide more details for the section: Don’t synchronize on-premises admin accounts to cloud identity providers

Is your point to grant admin roles in AAD only to cloud-only accounts?

AFAIK the managemant of administrative rights in AD and AAD are separated and from the perspective of the AAD a domain admin is a "normal account". Where is the path for the privilege escalation?

And please describe how AADC prevents the sync by default. In my experience Domain Admins are synced but you get an error message in the logs for the writeback of the ms-ds-consistencyGUID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def43e94-5049-5848-e385-dda52e7bd3dc
* Version Independent ID: 32cea313-ec24-f5b2-02bf-3cbe5a355a13
* Content: [Identity and Access Management in Azure](https://docs.microsoft.com/en-us/azure/architecture/security/identity?WT.mc_id=none-twitter-tajanca#feedback)
* Content Source: [docs/security/identity.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/security/identity.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by absheik** [comment]
AB#160260 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
We've discussed this with our SMEs and they feel the documentation is accurate. We've taken feedback for enhancements in a future iteration. Closing for now.
