### ISSUE TITLE
Conflicting info re: AD DS support for SharePoint 2016?

### ISSUE THREAD

**Issue by brianlala** [MicrosoftDocs/architecture-center#1686]
This article states that:

_SharePoint Server 2016 also supports using Azure Active Directory Domain Services. Azure AD Domain Services provides managed domain services, so that you don't need to deploy and manage domain controllers in Azure._

But then further down:

_The domain-level service accounts used to run SharePoint Server 2016 require Windows Server AD domain controllers for domain-join and authentication processes. Azure Active Directory Domain Services can't be used for this purpose._

Which statement is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d93eb87-54cb-cf38-dfae-0ebe7579d608
* Version Independent ID: c7ac665e-d194-ab07-c1bb-5d5a3049c5ec
* Content: [Run a highly available SharePoint Server 2016 farm in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/)
* Content Source: [docs/reference-architectures/sharepoint/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sharepoint/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@brianlala Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by pstork** [comment]
The original draft of this document was written before Azure VMs supported using Azure Active Directory Domain Services.  That's why the design includes AD domain controllers that are in a Trust relationship with on-premises AD servers. SharePoint does require domain-level service accounts, but at this point those can be provided either by an actual Domain or Azure AD Domain Services.  The first statement is more recent and technically more correct.

**Comment by brianlala** [comment]
Nice, and yeah I just basically confirmed this in my Azure lab. Might submit a PR shortly.

**Comment by doodlemania2** [comment]
Pretty please @brianlala !!! We love PRs!
