### ISSUE TITLE
Max lenght of the subscription name?

### ISSUE THREAD

**Issue by theheatDK** [MicrosoftDocs/architecture-center#1688]
Hi,
For most resources listed above, there is a min and max length for the name. But this is not stated for subscriptions. It would be nice if this was added :-)
Regards Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @theheatDK - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by theheatDK** [comment]
Hi @doodlemania2,
You have closed this without any comments? Is there a min/max? Do you not want to share what they are?
Regards Peter

**Comment by doodlemania2** [comment]
Hi @theheatDK - apologies for the confusion, your issue was closed as resolved as we pushed an update to the document this morning addressing it! It can take several hours to distribute the updated content worldwide. In the interim, the magic number is 1-64 alphanumeric except < > | and ;

**Comment by theheatDK** [comment]
Ah perfect. Thank you @doodlemania2
