### ISSUE TITLE
Scalability Capabilities

### ISSUE THREAD

**Issue by jasonbruno88** [MicrosoftDocs/architecture-center#1692]
Page needs to be updated to reflect that Azure SQL Data Warehouse now supports in-memory query caching as per adaptive caching.

Supports in-memory caching of data: Yes for Azure SQL Data Warehouse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6831bf64-b00f-b234-b16e-d1bd42ebb77b
* Version Independent ID: 43bb3955-7d3a-c348-bde4-c3740e93c300
* Content: [Data warehousing in Microsoft Azure](https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/data-warehousing#feedback)
* Content Source: [docs/data-guide/relational-data/data-warehousing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/relational-data/data-warehousing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @jasonbruno88 - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.
