### ISSUE TITLE
Cannot use guid's for storage account names

### ISSUE THREAD

**Issue by arjenkrap** [MicrosoftDocs/architecture-center#1693]
As an suggestion for naming storage accounts the following sentence is used in this article:

`use a function to calculate a unique guid for naming storage accounts`

This is however not possible because Guid's in string form are 36 characters long (32 without dashes). The max length of storage account names is 24.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#feedback)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@arjenkrap Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@arjenkrap Fix is been merged with the document and will be available soon. Thank you for catching this.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
