### ISSUE TITLE
Workload managers 2 references to the same workload

### ISSUE THREAD

**Issue by AlexandreJean** [MicrosoftDocs/architecture-center#1695]
Hello,

I can notice in the workload managers, Altair is presented 2 times with : the bullet "PBS pro" and the bullet "Altair", maybe it will be more explicit to change or remove the bullet Altair ? 
As Altair is the owner of PBSpro.
Thanks,
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing#feedback)
* Content Source: [docs/topics/high-performance-computing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/topics/high-performance-computing.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@AlexandreJean Thanks for the feedback!

I guess the intention was to differentiate between the [open-source PBS Pro](https://www.pbspro.org/) and [Altair PBS Professional](https://www.pbsworks.com/PBSProduct.aspx?n=Altair-PBS-Professional&c=Overview-and-Capabilities) which comes with commercial support.

@MikeWasson Could you confirm?

**Comment by adamboeglin** [comment]
Given that they're essentially the same product with different licensing models, I don't think they need to be called out separately.

**Comment by PramodValavala-MSFT** [comment]
@adamboeglin Thanks for chiming in!

@AlexandreJean We are assigning this issue to update the doc as required.
