### ISSUE TITLE
Storage Container Name invalid characterset mentioned

### ISSUE THREAD

**Issue by mrmanpreetsingh** [MicrosoftDocs/architecture-center#1696]
As per the doc the valid characterset for Storage Container name is [0-9, a-z, A-Z and -] but the casing allowed is lowercase. Even when we create container only lowercase is allowed therefore valid characters should be [0-9, a-z and -]. Can you please check if it is required to be corrected. Thanks.

Link: https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#storage

Entity | Scope | Length | Casing | Valid Characters | Suggested Pattern | Example
-- | -- | -- | -- | -- | -- | --
Container name | Storage account | 3-63 | Lowercase | 0-9, a-z, A-Z and - | <context> | logs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#feedback)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@mrmanpreetsingh Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@mrmanpreetsingh Thanks for catching that! The same applies to [blob containers](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names), [queues](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-queues-and-metadata) and [file shares](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata).

We have worked up a PR to update the doc accordingly.
