### ISSUE TITLE
Batch Cost

### ISSUE THREAD

**Issue by Sam-SFO** [MicrosoftDocs/architecture-center#1697]
I am assuming you pay for Batch only when you use. It is Not explicitly mentioned. Is that correct?
Is there any other fixed cost involved with Batch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing)
* Content Source: [docs/topics/high-performance-computing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/topics/high-performance-computing.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@Sam-SFO There’s no charge for Batch itself, only the underlying compute and other resources consumed to run your batch jobs, including applicable software license costs. For compute, Cloud Services, Linux Virtual Machines, or Windows Virtual Machines can be utilized by Batch. The standard rates for compute apply and can be viewed below and software licensing costs for batch graphics and rendering are available below. In addition, Batch allows low-priority virtual machines (VMs) to be used. Reserved Virtual Machine Instances are available when using the Azure Batch Service in User subscription pool application mode.

You can check the pricing for Azure Batch [here](https://azure.microsoft.com/en-us/pricing/details/batch/).

**Comment by KetanChawda-MSFT** [comment]
@Sam-SFO Checking in to see if the above post helped answering your question.

**Comment by Sam-SFO** [comment]
Yes, but the documentation should be made more precise.
    On Sunday, August 11, 2019, 11:20:10 PM CDT, KetanChawda-MSFT <notifications@github.com> wrote:  
 
 
@Sam-SFO Checking in to see if the above post helped answering your question.

**Comment by KetanChawda-MSFT** [comment]
@Sam-SFO We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
