### ISSUE TITLE
Decisions regarding IaaS, PaaS, or hybrid are made during the assess phase to optimized control and execution. 

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/architecture-center#1699]
This sentence is difficult to understand linguistically. Are you suggesting that these decisions are made to deliver optimized control and optimized execution.
Or are you referring that these decisions are made to optimize the control and execution of future phases? (i.e. is it a typo)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218b42ff-1cf2-c31c-1a1a-59625eb9e09e
* Version Independent ID: ab742d17-9eba-2daa-c4fc-50b17a1e0eba
* Content: [Getting started with a cloud migration journey - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/getting-started/migrate)
* Content Source: [docs/cloud-adoption/getting-started/migrate.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/getting-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by DixitArora-MSFT** [comment]
Hi @eyast Thanks for reaching out. We will review and update as appropriate.

**Comment by doodlemania2** [comment]
This is great feedback, thank you! We'll look to get this clarified in an upcoming sprint.
