### ISSUE TITLE
Customer reference in the article

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/architecture-center#1700]
A customer reference to Coverdell in the article could possibly be replaced by links to other (many) case studies on the official MS case study sites, where so many different organizations have reached their fiscal outcomes and met their strategy by using the Cloud. Although Coverdell's reference is a good one, the article doe snot point out that it's a reference, and new readers might have the perception it's the only one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853378ad-ac67-59e4-fb6b-b8158da3b8e9
* Version Independent ID: a441f60f-03b7-7bb0-308b-40b73101b685
* Content: [Examples of fiscal outcomes - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/business-strategy/business-outcomes/fiscal-outcomes)
* Content Source: [docs/cloud-adoption/business-strategy/business-outcomes/fiscal-outcomes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/business-strategy/business-outcomes/fiscal-outcomes.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by DixitArora-MSFT** [comment]
Hi @eyast Thanks for reaching out. We will review and update as appropriate.

**Comment by doodlemania2** [comment]
@eyast, do you have additional examples from our case studies that you think would be good to highlight? URLs?

**Comment by BrianBlanchard** [comment]
Holding on reply from @eyast regarding additional examples prior to closing this issue.

**Comment by BrianBlanchard** [comment]
Closing due to lack of response. Will reopen, if a reply comes back from @eyast
