### ISSUE TITLE
Fortune 500 quote

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/architecture-center#1701]
the Fortune 500 quote might be revised? the list started in 1955, therefore would it be better to simply say:
As of 2015, only 57 companies were still in the Fortune 500 61 years  &lt;!&gt; after the first publication of the list  appeared in 1955 &lt;!&gt;?
In addition, the list of companies might not be necessarily related to agility and this could be a fallacy, since effectively Fortune tracks fiscal outcome

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f12999-c1cc-3996-4773-e22583299a75
* Version Independent ID: a1b8ac9e-565b-fa98-41af-a4f6e5fd92ce
* Content: [Examples of agility outcomes - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/business-strategy/business-outcomes/agility-outcomes)
* Content Source: [docs/cloud-adoption/business-strategy/business-outcomes/agility-outcomes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/business-strategy/business-outcomes/agility-outcomes.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by KetanChawda-MSFT** [comment]
@eyast Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
Thanks so much for this feedback! We'll look to clarify this in an upcoming sprint.
