### ISSUE TITLE
Reference needed

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/architecture-center#1702]
"Hosting datacenters around the world can consume more than 80 percent of an annual IT budget"
Could a reference be added to increase the credibility of the figure please? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce8b55e-8db7-a1c0-a0e8-7b3f93ad1553
* Version Independent ID: f9044c8e-8665-1f66-6ee5-6f2fd8febe86
* Content: [Examples of global reach outcomes - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/business-strategy/business-outcomes/reach-outcomes)
* Content Source: [docs/cloud-adoption/business-strategy/business-outcomes/reach-outcomes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/business-strategy/business-outcomes/reach-outcomes.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by KetanChawda-MSFT** [comment]
@eyast Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by BrianBlanchard** [comment]
Added the backlog for Cloud Adoption Framework
