### ISSUE TITLE
DRBC

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/architecture-center#1703]
I believe the accepted term is BCDR, where the mantra is to lead with Business Continuity first, then recovery from Disaster second

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfaf030-7934-c7fa-a30d-012567a679f5
* Version Independent ID: cf850417-6d1c-83f3-81c3-c01ad0bbd67e
* Content: [Examples of performance outcomes - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/business-strategy/business-outcomes/performance-outcomes)
* Content Source: [docs/cloud-adoption/business-strategy/business-outcomes/performance-outcomes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/business-strategy/business-outcomes/performance-outcomes.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by KetanChawda-MSFT** [comment]
@eyast Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@BrianBlanchard / @MikeWasson  can you please confirm on this request.

**Comment by doodlemania2** [comment]
Thanks so much for your feedback on this. We've made that change and hope to have it appear in an upcoming sprint.
