### ISSUE TITLE
Highlight that Helm in ACR is not GA yet.

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#1704]
Please, highlight that as of today - storing Helm Charts in Azure Container registry is still in preview.
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos
I would be very careful with preview features, because essentially - we can use it on our own risk and will not receive support from Microsoft if something goes wrong 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f4d213-3eb1-5b4c-aa67-116e8fa36f7d
* Version Independent ID: 18199b5a-8f57-6574-c795-7540199ae49a
* Content: [Building a CI/CD pipeline for microservices on Kubernetes](https://docs.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes)
* Content Source: [docs/microservices/ci-cd-kubernetes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/ci-cd-kubernetes.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by SychevIgor** [comment]
![image](https://user-images.githubusercontent.com/578954/62850552-e06bac00-bceb-11e9-890a-43de90ba767d.png)

**Comment by DixitArora-MSFT** [comment]
Hi @SychevIgor Thanks for reaching out. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@doodlemania2 Thanks for contributing to the doc improvement.
@SychevIgor PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
