### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by taromielnaz** [MicrosoftDocs/architecture-center#1709]
Could you put a comparison table for import/export service to Databox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e037b-a226-62cf-6e2b-2af8783b7add
* Version Independent ID: c666597e-52ae-ee51-474a-c4dd3a63941b
* Content: [Choosing a data transfer technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer)
* Content Source: [docs/data-guide/scenarios/data-transfer.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/data-transfer.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@taromielnaz Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
