### ISSUE TITLE
What is in the JWT token that is signed?  Examples please!

### ISSUE THREAD

**Issue by chadsowald** [MicrosoftDocs/architecture-center#1711]
Hi.  This page is pretty nice, but lacks a fundamental detail, how does one build that JWT token that gets signed by the certificate?  What specifically is inside of it?  Assume someone is familiar with JWT tokens, but doesn't know what precise values should be put into one before signing and sending to Azure AD to be authenticated.  Please add 1 or more examples of the JWT tokens!  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a61866-afea-6799-104f-6f2382f2c64e
* Version Independent ID: 5b590818-2cb9-62e3-ebe5-be9d0d020d24
* Content: [Use client assertion to get access tokens from Azure AD](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/client-assertion#feedback)
* Content Source: [docs/multitenant-identity/client-assertion.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/client-assertion.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @chadsowald Thanks for reaching out. We will review and update as appropriate.

**Comment by johnnycardy** [comment]
Example code can be found within the TailSpin [sample project](https://github.com/Azure-Samples/guidance-identity-management-for-multitenant-apps/blob/master/src/Tailspin.Surveys.Web/Security/AuthenticationContextExtensions.cs).
For better or worse, it abstracts away the JWT token specifics, using the `Microsoft.IdentityModel.Clients.ActiveDirectory` assembly.

**Comment by chadsowald** [comment]
@johnnycardy and @DixitArora-MSFT, thank you.  I really wanted specifics around the JWT token contents, not just C# code.  That wasn't the point, but thank you nonetheless.  I found someone else who had figured it out, so they could do client cert auth in PHP:

https://github.com/thephpleague/oauth2-client/issues/713#issuecomment-522747495

Please take a look at their comment and consider enhancing your docs to have the actual JWT contents/header/payload... not just example code that magically does it.

**Comment by absheik** [comment]
AB#160259 - Thanks for reporting - this issue is under review

**Comment by vit100** [comment]
According to https://tools.ietf.org/html/rfc7523, POST request doesn't include client_id in POST parameters.

Sample probably should be fixed - removed client_id
> &client_id=87df91dc-63de-4765-8701-b59cc8bd9e11
