### ISSUE TITLE
Handling exceptions > Capture exceptions and return a meaningful response to clients > DeleteCustomer - 400 may not be right one?

### ISSUE THREAD

**Issue by maulik-modi** [MicrosoftDocs/architecture-center#1712]
In Topic:Handling exceptions
Section:Capture exceptions and return a meaningful response to clients

Can you add an explanation of scenarios that could lead to BadRequest(Strings.CustomerNotDeleted)?

 // Remove the customer from the repository
        // The DeleteCustomer method returns true if the customer
        // was successfully deleted
        if (repository.DeleteCustomer(id))
        {
            // Return a response message with status code 204 (No Content)
            // To indicate that the operation was successful
            return StatusCode(HttpStatusCode.NoContent);
        }
        else
        {
            // Otherwise return a 400 (Bad Request) error response
            return BadRequest(Strings.CustomerNotDeleted);
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329fde76-a838-59c9-73f6-96424c03a6e0
* Version Independent ID: 203cd155-00c5-286b-96ce-5961c24c6273
* Content: [API implementation guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-implementation)
* Content Source: [docs/best-practices/api-implementation.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/api-implementation.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
That would depend on the implementation. The main point is to return an appropriate error code based on the type of failure.

**Comment by MikeWasson** [comment]
It's a made-up scenario for illustration, so it could be anything really. That said ... I agree it's hard to picture why this particular API would return 400. Something like 403 (not authorized) might be a better example.

**Comment by MikeWasson** [comment]
Closing this issue - let me know if you had any other questions - thx!
