### ISSUE TITLE
aka.ms short URL in excel template not working.

### ISSUE THREAD

**Issue by andresravinet** [MicrosoftDocs/architecture-center#1713]
In the business outcome template, there's an aka.ms short URL (https://aka.ms/CloudAdoption/BusinessOutcomes) and it's not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9004df-bad0-2610-6c64-7c56697e285e
* Version Independent ID: 74e9daed-bce4-694d-80b6-10ba226bda49
* Content: [What business outcomes are associated with transformation journeys? - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/business-strategy/business-outcomes/index#feedback)
* Content Source: [docs/cloud-adoption/business-strategy/business-outcomes/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/business-strategy/business-outcomes/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
Thanks for the feedback. This has been resolved.
