### ISSUE TITLE
Visio Files

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/architecture-center#1717]
Hi, could you please make the Visio files available for the decision trees? we could customize it for our organization requirements.  Many Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7178605-13d2-69fc-e80d-884b18cd80f4
* Version Independent ID: 6f7c2419-3acd-0391-6a1e-80e11f0fb570
* Content: [Azure readiness networking design decisions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/ready/considerations/network-decisions)
* Content Source: [docs/cloud-adoption/ready/considerations/network-decisions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/ready/considerations/network-decisions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by mike-urnun-msft** [comment]
@knssub Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by BrianBlanchard** [comment]
Great suggestion. Adding to our backlog to find the best approach to sharing those visio files.
