### ISSUE TITLE
No details on various entities, e.g. Logic Apps

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/architecture-center#1721]
The lists don't contain details on various entity types, e.g. Logic Apps, Integration Accounts, Integration Service Environments, On-Premise Data Gateways

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#feedback)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@steveculshaw Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
