### ISSUE TITLE
Missing code examples: CircuitBreakerStateStoreFactory ...

### ISSUE THREAD

**Issue by IjsConsulting** [MicrosoftDocs/architecture-center#1722]
The code provided does cover the whole solution, I'd like to see either the code for CircuitBreakerStateStoreFactory and ICircuitBreakerStateStore concrete class implementation, or a link to get the full solution. Without this, the example above makes partial sense. Also the variable, OpenToHalfOpenWaitTime , hasn't been defined in the CircuitBreaker class .. are we to guess what this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16660c68-2989-3b3b-21cb-1cf0d325070e
* Version Independent ID: e65d705e-3a0a-9ea9-382e-1ed25a704fb7
* Content: [Circuit Breaker pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker#feedback)
* Content Source: [docs/patterns/circuit-breaker.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/circuit-breaker.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@IjsConsulting Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!

**Comment by div78641** [comment]
What "further research" is necessary? Either you have the code available or you don't. 

It is disappointing that the example is not fully baked.

**Comment by guojianwei001** [comment]
When do you finish "further research"?

**Comment by ckittel** [comment]
Hey there @guojianwei001, @div78641, and @IjsConsulting,

We do not have an implementation of this at this time; the article is stand alone. The code illustrated can be used as part of your implementation of this cloud pattern.  I'm sure this isn't the news you were looking for; however, not all is lost. One of our awesome apps consultants, @mleziva, has taken this exact article and put together a [sample implementation using .net core](https://github.com/mleziva/cloudpatterns/tree/master/CloudPatterns/Patterns/CircuitBreaker) for customers to reference.  You can even see it running in action at <http://cloudpatterns.austinmleziva.com/circuit-breaker>.

Hopefully this helps you along on your journey.

**Comment by guojianwei001** [comment]
Hey @ckittel,
Cool! Thanks so much for your information. I didn't expect a reply that time. I had to search it everywhere, finnally I got one [java version](https://github.com/satishnaidu/CloudDesignPatterns/tree/master/src/main/java/com/sample/patterns/circuitbreaker)
I believe your reply will help more people. If possible, could we add the full code sample link at the bottom of [this article](https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker)? 
So thank you once again.
