### ISSUE TITLE
Azure Migrate scale numbers are off

### ISSUE THREAD

**Issue by DeanCefola** [MicrosoftDocs/architecture-center#1725]
Migrate at scale section in this document...here is a quick link 
https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-scale?lc=1033#migrate-at-scale

this doc shows the scale limits at 1500 VMs 
The latest version of Azure Migrate increased these limits greatly 
https://docs.microsoft.com/en-us/azure/migrate/scale-hyper-v-assessment#planning-limits  -  number should be 10,000
https://docs.microsoft.com/en-us/azure/migrate/scale-vmware-assessment#planning-limits  -  number should be 35,000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c905d31a-38b4-b935-8448-e0263ed72b28
* Version Independent ID: 3ce7c1f1-ff23-486b-a6b7-1d69964d1ef4
* Content: [Scale a migration to Azure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-scale?lc=1033)
* Content Source: [docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-scale.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by DixitArora-MSFT** [comment]
Hi @DeanCefola  Thanks for your feedback. We will review and update as appropriate.
