### ISSUE TITLE
Are the images accurate?

### ISSUE THREAD

**Issue by larryms** [MicrosoftDocs/architecture-center#1726]
The images on this page don't seem to flow logically with the associated text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf238dff-1a18-aec1-3886-33c4afc84706
* Version Independent ID: 17596f12-b425-626f-c3f2-f00df75e6dc7
* Content: [Establish team structures - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/organization/organization-structures)
* Content Source: [docs/cloud-adoption/organization/organization-structures.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/organization/organization-structures.md)
* Service: **cloud-adoption-framework**
* Sub-service: **organize**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by DixitArora-MSFT** [comment]
Hi @larryms Thanks for your reaching out. We will review and update as appropriate.

**Comment by doodlemania2** [comment]
Thanks for this feedback. We have an upcoming update to this section that should fix that up!
