### ISSUE TITLE
large scaler

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/architecture-center#1741]
i might be mistaken, sorry - but the intro says "large scaler" when i think the intent was to say "larger scale"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab154f6-58af-5834-ae23-9824b21541e0
* Version Independent ID: bb8941b3-59fd-fae3-0cbb-f8c0307de62e
* Content: [Batch scoring with R Models on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/batch-scoring-r-models)
* Content Source: [docs/reference-architectures/ai/batch-scoring-R-models.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/batch-scoring-R-models.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @eyast Thank you for your feedback! We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@eyast I have created the PR for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
