### ISSUE TITLE
Typo in flowchart - Azure "Font" Door

### ISSUE THREAD

**Issue by phealy** [MicrosoftDocs/architecture-center#1743]
There's a typo in the 3rd blue box from the bottom - the AKS path. It references Azure "Font" Door instead of Front Door.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#feedback)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @sharad4u
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@phealy Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
Fixed!
