### ISSUE TITLE
Disk metrics are 0.0

### ISSUE THREAD

**Issue by tessem** [MicrosoftDocs/architecture-center#1744]
Seems like any disk metric has value of zero (0). Is this a known issue, or may it be related to using datastorage version 2 ?
The following gives no records:
SparkMetric_CL | where  name_s  contains "filesystem"  | where value_d &gt; 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@tessem Thank you for your question! We will review and provide an update as appropriate.

**Comment by absheik** [comment]
AB#160257 - Thanks for reporting - this issue is under review

**Comment by jocontr** [comment]
Closing on our end due to a no repro.

Could you provide more details if issues persist? For your reference I am providing a link to various Spark metrics -> https://spark.apache.org/docs/latest/monitoring.html
