### ISSUE TITLE
Consider adding the new HPC instances to this page (i.e. HB and HC) 

### ISSUE THREAD

**Issue by JonShelley** [MicrosoftDocs/architecture-center#1746]
Looking at https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing#networking we refer to A8, A9, H16r, and H16mr. Should we include HB and HC in that section as well or should we remove reference to the old instances and replace it with a link to a page that shows all HPC instances that have InfiniBand connectivity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing#networking)
* Content Source: [docs/topics/high-performance-computing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/topics/high-performance-computing.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @JonShelley Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
