### ISSUE TITLE
consider adding more missing services 

### ISSUE THREAD

**Issue by pbous123** [MicrosoftDocs/architecture-center#1747]
please consider adding missing services such as Azure Site Recovery, Log analytics, and network watcher in the Aws comparison https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services

**Comment by DixitArora-MSFT** [comment]
Hi @pbous123 Thank you for your feedback! We will review and update as appropriate.

**Comment by doodlemania2** [comment]
Thank you! We've taken this item to our backlog and hope to have some changes to include additional capabilities soon.
