### ISSUE TITLE
Your chart is misleading - with Front Door TLS 1.0 and 1.1 cannot be disabled

### ISSUE THREAD

**Issue by alvipeo** [MicrosoftDocs/architecture-center#1748]
So the only option is to use Traffic Manager. And disabling TLS 1.0 and 1.1 is PCI requirement. So for serious purposes Front Door is useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#feedback)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @sharad4u
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@alvipeo Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@doodlemania2 any thoughts here?

**Comment by doodlemania2** [comment]
This is okay to close as disabling 1.0 and 1.1 should come out in just a few weeks.

**Comment by alvipeo** [comment]
so, any updates on this? 

good, you closed it...

**Comment by doodlemania2** [comment]
I'm hearing any day now @alvipeo :)

**Comment by helizabethwhite** [comment]
@doodlemania2 has this been released yet?

**Comment by alvipeo** [comment]
I believe it's any hour now :))

**Comment by doodlemania2** [comment]
This is available now via API: https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontendendpoints/enablehttps#minimumtlsversion
Portal support TBD
