### ISSUE TITLE
Implementing an NSG for DMZ ("Public DMZ out")

### ISSUE THREAD

**Issue by osartavi** [MicrosoftDocs/architecture-center#1751]
Hi,
I am part of CSS and I would like you to consider the possibility of adding a clarification in the document. The diagram in our documentation shows that an NSG could/should be deployed for a trusted DMZ subnet handling outgoing internet traffic (as it is the case for "Public DMZ out")  

![Capture](https://user-images.githubusercontent.com/47437304/64050289-c972e980-cb34-11e9-88ef-5cf2fc1dd779.JPG)

While the document states that customer should ensure the right configuration for the NSG, no rule configuration sample is provided for such case. In a scenario like this an NSG placed in a subnet like  "Public DMZ out" will require a really specific configuration **(Allow "Internet" tag, Any(*) or "0.0.0.0/0" in the NSG inbound rules as "Destination Address")**. This configuration will be always true for subnets of this kind.

It is true that most customer opt for not using NSGs in a "trusted subnet" like this, however; it is not specified anywhere else that this should be the case. I understand that this could be considered as a "logical" assumption since the NSG should be configured based in the destination address of the IP header, nonetheless, this rule will be a constant for all subnets achieving the same function, therefore handling this as a special requirement might be beneficial. 

I consider adding a little note might be beneficial to avoid confusion for our customer in the future.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132f3909-1efc-e58a-7d58-8d378046f43a
* Version Independent ID: c94ad8d8-49c8-f47d-cf33-956f85b10ab1
* Content: [Implement a DMZ between Azure and the Internet - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@osartavi Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by osartavi** [comment]
Hi @KetanChawda-MSFT

Thank you for your reply. Please find the reference for the main document below:
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz

**Comment by doodlemania2** [comment]
We've added this request to our existing work on refining this document and hope to post an update soon!
