### ISSUE TITLE
Should 'date' be 'data'? 

### ISSUE THREAD

**Issue by ptuton** [MicrosoftDocs/architecture-center#1754]
Should the following sentence, "Optimizes replication date by using caching, compression, and encryption", read, "Optimizes replication data by using caching, compression, and encryption" ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524015bb-49a9-3291-a9b8-001908ebb3ec
* Version Independent ID: adab2d2a-d5cd-2b4c-cbef-ce8b88bf767c
* Content: [Rehost an on-premises app by migrating to Azure VMs and Azure SQL Database Managed Instance - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-rehost-vm-sql-managed-instance)
* Content Source: [docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-rehost-vm-sql-managed-instance.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-rehost-vm-sql-managed-instance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by ptuton** [comment]
Additionally for "Sends replication date to Azure Storage."

**Comment by DixitArora-MSFT** [comment]
@ptuton Thanks for your feedback. We will review and update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@ptuton Thanks you for pointing this out! I have created a PR to correct the typo's you mentioned. The changes will be reflected in next 24hrs.

**Comment by KetanChawda-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
