### ISSUE TITLE
ANF needs mentioning here

### ISSUE THREAD

**Issue by mkiernan** [MicrosoftDocs/architecture-center#1756]
It seems rather odd that Azure NetApp Files (ANF) is not mentioned in this page at all, particularly since it's being used very commonly in Azure HPC deployments now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing)
* Content Source: [docs/topics/high-performance-computing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/topics/high-performance-computing.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by MicahMcKittrick-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
