### ISSUE TITLE
Difference in resource type naming prefix or suffix

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/architecture-center#1757]
This document recommends resource type prefixes, yet another page (https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions) has the resource types as suffixes

Consistency would be nice  :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe077f3-402e-b5f8-5f7c-bb47f2de8200
* Version Independent ID: ce789235-4a85-1262-4502-9b47f673dcad
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/ready/considerations/name-and-tag)
* Content Source: [docs/cloud-adoption/ready/considerations/name-and-tag.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/ready/considerations/name-and-tag.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by KetanChawda-MSFT** [comment]
@steveculshaw Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
We've taken this item to our internal backlog for further research and will update as necessary!
