### ISSUE TITLE
Azure ADDS vis ADDS server?

### ISSUE THREAD

**Issue by theheatDK** [MicrosoftDocs/architecture-center#1759]
Hi,
The diagram is displaying two VMs running ADDS. Are any particular reason for not using the AADDS PaaS instead? I would assume that if the PaaS service is working it would be the natural first choice :-)
Regards Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implement a hub-spoke network topology - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @theheatDK Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@theheatDK The architecture shows how to extend Active Directory services from your on-premises data center to Azure. It basically facilitate management of assets moved to Azure from your on-premises network that depend on ADDS. Please let me know if I misunderstood the question.

**Comment by DixitArora-MSFT** [comment]
@theheatDK Just following up again in case missed the previous communication.

**Comment by doodlemania2** [comment]
Agreed - there should be additional docs that talk about how to leverage (and when) AADDS instead of AADS, but this particular article is focused on the hybrid approach. I think we can close this one out as a request to have a decision guide on when to choose one over the other. Copied to internal backlog!

**Comment by theheatDK** [comment]
Thanks @DixitArora-MSFT @doodlemania2 
I was confused since for me hybrid does not necessary mean that you install ADDS on VMs in Azure. Extending you on-premise ADDS by syncing it to an AADDS should be just as fine, and “equally” hybrid.
Looking forward to the decision guide :-)
Regards Peter

**Comment by doodlemania2** [comment]
That's a great point - we'll make sure to clarify that in an upcoming DG!
