### ISSUE TITLE
Virtual Network Peering Name?

### ISSUE THREAD

**Issue by theheatDK** [MicrosoftDocs/architecture-center#1764]
Hi,
It would be helpful with a standard for Virtual Network Peering Names. Any plans? :-)
Regards Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MicahMcKittrick-MSFT** [comment]
Thanks for the question! We are investigating and will update you shortly.

**Comment by doodlemania2** [comment]
Added to our list for updates which are in flight! Thanks so much @theheatDK for the suggestion. Update coming soon we hope!
