### ISSUE TITLE
Azure Data Lake Storage doesn't have a valid alternative

### ISSUE THREAD

**Issue by MySelfSivaKrishna** [MicrosoftDocs/architecture-center#1766]
Can you provide valid alternative for azure data lake storage in aws environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by MicahMcKittrick-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by doodlemania2** [comment]
We're currently working on this doc and have added it to the list of things to update. We hope to have changes out soon. Stay tuned!
