### ISSUE TITLE
AKS supports autoscaling - please correct document

### ISSUE THREAD

**Issue by qluo88** [MicrosoftDocs/architecture-center#1767]
The statement of AKS doe not support autoscaling need to updated. Please see AKS document on autoscaling.  https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbd9d8a-e443-aeab-cdf1-1c9c8858746c
* Version Independent ID: 5a0980f5-b246-0865-6f06-aa875f87a5ce
* Content: [Criteria for choosing an Azure compute service - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-comparison#feedback)
* Content Source: [docs/guide/technology-choices/compute-comparison.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-comparison.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @qluo88 - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
@qluo88 Thanks. Cluster autoscale is currently in preview so autoscale support is provided "as-is" and "as available"

**Comment by doodlemania2** [comment]
Yeah, we'd certainly update that once it goes to GA. Thanks for the note!
