### ISSUE TITLE
Excellent Article - Blurred / Unclear Images 

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/architecture-center#1768]
Excellent article, very crisp and super useful guidance. However, the images are not clear, could be due to the font used and also the image quality. Could you please upload better images? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e200d2-2d51-4a8a-d8ef-4c03890c42d0
* Version Independent ID: 12a83d63-c2cb-91ad-a3c6-b078d23d8a9d
* Content: [Monitoring and diagnostics guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/monitoring)
* Content Source: [docs/best-practices/monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/monitoring.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @knssub Thanks for your feedback. We will review and update as appropriate.
