### ISSUE TITLE
Usability improvement

### ISSUE THREAD

**Issue by VeryKross** [MicrosoftDocs/architecture-center#1770]
This is a great resource that I think could be improved if each of the decision endpoints (blue boxes) were also links to more information, perhaps the info landing page for each of those services (or maybe something more contextual for someone making this sort of decision). For many people, seeing that the decision tree suggests "Container Instances" is good … but leads to the question of "what's that"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Decision tree for Azure compute services - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#flowchart)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks - this is a great suggestion, but unfortunately the Microsoft docs platform doesn't support image maps or clickable SVG files. That said, it would be possible to add a "further resources" section.

**Comment by VeryKross** [comment]
Thanks for the quick feedback. Would it be possible to have a “More Info” link right below the SVG graphic? That would still keep the link in context. 
    	

    	Get Outlook for iOS
    
  



On Thu, Sep 5, 2019 at 12:22 PM -0400, "Mike Wasson" <notifications@github.com> wrote:












Thanks - this is a great suggestion, but unfortunately the Microsoft docs platform doesn't support image maps or clickable SVG files. That said, it would be possible to add a "further resources" section.

**Comment by absheik** [comment]
AB#160256 - Thanks for reporting - this issue is under review

**Comment by MikeWasson** [comment]
@VeryKross Hey - based on this feedback (and others) we consolidated several articles into one, and this article now includes links to overviews for all of the compute services mentioned. Hopefully this helps!

**Comment by Ericgre** [comment]
#please-close
