### ISSUE TITLE
Linguistic Analysis API

### ISSUE THREAD

**Issue by krusejan** [MicrosoftDocs/architecture-center#1771]
This Cognitive Service does not exist (anymore), please update the documentation accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a51dd9-65b7-5039-06d0-d096ad51d0bb
* Version Independent ID: 9c2c99ed-8d17-7865-e680-2107b7f0ebf1
* Content: [Choosing a natural language processing technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/natural-language-processing#feedback)
* Content Source: [docs/data-guide/technology-choices/natural-language-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/natural-language-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @krusejan Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@krusejan We still have Azure Cognitive Services. The catalog of services within Azure Cognitive Services can be categorized into five main pillars - Vision, Speech, Language, Web Search, and Decision.
More detail can be found here https://docs.microsoft.com/en-us/azure/cognitive-services/welcome

Please let me know if I misunderstood the question. So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
