### ISSUE TITLE
Mismatch between Architecture Guide and Navigation Pane

### ISSUE THREAD

**Issue by JeffreyFudge** [MicrosoftDocs/architecture-center#1778]
Within the Azure Architecture Guide under "Technology Choices", the two items listed are "choosing a compute service" and "choosing a data store".   However, in the navigation pane under "Technology Choices", the two items listed are "choosing a compute service" and "choosing a load balancing service".

Thus each section (navigation and the main page) is missing one of the three technology choices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/#feedback)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@JeffreyFudge Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson Could you please take a look at this ?

**Comment by absheik** [comment]
AB#160255 - Thanks for reporting - this issue is under review

**Comment by MikeWasson** [comment]
Moved "choosing a data store" back to that node in TOC.
