### ISSUE TITLE
Mismatch between Content Page and Navigation Pane

### ISSUE THREAD

**Issue by JeffreyFudge** [MicrosoftDocs/architecture-center#1779]
The "Pillars of Software Quality" have some inconsistencies between the navigation pane (4 pillars) and the content pane (5 pillars).  It appears that there are actually 6 uniquely named quality pillars.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Pillars of software quality - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/pillars#feedback)
* Content Source: [docs/guide/pillars.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/pillars.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
AB#160255 - Thanks for reporting - this issue is under review

**Comment by MikeWasson** [comment]
Fixed, update will be published tomorrow.
