### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/architecture-center#1782]
the text reads "Console can get both a discount, and prioritized capacity."  I believe it should refers to "Contoso", not Console

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c99f2c-3d30-6c23-7559-de463464e52a
* Version Independent ID: bc59e60a-7a1d-b31a-a173-8fb1dbde0a61
* Content: [Deploy a migration infrastructure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure)
* Content Source: [docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-best-practices/contoso-migration-infrastructure.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by DixitArora-MSFT** [comment]
Hi @eyast Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@eyast PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
