### ISSUE TITLE
Please update the information in "Use Azure Backup to create cross region backups that are application consistent" 

### ISSUE THREAD

**Issue by v-hakob** [MicrosoftDocs/architecture-center#1783]
According to the backup team, with the azure backup service, users can only restore VM’s/Disks to the same region as the backed up VM. So even though they may be using geo-replicated storage, they cannot leverage that to initiate a restore in the partner region. 
It contradicts the information in this document. Could you please update accordingly? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31c85c7-c25d-897f-e52d-789f7306457b
* Version Independent ID: 969106a5-df35-afef-5afc-96a26c970f44
* Content: [Recover from loss of an Azure region](https://docs.microsoft.com/en-us/azure/architecture/resiliency/recovery-loss-azure-region#feedback)
* Content Source: [docs/resiliency/recovery-loss-azure-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/resiliency/recovery-loss-azure-region.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @adamglick
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@v-hakob Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by absheik** [comment]
AB#160254 - Thanks for reporting - this issue is under review

**Comment by MikeWasson** [comment]
GRS is the recommend option (see [here](https://docs.microsoft.com/en-us/azure/backup/backup-overview#why-use-azure-backup)). GRS storage becomes available if Microsoft initiates a failover.

**Comment by absheik** [comment]
closing per previous comment
