### ISSUE TITLE
aka.ms links broken

### ISSUE THREAD

**Issue by piazzaandrea** [MicrosoftDocs/architecture-center#1786]
3 of the 4 links at the paragraph level are broken, they are using aka.ms short URLs which do not resolve
Page: https://docs.microsoft.com/en-us/azure/architecture/vdc/
Broken links: 

- Azure Virtual Datacenter: Concepts
- Azure Virtual Datacenter: Lift and Shift Guide 
- Azure Virtual Datacenter: Presentation Deck

**Comment by PramodValavala-MSFT** [comment]
@piazzaandrea Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by a-amalaa** [comment]
I think this was mistakenly assigned to me.

**Comment by MikeWasson** [comment]
@a-amalaa Yeah, sorry - fat fingered it 😺 Please ignore

**Comment by absheik** [comment]
AB#160248 - Thanks for reporting - this issue is under review

**Comment by TheGitHubBro** [comment]
Issue resolved.
