### ISSUE TITLE
Needs high-level overview of how permissions are granted to VMs (EC2 Instance Role equivalent)

### ISSUE THREAD

**Issue by eriksw** [MicrosoftDocs/architecture-center#1787]
Coming from AWS, I'm used to creating a role, attaching specific policies to that role, and then attaching that role to VM instances I create so that software running on those VMs has the desired access.

This page could benefit from a brief description of what the equivalent moving parts are in Azure's security model. I clicked on "Getting started with Microsoft Azure security" and that took me to a [documentation hub](https://docs.microsoft.com/en-us/azure/security/) (not a getting started guide at all!).

None of the things on that page are obviously relevant as starting points for the question "how do I give VM 001 read-only access to storage account foo, and VM 002 read/write access to storage accounts foo and bar?"

See also: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4388

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d100d43f-d48a-3d97-1aea-7a5409fdccc8
* Version Independent ID: 568dcd88-b93c-1d41-44d0-8643dd057a33
* Content: [Azure for Amazon Web Services (AWS) Professionals - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/#feedback)
* Content Source: [docs/aws-professional/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @eriksw Thanks for reaching out. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@eriksw Role-based access control (RBAC) is a system that provides fine-grained access management of Azure resources. Using RBAC, you can segregate duties within your team and grant only the amount of access to users that they need to perform their jobs.

Here are some examples of what you can do with RBAC:

- Allow one user to manage virtual machines in a subscription and another user to manage virtual networks
- Allow a DBA group to manage SQL databases in a subscription
- Allow a user to manage all resources in a resource group, such as virtual machines, websites, and subnets
- Allow an application to access all resources in a resource group

For more information, follow the documentation.  
https://docs.microsoft.com/en-us/azure/role-based-access-control/
https://docs.microsoft.com/en-us/azure/role-based-access-control/overview

**Comment by eriksw** [comment]
@DixitArora-MSFT No part of my question concerned granting access to users. My question/concern was about granting RBAC permissions _to VMs_ (not people! not users!) so that _software running on that VM_ has the desired access.

I know _now_ that the rough equivalent to an "Instance Role" ("Instance Profile" technically, but nobody uses that term) in AWS is a "user-assigned managed identity" in Azure, but despite that being a pretty fundamental thing to do (I have a thing and I want _that thing_ to have access to certain Azure resources), it was nearly impossible to discover in Azure's documentation. I was only pointed in that direction when I asked in a chat with the team of sales people working on my account.

The mention of managed identities in the "What is RBAC?" overview is way too buried and easy to miss: this is something _extremely fundamental_ to running stuff on EC2 and as such should have attention drawn to it in the "Azure for Amazon Web Services (AWS) Professionals" page, because the word anyone coming from EC2/AWS would know for the concept ("Role") has a different meaning in Azure's RBAC model that makes it nearly impossible to discover via search.

**Comment by doodlemania2** [comment]
This is excellent feedback, thank you so much @eriksw  - we've taken this to our internal backlog and updates will be forthcoming. You'll see a note posted to this issue when that update lands. We'll close it here for now.

**Comment by ritssoft** [comment]
Just wondering if someone has answer to this question yet? This seems to be very valid question and I couldn't find any explanation to it.

**Comment by doodlemania2** [comment]
The best thing we have that can talk about this is Managed Identity or Assigned Identity. Hopefully that helps?!
