### ISSUE TITLE
VSDX file download for diagram

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/architecture-center#1790]
Please provide a VSDX file download for the SVG diagram as you do for the other 3 reference architectures for web apps, https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/#web-applications.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df354e21-f263-30a9-1a5c-1460f2bf16a9
* Version Independent ID: 73d2f19b-00a0-fe4d-7042-15d27f586565
* Content: [Web application monitoring on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/app-monitoring)
* Content Source: [docs/reference-architectures/app-service-web-app/app-monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/app-monitoring.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @softwarecraft - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by absheik** [comment]
AB#160245 - Thanks for reporting - this issue is under review

**Comment by absheik** [comment]
@softwarecraft , you could download the image (righ click, save image as) as an SVG and then pull in to Visio on your end.
