### ISSUE TITLE
Operate vs. Manage

### ISSUE THREAD

**Issue by nickmoss99** [MicrosoftDocs/architecture-center#1791]
This may sound like splitting hairs, but I believe it is important: On this page, you introduce the "Manage" section, but refer to the 5 Operational Disciplines.  The current organization is:
- Operate
   -- Govern (includes 5 Governance Disciplines)
   -- Organize
   -- Manage (includes 5 Operations Disciplines)

Wouldn't it make more sense as:
- Manage
   -- Govern (includes 5 Governance Disciplines)
   -- Organize
   -- Operate (includes 5 Operations Disciplines)

Manage is a much broader term and it can encompass the (Govern, Organize, and Operate) much better.

As an MCS Solutions Architect, I tell my customers that Governance provides the guard rails, Operations is how we behave within the guard rails... the proposed organization uses these components as complimentary vs. governance being subordinate to Ops. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e7d57c3-996d-fa1f-e3d4-3f25c4fe1ad2
* Version Independent ID: 1a6428b3-839d-0bc8-eac3-6d847219a508
* Content: [Intro to the operational management - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/operations/)
* Content Source: [docs/cloud-adoption/operations/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/operations/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
@nickmoss99 Great feedback. 
This has been a strong debate internal to the CAF LT.
I'm going to close this thread but pull you into the internal conversation. I'd like to get additional feedback & ask you to review some of the new guidance we are pulling together for Ignite. It might address your feedback.

**Comment by nickmoss99** [comment]
Awesome!

@Fouad Rachkidi<mailto:Fouad.Rachkidi@microsoft.com> and I are building out an MCS engagement based on the 5 Governance Disciplines, and would like to focus on Operations next.

-Nick
