### ISSUE TITLE
Wrong visio diagram referenced

### ISSUE THREAD

**Issue by rickpeters** [MicrosoftDocs/architecture-center#1793]
The visio file of the diagram referenced is not for this architecture but for the normal hub-spoke?

regards,
Rick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@rickpeters Thanks for the feedback! Though the name of the file seems wrong, looks like its the right file for this doc but the link in the [base hub spoke doc](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke) points to the same visio file which is incorrect.

**Comment by rickpeters** [comment]
@PramodValavala-MSFT that could be, however the visio I get shows the toplogy for normal hub-spoke and not the version with shared services (https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services)

**Comment by PramodValavala-MSFT** [comment]
@rickpeters I took another look and turned out both the diagrams are in the same file. You should tabs at the bottom for each.

![image](https://user-images.githubusercontent.com/43602528/65611241-2183fb00-dfd0-11e9-8e5d-2dc1425bbbbc.png)

**Comment by PramodValavala-MSFT** [comment]
@rickpeters Just following up here... Hope my previous comment clears things up.

**Comment by rickpeters** [comment]
Yes it did. I tried to import the file in draw.io which doesn’t have support for this. Since I don’t have Visio I have to find another program to extract the second tab. Thanks for clearing this up
