### ISSUE TITLE
Formatting: Missing or incorrect space character

### ISSUE THREAD

**Issue by sammcj** [MicrosoftDocs/architecture-center#1800]
Section: Cloud Service

- Currently reads: `Web or worker roles are unexpectedlybeing shut down`
- Should read: `Web or worker roles are unexpectedly being shut down`

It looks like the character between the words `unexpectedly` and `being` is not a standard space character, giving the illusion there is a space between the words in the markdown source, however when the page is rentered the words appear concatenated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b1bb22b-9a56-0cbd-36c5-5f31d571900a
* Version Independent ID: 6a5b36aa-c051-c519-d6cf-61c77c3acb48
* Content: [Failure mode analysis](https://docs.microsoft.com/en-us/azure/architecture/resiliency/failure-mode-analysis#feedback)
* Content Source: [docs/resiliency/failure-mode-analysis.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/resiliency/failure-mode-analysis.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @sammcj Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@sammcj PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
