### ISSUE TITLE
AKS supports auto-scaling

### ISSUE THREAD

**Issue by benc-uk** [MicrosoftDocs/architecture-center#1803]
Both the Horizontal Pod Autoscaler and the Cluster Autoscaler are supported in AKS
https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbd9d8a-e443-aeab-cdf1-1c9c8858746c
* Version Independent ID: 5a0980f5-b246-0865-6f06-aa875f87a5ce
* Content: [Criteria for choosing an Azure compute service - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-comparison)
* Content Source: [docs/guide/technology-choices/compute-comparison.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-comparison.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@benc-uk Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson  Any thoughts here?

**Comment by MikeWasson** [comment]
Yes - I'll update the doc. Thanks for opening this issue, @benc-uk 😺
