### ISSUE TITLE
link is not working 

### ISSUE THREAD

**Issue by jmertens1** [MicrosoftDocs/architecture-center#1805]
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/training-with-deep-learning/tensorboard/tensorboard.ipynb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650239f8-0c0f-aeca-a8ff-f74a03b15e61
* Version Independent ID: 3bbf5d1a-0be8-e8a9-318b-71dfcdc336bf
* Content: [Distributed training of deep learning models on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/training-deep-learning#feedback)
* Content Source: [docs/reference-architectures/ai/training-deep-learning.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/training-deep-learning.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @msalvaris
* Microsoft Alias: **pnp**

**Comment by msalvaris** [comment]
Thanks for reporting. Will look into it.

**Comment by DixitArora-MSFT** [comment]
@msalvaris Any updates on this ?

**Comment by absheik** [comment]
AB#160242 - Thanks for reporting - this issue is under review

**Comment by ckittel** [comment]
@jmertens1, thanks for pointing this out.  The link has been updated.
