### ISSUE TITLE
The visio should show the SPA app also serverless

### ISSUE THREAD

**Issue by ashbham** [MicrosoftDocs/architecture-center#1806]
Would it be possible to change the visio diagram here - https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app so that the SPA web app is also depicted as Serverless. That way the end to end architecture would be Serverless and Azure native.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524d1f97-ce37-f9ac-cf05-d33665eb34df
* Version Independent ID: fe4cc63f-a4b1-c30e-f39f-f4c3de1c57be
* Content: [Serverless web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app)
* Content Source: [docs/reference-architectures/serverless/web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/serverless/web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@ashbham Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson any thoughts ?

**Comment by MikeWasson** [comment]
Hi @ashbham - The SPA app is serverless, because it pulls static files from CDN. There's no server-side rendering. Do you have a suggestion for how to make that more clear in the diagram?

**Comment by KetanChawda-MSFT** [comment]
@ashbham Did you get a chance to look the last post ?

**Comment by KetanChawda-MSFT** [comment]
@ashbham Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
