### ISSUE TITLE
What happened to the Azure Data lake?

### ISSUE THREAD

**Issue by sy-huss** [MicrosoftDocs/architecture-center#1807]
The Azure Data Lake as an Analytical Data Store was mentioned in the Overview section, yet it has been omitted here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e643be6d-22a2-2b91-c370-edf83d694efe
* Version Independent ID: 770f2e51-9c53-e5ca-1107-9577369b15a6
* Content: [Choosing an analytical data store](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analytical-data-stores)
* Content Source: [docs/data-guide/technology-choices/analytical-data-stores.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/analytical-data-stores.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @sy-huss  Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@sy-huss It is mentioned in the Batch Processing https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing

**Comment by DixitArora-MSFT** [comment]
@sy-huss For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by ryancrawcour** [comment]
i agree with OP. Azure Data Lake is a store for analytical data and should be included in this comparison. including it only in "batch processing" is not the correct messaging.
