### ISSUE TITLE
Is Service Bus a relevant option for real-time ingestion?

### ISSUE THREAD

**Issue by MithunChopda** [MicrosoftDocs/architecture-center#1809]
Service Bus acts as Message Broker and can be used to ingest messages. Is there a reason why it has not been considered as an alternative in the comparison matrix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc25fa01-4939-49b8-2e56-fb2cd8f0ccb1
* Version Independent ID: c4815a00-938c-7f7b-67a5-c16a78871b4a
* Content: [Choosing a real-time message ingestion technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/real-time-ingestion#feedback)
* Content Source: [docs/data-guide/technology-choices/real-time-ingestion.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/real-time-ingestion.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@MithunChopda Service Bus is designed to be a reliable message broker especially useful in [enterprise](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/queues-events) and [event-driven](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/event-driven) architectures.

[This table](https://docs.microsoft.com/en-in/azure/event-grid/compare-messaging-services?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-in%2Fazure%2Fservice-bus-messaging%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-in%2Fazure%2Fbread%2Ftoc.json#comparison-of-services) covers the differences between Service Bus, Event Hubs and Event Grid. Here is the same for reference

| Service | Purpose | Type | When to use |
| ------- | ------- | ---- | ----------- |
| Event Grid | Reactive programming | Event distribution (discrete) | React to status changes |
| Event Hubs | Big data pipeline | Event streaming (series) | Telemetry and distributed data streaming |
| Service Bus | High-value enterprise messaging | Message | Order processing and financial transactions |

**Comment by MithunChopda** [comment]
Thank you for your response @PramodValavala
I had read this comparison earlier. My point was this article talks about "Message Ingestion". EventHubs by design are aimed at ingesting Events though they can be used for other scenarios. Whereas Service Bus being aimed at Message ingestion, it has been left out in this article.

**Comment by bytemech** [comment]
I had the exact same thought when reading this article. In implementation scenarios I've seen more Service Buses than Event Hubs for no other reason than they are designed to be a reliable message service.

**Comment by PramodValavala-MSFT** [comment]
@MithunChopda @bytemech The Message Ingestion discussed in this document is for massive scales of data ingestion ranging in the 100K to millions of events. This is especially needed in scenarios involving IOT devices.

Service Bus has lots of additional features which are great for enterprise integration scenarios but when you need to ingest large volumes of data, services like Azure Events Hubs are the way to go.

Here are [some benchmarks](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dedicated-overview#what-can-i-achieve-with-a-cluster) in the official docs for Azure Event Hubs Dedicated.

**Comment by PramodValavala-MSFT** [comment]
@MithunChopda @bytemech Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@MithunChopda @bytemech Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by MithunChopda** [comment]
Thank you @PramodValavala-MSFT for the follow up and closing this.
I got the sense it was about scale. It would be great if the article clarifies this aspect probably using a Note section. Thanks again.
