### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by suterma** [MicrosoftDocs/architecture-center#1812]
Nice overview!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bde15d-d343-b84d-b77f-55b8e3f12638
* Version Independent ID: 9d35a3eb-707b-47f6-68bc-3f22fee4c78c
* Content: [Time series data](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/time-series#feedback)
* Content Source: [docs/data-guide/scenarios/time-series.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/time-series.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @suterma Thanks for your feedback. Just checking if you have any question or query related to this article/doc ?

**Comment by suterma** [comment]
No, its all fine!Sent with my PhoneAm 15.10.2019 04:56 schrieb DixitArora-MSFT <notifications@github.com>:Hi @suterma Thanks for your feedback. Just checking if you have any question or query related to this article/doc ?

**Comment by DixitArora-MSFT** [comment]
Hi @suterma So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
