### ISSUE TITLE
KeyVault does not accept numbers as first character 

### ISSUE THREAD

**Issue by ebrucucen** [MicrosoftDocs/architecture-center#1814]
KeyVault section does not include the restriction it can't handle number as first character in name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming#feedback)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@ebrucucen Thanks for catching that! We have worked up a PR to update the doc accordingly.
