### ISSUE TITLE
Missing details about having multiple subscriptions / vnets

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/architecture-center#1817]
MSFT still positions subscriptions to be one of the scale units and even recommends it down at the application or business group level (e.g. https://azure.microsoft.com/en-us/blog/organizing-subscriptions-and-resource-groups-within-the-enterprise/).  This structure then forces you into having many virtual networks.  Please add more realistic examples of how you would structure a network architecture across a global organization with multiple subscriptions (and therefore vnets) across multiple azure regions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec640d8-1064-c083-4313-5e8c23fbc2cf
* Version Independent ID: 5f7c63ca-7ab2-9129-4c34-191286e67af1
* Content: [Connect an on-premises network to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute-vpn-failover)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@danmyhre For connectivity between VNETs, [VNET Peering](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview) is the feature that links them together.

This is mentioned in the [Azure Enterprise Scaffold doc](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/azure-scaffold) (under [Core Network](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/azure-scaffold#core-network)) that is referenced in the link that you've shared.

**Comment by danmyhre** [comment]
Right, so what I suggesting is that more realistic large enterprise examples be added to the detailed network topology design documentation.  That is is what is missing.  Get into the details about remote gateways, transit networks, UDRs, etc, etc

**Comment by PramodValavala-MSFT** [comment]
@danmyhre Thanks for the feedback! We are assigning this issue to the content author for further review.

**Comment by absheik** [comment]
AB#160241 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
For the most part, this is recommended best practices. There have been some updates and this material stays accurate in CAF: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/standard/
