### ISSUE TITLE
2 Azure function apps reading from one Azure Service bus queue

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1821]
Based on statement below on this article, is it ok to use 2 Azure function apps reading from one Azure Service bus queue?

"
Be careful if you apply autoscaling to services that are listening for requests on the queue. This can result in increased contention for any resources that these services share and diminish the effectiveness of using the queue to level the load.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b2b229-0cae-3ba9-180c-5aab1a5a4897
* Version Independent ID: 85c2c9d6-cef4-9a7c-a512-ecdd69e1b456
* Content: [Queue-Based Load Leveling pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling)
* Content Source: [docs/patterns/queue-based-load-leveling.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/queue-based-load-leveling.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@PingPongSet Thank you for your question! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@PingPongSet  You wouldn't want two *different* function apps reading from the same queue, because you couldn't predict which app would get which messages. You can have different *instances* of the same function app read from a queue. Using the consumption plan, the platform handles that for you. In the App Service plan, you pick the instant count.

**Comment by KetanChawda-MSFT** [comment]
@PingPongSet Checking in to see if the above post helped answering your question.

**Comment by KetanChawda-MSFT** [comment]
@PingPongSet Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by PingPongSet** [comment]
@MikeWasson 


> You wouldn't want two different function apps reading from the same queue, because you couldn't predict which app would get which messages. You can have different instances of the same function app read from a queue. Using the consumption plan, the platform handles that for you. In the App Service plan, you pick the instant count.


Should what you said be included on the article to make it clear? 

However, different function apps could read the same queue without issue.
