### ISSUE TITLE
choreography with message queues

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1823]
Can anyone elaborate on the below? I thought resiliency is robust when message queue is used. Why does below say "less robus"?
"On the other hand, for choreography, the role is distributed amongst all services and resiliency becomes less robust."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f568e9ac-4d16-5076-4863-5e007112b3db
* Version Independent ID: 9180ec47-aaf4-d811-d89d-437dd85fa878
* Content: [Choreography - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography#example)
* Content Source: [docs/patterns/choreography.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/choreography.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@PingPongSet I believe while that is true for message queues generally, in the case of choreography, failures at one service could break the complete workflow.

As the following paragraph in the docs mention, each service has to be responsible for resiliency of the workflow as a while which could be hard to implement.

Like in the [example](https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography#example) the docs portray, event grid is used for retries and consequent failures are dead-lettered, which will have to be picked up by another service and/or require manual intervention.

**Comment by PramodValavala-MSFT** [comment]
@PingPongSet Just following up here... Hope my previous comment clears things up.

**Comment by PingPongSet** [comment]
@PageWriter-MSFT  Thanks for your comment. I agree it is less robut.

Another question is that on the solution below, how does it achieve choreography when pub/sub is used?

https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography#solution

**Comment by PramodValavala-MSFT** [comment]
@PingPongSet The pub/sub is used for message delivery. The services would subscribe for specific messages and send the response via another message to the same queue or a different queue.

The [example](https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography#example) uses Event Grid for the pub/sub. [Service Bus Topics](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview#topics) are a great choice too.
