### ISSUE TITLE
Downloadable PDF Document

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1826]
A great resource for Azure architecture here. Is it possible to download the document in pdf like other Azure doc sites?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Guide](https://docs.microsoft.com/en-gb/azure/architecture/guide/)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by TravisCragg-MSFT** [comment]
@PingPongSet Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by ac9999** [comment]
Yes, definitely would like a PDF version of this to download on iPad or mobile.

**Comment by vasuPrasad** [comment]
You can access directly from here:
https://download.microsoft.com/download/2/D/2/2D29C8A8-A758-4152-A204-2BE86548F995/Cloud_Application_Architecture_Guide_EN_US.pdf

**Comment by absheik** [comment]
AB#160200 - Thanks for reporting - this issue is under review

**Comment by sombanerjee** [comment]
Any updates? There used to be a PDF link earlier, which seems to be missing.

**Comment by Sarkie** [comment]
@sombanerjee is the link working now?

**Comment by sombanerjee** [comment]
@Sarkie - I still don't see the link.

**Comment by doodlemania2** [comment]
Should be fixed shortly.

**Comment by sombanerjee** [comment]
@doodlemania2 and @Sarkie - Thank you, the download PDF link is now working.
