### ISSUE TITLE
Azure Services for Management Service Discovery

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#1827]
Is there Azure Services available for Management Service Discovery mentioned here?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7e7bd-23f3-a39f-9015-b77f14bb43e5
* Version Independent ID: 0ac34e7e-315f-2452-bf0a-74e9b1068c38
* Content: [Microservices architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-gb/azure/architecture/guide/architecture-styles/microservices)
* Content Source: [docs/guide/architecture-styles/microservices.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/microservices.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by TravisCragg-MSFT** [comment]
@PingPongSet Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by absheik** [comment]
AB#160239 - Thanks for reporting - this issue is under review

**Comment by MikeWasson** [comment]
Management would be something like Kubernetes for orchestration. Same thing for service discovery.
