### ISSUE TITLE
Readiness and liveness probes considerations 

### ISSUE THREAD

**Issue by dzoech** [MicrosoftDocs/architecture-center#1830]
"Sometimes readiness probes are used to check dependent services. For example, if a pod has a dependency on a database, the *liveness probe* might check the database connection. [...]"

Didn't you mean to write "readiness probe" in the second sentence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks)
* Content Source: [docs/reference-architectures/microservices/aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/microservices/aks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@dzoech Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@dzoech That's correct - thanks! 😺
