### ISSUE TITLE
Partitioned Indexes

### ISSUE THREAD

**Issue by AntipodeYarns** [MicrosoftDocs/architecture-center#1831]
There's another index-related tweak you can do if you have tables with relatively sparse alternate keys. If you create separate indexes with included columns for the most commonly hit data that explicitly exclude the null alternate key rows from the covering index using an index predicate, you can give the query optimizer more information to use the best index for the query. This pattern is particularly useful when a transactional table has been denormalised by combining multiple entities that share a common primary key or several common data fields but have different sets of optional fields (e.g. different types of health insurance claims). The covering indexes for each secondary index in such situations will often end up covering different fields.

This is a real-life situation to real-life brown-field scenarios and serves to protect against "parameter sniffing" queries quite effectively, especially when the targeted key value predicate in the search query includes "IS NOT NULL".

I hope some people find this useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36982a55-b653-9f6b-6b51-f50105abde18
* Version Independent ID: 81ada183-46a5-9101-7f53-b008e83c7f68
* Content: [Index Table pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/index-table#feedback)
* Content Source: [docs/patterns/index-table.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/index-table.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@AntipodeYarns Thank you for providing your suggestion. This will definitely help other in the community.

Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
