### ISSUE TITLE
Isn't Dynamic Data Masking also supported on Azure SQL DW?

### ISSUE THREAD

**Issue by tonio-lora** [MicrosoftDocs/architecture-center#1832]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e643be6d-22a2-2b91-c370-edf83d694efe
* Version Independent ID: 770f2e51-9c53-e5ca-1107-9577369b15a6
* Content: [Choosing an analytical data store](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analytical-data-stores)
* Content Source: [docs/data-guide/technology-choices/analytical-data-stores.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/analytical-data-stores.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by ChiragMishra-MSFT** [comment]
@tonio-lora Can you please help us understand what's the exact issue you are facing ?

**Comment by tonio-lora** [comment]
Hi,
Sorry for the lack of details on the original ticket. I was wondering if we should update the cell on the second column / last row of the [security capabilities matrix](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/analytical-data-stores.md#security-capabilities) from No to Yes to reflect the fact that [Azure SQL Data warehouse does support Dynamic Data Masking](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-dynamic-data-masking-get-started)

**Comment by KalyanChanumolu-MSFT** [comment]
@tonio-lora Thank you for pointing this out.
I have submitted a PR to update the document.

**Comment by KalyanChanumolu-MSFT** [comment]
@tonio-lora The PR is merged now. We will proceed to close this issue. 
In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. 
We love taking contributions from the community.
