### ISSUE TITLE
This page has invalid page link

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [MicrosoftDocs/architecture-center#1834]
For recommendations on developing resource naming conventions for your organization, see Ready: Recommended naming and tagging conventions.

https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/ready/considerations/name-and-tag

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@vairakkumar-vairaperumal Thanks for catching that! We will review and update the doc accordingly.

**Comment by PramodValavala-MSFT** [comment]
@vairakkumar-vairaperumal We have worked up a PR to update the link. Here is [the updated link](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging) for reference.

The doc update should reflect in a couple of hours.
