### ISSUE TITLE
please update the PS command with Az module !

### ISSUE THREAD

**Issue by ehsf973** [MicrosoftDocs/architecture-center#1835]
please update the PS command with Az module !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec640d8-1064-c083-4313-5e8c23fbc2cf
* Version Independent ID: 5f7c63ca-7ab2-9129-4c34-191286e67af1
* Content: [Connect an on-premises network to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute-vpn-failover#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@ehsf973 Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@ehsf973 We have worked up a PR to update the docs.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
