### ISSUE TITLE
[spelled-out version] IDP stands for Identity Provider 

### ISSUE THREAD

**Issue by VishwajitG** [MicrosoftDocs/architecture-center#1838]
IDP stands for Identity Provider on line #8. 
(The first time you use an abbreviation in the text, present both the spelled-out version and the short form) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d00031-82e8-a8ee-0a66-e9b84231e837
* Version Independent ID: 9a9da08f-83e2-c493-61af-c4b5316c6f8e
* Content: [Work with claim-based identities in multitenant applications](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/claims#feedback)
* Content Source: [docs/multitenant-identity/claims.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/claims.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@VishwajitG Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@VishwajitG Thanks for the feedback! We have worked up a PR to address this. The same should reflect in a couple of hours.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
