### ISSUE TITLE
"Automate deployments." is appear twice

### ISSUE THREAD

**Issue by tsubasaxZZZ** [MicrosoftDocs/architecture-center#1840]
"Automate deployments." is appear twice at Release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2bdcdc-80e6-c47a-dae6-0f1bc44b765b
* Version Independent ID: aec4e510-ca48-54ba-beda-82e6ac06bf11
* Content: [DevOps checklist - Azure Design Review Framework](https://docs.microsoft.com/en-us/azure/architecture/checklist/dev-ops#management)
* Content Source: [docs/checklist/dev-ops.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/checklist/dev-ops.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@tsubasaxZZZ I believe the text in **bold** is meant to signify the heading for that paragraph and the following text is its description.

**Comment by tsubasaxZZZ** [comment]
@PramodValavala-MSFT My comment is appear **twice**. So I suggest "Rollforwardable" second one.

**Comment by PramodValavala-MSFT** [comment]
@tsubasaxZZZ Sorry about that. Missed that earlier.

We are assigning this issue to the content author for further review and to update the doc accordingly.
