### ISSUE TITLE
What is IDP?

### ISSUE THREAD

**Issue by alindgren** [MicrosoftDocs/architecture-center#1841]
I am guessing Identity Provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5df2491-1abe-0211-efbf-c1fb384862e9
* Version Independent ID: f7f0d2cf-3f4f-44dc-54aa-cd59221264d2
* Content: [Secure a backend web API in a multitenant application](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/web-api)
* Content Source: [docs/multitenant-identity/web-api.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/web-api.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Yep. I'll change this to spell out on first mention. Thanks!
