### ISSUE TITLE
Microsoft.Graph library retry guidance

### ISSUE THREAD

**Issue by ksgopal4** [MicrosoftDocs/architecture-center#1842]
Is retry logic built into Microsoft.Graph library, couldn't find any information on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@ksgopal4  Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@darrelmiller can you please provide your thoughts here .

**Comment by takekazuomi** [comment]
The following document says "Wait the number of seconds specified in the Retry-After header". However, not all resources support "Retry-After" header. Do you have guidance for unsupported resources?

https://docs.microsoft.com/en-us/graph/throttling#best-practices-to-handle-throttling

**Comment by absheik** [comment]
AB#160236 - Thanks for reporting - this issue is under review

**Comment by absheik** [comment]
closing as all up transient fault guidance is covered in https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults

**Comment by takekazuomi** [comment]
@absheik 

The linked document is general guidance and does not include service-specific retry handling.
It is necessary to describe retry handling in Microsoft Graph as shown in the following document.

https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific
