### ISSUE TITLE
Visio file download is incorrect

### ISSUE THREAD

**Issue by WindyCityCassie** [MicrosoftDocs/architecture-center#1843]
This is using the same visio file as one of the other hybrid network pages, and shows Azure stack on the left and is missing the VPN gateway + Expressroute shapes as shown in the actual image at the top of the page.  Download needs to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec640d8-1064-c083-4313-5e8c23fbc2cf
* Version Independent ID: 5f7c63ca-7ab2-9129-4c34-191286e67af1
* Content: [Connect an on-premises network to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute-vpn-failover#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@WindyCityCassie The visio diagrams for all 3 hybrid networking docs (VPN, ExpressRoute, ExpressRoute with VPN failover) are present in the same visio file in separate tabs.

![image](https://user-images.githubusercontent.com/43602528/68362041-e5ee5c00-014b-11ea-8ebd-1e075444b9fb.png)

**Comment by PramodValavala-MSFT** [comment]
@WindyCityCassie Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@WindyCityCassie Hope my previous comment clears things up.

Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
