### ISSUE TITLE
Icon error in the diagram

### ISSUE THREAD

**Issue by sanjayntms** [MicrosoftDocs/architecture-center#1844]
Pl correct icon of products in the above architecture

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac160993-f333-03d1-ee24-394adedbb830
* Version Independent ID: a9be7642-9bea-b561-7a30-0b152b93285f
* Content: [Securely managed web applications - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/fully-managed-secure-apps)
* Content Source: [docs/example-scenario/apps/fully-managed-secure-apps.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/fully-managed-secure-apps.md)
* Service: **architecture-center**
* Sub-service: **example-scenarios**
* GitHub Login: @fmustaf
* Microsoft Alias: **faisalm**

**Comment by PramodValavala-MSFT** [comment]
@sanjayntms Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
AB#160235 - Thanks for reporting - this issue is under review
