### ISSUE TITLE
Azure Synapse

### ISSUE THREAD

**Issue by mjtpena** [MicrosoftDocs/architecture-center#1846]
Hi Team, The SQL Data Warehouse should be Azure Synapse. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c337b22b-b387-5eea-9b16-656885eae759
* Version Independent ID: 6c1ad9b6-fdf4-f23a-20dc-118f262d0a8c
* Content: [Automated enterprise business intelligence (BI) - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-adf#feedback)
* Content Source: [docs/reference-architectures/data/enterprise-bi-adf.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/enterprise-bi-adf.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@mjtpena Thank you for your feedback! We will review and provide an update as appropriate.
