### ISSUE TITLE
Big data processing - Azure Databricks

### ISSUE THREAD

**Issue by ashokmagadum** [MicrosoftDocs/architecture-center#1847]
Hi,

I observed that 'Azure Databricks' equivalent service in AWS is mentioned as 'EMR'.

Nonetheless, I urge its 'AWS Glue' which is appropriate service.

![Screen Shot 2019-11-08 at 10 13 28 am](https://user-images.githubusercontent.com/35385853/68435871-94f46b80-0210-11ea-9d3b-656e867397d4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@ashokmagadum Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by absheik** [comment]
AB#160232 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
We've taken this to our backlog for a large update in the coming days. Thanks so much, closing for now.
