### ISSUE TITLE
ICommandHandler

### ISSUE THREAD

**Issue by AdrianEmmott** [MicrosoftDocs/architecture-center#1848]
Hi there, thanks for this article on CQRS, very interesting.

I'm trying this out in VSCode on a Chromebook but cannot add the namespace Microsoft.VisualStudio.Commanding via NuGet (to use ICommandHandler) - does anyone know how to add that namespace into VSCode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [Command and Query Responsibility Segregation (CQRS) pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs#feedback)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by YutongTie-MSFT** [comment]
@AdrianEmmott 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by absheik** [comment]
AB#160231 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
Per: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.commanding.icommandhandler-1?view=visualstudiosdk-2019 the API is present but would be dependent upon your context and what references were added to your project. Closing for now as we were able to see it on our side when loading up.
