### ISSUE TITLE
Event Bridge & Event Grid

### ISSUE THREAD

**Issue by Jandev** [MicrosoftDocs/architecture-center#1849]
The AWS equivalent now states it's SQS, which was the best equivalent AWS had to offer a couple of months ago.
However, with the recent release of Amazon EventBridge (https://aws.amazon.com/eventbridge/) I think this new service fits as a better equivalent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#messaging-and-eventing)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@Jandev Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
AB#160228 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
We've taken this to our backlog for a large update in the coming days. Thanks so much, closing for now.
