### ISSUE TITLE
Why no mentioning of Azure Data Explorer?

### ISSUE THREAD

**Issue by olavt** [MicrosoftDocs/architecture-center#1850]
Why isn't Azure Data Explorer mentioned as a viable alternative for storing time-series data? https://azure.microsoft.com/en-us/services/data-explorer/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bde15d-d343-b84d-b77f-55b8e3f12638
* Version Independent ID: 9d35a3eb-707b-47f6-68bc-3f22fee4c78c
* Content: [Time series data](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/time-series#feedback)
* Content Source: [docs/data-guide/scenarios/time-series.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/time-series.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @olavt Thanks for your feedback. We will review and update as appropriate.

**Comment by absheik** [comment]
AB#160222 - Thanks for reporting - this issue is under review

**Comment by adamboeglin** [comment]
Added in #2059
