### ISSUE TITLE
Update for revision 4 HLI?

### ISSUE THREAD

**Issue by dohughes-msft** [MicrosoftDocs/architecture-center#1851]
Hi, would it be possible to update this page and diagram for revision 4 of HANA large instances?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 297fe58b-8232-9b2a-c92e-9f7f94ec3e4e
* Version Independent ID: 3da45f17-e475-f23e-c77f-465933ed02f4
* Content: [Run SAP HANA on Azure Large Instances - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/hana-large-instances)
* Content Source: [docs/reference-architectures/sap/hana-large-instances.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/hana-large-instances.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@dohughes-msft Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
AB#160220 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
Thank you for this-  we've added this to our backlog for updates in the next few weeks. Closing for now.

**Comment by doodlemania2** [comment]
Update is staging for this. Thanks again!

**Comment by dsk-2015** [comment]
@dohughes-msft , Hi Donovan, the article already mentions the revision 4 in the "Architecture" section. It is generally not advisable to add revisions/version information in the architecture diagram.
