### ISSUE TITLE
SQL Data Warehouse supports Dynamic data masking	

### ISSUE THREAD

**Issue by ozanabuse** [MicrosoftDocs/architecture-center#1853]
SQL Data Warehouse supports Dynamic data masking	: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-dynamic-data-masking-get-started#set-up-dynamic-data-masking-for-your-database-using-powershell-cmdlets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba35cbb-4160-0b5d-6829-103b25ad6ce9
* Version Independent ID: fa12ea8e-401a-9567-7b35-ffff532a99b6
* Content: [Choosing a batch processing technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing#feedback)
* Content Source: [docs/data-guide/technology-choices/batch-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/batch-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @ozanabuse Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@ozanabuse PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
