### ISSUE TITLE
Awesome post! Very helpful to understand Azure Vnet design with Hub and spoke,

### ISSUE THREAD

**Issue by stateofthearb** [MicrosoftDocs/architecture-center#1854]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@stateofthearb Thanks for the feedback! Glad that you liked it. 😄
