### ISSUE TITLE
Partitioning Azure table storage should be a H2

### ISSUE THREAD

**Issue by serpent5** [MicrosoftDocs/architecture-center#1855]
The "Partitioning Azure table storage" header comes out as a h3, but I think it should be a h2 to match the others.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef578ecf-7b41-cac8-ba5d-2e132c337b1e
* Version Independent ID: f325ab09-f55d-42ce-5892-a116d4958d6c
* Content: [Data partitioning strategies - Best practices for cloud applications](https://docs.microsoft.com/en-gb/azure/architecture/best-practices/data-partitioning-strategies#feedback)
* Content Source: [docs/best-practices/data-partitioning-strategies.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/data-partitioning-strategies.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @serpent5 Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@serpent5 PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
