### ISSUE TITLE
Pricing estimates no longer work.

### ISSUE THREAD

**Issue by iamalexmang** [MicrosoftDocs/architecture-center#1857]
Neither of the pricing estimates work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8866b26b-b0e7-494e-48cf-491db44b3aeb
* Version Independent ID: bd1d10ff-39db-a6cb-1a63-805e19159561
* Content: [Image classification for insurance claims - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/ai/intelligent-apps-image-processing)
* Content Source: [docs/example-scenario/ai/intelligent-apps-image-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/ai/intelligent-apps-image-processing.md)
* Service: **architecture-center**
* Sub-service: **example-scenarios**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @amang2205 Thanks for your feedback. We will review and update as appropriate.

**Comment by absheik** [comment]
AB#160216 - Thanks for reporting - this issue is under review

**Comment by adamboeglin** [comment]
I've been unable to reproduce any problems with the pricing estimates.  Please re-open an issue if you are still experiencing issues.
