### ISSUE TITLE
DMZ on the edge between Spoke and Hub

### ISSUE THREAD

**Issue by ivanignatiev** [MicrosoftDocs/architecture-center#1858]
Hello,

I did not found this scenario anywhere in the documentation. 

How to design the network correctly or configure the routing table correctly, to organise DMZ between Hub and Spoke?

![Hub-Spoke-DMZ](https://user-images.githubusercontent.com/1072103/69046605-af40fd00-09f9-11ea-8d31-8415a138dd4b.png)

As I understood if I add 10.0.0.0/16 -> 10.0.1.1, it will replace Peering route and break connectivity with Hub network.

So, do I have to precise all subnetworks of Hub in Route table associated with Spoke subnet or there is better way to achieve the goal? i.e. :  10.0.x.0/24 -> 10.0.1.1 

Thank you !

Best regards,
Ivan Ignatiev
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#deploy-the-solution)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @ivanignatiev Thanks for reaching out. We will review and update as appropriate.

**Comment by msrini-MSFT** [comment]
@ivanignatiev , If you are applying an UDR on the Spoke VNET, then you need to isolate the Virtual Appliance subnet and add rules. That is you need to route traffic 10.0.x.0/24 next hop as 10.0.1.1(NVA). 

Let me know if you have any further questions.

**Comment by msrini-MSFT** [comment]
@ivanignatiev , Do you have any update on this issue?

**Comment by DixitArora-MSFT** [comment]
@ivanignatiev Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
