### ISSUE TITLE
Great content for business continuity planning (last updated in 2016)

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/architecture-center#1859]
(1) This article is a key resource in region-wide business continuity planning. This may be the only document that focuses specifically on a region-wide outage scenario.  Since so many new capabilities are continually added to Azure, can this article be updated to cover new services, new best practices, etc. The publish date lists that the last update was in 2016 - if that is accurate an overall review and update to this would be really appreciated.

(2) The *Checklists for disaster recovery* section is good but many of the sections make reference to other sections in the document (if possible can you add links to these sections as direct pointers)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31c85c7-c25d-897f-e52d-789f7306457b
* Version Independent ID: 969106a5-df35-afef-5afc-96a26c970f44
* Content: [Recover from loss of an Azure region](https://docs.microsoft.com/en-us/azure/architecture/resiliency/recovery-loss-azure-region#feedback)
* Content Source: [docs/resiliency/recovery-loss-azure-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/resiliency/recovery-loss-azure-region.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @adamglick
* Microsoft Alias: **pnp**

**Comment by Alberto-Vega-MSFT** [comment]
@tfurstms Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by doodlemania2** [comment]
Thank you for this great feedback! We are currently working on updating this document as I type. We hope to have updated guidance early in the new year that addresses these exact comments. Thanks so much. Will close for now.
