### ISSUE TITLE
Custom Image scale set limits

### ISSUE THREAD

**Issue by frfriel** [MicrosoftDocs/architecture-center#1860]
...have been increased to 600 now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbd9d8a-e443-aeab-cdf1-1c9c8858746c
* Version Independent ID: 5a0980f5-b246-0865-6f06-aa875f87a5ce
* Content: [Criteria for choosing an Azure compute service - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-comparison#feedback)
* Content Source: [docs/guide/technology-choices/compute-comparison.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-comparison.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@frfriel Thank you for your feedback! We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@frfriel PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
