### ISSUE TITLE
A few inaccuracies noted on this service comparsion page

### ISSUE THREAD

**Issue by Sharonfun101** [MicrosoftDocs/architecture-center#1861]
I noticed a couple of inaccuracies on this service comparison:

1. AWS Glue is AWS fully- managed service utilizing Apache Spark framework not EMR. EMR is IaaS offering. As a result, this comparison should be between Glue and HDsight
   - This is in the context comparison below:
EMR | HDInsight | Managed Hadoop service. Deploy and manage Hadoop clusters in Azure.

2. Sagemaker does not do drag and drop. 
    This is in context of comparing Sagemaker to Azure ML Studio 
3.  AWS has ELK stack -Elasticsearch used for search engine 
     This is in the context of comparing CloudSearch and AzureSearch
4. Batch data transfer has AWS DataSync 
     This is in the context of comparing AWS import/export vs Azure import/export
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @Sharonfun101 - Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by absheik** [comment]
AB#160214 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
Thank you for this suggestion. We've taken this feedback into our backlog for a significant content update in the coming period. Closing for now.
