### ISSUE TITLE
Netflix Hystrix  is EOL

### ISSUE THREAD

**Issue by siepkes** [MicrosoftDocs/architecture-center#1862]
Netflix Hystrix is end of life. They recommend Resilience4J ( https://github.com/resilience4j/resilience4j ) as an alternative in their readme: https://github.com/Netflix/Hystrix/blob/master/README.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4699b7a-fc21-817e-5a37-aa17b55f47a2
* Version Independent ID: 23efcd5d-11a5-c46f-a73e-5cc638591bcd
* Content: [Bulkhead pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead#feedback)
* Content Source: [docs/patterns/bulkhead.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/bulkhead.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by AjayKumar-MSFT** [comment]
@siepkes, Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by PramodValavala-MSFT** [comment]
@siepkes Thanks for the feedback! We have assigned this issue to the content author for further review and to update the doc accordingly.

**Comment by absheik** [comment]
AB#160212 - Thanks for reporting - this issue is under review
