### ISSUE TITLE
Blob vs Data lake

### ISSUE THREAD

**Issue by r3dr4gon** [MicrosoftDocs/architecture-center#1865]
I was wondering why do we prefer blob storage here instead of a data lake (cold)? or even why do we prefer cosmos db over data lake (hot)?

Is there any reason to use data lake at all?
because when i look on the numbers (and i might missed somthing) azure data lake cost as much as a blob storage those days. as for cosmos vs data lake i'm having a bit more trouble to compare them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa3f2c8a-9d2a-579b-6cb7-4e81fb561067
* Version Independent ID: 0d48338a-52aa-f518-82c3-e5ac281bd8f5
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot/)
* Content Source: [docs/reference-architectures/iot/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@r3dr4gon Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
AB#160211 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
Thanks for the suggestion. We've taken this into our backlog for review and a possible update shortly. Closing for now.
