### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by behramkhan** [MicrosoftDocs/architecture-center#1866]
1. This sentence just does not finish

"As part of the ETL process, create an additional column that "

The paragraph just ends after 'that'!

2. The sql queries do not relate to each other when they should .

The SQL query after this sentence.
"The following T-SQL query creates a temporary table that associates each invoice with the correct City Key from the City dimension table."
Deals with the city dimension. 

"CREATE TABLE CityHolder……."

and the very next sql query starts using  "CustomerHolder"

"SET [Integration].[Sale_Staging].[WWI Customer ID] =  CustomerHolder.[WWI Customer ID]"

This makes it really confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c337b22b-b387-5eea-9b16-656885eae759
* Version Independent ID: 6c1ad9b6-fdf4-f23a-20dc-118f262d0a8c
* Content: [Automated enterprise business intelligence (BI) - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-adf#feedback)
* Content Source: [docs/reference-architectures/data/enterprise-bi-adf.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/enterprise-bi-adf.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@behramkhan Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
AB#160209 - Thanks for reporting - this issue is under review
