### ISSUE TITLE
Incorrect Hyperlink

### ISSUE THREAD

**Issue by ryaniam** [MicrosoftDocs/architecture-center#1867]
'Security Operations' appears to be linking to the 'Identity and access management' page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55000863-6c61-319b-7d0d-5366c403e5e2
* Version Independent ID: 7bb9bb22-f939-6176-236f-79399b6ab2b4
* Content: [Overview of the security pillar](https://docs.microsoft.com/en-us/azure/architecture/framework/security/overview#feedback)
* Content Source: [docs/framework/security/overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/overview.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@ryaniam Thanks for your feedback. We will review and update as appropriate.

**Comment by absheik** [comment]
AB#160208 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
Fixed.
