### ISSUE TITLE
"might" or "might not"?

### ISSUE THREAD

**Issue by Kamil-Zakiev** [MicrosoftDocs/architecture-center#1869]
Hello!
I have a doubt about a phrase in this paragraph:
"If the client code runs in a web browser, the browser might need to support cross-origin resource sharing (CORS) to enable code that executes within the web browser to access data in a different domain from the one that served the page. Some older browsers and some data stores don't support CORS, and code that runs in these browsers **might be able to** use a valet key to provide access to data in a different domain, such as a cloud storage account."

By semantic it should be "might **not** be able to", am I right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d94a95d1-5371-4c6a-87d6-00fae7dfb401
* Version Independent ID: d9abac19-dfd7-18d7-2479-42fe5476b569
* Content: [Valet Key pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/valet-key#issues-and-considerations)
* Content Source: [docs/patterns/valet-key.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/valet-key.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by AshokPeddakotla-MSFT** [comment]
@Kamil-Zakiev Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by PramodValavala-MSFT** [comment]
@Kamil-Zakiev Thanks for catching that! We have worked up a PR to address this. Once merged, the change will reflect in a couple of hours.
