### ISSUE TITLE
Web app vs Web app name

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/architecture-center#1871]
There are two separate lines for "Web app" and "Web app name". To add further confusion, the minimum according to the Portal is 2, which doesn't match either of the values (error: "The name must be at least 2 characters"). My understanding is that the name given to a web app must be globally unique.
Can someone review those two lines and make sure they are up to date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming#web)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by dcbrown16** [comment]
Example from Web App docs:
"In the following example, replace <app_name> with a globally unique app name (valid characters are a-z, 0-9, and -). "
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-php#create-a-web-app

**Comment by DixitArora-MSFT** [comment]
Hi @dcbrown16 Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@dcbrown16 PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
