### ISSUE TITLE
AWS AppSync comparison

### ISSUE THREAD

**Issue by ajurcevic** [MicrosoftDocs/architecture-center#1873]
Hi team, love your work on this comparison list.

Curious to know if Azure would have anything that compares with the AWS AppSync solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @ajurcevic Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@ajurcevic There is already work in progress for this. This has been discussed [here](https://dev.to/kayis/comment/a4g3) as well. So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
