### ISSUE TITLE
Example of VM name confusing

### ISSUE THREAD

**Issue by mdi-db** [MicrosoftDocs/architecture-center#1874]
In the intro text of the article, it says "For example, the name of a virtual machine (VM) maps to a DNS name, so the VM name must be unique throughout Azure. But the name of a VM is scoped to the resource group in which it resides."

Although I think I understand what the author is getting at with this sentence based on my understanding of DNS labels needing to be globally unique, it is confusing (especially to someone who does not know this) and appears contradictory when you first read it - i.e., it could easily be interpreted as "VM names need to be globally unique because of DNS, but they only need to be unique within a resource group." which is obviously contradictory.

Would it be possible to clarify or replace the example with something else? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming#feedback)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
@mdi-db Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@mdi-db PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
