### ISSUE TITLE
Networking -> NSG rule incorrect

### ISSUE THREAD

**Issue by TravisCragg-MSFT** [MicrosoftDocs/architecture-center#1875]
NSG Rules have a scope of the parent NSG, and not the RG. This came from https://github.com/MicrosoftDocs/azure-docs/issues/44144

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming?source=docs#feedback)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by AshokPeddakotla-MSFT** [comment]
@MikeWasson Please check this and update the doc as appropriate.

**Comment by MikeWasson** [comment]
See MicrosoftDocs/architecture-center-pr#786
