### ISSUE TITLE
Creating release/<microservice>/v* pipeline does not trigger fullCI

### ISSUE THREAD

**Issue by kjbanaszczyk** [MicrosoftDocs/architecture-center#1876]
In documentation is written "Creation of this branch triggers a full CI build", but as trigger 'path' is set we need to commit and push some change to this branch for it to trigger full CI build. 

Expected behaviour:
* creating branch should trigger full CI build

Actual behaviour:
* creating branch does not trigger full CI build, we need to commit some change to microservice directory for it to trigger full CI build

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f4d213-3eb1-5b4c-aa67-116e8fa36f7d
* Version Independent ID: 18199b5a-8f57-6574-c795-7540199ae49a
* Content: [Building a CI/CD pipeline for microservices on Kubernetes](https://docs.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes#feedback)
* Content Source: [docs/microservices/ci-cd-kubernetes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/ci-cd-kubernetes.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MicahMcKittrick-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by absheik** [comment]
AB#160206 - Thanks for reporting - this issue is under review

**Comment by absheik** [comment]
this is expected behavior.  Triggering a CI build on branch create is not optimal.

**Comment by kjbanaszczyk** [comment]
I believe there is need to amend documentation, because it is misleading
