### ISSUE TITLE
Remove reference to Message Analyzer

### ISSUE THREAD

**Issue by BittahCriminal** [MicrosoftDocs/architecture-center#1877]
Since the product was retired on November 2019, It makes sense to remove links to that product.  See below for retirement reference.

https://docs.microsoft.com/en-us/message-analyzer/microsoft-message-analyzer-operating-guide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz#feedback)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @BittahCriminal Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@BittahCriminal PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
