### ISSUE TITLE
Status of QUIC and HTTP/3

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/architecture-center#1878]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/architecture-center.de-de/issues/6

@git001 commented 2 hours ago — with docs.microsoft.com
Do you plan to offer also QUIC & HTTP/3 in your loadbalancers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @sharad4u
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @CeciAc Thanks for reaching out. We will review and update as appropriate.

**Comment by absheik** [comment]
AB#160203 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
It is Microsoft policy that we don't publicly comment on roadmap items outside our announcements page located on Azure.com. In the event you are blocked, please contact your Microsoft Account Team for more information.
