### ISSUE TITLE
Lower vs. higher routing priority

### ISSUE THREAD

**Issue by mreinli** [MicrosoftDocs/architecture-center#1879]
There is a mistake in the Front Door routing section: "Set the backend pool with different priority values, 1 for the active region and 2 or lower for the standby or passive region." It should be 2 or higher. According to https://docs.microsoft.com/en-us/azure/frontdoor/front-door-routing-methods#priority lower means higher priority.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region#availability-considerations---front-door)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@mreinli 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MarileeTurscak-MSFT** [comment]
Thanks. I made a pull request to add this. CC: @MikeWasson 

https://github.com/MicrosoftDocs/architecture-center/pull/1880

(I was only able to make a public PR since I don't have access to this repo.)
