### ISSUE TITLE
Pricing demonstrated are monthly or daily?

### ISSUE THREAD

**Issue by JawadJaber** [MicrosoftDocs/architecture-center#1884]
The pricing example given here, is it per month or on daily basis?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cc3d81-d33a-bc9b-ab91-d7c4c8e26a95
* Version Independent ID: d3ce3924-f004-a61a-867c-b81fae8cf5f9
* Content: [Sharing location in real time using low-cost serverless Azure services - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/signalr/?WT.mc_id=linkedin&fbclid=IwAR1Baz9IpezPDUMOspz7luGss4qe0ievd6xqzkVMe0Dvg1STKkC4OBi9Eqw#feedback)
* Content Source: [docs/example-scenario/signalr/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/signalr/index.md)
* Service: **architecture-center**
* Sub-service: **example-scenarios**
* GitHub Login: @talhanaveed
* Microsoft Alias: **pnp**

**Comment by ManojReddy-MSFT** [comment]
@JawadJaber We are looking into this and will get back to you shortly.

**Comment by talhanaveed** [comment]
Hi,

The price mentioned is monthly for production grade load.

**Comment by PramodValavala-MSFT** [comment]
@talhanaveed Thanks!

@JawadJaber Hope that clears things up. We will work up a PR to update the doc for more clarity.

**Comment by PramodValavala-MSFT** [comment]
@JawadJaber We have worked up a PR to address this, which once merged will take a couple of hours to reflect.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
