### ISSUE TITLE
Add comparison details about Regions, Azure geographies, Availability Zone and Region pairs

### ISSUE THREAD

**Issue by codingyoga** [MicrosoftDocs/architecture-center#1886]
Hi Team,
It will be informative if we have comparison details about Azure regions, Azure geographies, Availability Zone and Region pairs with AWS regions, Availability Zone and Local Zone. 
Thanks,
Manasa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @codingyoga Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@codingyoga For Azure regions, Azure geographies, Availability Zone information , you need to go to specific service and will easily get the information. I agree with your idea  of having this here only but it might be a lot of information on one page and might add confusion to some of the users.

**Comment by codingyoga** [comment]
Thanks a lot for the response.
Region pairs concept is not available in AWS So I thought it is good idea
to write a table difference between AWS and Azure regions, geographies etc.
If it is too much information, I agree with you.

**Comment by DixitArora-MSFT** [comment]
@codingyoga Thanks for the response. I will work with content team and see if this can be accommodated.  If there are no further questions, Shall we proceed with closure of this ?

**Comment by codingyoga** [comment]
@DixitArora-MSFT Sure will close it. Thanks.
