### ISSUE TITLE
documentation folder missing in git repo

### ISSUE THREAD

**Issue by vbrinza** [MicrosoftDocs/architecture-center#1887]
Was the docs/framework/devops/iac.md removed from git?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5490ef64-9b6d-59be-1e9b-a2b2d10388b2
* Version Independent ID: 4e37976c-47f3-1481-b312-e7be38f93e07
* Content: [Infrastructure Deployment](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/iac#feedback)
* Content Source: [docs/framework/devops/iac.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/iac.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @Jose-Moreno
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@vbrinza 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@vbrinza I have assigned this to content author for further review and update as appropriate.

**Comment by absheik** [comment]
AB#160198 - Thanks for reporting - this issue is under review

**Comment by david-stanford** [comment]
Hi, this file is still there.  If you are seeing an issue please let me know.
