### ISSUE TITLE
Typo: "Anomoly"

### ISSUE THREAD

**Issue by kumar-dhanagopal** [MicrosoftDocs/architecture-center#1889]
This feedback isn't about the article. It's for the parent node of the article. The node has a typo: "Anomoly". It should be "Anomaly".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2a5d359-b35d-f8c1-480e-ea9aff4255b5
* Version Independent ID: 971a1042-d297-7cda-2961-3f5b1b422a9b
* Content: [Anomaly Detector Process - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/anomaly-detector-process)
* Content Source: [docs/solution-ideas/articles/anomaly-detector-process.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/anomaly-detector-process.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@kumar-dhanagopal thanks for this! I don't have access to edit the headers so I'm assigning this to the content author to look into.

**Comment by adamboeglin** [comment]
Resolved
