### ISSUE TITLE
Does each new service have its own database? 

### ISSUE THREAD

**Issue by absilver808** [MicrosoftDocs/architecture-center#1890]
I think this article and its pictures could clarify whether or not each new service gets its own database, and syncs its data back to the monolith. Or perhaps if the new service starts pointing at the monolith's database and eventually migrates to its own?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3d720e-441b-16f6-a73d-d7a66f81fa32
* Version Independent ID: 8a923182-0020-db36-e896-0cf71d277c67
* Content: [Monoliths to microservices using domain-driven design - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/migrate-monolith#feedback)
* Content Source: [docs/microservices/migrate-monolith.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/migrate-monolith.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @lavann
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@absilver808 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@absilver808 While the migration journey described in this doc ends up in a scenario with a single data source (which is still OK in different cases), each service could still have their own data source, especially in cases where different kinds of persistence capabilities are required. For example, RDBMS vs NoSQL.

You can read more about [data considerations](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/data-considerations) to make when designing micro-services. Notice the note in this doc that states

> It's fine for services to share the same physical database server. The problem occurs when services share the same schema, or read and write to the same set of database tables.

**Comment by absilver808** [comment]
Thanks for the timely response! So then would it be an anti-pattern to begin the migration by starting new services on the same schema/tables as the monolith?

**Comment by PramodValavala-MSFT** [comment]
@absilver808 Yes. Ideally, each service should have its own schema/tables and places where the monolith would have to interact with this service, you should have glue code as described in the last section of this doc.

**Comment by PramodValavala-MSFT** [comment]
@absilver808 Just following up here... Hope my previous comments clears things up.

**Comment by PramodValavala-MSFT** [comment]
@absilver808 Hope my previous comments clears things up.

Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
