### ISSUE TITLE
Suggestion - Add Key Vault 

### ISSUE THREAD

**Issue by asears** [MicrosoftDocs/architecture-center#1892]
Could call out Key Vault in the solution architecture / provide separate security / network logical implementation details.

"Ingest" should probably read "Orchestrate" as ADF can trigger Azure Synapse Analytics stored procedures, Databricks notebooks and jobs as part of the workflow.  

Clicking on the contributor link in the heading brings 404 error on Github.
https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@asears 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MarileeTurscak-MSFT** [comment]
@asears you are right that it gives a 404. I'm assigning this to the content author, @adamboeglin , to look into.

**Comment by absheik** [comment]
AB#160191 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
This article has recently received an update and is now more clear. We'll keep thinking on the Key Vault bit as well.
