### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by wiewioor** [MicrosoftDocs/architecture-center#1893]
There is a missing link to [Sharding pattern]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51bec992-bf19-01e4-107d-d70a83febceb
* Version Independent ID: 072c2533-b725-26a6-f294-82f825cd0fbd
* Content: [Data partitioning guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning#feedback)
* Content Source: [docs/best-practices/data-partitioning.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/data-partitioning.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@wiewioor 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@wiewioor PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
