### ISSUE TITLE
Low-priority VMs

### ISSUE THREAD

**Issue by sanjayntms** [MicrosoftDocs/architecture-center#1894]
Use Azure Spot VM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4aca20-be78-ed61-145d-563fb3ff6d13
* Version Independent ID: c3f02005-d0e7-d756-04b5-655ecd84b1e8
* Content: [Modeling your cloud costs](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/modeling)
* Content Source: [docs/framework/cost/modeling.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/modeling.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@sanjayntms thanks for your feedback! Can you please clarify your ask?

**Comment by sanjayntms** [comment]
Pl add Azure spot VMs in the articleyours sincerely,Sanjay DubeyNTMS Training Institute
Whatsapp - 9702553000 
Web Site: ntmsworld.com

NTMS on Facebook
 

    On Tuesday, 24 December, 2019, 02:01:54 am IST, Marilee Turscak - MSFT <notifications@github.com> wrote:  
 
 
@sanjayntms thanks for your feedback! Can you please clarify your ask?

**Comment by absheik** [comment]
AB#160189 - Thanks for reporting - this issue is under review
