### ISSUE TITLE
Numbers on list are wrong

### ISSUE THREAD

**Issue by rafik8** [MicrosoftDocs/architecture-center#1895]
Steps on the diagram are from 1 to 8 but the numbered list is wrong: 1-1-1-2-1-2-1-2-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc547e3a-5433-08eb-9bc2-c0a44e4280a5
* Version Independent ID: 3ab8ba71-f5c5-dcb4-c1be-cde8b61cda34
* Content: [Secure DevOps for AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/secure-devops-for-kubernetes#feedback)
* Content Source: [docs/solution-ideas/articles/secure-devops-for-kubernetes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/secure-devops-for-kubernetes.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by SnehaAgrawal-MSFT** [comment]
@rafik8 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by absheik** [comment]
AB#160187 - Thanks for reporting - this issue is under review

**Comment by adamboeglin** [comment]
This has been resolved.
