### ISSUE TITLE
Numerous Missing Resources

### ISSUE THREAD

**Issue by slynickel** [MicrosoftDocs/architecture-center#1896]
This page appears to be missing a number of resource naming restrictions. Cross referencing the list on this page with https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#sample-naming-convention shows a number of missing resources. I've provided some below but it's not exhaustive. If this isn't going to be centralized place for recommendations wouldn't it be better to just push the limitations back to each page's documentation?

- Azure SQL Database (numerous on this, SQL Data warehouse, MySQL, etc.)
- Cosmos DB
- Azure Search
- Azure Kubernetes Service
- Event Grid
- Log Analytics (this one isn't too hard to find, it's global but I don't know the length restriction)
- Azure Monitor specifics like action group and log alerts

The other page alone isn't enough in it's current format. For example, Cosmos DB requires the name be globally unique but on the other page it states you should name your database "cosdb-emissions-dev" this isn't a good recommendation as it should likely contain some random entropy to avoid name conflicts. Or at least let you know that it needs to be globally unique.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by SnehaAgrawal-MSFT** [comment]
@slynickel Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by absheik** [comment]
AB#160181 - Thanks for reporting - this issue is under review

**Comment by BrianBlanchard** [comment]
This issues is actively being addressed in the CAF repo.

**Comment by slynickel** [comment]
To clarify, is the CAF some internal thing?

**Comment by doodlemania2** [comment]
Thank you for this suggestion. We've taken this feedback into our backlog for a significant content update in the coming period. Closing for now.
