### ISSUE TITLE
Page contains AzureRM powershell commands

### ISSUE THREAD

**Issue by Coldpawz** [MicrosoftDocs/architecture-center#1897]
Hi, after reading the page, I noticed AzureRM commands listed at the bottom, under 'Deploy the solution'. Could these please be updated to the Az commands?

MT!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84bcf722-abb3-69b8-8073-15ae4a6890de
* Version Independent ID: 7b2010c6-696d-de66-8e56-8ac5d3e54526
* Content: [Basic web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app#feedback)
* Content Source: [docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/basic-web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@Coldpawz Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@Coldpawz We have worked up a PR to address this. Once merged, the change should reflect in a couple of hours.
