### ISSUE TITLE
Mismatch in Architecture Diagram and Data Flow Steps. 

### ISSUE THREAD

**Issue by gdprtcl** [MicrosoftDocs/architecture-center#1899]
I observe that the Data Flow is not following the Architecture Diagram as shown. The numbering seems to be off. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed7b54c-fe6b-4331-f6d4-1e369ebad0c1
* Version Independent ID: 70f614a9-153c-3a7e-107c-526ba68adad6
* Content: [Supply Chain Track and Trace - Azure Solution Ideas](https://docs.microsoft.com/en-gb/azure/architecture/solution-ideas/articles/supply-chain-track-and-trace#feedback)
* Content Source: [docs/solution-ideas/articles/supply-chain-track-and-trace.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/supply-chain-track-and-trace.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by SnehaAgrawal-MSFT** [comment]
@gdprtcl Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by absheik** [comment]
AB#160175 - Thanks for reporting - this issue is under review

**Comment by adamboeglin** [comment]
This has been fixed in https://github.com/MicrosoftDocs/architecture-center-pr/pull/1115 and should be merged shortly.
