### ISSUE TITLE
Incorrect DB store mentioned

### ISSUE THREAD

**Issue by ARIT2018** [MicrosoftDocs/architecture-center#1900]
Per the illustration, member record is created in Cosmos DB which is incorrectly referred as SQL Database in the clause "The solution creates a record of the member in SQL Database". Obviously SQL Database != Cosmos DB. So either update the diagram or correct the clause. Also renumber the points after 2. to begin with 3. rather than 1. to correspond with highlighted numbers in the illustration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8103c803-61c9-a383-b1bf-31368060c7a1
* Version Independent ID: c5184b7d-739d-9592-5ec0-cc4edb432a99
* Content: [Serverless Computing Solution for LOB Apps - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/onboarding-customers-with-a-cloud-native-serverless-architecture#feedback)
* Content Source: [docs/solution-ideas/articles/onboarding-customers-with-a-cloud-native-serverless-architecture.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/onboarding-customers-with-a-cloud-native-serverless-architecture.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @ARIT2018 Thanks for your feedback. We will review and update as appropriate

**Comment by absheik** [comment]
AB#160174 - Thanks for reporting - this issue is under review
