### ISSUE TITLE
Missing entries for General types

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/architecture-center#1901]
Please add rows under the general types section for 
- Subscription
- Management Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by mike-urnun-msft** [comment]
@danmyhre Thanks for helping us drive improvements towards MS Docs! I've submitted a PR that adds the details for the two types. Once reviewed and merged, the changes should be live shortly thereafter.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
