### ISSUE TITLE
Software Quality vs Great Azure Architecture Pillars?

### ISSUE THREAD

**Issue by mraswinc** [MicrosoftDocs/architecture-center#1902]
In Microsoft Docs - there are 5 pillars of great software quality. However, in Microsoft Learn (https://docs.microsoft.com/en-us/learn/modules/pillars-of-a-great-azure-architecture/) - the definition is slightly different, it is 4 pillars of Great Azure Architecture instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Pillars of software quality - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/pillars#feedback)
* Content Source: [docs/guide/pillars.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/pillars.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@mraswinc The concepts discussed I believe are the same, whether they are applied on Azure or not. We are assigning this issue to the content author for further review.

**Comment by absheik** [comment]
AB#160173 - Thanks for reporting - this issue is under review

**Comment by david-stanford** [comment]
We are updating all of this content so it is consistent, it will be released over the next six weeks.
