### ISSUE TITLE
Function App Length issue

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftDocs/architecture-center#1904]
deploying a function app with more than 24 characters via portal throws a 400 "Bad Request" error with no further details. Seems to us like the length might be an issue

Length for funtion app names is stated in the document with 1-60 characters. For us, 24 characters did work, 60 did not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @DerMar
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@derhoppe Thank you for your feedback! We will review and update as appropriate.

**Comment by absheik** [comment]
AB#160166 - Thanks for reporting - this issue is under review

**Comment by doodlemania2** [comment]
We have an update coming for this section in the coming weeks. Closing for now! Thanks for reporting.
