### ISSUE TITLE
Not able to download visio file

### ISSUE THREAD

**Issue by Prince269090** [MicrosoftDocs/architecture-center#1907]
I should be able to able to download the visio file which i was able to do previously. please provide suggestions on how to download the vsd file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a5d586-36db-1258-a949-04084fa331e6
* Version Independent ID: 5615a84e-21d7-6a9c-6c2a-37bba2b9d5d8
* Content: [Information Chatbot - Azure Solution Ideas](https://docs.microsoft.com/en-in/azure/architecture/solution-ideas/articles/information-chatbot#feedback)
* Content Source: [docs/solution-ideas/articles/information-chatbot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/information-chatbot.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@Prince269090 Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by adamboeglin** [comment]
I've added the ability to download the diagram as an SVG.  You can import this into Visio.
