### ISSUE TITLE
Provide more details

### ISSUE THREAD

**Issue by panjevic** [MicrosoftDocs/architecture-center#1908]
Seems like a great use case. Would love to see solution accelerator or at least code examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041da9ff-57a4-916d-ae12-8b1e4fe77d44
* Version Independent ID: a56ac57e-3796-559f-261f-76061e0e4810
* Content: [Blockchain Workflow Application - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/blockchain-workflow-application#feedback)
* Content Source: [docs/solution-ideas/articles/blockchain-workflow-application.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/blockchain-workflow-application.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @panjevic Thanks for your feedback. We will review and update as appropriate.

**Comment by doodlemania2** [comment]
Thanks for the suggestion. As this was a solution idea and not an example workload or reference architecture, we didn't create any implementation for it. We'd love to review one if you have one you could share via a pull request. Closing for now!
