### ISSUE TITLE
Always have backup for your critical resources

### ISSUE THREAD

**Issue by Saby007** [MicrosoftDocs/architecture-center#1911]
Depend on the project we should always design backup for our critical resources. The resources will vary from project to project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a14304-4ef8-dc1b-b92d-b021fc169710
* Version Independent ID: 33ad8550-7676-2b43-f6cc-a9eb3d3f2093
* Content: [Make all things redundant - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/redundancy#feedback)
* Content Source: [docs/guide/design-principles/redundancy.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/design-principles/redundancy.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @Saby007 Thanks for reaching out. Could you please let us know the exact ask for this feedback.

**Comment by Saby007** [comment]
Hi, What I feel the identification of critical components in any design is very important. Once we identify it we should always look for options to make it highly available. Hence I feel this should be part of the design principles.

**Comment by DixitArora-MSFT** [comment]
@Saby007 Yes, I do agree that we should always have the the back up for any critical resources . Ideally it should be a part of good practice not the part of any specific design principle.
