### ISSUE TITLE
using Materialized View with microservies is problematic

### ISSUE THREAD

**Issue by FedorRomanov** [MicrosoftDocs/architecture-center#1912]
It is worth mentioning that Materialized View(DB feature) could used in monolitic application only, i.e. when whole set of data(Order, OrderItem, and Customer tables) are located in single DB.
With mictoservices approach, there would be at least 2 services: 
 * Order Service encapsulating Order and OrderItem tables
 * Customer Service encapsulating Customer table
Order Service and Customer Service should be communicating over API without sharing DB access, so create common Materialized View aggregating Order, OrderItem, and Customer tables is problematic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4ffec9b-27ef-0f8c-5fcf-58347950feaf
* Version Independent ID: 8dadd327-8781-e1ef-e2b3-f75f416524e6
* Content: [Materialized View pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view#feedback)
* Content Source: [docs/patterns/materialized-view.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/materialized-view.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@FedorRomanov Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by TapanSharma21** [comment]
Hi FedorRomanov ,

In case of Microservices, the answer will be Domain Service Aggregation pattern.

You will have the separate data-stores for Domain Services.

Then there will be one data store for Aggregation Service which gets the data from all the Domain  services and updates it's data-store. (To Ensure loose coupling it be event based)

In this pattern, Domain Services data-store needs to be highly available which is a source of truth but the Aggregated Service data-source needs not to be highly available as it can be constructed again from the Events from Domain Services.
