### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by stevep0000** [MicrosoftDocs/architecture-center#1913]
As you continue to peel away the monolith, eventually there will come the point in which it no longer needs to exist, the microservices have been successfully extracted from the monolith. At this point, the anti-corruption layer (glue code) can be safely xxxxxx. 

Probably should be "removed".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3d720e-441b-16f6-a73d-d7a66f81fa32
* Version Independent ID: 8a923182-0020-db36-e896-0cf71d277c67
* Content: [Monoliths to microservices using domain-driven design - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/migrate-monolith#feedback)
* Content Source: [docs/microservices/migrate-monolith.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/migrate-monolith.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @lavann
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @stevep0000 Thanks for your feedback. We will review and update as appropriate.

**Comment by MikeWasson** [comment]
Good catch, thanks! 😺
