### ISSUE TITLE
Training Time and Cost

### ISSUE THREAD

**Issue by wmpauli** [MicrosoftDocs/architecture-center#1914]
Do you have any benchmarks on how long it would take to train various ResNets and the cost would be?

I'm looking for info comparable to this: https://dawn.cs.stanford.edu/benchmark/

E.g. Time taken to train an image classification model to a top-5 validation accuracy of 93% or greater on ImageNet.

Thank you!

**Comment by DixitArora-MSFT** [comment]
Hi @wmpauli Thank you for reaching out Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by wmpauli** [comment]
Hi @DixitArora-MSFT , thanks for your response. I was referring to this [page](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/training-deep-learning).
