### ISSUE TITLE
More details required

### ISSUE THREAD

**Issue by Alghurairproperties** [MicrosoftDocs/architecture-center#1915]
Could you pls send us more details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca97a7c-e27f-7565-29cb-73897ed6e16f
* Version Independent ID: 7f7eac20-58ae-21fc-7551-df13aa20c545
* Content: [Hybrid Identity - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/hybrid-identity#feedback)
* Content Source: [docs/solution-ideas/articles/hybrid-identity.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/hybrid-identity.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @Alghurairproperties Thanks for your feedback. Could you please let us know the details for which you are looking for more information.

**Comment by Alghurairproperties** [comment]
Hello,

We are hosting Dynamics within our tenant and would like to extend this application to a lot more external AD domains(recently acquired companies), such that they could use the Hybrid Identity solution using Federated services to authenticate. Wondering If you may have any reference architectures for the same.

Best Regards


Abdulla Ansar
Technical Infrastructure Architect
 
  
  
  T  +971 4 2029777
  M   +971 50 4536771
 www.al-ghurair.com
 | D +971 4 2029716
 | F +971 4 2942664
The information contained in this communication is intended solely for the use of the individual, or entity to whom it is addressed to, and others authorized to receive it. If you are not the intended recipient, any copying, distribution or use of this email or its attachments, or of the information contained therein, is strictly prohibited. The company accepts no liability for any damages caused by any virus if transmitted by this email. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.

**Comment by DixitArora-MSFT** [comment]
@Alghurairproperties Just checking if you have gone through this and see if that helps.

https://docs.microsoft.com/en-us/azure/active-directory/develop/setup-multi-tenant-app

**Comment by DixitArora-MSFT** [comment]
@Alghurairproperties Just following up again in case missed the previous communication.

**Comment by Alghurairproperties** [comment]
Thanks,

It works well

Best Regards

Abdulla Ansar
Technical Architect
Al Ghurair Investment

Abdulla Ansar
Technical Infrastructure Architect
 
  
  
  T  +971 4 2029777
  M   +971 50 4536771
 www.al-ghurair.com
 | D +971 4 2029716
 | F +971 4 2942664
The information contained in this communication is intended solely for the use of the individual, or entity to whom it is addressed to, and others authorized to receive it. If you are not the intended recipient, any copying, distribution or use of this email or its attachments, or of the information contained therein, is strictly prohibited. The company accepts no liability for any damages caused by any virus if transmitted by this email. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.
________________________________

**Comment by DixitArora-MSFT** [comment]
@Alghurairproperties So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by Alghurairproperties** [comment]
Thanks Dixit

Best Regards


Abdulla Ansar
Technical Infrastructure Architect
 
  
  
  T  +971 4 2029777
  M   +971 50 4536771
 www.al-ghurair.com
 | D +971 4 2029716
 | F +971 4 2942664
The information contained in this communication is intended solely for the use of the individual, or entity to whom it is addressed to, and others authorized to receive it. If you are not the intended recipient, any copying, distribution or use of this email or its attachments, or of the information contained therein, is strictly prohibited. The company accepts no liability for any damages caused by any virus if transmitted by this email. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.
