### ISSUE TITLE
ASK cluster

### ISSUE THREAD

**Issue by satrijotomo** [MicrosoftDocs/architecture-center#1916]
I think there is a typo here: "This option requires CNI networking to be enabled when you configure the ASK cluster...". Isn't it AKS cluster instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks#api-gateway)
* Content Source: [docs/reference-architectures/microservices/aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/microservices/aks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@satrijotomo https://godoc.org/github.com/Azure/azure-sdk-for-go/services/eventgrid/2018-01-01/eventgrid#KeyVaultCertificateNearExpiryEventData

**Comment by ketan-chawda-msft** [comment]
Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@satrijotomo Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@satrijotomo Thank you for pointing this out!

I have created a PR to fix the typo. The changes will be available to the document in next 24-48 hrs.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
