### ISSUE TITLE
Can this page be updated with corresponding Azure service of below AWS services

### ISSUE THREAD

**Issue by DebabrataHowlee** [MicrosoftDocs/architecture-center#1917]
Amazon   Elasticsearch Service
Amazon Kinesis
Amazon S3 Glacier   Deep Archive
Amazon Simple Email Service
AWS CloudTrail
AWS Cost Explorer
AWS Data Transfer
AWS Elemental MediaConvert
Amazon Simple Queue   Service
Amazon Simple Queue Service
AWS X-Ray
AWS Data Pipeline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@DebabrataHowlee Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by DebabrataHowlee** [comment]
Hey @ketan-chawda-msft, I should have mentioned that earlier, my bad. Here is it
https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services

**Comment by ketan-chawda-msft** [comment]
@DebabrataHowlee I am glad that you found the relevant document.

Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by DebabrataHowlee** [comment]
Do you mean there are no corresponding services available in Azure for these AWS services now?

**Comment by ketan-chawda-msft** [comment]
Apologies, I got confused with your comment. 

I have reopened the issue and assigned it to the author to provide update as appropriate.

**Comment by ketan-chawda-msft** [comment]
Most of the service is already mentioned in the document https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services

Let us know which specific services are missing from this document.

**Comment by ketan-chawda-msft** [comment]
@DebabrataHowlee Most of the service are already mentioned in the document https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services

Let us know which specific services are missing from this document.

**Comment by DebabrataHowlee** [comment]
Basically, I didn't find Azure services corresponding below AWS services:

AWS CloudTrail
AWS Cost Explorer
AWS Data Transfer
AWS Elemental MediaConvert

**Comment by ketan-chawda-msft** [comment]
@MikeWasson can you comment here?

**Comment by DebabrataHowlee** [comment]
any update on this ?

**Comment by DebabrataHowlee** [comment]
@ketan-chawda-msft or @MikeWasson can you please provide some update on this.

**Comment by doodlemania2** [comment]
An update is now under review. Thank you!

**Comment by adnan-iqbal** [comment]
Could you also include AWS Security Hub with the corresponding service being Azure Security Center.

**Comment by doodlemania2** [comment]
Yep! Am sorry this is taking so long, we're completely re-writing it and making sure it is as accurate as possible. Going to close this issue for now as we have this list in hand. Hope to have it published soon!
