### ISSUE TITLE
Retail inventory management

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/architecture-center#1919]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/architecture-center.zh-cn/issues/77

@richfox commented yesterday — with docs.microsoft.com
how to realize a small inventory control system with azure, do u have a code sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d11b63e-15f8-5a33-5ab6-eeaf1f7db932
* Version Independent ID: 6c36fc2f-a896-53f1-34fa-934e6e216158
* Content: [Retail and e-commerce using Azure MySQL - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/retail-and-ecommerce-using-azure-database-for-mysql#feedback)
* Content Source: [docs/solution-ideas/articles/retail-and-ecommerce-using-azure-database-for-mysql.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/retail-and-ecommerce-using-azure-database-for-mysql.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by KrishnaG-MSFT** [comment]
@CeciAc Thanks for the comment. We are actively investigating on the issue and will get back to you shortly with an update.

**Comment by doodlemania2** [comment]
We don't currently have a deployment example for this but will capture this request for a future iteration. Thanks so much!
