### ISSUE TITLE
AWS AppSync equivalent for Azure

### ISSUE THREAD

**Issue by praneetnadkar** [MicrosoftDocs/architecture-center#1924]
Missing the AWS AppSync service from AWS and its respective equivalent in Azure. May be some more services would be there which are in AWS and not in Azure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by KrishnaG-MSFT** [comment]
@praneetnadkar Thanks for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
Thank you for submitting this. We've taken this to our backlog for a broad update in the coming period. Closing for now.

**Comment by mikelhamer** [comment]
Any update on this?

**Comment by DilLip-Chowdary-Codes** [comment]
It's 2024... Any update on this @doodlemania2 ?
