### ISSUE TITLE
Comparison of availability terms

### ISSUE THREAD

**Issue by new-kirte** [MicrosoftDocs/architecture-center#1925]
Please add comparison of AWS and Azure availability terms (region, AZ, availability set, etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by KrishnaG-MSFT** [comment]
@new-kirte Thanks for your comment. We will review and get back to you shortly with an update.

**Comment by MikeWasson** [comment]
Hi @new-kirte, take a look at this doc, I think it answers what you're asking:

https://docs.microsoft.com/azure/architecture/aws-professional/#regions-and-zones-high-availability

**Comment by ketan-chawda-msft** [comment]
@new-kirte did you get a chance to take a look at the document link provided in the last post?

**Comment by ketan-chawda-msft** [comment]
@new-kirte Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
