### ISSUE TITLE
Corrupted lilnks

### ISSUE THREAD

**Issue by adrydez** [MicrosoftDocs/architecture-center#1926]
All "Next Steps links" don't work
Byez

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2afdbbba-ae07-bdf4-fa21-65955f1623d1
* Version Independent ID: 189aa6c3-a454-66c1-7346-d0fe53235c25
* Content: [Live streaming digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-live-stream#feedback)
* Content Source: [docs/solution-ideas/articles/digital-media-live-stream.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-live-stream.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by KrishnaG-MSFT** [comment]
@adrydez Thanks for the feedback.
Assigning @adamboeglin for visibility, review and document enhancement consideration.

**Comment by adamboeglin** [comment]
This has been resolved and should be updated in a few days.  Thanks for notifying us!
