### ISSUE TITLE
Reference architecture needs to be updated to include VA Template

### ISSUE THREAD

**Issue by managedcoder** [MicrosoftDocs/architecture-center#1927]
This reference architecture needs to be updated to include a discussion of the [Virtual Assistant Template](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-virtual-assistant-introduction?view=azure-bot-service-4.0) and needs to include links to the Virtual Assistant doc and repo.  The Virtual Assistant implements all the key aspects of this referece architecture via a simple Visual Studio "File | New | Project"!!!  Also, it's documentation has links to full doc on other topics discussed like CI/CD, security, best practices, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d6aeb8-ec6a-4d27-2d10-1b404de450b7
* Version Independent ID: 65b165e4-a2e4-7f57-19eb-884fce7bf880
* Content: [Build an enterprise-grade conversational bot](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/conversational-bot)
* Content Source: [docs/reference-architectures/ai/conversational-bot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/conversational-bot.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @roalexan
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @managedcoder Thanks for your feedback. We will review and update as appropriate.
