### ISSUE TITLE
azbb broken?

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/architecture-center#1930]
Trying this out, azbb -s &lt;subscription_id&gt; -g onprem-vnet-rg -l &lt;location&gt; -p shared-services-stack.json --deploy trows:
error: error executing az
  message:
  status: null
  arguments: vm list-skus --resource-type virtualMachines --zone false --subscription &lt;id&gt;

However, running az with "arguments:" param works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implement a hub-spoke network topology - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services#deploy-the-solution)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by juanand** [comment]
Using az cli 2.0.80, node 12.14.1x64. Fails same way in two distinct computers.

**Comment by DixitArora-MSFT** [comment]
Hi @juanand Thanks for reaching out. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@MikeWasson Any inputs in this ?

**Comment by prak2419** [comment]
Has this been fixed?

**Comment by absheik** [comment]
@juanand , @prak2419 , the nuget package version of AzBB needs to be updated.  The Source code has been fixed by https://github.com/mspnp/template-building-blocks/pull/423.  Please build locally and run while we update the nuget package.
