### ISSUE TITLE
Boken links

### ISSUE THREAD

**Issue by achimismaili** [MicrosoftDocs/architecture-center#1933]
It seems, the last five links under "Next steps" are all broken.
Maybe this is the right one for the REDIS article (?): https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-web-app-howto

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900b3b20-5693-1beb-0b4b-161548a7d14f
* Version Independent ID: 94d5daef-6e7b-23d2-58bd-b2796bbbc7e1
* Content: [Dev-Test deployment for testing PaaS solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-paas#feedback)
* Content Source: [docs/solution-ideas/articles/dev-test-paas.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/dev-test-paas.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@achimismaili Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@achimismaili  Thanks for reporting this issue. I have created a PR to fix the broken links which will be available to the document in next 24-48 hours.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
