### ISSUE TITLE
Data Flow Description for point 6 should be related to AAS on top of Synapse

### ISSUE THREAD

**Issue by nikhilsinghmsft** [MicrosoftDocs/architecture-center#1934]
the Data flow for point 6 description is : Run ad hoc queries directly on data within Azure Databricks.
Its should be related to Azure Analysis Service  on top of Synapse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data#feedback)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@nikhilsinghmsft Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@MikeWasson can you please share your thoughts here?

**Comment by ashitabh** [comment]
Spark connnector for PowerBI works for PowerBI desktop only. Can we publish this to app.powerbi.com ( powerbi online) without using PowerBI Gateway ?

**Comment by tim-pluralgroup** [comment]
can MS please answer this?

**Comment by doodlemania2** [comment]
Created in internal backlog for improvement. https://github.com/MicrosoftDocs/architecture-center/issues/1934
