### ISSUE TITLE
Azure SQL

### ISSUE THREAD

**Issue by rasinghb** [MicrosoftDocs/architecture-center#1935]
Why is there no reference to Azure SQL in the reference architectures? Can't we use Azure SQL that has inherent high-availability, is a managed service that needs no AlwaysON configuration management?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Multi-region N-tier application for high availability - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server#feedback)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/multi-region-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@rasinghb There is indeed a reference to Azure SQL in the form of a note under the [architecture sub-section](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server#architecture).

![image](https://user-images.githubusercontent.com/43602528/72584761-54e8ed80-3911-11ea-85fa-67891f82af09.png)

With Azure SQL, you could refer to its docs for how [High Availability](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-high-availability) and [Geo Replication](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-active-geo-replication) can be achieved.

**Comment by PramodValavala-MSFT** [comment]
@rasinghb Just following up here... Hope my previous comment clears things up.

Since there is no doc update required here, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
