### ISSUE TITLE
Some GitHub URL is not Found

### ISSUE THREAD

**Issue by azmathasan92** [MicrosoftDocs/architecture-center#1936]
Here is the URL:
https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs

All the example GITHUB link is not found please update it soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@azmathasan92 Thanks for catching that! We will work up a PR to address this, which once merged, should reflect in a couple of hours.
