### ISSUE TITLE
Swap numbers

### ISSUE THREAD

**Issue by arthurhams** [MicrosoftDocs/architecture-center#1937]
Hi, please swap bullet 7 and 8 in the Data Flow as they are currently incorrect 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4aaadeb-76bf-55bf-0d25-92e50a05145a
* Version Independent ID: 476a24c1-7109-cb35-0a4e-31b5320b4906
* Content: [Custom Mobile Workforce App - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/custom-mobile-workforce-app#feedback)
* Content Source: [docs/solution-ideas/articles/custom-mobile-workforce-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/custom-mobile-workforce-app.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@arthurhams Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.
