### ISSUE TITLE
Misconception about Identity Synchronization

### ISSUE THREAD

**Issue by cdanieloliveira** [MicrosoftDocs/architecture-center#1938]
The architecture itself is just amazing and it shows how migration plans should be. However, I see some misconception about Id synchronization because Active Directory why it's not and should be not one of the candidates to replatform to Azure Active Directory. 

I understand that the picture represents synchronization maybe through Azure AD Connect but still does not show how does an enterprise grade solution actually look like. In enterprise-grade environments, you have lots of legacy systems that still relies on kerberos authentication and, for those, Azure Active Directory Solutions is not be the best way. 

Using this kind of topology makes Authentication be a SPOF (Single Point Of Failure), which is unacceptable in most of mission critical environment. 

What I'd suggest to you guys is updating this architecture using Domain Controller Replica as a solution for Active Directory or even Azure AD Domain Services as a potential candidate. Only this way it's possible to avoid this potential SPOF and garantee a friction free migration to the cloud. 

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 018a7aef-3117-17c5-8693-7455cefa54d3
* Version Independent ID: a6c4e7a0-3cfa-1c4c-bc48-6281c870b035
* Content: [Enterprise-scale disaster recovery - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/disaster-recovery-enterprise-scale-dr)
* Content Source: [docs/solution-ideas/articles/disaster-recovery-enterprise-scale-dr.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/disaster-recovery-enterprise-scale-dr.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by MohitVerma-MSFT** [comment]
Hello @cdanieloliveira ,

Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
@cdanieloliveira - would you be willing to offer a PR on the topic describing what you'd like to see and we'd be happy to review it and run it past the AD product team! Closing for now as the article is technically accurate, but that sounds like a great idea for improvements.
