### ISSUE TITLE
Most "Next Steps" links are broken

### ISSUE THREAD

**Issue by AgileXRM** [MicrosoftDocs/architecture-center#1939]
Most "Next Steps" links are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115fe9d4-6876-b76b-c194-6dbe760f0131
* Version Independent ID: bd2dbb27-a069-8609-5421-33d223df06eb
* Content: [Dev-Test deployment for testing IaaS solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-iaas)
* Content Source: [docs/solution-ideas/articles/dev-test-iaas.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/dev-test-iaas.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@AgileXRM Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@AgileXRM Thanks for reporting this issue. I have created a PR to fix the broken links which will be available to the document in next 24-48 hours.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
