### ISSUE TITLE
Question about part 6 of Data Flow

### ISSUE THREAD

**Issue by samleung314** [MicrosoftDocs/architecture-center#1941]
For the diagram, can clarity be provided about the role of "SQL structured" icon in the architecture? Is it a separate discrete component that Azure Search interacts with? Or is it part of the greater Azure Search Service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a5d586-36db-1258-a949-04084fa331e6
* Version Independent ID: 5615a84e-21d7-6a9c-6c2a-37bba2b9d5d8
* Content: [Information Chatbot - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/information-chatbot#feedback)
* Content Source: [docs/solution-ideas/articles/information-chatbot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/information-chatbot.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@samleung314 Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by adamboeglin** [comment]
We're deprecating this article in favor of the much more detailed reference architecture here: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/conversational-bot

Please review this article and open a new issue if you still have questions.
