### ISSUE TITLE
Duplicate page titles

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#1942]
There are 2 pages in the Solutions Ideas section with the exact same title "Medical Data Storage Solutions". Please change one of them to minimize confusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5f1109-6e79-d75f-44a6-c573e214e351
* Version Independent ID: a63bdc30-afca-f42a-591b-2c4c2abfc025
* Content: [Medical Data Storage Solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/security-compliance-blueprint-hippa-hitrust-health-data-ai?source=docs)
* Content Source: [docs/solution-ideas/articles/security-compliance-blueprint-hippa-hitrust-health-data-ai.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/security-compliance-blueprint-hippa-hitrust-health-data-ai.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @DeanGross Thanks for your feedback. We will review and update as appropriate.
