### ISSUE TITLE
DSVM on CentOS is available in the Azure image gallery.

### ISSUE THREAD

**Issue by davecatt** [MicrosoftDocs/architecture-center#1943]
The page still states DSVM is not supported on CentOS but the gallery seems to offer this.  In Azure, create a virtual machine and browse the marketplace images.  Search data science and the CentOS DSVM is shown.

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-ads.linux-data-science-vm?tab=Overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bdc71b-0a54-4cc4-1b79-f60e274e9a51
* Version Independent ID: 1783570c-3545-71c8-72d3-d5657f77c070
* Content: [Choosing a machine learning technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning)
* Content Source: [docs/data-guide/technology-choices/data-science-and-machine-learning.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/data-science-and-machine-learning.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @davecatt Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@davecatt PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
