### ISSUE TITLE
"In the web tier subnet, all traffic (0.0.0.0/0) is sent to the Azure Firewall." is incorrect

### ISSUE THREAD

**Issue by LucianFrango** [MicrosoftDocs/architecture-center#1944]
Hi, this statement is incorrect in that this simply overrides the system route default route for "0.0.0.0/0 > Virtual Appliance > [firewall IP]". Since there is no route for the address space of the VNet itself to point to Azure firewall, web tier instances are able to communicate directly to each other, not via Azure Firewall.

**Comment by DixitArora-MSFT** [comment]
Hi @LucianFrango Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by LucianFrango** [comment]
Hi, sorry about that, here's the article - https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz#feedback

**Comment by DixitArora-MSFT** [comment]
@LucianFrango  PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
