### ISSUE TITLE
do not use << or >> in the PS commands line

### ISSUE THREAD

**Issue by ehsf973** [MicrosoftDocs/architecture-center#1945]
do not use &lt;&lt;or &gt;&gt; in the PowerShell examples. thoses characters are not recognized by the ISE PowerShell 5.x editor and the copy paste options now  requires  some corrections before executing directly the shell .ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Connect an on-premises network to Azure using ExpressRoute - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@ehsf973 I believe the intention here is that they are placeholders for the user to replace before running. But I guess making them variables instead would be better.

@MikeWasson Thoughts?

**Comment by PramodValavala-MSFT** [comment]
@ehsf973 Since many of the docs here use similar placeholders, we are assigning this issue to the content author for further review.

**Comment by doodlemania2** [comment]
This is a pretty common practice across the platform. It's a good suggestion though and we'll pass it along. Closing for now but we'll keep an eye on alternative patterns in the future.
