### ISSUE TITLE
mspnp / spark-monitoring Is not working properly

### ISSUE THREAD

**Issue by azmathasan92** [MicrosoftDocs/architecture-center#1946]
The library which you have shared is not working properly mspnp/spark-monitoring please rectify it.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor](https://docs.microsoft.com/en-gb/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by MohitVerma-MSFT** [comment]
Hello @azmathasan92 ,

Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by absheik** [comment]
Not enough information to troubleshoot the issue.
