### ISSUE TITLE
Something is missing

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/architecture-center#1947]
Hello
I think something is missing here. You're introducing Cost Modeling and then jump straight into solutions to leverage such as Low Priority VMs and so on.
I think you should not be so exhaustive and move these solutions elsewhere.

I'm expecting from here to get guidelines to do cost modeling at a high level and not finding solutions answering to how to optimize so from my view point everything before the "Estimating and Comparing costs" should be moved after in a section like "Rely on Azure features" within this article or elsewhere in another one.

What's your thought ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4aca20-be78-ed61-145d-563fb3ff6d13
* Version Independent ID: c3f02005-d0e7-d756-04b5-655ecd84b1e8
* Content: [Modeling your cloud costs](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/modeling)
* Content Source: [docs/framework/cost/modeling.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/modeling.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@olileger Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by olileger** [comment]
Thanks Pramod.
I think it's important at least to set the goal of cost modeling.
Something like "Cloud cost modeling is about mapping the cloud resources to the organizational structure to clearly identify where the cloud services are deployed and how they are governed." would be of a great help at the beginning of the article.
My 2 cents
Feel free to loop me in internal thread if needed, I'd be happy to contribute.

**Comment by doodlemania2** [comment]
We'd be happy to review a PR on this is you wanted to offer one up? From a recent review of the doc, it's accurate but could be simplified for sure. Open to thoughts. Closing for now :)
