### ISSUE TITLE
Update on maximum bandwidth

### ISSUE THREAD

**Issue by rolgran** [MicrosoftDocs/architecture-center#1950]
Is not the maximum bandwidth 10 Gbps when using VpnGw5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c72e16-a607-68cc-4d47-7e6f16b546c1
* Version Independent ID: 897309eb-6e9b-1f5c-714b-b12c91e9091d
* Content: [Solutions for connecting an on-premises network to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/index#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MohitVerma-MSFT** [comment]
Hello @rolgran ,

Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@rolgran Thanks for reporting this issue. I have created a PR to update the document. The updates will be available to the document in next 24-48 hours.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
