### ISSUE TITLE
Invalid syntax in example.

### ISSUE THREAD

**Issue by JerryNixon** [MicrosoftDocs/architecture-center#1952]
The example shows the syntax `for (;;)` which is clearly invalid. 
I think we somehow trimmed out the content like `for (var i = 1; i &lt;= 5; i++)` or something like it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497c1436-d32c-1fb5-3209-22058fece4b2
* Version Independent ID: 4818d7be-c866-39bc-f2c3-d7af59d2cd4e
* Content: [Retry pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry#feedback)
* Content Source: [docs/patterns/retry.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/retry.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by TravisCragg-MSFT** [comment]
@JerryNixon I see you closed this issue, please let me know if you need any further assistance and we will re-open and continue.
