### ISSUE TITLE
Issue with diagram

### ISSUE THREAD

**Issue by EdwinGomes** [MicrosoftDocs/architecture-center#1953]
Hi, the diagram does not appear to render correctly.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba39518b-4b1f-f0df-e1c1-bfcc1f586dc9
* Version Independent ID: 7c0dfce9-73a6-7a64-5439-5ff07d6eb686
* Content: [Training and procedural guidance powered by mixed reality - Azure Solution Ideas](https://docs.microsoft.com/en-gb/azure/architecture/solution-ideas/articles/training-and-procedural-guidance-powered-by-mixed-reality#feedback)
* Content Source: [docs/solution-ideas/articles/training-and-procedural-guidance-powered-by-mixed-reality.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/training-and-procedural-guidance-powered-by-mixed-reality.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@EdwinGomes Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.
