### ISSUE TITLE
Visio Diagram 

### ISSUE THREAD

**Issue by SamiHouri** [MicrosoftDocs/architecture-center#1954]
please can we have the visio Diagram of the same architect?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac160993-f333-03d1-ee24-394adedbb830
* Version Independent ID: a9be7642-9bea-b561-7a30-0b152b93285f
* Content: [Securely managed web applications - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/fully-managed-secure-apps#feedback)
* Content Source: [docs/example-scenario/apps/fully-managed-secure-apps.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/fully-managed-secure-apps.md)
* Service: **architecture-center**
* Sub-service: **example-scenarios**
* GitHub Login: @fmustaf
* Microsoft Alias: **faisalm**

**Comment by MohitVerma-MSFT** [comment]
Hello @SamiHouri ,

Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@SamiHouri Follow [this](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/fully-managed-secure-apps#architecture) which discuss about this. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by SamiHouri** [comment]
The request was closed before getting an answer!

**Comment by SamiHouri** [comment]
Hello @MohitVerma-MSFT can you please let me know if the visio diagram is available

**Comment by DixitArora-MSFT** [comment]
@SamiHouri Do let me know if are expecting something different.

![image](https://user-images.githubusercontent.com/46984568/73623244-4c5b1b80-4662-11ea-8e03-b5def60369ef.png)

**Comment by SamiHouri** [comment]
@DixitArora-MSFT Hi Dear, I am expecting the same but visio version if possible.

thank you
