### ISSUE TITLE
Web App vs Web App name?

### ISSUE THREAD

**Issue by steveharrington1** [MicrosoftDocs/architecture-center#1955]
https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming#web

For these rules, what's the difference between a "Web App" and a "Web App name"?

In my subscription the names for Web Apps seem to be restricted by the conditions of the "Web App" rules (60 characters, globally unique.) So what is the "Web App name" referring to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddc35bf-00d9-67c8-bf6a-ade5ebea07ca
* Version Independent ID: 7324a1e6-7010-c620-145b-3d8027709545
* Content: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming#feedback)
* Content Source: [docs/best-practices/resource-naming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/resource-naming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by steveharrington1** [comment]
I see this is already a question that was closed with an "update coming" two months ago. But this wasn't actually answered. Can someone clarify?

**Comment by DixitArora-MSFT** [comment]
Hi @steveharrington1 Thanks for reaching out. We will review and update as appropriate.

**Comment by steveharrington1** [comment]
@DixitArora-MSFT From poking around in the Azure portal, it appears that the name of App Service Plans seems seem to follow the rules for "Web App name" in that they are required to be unique within resource groups. However, they are limited to 40 characters, not 24 as listed in the doc for "Web App name". I do not see a entry for App Service Plans in the doc, nor do I see any names that are limited to 40 characters, so I suspect this just needs to be updated (and renamed for clarity) here.

Web Apps seem to follow the rules for "Web App" - globally unique and limited to 60 characters.

We are currently developing an application that relies on us understanding when names are unique. Can you confirm that what I've suggested is true?

**Comment by absheik** [comment]
the naming rules documentation has been transitioned out of the Azure Architecture center to https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules
