### ISSUE TITLE
All the links in the Next Steps sections show 404

### ISSUE THREAD

**Issue by haokanga** [MicrosoftDocs/architecture-center#1957]
https://docs.microsoft.com/en-us/api/Redirect/documentation/articles/traffic-manager-configure-failover-routing-method/
https://docs.microsoft.com/en-us/api/Redirect/documentation/articles/site-recovery-components/
https://docs.microsoft.com/en-us/api/Redirect/documentation/articles/site-recovery-network-design/
https://docs.microsoft.com/en-us/api/Redirect/documentation/articles/storage-introduction/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d341ce9-13ab-a379-1af3-65390ce3b5e5
* Version Independent ID: e63d08d2-568a-9578-e8c0-74ff1584337b
* Content: [SMB disaster recovery with Azure Site Recovery - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/disaster-recovery-smb-azure-site-recovery)
* Content Source: [docs/solution-ideas/articles/disaster-recovery-smb-azure-site-recovery.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/disaster-recovery-smb-azure-site-recovery.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @haokanga Thanks for your feedback. We will review and update as appropriate.

**Comment by rgardler** [comment]
This issue should be re-opened. The pages no longer return a 404 but they take the user to https://docs.microsoft.com/en-us/azure/?product=featured which is an index page for all docs for all services.
