### ISSUE TITLE
DMZ Between Azure and Internet

### ISSUE THREAD

**Issue by AshleyRutlandSCC** [MicrosoftDocs/architecture-center#1959]
There used to be a 2nd version of this that showed DMZ between Azure and Internet and Azure and On-premise, it would be good to see that design back and updated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz#feedback)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
The previous version used a separate set of firewall appliances to create separate DMZs. With Azure Firewall, all traffic gets routed through the Firewall instance, so there's no substantive difference between Internet and hybrid on-premises, except for the routing rules.

**Comment by DixitArora-MSFT** [comment]
@AshleyRutlandSCC For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
