### ISSUE TITLE
DMZs ? 

### ISSUE THREAD

**Issue by AshleyRutlandSCC** [MicrosoftDocs/architecture-center#1960]
It would be good to see this with DMZ's for Internet Traffic INbound/Outbound using shared Firewall Appliances along with connectivity from On-Premise as an untrusted site so showing Public and Private DMZ's 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implement a hub-spoke network topology - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @AshleyRutlandSCC Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@AshleyRutlandSCC Referring [Issue ](https://github.com/MicrosoftDocs/architecture-center/issues/1959) The previous version used a separate set of firewall appliances to create separate DMZs. With Azure Firewall, all traffic gets routed through the Firewall instance, so there's no substantive difference between Internet and hybrid on-premises, except for the routing rules.

**Comment by DixitArora-MSFT** [comment]
@AshleyRutlandSCC For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
