### ISSUE TITLE
gitflow-branch-workflow.md copied from Atlassian without attribution

### ISSUE THREAD

**Issue by SydneyUniLibrary-Jim** [MicrosoftDocs/architecture-center#1964]
The content in architecture-center/docs/framework/devops/gitflow-branch-workflow.md is copied from https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow.

The original content is licensed under the [Creative Commons Attribution 2.5 Australia License](http://creativecommons.org/licenses/by/2.5/au/).

While the license means copying the original content is allowed, you must:
- give appropriate credit, 
- provide a link to the license, and
- indicate if changes were made.

@kuhlman-labs @david-stanford 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcba6ac8-d41d-9645-b899-d8977f235eed
* Version Independent ID: ec1b28ff-5c3d-6c71-a46c-078e167826a3
* Content: [GitFlow branch workflow](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/gitflow-branch-workflow)
* Content Source: [docs/framework/devops/gitflow-branch-workflow.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/gitflow-branch-workflow.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @UmarMohamedUsman
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@SydneyUniLibrary-Jim Thanks for bringing this up! We have assigned this issue to the content author for further review.

**Comment by david-stanford** [comment]
Thanks for this; we are removing the content over the next day (I've submitted the change, just waiting for it to publish)
