### ISSUE TITLE
Visio Diagrams

### ISSUE THREAD

**Issue by akaimal** [MicrosoftDocs/architecture-center#1965]
[Enter feedback here]
Please can you share the visio files for these diagrams. thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e15f1b-74fe-f944-2cef-2202c7771e72
* Version Independent ID: 4dfbb446-d568-ff0e-be2b-ea0484f33fb5
* Content: [Data Streaming scenario - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/data-streaming-scenario#feedback)
* Content Source: [docs/solution-ideas/articles/data-streaming-scenario.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/data-streaming-scenario.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@akaimal I believe the diagram here is an SVG. We have assigned this issue to the content author to review and update accordingly.

**Comment by adamboeglin** [comment]
> 
> 
> @akaimal I believe the diagram here is an SVG. We have assigned this issue to the content author to review and update accordingly.

This is correct.  This was created as an SVG, so we don't have a Visio diagram for this.

In the figure, we're going to add a "Download as SVG" link to the articles, but in the mean time you can download the SVG here: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/media/data-streaming-scenario.svg
