### ISSUE TITLE
Goals of the Cost Monitoring activities is missing

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/architecture-center#1966]
Hello
The article is going straight to the point on solutions but is missing introducing what is the purpose of Cost Monitoring.
I suggest the following definition: "Cost monitoring is about establishing controls and business processes for reviewing your cloud spend to avoid any misuse and take advantage of new opportunities through flexibility provided by the cloud."
Feel free to loop me in internal thread if needed, I'd be happy to contribute.
Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5ff56e-7e61-df64-5493-46232a9919a5
* Version Independent ID: 98dc2296-093e-47f2-8f50-eecc652ac6fc
* Content: [Monitoring your cloud costs](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/monitoring)
* Content Source: [docs/framework/cost/monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/monitoring.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @olileger Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@olileger PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
