### ISSUE TITLE
Goal is missing

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/architecture-center#1967]
Hello
This article didn't describe what is the goal of "Optimizing cloud costs".
I'd suggest the following definition: "Cloud cost optimization is about using the right Azure services with the right size and the right set of features regarding the needs either technical or business thus avoiding overkilled configuration."
Feel free to loop me in internal thread if needed, I'd be happy to contribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54dd2146-8293-bb39-e90a-f83b5207c000
* Version Independent ID: fdb76897-f950-4a7b-db74-35265c6ecfda
* Content: [Optimizing Cloud Costs](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/optimizing)
* Content Source: [docs/framework/cost/optimizing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/optimizing.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@olileger Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
Internal Microsoft DevOps Bug AB#169335

**Comment by absheik** [comment]
We are rewriting the entire section and have included goal. Closing this issue.
