### ISSUE TITLE
Cloud costs optimization solutions

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/architecture-center#1968]
This article is talking about Microsoft tools and Azure services that may help to optimize the costs.
Some options within the Cost Modeling article could also be applied here such as Low priority VM, Azure Spot Instance and either the newly Azure Dedicated Host could be leveraged in a cost optimization scenario.
Among other things I was also thinking about:
- scaling (up/down, in/out)
- auto-shutdown / auto-start
- Engineering on SLA (for instance single instance VM on Premium storage vs multiple instance in Availability Set, geo replication when not needed...)
- Right-sizing (from ops monitoring)
- Right-region (Data management article)
What's your thought ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54dd2146-8293-bb39-e90a-f83b5207c000
* Version Independent ID: fdb76897-f950-4a7b-db74-35265c6ecfda
* Content: [Optimizing Cloud Costs](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/optimizing)
* Content Source: [docs/framework/cost/optimizing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/optimizing.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@olileger Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
the Cost pillar content is being re written and your feedback is being incorporated.
