### ISSUE TITLE
Goal is missing

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/architecture-center#1969]
Hello
Here again the goal is missing.
I suggest: "Provisioning cloud resources to optimize cost is about deploying a set of rules and mechanism to restrict the possible options for your teams to deploy cloud services to only validated types and sizes."
Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d286b30-3838-73e5-02bf-d04b043632a1
* Version Independent ID: 503eb39c-c898-12ec-bc4a-b9c4f212dd76
* Content: [Provisioning cloud resources to optimize cost](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/provisioning)
* Content Source: [docs/framework/cost/provisioning.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/provisioning.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@olileger Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
Internal Microsoft DevOps bug AB#169343, is planned for this sprint

**Comment by absheik** [comment]
Rewriting the entire section and have included goal. Closing this issue.
