### ISSUE TITLE
Next Steps Links Broken

### ISSUE THREAD

**Issue by kevinlpeterson** [MicrosoftDocs/architecture-center#1970]
404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 018a7aef-3117-17c5-8693-7455cefa54d3
* Version Independent ID: a6c4e7a0-3cfa-1c4c-bc48-6281c870b035
* Content: [Enterprise-scale disaster recovery - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/disaster-recovery-enterprise-scale-dr#feedback)
* Content Source: [docs/solution-ideas/articles/disaster-recovery-enterprise-scale-dr.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/disaster-recovery-enterprise-scale-dr.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@kevinlpeterson Thanks for the feedback! We will work up a PR to address this, which once merged should reflect in a couple of hours.
