### ISSUE TITLE
Next Steps Links Broken

### ISSUE THREAD

**Issue by rvahaver** [MicrosoftDocs/architecture-center#1971]
All of the next steps links generate 401s.  Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a058a401-d8c8-e58a-23c1-d35990e4ab6f
* Version Independent ID: 4acb1715-c7ab-9c60-a55f-ceb09c223755
* Content: [Back up on-premises applications and data to cloud - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/backup-archive-on-premises-applications#feedback)
* Content Source: [docs/solution-ideas/articles/backup-archive-on-premises-applications.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/backup-archive-on-premises-applications.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @rvahaver Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@rvahaver PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
