### ISSUE TITLE
Wrong reference architecture

### ISSUE THREAD

**Issue by SGGIRBS** [MicrosoftDocs/architecture-center#1974]
The folder mentioned in this line...
"Navigate to the **/dmz/secure-vnet-dmz** folder of the reference architectures GitHub repository."

Seems to be incorrect and should be /dmz/secure-vnet-hybrid which matches the actual architecture referenced.
https://github.com/mspnp/reference-architectures/tree/master/dmz/secure-vnet-hybrid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@SGGIRBS Thanks for the feedback! We will review and update accordingly.

**Comment by absheik** [comment]
Internal Microsoft DevOps Bug AB#171794
