### ISSUE TITLE
More detail would be great!

### ISSUE THREAD

**Issue by JRhodes95** [MicrosoftDocs/architecture-center#1976]
We saw one of the CosmosDB Product Managers use a similar architecture at a recent meetup and it looked great, I'm struggling to find more code on it, so a well done example could be helpful!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25c5d5cf-09ea-ed8f-11d3-b8c8e8a8c2b9
* Version Independent ID: 5050d13f-4976-58a2-2a49-0a1f43b67a9f
* Content: [IoT using Cosmos DB - Azure Solution Ideas](https://docs.microsoft.com/en-gb/azure/architecture/solution-ideas/articles/iot-using-cosmos-db#feedback)
* Content Source: [docs/solution-ideas/articles/iot-using-cosmos-db.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/iot-using-cosmos-db.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by JasRobe** [comment]
We have a full IoT reference architecture that might help: https://docs.microsoft.com/en-gb/azure/architecture/reference-architectures/iot/

there is code supporting that linked at the bottom (in github)
directly here: https://github.com/mspnp/iot-guidance

**Comment by DixitArora-MSFT** [comment]
@JRhodes95  For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
