### ISSUE TITLE
Add AWS data exchange/ Azure data share under 

### ISSUE THREAD

**Issue by sumitsengupta** [MicrosoftDocs/architecture-center#1979]
AWS data exchange ( https://aws.amazon.com/data-exchange/ ) is similar to our Azure data share ( https://azure.microsoft.com/en-us/services/data-share/) and is not on the list ( as of Feb 8, 2020 ).

**Comment by DixitArora-MSFT** [comment]
Hi @sumitsengupta Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@sumitsengupta Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by DixitArora-MSFT** [comment]
@sumitsengupta Just following up again in case missed the previous communication.

**Comment by DixitArora-MSFT** [comment]
@sumitsengupta Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
