### ISSUE TITLE
Reload Configuration-There is scope to improve the external configuration store pattern.

### ISSUE THREAD

**Issue by rukhsarahmad-gep** [MicrosoftDocs/architecture-center#1980]
There is scope to improve the external configuration design pattern.

We can design applications in such a way that when an application deploys or restart, load configuration from external storage, and keep in a local cache and application subscribe to the Redis channel (Redis pub/sub framework). now if any configuration change then publishes a message to all subscribers, and the application will load configuration and update local cache.no need to monitor configuration changes at the application level.

This idea will work for all kinds of developed applications - C#, Python, NodeJs, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a97c79-e300-9361-a398-558ae26378ce
* Version Independent ID: 30f222db-c119-69c7-f542-87e012890026
* Content: [External Configuration Store pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/external-configuration-store#feedback)
* Content Source: [docs/patterns/external-configuration-store.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/external-configuration-store.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @rukhsarahmad-gep Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@rukhsarahmad-gep Since this channel is for driving improvements towards MS Docs, could you provide the details of specific section in the documentation that your feedback is applicable to?

**Comment by rukhsarahmad-gep** [comment]
Hi Dixit,

Please refer below PPT. let me know if you need further information.
[cid:image001.png@01D5E0D6.20FB9740]

[cid:image002.jpg@01D5E0D6.20FECB90]<https://www.gep.com/>
Rukhsar Ahmad
(O): +1 732 382 6565, 5120 | (M): +91 981 907 6079
rukhsar.ahmad@gep.com<mailto:rukhsar.ahmad@gep.com>

**Comment by rukhsarahmad-gep** [comment]
@DixitArora-MSFT I am suggesting to change approach at the application level to load configuration. load configuration on application deployment/restart and use Redis pub/sub-framework, to reload configuration again, on publishing Redis message to all subscribers (applications).
1. Application Deployment/Restart- load configuration and keep in the process.
2. Applications will subscribe to Redis Channel.
3. DevOps Team- Publish message, to a subscribed channel by applications and all applications load the latest configuration again from external storage.

**Comment by jocontr** [comment]
Closing this issue as it is a great request for more comprehensive content from our part.
