### ISSUE TITLE
Very interesting

### ISSUE THREAD

**Issue by mrmarten** [MicrosoftDocs/architecture-center#1982]
Please expand this one with some clear examples! This can lead to huge increase of business value!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c16d9ca-f2e2-5f3a-7c01-9187c7b1f02b
* Version Independent ID: 0ad9169e-20ce-4370-17bb-615ae64db0e9
* Content: [Demand Forecasting + Price Optimization - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/demand-forecasting-price-optimization-marketing#feedback)
* Content Source: [docs/solution-ideas/articles/demand-forecasting-price-optimization-marketing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/demand-forecasting-price-optimization-marketing.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by DixitArora-MSFT** [comment]
Hi @mrmarten Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@mrmarten Thanks for the idea and suggestion. Will create the internal work item for this. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
