### ISSUE TITLE
Valid for Service Principal / Managed identity as a member of AAD Security Group?

### ISSUE THREAD

**Issue by aws-scripting-guy** [MicrosoftDocs/architecture-center#1983]
"If the customer has Azure AD Premium, the admin can assign a security group to a role, and members of the group will inherit the app role. This is a convenient way to manage roles, because the group owner doesn't need to be an AD admin."

Can you please confirm if the above is valid also for scenario when:
1. Application role is assigned to an AAD Security Group
2. Service Principal or Managed Identity is a member of AAD Security Group 
3. Service Principal or  Managed Identity will request access_token through client_credentials flow

Note: Assigning application role to Service Principal / Managed Identity directly and requesting token via client_credentials works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#feedback)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@aws-scripting-guy Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@aws-scripting-guy 

> 1. Application role is assigned to an AAD Security Group 

**Yes, but as mentioned, only with Azure AD Premium**

> 2. Service Principal or Managed Identity is a member of AAD Security Group 

**Yes. Doesn't require AAD Premium** 

> 3. Service Principal or Managed Identity will request access_token through client_credentials flow 

**Yes. Doesn't require AAD Premium**

**Comment by aws-scripting-guy** [comment]
Does that mean that what happens after the request on the IdP backend is an evaluation of 

- group membership
- for each of the group, evaluation of any appRole assignment for the target application

So far I am not able to pass beyond the error below
```
"Request has failed with the following: AADSTS501051: Application Y is not assigned to a role for the application X" 
```
Application Y is a member of AD Security Group, which has assigned role for application X. When I assign application Y directly to an appRole for application X, I get the access_token. Running in AAD Premium. (AppRole can be assigned to a Security Group)

Please let me know if you need to clarify any of the above.

**Comment by PramodValavala-MSFT** [comment]
@aws-scripting-guy Looks like the role inheritance doesn't apply to service principals when they are part of a security group. I will check with the team to confirm if this is the expected behavior.

**Comment by psignoret** [comment]
@aws-scripting-guy @PramodValavala-MSFT I can confirm that this is expected. Service principals do not inherit app role assignments through groups, they can only be assigned app roles directly.

**Comment by PramodValavala-MSFT** [comment]
@psignoret Thanks for confirming and updating the doc!

@aws-scripting-guy Hope that clears things up.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
