### ISSUE TITLE
Serverless apps using CosmosDB

### ISSUE THREAD

**Issue by SliderCO-007** [MicrosoftDocs/architecture-center#1984]
I would like to see code examples in JAVA of this architecture. In addition, I would appreciate examples using the Quarkus framework which is much faster on a cold start than typical JAVA and Spring.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779b0c0e-591b-2a38-5076-1c3c046e662c
* Version Independent ID: d681f23c-1480-b49c-bbc6-f38d76958f7e
* Content: [Serverless apps using Cosmos DB - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/serverless-apps-using-cosmos-db#feedback)
* Content Source: [docs/solution-ideas/articles/serverless-apps-using-cosmos-db.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/serverless-apps-using-cosmos-db.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@SliderCO-007 Azure Functions supports CosmosDB through bindings which are covered in the [respective binding doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2?tabs=java) which you can refer to.

While I believe there isn't sample with Quarkus, there is a [Java SDK for CosmosDB](https://github.com/Azure/azure-cosmosdb-java/) built around [RxJava](https://github.com/ReactiveX/RxJava).

If you are looking for a cloud-native deployment strategy, the [Azure Functions Runtime is open-source](https://github.com/Azure/azure-functions-host) and can be built into a container. Also, utilize [KEDA](https://keda.sh/) for auto scaling this container based on the cosmosdb change feed.

**Comment by PramodValavala-MSFT** [comment]
@SliderCO-007 Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@SliderCO-007 Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
