### ISSUE TITLE
Azure equivalent for AWS ParallelCluster

### ISSUE THREAD

**Issue by hmahajanHM** [MicrosoftDocs/architecture-center#1985]
Please suggest

**Comment by DixitArora-MSFT** [comment]
Hi @hmahajanHM Thanks for reaching out. We will review and update as appropriate.

**Comment by absheik** [comment]
Internal Microsoft DevOps AB#174216

**Comment by DixitArora-MSFT** [comment]
@hmahajanHM There is already an internal work item for this. So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
