### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by AngelValdes** [MicrosoftDocs/architecture-center#1986]
It would be great if we get a detail step by step implementation details on how to do this. Specially updated with the newest options of technologies, data stores, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac60d9e-b851-afa6-beeb-74cdaa2a9146
* Version Independent ID: e300615f-1b32-df63-bc89-54b3b17dced5
* Content: [Modern Data Warehouse Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/modern-data-warehouse#feedback)
* Content Source: [docs/solution-ideas/articles/modern-data-warehouse.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/modern-data-warehouse.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@AngelValdes Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mwinel** [comment]
Probably a real-life example, these some times get us more excited to jump on some solutions and in most cases we get to understand how some solutions work in the quickest way possible.

**Comment by devlace** [comment]
Hi @mwinel and @AngelValdes, have a look at this repo for MDW samples: https://github.com/Azure-Samples/modern-data-warehouse-dataops

@ketan-chawda-msft Feel free to add a link to this repo for concrete examples on MDW.

**Comment by mwinel** [comment]
> Hi @mwinel and @AngelValdes, have a look at this repo for MDW samples: https://github.com/Azure-Samples/modern-data-warehouse-dataops
> 
> @ketan-chawda-msft Feel free to add a link to this repo for concrete examples on MDW.

Hi @devlace this is awesome and insightful.

**Comment by doodlemania2** [comment]
As this is a solution idea and not an example scenario or reference architecture, no implementation was created. We'd be happy to receive a PR and review it if you have time to try that out!
