### ISSUE TITLE
Medical Data Storage Solutions

### ISSUE THREAD

**Issue by keithkambanje** [MicrosoftDocs/architecture-center#1988]
I would like to have a full detailed architecture about the above.

I want to build a solution for my local hospital

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5f1109-6e79-d75f-44a6-c573e214e351
* Version Independent ID: a63bdc30-afca-f42a-591b-2c4c2abfc025
* Content: [Medical Data Storage Solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/security-compliance-blueprint-hippa-hitrust-health-data-ai#feedback)
* Content Source: [docs/solution-ideas/articles/security-compliance-blueprint-hippa-hitrust-health-data-ai.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/security-compliance-blueprint-hippa-hitrust-health-data-ai.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#177470

**Comment by DixitArora-MSFT** [comment]
@keithkambanje There is already an internal work item created for this. So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
