### ISSUE TITLE
Name of Visual Studio Team Services not changed to Azure DevOps

### ISSUE THREAD

**Issue by chilleregeravi** [MicrosoftDocs/architecture-center#1990]
Name from VSTS has not been changed to Azure DevOps in the architecture diagram

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20546dde-32a4-9fa5-899e-eb6e60f5cbf9
* Version Independent ID: 55a03d85-415e-4b93-1082-fbbf92712801
* Content: [Hybrid CI/CD - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/hybrid-ci-cd#feedback)
* Content Source: [docs/solution-ideas/articles/hybrid-ci-cd.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/hybrid-ci-cd.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#178078

**Comment by DixitArora-MSFT** [comment]
@chilleregeravi There is already an internal work item created for this. So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
