### ISSUE TITLE
Kafka Streams API

### ISSUE THREAD

**Issue by ZhenoSan** [MicrosoftDocs/architecture-center#1991]
Kafka Streams API should also be present here for comparison. https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-streams-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957618b3-8d25-49c4-950c-0c044d68f443
* Version Independent ID: 2ab67665-066b-fb14-9763-a12693b19bec
* Content: [Choosing a stream processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing#feedback)
* Content Source: [docs/data-guide/technology-choices/stream-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/stream-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#179108
