### ISSUE TITLE
Interesting architecture

### ISSUE THREAD

**Issue by rahulsahay19** [MicrosoftDocs/architecture-center#1993]
[Enter feedback here]

Interesting architecture. But it will be more resourceful or helpful if you can provide backing solution for the same. Blog probably will be a good idea.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks#feedback)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/microservices-with-aks.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#179296

**Comment by MikeWasson** [comment]
@rahulsahay19 Have you seen [this article](https://docs.microsoft.com/azure/architecture/reference-architectures/microservices/aks)? It covers this type of architecture in more depth.

**Comment by ckittel** [comment]
Previous comment answers this issue.  Closing.
