### ISSUE TITLE
Azure Functions

### ISSUE THREAD

**Issue by EddyHaigh** [MicrosoftDocs/architecture-center#1999]
Shouldn't Azure Functions be considered due to the infinite run time on the app service plan and durable functions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a65e47-b024-0c7c-0ee9-21ff095abafd
* Version Independent ID: a764689a-168d-dcef-a297-c47f84ea2d12
* Content: [Background jobs guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#types-of-background-jobs)
* Content Source: [docs/best-practices/background-jobs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/background-jobs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by DixitArora-MSFT** [comment]
@EddyHaigh There is already an internal work item created for this. So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
