### ISSUE TITLE
Incorrect Spelling

### ISSUE THREAD

**Issue by mchammer91** [MicrosoftDocs/architecture-center#2003]
Under the header "Data Flow", on Step 5, I believe "artefacts" should be spelled "artifacts".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d04d315-a0de-8f52-7898-72fda344e924
* Version Independent ID: 5b7bd552-d3fc-0d94-ddee-bed399fd7232
* Content: [CI/CD for Containers - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cicd-for-containers#feedback)
* Content Source: [docs/solution-ideas/articles/cicd-for-containers.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/cicd-for-containers.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by ketan-chawda-msft** [comment]
@mchammer91 Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by absheik** [comment]
fixed spelling error
