### ISSUE TITLE
There seem to be 2 versions of this article in the Table of contents:

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/architecture-center#2005]
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/medical-data-storage
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/security-compliance-blueprint-hippa-hitrust-health-data-ai
If there is a difference between both articles, maybe we can make it clear in the naming?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bc3179-b32b-66c7-40c0-1d5313a4db99
* Version Independent ID: 999cec7f-39f6-f0c2-fd58-56ae4b94bd95
* Content: [Medical Data Storage Solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/medical-data-storage)
* Content Source: [docs/solution-ideas/articles/medical-data-storage.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/medical-data-storage.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by DixitArora-MSFT** [comment]
@w0ut0 There is already an internal work item created for this. So for now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
