### ISSUE TITLE
App Gateway vs Front Door in the architecture diagram

### ISSUE THREAD

**Issue by joydipto1** [MicrosoftDocs/architecture-center#2006]
The architecture diagram on this page shows Azure Front Door while the downloadable visio template shows Application Gateway in "Scalable web app" section. Now I understand both can be used, but then if we choose Application Gateway, then shouldn't it be shown in its own subnet in the visio template ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec53963c-4c95-f6e7-90e0-d1e827df50b0
* Version Independent ID: 81cb35e8-e65d-41b7-f53d-5ddada2b6301
* Content: [Scalable web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app#feedback)
* Content Source: [docs/reference-architectures/app-service-web-app/scalable-web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/scalable-web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by ranabanerjee15** [comment]
Seems Like all of their App service diagram downloads only one Diagram, the BAsic one at https://archcenter.blob.core.windows.net/cdn/app-service-reference-architectures.vsdx

**Comment by MikeWasson** [comment]
We updated the reference architecture to use Front Door but then I forgot to update the Visio. 😺  I've uploaded the latest Visio file. As you say, both are options. [This article](https://docs.microsoft.com/azure/architecture/guide/technology-choices/load-balancing-overview) has guidelines for choosing Application Gateway vs Front Door.
