### ISSUE TITLE
Virtual Machines

### ISSUE THREAD

**Issue by Jurisnakib** [MicrosoftDocs/architecture-center#2007]
Thanks for a great resources. Please Check Virtual Machines section there is Deploy used 2 times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#feedback)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by DixitArora-MSFT** [comment]
@Jurisnakib PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
