### ISSUE TITLE
test1

### ISSUE THREAD

**Issue by pengbobobo1987** [MicrosoftDocs/architecture-center#2009]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa3f2c8a-9d2a-579b-6cb7-4e81fb561067
* Version Independent ID: 0d48338a-52aa-f518-82c3-e5ac281bd8f5
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot/)
* Content Source: [docs/reference-architectures/iot/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by DixitArora-MSFT** [comment]
@pengbobobo1987 Since this channel is for driving improvements towards MS Docs, could you provide the section in the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by DixitArora-MSFT** [comment]
@pengbobobo1987 For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by pengbobobo1987** [comment]
谢谢你的反馈，未来继续交流
