### ISSUE TITLE
Azure Tabe Storage is missing in Azure/AWS NoSQL database comparison

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/architecture-center#2010]
[Azure Table Storage](https://azure.microsoft.com/en-us/services/storage/tables/) ("_A NoSQL key-value store_") should be added to the **Database -> NoSQL / Document** section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by doodlemania2** [comment]
Thank you for this suggestion. We've taken this feedback into our backlog for a significant content update in the coming period. Closing for now.
