### ISSUE TITLE
menu on right hand side is blocking the architecture diagram view

### ISSUE THREAD

**Issue by nakkars** [MicrosoftDocs/architecture-center#2011]
Whenever the architecture diagram is lengthy, the right hand side menu (is this page helpful? and in this article) are blocking the diagram view while scrolling up.

Thanks,
Ravi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac60d9e-b851-afa6-beeb-74cdaa2a9146
* Version Independent ID: e300615f-1b32-df63-bc89-54b3b17dced5
* Content: [Modern Data Warehouse Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/modern-data-warehouse#feedback)
* Content Source: [docs/solution-ideas/articles/modern-data-warehouse.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/modern-data-warehouse.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by absheik** [comment]
This has been fixed
