### ISSUE TITLE
can you train on AKS in Azure ML?? 

### ISSUE THREAD

**Issue by lostmygithubaccount** [MicrosoftDocs/architecture-center#2012]
Can you train on AKS in Azure ML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c04a7e7b-ebe4-b967-3cd1-fab859a9a43f
* Version Independent ID: 3368462d-475c-2a21-07db-c23b557c5144
* Content: [Machine Learning model training with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/machine-learning-with-aks)
* Content Source: [docs/solution-ideas/articles/machine-learning-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/machine-learning-with-aks.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by DixitArora-MSFT** [comment]
@lostmygithubaccount Follow this doc which discuss about this https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-azure-kubernetes-service and let me know how it goes.

For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by lostmygithubaccount** [comment]
Hi @DixitArora-MSFT that is for *deploying* models to AKS on Azure ML, not *training*. It seems the latter isn't possible per Azure ML documentation, but is advertised in this documentation.

**Comment by vmagelo** [comment]
I'm recasting the article to just deal with deployment to AKS. @lostmygithubaccount is correct.
