### ISSUE TITLE
Is there a implementation of this architecture

### ISSUE THREAD

**Issue by ashithraj** [MicrosoftDocs/architecture-center#2013]
Is there a implementation of this architecture

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa600fa-247a-f5ed-d9c7-44af1cd7b132
* Version Independent ID: 194bdae7-041c-d4dd-3696-c05c9ff3b4dc
* Content: [Personalization using Cosmos DB - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/personalization-using-cosmos-db?source=docs#feedback)
* Content Source: [docs/solution-ideas/articles/personalization-using-cosmos-db.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/personalization-using-cosmos-db.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by micheleissa** [comment]
[Here](https://github.com/mspnp/microservices-reference-implementation) is it

**Comment by doodlemania2** [comment]
We'd be happy to receive a reference implementation if you are aware of one or have time to produce one. As this is a solution idea, not a full blow example scenario or reference architecture, we haven't gone through the process to create one.
