### ISSUE TITLE
Cosmos DB links are too vague

### ISSUE THREAD

**Issue by canuzun** [MicrosoftDocs/architecture-center#2015]
Since Cosmos Db is a multi-model database service, it would be much better if Cosmos Db links are linked to the exact DB type/API/offering. For example key/value storage should be linked to Table API documentation or service. So it would be better if the link is https://docs.microsoft.com/en-us/azure/cosmos-db/table-introduction.

Since the page is about data stores and what Azure offers; Table API should be mentioned when talking about key/value store and Cosmos DB main link is way to vague. An alternative may be to share both. Same thing is also valid for some other types...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a2dd11-b2f0-7821-a877-fc09af4ac967
* Version Independent ID: f7537dfd-5472-f0d2-d344-db85fd65bf71
* Content: [Choose the right data store - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by DixitArora-MSFT** [comment]
Hi @canuzun Thanks for your feedback. We will review and update as appropriate.

**Comment by DixitArora-MSFT** [comment]
@canuzun PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
