### ISSUE TITLE
Update IoT architectures to showcase IoT Hub

### ISSUE THREAD

**Issue by khilscher** [MicrosoftDocs/architecture-center#2016]
Several of our IoT architectures and examples do not show case our flagship IoT service, IoT Hub, and need to be updated. This issue will be linked with PRs containing the updates.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by khilscher** [comment]
Resubmitting updates through private repo.
