### ISSUE TITLE
Example Worload: Migrate API doesn't actually have Component Details but is tagged that it does

### ISSUE THREAD

**Issue by loarabia** [MicrosoftDocs/architecture-center#2019]
In the index of [example workloads](https://docs.microsoft.com/en-us/azure/architecture/architectures/example-workloads),  example-workloads.md, the workload for "Migrating a web app to an API-based architecture", apim-api-scenario, is tagged with component list but doesn't have a component list. Inside the article, it has a component and security header without a list of components.

I think this should be headered as "Data Flow" after reading it and the component list tag should be removed from the index.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by loarabia** [comment]
@absheik Is this the kind of thing I could submit a PR for or is there backend automation and configuration that needs to be updated to resolve this?

**Comment by adamboeglin** [comment]
These tags have been removed.
