### ISSUE TITLE
Where is the deploy button

### ISSUE THREAD

**Issue by behramkhan** [MicrosoftDocs/architecture-center#2023]
There is no deploy button in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42f5f6b4-e65b-eacd-10e4-a72c44375d96
* Version Independent ID: e39819f6-d71e-c586-7a16-a5cd4ae28ca3
* Content: [Demand Forecasting for Shipping and Distribution - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/demand-forecasting-for-shipping-and-distribution#feedback)
* Content Source: [docs/solution-ideas/articles/demand-forecasting-for-shipping-and-distribution.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/demand-forecasting-for-shipping-and-distribution.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by ketan-chawda-msft** [comment]
@behramkhan Thank you for your feedback! We will review and provide an update as appropriate.
