### ISSUE TITLE
Lack of infomration to deploy this solution

### ISSUE THREAD

**Issue by behramkhan** [MicrosoftDocs/architecture-center#2024]
There is no 'Deploy' button. Really finding it difficult to navigate to the actual solution from this webpage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa0449a1-4347-bf58-425b-ac873e6f0937
* Version Independent ID: e07346e2-502e-545b-e060-e3c0ba9259cc
* Content: [Demand Forecasting - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/demand-forecasting)
* Content Source: [docs/solution-ideas/articles/demand-forecasting.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/demand-forecasting.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by ketan-chawda-msft** [comment]
@behramkhan Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by doodlemania2** [comment]
As this is a solution idea, no deployment examples were developed. We have, however, taken this into our backlog for consideration of a future improvement. Will close for now!
