### ISSUE TITLE
Can you add GCP as well?

### ISSUE THREAD

**Issue by slavizh** [MicrosoftDocs/architecture-center#2026]
Would be nice if you can add GCP as well here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @JasRobe
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by doodlemania2** [comment]
Thanks so much for the suggestion. Happy to say that this page is in development now and we hope to publish it in the next month!

**Comment by absheik** [comment]
https://docs.microsoft.com/en-us/azure/architecture/gcp-professional, will be available in the next 24 hours
