### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by RamyaRaghuveera** [MicrosoftDocs/architecture-center#2030]
just testing how easy it is to create a issue in azure architecture center

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by RamyaRaghuveera** [comment]
Happy

**Comment by RamyaRaghuveera** [comment]
Happy to know how easy is to report anything/give feedback. Keep it up. Thanks
