### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by luisquintanilla** [MicrosoftDocs/architecture-center#2037]
Last link in article is broken.

https://github.com/Azure/cortana-intelligence-population-health-management/blob/master/Azure%20Data%20Lake/AutomatedDeploymentGuide/Post%20Deployment%20Instructions.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8be93cf-da00-d500-09fa-85388e8e9c4e
* Version Independent ID: abf64496-ef01-7b90-4819-8236621bde94
* Content: [Population Health Management for Healthcare - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/population-health-management-for-healthcare)
* Content Source: [docs/solution-ideas/articles/population-health-management-for-healthcare.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/population-health-management-for-healthcare.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190923
