### ISSUE TITLE
Build.js - MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by SalvatoreMeschini** [MicrosoftDocs/architecture-center#2039]
I ran:

```bash
npm install
node .\build\build.js
```

![build](https://user-images.githubusercontent.com/11814081/77305640-aee1a700-6cf6-11ea-968e-2d94ba329f28.png)

but the outcome is not the expected one:

```
node .\build\build.js
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'D:\Temp\Arch\build\build.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:859:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```

![2020-03-23 11_11_31-architecture-center_build at master · MicrosoftDocs_architecture-center - Opera](https://user-images.githubusercontent.com/11814081/77305896-1697f200-6cf7-11ea-885b-f66592736eed.png)

**Comment by ketan-chawda-msft** [comment]
@SalvatoreMeschini Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by SalvatoreMeschini** [comment]
I downloaded the repository available at **https://github.com/MicrosoftDocs/architecture-center** and then I just ran the commands to generate missing markdown files, as explained in "Understanding the local build process".

## Understanding the local build process

Some of the markdown files are generated from data stored in json files.
This is primarily to avoid human error for pages that still require some HTML.
The process that converts the json to markdown uses a utility script located in the `build` folder.
To run the build script, navigate to the root folder of this repository.

```bash
npm install
node .\build\build.js
```
I guess that specific documentation is:

"Microsoft patterns & practices
https://aka.ms/architecture"

**Comment by ketan-chawda-msft** [comment]
@SalvatoreMeschini Thanks for the details.

Looks like the file was deleted in [this commit](https://github.com/MicrosoftDocs/architecture-center/pull/1268/commits/d647e12ecd51e1c67a2beef1368650f596dbbd58). Adding @MikeWasson  to confirm.

**Comment by ketan-chawda-msft** [comment]
@SalvatoreMeschini try adding the [deleted file](https://github.com/MicrosoftDocs/architecture-center/blob/7cd5288be9057b7e50f0d3f1af2921876653805c/build/build.js) (build.js) on your local to see if that works.

**Comment by SalvatoreMeschini** [comment]
@KetanChawda-MSFT I added the missing build.js and now the error message is:

![2020-03-23 13_49_48-Administrator_ C__WINDOWS_system32_cmd exe](https://user-images.githubusercontent.com/11814081/77318410-4fdb5c80-6d0d-11ea-95b0-dc63fb0a62d1.png)

I guess that several files were deleted, including \docs\reference-architectures\index.json.txt.
I'm not sure whether the readme.md is not updated (maybe there is no longer need to generate the missing files) OR some files were actually deleted by mistake.

**Comment by MikeWasson** [comment]
That script was for internal use. Specifically, it was for building the previous version of the Reference Architectures landing page. It didn't build the doc set or anything like that. I'll update the readme to remove these instructions. Sorry for the confusion.

**Comment by TyagiAmitYahooMail** [comment]
How do I now build this 'architecture-center' documentation for local use on localhost iis/apache?
Please update the package.json or provide the steps.
