### ISSUE TITLE
The Github link is broken

### ISSUE THREAD

**Issue by LiorArmiev** [MicrosoftDocs/architecture-center#2040]
The Github link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ec8051-dea1-e162-6856-4de1bba362aa
* Version Independent ID: 17661180-e55f-ee23-97b4-f910735fb90a
* Content: [Interactive Voice Response Bot - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/interactive-voice-response-bot#feedback)
* Content Source: [docs/solution-ideas/articles/interactive-voice-response-bot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/interactive-voice-response-bot.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191928

**Comment by absheik** [comment]
pointed to https://github.com/ujjwalmsft/cortana-intelligence-call-center-solution
