### ISSUE TITLE
Dark theme ruins contrast of diagrams

### ISSUE THREAD

**Issue by Tyriar** [MicrosoftDocs/architecture-center#2042]
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data

![image](https://user-images.githubusercontent.com/2193314/77419502-c0be5b00-6d85-11ea-966c-2190d9367632.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#192547

**Comment by absheik** [comment]
@Tyriar thanks for reporting this issue.  We will plan a review of all of Azure Architecture Center content to support Dark theme.  I will keep the bug in our DevOps open, but close this issue.
