### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by BMichaelJ** [MicrosoftDocs/architecture-center#2043]
The link in broken
*Use Azure CDN in Azure App Service - https://docs.microsoft.com/en-us/api/Redirect/documentation/articles/cdn-websites-with-cdn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a55fba-7e30-02ff-b525-f00f19610b15
* Version Independent ID: 42905489-5272-bee8-531f-b4be826eeb7f
* Content: [Scalable Episerver marketing website - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-marketing-episerver#feedback)
* Content Source: [docs/solution-ideas/articles/digital-marketing-episerver.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-marketing-episerver.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#193751

**Comment by DixitArora-MSFT** [comment]
@BMichaelJ PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
