### ISSUE TITLE
text phrase issue

### ISSUE THREAD

**Issue by pandeyvaibhav** [MicrosoftDocs/architecture-center#2044]
In this para in the page - "Terraform: Terraform is a cloud-agnostic declarative framework that supports many private and public clouds, being Azure one of them. It has the main advantage of offering a cloud-agnostic framework: while Terraform configurations are specific to each cloud, the framework itself is the same for all of them." 
Have a question on this phrase - "being Azure one of them." shouldn't this written like "Azure being one of them."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5490ef64-9b6d-59be-1e9b-a2b2d10388b2
* Version Independent ID: 4e37976c-47f3-1481-b312-e7be38f93e07
* Content: [Infrastructure Deployment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/iac?source=docs)
* Content Source: [docs/framework/devops/iac.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/iac.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @Jose-Moreno
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#194170

**Comment by absheik** [comment]
https://github.com/MicrosoftDocs/architecture-center-pr/pull/1060
@pandeyvaibhav, Thanks for taking the time to report the issue.
