### ISSUE TITLE
No mention of the case where parameter of object type is optional

### ISSUE THREAD

**Issue by MirzaSikander** [MicrosoftDocs/architecture-center#2045]
Using the example given at the start of the article, what if parameter `VNetSettings` was optional and was omitted or set to an empty object during template generation. Would `[parameters('VNetSettings').name]` resolve to empty string or would it throw a validation error?

```
"resources": [
    {
        "apiVersion": "2015-06-15",
        "type": "Microsoft.Network/virtualNetworks",
        "name": "[parameters('VNetSettings').name]",
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa870d42-1b00-d600-4fef-dd67219a1dc6
* Version Independent ID: 61fa68a5-a08b-7693-ebfd-18711ebd1bbb
* Content: [Use an object as a parameter in an Azure Resource Manager template - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/objects-as-parameters#feedback)
* Content Source: [docs/building-blocks/extending-templates/objects-as-parameters.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/building-blocks/extending-templates/objects-as-parameters.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @petertay
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#194171

**Comment by absheik** [comment]
According to https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-deployment#parameters, the name Must be defined in the parameters section of the template.
It will throw an error for your scenario
