### ISSUE TITLE
Please make all session videos downloadable

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/architecture-center#2047]
currently the videos are not downloadable, only the transcript is

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fe47949-15a1-6073-0ac7-91a072ee4ff5
* Version Independent ID: f670a787-e68f-1216-8194-1472510c4525
* Content: [Governance, risk, and compliance in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/governance?toc=%2Fsecurity%2Fcompass%2Ftoc.json&bc=%2Fsecurity%2Fcompass%2Fbreadcrumb%2Ftoc.json#feedback)
* Content Source: [docs/framework/security/governance.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/governance.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#195018

**Comment by absheik** [comment]
@knssub, I verified internally and based on how the video's are hosted it is not possible enable Video download.
