### ISSUE TITLE
"Download PDF" option is not enabled for Azure Architecture center

### ISSUE THREAD

**Issue by sunil087** [MicrosoftDocs/architecture-center#2048]
Hi Team,

Download PDF option is presently not enabled for offline reference of complete documentation of Azure architecture center. However, I could see its enabled for "Get started guide for Azure developers". 

Can you please enable this option for Azure architecture center as well?

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by ketan-chawda-msft** [comment]
@sunil087 Thank you for reaching out to us. Can you please provide a link to the document which you are following so that I can engage the correct team to help you.

**Comment by sunil087** [comment]
@KetanChawda-MSFT  .. Thanks for getting back. This is the link - https://docs.microsoft.com/en-us/azure/architecture/

**Comment by ketan-chawda-msft** [comment]
@sunil087 Can you try downloading from [this page](https://azure.microsoft.com/en-in/campaigns/cloud-application-architecture-guide/).

**Comment by sunil087** [comment]
Thanks. I do have a copy of this ebook. However, the articles which are updated in "https://docs.microsoft.com/en-us/azure/architecture/" will not reflect in the ebook. I do recollect that "Download PDF" option was enabled earlier but now its not. 

For example - https://docs.microsoft.com/en-us/azure/guides/developer/azure-developer-guide - The whole updated contents in this link can be downloaded as PDF. 

I am looking for a similar one for "https://docs.microsoft.com/en-us/azure/architecture/" which I can use for my offline reference.

**Comment by ketan-chawda-msft** [comment]
@sunil087 Sure thing, I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by absheik** [comment]
Download PDF has been enabled https://docs.microsoft.com/en-us/azure/architecture/opbuildpdf/toc.pdf?branch=live.  This is not the most ideal experience of PDF download.   We pulled this out because of the experience issues.  But enabled it back on because of multiple user requests.  We will update the PDF download experience as those features becomes available.
