### ISSUE TITLE
Columnar data stores

### ISSUE THREAD

**Issue by Rodrigossz** [MicrosoftDocs/architecture-center#2050]
Hello! Cosmos DB can also be considered a columnar data stores because of the Cassandra API. Makes sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aca5ad7e-2611-198b-6327-d253f5519964
* Version Independent ID: 19059344-22ca-3103-efb8-df3820d92c9e
* Content: [Non-relational data and NoSQL - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/non-relational-data#feedback)
* Content Source: [docs/data-guide/big-data/non-relational-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/big-data/non-relational-data.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#196075
