### ISSUE TITLE
image not available

### ISSUE THREAD

**Issue by sscrawfo** [MicrosoftDocs/architecture-center#2052]
the bitnami grafana image in the template here is not available, this needs to be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e17f2434-814c-4ebc-c05d-501566aa3c0f
* Version Independent ID: 6cf80861-2ab6-0c28-8a68-4f641491a61a
* Content: [Use dashboards to visualize Azure Databricks metrics - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/dashboards#feedback)
* Content Source: [docs/databricks-monitoring/dashboards.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/dashboards.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#196205

**Comment by absheik** [comment]
@sscrawfo, this appears to be a temporary issue limited to certain regions.  You can download the image from https://bitnami.com/stack/grafana/virtual-machine
