### ISSUE TITLE
Backup strategies explanation - warm spare

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/architecture-center#2053]
Hello, I would like to ask for additional explanation for those three backup strategies.

1) Redeploy on disaster - all the components are in one region and we simply redeploy all to another region. Data is lost unless there are some backups

3)Hot spare - we have two running regions with failover group and traffic manager/frontdoor. Secondary region can run on lower tiers and we can scale it up when traffic is redirected there.

2) Warm spare should be somewhere in the middle, right? Do we just keep there failover group and app services are redeployed or do we keep just part of the application that enables some basic usage of it?

Would be extremely grateful if someone could clarify that in PaaS example :)
Thanks,
Rafal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefa78da-afbb-5529-d707-b158d991cb16
* Version Independent ID: 64342775-2746-0e51-9aba-253074530f27
* Content: [Backup and disaster recover for Azure applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/backup-and-recovery)
* Content Source: [docs/framework/resiliency/backup-and-recovery.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/resiliency/backup-and-recovery.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#196533

**Comment by absheik** [comment]
@roofiq your understanding is correct.  I have updated the Doc with links to solutions and examples that correspond to these strategies.
