### ISSUE TITLE
What application is DATABASE COPY for?

### ISSUE THREAD

**Issue by LUKEALDRED** [MicrosoftDocs/architecture-center#2055]
Use the DATABASE COPY command to create a backup copy of the database with transactional consistency.

It's not clear if this is an SQL command or a command for somewhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefa78da-afbb-5529-d707-b158d991cb16
* Version Independent ID: 64342775-2746-0e51-9aba-253074530f27
* Content: [Backup and disaster recover for Azure applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/backup-and-recovery#feedback)
* Content Source: [docs/framework/resiliency/backup-and-recovery.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/resiliency/backup-and-recovery.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#197129
