### ISSUE TITLE
Which are the communication protocol used at stage 1 to 5

### ISSUE THREAD

**Issue by sharad006** [MicrosoftDocs/architecture-center#2056]
Which are the communication protocol used at stage 1 to 5

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#197143

**Comment by absheik** [comment]
@sharad006 can you please provide links to the Document this questions refers to?

**Comment by adamboeglin** [comment]
Closing this issue due to lack of information.  Please reopen if needed.
