### ISSUE TITLE
Slide 25 of Deck - Correction

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/architecture-center#2062]
On the slide 25 of the deck, you should remove OMS and include Azure Monitor and Log Analytics there. OMS is no more relevant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa2c3bde-66e8-b501-0152-aa95553970c1
* Version Independent ID: 501576d2-852d-6f9c-9623-85fcce84ed42
* Content: [Security design principles in Azure - Azure Architecture Center](https://docs.microsoft.com/en-in/azure/architecture/framework/security/security-principles#feedback)
* Content Source: [docs/framework/security/security-principles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/security-principles.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#197465

**Comment by knssub** [comment]
Also, please note, even Azure Sentinel is missing in the slide 25, this is a pretty old slide from MSFT, should relook

**Comment by absheik** [comment]
@knssub can you please share the link to the slide you are referring to?  The document you have open the issue against does not have a link to that deck.

**Comment by absheik** [comment]
closing as not enough information about the deck mentioned in the issue.

**Comment by knssub** [comment]
I did respond in email, not sure why it did not register there.

The direct link to PPT is here: https://docs.microsoft.com/microsoft-365/downloads/security-compass-presentation.pptx

It is related to the https://docs.microsoft.com/en-us/security/compass/compass documentation, however, as there is no way to provide feedback, I provided feedback in a different doc page of the same documentation.
