### ISSUE TITLE
Update for page

### ISSUE THREAD

**Issue by HenryFreiburg** [MicrosoftDocs/architecture-center#2063]
Hello, for the list of IaaS/PaaS options, please add "Managed Disk"  vs  "Azure NetApp Files"  Thanks -Henry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 952ee382-9a9e-0f79-807b-1f7c2b819a42
* Version Independent ID: 82f16168-5f05-f8e3-8971-fa9c7cbb828f
* Content: [Use platform as a service (PaaS) options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/managed-services#feedback)
* Content Source: [docs/guide/design-principles/managed-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/design-principles/managed-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#197525

**Comment by DixitArora-MSFT** [comment]
Hi @HenryFreiburg Thanks for reaching out. We will review and update as appropriate.
