### ISSUE TITLE
Misleading information regarding Cosmos DB and partial updates

### ISSUE THREAD

**Issue by maurert** [MicrosoftDocs/architecture-center#2064]
When reading the following section the user can be led to believe that Cosmos DB supports partial updates:

"Many document databases support in-place updates, enabling an application to modify the values of specific fields in a document without rewriting the entire document. Read and write operations over multiple fields in a single document are usually atomic.

Relevant Azure service: Cosmos DB"

Since 2014 there is feature request open to support partial updates in cosmos db. But event though it is claimed that work has started on this, there has been little feedback from Microsoft as to what the status is:

https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6693091-be-able-to-do-partial-updates-on-document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a2dd11-b2f0-7821-a877-fc09af4ac967
* Version Independent ID: f7537dfd-5472-f0d2-d344-db85fd65bf71
* Content: [Choose the right data store - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#197587

**Comment by absheik** [comment]
@maurert this paragraph you have referred to discusses General capabilities of a "Dcoument Database" at the end the link points to a CosmosDB which supports multile Document Database API's.  For example https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-feature-support-36#field-update-operators supports **($inc)** Increment update operators.

**Comment by absheik** [comment]
closing per previous comment
