### ISSUE TITLE
Avoiding race conditions: what when there are no more seats?

### ISSUE THREAD

**Issue by Ricordel** [MicrosoftDocs/architecture-center#2065]
Either I'm missing something, or the seats reservation example contains an evident TOCTOU race condition between checking seat availability and making the reservation, which will lead to overbooking (with a perfect audit trail, though).

This is something that is quite easily solved with a traditional transactionnal system (or with optimistic locking and retries) that both have stronger consistency characteristics, and as a more or less direct consequence also have scaling issues (no free lunch).

* How do you propose to solve that in this particular case?
* What impact will the solution have on some of the benefits of event sourcing (specifically here: scalability)?
* Globally, how is event sourcing compatible with enforcing constraints on the aggregated data (e.g: "don't reserve more seats than room capacity")? We are now dealing with an asynchronous, eventually consistent system, maybe some distributed commit would work, with one event per phase in the event log?

Those issues may go beyond the scope of the article, but I think that they should at least be stated, not ignored, as they are very important issues that may drive the developer's choice between event sourcing and another strategy.

Alternatively, maybe the example should be changed to target an application domain where this kind of problem does not show. Still, I think that an example of when this is an issue is a good thing to have to help guide system designer's choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing#feedback)
* Content Source: [docs/patterns/event-sourcing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/event-sourcing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#197592

**Comment by absheik** [comment]
@Ricordel the article calls out the risk of this approach in the [**Issues and Considerations**](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing#issues-and-considerations) section as "_Even though event sourcing minimizes the chance of conflicting updates to the data, the application must still be able to deal with inconsistencies that result from eventual consistency and the lack of transactions. For example, an event that indicates a reduction in stock inventory might arrive in the data store while an order for that item is being placed, resulting in a requirement to reconcile the two operations either by advising the customer or creating a back order._"
Although we could specifically mention TOCTOU as you have suggested.

**Comment by absheik** [comment]
closing per previous comment.
