### ISSUE TITLE
The architecture diagram is damaged

### ISSUE THREAD

**Issue by jbegnami** [MicrosoftDocs/architecture-center#2066]
Please, would you mind to share the diagram again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba39518b-4b1f-f0df-e1c1-bfcc1f586dc9
* Version Independent ID: 7c0dfce9-73a6-7a64-5439-5ff07d6eb686
* Content: [Training and procedural guidance powered by mixed reality - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/training-and-procedural-guidance-powered-by-mixed-reality#feedback)
* Content Source: [docs/solution-ideas/articles/training-and-procedural-guidance-powered-by-mixed-reality.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/training-and-procedural-guidance-powered-by-mixed-reality.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#197607
