### ISSUE TITLE
Heapster is deprecated

### ISSUE THREAD

**Issue by technovikram** [MicrosoftDocs/architecture-center#2069]
Hi Microsoft Team,
Thanks for these insightful material. I found mention of use of Heapster while exporting metrics to a time-series database. Since Heapster is deprecated, this must be updated to use Kubernetis metrics server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1160782c-3fd6-3236-1cbd-6ddecf56c3db
* Version Independent ID: cbcfb4e3-4fb5-9427-3a17-cb296339b1ad
* Content: [Monitoring a microservices application in AKS - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring#feedback)
* Content Source: [docs/microservices/logging-monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/logging-monitoring.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#198400
