### ISSUE TITLE
PDF links point to web instead of pointing to PDF

### ISSUE THREAD

**Issue by josersleal** [MicrosoftDocs/architecture-center#2070]
[Enter feedback here]
The pdf create has an error. The links are create to the pages in the web while these links should point to the location on the pdf itself

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041da9ff-57a4-916d-ae12-8b1e4fe77d44
* Version Independent ID: a56ac57e-3796-559f-261f-76061e0e4810
* Content: [Blockchain Workflow Application - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/blockchain-workflow-application)
* Content Source: [docs/solution-ideas/articles/blockchain-workflow-application.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/blockchain-workflow-application.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#198943

**Comment by absheik** [comment]
@josersleal this behavior is by design.  We would like the links in the PDF document to go to live Documentation as the Docs are continually updated.  If you are looking for offline browsing, you would search within the PDF for the content instead of leveraging the link.
