### ISSUE TITLE
Enhancement proposal: Catalog table

### ISSUE THREAD

**Issue by ihommani** [MicrosoftDocs/architecture-center#2071]
In the table Catalog of patterns a third columns with a list of challenges it solve would help to organise its reading.
It's a kind of frustrating because the part just before mention those challenges to tackle. 
E.g: Circuit breaker | [Summary] | Resiliency 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [Cloud Design Patterns - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/#feedback)
* Content Source: [docs/patterns/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#199055
