### ISSUE TITLE
Validate data types of properties inside the object

### ISSUE THREAD

**Issue by dohughes-msft** [MicrosoftDocs/architecture-center#2072]
When I expect an object as a parameter, is it possible to define the data types of the properties inside it?

Example: I expect object parameter "credential" to be supplied. This object will contain two properties "user" and "password". I need ARM to treat "password" as a securestring and not a normal string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa870d42-1b00-d600-4fef-dd67219a1dc6
* Version Independent ID: 61fa68a5-a08b-7693-ebfd-18711ebd1bbb
* Content: [Use an object as a parameter in an Azure Resource Manager template - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/objects-as-parameters)
* Content Source: [docs/building-blocks/extending-templates/objects-as-parameters.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/building-blocks/extending-templates/objects-as-parameters.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#199078

**Comment by absheik** [comment]
All the elements of a parameter will have to be of the same type as declared at the creation of the parameters.  In this case the object is a JSON Object, so they are essentially strings.
You can create parameters of type securestring and secureObject as described at https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax#parameters.  
I don’t think you can have parameters with elements of mixed types.  For example you cannot have one element be a string and the other element be an int.  

If you look at this docs link https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/key-vault-parameter?tabs=azure-cli, they create a separate parameter for adminLogin and adminPassword, one as string and the other as securestring.
