### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ojmendezz** [MicrosoftDocs/architecture-center#2073]
The following two links are broken:
[Azure Load Balancer Pricing][az-lb-pricing]
[Azure Monitor Pricing][az-monitor-pricing]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks#feedback)
* Content Source: [docs/reference-architectures/microservices/aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/microservices/aks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#199459

**Comment by absheik** [comment]
@ojmendezz thanks for reporting.fixed both the links in the above pr.
