### ISSUE TITLE
Cost estimation needed

### ISSUE THREAD

**Issue by edidako** [MicrosoftDocs/architecture-center#2074]
Hello,
Can I have an estimation about pricing of this scenario?
Thanks,
Edi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73dc00bc-c571-72c0-c3de-8e1a35b9e27a
* Version Independent ID: 424eb559-47a7-bcc5-e567-e428e59c11cb
* Content: [E-commerce website running in secured App Service Environment - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/ecommerce-website-running-in-secured-ase#feedback)
* Content Source: [docs/solution-ideas/articles/ecommerce-website-running-in-secured-ase.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/ecommerce-website-running-in-secured-ase.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#199476

**Comment by absheik** [comment]
@edidako  in a similar architecture we have pricing that covers a small, medium and large scenario. https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/ecommerce-scenario#pricing.  This one uses App Service, you were looking at App Services Environment (ASE).  Please make the appropriate changes in the cost calculator for your needs.
