### ISSUE TITLE
Azure for Google Cloud Professionals

### ISSUE THREAD

**Issue by eyusubov** [MicrosoftDocs/architecture-center#2076]
Any references of Azure for GCP Professionals?
Comparison of services will be much appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d100d43f-d48a-3d97-1aea-7a5409fdccc8
* Version Independent ID: 568dcd88-b93c-1d41-44d0-8643dd057a33
* Content: [Azure for AWS professionals - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/)
* Content Source: [docs/aws-professional/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @author
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#201746

**Comment by absheik** [comment]
@eyusubov , look for https://docs.microsoft.com/en-us/azure/architecture/gcp-professional in the next 24 hours.  This page is being launched today.  I will close this issue and track internally for additional feedback.

**Comment by eyusubov** [comment]
Hi @absheik - 
I am not able to access the gcp-professional link:
https://docs.microsoft.com/en-us/azure/architecture/gcp-professional

Getting 404 :(

**Comment by eyusubov** [comment]
Hej @absheik - i am stilling getting 404 when navigating to new url.
Could you check its status?

**Comment by ElYusubov** [comment]
I was able access link last week, it is active.
Thanks for putting this reference into docs!
