### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by gitsathish** [MicrosoftDocs/architecture-center#2077]
The links in the "Related Resources" section at the bottom of this page are all broken.
https://github.com/MicrosoftDocs/architecture-center/blob/master/docs/reference-architectures/data/enterprise-bi-adf.md

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#202600

**Comment by absheik** [comment]
@gitsathish when browsed through the [Azure Docs](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-adf), the links are all working.
