### ISSUE TITLE
EventHubs with Kafka support

### ISSUE THREAD

**Issue by ryancrawcour** [MicrosoftDocs/architecture-center#2078]
now that EventHubs supports Kafka endpoints this document should be updated to reflect the protocols that EventHubs supports to include Kafka 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc25fa01-4939-49b8-2e56-fb2cd8f0ccb1
* Version Independent ID: c4815a00-938c-7f7b-67a5-c16a78871b4a
* Content: [Choosing a real-time message ingestion technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/real-time-ingestion#feedback)
* Content Source: [docs/data-guide/technology-choices/real-time-ingestion.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/real-time-ingestion.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#202928
