### ISSUE TITLE
Azure Search more than just .NET

### ISSUE THREAD

**Issue by ryancrawcour** [MicrosoftDocs/architecture-center#2079]
there is broader support for Azure Search programmability than just .NET

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc525ce2-d021-8e7a-2a88-10b84a2a37e6
* Version Independent ID: 53450f8d-f877-a903-2101-e4265ef6ec75
* Content: [Choosing a search data store - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/search-options#feedback)
* Content Source: [docs/data-guide/technology-choices/search-options.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/search-options.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#202931
