### ISSUE TITLE
log4j: ERROR Error sending logging event to Log Analytics

### ISSUE THREAD

**Issue by shbhmpthk** [MicrosoftDocs/architecture-center#2081]
I am trying to log custom events **directly from databricks notebook**. i have followed all the instruction given. while running the sample code directly in notebook i am getting following error...
![image](https://user-images.githubusercontent.com/26686309/79311802-95113980-7f1b-11ea-90bf-3c00b2e565bf.png)

The code i am trying to run is :

```
import com.microsoft.pnp.logging.Log4jConfiguration
import com.microsoft.pnp.util.TryWith
import org.apache.spark.SparkEnv
import org.apache.spark.internal.Logging
import org.apache.spark.metrics.UserMetricsSystems
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions.window
import org.apache.spark.sql.types.{StringType, StructType, TimestampType}

object StreamingQueryListenerSampleJob extends Logging {

  private final val METRICS_NAMESPACE = "streamingquerylistenersamplejob"
  private final val COUNTER_NAME = "rowcounter"

  def main(args: Array[String]): Unit = {

    // Configure our logging
    TryWith(getClass.getResourceAsStream("/log4j.properties")) {
      stream => {
        Log4jConfiguration.configure(stream)
      }
    }

    logTrace("Trace message from StreamingQueryListenerSampleJob")
    logDebug("Debug message from StreamingQueryListenerSampleJob")
    logInfo("Info message from StreamingQueryListenerSampleJob")
    logWarning("Warning message from StreamingQueryListenerSampleJob")
    logError("Error message from StreamingQueryListenerSampleJob")

    print("Logging done")
  }
}
```

where _log4j.properties_ file is residing in dbfs. Please help me with this.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#204443

**Comment by DixitArora-MSFT** [comment]
@shbhmpthk Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by shbhmpthk** [comment]
[https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs](url)

**Comment by absheik** [comment]
@shbhmpthk please follow the discussion at https://github.com/mspnp/spark-monitoring/issues/28 regarding your issue.

**Comment by DixitArora-MSFT** [comment]
@shbhmpthk  For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by shbhmpthk** [comment]
I have used the code provided in above link. but it is showing weird behavior to me. Sometime it will work fine but if I try to log anything below the level I declared in configuration it will throw above same error. and after that no matter what changes I make in my code, it will only work after I restart my cluster. and sometime it will even keep on running for indefinite period of time.

below is the code 
````
import com.microsoft.pnp.util.TryWith
import com.microsoft.pnp.logging.Log4jConfiguration
import java.io.ByteArrayInputStream
import org.slf4j.LoggerFactory
import org.slf4j.Logger


val loggerName :String = "fromNotebook"
val level : String = "INFO" 
val logType: String = "HerculesDataBricksUAT"

    
    val log4jConfig = s"""
    log4j.appender.logAnalytics=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
    log4j.appender.logAnalytics.layout=com.microsoft.pnp.logging.JSONLayout
    log4j.appender.logAnalytics.layout.LocationInfo=false
    log4j.appender.logAnalytics.logType=$logType
    log4j.additivity.$loggerName=false
    log4j.logger.$loggerName=$level, logAnalytics
    """
    TryWith(new ByteArrayInputStream(log4jConfig.getBytes())) {
      stream => {
        Log4jConfiguration.configure(stream)
      }
    }
val logger = LoggerFactory.getLogger(loggerName);
 logger.info("Exception after ghrologger " + loggerName)
logger.warn("Warn message after ghrologger " + loggerName)
logger.error("Error message after ghrologger " + loggerName)
````

error is same as given above.

**Comment by shbhmpthk** [comment]
> I have used the code provided in above link. but it is showing weird behavior to me. Sometime it will work fine but if I try to log anything below the level I declared in configuration it will throw above same error. and after that no matter what changes I make in my code, it will only work after I restart my cluster. and sometime it will even keep on running for indefinite period of time.
> 
> below is the code
> 
> ```
> import com.microsoft.pnp.util.TryWith
> import com.microsoft.pnp.logging.Log4jConfiguration
> import java.io.ByteArrayInputStream
> import org.slf4j.LoggerFactory
> import org.slf4j.Logger
> 
> 
> val loggerName :String = "fromNotebook"
> val level : String = "INFO" 
> val logType: String = "HerculesDataBricksUAT"
> 
>     
>     val log4jConfig = s"""
>     log4j.appender.logAnalytics=com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender
>     log4j.appender.logAnalytics.layout=com.microsoft.pnp.logging.JSONLayout
>     log4j.appender.logAnalytics.layout.LocationInfo=false
>     log4j.appender.logAnalytics.logType=$logType
>     log4j.additivity.$loggerName=false
>     log4j.logger.$loggerName=$level, logAnalytics
>     """
>     TryWith(new ByteArrayInputStream(log4jConfig.getBytes())) {
>       stream => {
>         Log4jConfiguration.configure(stream)
>       }
>     }
> val logger = LoggerFactory.getLogger(loggerName);
>  logger.info("Exception after ghrologger " + loggerName)
> logger.warn("Warn message after ghrologger " + loggerName)
> logger.error("Error message after ghrologger " + loggerName)
> ```
> 
> error is same as given above.
> @DixitArora-MSFT

@absheik can you help me here
