### ISSUE TITLE
your presentation is awful. totally disjointed.  more confusing than helpful

### ISSUE THREAD

**Issue by mpryandds** [MicrosoftDocs/architecture-center#2087]
Graphic is totally confusing.  what does it take to run a vm simply/.   this is far too confusing.  from the portal it is impossible.  i expect this will cost abot $3.72 a month.  for the VM anyway.  now you're saying more has to be added.  how much is that?  all the mouse clicking is ridiculous.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678f3299-1ff9-8a31-a434-be16f33f90ef
* Version Independent ID: 18de51b9-9bdc-da60-1e2f-383c79b08e54
* Content: [Run a Windows VM on Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/windows-vm#feedback)
* Content Source: [docs/reference-architectures/n-tier/windows-vm.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/windows-vm.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#205399

**Comment by doodlemania2** [comment]
An easy approach to deploying a simple VM in Azure can be the CLI: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-cli. You can also look at pricing for a simple Linux VM via the calculator: https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/
