### ISSUE TITLE
How I may create HPC cluster in Azure portal?

### ISSUE THREAD

**Issue by JuliaRS** [MicrosoftDocs/architecture-center#2088]
I didn't find instruction only arhitecture for HPC cluster

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#205881

**Comment by absheik** [comment]
this Docs page covers a high level overview of Azure HPC capabilities.  https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing
