### ISSUE TITLE
ا

### ISSUE THREAD

**Issue by looody-438** [MicrosoftDocs/architecture-center#2090]
موافق

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: bda44b47-a324-f269-e3f2-df57c0a55321
* Version Independent ID: 76887d70-48fe-dee6-e653-785441723d07
* Content: [Application security in Azure - Azure Architecture Center](https://docs.microsoft.com/ar-sa/azure/architecture/framework/security/applications-services)
* Content Source: [docs/framework/security/applications-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/applications-services.md)
* Service: **architecture-center**
* Sub-service: **cloud-design-principles**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#206636

**Comment by absheik** [comment]
@looody-438 can you please provide additional context on this issue.  I am unable to determine what action I need to take.
