### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Rodrigossz** [MicrosoftDocs/architecture-center#2093]
Hello! This architecture looks strange. The search service should be between Cosmos Db and the web portal. Tks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddae0f8b-245b-751d-8960-dfd0d1f62997
* Version Independent ID: c2e88fc0-e750-9eae-b309-bc08c61ae3cf
* Content: [Retail and e-commerce using Cosmos DB - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/retail-and-e-commerce-using-cosmos-db)
* Content Source: [docs/solution-ideas/articles/retail-and-e-commerce-using-cosmos-db.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/retail-and-e-commerce-using-cosmos-db.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#207248

**Comment by doodlemania2** [comment]
This is on our backlog for improvement. Thanks for reporting. We'll close here for now and will hopefully get it updated soon!
