### ISSUE TITLE
Use of Azure Cosmos DB bulk executor library

### ISSUE THREAD

**Issue by RicardoNiepel** [MicrosoftDocs/architecture-center#2095]
Would be a great benefit to add the usage of [Azure Cosmos DB bulk executor library](https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-overview).

"It significantly reduces the client-side compute resources needed to saturate the throughput allocated to a container. A single threaded application that writes data using the bulk import API achieves 10 times greater write throughput when compared to a multi-threaded application that writes data in parallel while saturating the client machine's CPU."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8baf8aa0-ab4c-0731-a1b9-742953f8a791
* Version Independent ID: 7d2dacc0-9fc9-83b0-7a0f-049006024279
* Content: [Performance tuning - Event streaming with Azure Functions - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/performance/event-streaming)
* Content Source: [docs/performance/event-streaming.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/performance/event-streaming.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#208363
