### ISSUE TITLE
on using generic identifiers

### ISSUE THREAD

**Issue by bagira-kr** [MicrosoftDocs/architecture-center#2096]
there is no such thing as a "business tier" in n-tier architecture.  this is meant to represent the logic layer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [N-tier architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/n-tier#feedback)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#208921

**Comment by ckittel** [comment]
Hello @bagira-kr . You are correct in observing that the layer labeled "Business Tier" in our reference diagram is the moniker we gave to the _business logic tier_.  Likewise, we also call the _presentation tier_ the "Web Tier."  In our example, this is a web application, though multi-tier architectures can be used for other topologies as well (like desktop apps).  The words in the article map back to the reference diagram where we applied these monikers to each of the logical tiers.  

You're free to name your tiers whatever works best for your team to communicate the intent of that logical and/or physical tier in your application - you could even express that naming in resources you choose to represent that tier (e.g. `vmss-appName-business-layer`).

**Comment by bagira-kr** [comment]
Hey all, thanks so much for the followup.

We're in agreement about what they represent, I just might suggest that more abstract identifiers be used pretty universally so that this is more an architectural definition of N-Tier design patterns than a use case / scenario to prevent downstream confusion.  I.e. in most situations a "business" layer's identifier wouldn't be particularly meaningful to the purpose of the layer but a "logic" layer (and also as you mentioned "presentation") would.

The more atomic and generic these patterns become the more usable they become, and I think that starts with more granular and formal definitions.  I'm not sure if that makes as much sense out of my head than in my head :)

**Comment by ckittel** [comment]
Thank you for the clarification.  Your ask is what we thought you were implying, but we didn't want to make any assumptions.  As mentioned, this is tracked in our backlog and will be prioritized against the rest of our backlog.  If you have the means and feel compelled to propose this change via the PR process, you're welcome to; that sometimes leads to faster resolution time than waiting for it to hit the current backlog iteration.

**Comment by DixitArora-MSFT** [comment]
@ckittel Thanks for providing the clarification.

@bagira-kr For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by bagira-kr** [comment]
@DixitArora-MSFT Please re-open this as the issue is not resolved.  Also, please stop closing unresolved issues.

**Comment by DixitArora-MSFT** [comment]
@bagira-kr Chad has already made the clarification. Is there anything more you are looking for ?

**Comment by bagira-kr** [comment]
@DixitArora-MSFT Happy to clarify -- the purpose of an issue tracker is to track outstanding issues.  Chad mentioned that they have a backlogged item to repair this.  This is good, but the issue is not resolved until that backlogged item is worked.  This prevents reported issues from falling through the cracks.  Please keep open until the work is complete.

**Comment by bagira-kr** [comment]
@absheik  

Hello,

I am seeing that the defect in the documentation was not repaired but that this issue is now closed again.  I'm a little confused by this.  Please clarify.  I am unsure of why this issue reporting mechanism exists now.

-C
