### ISSUE TITLE
More info please

### ISSUE THREAD

**Issue by tapialuism** [MicrosoftDocs/architecture-center#2098]
My interest in this has grown, please elaborate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ab85bfa-c5d2-5df4-b3c5-1e229ee58363
* Version Independent ID: 76c1d5fe-00cc-290c-b826-3c8c2fd0104e
* Content: [Predict Length of Stay and Patient Flow - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/predict-length-of-stay-and-patient-flow-with-healthcare-analytics#feedback)
* Content Source: [docs/solution-ideas/articles/predict-length-of-stay-and-patient-flow-with-healthcare-analytics.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/predict-length-of-stay-and-patient-flow-with-healthcare-analytics.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#210165

**Comment by adamboeglin** [comment]
Thank you for your request.  This has been entered in our backlog and we'll work to prioritize it along side our other content.
