### ISSUE TITLE
This page redirected from https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot-with-sql but it talks about reference architecture and not on IoT using SQL as stated in the link

### ISSUE THREAD

**Issue by aviwert** [MicrosoftDocs/architecture-center#2099]
for more, contact me at avi@wertheimer.co.il

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot#feedback)
* Content Source: [docs/reference-architectures/iot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#210187

**Comment by ckittel** [comment]
@aviwert - Not sure I follow what you're suggesting here.  The Link that you provided <https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot-with-sql> lands a user on an IoT + SQL Database page, not <https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot> -- no redirects happening.  Now this is in en-us, maybe there is a redirect happening in another locale?  Can you provide some more detail on this issue so we can take a look at what might be going on.

**Comment by aviwert** [comment]
Hi,

I looked again in these 2 web pages and found the required dissimilarity between both. You may ignore my note.

It is just that both page have the same subject in the header and big part of the beginning of the document is very much the same, so it is a bit confused me.

Thanks for your response and sorry for bothering.

Yours,

Avi Wertheimer

**Comment by ckittel** [comment]
Thank you, have a great weekend.
