### ISSUE TITLE
Infrastructure as Code

### ISSUE THREAD

**Issue by blikenoother** [MicrosoftDocs/architecture-center#2101]
AWS: CloudFormation
Azure: Azure Resource Manager (ARM)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#feedback)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#210617

**Comment by ckittel** [comment]
@blikenoother - Thanks for reaching out.   CloudFormation -> ARM is called out in the DevOps section at https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md#devops-and-application-monitoring -- is there something else you'd like to see there specifically?

**Comment by blikenoother** [comment]
Ohh yes, I missed it before raising this :(

**Comment by doodlemania2** [comment]
Thanks for reaching out though @blikenoother - appreciated!
