### ISSUE TITLE
RSS Feed Button for Architecture Center "What's New" Broken

### ISSUE THREAD

**Issue by matthansen0** [MicrosoftDocs/architecture-center#2106]
The RSS feed button for the https://docs.microsoft.com/en-us/azure/architecture/changelog page gives a 404 response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd7bc22-da10-1d3b-ba22-7d5e374be441
* Version Independent ID: 9f466c91-adc7-0489-5b1e-17633d27c98c
* Content: [What's New in the Azure Architecture Center - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/changelog)
* Content Source: [docs/changelog.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/changelog.md)
* Service: **architecture-center**
* Sub-service: **meta**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by matthansen0** [comment]
Why was this closed?

**Comment by adamboeglin** [comment]
This has been fixed and should be made live shortly.

**Comment by matthansen0** [comment]
Works now - thanks!
