### ISSUE TITLE
Step By step Solutions

### ISSUE THREAD

**Issue by ashishgarg2511** [MicrosoftDocs/architecture-center#2107]
Please Provide step by step for this solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90981e8d-b753-e389-1569-c544fe1c58e6
* Version Independent ID: 10c830e2-8257-2ee2-aae0-0a6e7df69695
* Content: [Forecast Energy and Power Demand - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/forecast-energy-power-demand#feedback)
* Content Source: [docs/solution-ideas/articles/forecast-energy-power-demand.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/forecast-energy-power-demand.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#212581

**Comment by doodlemania2** [comment]
As this is a solution idea, step by step instructions were not prepared. We've captured this as a possible future improvement in our internal backlog. Thanks for the request and we'll get it prioritized.
