### ISSUE TITLE
Wrong HTTP Method in the explanation of exmple

### ISSUE THREAD

**Issue by gpj1** [MicrosoftDocs/architecture-center#2108]
In section "Processing Requests" the last point "An HTTP PUT request to the URI https://adventure-works.com/customers/2/orders to create a new order for this customer. The data must be provided in the request message in x-www-form-urlencoded format" says PUT request. But as per related JSON response example should this be POST instead of PUT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329fde76-a838-59c9-73f6-96424c03a6e0
* Version Independent ID: 203cd155-00c5-286b-96ce-5961c24c6273
* Content: [API implementation guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-implementation)
* Content Source: [docs/best-practices/api-implementation.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/api-implementation.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#212609

**Comment by ckittel** [comment]
Good catch @gpj1 - I've opened a PR for this internally.

**Comment by ckittel** [comment]
This correction will go live with the next production publish of the content. Thanks.
