### ISSUE TITLE
Next Steps Links Broken

### ISSUE THREAD

**Issue by duanecr** [MicrosoftDocs/architecture-center#2109]
The links for "How to use Azure Blob storage" and "How to encode an asset using Media Encoder" take to a main page instead of specific articles.  I didn't try other links but they all need to be verified and fixed if broken as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video#feedback)
* Content Source: [docs/solution-ideas/articles/digital-media-video.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-video.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#212901

**Comment by DixitArora-MSFT** [comment]
@duanecr PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
