### ISSUE TITLE
AWS Macie comparison

### ISSUE THREAD

**Issue by wayneme75** [MicrosoftDocs/architecture-center#2112]
what is the comparative AWS Macie service in Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#213411

**Comment by DixitArora-MSFT** [comment]
@wayneme75 Azure Advanced Threat Protection https://azure.microsoft.com/features/azure-advanced-threat-protection/

This is also mentioned in this issue and PR

https://github.com/MicrosoftDocs/architecture-center/issues/737

https://github.com/MicrosoftDocs/architecture-center/pull/925/files

For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
