### ISSUE TITLE
W3C Trace-Context is no longer a proposal

### ISSUE THREAD

**Issue by damonbarry** [MicrosoftDocs/architecture-center#2113]
This article says:

> There is currently no standard HTTP header for correlation IDs, although a W3C proposal exists.

It looks like [W3C Trace-Context](https://www.w3.org/TR/trace-context/) is an official Recommendation as of February.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1160782c-3fd6-3236-1cbd-6ddecf56c3db
* Version Independent ID: cbcfb4e3-4fb5-9427-3a17-cb296339b1ad
* Content: [Monitoring a microservices application in AKS - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring#distributed-tracing)
* Content Source: [docs/microservices/logging-monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/logging-monitoring.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#213469
