### ISSUE TITLE
Kubernetes-KeyVault-FlexVolume deprecated

### ISSUE THREAD

**Issue by fduran** [MicrosoftDocs/architecture-center#2114]
"For more information, see the Kubernetes-KeyVault-FlexVolume project on GitHub." but this project https://github.com/Azure/kubernetes-keyvault-flexvol is deprecated in favour of https://github.com/Azure/secrets-store-csi-driver-provider-azure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks#feedback)
* Content Source: [docs/reference-architectures/microservices/aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/microservices/aks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#213599

**Comment by DixitArora-MSFT** [comment]
@fduran PR has been created for this which will address this. Thanks so much for providing the feedback that help us in improving the documentation. For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
