### ISSUE TITLE
Include Azure Data Explorer in this ref article

### ISSUE THREAD

**Issue by ManojRaheja** [MicrosoftDocs/architecture-center#2115]
The diagram is a good representation of a generic IoT reference architecture. Please include links to the Azure Data Explorer documentation and add recommendations for an alternate option as a warm store. If you have any questions, please reach out to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b30c2a4-8c2c-d041-b7a6-2766b9aa9bb6
* Version Independent ID: 2cdc5376-7817-7f86-41c1-7ee492833eda
* Content: [IoT Architecture – Azure IoT Subsystems - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-iot-subsystems#feedback)
* Content Source: [docs/solution-ideas/articles/azure-iot-subsystems.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/azure-iot-subsystems.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#214543
