### ISSUE TITLE
Include Azure Data Explorer in this pattern

### ISSUE THREAD

**Issue by ManojRaheja** [MicrosoftDocs/architecture-center#2116]
Azure Data Explorer is part of the new real-time analytics pattern which is not reflected on this page. Please add it and ping me if you have any questions. - maraheja@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4bb287-fa40-af1d-0af9-e8bc30cfb33e
* Version Independent ID: 12ab4c06-2e95-bb73-f62a-2d1eb79bc735
* Content: [Real Time Analytics on Big Data Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics#feedback)
* Content Source: [docs/solution-ideas/articles/real-time-analytics.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/real-time-analytics.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#214545
