### ISSUE TITLE
Can we have the detail implementation steps

### ISSUE THREAD

**Issue by forgotten-warrior** [MicrosoftDocs/architecture-center#2117]
It would be great if this article goes with detailed steps, benefits, challenges ... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca76f303-efb9-b535-3025-52ca002a6ed9
* Version Independent ID: 6b05002e-45a5-ec82-a8cd-3d82544ea296
* Content: [Archive on-premises data to cloud - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/backup-archive-on-premises)
* Content Source: [docs/solution-ideas/articles/backup-archive-on-premises.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/backup-archive-on-premises.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#214633

**Comment by doodlemania2** [comment]
As this was a solution idea, no implementation steps were provided. We've captured this in our internal backlog for possible future enhancements and hope to get it updated ASAP. Closing for now.
