### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/architecture-center#2118]
The link https://docs.microsoft.com/en-us/azure/architecture/browse/#windows-virtual-desktop directs to this page which should be Windows Virtual Desktop. Should this page be updated to reference the new WVD product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cadda1fe-e283-6b44-a0e0-671f99fde321
* Version Independent ID: e16a2608-1013-7a6b-d0c9-8acc77a12429
* Content: [Linux virtual desktops with Citrix - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/linux-vdi-citrix)
* Content Source: [docs/example-scenario/infrastructure/linux-vdi-citrix.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/infrastructure/linux-vdi-citrix.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @miguelangelopereira
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#214679

**Comment by DixitArora-MSFT** [comment]
Hi @win2000b Thanks for your feedback. We will review and update as appropriate.

**Comment by adamboeglin** [comment]
This will be fixed in an upcoming release.
