### ISSUE TITLE
For PostgreSQL

### ISSUE THREAD

**Issue by hamidyaseen** [MicrosoftDocs/architecture-center#2119]
It very nice to know more about this direct and simple architecture for using PostgreSQL for mobile apps.
Thanks
Regards
 Hamid  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e325f722-cf4e-9e25-a612-3f832c1be677
* Version Independent ID: 7c43cd20-badd-7585-a7e9-8e1787f62def
* Content: [Scalable web and mobile applications using Azure Database for PostgreSQL - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql#feedback)
* Content Source: [docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#215162

**Comment by absheik** [comment]
@hamidyaseen here a tutorial which shows how to deploy a data-driven Python (Django) web app to Azure App Service and connect it to an Azure Database for PostgreSQL database.
https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-python-postgresql-app?tabs=bash
