### ISSUE TITLE
SVG Request

### ISSUE THREAD

**Issue by nikmithani** [MicrosoftDocs/architecture-center#2120]
Can we get an svg of this architecture please. Tks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524d1f97-ce37-f9ac-cf05-d33665eb34df
* Version Independent ID: fe4cc63f-a4b1-c30e-f39f-f4c3de1c57be
* Content: [Serverless web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app#feedback)
* Content Source: [docs/reference-architectures/serverless/web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/serverless/web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#215502
