### ISSUE TITLE
Use of azbb in these examples

### ISSUE THREAD

**Issue by mschulz531** [MicrosoftDocs/architecture-center#2124]
I found a recommendation in other Microsoft docs: "Don't use azbb - it is in sustain mode and the npm package is out of date"

This documentation should be updated to reflect that.  Someone could waste a lot of time following these instructions only to encounter an error while deploying the generated template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#216066
