### ISSUE TITLE
Service Fabric to AppService using .netcore

### ISSUE THREAD

**Issue by umashankariv** [MicrosoftDocs/architecture-center#2126]
Thanks for the document, do you have example/document to migrate a service fabric application to AppService

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19b08a2e-bd6c-5908-b03f-c1c711aee746
* Version Independent ID: f79fa09d-91c5-abb7-0758-16ca6a9d4f34
* Content: [Migrate an Azure Cloud Services application to Azure Service Fabric - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/service-fabric/migrate-from-cloud-services#feedback)
* Content Source: [docs/service-fabric/migrate-from-cloud-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/service-fabric/migrate-from-cloud-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#217556

**Comment by DixitArora-MSFT** [comment]
@umashankariv various considerations before you consider migrating your applications to Azure App Service

**Port Bindings** - Azure App Service support port 80 for http and port 443 for HTTPS traffic. If you have sites using any other port after migration to Azure App Service, do remember that these are the only ports that will be used.

**Usage of assemblies in the GAC (Global Assembly Cache)**- This is not supported. Consider bin placing the assemblies in the local bin.

**IIS5 Compatibility Mode**- IIS5 Compatibility Mode is not supported. In Azure App Service each Web App and all the applications under it run in the same worker process with a specific set of application pool settings.

**IIS7+ Schema Compliance-** One or more elements and/or attributes are being used which are not defined in Azure App Service IIS schema. Consider using XDT transforms.

**Single Application Pool Per Site**- In Azure App Service each Web App and all the applications under it, run in the same application pool. In case you have applications with different application pool in IIS, consider establishing a single application pool with common settings or creating a separate Web App for each application.

**COM and COM+ components**- Azure App Service does not allow the registration of COM components on the platform. If your site(s) or application(s) make use of any COM components, these would need to be rewritten in managed code and deployed with the site or application.

**ISAPI Extensions**- Azure App Service can support the use of ISAPI Extensions, however, the DLL(s) need to be deployed with your site and registered via the web.config.

Once the above limitations have been taken into consideration, you will need to migrate your applications. The easiest form of migrating is through Azure App Service Migration Assistant. The Azure App Service Migration site and the tool can be utilized to migrate sites from Windows and Linux web servers to Azure App Service. As part of the migration the tool, this will create Web Apps and databases on Azure and publish content and publish your database.

This tool is available for both Windows server and Linux servers. The migration tool for Windows Server works either from the local machine or from a remote machine. It allows you to migrate sites from IIS running on Windows Server 2003 onwards.

Please refer to Windows Site Migration Tool for details.

The Linux site migration tool allows you to migrate sites from Linux web servers running Apache to the cloud. Only Apache is supported at this point in time.

Please refer to Linux Site Migration Tool for details.
