### ISSUE TITLE
SignalR Service details

### ISSUE THREAD

**Issue by ashuisonline** [MicrosoftDocs/architecture-center#2127]
It would be great if you can include SingalR service architectural and implementation details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ea26cb-1cc0-2616-d0b4-cd50f1194a75
* Version Independent ID: 01eb1d9d-060a-01a8-aa50-68e017b2db38
* Content: [Messaging - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/messaging#feedback)
* Content Source: [docs/solution-ideas/articles/messaging.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/messaging.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#217570

**Comment by s-hubert** [comment]
I can imagine a similar strategy as presented in https://youtu.be/6w6E_B55p0E?t=531 by Netflix using their Zuul server implementation. Have a separate SignalR service infrastructure that is a subscriber to the event queue (Azure Redis Cache in this case) and deliver those to the clients - but keep it totally separated not breaking the API gateway in other places of your app infrastructure.

**Comment by josevarela** [comment]
@ashuisonline, Using the SignalR service to implement a messaging solution is showcased in the [Real-time Web Dashboard ](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-web-dashboard) solution idea. Let us know, through the feedback on that page, if you'd like to see us expand this article with more information (implementation details, pricing guidance, code examples, etc)
