### ISSUE TITLE
Grammar check

### ISSUE THREAD

**Issue by thnagler** [MicrosoftDocs/architecture-center#2130]
Use cloud provider identity source for third parties
Use cloud identity services ...least privilege approach and clear clearly differentiation of external accounts...

What is "clear clearly"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def43e94-5049-5848-e385-dda52e7bd3dc
* Version Independent ID: 32cea313-ec24-f5b2-02bf-3cbe5a355a13
* Content: [Identity and Access Management in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/identity#feedback)
* Content Source: [docs/framework/security/identity.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/identity.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#217935
