### ISSUE TITLE
Broken link to Azure Cache for Redis

### ISSUE THREAD

**Issue by peteke** [MicrosoftDocs/architecture-center#2133]
The link: "How to create a Web App with Azure Cache for Redis" https://docs.microsoft.com/api/Redirect/documentation/articles/cache-web-app-howto is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a55fba-7e30-02ff-b525-f00f19610b15
* Version Independent ID: 42905489-5272-bee8-531f-b4be826eeb7f
* Content: [Scalable Episerver marketing website - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-marketing-episerver#feedback)
* Content Source: [docs/solution-ideas/articles/digital-marketing-episerver.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-marketing-episerver.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#219914
