### ISSUE TITLE
Wrong info about NoSQL

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/architecture-center#2135]
You say about NoSQL:
"(The term isn't quite accurate, because many non-relational data stores support SQL compatible queries.)"
I thought it stood for "Not Only SQL", in which case it is completely accurate!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf39ec6-5a99-ca3d-8913-9021898dcfbb
* Version Independent ID: 7aa2e806-302b-23b3-7002-1dfed4b7dd28
* Content: [Azure Data Architecture Guide - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/data-guide/)
* Content Source: [docs/data-guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#221589
