### ISSUE TITLE
This article should mention or have a link to Azure Media Services documentation.

### ISSUE THREAD

**Issue by tmart-ops** [MicrosoftDocs/architecture-center#2136]
The first "Next steps" step should probably be to visit the Media Services Overview link which provides an abundance of relevant information to this article.
https://docs.microsoft.com/en-us/azure/media-services/latest/media-services-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video#feedback)
* Content Source: [docs/solution-ideas/articles/digital-media-video.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-video.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#221999

**Comment by DixitArora-MSFT** [comment]
@tmart-ops Thanks for the feedback and for now closing this issue and will keep the internal DevOps bug open to ensure your request feedback is captured.
