### ISSUE TITLE
Updated Articles links return 404 error

### ISSUE THREAD

**Issue by timstockford** [MicrosoftDocs/architecture-center#2138]
Clicking any of the "New Article" or "Updated Articles" links on this page result in 404 errors.
Tried Edge Chromium and Google Chrome on Windows 10 and Chrome on Android.
Navigating to other pages in the Architecture centre seem to be fine.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd7bc22-da10-1d3b-ba22-7d5e374be441
* Version Independent ID: 9f466c91-adc7-0489-5b1e-17633d27c98c
* Content: [What's New in the Azure Architecture Center - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/changelog#feedback)
* Content Source: [docs/changelog.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/changelog.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#222011

**Comment by DixitArora-MSFT** [comment]
@timstockford I have tried many links in "New Article" or "Updated Articles" and it is working fine for me without any issue in Chrome.

For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by timstockford** [comment]
Thanks @DixitArora-MSFT . I have just retested  and it seems to be working fine for me too. Thanks.
