### ISSUE TITLE
Azure pattern to Setup IoT devices and Purdue Model

### ISSUE THREAD

**Issue by vinodmelvinanir** [MicrosoftDocs/architecture-center#2139]
Is there a azure patterns to setup IoT devices and connect to cloud while conforming Purdue model ,when IoT Devices are in Level 1 or Level 0 and Azure is at Level 4/5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0b0e3ea-63c1-60ee-f1f2-29affd74aa5d
* Version Independent ID: ce0a6a10-a89f-97b8-8f39-b9930b77e1d5
* Content: [Big data architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/big-data#feedback)
* Content Source: [docs/guide/architecture-styles/big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/big-data.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#222016

**Comment by DixitArora-MSFT** [comment]
@vinodmelvinanir There is already an [Azure IoT Reference Architecture Guide](https://azure.microsoft.com/en-us/blog/azure-iot-reference-architecture-update/). 

For now I will proceed with closure of this and If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by jocontr** [comment]
@vinodmelvinanir here is an interesting article for reference https://www.automationworld.com/factory/iiot/article/21132891/is-the-purdue-model-still-relevant 

In terms of an existing architectural pattern, we do not currently have one that reflect such model.
