### ISSUE TITLE
AWS Amplify comparison

### ISSUE THREAD

**Issue by wattcode** [MicrosoftDocs/architecture-center#2141]
Could you please provide a comparison to [AWS Amplify](https://aws.amazon.com/amplify/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#222773

**Comment by DixitArora-MSFT** [comment]
@wattcode Thanks for the feedback and for now closing this issue and will keep the internal DevOps bug open to ensure your request feedback is captured.
