### ISSUE TITLE
Please provide implementation details and code examples

### ISSUE THREAD

**Issue by diuleilomo** [MicrosoftDocs/architecture-center#2142]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839bcfd0-caf7-c1f2-0dab-3340d9f8f528
* Version Independent ID: 8631e812-4b30-9c93-a007-203bc05a238e
* Content: [Social App for Mobile and Web with Authentication - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/social-mobile-and-web-app-with-authentication#feedback)
* Content Source: [docs/solution-ideas/articles/social-mobile-and-web-app-with-authentication.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/social-mobile-and-web-app-with-authentication.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#222836

**Comment by doodlemania2** [comment]
As this was a solution idea, no implementation details were prepared. We've taken this into our backlog for a future enhancement. Thanks for the interest in it! Closing for now.

**Comment by DavidPaf** [comment]
Any progress for this in 2022? 

Hope there will be Django and Reactjs example.
