### ISSUE TITLE
Details and implementation steps needed to try out in a sandbox environment

### ISSUE THREAD

**Issue by vikramdarade** [MicrosoftDocs/architecture-center#2143]
Need details and Implementation Blue prints to try out in a sandbox environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks#feedback)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/microservices-with-aks.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#223210

**Comment by absheik** [comment]
@vikramdarade a slight variant of this Solution Idea is at https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks.  This Reference architecture has the Reference Implementation at https://github.com/mspnp/microservices-reference-implementation.  Closing this issue and will keep the internal DevOps bug open to ensure your request feedback is captured.
