### ISSUE TITLE
How about Azure Data Explorer in this echo system

### ISSUE THREAD

**Issue by udaykumar54** [MicrosoftDocs/architecture-center#2144]
How about Azure Data Explorer in this echo system. When to choose between Azure Synapse vs Azure Data Explorer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#223560

**Comment by absheik** [comment]
@udaykumar54 [Azure Synapse is the next version of Azure SQL Data Warehouse](https://docs.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-overview-what-is).  Whereas Azure Data Explorer is a fast and highly scalable data exploration service for log and telemetry data and other large datasets.  You can leverage it in the Synapse process workflow as illustrated [here](https://docs.microsoft.com/en-us/azure/data-explorer/data-explorer-overview#data-warehousing-workflow).
