### ISSUE TITLE
Content is outdated

### ISSUE THREAD

**Issue by anniexudan** [MicrosoftDocs/architecture-center#2145]
New Azure Services like Azure Synapse Analytics, Power BI Premium Capacity need to be added for OLAP workloads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560fb3dc-3a89-aa28-f4c1-564f7920f5ca
* Version Independent ID: b5255403-369f-9324-fb16-02526b24dba6
* Content: [Online analytical processing (OLAP) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-analytical-processing#feedback)
* Content Source: [docs/data-guide/relational-data/online-analytical-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/relational-data/online-analytical-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#223641

**Comment by DixitArora-MSFT** [comment]
@anniexudan Thanks for the feedback and for now closing this issue and will keep the internal DevOps bug open to ensure your request feedback is captured.
