### ISSUE TITLE
Jenkins diagram on Market place is outdated

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#2149]
This page has a link which leads to https://azuremarketplace.microsoft.com/en-us/marketplace/apps/azure-oss.jenkins where there are 2 Diagrams for Jenkins :

1. [One including Service Fabric](https://store-images.s-microsoft.com/image/apps.44505.8bd7a3e6-2304-4160-abbf-83214f80cd4f.4f485563-e5d5-477c-ae3a-aa0da067632f.a3a05e44-26b9-423f-9977-4bca2c767c25), SF should be removed
2. [One including Contrainer Service ](https://store-images.s-microsoft.com/image/apps.35285.8bd7a3e6-2304-4160-abbf-83214f80cd4f.4f485563-e5d5-477c-ae3a-aa0da067632f.46508ac7-3803-4138-b921-f32c931ff9a2)( former ACS) which should be AKS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c5ba03-a6ce-5d5c-fb83-e3e4e13da80d
* Version Independent ID: 6f235fae-19ab-9b12-72a9-f9962076ef5b
* Content: [Run a Jenkins server on Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/jenkins)
* Content Source: [docs/example-scenario/apps/jenkins.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/jenkins.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#225132

**Comment by adamboeglin** [comment]
Unfortunately, we don't manage the architecture diagrams for Jenkins in the Marketplace.  Please contact the marketplace if you'd like for them to be updated.
