### ISSUE TITLE
Partitioning Azure table storage : entity with one natural key

### ISSUE THREAD

**Issue by gpj1** [MicrosoftDocs/architecture-center#2150]
Documentation https://docs.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning-strategies#partitioning-azure-table-storage states that "If an entity has one natural key, then use it as the partition key and specify an empty string as the row key". But it also states that the combination of partition key and row key should be unique. Isn't the usage of empty string as row key violation of this constraint unless we want separate partition for each entity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef578ecf-7b41-cac8-ba5d-2e132c337b1e
* Version Independent ID: f325ab09-f55d-42ce-5892-a116d4958d6c
* Content: [Data partitioning strategies - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning-strategies)
* Content Source: [docs/best-practices/data-partitioning-strategies.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/data-partitioning-strategies.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#226844

**Comment by absheik** [comment]
@gpj1 thanks for opening this issue.  
The empty Row Key covers a very unique scenario.  It is particularly useful in range queries as described [here](https://docs.microsoft.com/en-us/rest/api/storageservices/designing-a-scalable-partitioning-strategy-for-azure-table-storage#range-partitions). Table storage [allows empty string](https://docs.microsoft.com/en-us/rest/api/storageservices/designing-a-scalable-partitioning-strategy-for-azure-table-storage#yyy) as Partition Key and Row Key.
