### ISSUE TITLE
KEDA

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#2151]
As article named "elastic", maybe KEDA (event driven auto-scaling) can be at least mentioned here?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46ad00f8-c495-75e6-4f12-7555fce7f92f
* Version Independent ID: e2d14901-6be8-cae3-93ab-76d28edb5653
* Content: [Elastic demand handling with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/aks-demand-spikes)
* Content Source: [docs/solution-ideas/articles/aks-demand-spikes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/aks-demand-spikes.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **stellal**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#227280

**Comment by DixitArora-MSFT** [comment]
@SychevIgor Closing this issue and will keep the internal DevOps bug open to ensure your request feedback is captured.
