### ISSUE TITLE
The Architecture Diagram is not visible properly 

### ISSUE THREAD

**Issue by rashmip22** [MicrosoftDocs/architecture-center#2152]
As the background is black, the architecture diagram is not visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcaeba82-a634-d73a-77fd-a07258be2c17
* Version Independent ID: 4ba78d8a-60c9-9df8-1d2c-0a375a094acb
* Content: [DevSecOps in Azure - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-azure)
* Content Source: [docs/solution-ideas/articles/devsecops-in-azure.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/devsecops-in-azure.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **asegala**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#227545

**Comment by rashmip22** [comment]
> 
<img width="528" alt="devsecops-in-azure" src="https://user-images.githubusercontent.com/25289145/83091846-c2740a00-a0b9-11ea-96d1-2ef1f19b1d9a.png">
