### ISSUE TITLE
link to "Set up Azure DevOps" is broken

### ISSUE THREAD

**Issue by BillDarcy** [MicrosoftDocs/architecture-center#2153]
The link to "Set up Azure DevOps" is broken. On this page, the link is https://www.visualstudio.com/docs/setup-admin/get-started
It gets redirected to https://docs.microsoft.com/en-us/azure/devops/?view=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900b3b20-5693-1beb-0b4b-161548a7d14f
* Version Independent ID: 94d5daef-6e7b-23d2-58bd-b2796bbbc7e1
* Content: [Dev-Test deployment for testing PaaS solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-paas)
* Content Source: [docs/solution-ideas/articles/dev-test-paas.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/dev-test-paas.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#
