### ISSUE TITLE
Is Databricks query logs available in diagnostic setting?

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [MicrosoftDocs/architecture-center#2154]
Hi,

We have enabled diagnostic setting for our Azure Databricks workspace and the logs are exported to Log Analytics Workspace. However when we go to Log Analytics workspace, we are not able to see logs of queries run in Databricks. Would you please suggest how we can get this information?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#227950

**Comment by CharmanderJieniJieni** [comment]
Sorry I have no access to the devops workspace. Can I have more context for
that?

**Comment by jocontr** [comment]
Hi @CharmanderJieniJieni , without having additional context I would suggest studying the possibility of expanding these [https://github.com/mspnp/spark-monitoring/tree/master/src/spark-listeners/src/main/scala/org/apache/spark/metrics](https://github.com/mspnp/spark-monitoring/tree/master/src/spark-listeners/src/main/scala/org/apache/spark/metrics) . In terms of spark query metrics; could you share a link to the subset you are interested?
