### ISSUE TITLE
Content is broken

### ISSUE THREAD

**Issue by jfoarde** [MicrosoftDocs/architecture-center#2155]
I'm interested in this solution, but a lot of the content has been moved or is broken.  Has Microsoft abandoned this or is there a newer version somewhere else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495425b0-36b2-9391-b1ef-b2ec2e7f3423
* Version Independent ID: e9ab6970-e1d7-5780-606b-50e35f0676fd
* Content: [Anomaly Detection in Real-time Data Streams - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/anomaly-detection-in-real-time-data-streams)
* Content Source: [docs/solution-ideas/articles/anomaly-detection-in-real-time-data-streams.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/anomaly-detection-in-real-time-data-streams.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#228149

**Comment by absheik** [comment]
@jfoarde thanks for creating the issue.  The Azure Anomaly Detection API's have moved form Cortana Analytics to a dedicated API.  You can find the documentation at https://docs.microsoft.com/en-us/azure/cognitive-services/anomaly-detector/.  We will update this page to point to the the current API

**Comment by absheik** [comment]
We are pulling this content out as there are significant changes in the API and needs a complete rewrite.
