### ISSUE TITLE
Switch to immersive reader in Edge, Japanese and English alternate

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/architecture-center#2156]
The comments below were machine-translated

@cweuphoria commented on [Thu May 28 2020](https://github.com/MicrosoftDocs/architecture-center.ja-jp/issues/49)

When you switch to immersive reader in Edge, Japanese and English are mixed alternately.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT 参照アーキテクチャ - Azure Reference Architectures](https://docs.microsoft.com/ja-jp/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.md](https://github.com/microsoftdocs/architecture-center.ja-jp/blob/live/docs/reference-architectures/iot.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

---

@srvbpigh commented on [Fri May 29 2020](https://github.com/MicrosoftDocs/architecture-center.ja-jp/issues/49#issuecomment-635809206)

Hello, @cweuphoria
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#228620

**Comment by cweuphoria** [comment]
Thank you for taking care of this.  Just a side note to the issue itself, it might be smarter not to cross out to change the subject as users may feel disrespected reporting with their local languages.  Please note that the reporting form presented was in their languages.

**Comment by adamboeglin** [comment]
Thank you for submitting this.

We're tracking this issue internally and have it on our backlog to review.
