### ISSUE TITLE
Implementation details for AuthN/AuthZ and .Net Core backend

### ISSUE THREAD

**Issue by aaRopi** [MicrosoftDocs/architecture-center#2159]
Hi,

Thank you for the article. It's clear on how this can be setup. However, if you can also provide some implementation details on the following tech stack, that would be much appreciated!

1. Backend with RestApi services built in .Net Core (hosted on AppService of course).
2. AuthN/AuthZ to manage users, along with authentication provided by Facebook and Google.
3. Xamarin app which manages AuthN using client sdk's from Facebook and Google.

Question: Where would the users be managed? How will they be connected to the backend data models to their data?

Question: According to this link: https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization , .Net Core does not support populating the current user. How will the whole tree work without that then?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839bcfd0-caf7-c1f2-0dab-3340d9f8f528
* Version Independent ID: 8631e812-4b30-9c93-a007-203bc05a238e
* Content: [Social App for Mobile and Web with Authentication - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/social-mobile-and-web-app-with-authentication#feedback)
* Content Source: [docs/solution-ideas/articles/social-mobile-and-web-app-with-authentication.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/social-mobile-and-web-app-with-authentication.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#230318

**Comment by MarileeTurscak-MSFT** [comment]
Thanks! Closing this out since it is being tracked internally. (Feel free to reopen if needed.)

**Comment by aaRopi** [comment]
Thank you for the quick replies! 

Just a note, the referenced [bug](https://dev.azure.com/ceapex/0ed5b4a0-21d8-4dc2-8b95-5fdb8449e2bd/_workitems/edit/230318) is not accessible to me. Anyway, if you could also give a timeline on when you expect this might be resolved, that would be great! :)
