### ISSUE TITLE
Updated pricing options

### ISSUE THREAD

**Issue by griffinbird** [MicrosoftDocs/architecture-center#2160]
[Enter feedback here]
Need to update the pricing section to also include serverless and autoscaling tiers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#230444

**Comment by DixitArora-MSFT** [comment]
@griffinbird Thanks for your feedback. Closing this issue and will keep the internal DevOps bug open to ensure your request feedback is captured.
