### ISSUE TITLE
typo on caching

### ISSUE THREAD

**Issue by Miteshc1** [MicrosoftDocs/architecture-center#2161]
Cachicn should read "caching" i think..
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98309d8-d1f8-87f7-2662-c12462d11bbd
* Version Independent ID: 7c0ed47b-e6ad-f62d-b8eb-e3776c69a4bf
* Content: [Checklist - Optimize cost - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/optimize-checklist)
* Content Source: [docs/framework/cost/optimize-checklist.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/optimize-checklist.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#231124

**Comment by josevarela** [comment]
Fixes issue https://github.com/MicrosoftDocs/architecture-center/issues/2161

**Comment by absheik** [comment]
closed per above pr.
