### ISSUE TITLE
Retry Exponential from Azure function app (node js)

### ISSUE THREAD

**Issue by itaym8** [MicrosoftDocs/architecture-center#2162]
[Enter feedback here]
Hello,

There is any way to use retry exponential for messages receiving in function app (Service Bus Trigger) from the function without using microsoft sdk (bindings / internal settings) ?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#231204

**Comment by absheik** [comment]
@itaym8, Please review this closed issue where Jeff provides a solution https://github.com/Azure/azure-functions-host/issues/2192.  Your ask is to do this without using SDK, don't understand why.  Can you elaborate?

**Comment by absheik** [comment]
@MarileeTurscak-MSFT can you please remove the doc-bug tag?  This is an issue where the customer is looking to implement the solution in manner that is unique.

**Comment by itaym8** [comment]
> @itaym8, Please review this closed issue where Jeff provides a solution [Azure/azure-functions-host#2192](https://github.com/Azure/azure-functions-host/issues/2192). Your ask is to do this without using SDK, don't understand why. Can you elaborate?

Sure. If I already use Azure funcrion (in Azure), then why should I use an external sdk ?
I just want to verify that my solution was good enough and make sure there is no build-in solution to do that (like use the bindings, etc.).
Thanks.

**Comment by jocontr** [comment]
Hi @itaym8 , you will not need an additional SDK. What is described above is part of the Azure SDK. Thank you.
