### ISSUE TITLE
Missing code example

### ISSUE THREAD

**Issue by mojjeietuna** [MicrosoftDocs/architecture-center#2163]
Should include a sample code example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608c01ec-d21f-7bdf-a700-7288222ad27c
* Version Independent ID: 94920b97-adc0-3899-f8bd-aff821f3435b
* Content: [Cross-platform Chat - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cross-platform-chat)
* Content Source: [docs/solution-ideas/articles/cross-platform-chat.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/cross-platform-chat.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#232335

**Comment by absheik** [comment]
@mojjeietuna , here is a more detailed chat bot example with code.  https://docs.microsoft.com/en-us/azure/architecture/example-scenario/ai/commerce-chatbot
