### ISSUE TITLE
Typo in Reference Architecture

### ISSUE THREAD

**Issue by nipunas** [MicrosoftDocs/architecture-center#2165]
In the reference architecture diagram for the first step it mentions as Azure Data Lake Storage but in the Data Flow step 1 it mentions as Azure Blob Storage. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data#feedback)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#232454

**Comment by MarileeTurscak-MSFT** [comment]
Thanks! I made a pull request to update this and it looks like @absheik created a work item as well.

https://github.com/MicrosoftDocs/architecture-center-pr/pull/1340
