### ISSUE TITLE
Will it be only event store or some persistence as well ?

### ISSUE THREAD

**Issue by mkdewangan** [MicrosoftDocs/architecture-center#2166]
One example --
Suppose in a ecommerce store like amazon when a new prime member is added , will it be just an entry in event store or this info persisted in DB ? If it is just event store , how to fire query like get total number of prime customer from california ?
Similarly
If existing customer add a new credit card for payment ,  we enter a new event "a payment method is added for customer A" with details in event store.
In UI when we are displaying customer's all payment methods , will this info be coming to replay the events / snapshots ? will it not be very complex ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing)
* Content Source: [docs/patterns/event-sourcing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/event-sourcing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#232829

**Comment by absheik** [comment]
@mkdewangan this Event Sourcing Pattern is an eventually consistent pattern.  If you need real time or near real time processing please review https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/real-time-processing
