### ISSUE TITLE
Feedback for Personalized Offers 

### ISSUE THREAD

**Issue by maloyhalder** [MicrosoftDocs/architecture-center#2167]
The sequence of steps is not clear. It seems someone has rushed to create these diagrams but didn't think through how it will look to someone who has started new. 
I think we should have two diagrams 

1. What's happening before the model is put into the production server. ML and previous usage history helped build the model.

2. When it's in deployed:
We have the following steps
i. Azure function gets triggered per user and sends the information to Queue
ii. Queue sends information to Another Azure Function which applied the model and finds of personalized offer and sends it back to the user
iii. How Stream Analytics fits in here is confusing? Perhaps live data first goes through stream analytics and then An Azure function gets triggered if it fits a certain condition. 
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 831d2c33-e3c1-f325-57af-b97c8b12d4ff
* Version Independent ID: 66882a3f-18d9-8aa4-9b3e-6c8e428a17cb
* Content: [Personalized Offers - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/personalized-offers)
* Content Source: [docs/solution-ideas/articles/personalized-offers.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/personalized-offers.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#233004

**Comment by absheik** [comment]
@maloyhalder thanks for creating the issue.  A more detailed implementation and a commentary on the architecture is found at https://github.com/Azure/azure-ai-personalized-offers.  Hope this answers your questions.
