### ISSUE TITLE
architecture visio

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/architecture-center#2170]
Moved from here: https://github.com/MicrosoftDocs/architecture-center.pl-pl/issues/2

@maciejgajownik commented 9 hours ago
there is wrong visio file linked for this architecture

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Multi-region N-tier application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server#related-resources)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/multi-region-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#233798

**Comment by absheik** [comment]
@CeciAc , the linked file has several tabs.  One of the tabs named "Windows multi-region" has the diagram referred to in this article.
