### ISSUE TITLE
Image text cut off

### ISSUE THREAD

**Issue by eric-camplin** [MicrosoftDocs/architecture-center#2171]
**Low priority:** https://docs.microsoft.com/en-us/azure/architecture/guide/ the image has the text cut off of the last item on the image "**Microsoft Azure Well Architected Frame**work" is cut off in the middle of the word "Framework."
![image](https://user-images.githubusercontent.com/12022944/84080812-a57ce800-a991-11ea-9cac-9c5f055e78d1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Guide - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#233842
