### ISSUE TITLE
Should there be a load balancer that from the DB?

### ISSUE THREAD

**Issue by ps2cheung** [MicrosoftDocs/architecture-center#2174]
[Enter feedback here]
Should there be a load balancer that from the DB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9285685-ad3d-5897-745e-bd7a8254370e
* Version Independent ID: 375f014d-bd6e-8bb8-b59d-64cd4b9197b2
* Content: [Build high availability into your BCDR strategy - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/build-high-availability-into-your-bcdr-strategy)
* Content Source: [docs/solution-ideas/articles/build-high-availability-into-your-bcdr-strategy.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/build-high-availability-into-your-bcdr-strategy.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
@ps2cheung "**Configure zone-redundant SQL DB**" does not need a load balancer in front of the database layer. https://docs.microsoft.com/en-us/azure/azure-sql/database/high-availability-sla
