### ISSUE TITLE
Links are referring to the wrong page

### ISSUE THREAD

**Issue by ibawwad** [MicrosoftDocs/architecture-center#2175]
### Under the section _For more information about running N-tier applications on Azure:_
The links are messed up together:

**This link:** Run Windows VMs for an N-tier application >> leads to [Windows N-tier application on Azure with SQL Server](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/n-tier-sql-server)

**This link:** Windows N-tier application on Azure with SQL Server >> [leads to Linux N-tier application in Azure with Apache Cassandra](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/n-tier-cassandra)

This link: 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [N-tier architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/n-tier)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#235164
