### ISSUE TITLE
Azure App Center not comparable to Amazon Cognito

### ISSUE THREAD

**Issue by rishabh-singh** [MicrosoftDocs/architecture-center#2177]
Reference: https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#mobile-services

Azure App Center focuses on building mobile and desktop applications. It revolves around the application and it's release, monitoring, etc.

While Cognito, focuses on providing SAML authentication to users. It facilitates user's sign-up/in and access control.

To my understanding, these are very different services, but the document mentions them as comparable.

The document in one section does list the proper corresponding service for Cognito, i.e. Azure Active Directory B2C.
Link: https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#security-identity-and-access

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#235869

**Comment by absheik** [comment]
@rishabh-singh thanks for cresting the issue.  The table you mention is comparing the equivalent features of Cognito and App Center in the Mobile Services category.  App Centers capabilities in creating and managing organizations https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-organizations#creating-an-organization is what makes this comparison possible.  
Please let me know if this answers your question.

**Comment by absheik** [comment]
Closing per pervious comment
