### ISSUE TITLE
Add Email Campaigns and Click Stream Data Collection Solutions

### ISSUE THREAD

**Issue by ambartyagi** [MicrosoftDocs/architecture-center#2179]
Add Email Campaigns and Click Stream Data Collection Solutions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d7b1d5-7e3e-221f-bd7e-b576364784f8
* Version Independent ID: c08a3f61-caee-ec20-c9ba-cd1a62ab5662
* Content: [Digital Campaign Management - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-marketing-using-azure-database-for-postgresql#feedback)
* Content Source: [docs/solution-ideas/articles/digital-marketing-using-azure-database-for-postgresql.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-marketing-using-azure-database-for-postgresql.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#236573

**Comment by absheik** [comment]
@ambartyagi thank you for making the request.  We have captured your request in our backlog.
