### ISSUE TITLE
Cost considerations for bandwidth for VNET Peering should be added

### ISSUE THREAD

**Issue by svenwasmer** [MicrosoftDocs/architecture-center#2183]
Hi Tech-Doc Team, 
[I was looking at the cost considerations. ](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server#cost-considerations)

The Blueprint shows a VNET-peering, which leads to some costs.
https://azure.microsoft.com/en-us/pricing/details/virtual-network/

It should be listed as well to make the picture more complete.

Proposed content:

**VNET-Peering pricing**
A high-availability deployment that leverages multiple Azure Regions will make use of VNET-Peering. There are different charges for VNET-Peering within the same region and for Global VNET-Peering. [Learn more.](https://azure.microsoft.com/en-us/pricing/details/virtual-network/)

Regards
Sven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Multi-region N-tier application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/multi-region-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#238095
