### ISSUE TITLE
Shouldn't Jumpbox in the diagram be replaced with Azure Bastion?

### ISSUE THREAD

**Issue by ts46235** [MicrosoftDocs/architecture-center#2184]
[Enter feedback here]
This diagram pre dates the release of Bastion and I think it should replace jumpboxes in the diagram since thats its purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Multi-region N-tier application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/multi-region-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#238107
