### ISSUE TITLE
Needs to be updated...still talks about web/worker roles

### ISSUE THREAD

**Issue by ts46235** [MicrosoftDocs/architecture-center#2185]
[Enter feedback here]
Remove/replace all documentation about the web and worker roles for newer azure technologies 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9425297d-8ddb-c092-5c2a-79015f4e8954
* Version Independent ID: 95fcd443-8a9f-0838-e73a-c6578f2d57f8
* Content: [Competing Consumers pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/competing-consumers)
* Content Source: [docs/patterns/competing-consumers.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/competing-consumers.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#238143

**Comment by absheik** [comment]
Fixed by https://github.com/MicrosoftDocs/architecture-center-pr/pull/1405
