### ISSUE TITLE
Caution  "Don't use azbb - it is in sustain mode and the npm package is out of date"

### ISSUE THREAD

**Issue by JerryMWeeks** [MicrosoftDocs/architecture-center#2186]
The entire script post this message uses AZBB, and the link provided refers to this architecture!
So what command should be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by absheik** [comment]
@JerryMWeeks thanks for the suggestion.  I will update the content
In the mean time please refer to:
ARM Template: https://github.com/Azure/azure-quickstart-templates/tree/master/101-hub-and-spoke-sandbox
Using Terraform: https://docs.microsoft.com/en-us/azure/developer/terraform/hub-spoke-introduction
