### ISSUE TITLE
Visio download link does not match the article diagram

### ISSUE THREAD

**Issue by lloydmills** [MicrosoftDocs/architecture-center#2188]
[Enter feedback here]

The visio file download link in this article does not match the diagram displayed in the article.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implement a hub-spoke network topology - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#239350

**Comment by absheik** [comment]
@lloydmills , please review the "shared services" tab in the downloaded visio file.  That has the architecture diagram that matches the png file in the article.
