### ISSUE TITLE
Require more information

### ISSUE THREAD

**Issue by niranjankala** [MicrosoftDocs/architecture-center#2189]
This article has just the diagram but no description of the components communication. It would be great if IOT documentation has real implementation diagram and example applications

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe173a6b-1bdd-3061-c50b-58d73c74b444
* Version Independent ID: 02dbd5c8-a175-80d7-c085-d1542830e76c
* Content: [IoT device deployment and management on demand - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/iot-with-aks)
* Content Source: [docs/solution-ideas/articles/iot-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/iot-with-aks.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#239667

**Comment by absheik** [comment]
@niranjankala, your request has been captured in the workitem  AB#239667, our team is capturing and prioritizing these requests. 
In the mean time, please leverage existing IoT reference architectures at [Azure IoT reference architecture](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot)

**Comment by EdPrice-MSFT** [comment]
I think we ended up removing this one.
