### ISSUE TITLE
I would be great to have a github reference example for this article.

### ISSUE THREAD

**Issue by giovanni-ferrari** [MicrosoftDocs/architecture-center#2190]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0086ec3a-1c25-966d-da07-7cf4258e187f
* Version Independent ID: f96d13e8-a5a2-b3c4-8c44-0d9e32a3ddf5
* Content: [Scalable Web Apps - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scalable-web-apps)
* Content Source: [docs/solution-ideas/articles/scalable-web-apps.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scalable-web-apps.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#239752

**Comment by absheik** [comment]
@giovanni-ferrari , here is an implementation of App Services Environment that covers both Security and Availability considerations.  
[Enterprise app deployment using App Service Environment](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/ase-standard-deployment)
[Highly available app deployment in App Services Environment](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/ase-high-availability-deployment)
