### ISSUE TITLE
SignalR - Realtime Web Dashboard

### ISSUE THREAD

**Issue by ashuisonline** [MicrosoftDocs/architecture-center#2191]
It would be great if you can enhance this documentation with implementation details, pricing guidance, code examples, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec994a02-c71a-8dea-8994-eb8c1e5e2992
* Version Independent ID: 2520c9c8-9d28-dd38-fa05-2c748b20ed8c
* Content: [Real-time Web Dashboard - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-web-dashboard)
* Content Source: [docs/solution-ideas/articles/real-time-web-dashboard.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/real-time-web-dashboard.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241145

**Comment by absheik** [comment]
@ashuisonline thanks for opening this issue.
Here is a more detailed SignalR scenario https://docs.microsoft.com/en-us/azure/architecture/example-scenario/signalr/.  Also look at the Azure SignalR Service Tutorial at https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-authenticate-azure-functions.
I will close this issue and Keep the above DevOps work item open to track this for our backlog.

**Comment by alexhart11** [comment]
We have this captured as an article to improve. Thank you for your feedback!
