### ISSUE TITLE
This script does not work and needs to be updated. I am working on that.

### ISSUE THREAD

**Issue by djcornutt** [MicrosoftDocs/architecture-center#2192]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636aa53e-3ca0-7a30-fe16-7219f3e8d1a9
* Version Independent ID: c503b39a-cd8a-669a-0882-27d8c13d3570
* Content: [Add IP address spaces to peered virtual networks - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/prefixes/add-ip-space-peered-vnet)
* Content Source: [docs/networking/prefixes/add-ip-space-peered-vnet.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/networking/prefixes/add-ip-space-peered-vnet.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @randycampbell
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241456

**Comment by djcornutt** [comment]
#tested and validated by Drew Cornutt in Azure Public
param (
    # Address Prefix range (CIDR Notation, e.g., 10.0.0.0/24 or 2607:f000:0000:00::/64)
    [Parameter(Mandatory = $true)]
    [String[]]
    $IPAddressRange,

    # Address Prefix range (Hub VNet Resource Group Name)
    [Parameter(Mandatory = $true)]
    [String]
    $HubVNetRGName, 

    # Address Prefix range (Hub VNet Name)
    [Parameter(Mandatory = $true)]
    [String]
    $HubVNetName
)

#Set context to Hub VNet Subscription
Get-AzSubscription -SubscriptionName YourSubscriptionName | Set-AzContext

#end

#Get All Hub VNet Peerings and Hub VNet Object
$hubPeerings = Get-AzVirtualNetworkPeering -ResourceGroupName $HubVNetRGName -VirtualNetworkName $HubVNetName
$hubVNet = Get-AzVirtualNetwork -Name $HubVNetName -ResourceGroupName $HubVNetRGName
#end

#Remove All Hub VNet Peerings
Remove-AzVirtualNetworkPeering -VirtualNetworkName $HubVNetName -ResourceGroupName $HubVNetRGName -name $hubPeerings.Name -Force
#end

#Add IP address range to the hub vnet
$hubVNet.AddressSpace.AddressPrefixes.Add($IPAddressRange)
# Add $IPAddressRange to subnet
$subnet = $HUBvnet.subnets[0]
$subnet.addressprefix.add($IPAddressRange)

#Apply configuration stored in $hubVnet
Set-AzVirtualNetwork -VirtualNetwork $hubVNet
#end 

foreach ($vNetPeering in $hubPeerings)
{
    # Get remote vnet name
    $vNetFullId = $vNetPeering.RemoteVirtualNetwork.Id
    $vNetName = $vNetFullId.Substring($vNetFullId.LastIndexOf('/') + 1)

    # Pull remote vNet object
    $vNetObj = Get-AzVirtualNetwork -Name $vNetName

    # Get the peering from the remote vnet object
    $peeringName = $vNetObj.VirtualNetworkPeerings.Where({$_.RemoteVirtualNetwork.Id -like "*$($hubVNet.Name)"}).Name
    $peering = Get-AzVirtualNetworkPeering -ResourceGroupName $vNetObj.ResourceGroupName -VirtualNetworkName $vNetName -Name $peeringName

    # Reset to initiated state
    Set-AzVirtualNetworkPeering -VirtualNetworkPeering $peering

    # Re-create peering on hub
    Add-AzVirtualNetworkPeering -Name $vNetPeering.Name -VirtualNetwork $HubVNet -RemoteVirtualNetworkId $vNetFullId -AllowGatewayTransit

}

**Comment by absheik** [comment]
@djcornutt thanks for opening the issue and providing the fix.
Updated using pr https://github.com/MicrosoftDocs/architecture-center-pr/pull/1431.  Will be available publicly in the next master to live build completes.
