### ISSUE TITLE
Error in requirement notice? 

### ISSUE THREAD

**Issue by chwolfe** [MicrosoftDocs/architecture-center#2193]
Is this sentence accurate? "For customers who do not have Azure AD Premium, this approach enables the customer to use security groups to manage role assignments." 

My understanding is that Azure AD Premium **is** required for security group role assignment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#roles-using-azure-ad-app-roles)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241484

**Comment by absheik** [comment]
@chwolfe you don't need AD Premium to create and use Groups.  For example, I was able to create groups in my MSDN Azure subscription that does not have AD Premium.
