### ISSUE TITLE
Relevance to Media Services is not evident

### ISSUE THREAD

**Issue by ksivasenthil** [MicrosoftDocs/architecture-center#2194]
The document is cataloged under Media Services. Content on the page is scanty and bears no resemblance to media services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3bee659-9929-c4e8-3f4c-de328edcab1c
* Version Independent ID: 7747dfe6-f1df-d54a-e703-128d0bad2697
* Content: [Instant Broadcasting on Serverless Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/instant-broadcasting-on-serverless-architecture)
* Content Source: [docs/solution-ideas/articles/instant-broadcasting-on-serverless-architecture.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/instant-broadcasting-on-serverless-architecture.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241529

**Comment by absheik** [comment]
@ksivasenthil SignalR can be used for **real time broadcasting** of audio/video. https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-overview#what-is-azure-signalr-service-used-for
