### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ksivasenthil** [MicrosoftDocs/architecture-center#2195]
"Partner on-premises live encoder" text is linked to an unavailable resource https://docs.microsoft.com/en-us/api/Redirect/documentation/articles/media-services-live-encoders-overview 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2afdbbba-ae07-bdf4-fa21-65955f1623d1
* Version Independent ID: 189aa6c3-a454-66c1-7346-d0fe53235c25
* Content: [Live streaming digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-live-stream)
* Content Source: [docs/solution-ideas/articles/digital-media-live-stream.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-live-stream.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241538

**Comment by ksivasenthil** [comment]
@absheik  the link is still leading to HTTP 404 ! Why would you close it without resolving to an existent page?
