### ISSUE TITLE
404 error on ARM templates link

### ISSUE THREAD

**Issue by RossCavanagh** [MicrosoftDocs/architecture-center#2196]
Under the components section, the following link fails (404): [Azure Resource Manager templates](https://docs.microsoft.com/en-us/api/Redirect/documentation/articles/virtual-machines-windows-cli-deploy-templates)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf4b377-2f24-8bcb-0e7a-a353564fb0cb
* Version Independent ID: fd0164e3-7acf-8dca-ff63-44d8055919dc
* Content: [HPC cluster deployed in the cloud - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/hpc-cluster)
* Content Source: [docs/solution-ideas/articles/hpc-cluster.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/hpc-cluster.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241825
