### ISSUE TITLE
Diagram for Service choice needs some correction

### ISSUE THREAD

**Issue by mukesh-dua** [MicrosoftDocs/architecture-center#2197]
Feedback for the diagram under section "Choose a candidate service":
Path: Start -> Migrate -> Lift-and-Shift -> Can be Containerized (Yes) -> Needs full-fledged orchestration? (No)

Shouldn't this be a "Container Instance" service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#242155

**Comment by absheik** [comment]
@mukesh-dua we were covering the Web App Container scenario in that path.  https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-docker.
