### ISSUE TITLE
Great content, but should be in a different section of the Architecture Center

### ISSUE THREAD

**Issue by nzthiago** [MicrosoftDocs/architecture-center#2198]
This entire 'serverless quest' section is great; but I don't think it should be under Developer Tools on the navigation menu though. It should either be it's own category called Serverless directly under Azure categories, or at least under Compute.

![image](https://user-images.githubusercontent.com/1563288/85750809-e299e780-b6be-11ea-8318-9090e6c32056.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064087b4-3a9c-21a1-04e6-af522f587157
* Version Independent ID: 1d2dd6fd-4dcd-5d6e-a148-4edadbff9bf4
* Content: [Serverless Functions overview - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/serverless-quest/serverless-overview)
* Content Source: [docs/serverless-quest/serverless-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/serverless-quest/serverless-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @rogeriohc
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#242776

**Comment by absheik** [comment]
@nzthiago thanks for creating the issue.  
The target audience of the Azure Architecture center is Developers and Architects.  Our goal in this TOC placement is to look at Serverless from an implementation architectural choice perspective rather than a Compute technology choice.  We have a robust [Compute decision tree](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree) where we cover Functions and event driven compute choices.

**Comment by nzthiago** [comment]
> @nzthiago thanks for creating the issue.
> The target audience of the Azure Architecture center is Developers and Architects. Our goal in this TOC placement is to look at Serverless from an implementation architectural choice perspective rather than a Compute technology choice. We have a robust [Compute decision tree](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree) where we cover Functions and event driven compute choices.

Thank you for the reply @absheik. What is throwing me off is it's placement under a "Developer Tools" section, especially the **Tools** bit of that section title. When I see dev tools I think of Visual Studio, VS Code, Eclipse, SDKs, and etc., and not the type of content under that section like Microservices and Serverless. I'd recommend either the Developer Tools section to be renamed (to Developer Architectures, Developer Patterns, ?), or these Microservices and Serverless sections under Developer Tools to be moved. 

For example, looking at the content of this new [Serverless applications](https://github.com/microsoftdocs/architecture-center/blob/master/docs/serverless-quest/serverless-overview.md#implementation-steps) section, from that first page it discusses four personas for the content: Architects and technical decision makers (TDMs), Developers, IT Pros / Ops, and Security professionals. So not only it isn't specific to dev tooling, it's target audience is also broader than just developers.

**Comment by absheik** [comment]
@nzthiago, I will change the TOC to say Developer options instead of tools.
