### ISSUE TITLE
No mention of Azure Table Storage

### ISSUE THREAD

**Issue by MagicBulletDave** [MicrosoftDocs/architecture-center#2200]
Should Azure Table Storage get a mention here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a2dd11-b2f0-7821-a877-fc09af4ac967
* Version Independent ID: f7537dfd-5472-f0d2-d344-db85fd65bf71
* Content: [Choose the right data store - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#242903

**Comment by absheik** [comment]
@MagicBulletDave the CosmosDB links actually point to the [CosmosDB Table API](https://docs.microsoft.com/en-us/azure/cosmos-db/table-introduction).  There are subtle difference between Table Storage and this API as called out [here](https://docs.microsoft.com/en-us/azure/cosmos-db/table-api-faq#table-api-vs-table-storage)

**Comment by absheik** [comment]
Proceeding to close per previous comment.
