### ISSUE TITLE
Double-Take DR - Azure Solution

### ISSUE THREAD

**Issue by suniltumma** [MicrosoftDocs/architecture-center#2202]
I am looking for this architecture, how we can implement on Azure Cloud. Is it a separate services available from Azure

This architecture will help to achieve on-demand DR on Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82dcb69b-d7f0-4a59-cc3e-46cc7dcf1469
* Version Independent ID: 6b691aff-88eb-5444-47ea-f06103d28e6a
* Content: [SMB disaster recovery with Double-Take DR - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/disaster-recovery-smb-double-take-dr)
* Content Source: [docs/solution-ideas/articles/disaster-recovery-smb-double-take-dr.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/disaster-recovery-smb-double-take-dr.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#243142

**Comment by absheik** [comment]
@suniltumma thanks for opening this issue.
Several [partner disaster recovery solutions are available in Microsoft Azure Market place](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/category/storage?page=1&subcategories=backup-and-recovery).  First party Azure DR solution is https://azure.microsoft.com/en-us/services/site-recovery/
