### ISSUE TITLE
AuthenticationValidated event should now be TokenValidated event

### ISSUE THREAD

**Issue by Jawvig** [MicrosoftDocs/architecture-center#2204]
There are a places in this page and the others in the whole article that refer to the "AuthenticationValidated" event, which doesn't exist. The code snippets shown refer to the "TokenValidated" event, so I assume the former has been renamed to the latter and thus the web page content needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33051532-cd1d-75bb-9f62-10a21648e50f
* Version Independent ID: 0cf085c9-1e62-5231-6e21-beed6aaf7d41
* Content: [Sign-up and tenant onboarding in multitenant applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/signup)
* Content Source: [docs/multitenant-identity/signup.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/signup.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#244095

**Comment by absheik** [comment]
@Jawvig the reference to "**AuthenticationValidated**" comes from https://github.com/mspnp/multitenant-saas-guidance/blob/master/src/Tailspin.Surveys.Web/Logging/SurveyAuthenticationEventsLoggingExtensions.cs

**Comment by Jawvig** [comment]
@absheik I'm afraid I think you missed the point here. You've pointed out a logging extension called `AuthenticationValidated`, but the text is referring to an event, not a logging extension. In fact, I think the logging extension also needs to be renamed to `TokenValidated`

> When a new tenant signs up, the Surveys application writes a tenant record to the database. This happens inside the AuthenticationValidated event. 

The call to the logging extension event happens within the `TokenValidated` method, which is the event handler for the `TokenValidated` event.
