### ISSUE TITLE
Maybe an error in the flowchart

### ISSUE THREAD

**Issue by miiitch** [MicrosoftDocs/architecture-center#2205]
Hi I think that the box pointed here should be Container services: 
![image](https://user-images.githubusercontent.com/2396269/85994045-85bc6b00-b9f7-11ea-8b47-88d29e1995af.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#244590

**Comment by PramodValavala-MSFT** [comment]
@miiitch Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by absheik** [comment]
@miiitch , this path leads to the Web App Container scenario https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-docker.  When **full-fledged orchestration is not**  needed, App Services  is a good Compute choice.  Let me know if this answers your question.

**Comment by miiitch** [comment]
Thanks @absheik, but it's not consistant with the path on the right that leads to Container Instances (which, with Web App containers, is also a good choice)

**Comment by absheik** [comment]
@miiitch, agree.  I will add ACI to this path as well.

**Comment by miiitch** [comment]
Thanks, any guidance between wep app container and ACI is a good addition to this diagram 👍👍
