### ISSUE TITLE
Multi-Region Failover for Azure Function App

### ISSUE THREAD

**Issue by mcollis2** [MicrosoftDocs/architecture-center#2206]
The documentation indicates that Multi-Region failover is not supported for Azure Function App, however it looks like you can failover to a different region using Azure Front Door and multiple instances of your Azure function:  [functions-geo-disaster-recovery](https://docs.microsoft.com/en-us/azure/azure-functions/functions-geo-disaster-recovery).  Should this be reflected in documentation as the listing "Not Supported" may lead people to not considering functions if the needs require multi-region redundancy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#244696

**Comment by absheik** [comment]
@mcollis2 thanks for creating the issue.  I have made the change to point to the AFD link

**Comment by AjayKumar-MSFT** [comment]
Matthew, Thanks for bringing this to our attention and taking time to share your valuable feedback in improving the Azure documentation. It's highly appreciated. The document now reflects the changes pushed by Absheik - Thank you!
