### ISSUE TITLE
Dear Supporters,

### ISSUE THREAD

**Issue by alexgdcas** [MicrosoftDocs/architecture-center#2208]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#245431

**Comment by alexgdcas** [comment]
(sorry for hitting return too early)
from the doc I see how to log Counters, Timers, Metrics and Histograms. However the same method doesn't seem to apply to Gauges. Do you have an example how to report them to logAnalytics?

Thanks.

**Comment by jocontr** [comment]
Hi @alexdgcas , sadly today we do not have one to showcase. If you do create one, please feel free to contribute to the guidance.
