### ISSUE TITLE
misleading in Azure Test Plans for non en-us users.

### ISSUE THREAD

**Issue by kkamegawa** [MicrosoftDocs/architecture-center#2210]
> 3.Continuous integration triggers application build and unit tests using Azure Test Plans.

Localized version(ja-jp) of this document is much more misleading than English version.
Some inexperienced Japanese consider it "building and testing with Azure test plans."

Is there a more concise way to write a translation that is less misleading?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8865190-b9ac-ae5e-2590-30237ed43697
* Version Independent ID: 45d8bb8c-10f1-de72-6644-a20ba60a32af
* Content: [Design a CI/CD pipeline using Azure DevOps - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp)
* Content Source: [docs/example-scenario/apps/devops-dotnet-webapp.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/devops-dotnet-webapp.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @chrisreddington
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#246481

**Comment by adamboeglin** [comment]
Thank you for letting us know.  We're tracking this issue in our localized repository.
