### ISSUE TITLE
Pricing section links to calculator with Chinese Language

### ISSUE THREAD

**Issue by wely** [MicrosoftDocs/architecture-center#2212]
On the pricing section, all the 3 links (Small, Medium, Large) such as (https://azure.com/e/841f0a75b1ea4802ba1ac8f7918a71e7) redirect to Azure calculator with Chinese language.
Can we change to English or language based on user settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5978df0f-98f5-f365-1912-48fc8c27566e
* Version Independent ID: 4f2b4216-1cc7-a267-eee4-d7716ce5ed03
* Content: [CI/CD pipeline for container-based workloads - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-with-aks)
* Content Source: [docs/example-scenario/apps/devops-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/devops-with-aks.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @iainfoulds
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#247315

**Comment by absheik** [comment]
@wely, I am unable to reproduce the issue.  It is showing me **en-us** pricing when my browser setting is that and shows the appropriate localized versions for **zh-cn** as well.

**Comment by absheik** [comment]
no repro
