### ISSUE TITLE
Is there a reference implementation example for such architecture? like an ARM template or something?

### ISSUE THREAD

**Issue by raul-guerrero** [MicrosoftDocs/architecture-center#2213]
It would be great to include a sample implementation of this architecture that includes an ARM template to setup all the services, plus a simple Logic Apps workflow doing something very basic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58f4706b-af61-c661-279d-05e9e9abb79a
* Version Independent ID: d5a4b726-4c50-0851-edc5-04b60ee5ce89
* Content: [Enterprise integration using queues and events - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/queues-events)
* Content Source: [docs/reference-architectures/enterprise-integration/queues-events.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/enterprise-integration/queues-events.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MattFarm
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#248522

**Comment by absheik** [comment]
@raul-guerrero , please check these ARM templates
https://github.com/Azure/azure-quickstart-templates/tree/master/101-integrationpatterns-messagerouter-servicebus/
https://github.com/Azure/azure-quickstart-templates/tree/master/101-integrationpatterns-messagerouter-logicapp/

**Comment by absheik** [comment]
closing per previous comment.
