### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by notesforsk** [MicrosoftDocs/architecture-center#2214]
needs some code examples. A step by step document would be great to show a sample ecommerce app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae02d869-5b00-9a9c-e7f4-2dea56bbd360
* Version Independent ID: 1326c190-21b4-de15-a37f-89eea0023399
* Content: [Architect scalable e-commerce web app - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scalable-ecommerce-web-app)
* Content Source: [docs/solution-ideas/articles/scalable-ecommerce-web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scalable-ecommerce-web-app.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#249113

**Comment by absheik** [comment]
@notesforsk please review the following two articles about leveraging App Service Environment (ASE) for an enterprise scale Web Application

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/ase-standard-deployment
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/ase-high-availability-deployment

the reference implementation is available https://github.com/mspnp/app-service-environments-ILB-deployments

**Comment by absheik** [comment]
closing per previous comment
