### ISSUE TITLE
Awkward Sentence

### ISSUE THREAD

**Issue by writex** [MicrosoftDocs/architecture-center#2215]
It is awkward for this second sentence to begin with Then:

Azure Cosmos DB is a globally distributed, multi-model database service. Then learn how to replicate your data across any number of Azure regions and scale your throughput independent from your storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#249402

**Comment by absheik** [comment]
@writex thanks for creating the issue.  When [this pr ](https://github.com/MicrosoftDocs/architecture-center-pr/pull/1467)is reviewed and merged the word "Then" will be removed.
