### ISSUE TITLE
Image file extension should be .png instead of .jpg

### ISSUE THREAD

**Issue by JasonCard** [MicrosoftDocs/architecture-center#2222]
When .jpg image is used like below, it's sometimes not rendered correctly for Internet Explorer, so could it be fixed to be .png file? Currently, it's causing broken image for German (de-de) in IE browser only.

`![Diagram of the Claim-Check pattern](./_images/claim-check.jpg)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1970e0cd-53ae-02f6-479b-9ca386a5220e
* Version Independent ID: 8a81baa3-61c2-a8f6-540c-9a239583b8d6
* Content: [Claim-Check pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check)
* Content Source: [docs/patterns/claim-check.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/claim-check.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @yorek
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#264578

**Comment by absheik** [comment]
@JasonCard thanks for creating this issue.  When [this pr ](https://github.com/MicrosoftDocs/architecture-center-pr/pull/1468)is merged this issue will be resolved.
