### ISSUE TITLE
Where is AadIssuerValidator ?

### ISSUE THREAD

**Issue by KatteKwaad** [MicrosoftDocs/architecture-center#2225]
I am having isssues finding the AadIssuerValidator as it is not found in the Microsoft.Identity.Web nuget
Where is the source code for the samples used here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5df2491-1abe-0211-efbf-c1fb384862e9
* Version Independent ID: f7f0d2cf-3f4f-44dc-54aa-cd59221264d2
* Content: [Secure a backend web API in a multitenant application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/web-api#authenticating-in-the-web-api)
* Content Source: [docs/multitenant-identity/web-api.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/web-api.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#265611

**Comment by ckittel** [comment]
Hi there @KatteKwaad, thanks for posting. I'm not seeing where you're finding `AadIssuerValidator` being referenced.  [The article that you opened this against](https://docs.microsoft.com/azure/architecture/multitenant-identity/web-api#authenticating-in-the-web-api) doesn't appear to reference it (at least not in `en-us`).  The source code for that article is hosted [here in GitHub](https://github.com/mspnp/multitenant-saas-guidance), which also doesn't appear to reference `AadIssuerValidator`.

Can you maybe respond with a link to where you're seeing that reference so that we can track this down for you?  Thanks!

**Comment by KatteKwaad** [comment]
Hi, 

Thanks for the response.

The article refrenced: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration

Thanks

**Comment by ckittel** [comment]
Ah, that makes more sense.  That article is owned by another team, in another location in GitHub.  What I'll do for you is to open the ticket there and I'll add you to the ticket and you can track it with that team.

**Comment by ckittel** [comment]
@KatteKwaad, I've reopened this request @ MicrosoftDocs/azure-docs#58819 -- and it's being assigned to the active directory team to handle. Thank you!  Have a wonderful weekend, I'll close out this issue here.

cc: @absheik

**Comment by shashishailaj** [comment]
@KatteKwaad The code is here https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs . I hope this is what you were looking for. Please let us know if this helps . The complete code for Microsoft Identity web is present at https://github.com/AzureAD/microsoft-identity-web URL . Let us know in case you have any further queries on this.  We have closed both the issues . Should you have any further queries , feel free to tag me to your reply on the main issue here MicrosoftDocs/azure-docs#58819 as I will be happy to help .

**Comment by KatteKwaad** [comment]
Thanks everyone
