### ISSUE TITLE
Broken links for 2 images in browse arquitectures page

### ISSUE THREAD

**Issue by Noradrex** [MicrosoftDocs/architecture-center#2227]
In page: https://docs.microsoft.com/en-us/azure/architecture/browse/#
There are broken links for this images:
- At "*DevOps*" section: https://docs.microsoft.com/en-us/azure/architecture/browse/thumbs/signalr.png for "**Sharing location in real time using low-cost serverless Azure services**".
- At "*Hybrid*" section: https://docs.microsoft.com/en-us/azure/architecture/browse/thumbs/hybrid-networking.png
"**Connect an on-premises network to Azure**".

I've found that the articles linked does not contains any image, so I suppose the links are autogenerated but there is no such content.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#266492
