### ISSUE TITLE
The German translation of the pattern name is nonsense. 

### ISSUE THREAD

**Issue by clemensv** [MicrosoftDocs/architecture-center#2228]
"Muster für die Anspruchsprüfung" is outrageously wrong. 

The entire article's translation is so embarrassing that I don't even know where to start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1970e0cd-53ae-02f6-479b-9ca386a5220e
* Version Independent ID: 8a81baa3-61c2-a8f6-540c-9a239583b8d6
* Content: [Claim-Check pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check)
* Content Source: [docs/patterns/claim-check.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/claim-check.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @yorek
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#267893

**Comment by ckittel** [comment]
@BhargaviAnnadevara-MSFT - who can we get from the loc team to evaluate that page?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ckittel Adding @SunnyDeng and @CeciAc from the Localization Team to evaluate this further.

**Comment by JasonCard** [comment]
Hi @clemensv
Thank you for your feedback. 
I own loc content for architecture-center, so I'll follow up on this issue. Since the entire translation should be reviewed, I've requested for a linguistic quality check to evaluate and fix the translation. However, please allow some time as this process may not finish until 8/14 according to our sprint schedule. Will update this issue when work is completed.
cc @absheik @BhargaviAnnadevara-MSFT @ckittel @SunnyDeng @CeciAc

**Comment by ckittel** [comment]
Thanks @JasonCard for looking into it.  HT @JasRobe for making the connection.

**Comment by ckittel** [comment]
@JasonCard has this de version been through the process yet?

**Comment by JasonCard** [comment]
@ckittel Linguistic review has been completed, but the translation fixes have not yet been implemented. I'm currently following up on the progress and will update when completed.

**Comment by JasonCard** [comment]
Sorry, the implementation had to be put on hold as the process had changed. Then we had to restart the implementation today since there was update to the English source content and localized files were synced yesterday. The translation fixes should be published by Mon 8/24.

**Comment by JasonCard** [comment]
@ckittel @clemensv German translation fixes from linguistic review was completed and is now published [live](https://docs.microsoft.com/de-de/azure/architecture/patterns/claim-check). Thank you again for your feedback!

**Comment by ckittel** [comment]
@clemensv -- how does it look now?  We okay to close?
