### ISSUE TITLE
Update "Publishing internal APIs to external consumers" page with newer Azure services (e.g., Front Door)

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftDocs/architecture-center#2236]
I think it would be great to update the reference architecture on the "Publishing internal APIs to external consumers" page with newer Azure services such as Azure Front Door, and perhaps changing the API App icon to a Web App icon (since I am under the impression that the API App concept is being merged into Web Apps).
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/publish-internal-apis-externally

Also, it would be great to add a description around why the multiple layers of virtual networks are recommended as shown in the diagram for the specific situation that is assumed.

I wouldn't mind helping update this diagram, but would like to work with someone from Microsoft who has ownership around this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb14c845-07c9-0fe2-0108-119b7e913b35
* Version Independent ID: c3fdc7ba-6743-33a6-d41d-3328e2e22e93
* Content: [Publishing internal APIs to external users - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/publish-internal-apis-externally?source=docs)
* Content Source: [docs/example-scenario/apps/publish-internal-apis-externally.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/publish-internal-apis-externally.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ssarwa
* Microsoft Alias: **ssarwa**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by BhargaviAnnadevara-MSFT** [comment]
@rukasakurai Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by absheik** [comment]
@rukasakurai , thanks for creating the issue.  
The multiple layers of networks you mention are subnets.  best practices for network segmentation are at https://docs.microsoft.com/en-us/azure/security/fundamentals/network-best-practices#logically-segment-subnets.   ASE ILB for example has to be deployed in to a separate subnet.
Regarding Front door, Azure Front door is a gateway technology, where as API management is a service specific for API lifecycle, security, caching, scale etc.  
Can you please elaborate on your statement " API App concept is being merged into Web Apps"?
