### ISSUE TITLE
Decision tree for which data store to use

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftDocs/architecture-center#2237]
I think it would be useful to have a decision tree to help people choose which data store to use (like the one in the compute section).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a2dd11-b2f0-7821-a877-fc09af4ac967
* Version Independent ID: f7537dfd-5472-f0d2-d344-db85fd65bf71
* Content: [Choose the right data store - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#268930

**Comment by BhargaviAnnadevara-MSFT** [comment]
@rukasakurai Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by rukasakurai** [comment]
One idea could be to add a link to 
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/data-options
which has a decision tree for data options, although the current version of the decision tree in the link above does not cover the Azure Storage (e.g., Blob, Files) options.

**Comment by JasRobe** [comment]
https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree
