### ISSUE TITLE
Curse of dimensionality and overfitting

### ISSUE THREAD

**Issue by umbersar** [MicrosoftDocs/architecture-center#2239]
[It has been mentioned on this page that curse of dimensionality leads to 'underfitting'. Either that is an error or I fail to understand the reasoning. I think that the curse of dimensionality leads to 'overfitting'.

The line in question is:

> The training algorithm has a large learning capacity to accurately model the problem, but needs more data to prevent underfitting.

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5beb8e-5dc7-3ac9-dae1-cdae8ed0f760
* Version Independent ID: 86f89d9d-4c08-8362-1f6f-751dff462a8f
* Content: [Machine teaching - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/machine-teaching)
* Content Source: [docs/solution-ideas/articles/machine-teaching.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/machine-teaching.md)
* Service: **architecture-center**
* GitHub Login: @jocontr
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#268934

**Comment by BhargaviAnnadevara-MSFT** [comment]
@umbersar Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by absheik** [comment]
@umbersar, The content is correct in discussing underfitting from the perspective of exponential data needs because of large dimensions leading to underfitting.  When there is not enough data to train the model, the model may exabit an inadequate relationship with the training data.
