### ISSUE TITLE
Where is the ACI in the diagram?

### ISSUE THREAD

**Issue by salowenh** [MicrosoftDocs/architecture-center#2240]
I might be missing something, but shouldn't the architecture diagram should mention the rightmost node is an ACI node?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f8f943-7688-65e6-26c9-5d682a225306
* Version Independent ID: 18d298ba-be2b-bc4a-abac-5ea5a94fadca
* Content: [Bursting from AKS with ACI - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scale-using-aks-with-aci)
* Content Source: [docs/solution-ideas/articles/scale-using-aks-with-aci.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scale-using-aks-with-aci.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#269475

**Comment by ckittel** [comment]
Indeed, we'll update the graphic to be reflect this better.  Thank you @salowenh

**Comment by ckittel** [comment]
This will be released with the next content publish.  Thank you for your contribution!
