### ISSUE TITLE
Why is there an additional IoT Hub in the long version of the architecture?

### ISSUE THREAD

**Issue by fmms** [MicrosoftDocs/architecture-center#2242]
In the documentation the architecture is depicted as follows:
![image](https://user-images.githubusercontent.com/908734/87882230-07a02280-c9ff-11ea-835c-45af824f6f05.png)

In the linked reference architecture document (page 30)
![image](https://user-images.githubusercontent.com/908734/87882319-9d3bb200-c9ff-11ea-8305-a63a3650aeaf.png)

Why does that document have a 2) an Event Hub in between the IoT Hub and the Azure Function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#269827

**Comment by ckittel** [comment]
Thanks for reaching out.

In the second diagram, it is showing that the IoT Hub Route (1) has selected to use either the "built-in" or external (wouldn't matter which one) Event Hub endpoint.  IoT Hub Routes can point to various services directly.  Storage being one, Service Bus another, and most commonly Event Hub.  Event Hub can be the built-in one (think of IoT Hub as an ingress (decision) layer in front of Event Hub) or your own provided one.  Usually customers opt for the built-in Event Hub.

The first diagram simplifies the visuals here, treating IoT hub as a bit of a black box, the second is expanding it showing a "direct to storage" flow and a "direct to event stream (Event Hub)" flow.  The stream version is important for "on demand" work to be done by Functions.  The Azure Storage path is for scheduled (batch) processing.

You can see more at [the documentation here](https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messages-d2c#routing-endpoints).
