### ISSUE TITLE
Empty alert in the Sharding section

### ISSUE THREAD

**Issue by epignosisx** [MicrosoftDocs/architecture-center#2243]
There is an empty alert in the Sharding section

Url: https://docs.microsoft.com/en-us/azure/architecture/patterns/sharding#when-to-use-this-pattern

![image](https://user-images.githubusercontent.com/697377/87882461-1e7a5100-c9ce-11ea-95b1-a41be4e0800d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050bb1fd-56ca-63bc-b105-17a56e3b0362
* Version Independent ID: ce84d0a7-3596-e259-dfc3-a9789efd9948
* Content: [Sharding pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/sharding)
* Content Source: [docs/patterns/sharding.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/sharding.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#269832

**Comment by ckittel** [comment]
Thank you for noticing this.  We've applied the change and it will go out with next scheduled publish.
