### ISSUE TITLE
Incorrect Security Layer specified - should be TLS - not SSL

### ISSUE THREAD

**Issue by intltechventures** [MicrosoftDocs/architecture-center#2245]
This sentence should specify TLS -not SSL
"The web APIs are hosted over secured HTTPS protocol and will be using an SSL Certificate."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb14c845-07c9-0fe2-0108-119b7e913b35
* Version Independent ID: c3fdc7ba-6743-33a6-d41d-3328e2e22e93
* Content: [Publishing internal APIs to external users - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/publish-internal-apis-externally)
* Content Source: [docs/example-scenario/apps/publish-internal-apis-externally.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/publish-internal-apis-externally.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ssarwa
* Microsoft Alias: **ssarwa**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#269977

**Comment by ckittel** [comment]
Thank you Kelvin for the suggestion.  I've opened a PR up for this internally.  Once it gets through review, I'll update this ticket accordingly.

**Comment by ckittel** [comment]
The change was made and should be published within the next 24 hours.  Thank you.
