### ISSUE TITLE
What is a offical process to publish a reference architecture in architecture center

### ISSUE THREAD

**Issue by huangyingting** [MicrosoftDocs/architecture-center#2246]
Hi,

I am a Microsoft employee, can you help point me to our offical process to publish a reference architecture in architecture center.

Thanks

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#270585

**Comment by BhargaviAnnadevara-MSFT** [comment]
Thanks for the question. Assigning to @absheik for providing guidance on this.

**Comment by ckittel** [comment]
@huangyingting - thank you for the interest, it's super easy! As a MSFT employee, please go to [our contribution page](https://review.docs.microsoft.com/en-us/help/contribute/architecture-center#aac-field-contributions).  If you have any questions, you can ping me directly on the process, and I can get you going.
