### ISSUE TITLE
Facade or multi-operation/ responsibility, non SOLID implementation for command handler?

### ISSUE THREAD

**Issue by martinokeefe** [MicrosoftDocs/architecture-center#2247]
In a 2020 Microsoft Architecture Article, is the promotion of a multi-responsibility class and Facade, particularly where each responsibility may have different dependencies, really the best way to demonstrate a command handler in practice?

Would CommandHandler<TCommand, TResult>, or simpler (e.g. standard result), with a concrete implementation for each, possibly displayed as a simple list in the article, be a better approach?

ICommandHandler<TCommand> --> TCommandConcreteHandler : ICommandHandler<TCommand>

_Pseudo_
ICommandHandler<T> defines  Execute(TCommand command) returns GenericCommandResult

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [CQRS pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#271029

**Comment by jocontr** [comment]
Hi @martinokeefe, 

I would consider that neither approach is wrong. I believe the intent of the author was to meticulously walk through each step and describe the process in detail.
