### ISSUE TITLE
Where can I find Visio stencils for these new Azure icons?

### ISSUE THREAD

**Issue by kaseyshah** [MicrosoftDocs/architecture-center#2249]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#271254

**Comment by PramodValavala-MSFT** [comment]
@absheik Do we have an official visio stencil for these icons? There does seem to be a [community maintained](https://github.com/sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio) one.

@kaseyshah You should still be able to use the [official SVG Icons](https://www.microsoft.com/en-in/download/details.aspx?id=41937) in your visio drawings.

**Comment by peppekerstens** [comment]
@PramodValavala-MSFT the official SVG icons download fails.. 404 error

**Comment by PramodValavala-MSFT** [comment]
@peppekerstens @kaseyshah Looks like there is a version of them available at the bottom of [this doc](https://docs.microsoft.com/en-us/azure/architecture/icons/) as well which works.

**Comment by absheik** [comment]
Visio Stencils are available for the Web version of Visio.  
Blog post written by @Shefali Birla: 
https://techcommunity.microsoft.com/t5/visio-blog/visually-represent-your-azure-architecture-using-the-latest/ba-p/1634509
