### ISSUE TITLE
Azure Shapes

### ISSUE THREAD

**Issue by JohnVisioMVP** [MicrosoftDocs/architecture-center#2250]
Thank you for making them available as SVG shapes. It makes it easier to convert them to Visio shapes. Other MS products have produced "Visio shapes", but they are just bitmaps. They should have had their "shapes" reviewed by the Visio team. Visio shapes are more than just clipart they have smarts and can retain data. I hope some one takes the next step and creates Visio shapes with the extras.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/?WT.mc_id=thomasmaurer-blog-thmaure)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#271372

**Comment by BhargaviAnnadevara-MSFT** [comment]
@JohnVisioMVP Thanks for the feedback. I have assigned the issue to the content author to evaluate this further.

**Comment by absheik** [comment]
Visio shapes are in the roadmap.  We are working with the Visio team.  No timeline to mention here though.  A new zip file with additional Icons have been published through https://github.com/MicrosoftDocs/architecture-center-pr/pull/1999/

**Comment by JohnVisioMVP** [comment]
The link is broken - 404
John…
