### ISSUE TITLE
Updated Diagram with new Azure Databricks Logo

### ISSUE THREAD

**Issue by clintonwford** [MicrosoftDocs/architecture-center#2252]
Hi, could you help me update the Databricks logo on the architecture diagram shown on the [advanced analytics on big data](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data)? I have created an [updated architecture diagram image](https://drive.google.com/file/d/1a9Nyj2vv2DwZalmGOYR4zLMTxsq1cHph/), using the [new Databricks icon](https://drive.google.com/file/d/1QvtmjSvrRo8Y9T3aRR9e4RHmXMqqFihP/).

Thank you!

Clinton Ford
Staff Partner Marketing Manager
Databricks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data#feedback)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#271996
