### ISSUE TITLE
Broken Link: Failure Mode Analysis Samples 

### ISSUE THREAD

**Issue by Mahesh-MSFT** [MicrosoftDocs/architecture-center#2255]
Failure mode samples link is broken. Can it be updated?

Also, failure mode analysis samples on Azure seems to have SEO problem. It's not easy to find the samples.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4acf791-5dbe-8b1a-2746-9174afef080c
* Version Independent ID: ff3b6772-a869-e0ef-dc00-09d709c6521f
* Content: [Designing resilient Azure applications - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/framework/Resiliency/app-design#failure-mode-analysis)
* Content Source: [docs/framework/resiliency/app-design.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/resiliency/app-design.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#272604

**Comment by PramodValavala-MSFT** [comment]
@Mahesh-MSFT  This has now been fixed.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
