### ISSUE TITLE
Link to Failure Mode Analysis sample is not working

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/architecture-center#2257]
Link to Failure Mode Analysis sample is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4acf791-5dbe-8b1a-2746-9174afef080c
* Version Independent ID: ff3b6772-a869-e0ef-dc00-09d709c6521f
* Content: [Designing resilient Azure applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/Resiliency/app-design#single-points-of-failure-(spof))
* Content Source: [docs/framework/resiliency/app-design.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/resiliency/app-design.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#272920

**Comment by NavtejSaini-MSFT** [comment]
@pisees We are checking this and will get back to you.

**Comment by ckittel** [comment]
Related: #2255

**Comment by PramodValavala-MSFT** [comment]
@pisees This has now been fixed.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
