### ISSUE TITLE
Link to AKS SLA is broken

### ISSUE THREAD

**Issue by mjeromeleonardGH** [MicrosoftDocs/architecture-center#2258]
The link to AKS SLA is broken : https://docs.microsoft.com/azure.microsoft.com/support/legal/sla/kubernetes-service/v1_1/

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#273280

**Comment by ckittel** [comment]
Thank you for the report.  This has been fixed and will be included in the next content publish.
