### ISSUE TITLE
"Azure Well-Architected Framework" link is broken

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/architecture-center#2262]
The link referenced in the first paragraph is broken https://docs.microsoft.com/en-us/azure/architecture/framework/index.md

```
In this reference architecture, we’ll build a baseline infrastructure that deploys an Azure Kubernetes Service (AKS) 
cluster with focus on security. This article includes recommendations for networking, security, identity, 
management, and monitoring of the cluster based on an organization’s business requirements and follows the
Azure Well-Architected Framework.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an Azure Kubernetes Service (AKS) cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mydiemho Thank you for catching that error in the docs! I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
