### ISSUE TITLE
Architecture Diagram and data flow steps in textual descriptions are not matching!

### ISSUE THREAD

**Issue by keerthiprakashr** [MicrosoftDocs/architecture-center#2265]
Architecture Diagram and data flow steps in textual descriptions are not matching!
example: The description explains two service buses outbox and inbox, but the diagram shows only one.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed7b54c-fe6b-4331-f6d4-1e369ebad0c1
* Version Independent ID: 70f614a9-153c-3a7e-107c-526ba68adad6
* Content: [Supply Chain Track and Trace - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/supply-chain-track-and-trace#feedback)
* Content Source: [docs/solution-ideas/articles/supply-chain-track-and-trace.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/supply-chain-track-and-trace.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#275944
