### ISSUE TITLE
Implementation FAQ Chatbot with data champion model

### ISSUE THREAD

**Issue by PadhuKudi** [MicrosoftDocs/architecture-center#2266]
Hi Team ,

We would need your support in implementing  "FAQ Chatbot with data champion model" architecture for one of our client , could you please let me know pricing for architecture model ? what is an "Data champion" model , any document on data champion model would be helpful

With regards ,
Padmanabhan Kudiarasu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d6b01e-9e6f-5fdb-4ac4-95f71887908f
* Version Independent ID: d60fa02f-3cfe-e46d-0a8b-8b42e1bf62ff
* Content: [FAQ Chatbot with data champion model - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/faq-chatbot-with-data-champion-model)
* Content Source: [docs/solution-ideas/articles/faq-chatbot-with-data-champion-model.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/faq-chatbot-with-data-champion-model.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#276151

**Comment by jocontr** [comment]
@PadhuKudi do not sell the guidance that is being provided, nor co-develop with customers. I would recommend reaching out to your local Microsoft consulting partners for direct support. Good luck.
