### ISSUE TITLE
Small correction 

### ISSUE THREAD

**Issue by assilabdulrahim** [MicrosoftDocs/architecture-center#2267]
[Enter feedback here]
In the diagram , it shows BC2 instead of B2C.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8a5bf-e3a5-3e47-51d9-a15364f8e38b
* Version Independent ID: 419a15fd-abf6-31de-f64b-627cc4466650
* Content: [Commerce Chatbot - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/commerce-chatbot)
* Content Source: [docs/solution-ideas/articles/commerce-chatbot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/commerce-chatbot.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#276174

**Comment by absheik** [comment]
thanks you for creating the issue @assilabdulrahim.  The above pr when merged will fix it.
