### ISSUE TITLE
Microservices arch link is broken in the "browse all" page

### ISSUE THREAD

**Issue by Vallentyne** [MicrosoftDocs/architecture-center#2268]
The browse all arch page (https://docs.microsoft.com/en-us/azure/architecture/browse/) has a broken link for the Microservices architecture page.  

Link is this:  https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks 

it should be:  https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by PramodValavala-MSFT** [comment]
@absheik Looks like the links here are generated from the folder structure. Assigning this to you for further review.

**Comment by ckittel** [comment]
The link works now, we had a broken URL redirect that was since fixed.  Thank you @Vallentyne .
