### ISSUE TITLE
Repo not found when deploying

### ISSUE THREAD

**Issue by moazmirza** [MicrosoftDocs/architecture-center#2269]
I am trying to deploy this Dev/Test for SAP template but it gives this error when Review+Create: Can you please confirm if the github repo link is still valid. Thanks!

 "message": "Multiple error occurred: BadRequest,BadRequest. Please see details.",
    "details": [
      {
        "code": "InvalidContentLink",
        "message": "Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/sap-2-tier-marketplace-image-md//shared/nic-config.json'. The tracking Id is '53709288-5c29-4725-b5fc-5c56051d801e'. Please see https://aka.ms/arm-deploy for usage details."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8307bb37-3a4f-0073-c495-b2aaa4cc8797
* Version Independent ID: 60702144-7610-fda2-a68d-f9f05aff2921
* Content: [Development and test environments for SAP workloads on Azure - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-dev-test)
* Content Source: [docs/example-scenario/apps/sap-dev-test.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/sap-dev-test.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @AndrewDibbins
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#276189

**Comment by absheik** [comment]
@moazmirza , please check whether you have access to https://github.com/mspnp/solution-architectures/tree/master/apps/sap-2tier

**Comment by moazmirza** [comment]
Yes I can open this github page.

**Comment by moazmirza** [comment]
I am getting this error when i click on Deploy to Azure on this page:
[image: image.png]

**Comment by PramodValavala-MSFT** [comment]
@absheik Looks like the shared templates are no longer available in the linked quickstarts location. I have raised a PR to fix this by using the shared templates present in the same repo as `azuredeploy.json`.

@moazmirza Could you check if the below works?

[![Deploy to Azure](https://azuredeploy.net/deploybutton.png)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FPramodValavala-MSFT%2Fsolution-architectures%2Fpatch-1%2Fapps%2Fsap-2tier%2Fazuredeploy.json)

**Comment by ckittel** [comment]
Thanks for the report @moazmirza  and the PR @PramodValavala-MSFT.  The defaultValue for those file locations are now looking accurate.  Note, the URL still won't render in the browser, and that's okay, as raw.githubusercontent.com doesn't do directory browsing.  If there is still any more issues around this, feel free to reopen the issue.

Have a great day

**Comment by moazmirza** [comment]
Thanks. I will check


Regards,
Moaz
