### ISSUE TITLE
Architectural details

### ISSUE THREAD

**Issue by RoozbehBandpey** [MicrosoftDocs/architecture-center#2270]
Hi,

I would love to know more about the architectural details of **Streaming using HDInsight**

- Code samples
- nonfunctional requirements
- functional requirements

Thanks & regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e96622a-0a60-2763-cf7a-1f4d45fa8091
* Version Independent ID: 6b1a5bc8-b0a3-d94e-c1ce-7f1a54332574
* Content: [Streaming using HDInsight - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/streaming-using-hdinsight)
* Content Source: [docs/solution-ideas/articles/streaming-using-hdinsight.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/streaming-using-hdinsight.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#276292

**Comment by ckittel** [comment]
Closing as this article has been removed.

#please-close
