### ISSUE TITLE
How about contextual / content specific links or an example ?

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/architecture-center#2271]
So you have a link in the "Components" section 
_Xamarin: Create mobile apps for iOS and Android using C# and Azure SDKs._

The issue is it takes you to the Xamarin front page ...
How about linking me to information about each step ...

I have been doing mobile and building WebAPI backends fora long time and getting mobile to work with Azure is a PITA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38528b0d-5156-c944-25c6-8027cda69322
* Version Independent ID: 222b8546-a265-1d0e-f2ac-147c4ae791b9
* Content: [Task-Based Consumer Mobile App - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/task-based-consumer-mobile-app)
* Content Source: [docs/solution-ideas/articles/task-based-consumer-mobile-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/task-based-consumer-mobile-app.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#276973

**Comment by Zimmergren** [comment]
In reviewing the latest version of this article, the links have been updated. 
The relevant links now point to an updated Microsoft Learn module with a lot more relevant information. 

#please-close
