### ISSUE TITLE
AKS - Implementation details Request

### ISSUE THREAD

**Issue by techarchconsulting** [MicrosoftDocs/architecture-center#2272]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/microservices-with-aks.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#276989

**Comment by techarchconsulting** [comment]
Hi,

I would love to know more about the architectural details of AKS

Code samples (.NET C# or Node JS)
Implementation guide
Pricing guidelines 


Thanks & regards

**Comment by AjayKumar-MSFT** [comment]
@techarchconsulting, Thanks for leveraging Azure docs feedback channel to share your valuable feedback. 


Please checkout '[Kubernetes cluster architecture](https://docs.microsoft.com/azure/aks/concepts-clusters-workloads#kubernetes-cluster-architecture)' - This article introduces the core Kubernetes infrastructure components such as the control plane, nodes, and node pools. Workload resources such as pods, deployments, and sets are also introduced, along with how to group resources into namespace, it's good starting point. 

There are good documentation on implementation guides/[reference architecture](https://docs.microsoft.com/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json) - This article includes recommendations for networking, security, identity, management, and monitoring of the cluster based on an organization’s business requirements and follows the Azure Well-Architected Framework.

Please see [Cluster operator and developer best practices to build and manage applications on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/azure/aks/best-practices) -  These best practices and conceptual articles have been written in conjunction with the AKS product group, engineering teams, and field teams including global black belts (GBBs).

For samples, request you to see [Getting started on managing Kubernetes clusters (AKS) using C#](https://docs.microsoft.com/samples/azure-samples/aks-voting-app/aks-voting-app/), [Node.js](https://docs.microsoft.com/javascript/api/overview/azure/container-service?view=azure-node-latest) and [C#](https://docs.microsoft.com/samples/azure-samples/aks-dotnet-manage-kubernetes-cluster/getting-started-on-managing-kubernetes-clusters-aks-using-c/)

Kindly refer [this document ](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#cost-optimization) for Cost Optimization strategies.

Hope this helps! Kindly let us know if you're looking for something else.

**Comment by ckittel** [comment]
Thank you @AjayKumar-MSFT - great resources - I'm going to close this topic for now.
