### ISSUE TITLE
PNG icons would be helpful

### ISSUE THREAD

**Issue by michaelcretzman** [MicrosoftDocs/architecture-center#2275]
PNGs would be really useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#277259

**Comment by AjayKumar-MSFT** [comment]
@michaelcretzman, That's a good feedback! Thanks for taking time to share your valuable feedback. Your suggestions has been shared with the content owner for further review.

**Comment by absheik** [comment]
@michaelcretzman, we have PNG icons in our backlog.  I am reviewing all open icon issues to summarize for our next quarter plan.
