### ISSUE TITLE
Can you please provide one implementation sample for this.

### ISSUE THREAD

**Issue by nitinkhandelwal26** [MicrosoftDocs/architecture-center#2282]
[Enter feedback here]
Can you please provide one implementation sample for this architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc547e3a-5433-08eb-9bc2-c0a44e4280a5
* Version Independent ID: 3ab8ba71-f5c5-dcb4-c1be-cde8b61cda34
* Content: [Secure DevOps for AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/secure-devops-for-kubernetes)
* Content Source: [docs/solution-ideas/articles/secure-devops-for-kubernetes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/secure-devops-for-kubernetes.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#278902

**Comment by absheik** [comment]
@nitinkhandelwal26, please refer to https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops
