### ISSUE TITLE
Language corrections/ suggestions

### ISSUE THREAD

**Issue by jmadhanraj** [MicrosoftDocs/architecture-center#2283]
[Enter feedback here]

In the first paragraph under "Reliability", the last line reads as "Availability is can your users get to your workload when they need to.". The phrase "Availability is" and the following words can be rephrased.

In the first paragraph under "Data sovereignty and encryption", the opening line read as "Make sure that your data remains in the correct geopolitical zone when using Azure's highly available. ". The last 3 words seems to be broken sentence.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Microsoft Azure Well-Architected Framework - Microsoft Azure Well-Architected Framework introduction](https://docs.microsoft.com/en-us/azure/architecture/framework/)
* Content Source: [docs/framework/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#279715

**Comment by ChaitanyaNaykodi-MSFT** [comment]
@jmadhanraj, Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by neilpeterson** [comment]
This has been fixed and will publish today. Thanks for submitting the issue.
