### ISSUE TITLE
Manageability Considerations

### ISSUE THREAD

**Issue by colin-small** [MicrosoftDocs/architecture-center#2288]
Please clarify in the Manageability Considerations section if restarting the vm via the portal is okay to do. Many people are confused including myself if it is just shutdown via the portal that is dangerous or shutdowns and restarts.

Also, will Windows Server 2012 and higher "self heal"  if the vm is deallocated? What actions need to be taken in the event of vm deallocation with respect to the domain /AD DS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#280157

**Comment by Mike-Crowley** [comment]
@colin-small it's fine to restart the VM from the Azure portal. This uses guest services within the VM to shut it down similar to the method of doing it within the VM - assuming you don't have any open user files (notepad, etc). As for the deallocation, from the VM's perspective its just being shut down. You can simply turn it back on.

**Comment by Mike-Crowley** [comment]
This seems to be addressed in the current version of the article. there are 3 side effects mentioned, none of which are significant in most environments.

**Comment by jocontr** [comment]
Closing issue after @Mike-Crowley reply.
