### ISSUE TITLE
Consider adding Pulumi to infrastructure deployment

### ISSUE THREAD

**Issue by marcusturewicz** [MicrosoftDocs/architecture-center#2289]
[Pulumi](https://www.pulumi.com) is another tool for infrastructure deployment. It is Infrastructure as Software rather than IaC, with a hybrid imperative/declarative style, where you can deploy infrastructure using many programming languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5490ef64-9b6d-59be-1e9b-a2b2d10388b2
* Version Independent ID: 4e37976c-47f3-1481-b312-e7be38f93e07
* Content: [Infrastructure Deployment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/iac)
* Content Source: [docs/framework/devops/iac.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/iac.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @Jose-Moreno
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#280160

**Comment by ckittel** [comment]
Pulumi is certainly gathering attention, great call out @marcusturewicz.  Based on our team's existing backlog, we might not get to this request for a while.  If you wish to contribute via a PR to make a suggestion of what that content would look like, it'll likely make its way through the system much faster than waiting for this to be prioritized on our backlog.

You can find the [contributor guide here](http://docs.microsoft.com/contribute), if you desire to go down this path and don't already know the process (sorry if you already do, didn't look at your commit history).

**Comment by marcusturewicz** [comment]
Sounds good @ckittel. I'll send through a PR soon 👍
