### ISSUE TITLE
Azure Sentinel Icons

### ISSUE THREAD

**Issue by MerelyPerfect** [MicrosoftDocs/architecture-center#2290]
I cannot find any azure sentinel icons in the Icon sets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#280299

**Comment by BhargaviAnnadevara-MSFT** [comment]
@MerelyPerfect Thanks for bringing this to our attention. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by ckittel** [comment]
@MerelyPerfect -- thanks to @t2kx -- we are going to try to track them all in one issue.  Closing. 

Follow @ #2339
