### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by tejinderrai** [MicrosoftDocs/architecture-center#2292]
Hello,

Could you please advise why governance is not a pillar in the Well Architected Framework? Without having governance guidance as an overarching pillar, any effort on designing, implementing and maintaining/supporting a well architected framework can negatively affect a solution.

Thank you

Tejinder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Microsoft Azure Well-Architected Framework - Microsoft Azure Well-Architected Framework introduction](https://docs.microsoft.com/en-us/azure/architecture/framework/)
* Content Source: [docs/framework/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#280809

**Comment by absheik** [comment]
@tejinderrai, thank you for creating the issue.  Excellent question.  We cover Governance extensively as a step in the Microsoft Azure Cloud Adoption Framework - [Govern](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/).  
Our objective is to get the customer setup for Governance at an organization level.  A workload that will be assessed and improved using the Azure Well Architected Framework will inherit all the Governance principles of the organization and will be reviewed and acted on in the Operational Excellence and Cost Optimization pillars.
