### ISSUE TITLE
Offline installer

### ISSUE THREAD

**Issue by MepMS** [MicrosoftDocs/architecture-center#2294]
[Enter feedback here]
Please can you give more insights on the offline installer?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9deb5142-8bb3-bfec-1775-bbb7f49364ed
* Version Independent ID: c1de3271-22f4-d472-f4ba-697e398c1dfa
* Content: [AI at the Edge with Azure Stack - disconnected - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/ai-at-the-edge-disconnected)
* Content Source: [docs/solution-ideas/articles/ai-at-the-edge-disconnected.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/ai-at-the-edge-disconnected.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#280954

**Comment by absheik** [comment]
@MepMS, offline refers to not represented in the diagram, or discussed by the article.  Poor choice of a word.  I will update the content.
