### ISSUE TITLE
Diagram typo?

### ISSUE THREAD

**Issue by edwiles** [MicrosoftDocs/architecture-center#2295]
Minor issue - in the diagram at the top of this page, I believe the box label "Azure DevOps release gate" should be "Azure DevOps release pipeline". Other than that, great diagram. Thanks a lot.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64e76ff-1388-ed4d-4c8b-92bb4419cc61
* Version Independent ID: 3cdec53f-38ba-c0bb-3315-5ad8b357aabf
* Content: [MLOps for Python models using Azure Machine Learning - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/mlops-python)
* Content Source: [docs/reference-architectures/ai/mlops-python.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/mlops-python.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @praneet22
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#280997

**Comment by absheik** [comment]
@edwiles, the text refers to Gating a process stop through Azure DevOps, the diagram also refers to a Manual release gate.  IN that context this labeling makes sense.  Please let me know your thoughts. Will close the issue after we hear form you.

**Comment by edwiles** [comment]
Thanks for the reply. I still suggest it should be "pipeline", because there are 3 pipelines as described in the page text (underneath the MLOps Pipeline heading) which correspond to the 3 shaded areas in the diagram. Two of them are correctly labelled pipeline. The Manual release gate is only one part of the pipeline, not the whole thing.

**Comment by absheik** [comment]
@edwiles agree with your perspective. thanks for the clarification.  Will update the diagram to change Azure DevOps release gate to pipeline.
