### ISSUE TITLE
Mistake in AzureBastionSubnet IP address

### ISSUE THREAD

**Issue by oyara** [MicrosoftDocs/architecture-center#2296]
The IP address in AzureBastionSubnet is not correct (10.0.0.254.0/27). Should be 10.0.254.0/27
[dmz-reference-architectures.zip](https://github.com/MicrosoftDocs/architecture-center/files/5034747/dmz-reference-architectures.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz?toc=%2Fazure%2Fvirtual-network%2Ftoc.json)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#281019
