### ISSUE TITLE
Update Note in ASR section about PPG Support

### ISSUE THREAD

**Issue by dmhelm** [MicrosoftDocs/architecture-center#2298]
[Enter feedback here]
Says ASR doesn't support PPG when the ASR support matrix states that it does.
https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-support-matrix
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fff09dc-014d-d685-881e-dc7d1ef353ff
* Version Independent ID: ca3d7830-d394-d280-dd35-19749ee53f6b
* Content: [Run SAP HANA for Linux virtual machines in a scale-up architecture on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines#feedback)
* Content Source: [docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines.md)
* Service: **architecture-center**
* GitHub Login: @Maggsl
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#281284

**Comment by RobBagby** [comment]
@dmhelm - I am closing this issue, as it appears to have been resolved. Please feel free to re-open if you believe I closed this in error.
