### ISSUE TITLE
Link to visio file is not working

### ISSUE THREAD

**Issue by lukaszkrkpl** [MicrosoftDocs/architecture-center#2299]
[Enter feedback here]

the visio file is not accessible 
Download a Visio file of this architecture.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d6aeb8-ec6a-4d27-2d10-1b404de450b7
* Version Independent ID: 65b165e4-a2e4-7f57-19eb-884fce7bf880
* Content: [Build an enterprise-grade conversational bot - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/conversational-bot)
* Content Source: [docs/reference-architectures/ai/conversational-bot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/conversational-bot.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @roalexan
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#281757

**Comment by lukaszkrkpl** [comment]
d
