### ISSUE TITLE
Possible typo: "application stamp"?

### ISSUE THREAD

**Issue by kyle30312** [MicrosoftDocs/architecture-center#2300]
"You can think of them as systems that load balance between **application stamps**, ..."

What is an application stamp? Should this perhaps read "application stacks"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by PramodValavala-MSFT** [comment]
@kyle30312 I believe "application stamps" is in reference to the [deployment stamps pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/deployment-stamp).

@absheik @doodlemania2 Could you please clarify?

**Comment by kyle30312** [comment]
Thank you for the clarification, @PramodValavala-MSFT -- that helps.

I found related information online by searching "azure stamp".
And I noticed a similar question from last year: https://github.com/MicrosoftDocs/azure-docs/issues/34306
