### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by RoozbehBandpey** [MicrosoftDocs/architecture-center#2301]
I would love to know more about the architectural details of **Extract, transform, and load (ETL) using HDInsight**

* Code samples
* nonfunctional requirements
* functional requirements

Thanks & regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35186e5-f0c5-8a9a-f2a6-ee53c80facfc
* Version Independent ID: 918cfabe-c932-4072-e4a0-5ab79c827365
* Content: [Extract, transform, and load (ETL) using HDInsight - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/extract-transform-and-load-using-hdinsight)
* Content Source: [docs/solution-ideas/articles/extract-transform-and-load-using-hdinsight.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/extract-transform-and-load-using-hdinsight.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#282601

**Comment by hallihan** [comment]
@RoozbehBandpey Thanks for your feedback on this Solution Idea.  We're tracking this on our backlog for possible expansion.  Please also check out the following related topics in the HDInsight docs: 
https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-etl-at-scale
https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-using-apache-hive-as-an-etl-tool
