### ISSUE TITLE
Azure storage examples using legacy version

### ISSUE THREAD

**Issue by alucao** [MicrosoftDocs/architecture-center#2302]
Hi,

In the section Azure Storage, the examples provided apply to the legacy version 11 of Azure Storage library. 
Is it possible to provide examples for the latest version (v12)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-storage)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#282719
