### ISSUE TITLE
Visio Stencils are also needed with SVG version.

### ISSUE THREAD

**Issue by paisleypark** [MicrosoftDocs/architecture-center#2303]
Please include something that can be used by native Microsoft tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#282882

**Comment by ckittel** [comment]
For sure, we are tracking that at this open issue #2249.  Feel free to follow along with that one, and we'll close this one as a duplicate.  Thanks!
