### ISSUE TITLE
Spelling on region 2 is incorrect!!

### ISSUE THREAD

**Issue by amitlalaawaz** [MicrosoftDocs/architecture-center#2306]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 297fe58b-8232-9b2a-c92e-9f7f94ec3e4e
* Version Independent ID: 3da45f17-e475-f23e-c77f-465933ed02f4
* Content: [Run SAP HANA on Azure (Large Instances) - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/hana-large-instances)
* Content Source: [docs/reference-architectures/sap/hana-large-instances.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/hana-large-instances.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @BenTrin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#283136

**Comment by PramodValavala-MSFT** [comment]
@amitlalaawaz Thanks for catching that! We have worked up a PR to fix this, which once merged should reflect in a couple of hours.
