### ISSUE TITLE
Code sample for Blockchain examples

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/architecture-center#2309]
I would like to see code sample for the three Blockchain examples.

There is an editting issue with point 1 repeated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed7b54c-fe6b-4331-f6d4-1e369ebad0c1
* Version Independent ID: 70f614a9-153c-3a7e-107c-526ba68adad6
* Content: [Supply Chain Track and Trace - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/supply-chain-track-and-trace)
* Content Source: [docs/solution-ideas/articles/supply-chain-track-and-trace.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/supply-chain-track-and-trace.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#283670

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24399 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
