### ISSUE TITLE
Syntax for link to service or URL showing up in doc

### ISSUE THREAD

**Issue by tom-schultz** [MicrosoftDocs/architecture-center#2310]
`Paired regions
To protect an application against a regional outage, you can deploy the application across multiple regions, using [Azure Traffic Manager][traffic-manager]`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42fd9ae-205d-042a-4d38-4ca356e27d17
* Version Independent ID: 694c671b-430e-31b6-9133-2324bb3a2efa
* Content: [Comparing AWS and Azure regions and zones - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/regions-zones)
* Content Source: [docs/aws-professional/regions-zones.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/regions-zones.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#283697

**Comment by BhargaviAnnadevara-MSFT** [comment]
@tom-schultz Thank you for catching that error in the docs! I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
