### ISSUE TITLE
Blob storage should be block storage

### ISSUE THREAD

**Issue by tom-schultz** [MicrosoftDocs/architecture-center#2311]
"Durable data storage for Azure VMs is provided by data disks residing in blob storage."

should be:

"Durable data storage for Azure VMs is provided by data disks residing in **block** storage."

If you click on the data disks link, it says "Azure managed disks are **block-level storage volumes**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ef54ba-28f9-bf3d-214d-d15ff2595a55
* Version Independent ID: 2c9fabc5-0288-ce98-a906-0dcc720f0c7f
* Content: [Comparing AWS and Azure compute services - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/compute)
* Content Source: [docs/aws-professional/compute.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/compute.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#283704

**Comment by tom-schultz** [comment]
Woops, looks like I'm wrong here. Turns out that Azure block storage is backed by... blob storage.
