### ISSUE TITLE
UseOpenIdConnectAuthentication() is obsolete

### ISSUE THREAD

**Issue by sp4rc** [MicrosoftDocs/architecture-center#2312]
The use of `UseOpenIdConnectAuthentication()` is obsolete. Instead `AddAuthentication()`, etc. should be used and reflected in this document. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.openidconnectappbuilderextensions.useopenidconnectauthentication?view=aspnetcore-2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcd84ea-bc3e-0449-83da-3295143988be
* Version Independent ID: a7e08b3a-46f8-6eb4-961a-35fda94353c0
* Content: [Authentication in multitenant applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/authenticate)
* Content Source: [docs/multitenant-identity/authenticate.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/authenticate.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#283982

**Comment by PramodValavala-MSFT** [comment]
@sp4rc Thanks for catching that! We have worked up a PR to address this, which once merged should reflect in a couple of hours.
