### ISSUE TITLE
Need imementation steps

### ISSUE THREAD

**Issue by sumisamm** [MicrosoftDocs/architecture-center#2313]
I would like to know implementation steps for this architecture thanks you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e74d52e1-beaa-6f00-e0b6-2bbdd00cf830
* Version Independent ID: 94ad0a2e-1eac-eac8-11d8-c3b80f7ca6db
* Content: [Application integration using Event Grid - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/application-integration-using-event-grid)
* Content Source: [docs/solution-ideas/articles/application-integration-using-event-grid.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/application-integration-using-event-grid.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#284348

**Comment by hallihan** [comment]
@sumisamm Thanks for your feedback.  We're tracking all feedback for expansion of Solution Ideas on our backlog.  Please also check out this sample that shows how to publish events to Event Grid:
https://docs.microsoft.com/en-us/samples/azure-samples/event-grid-dotnet-publish-consume-events/event-grid-dotnet-publish-consume-events/
