### ISSUE TITLE
Examples for non-web workloads and internet facing

### ISSUE THREAD

**Issue by RonnieQuan** [MicrosoftDocs/architecture-center#2316]
I have a little bit hard time to understand non-web workloads.

Do you have use case or example application for non-web workloads and internet facing?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#285905

**Comment by Zimmergren** [comment]
The latest edition of this guide covers options for using both internet-facing workloads and non-web workloads, including a relevant decision tree as a starting point. Further, the relevant links cover the use cases of each of these services, and there are now a great section with reference architecture examples.

#please-close
