### ISSUE TITLE
Wrong tense of word "increases" in "Limits" Section

### ISSUE THREAD

**Issue by jaspecla** [MicrosoftDocs/architecture-center#2320]
https://docs.microsoft.com/en-us/azure/architecture/framework/devops/app-design#limits

The sentence that reads, "Some limits are a hard maximum, while others are a soft limit that can be increases upon request..." should read "Some limits are a hard maximum, while others are a soft limit that can be increased upon request..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5d9240-7176-838b-5a41-1159799e4456
* Version Independent ID: e38a4b5c-32b1-d6bc-56b3-c8a84def4471
* Content: [Application design for DevOps - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/app-design)
* Content Source: [docs/framework/devops/app-design.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/app-design.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @UmarMohamedUsman
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jaspecla Thank you for catching that error in the docs. I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
