### ISSUE TITLE
wrong information in the diagram for the UDR of the express route

### ISSUE THREAD

**Issue by mthoger** [MicrosoftDocs/architecture-center#2321]
[thats not the way UDR in the Express route subnet works, its not where the traffic is orginating from but the destination, the the route is decided on. 

So if you have peerings to the network, those adderes spaces with have to be added to the routetable, to overwrite the route propagation of the peerings. 

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#287167

**Comment by josevarela** [comment]
Looks like this issue was created quite a while back, the  diagram and content of the article have been fundamentally changed since then and the issue doesn't seem to be relevant anymore.  

Closing the issue. @mthoger let us know if you feel this is still an issue and we'll take another look
