### ISSUE TITLE
Add Azure Functions as another hosting environment

### ISSUE THREAD

**Issue by chunliu** [MicrosoftDocs/architecture-center#2324]
Azure Functions should be a good option to host background jobs as well. It should be added as another hosting environment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a65e47-b024-0c7c-0ee9-21ff095abafd
* Version Independent ID: a764689a-168d-dcef-a297-c47f84ea2d12
* Content: [Background jobs guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs)
* Content Source: [docs/best-practices/background-jobs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/background-jobs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#287607

**Comment by PageWriter-MSFT** [comment]
Hi @chunliu 

Thanks for the recommendation. Based on your feedback, we've added Azure Functions as an option for the hosting environment. Also, added a section on considerations.

https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#azure-functions

Thanks again for opening this issue,
