### ISSUE TITLE
Potentially misleading item in decision tree graphic

### ISSUE THREAD

**Issue by kyleburnsdev** [MicrosoftDocs/architecture-center#2325]
In `architecture-center/docs/guide/images/compute-decision-tree.svg`, the path followed for new applications requiring orchestration leads to a decision between AKS and Service Fabric. The branch to Service Fabric is predicated on "Needs .NET integration..." and the reader could take this to include .NET Core in addition to the .NET Framework which was intended. This should be updated for clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#287622

**Comment by absheik** [comment]
@kyleburnsdev thanks for calling that out. Will fix it by saying "Needs .NET Framework integration"

**Comment by kyleburnsdev** [comment]
That should help avoid the confusion. Thanks for the quick response
