### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by puneetsaha** [MicrosoftDocs/architecture-center#2332]
[Enter feedback here]

This  is great use case! Any detailing would be much appreciated! Especially on selection of each of the tools ,their pros and cons.And any issues or anti-pattern to watch for.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2a5d359-b35d-f8c1-480e-ea9aff4255b5
* Version Independent ID: 971a1042-d297-7cda-2961-3f5b1b422a9b
* Content: [Anomaly Detector Process - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/anomaly-detector-process)
* Content Source: [docs/solution-ideas/articles/anomaly-detector-process.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/anomaly-detector-process.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
@puneetsaha, thanks for creating issue.  We will take your interest in anomaly detection as a user voice input to our prioritization signal for expanding on these Solution ideas.
