### ISSUE TITLE
Lift and shift to containers with AKS

### ISSUE THREAD

**Issue by bijuthan** [MicrosoftDocs/architecture-center#2333]
Hi Team,

Would love it if you can provide complete detailed steps to achieve Lift and shift to containers with AKS.

Best Regards,
Biju Thankappan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6b1bb0-6374-bc0f-fa77-fc9e7a8cbc7a
* Version Independent ID: a4b68beb-1369-19ed-36ca-9198c37ac05b
* Content: [Lift and shift to containers with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/migrate-existing-applications-with-aks)
* Content Source: [docs/solution-ideas/articles/migrate-existing-applications-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/migrate-existing-applications-with-aks.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by jocontr** [comment]
Hi @bijuthan , I would like to refer you to the following guidance:
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-start-here
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/
