### ISSUE TITLE
Content feedback: Update the solution with Windows Virtual Desktop as RDP solution

### ISSUE THREAD

**Issue by BenMartinBaur** [MicrosoftDocs/architecture-center#2334]
Hi Team,
I would recommend to update design with Windows Virtual Desktop as preferred remote desktop / access solution and remove the Apache Guacamole part. 

Best regards
Ben
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e1dc54-d828-b7ee-9d32-7d43b83966a9
* Version Independent ID: 4be88949-4cba-8269-fd78-2cd19884d603
* Content: [A computer-aided engineering service - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/hpc-saas)
* Content Source: [docs/example-scenario/apps/hpc-saas.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/hpc-saas.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#289933

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24401 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
