### ISSUE TITLE
list of missing icons in the new icon pack location

### ISSUE THREAD

**Issue by t2kx** [MicrosoftDocs/architecture-center#2339]
this list could contain doubles but maybe merge with other issues   ( #2290 ,  #2315 ) (@absheik just an idea)
- Machine Learning
- Genomics
- Azure API for FHIR
- Bonsai
- Databricks
- PowerBi Embedded
- Spring Cloud
- Container Instance
- Database Migration Service
- SQL Server Registries
- Application Change Analysis
- Resource Explorer
- AAD B2C
- AAD Privileged Identity Managememt
- AAD Conditional Access
- AAD Information Protection
- Spatial Anchors
- Bastion
- Azure Security Center
- Routing Tables
- Sentinel
- Storage Explorer
- Hyper Converged Infrastructure
- Time Series
- Azure Maps
- VWAN
- Edge Devices
- Peering
- Universal Print
- Windows Virtual Desktop
- Key Vault
- IoT Hub
- IoT DPS
- IoT Edge
- Azure Sphere
- Azure RTOS
- Azure Digital Twins
- Azure Time Series Insights

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#290845

**Comment by t2kx** [comment]
added content from the IoT issue immediately into these comments

**Comment by absheik** [comment]
@t2kx, thanks for the list of Icons requested.  We recently published **Azure_Public_Service_Icons_V2** that contains some of Icons you were requesting like KeyVault etc.  
We are continually reviewing these requests and updating our SVG files as these Icons are finalized for public release.

**Comment by absheik** [comment]
closing this issue as we are doing an all up review of Icons based on all the issues opened on the topic so far.
