### ISSUE TITLE
"Azure Load Balancer is a layer 5 load balancer" is incorrect

### ISSUE THREAD

**Issue by msdotnetclr** [MicrosoftDocs/architecture-center#2340]
The web page says "Azure Load Balancer is a layer 5 load balancer", while it actually should be at OSI Layer 4. The language directly contradicts the statements at https://docs.microsoft.com/azure/load-balancer/load-balancer-standard-overview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b8e780c-8b2b-f579-d380-a33cb76f0e82
* Version Independent ID: e666a3fc-cb2e-30a8-c4ab-b8db700e05cb
* Content: [IaaS: Web application with relational database - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/high-availability/ref-arch-iaas-web-and-db)
* Content Source: [docs/high-availability/ref-arch-iaas-web-and-db.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/high-availability/ref-arch-iaas-web-and-db.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Maggsl
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by PramodValavala-MSFT** [comment]
@msdotnetclr Thanks for catching that! We have worked up a PR to address this, which once merged, should reflect in a couple of hours.
