### ISSUE TITLE
Azure functions - hybrid connectivity

### ISSUE THREAD

**Issue by karpikpl** [MicrosoftDocs/architecture-center#2341]
As far as I know - ASE is no longer required to provide hybrid connectivity to azure functions, since there's private link, right?

![image](https://user-images.githubusercontent.com/3539908/91245838-6fdbd580-e71c-11ea-8b85-7ec0f8caedb3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#note7)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#291262

**Comment by PramodValavala-MSFT** [comment]
@karpikpl Private Link allows for one to access PaaS services securely via a private endpoint from within a VNET. For this, Functions would have to be either deployed within a VNET (ASE) or leverage [VNET Integration](https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet) available to App Service Plans and the Functions Premium Tier.

**Comment by karpikpl** [comment]
Right, that was my point - the documentation is outdated, since with premium plan, either ASE or private link can be used.

Should I make a PR with a fix?

**Comment by PramodValavala-MSFT** [comment]
@karpikpl Thanks! Please feel free to create a PR for it. Here is the [contributing guide](https://docs.microsoft.com/en-us/contribute/) to help.

**Comment by ckittel** [comment]
@karpikpl -- this has been fixed and the updated text will be deployed within the next 24 hours.  Thank you for your contribution.
