### ISSUE TITLE
Broke links "What's new in the Azure Architecture Center"

### ISSUE THREAD

**Issue by romulobrandino** [MicrosoftDocs/architecture-center#2342]
The links for Architecture in **"What's new"** are broke, 404 - Page not found.

Example:

https://docs.microsoft.com/en-us/azure/architecture/changelog#new-articles

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by PramodValavala-MSFT** [comment]
@romulobrandino Thanks for catching that! We have assigned this issue to the content author to review and update accordingly.

@absheik Looks like this file is generated. Could you please take a look at how we can fix this?

**Comment by cyberjacob** [comment]
This is affecting all links on the changelog page, appears to have been caused by 3c14132

**Comment by ckittel** [comment]
Thank you all for bringing this to our attention.  The links have been corrected.
