### ISSUE TITLE
Azure Table Storage missing

### ISSUE THREAD

**Issue by MartinDBakerCDW** [MicrosoftDocs/architecture-center#2343]
Surely Azure Table Storage is an example of Key/value storage? It's missing...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40cb85c-ee53-7b49-0622-bed8ebedea81
* Version Independent ID: 896e0838-dfd1-c442-414d-ad9ea6dc8f7d
* Content: [Understand data store models - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#291546

**Comment by ckittel** [comment]
Thank you @MartinDBakerCDW - we have this change stagged internally and will send it through the review process and update here with any status changes.

**Comment by ckittel** [comment]
This change has been made and is scheduled to go out sometime in the next 24 hours.  Thanks.
