### ISSUE TITLE
Naming conventions of Icons

### ISSUE THREAD

**Issue by Cairn23** [MicrosoftDocs/architecture-center#2344]
We are doing some work with ARM templates and attempting to use the latest Icon sets.
The problem we are seeing is there is no consistence way in which the icons are named which can map to templates or schemas.
Please could it be considered .
 e.g Template schemas refer to Virtual scale sets as 'virtualMachineScaleSets', but the icon is buried in the Compute directory called "10034-icon-service-VM-Scalte-Sets".

How are we meant to quick / auto identify between the too. Before the naming convention did link back to the recourses types

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#291888

**Comment by absheik** [comment]
@Cairn23, thank you for reporting the issue.  We did not intend for these Icons to be used in ARM template automation.  However this a good scenario that you have called out.  We will take this in to our backlog.
