### ISSUE TITLE
aws-professional/services > Shared Files is missing AWS FSx

### ISSUE THREAD

**Issue by jyjohnson** [MicrosoftDocs/architecture-center#2354]
Please add FSx for Windows and FSx Lustre (Linux).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#storage)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#292000

**Comment by PramodValavala-MSFT** [comment]
@jyjohnson Could you please share the doc that you are referring to here?

**Comment by jyjohnson** [comment]
This Azure page - https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#storage 

Should have these two AWS services: 

FSx for windows: https://docs.aws.amazon.com/fsx/latest/WindowsGuide/what-is.html
FSx for linux: https://docs.aws.amazon.com/fsx/latest/LustreGuide/what-is.html

**Comment by PramodValavala-MSFT** [comment]
@jyjohnson Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24402 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
