### ISSUE TITLE
Unnecessary network usage in this pattern?

### ISSUE THREAD

**Issue by granmaester** [MicrosoftDocs/architecture-center#2359]
I wanted to understand this flow (quoted from the doc):

>If an application updates information, it can follow the write-through strategy by making the modification to the data store, >**and by invalidating the corresponding item in the cache.**

>When the item is next required, using the cache-aside strategy will **cause the updated data to be retrieved from the data >store and added back into the cache**.

Why not just update the cache with the latest data rather than invalidating it? The next time, a call to the data store is not required. A network call can be saved

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f58625-4e97-1fc6-197b-8b25341f5a4f
* Version Independent ID: bdabf990-9a18-ec7f-a948-3fc79dc255e0
* Content: [Cache-Aside pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/cache-aside)
* Content Source: [docs/patterns/cache-aside.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cache-aside.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#293667

**Comment by PramodValavala-MSFT** [comment]
@granmaester The first paragraph of the solution is for systems which provide read-through and write-through/write-behind operations, in which the extra network call isn't required.

The statements following that are for systems that do not provide these functionalities and describe what the application would have to do for similar results.

**Comment by granmaester** [comment]
@PramodValavala-MSFT I see, the distinction was not obvious.
