### ISSUE TITLE
Loan Credit Risk Solution

### ISSUE THREAD

**Issue by atulghadge** [MicrosoftDocs/architecture-center#2366]
Hi, I'm Atul and I'd love to check out the complete solution for the loan credit risk solution on Azure and then try and run it in Azure as well. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed6476ec-ceb9-cb1a-92dd-5dbe50b729a0
* Version Independent ID: 0081a02f-b8d0-0945-51e7-a9a53c47f66d
* Content: [Loan Credit Risk + Default Modeling - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/loan-credit-risk-analyzer-and-default-modeling#feedback)
* Content Source: [docs/solution-ideas/articles/loan-credit-risk-analyzer-and-default-modeling.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/loan-credit-risk-analyzer-and-default-modeling.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#296031

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @atulghadge,  Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by hallihan** [comment]
Hi @atulghadge , thanks for your feedback.  We're tracking the expansion of this article on our backlog.
