### ISSUE TITLE
Layer is not necessarily a separate service/tier

### ISSUE THREAD

**Issue by harkinj** [MicrosoftDocs/architecture-center#2367]
Hi,
Nice article.
the article seems to assume the anti-corruption layer will be implemented as a separate out of process  tier/service.
It doesn't necesessarily have to be and the issues mentioned such as latency/scalability may then disappear.
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b204d4-aa9e-127b-5d80-6b3a80128e7f
* Version Independent ID: 54ffc524-0c3a-b349-f89a-459271f6c980
* Content: [Anti-Corruption Layer pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer)
* Content Source: [docs/patterns/anti-corruption-layer.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/anti-corruption-layer.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#296596

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @harkinj, sorry for the delay in my response. We have assigned this issue to the author to review further and take the next course of action.

**Comment by twentyonegrams** [comment]
More a question than feedback, throughout the article it has mentioned semantics and it is a major guidance on when the anti-corruption-layer pattern should or shouldn't be used. However, what exactly semantic means here? When I google online the definition of semantic in computer science is the study of meaning in programming languages. For instance two variables could be of the same type but the semantic of them could be different, one could be someone's age and the other could be someone's salary. So age and salary would be the semantics of the variables. Applying this to the pattern, we should use only when the semantic of two subsystems are different but how could two subsystems have the same semantic?
