### ISSUE TITLE
Bash shell script in "Create Dashboard" section doesn't work as expected

### ISSUE THREAD

**Issue by justPaulo** [MicrosoftDocs/architecture-center#2368]
[Output is: sed: 1: "/workspace/c\   \t\t\t" ...": extra characters after \ at the end of c command]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e17f2434-814c-4ebc-c05d-501566aa3c0f
* Version Independent ID: 6cf80861-2ab6-0c28-8a68-4f641491a61a
* Content: [Use dashboards to visualize Azure Databricks metrics - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/dashboards)
* Content Source: [docs/databricks-monitoring/dashboards.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/dashboards.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by justPaulo** [comment]
You're welcome, it looks like a simple sed syntax error. I tried to manually perform the sed intent replacing the environment variables but didn't work as expected.

**Comment by ckittel** [comment]
@justPaulo -- since the fix for this will be in mspnp/spark-monitoring repo, I've opened up a mirror of this ticket in that repo.  I'll close it here.

See & follow @ mspnp/spark-monitoring#108
