### ISSUE TITLE
The Next Steps Section is looping towards same page

### ISSUE THREAD

**Issue by vishnuvg1984** [MicrosoftDocs/architecture-center#2369]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7e7bd-23f3-a39f-9015-b77f14bb43e5
* Version Independent ID: 0ac34e7e-315f-2452-bf0a-74e9b1068c38
* Content: [Microservices architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices)
* Content Source: [docs/guide/architecture-styles/microservices.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/microservices.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#296985

**Comment by ckittel** [comment]
While they look the same, but buttom is different.  There does appear to be quite a bit of duplicate, but they do talk about different lens for the same general topic.  Took me a while to realize that as well 👍  I'm going to close, but if you feel there needs to be something else here, please do let us know.
