### ISSUE TITLE
Expand Solution

### ISSUE THREAD

**Issue by Marhoon** [MicrosoftDocs/architecture-center#2370]
[Enter feedback here]
I would like to see expand this article with more information (implementation details, pricing guidance, code examples, etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfcc112-0a30-557c-bf69-738c45b325d8
* Version Independent ID: 9385c916-ec7c-2f12-390b-80d136a16cb7
* Content: [Dynamics Business Central as a Service on Azure - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/business-central#feedback)
* Content Source: [docs/solution-ideas/articles/business-central.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/business-central.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @altotovi
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#298150

**Comment by hallihan** [comment]
@Marhoon - the article has had several updates since you reported this. Please open a new feedback item if there are still specific items missing that you would like to see.
