### ISSUE TITLE
The link to the MS Ignite session does not work

### ISSUE THREAD

**Issue by abhirockzz** [MicrosoftDocs/architecture-center#2371]
The doc links to this session - https://myignite.techcommunity.microsoft.com/sessions/81060?source=sessions but it's not available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09011510-4353-7237-6d31-e6451449d03f
* Version Independent ID: ac4f2053-f2a0-985a-1111-a44293192663
* Content: [Big data analytics with Azure Data Explorer - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/big-data-azure-data-explorer)
* Content Source: [docs/solution-ideas/articles/big-data-azure-data-explorer.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/big-data-azure-data-explorer.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @orspod
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#298264

**Comment by PramodValavala-MSFT** [comment]
@abhirockzz Thanks for catching that! Looks like the older sessions aren't available anymore but it's still available on [YouTube](https://www.youtube.com/watch?v=K9FYqprpzRE&t=1230&ab_channel=MicrosoftIgnite).

@absheik @orspod Would it be OK to update the link to point to YouTube instead?

**Comment by orspod** [comment]
@PramodValavala-MSFT - please update the link. Thanks all for your help.

**Comment by PramodValavala-MSFT** [comment]
@orspod Thanks! Glad to help.

@abhirockzz We have worked up a PR to fix the link with the one I've shared earlier. Once merged, the change should reflect in a couple of hours.
