### ISSUE TITLE
Security & Privacy

### ISSUE THREAD

**Issue by niranjanlogin** [MicrosoftDocs/architecture-center#2372]
[Security & Privacy Framework for an organisation gets motivated by Security Standards, Practices and Frameworks. 

In my opinion; instead of going ahead we are going backward in Security & Privacy area. If you look at the journey so far as following…

875+ Controls (Information Security, Cyber Security, Cloud Security, Privacy)
135+ Regulatory
130+ Technology Components
2600+ OEM Products
35+ Specialty Areas
50+ Work Roles
1200+ Knowledge, Skill & Abilities, Areas
1000+ Tasks

Excluding few there will be hardly any organization who might be performing all possible business justifications & traceability for Security & Privacy coverage.

In accordance to digital disruption these counts shall be reduced/minimized by now through Automation, AI, ML, Robotics etc. so that human brains can be free for further required innovations. But unfortunately, somehow our most of the Security & Privacy professionals are busy in doing those repetitive tasks every-time for every organisation.

Just a thought!!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55000863-6c61-319b-7d0d-5366c403e5e2
* Version Independent ID: 7bb9bb22-f939-6176-236f-79399b6ab2b4
* Content: [Overview of the security pillar - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/overview)
* Content Source: [docs/framework/security/overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/overview.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#298714

**Comment by PramodValavala-MSFT** [comment]
@niranjanlogin Thanks for the feedback! More intelligent systems are indeed the future and today we do have intelligence backed into [Azure Security Center](https://docs.microsoft.com/en-us/azure/security-center/security-center-intro), which is only going to get better.

[Security Alerts](https://docs.microsoft.com/en-us/azure/security-center/security-center-alerts-overview) and [Adaptive Application Controls](https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application) are some features that leverage machine learning to provide valuable insights to security professionals.

**Comment by PramodValavala-MSFT** [comment]
@niranjanlogin I hope me previous comment helps. This repo is primarily to address doc related feedback. So, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please feel free to share your feedback about having more intelligent security systems [here](https://feedback.azure.com/forums/347535-azure-security-center).
