### ISSUE TITLE
Security & Privacy

### ISSUE THREAD

**Issue by niranjanlogin** [MicrosoftDocs/architecture-center#2373]
[The possible business drivers for Security & Privacy can be as per following:

Sl. No. | Business Driver
-- | --
BD 1 | Protecting the Reputation of the Organization, ensuring that it is perceived as competent in its sector.
BD 2 | Providing support to claims made by the Organization about the competence to carry out its intended functions
BD 3 | Protecting the Trust that exists in Business Relationships and propagating that trust across remote   electronic business communication links and distributed information systems
BD 4 | Maintaining the confidence of the Key parties in their relationship with Organization
BD 5 | Maintaining the Operational Capabilities of the Organization Systems
BD 6 | Maintaining the Continuity of the Service Delivery, including the ability to meet the requirements of the   service level agreements of service levels agreements where these exists
BD 7 | Maintaining the accuracy of the   information
BD 8 | Maintaining the ability to govern
BD 9 | Preventing Losses through financial fraud
BD 10 | Detecting attempted financial fraud
BD 11 | Providing the ability to prosecute those who attempt to defraud the Organization
BD 12 | Providing and Maintaining the ability to ensure the solutions provided for securing electronics business   services provide a clear and unambiguous definition of responsibilities and   liabilities for all parties, quickly, efficiently, and with minimum cost.
BD 13 | Ensuring that information processed in the Organization Systems can be brought to court of Law as evidence and that the evidence will withstand hostile criticism by the other side's expert witness
BD 14 | Ensuring that the information security approaches used in the systems directly support compliance by the   organization with commercial contracts to which organization is a party.
BD 15 | Ensuring that the organization is at all times compliant with the laws and sectoral regulations, and that   the information security approach in the systems directly and indirectly   supports legal compliance
BD 16 | Maintaining the Privacy of   Personal and Business Information that is stored, processed and communicated   by the organizations systems
BD 17 | Protecting against the   deliberate, accidental or negligent corruption of personal and business   information that is stored, processed and communicated by all systems
BD 18 | Ensuring that an entity that   makes the Business Transaction cannot later deny having made the transaction   and that the entity will be bound by the contractual obligation associated   with making the transaction
BD 19 | Ensuring that all users can be   held accountable for the actions that they take in making use of their access   privileges
BD 20 | Ensuring that access privileges   are designed and implemented in such a way as to minimize the risk of a   single individual having excessive power that could be abused without easily   being detected
BD 21 | Providing a means by which the   organization can monitor compliance with its various information security   policies and can detect, investigate and remedy any attempted violation of   those polices
BD 22 | Providing assurance of the   correct functioning of the Organization's Systems and Sub-systems
BD 23 | Providing the setting of the   policy and the control and monitoring of the compliance with policy by the   authorities vested with responsibility for corporate governance in the system   environment
BD 24 | Protecting other parties with whom the organization has the Business dealings from abuse, loss of business   and personal information
BD 25 | Ensuring that the employees using the system are only granted authorized access within need to know and   need to use privileges
BD 26 | Ensuring that System security  solution is cost effective and provides good value for money
BD 27 | Ensuring that the security of   the Organization's information is dependent only upon its system security   measures and not on the security competence of any other organization
BD 28 | Ensuring that the system   security solution is cost effective and provides good value for money
BD 29 | Ensuring the  security of the organization's information   is dependent only upon its system security measures and not on the security   competence of any other organization
BD 30 | Ensuring that the granularity   of the system security services is appropriate to business needs
BD 31 | Preserving the ability of   authorized business users to maintain the high level of productivity
BD 32 | Ensuring that the information   security interface are easy and simple to use
BD 33 | Utilizing where possible   commercial of the shelf products to built information security solutions
BD 34 | Ensuring that security solution   services can be extended to all the locations, to all interface types and   across all network types that will be used to support delivery
BD 35 | Maximize the economic advantage   of the enterprise security architecture
BD 36 | Security services to be   supported through electronic communications, without the need for physical   transfer of documents and storage media
BD 37 | System security solution should   as far as possible comply with external and internal standards and best   practices
BD 38 | The security architecture   should be independent of any specific vendor or product, and should be   capable of supporting multiple products from multiple vendors
BD 39 | The security Architecture must   remain compatible with new technical solutions as these evolve and become   available and with new business requirements as these emerge with a minimum   of redesign
BD 40 | The security architecture must   be able to be adapted to counter new threats and vulnerabilities as they are   discovered
BD 41 | Ensured that the required   internal and external cultural shift is achieved to support the security   architecture
BD 42 | Ensuring accurate information   is available when needed
BD 43 | Minimise the risk of loss of   key customer relationships
BD 44 | Minimize the risk of excessive   loading on insurance premiums due to negligence on the organization's behalf   or lack of due-diligence
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa2c3bde-66e8-b501-0152-aa95553970c1
* Version Independent ID: 501576d2-852d-6f9c-9623-85fcce84ed42
* Content: [Security design principles in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/security-principles)
* Content Source: [docs/framework/security/security-principles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/security-principles.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#298735

**Comment by NaomiOooo** [comment]
Thank you for your comment.  This issue is being reviewed.
