### ISSUE TITLE
Validation host pool

### ISSUE THREAD

**Issue by PeterSmallbone** [MicrosoftDocs/architecture-center#2375]
This article is great! Have you thought of including a validation host pool as part of the architecture, as per https://docs.microsoft.com/en-us/azure/virtual-desktop/create-validation-host-pool

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Windows Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#298869

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24086 to track and investigate this issue.
