### ISSUE TITLE
Incorrect sentence: "Availability is can your users get to your workload when they need to."

### ISSUE THREAD

**Issue by rwaal** [MicrosoftDocs/architecture-center#2376]
The following sentence, in the [Reliability chapter](https://docs.microsoft.com/en-us/azure/architecture/framework/#reliability), is not right: `"Availability is can your users get to your workload when they need to."`. Not sure what the author is trying to say there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Microsoft Azure Well-Architected Framework - Microsoft Azure Well-Architected Framework introduction](https://docs.microsoft.com/en-us/azure/architecture/framework/#reliability)
* Content Source: [docs/framework/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#
