### ISSUE TITLE
Please expand the article "Machine Learning model training with AKS" with more details

### ISSUE THREAD

**Issue by kristianjaeger** [MicrosoftDocs/architecture-center#2378]
Please expand this article with moreinformation (implementation details, pricing guidance, code examples, etc),
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c04a7e7b-ebe4-b967-3cd1-fab859a9a43f
* Version Independent ID: 3368462d-475c-2a21-07db-c23b557c5144
* Content: [Machine Learning model training with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/machine-learning-with-aks)
* Content Source: [docs/solution-ideas/articles/machine-learning-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/machine-learning-with-aks.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by absheik** [comment]
@kristianjaeger,thanks for creating the issue, we have added this request to our backlog as a data point for prioritizing Solution Ideas articles to expand on.

**Comment by kristianjaeger** [comment]
Thanks, @absheik !
