### ISSUE TITLE
What about Azure reservations and Azure hybrid benefits to save costs? That should be mentioned on these docs....? 

### ISSUE THREAD

**Issue by yashesvi** [MicrosoftDocs/architecture-center#2379]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff40c714-9fda-c2ac-0a3c-63c246a9b773
* Version Independent ID: 6d3e4e6e-3a65-c181-7d45-90a59013e756
* Content: [Principles of cost optimization - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/overview)
* Content Source: [docs/framework/cost/overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/overview.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#300814

**Comment by absheik** [comment]
@yashesvi, thanks for creating the issue.  We are trying to differentiate the Principles for Cost Optimization and the actual tasks and opportunities to accomplish those principles.    If you look at Design, Provision, Monitor, optimize and tradeoff's section in the TOC, you will see the discussion on when to use what.
