### ISSUE TITLE
Data Bricks and Key Vault Stencils Missing?

### ISSUE THREAD

**Issue by MilfordSound** [MicrosoftDocs/architecture-center#2380]
I don't see "Data Bricks" or "Key Vault" stencils in this collection.

Any plans on adding them?

Thanks,

Sean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by hallihan** [comment]
@MilfordSound - Azure Databricks and Key Vault icons are now included.
