### ISSUE TITLE
The "more scalable" architecture seem incomplete. 

### ISSUE THREAD

**Issue by AlbozDroid** [MicrosoftDocs/architecture-center#2382]
Hello, the following documentation seems incomplete to me. 

How do we scale the Database to multiple regions? Read/Write to more than one region.

Redis is just one piece of the puzzle for the web session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0086ec3a-1c25-966d-da07-7cf4258e187f
* Version Independent ID: f96d13e8-a5a2-b3c4-8c44-0d9e32a3ddf5
* Content: [Scalable Web Apps - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scalable-web-apps)
* Content Source: [docs/solution-ideas/articles/scalable-web-apps.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scalable-web-apps.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by NeuralMX** [comment]
> Hello, the following documentation seems incomplete to me.

Agreed. I'm looking at various options and best practices to build a scalable and possibly totally serverless Azure website, and looking ad the docs I found this doc that looks pretty useless. Too basic, no explanation, no in-depth analysis. The "Scalable web application" doc mentions Azure Cache for Redis cache too, for the same reasons of this doc. So what's the purpose of this one?

**Comment by Zimmergren** [comment]
This article has been deprecated. A more favorable article exist here: https://learn.microsoft.com/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app

#please-close
