### ISSUE TITLE
Broken links in Well Architected Framework - Security

### ISSUE THREAD

**Issue by zojovano** [MicrosoftDocs/architecture-center#2384]
Broken links in the main navigation menu of https://docs.microsoft.com/en-us/azure/architecture/framework/:
- Well Architected Framework -> Security -> Tradeoffs (the link points to https://docs.microsoft.com/en-us/ ) 
- Well Architected Framework -> Security -> Checklist (the link points to https://docs.microsoft.com/en-us/ )
(as of 14th of Sept, 22:48H CET) 

Edited: Added doc metadata info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Microsoft Azure Well-Architected Framework - Microsoft Azure Well-Architected Framework introduction](https://docs.microsoft.com/en-us/azure/architecture/framework/)
* Content Source: [docs/framework/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302031

**Comment by zojovano** [comment]
I discovered few more broken links: Well Architected Framework -> Security -> Test -> Penetration Testing (and all links below "Test")

**Comment by absheik** [comment]
@zojovano, thanks for creating issue.  There appears to be a a difference in the version of TOC and the content.  We will try and fix it ASAP.

**Comment by neilpeterson** [comment]
Thanks @zojovano, it appears that this content was not quite complete. We are removing the TOC entries for now. This should be complete by end of day.

**Comment by zojovano** [comment]
thanks for the update
