### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by The-Violinist** [MicrosoftDocs/architecture-center#2385]
The second section of this page has the word "dingle" where I assume it is meant "single".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee907a51-a7f2-16b6-7c61-e5b09f14229f
* Version Independent ID: 4725a038-dcf1-efee-bc9e-86d3322d52d0
* Content: [Security with identity and access management (IAM) in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/design-identity#feedback)
* Content Source: [docs/framework/security/design-identity.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/design-identity.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302235

**Comment by PramodValavala-MSFT** [comment]
@The-Violinist Thanks for catching that! We have worked up a PR to address this, which once merged should reflect in a couple of hours.
