### ISSUE TITLE
Keys Icon is corrupted or missing

### ISSUE THREAD

**Issue by dhawallseth** [MicrosoftDocs/architecture-center#2387]
Azure_Public_Service_Icons_V2.zip\Azure_Public_Service_Icons\Security\00787-icon-service-Keys.svg is corrupted or missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/?source=docs)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302367

**Comment by absheik** [comment]
@dhawallseth, thank you for creating the issue.  I am able to open it in Inkscape, however I am unable to import in to Visio, we will track this bug internally and fix it in the next iteration.

**Comment by absheik** [comment]
A new version of the file Azure_Public_Service_Icons_V4.zip is now available for download.
