### ISSUE TITLE
How is SignalR used

### ISSUE THREAD

**Issue by bfontana6** [MicrosoftDocs/architecture-center#2388]
I would love to see more about the SignalR implementation details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3bee659-9929-c4e8-3f4c-de328edcab1c
* Version Independent ID: 7747dfe6-f1df-d54a-e703-128d0bad2697
* Content: [Instant Broadcasting on Serverless Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/instant-broadcasting-on-serverless-architecture#feedback)
* Content Source: [docs/solution-ideas/articles/instant-broadcasting-on-serverless-architecture.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/instant-broadcasting-on-serverless-architecture.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302494

**Comment by absheik** [comment]
@bfontana6 , https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-internals
