### ISSUE TITLE
Reverse admin sync guidance

### ISSUE THREAD

**Issue by cnadler-MSFT** [MicrosoftDocs/architecture-center#2389]
Recommending reversing the guidance regarding separating on-prem and cloud-only accounts.  The guidance is to avoid synching cloud-only accounts to on-prem vs the recommendation should be avoid synching on-prem admins to cloud-only.  As stated, AAD Connect has a default rule that won't sync an admin account (admincount = 1 I believe), but another poor practice I've seen is a customer has an additional on-prem NON-admin account that is synced to AAD as a global admin.  

Looking at it from cloud-only to on-prem doesn't happen frequently and not even show how this would be setup, guess custom AAD rule?  Either way, not common.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee907a51-a7f2-16b6-7c61-e5b09f14229f
* Version Independent ID: 4725a038-dcf1-efee-bc9e-86d3322d52d0
* Content: [Security with identity and access management (IAM) in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/Security/design-identity#dont-synchronize-on-premises-admin-accounts-to-cloud-identity-providers)
* Content Source: [docs/framework/security/design-identity.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/design-identity.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302498

**Comment by PageWriter-MSFT** [comment]
@cnadler-MSFT Thanks for opening the issue. The reported text has been fixed. There's a cautionary note that addresses your concerns. https://docs.microsoft.com/en-us/azure/architecture/framework/security/design-identity-authentication#centralize-all-identity-systems.
