### ISSUE TITLE
Azure virtual network subnets link appears to be incorrect

### ISSUE THREAD

**Issue by cnadler-MSFT** [MicrosoftDocs/architecture-center#2390]
Resolves to https://almbok.com/office365/microsoft_cloud_it_architecture_resources which has nothing to do with the topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f78e284-fb28-8ac2-0ce6-590b48c74a45
* Version Independent ID: 3baed527-6023-bc26-d3f9-9fda0a43925e
* Content: [Network security and containment in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/Security/network-security-containment#design-virtual-network-subnet-security)
* Content Source: [docs/framework/security/network-security-containment.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/network-security-containment.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302792

**Comment by hallihan** [comment]
@cnadler-MSFT - This content has been [relocated](https://docs.microsoft.com/azure/architecture/framework/security/design-network-segmentation) and it appears all links are functional now.
