### ISSUE TITLE
Change name to Strangler Fig Application

### ISSUE THREAD

**Issue by torarve** [MicrosoftDocs/architecture-center#2391]
Martin Fowler has changed the name to Strangler Fig Application to avoid the violent connotation. From his own revision comment:

> Changed URL and name to Strangler Fig Application April 29 2019
>
> I thought this post was a nice metaphor, but didn't expect the degree that it would grow in popularity (in recent months it gets over 3000 page views a month). The popularity is nice, but there is a problem. The original post was entitled “Strangler Application”, and when used, the pattern is often referred to as a “strangler”. But its usage often gets separated from its metaphorical root, and takes on a unpleasantly violent connotation.
>
> Some people, therefore, have advocated avoiding or changing the name. I don't have any great objection to that, I haven't used the name in my own writing since that original posting. But the trouble with attempting a rename, is that once a name has lodged itself in a community's mind, it's very hard to dislodge.
>
> Recently I thought of a small tweak that might help things a little. If I rename the post to “Strangler Fig Application”, and use the term “Strangler Fig” as much as possible, then hopefully that would reduce the violent connotation by reinforcing the metaphorical link that is the whole point of the name. Because it's a small change, maybe it will spread enough to be worthwhile, and it's not much effort, so seems worth a try.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b580bcd-bba9-0799-6f9f-4b0e2ae9739f
* Version Independent ID: 6603e60e-ad3b-9aec-0633-eed88c218561
* Content: [Strangler pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/strangler)
* Content Source: [docs/patterns/strangler.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/strangler.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302971

**Comment by neilpeterson** [comment]
@torarve thanks for bringing this up, good call. I've updated all references and also the URL to the doc (with redirect). These should publish today.
