### ISSUE TITLE
Icons too small

### ISSUE THREAD

**Issue by NNITarchitectureQHS** [MicrosoftDocs/architecture-center#2392]
All icons seem to be 18x18 px. in default rendering size. This makes them less usable when used from Windows Explorer. Using PowerToys SVG thumbnail and SVG previewer function in Windows Explorer the icons appears very blurry when Explorer is set to show the content of the directory as medium or larger icons ... the blurry-nes makes it very hard to find the right icon.

The previous CNE_Symbols didn't have this limitation and was very easy to use e.g. in Visio and PowerPoint.

please consider removing the canvas size from the files or make it considerably larger e.g. 96x96 or even bigger.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#302992

**Comment by absheik** [comment]
@NNITarchitectureQHS, your request to consider removing the canvas size from the files or make it considerably larger e.g. 96x96 or even bigger is being reviewed.  We will try to incorporate it in an upcoming release.  Thanks for your feedback.
