### ISSUE TITLE
Finance management apps using Azure Database for MySQL solution

### ISSUE THREAD

**Issue by Kevdome3000** [MicrosoftDocs/architecture-center#2396]
I am very much interested in seeing implementation details, pricing guidance, code examples, as well as guidance on the best services to use within the Azure Eco System for this type of product.

Specifically for providing a user with real-time analytics, forecasts, and benchmarks against their peers regarding their spending behaviors.

This would be based on a data store of their historical transaction data and a stream of real-time transaction data.

Thanks!
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc37e50a-b8c1-d761-d0b0-a4e83662588b
* Version Independent ID: 74bb26d2-fe65-05fc-4af4-419d3d7b7b3e
* Content: [Finance management apps using Azure Database for MySQL - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/finance-management-apps-using-azure-database-for-mysql)
* Content Source: [docs/solution-ideas/articles/finance-management-apps-using-azure-database-for-mysql.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/finance-management-apps-using-azure-database-for-mysql.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#303387

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24394 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
