### ISSUE TITLE
FSLogix single disk

### ISSUE THREAD

**Issue by JimMoyle** [MicrosoftDocs/architecture-center#2397]
I think it's much more appropriate to to recommend two containers than one as using one container means you miss out on several features.

This also drives the advice below to only have one session, this misses out on a great deal of scenarios.

The docs should not be so prescriptive.

Jim
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#profile-container-and-office-container)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md)
* Service: **architecture-center**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#303646

**Comment by hallihan** [comment]
@JimMoyle - the article has had many updates since you originally reported this, and I see mentions of multiple sessions and using a container per host pool.  If there are other specific suggestions, feel free to re-open with more detail, or submit a new feedback item.
