### ISSUE TITLE
Update this documentation to Az module

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/architecture-center#2398]
Hello guys,

This documentation should be updated to az module. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Extend an on-premises network using ExpressRoute - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#303933

**Comment by ckittel** [comment]
Closing the issue as this was fixed in Feb, but the issue was never closed.
