### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by abdale** [MicrosoftDocs/architecture-center#2399]
I was redirected to this page from [here](https://www.microsoft.com/en-us/download/details.aspx?id=41937), where it said under "install instructions" that you will find installation instructions on this page. But this page doesn't have any installation instructions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#303942

**Comment by PramodValavala-MSFT** [comment]
@abdale the icons are now general-purpose SVG icons which you could copy/paste or drag/drop anywhere. No instructions needed compared to a Visio Stencil like before.

**Comment by abdale** [comment]
Understood. That's what I ended up doing as well. Perhaps the [initial page](https://www.microsoft.com/en-us/download/details.aspx?id=41937) which points to this page by saying "Go to https://docs.microsoft.com/en-us/azure/architecture/icons/ and follow the instructions there.
" should be updated, but I understand that's not a docs page.

Thanks!
