### ISSUE TITLE
Exclusions

### ISSUE THREAD

**Issue by NebV** [MicrosoftDocs/architecture-center#2401]
Please provide more information on what folders to exclude and include as part of the redirections.xml.  You specifically say not to exclude %appdata%\Microsoft\Teams, but what folders can we exclude? It contradicts what I've found in the following article which excludes several folders within %appdata%\Microsoft\Teams.  Our FSLogix profile folders are getting very large (10-20 GB) and we need to know what is safe to exclude.
https://techcommunity.microsoft.com/t5/windows-virtual-desktop/wvd-fslogix-reduce-profile-container-size-exclude-teams-cache/m-p/1503683

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md)
* Service: **architecture-center**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#304570

**Comment by hallihan** [comment]
Edits were previously made to address Teams folder exclusions in this section: https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions
