### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by bigdatamoore** [MicrosoftDocs/architecture-center#2402]
There is a typo here: 

“Access to the Azure Database workspace is controlled using the administrator console.“

Should be:

“Access to the Azure Databricks workspace is controlled using the administrator console.“

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42385d9e-bf16-c83f-4cc4-bc7819b7c72a
* Version Independent ID: 8ff90608-83ab-fe3f-c01a-5e4e288f28fc
* Content: [Stream processing with Azure Databricks - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/stream-processing-databricks)
* Content Source: [docs/reference-architectures/data/stream-processing-databricks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/stream-processing-databricks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#304672

**Comment by AjayKumar-MSFT** [comment]
@bigdatamoore, That's a good catch! Thanks for taking time to share your feedback on this. We will fix this shortly.

**Comment by absheik** [comment]
Fixed
