### ISSUE TITLE
Traffic Manager vs Front Door

### ISSUE THREAD

**Issue by mmitul1979** [MicrosoftDocs/architecture-center#2403]
why can't we use the front door service instead of the traffic manager?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2442849c-9e87-56b2-dffd-5c8089e8132c
* Version Independent ID: 828da465-186b-f819-9575-ee51e8c83306
* Content: [Multi-tier web application built for HA/DR - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/multi-tier-app-disaster-recovery)
* Content Source: [docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @sujayt
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#304760

**Comment by mmitul1979** [comment]
![Capture](https://user-images.githubusercontent.com/60380205/93668096-0f844d80-faa8-11ea-9a32-921788eb01fb.PNG)
Here is my proposed architecture for the asp.net website with HA and DR.

**Comment by skabou** [comment]
It's unclear from this problem description which article this applies to, please re-open with additional details if help is still needed.
