### ISSUE TITLE
Attach the original visio diagram to this page 

### ISSUE THREAD

**Issue by SokoloffMaxim** [MicrosoftDocs/architecture-center#2404]
Hi, can we have the original visio diagram attached to this page ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f491d2a8-2895-9075-29f2-fde88888b6b6
* Version Independent ID: d59e120b-9968-9212-571b-99345aa8fa83
* Content: [Multiple forests with AD DS, Azure AD, and Azure AD DS - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/multi-forest-azure-managed)
* Content Source: [docs/example-scenario/wvd/multi-forest-azure-managed.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/multi-forest-azure-managed.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @nehalineogi
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#305263

**Comment by ckittel** [comment]
Visio file has been attached.  Thank you for bringing that to our attention.
