### ISSUE TITLE
Diagram is confusing 

### ISSUE THREAD

**Issue by SokoloffMaxim** [MicrosoftDocs/architecture-center#2405]
Hi there, diagram is confusing. Especially , when it comes to azure files/net app files.
It is no clear which subscription they belog to ? Dedicated spoke? HUB? WVD Spoke? Or both?
Can you please make it clear and place those azure files/net app files within a subscription boundaries..
Secondly , is that conceptually correct to place a Virtual Desktop subnet in the hub vnet? 
According to CAF /enterprise scale deployment, WVD  SHOULD be placed / belong to SPoke subs/vnets/subnets
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Windows Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#305396

**Comment by doodlemania2** [comment]
@christiaanbrinkhoff - could you take a look at this?

**Comment by doodlemania2** [comment]
@christiaanbrinkhoff -- double checking here sir.

**Comment by christiaanbrinkhoff** [comment]
I received only positive feedback about the diagram so far. Please reject due to lack of details and what to improve to make it better.
