### ISSUE TITLE
hihi

### ISSUE THREAD

**Issue by bacmodung** [MicrosoftDocs/architecture-center#2406]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d24b72-655e-f9fe-1861-acc1c160f485
* Version Independent ID: afeb6a58-7064-33f7-5532-65c2f2aa6fde
* Content: [IoT Connected Platform for COVID-19 detection and prevention - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/iot-connected-platform)
* Content Source: [docs/solution-ideas/articles/iot-connected-platform.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/iot-connected-platform.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#305627

**Comment by ckittel** [comment]
@bacmodung I'm going to close this issue.  If you have more content to add, please go ahead and open a new issue.  Thanks.
