### ISSUE TITLE
Naming error in drawing and Visio file

### ISSUE THREAD

**Issue by steinrr** [MicrosoftDocs/architecture-center#2408]
There might be some errors in both the online drawing and the Visio file.

Because the workload in the "Disconnected Subscription" is called "Workload 2", it might seem that:

* Should the public IP address in the "Disconnected Subscription" be "Wkld 2 public IP address" and not "Wkld 1 public IP address"?
* Should the Azure Bastion name in the "Disconnected Subscription" be "Wkld 2 Azure Bastion" and not "Wkld 1 Azure Bastion"?
* Should the private end point and private link service also be named something with "Wkld 2" instead of "Wkld 1"?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d19d00-c368-c49f-0b21-50004f05f2ef
* Version Independent ID: b0dd7137-6c32-84f5-d604-b6f9bca2768b
* Content: [Design a hybrid Domain Name System solution with Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-dns-infra)
* Content Source: [docs/hybrid/hybrid-dns-infra.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/hybrid-dns-infra.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#305951

**Comment by BryanLa** [comment]
@steinrr - apologies for the long delay, and thanks for your contribution.

The diagram has been updated and will republish today.

#please-close
