### ISSUE TITLE
Updated Diagram with new Azure Databricks Logo

### ISSUE THREAD

**Issue by clintonwford** [MicrosoftDocs/architecture-center#2409]
Hi, could you help me update the Azure Databricks logo on the [Real Time Analytics on Big Data Architecture](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics) reference architecture diagram? I have created an [updated architecture diagram image](https://drive.google.com/file/d/1ij7lT4BKzMrOit3MlyGH7ySA1J6yWoL_/), using the [new Databricks icon](https://drive.google.com/file/d/1QvtmjSvrRo8Y9T3aRR9e4RHmXMqqFihP/).

Thank you!

Clinton Ford
Staff Partner Marketing Manager
Databricks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4bb287-fa40-af1d-0af9-e8bc30cfb33e
* Version Independent ID: 12ab4c06-2e95-bb73-f62a-2d1eb79bc735
* Content: [Real Time Analytics on Big Data Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics)
* Content Source: [docs/solution-ideas/articles/real-time-analytics.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/real-time-analytics.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#306393

**Comment by jocontr** [comment]
@clintonwford ; thanks for the update. Could you provide the SVG file instead? Also if you have a high-res image of the new logo I will make sure that other diagrams are updated as well. Thank you

**Comment by jocontr** [comment]
@clintonwford closing issue for now. Please reopen once you have news. Thank you.
