### ISSUE TITLE
Oracle database migration overview

### ISSUE THREAD

**Issue by parasparekh** [MicrosoftDocs/architecture-center#2412]
In the Migration decision tree I don't see the option to migrate Oracle databases to SQL Server Azure VM. Is this option for migration not recommended for customers ? I have a customer who is looking to migrate the Oracle databases for their Deltek Costpoint and Kronos (ERP systems), so I was thinking if SQL on Azure VM is a potential migration path for them but I don't see it in the decision tree.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0676437-a746-19de-2df2-7919004a14f0
* Version Independent ID: 35cfce4b-fc76-f140-02fb-9ac605157313
* Content: [Overview of Oracle database migration - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/oracle-migrate/oracle-migration-overview)
* Content Source: [docs/example-scenario/oracle-migrate/oracle-migration-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/oracle-migrate/oracle-migration-overview.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @amberz
* Microsoft Alias: **amberz**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#308176

**Comment by parasparekh** [comment]
Is there a timeline of when the documentation will get updated ?

**Comment by parasparekh** [comment]
hello Abdul, just checking to see if there is an ETA on updated documentation.

**Comment by doodlemania2** [comment]
@parasparekh - we've got this in flight now

**Comment by amberz** [comment]
parasparekh, in the decision tree, there is a option is for Azure VM, we didn't specific to point out to SQL Server VM. For sure, you would go SQL Server VM. Meanwhile, I want to share my thoughts, if customer can accept to do heterogeneous migration from Oracle Database to SQL, we normally suggest customer to to SQL DB/MI given that's platform as service offering, customer is no need to maintain SQL Server VM on Azure. Feel free to reach out me if you'd like to discuss.
