### ISSUE TITLE
How is this asynchronous?!

### ISSUE THREAD

**Issue by abhijeetdalal** [MicrosoftDocs/architecture-center#2413]
I am not able to understand how this is asynchronous? From the example diagram it clearly sends a response status on the first call! The status check call is for post processing!
I may be completely wrong on understanding the complete picture, but are we saying server side asynchronous operation makes client server asynchronous?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/async-request-reply.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @WillEastbury
* Microsoft Alias: **wieastbu**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#308693

**Comment by PramodValavala-MSFT** [comment]
@abhijeetdalal While a response is returned immediately, it is not the final response expected from the initial call. The immediate response contains additional information on how to monitor the state of the actual request while it is being processed behind the scenes.

Normally, the original call would have to wait for processing to complete having to keep the underlying TCP connection open, which could be closed by the network infrastructure or client restarts. Instead, this asynchronous pattern works around such limitations by not having the client wait.

**Comment by WillEastbury** [comment]
I'd concur with Pramod's comment. The overall request reply pattern is asynchronously processed in line with the description. 

The initial response is simply an acknowledgement that the request has been recieved, but not yet processed.

**Comment by PramodValavala-MSFT** [comment]
@abhijeetdalal Just following up here... Hope our previous comments clear things up.

Since there is no doc update required here, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
