### ISSUE TITLE
Reference to "availability"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/architecture-center#2414]
> VMs within the same **availability** are deployed across multiple physical servers, compute racks, storage units, and network switches for redundancy.

I think this sentence was intended to say "availability set".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c00d25f-b981-29e3-bd64-865fda0b0d33
* Version Independent ID: 36bcc6f0-0fa4-df9c-cff5-4fdfb3460432
* Content: [Windows N-tier application on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/n-tier-sql-server)
* Content Source: [docs/reference-architectures/n-tier/n-tier-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/n-tier-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by BhargaviAnnadevara-MSFT** [comment]
@VitalyMCT Thank you for catching that error in the docs! We have updated the docs to reflect the same.
