### ISSUE TITLE
Access Token Management

### ISSUE THREAD

**Issue by reecebradley** [MicrosoftDocs/architecture-center#2415]
Recently, a new NuGet package has entered the space of dealing with this problem of caching tokens. I think this could be part of the solution of the problems stated here.
[IdentityModel.AspNetCore](https://github.com/IdentityModel/IdentityModel.AspNetCore)
Its weird no library like this is in the MS arsenal but hey, IdentityModel is pretty well known at this point. Maybe this will help the next guy/gal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab204a8d-c451-ef99-6610-139a0dee61ac
* Version Independent ID: 23a69ae2-70bc-aab5-bbe1-e9699d57558b
* Content: [Cache access tokens in a multitenant application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache)
* Content Source: [docs/multitenant-identity/token-cache.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/token-cache.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#310529

**Comment by jocontr** [comment]
Thank your for your feedback. We will address this as a request to update our guidance. Thank you.
