### ISSUE TITLE
expand data cache to cover api response caching with cosmos and SQL databases

### ISSUE THREAD

**Issue by ashithraj** [MicrosoftDocs/architecture-center#2416]
Please expand data cache architecture and design to cover API response caching, Caching data from cosmos and Azure SQL databases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8147492d-6f95-4d66-830c-022d63835610
* Version Independent ID: 5cf7b942-0bfa-bb7d-d824-b157e60840df
* Content: [Data cache - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/data-cache-with-redis-cache#feedback)
* Content Source: [docs/solution-ideas/articles/data-cache-with-redis-cache.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/data-cache-with-redis-cache.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#311959

**Comment by jocontr** [comment]
I would recommend also reviewing our pattern library for additional context. Here is one example that may be applicable. https://learn.microsoft.com/en-us/azure/architecture/patterns/cache-aside
