### ISSUE TITLE
Template validation ignores conditional deployment, complains about array-out-of-bounds

### ISSUE THREAD

**Issue by aschechter88** [MicrosoftDocs/architecture-center#2418]
I am trying to conditionally deploy a block of resources based on an array in a parameter that has a default value of `[]`. My resource condition is `[not(empty(parameters('myArray'))]`. I keep getting `property array index out of bounds` errors during validation, except that...the array is supposed to be empty and the entire block should be skipped.

Is the validator sophisticated enough to do this or do I have to concoct something?

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#312284

**Comment by absheik** [comment]
@aschechter88 , please let us know which article this is referring to.

**Comment by aschechter88** [comment]
@absheik Not sure what you mean. It's not a documentation gap. I think I was having trouble with template validation not recognizing a conditional statement over an empty array, and getting array index errors during validation. The validation engine was trying to tell me "hey you're running copyIndex() or something over a blank array, that's invalid" -- except that the block in question wouldn't ever run as long as the array was blank.

**Comment by jocontr** [comment]
@aschechter88 could you provide more context? Azure service, etc.? This bug likely belongs to the service documentation or product; but we would like to not close it and aim to help in any way we can. Thank you

**Comment by jocontr** [comment]
@aschechter88 closing until further info is available. Feel free to reopen / file a new issue with more details. Thank you.
