### ISSUE TITLE
Can you provide a Visio stencil set for download?

### ISSUE THREAD

**Issue by USMA56795** [MicrosoftDocs/architecture-center#2420]
The SVG icons are great, but have to be inserted one at a time into Visio to use them.  Could you provide a Visio stencil file with these icons for use in the desktop client?

Ideally Visio would have the ability to bulk import SVGs to create stencil files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#313893

**Comment by absheik** [comment]
Visio stencils are on the roadmap.  Currently available for Visio Web as announced here.  https://techcommunity.microsoft.com/t5/visio-blog/visually-represent-your-azure-architecture-using-the-latest/ba-p/1634509.

A new version of the Zip file with SVG also published today.  https://docs.microsoft.com/en-us/azure/architecture/icons/
