### ISSUE TITLE
Spelling correction needed

### ISSUE THREAD

**Issue by vkumargit17** [MicrosoftDocs/architecture-center#2423]
Under the **Alternatives** section, first bullet point has 'considrered' misspelled and needs updating to 'considered'
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f10895e-4e1d-1cdd-2d57-32880e0cc45a
* Version Independent ID: 3518d0a5-ffd1-dfa7-6d6b-de2a9ef170d6
* Content: [Azure data platform end-to-end - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end)
* Content Source: [docs/example-scenario/dataplate2e/data-platform-end-to-end.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/dataplate2e/data-platform-end-to-end.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @fabragaMS
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#314961

**Comment by absheik** [comment]
https://github.com/MicrosoftDocs/architecture-center-pr/pull/1870 Fixes this.  @vkumargit17 thanks for creating the issue.
