### ISSUE TITLE
NetApp Files on Azure

### ISSUE THREAD

**Issue by msandbu** [MicrosoftDocs/architecture-center#2426]
can you please update this section here for Azure NetApp Files Currently, up to 1000 IP connections per active VNet are possible. This also includes VNET Peerings as well. To VNET + Peered VNETs (1000 IP's in total)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md)
* Service: **architecture-center**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#317375

**Comment by dsk-2015** [comment]
@msandbu  Thanks for your feedback. It has been incorporated in the article since some time, so closing this issue.
