### ISSUE TITLE
App Gateway flow is incorrect

### ISSUE THREAD

**Issue by JayWitt** [MicrosoftDocs/architecture-center#2435]
I have been able to prove that the App Gateway (v2) doesn't use the front end IP address of the App Gateway as the source IP when communicating to the backend pool. It rather is using the IP address of the nodes. The document should be updated to reflect this. I have a note out of the PG to confirm if this is indeed the case but this is how it worked within my test environment.

As an example, my App Gateway was given an IP address of 10.0.0.10 but the source IP addresses that I saw when communicating to the back end pool where 10.0.0.4 and 10.0.0.5 which were the node IPs that made up the App Gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall and Application Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway#application-gateway-before-firewall)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/gateway/firewall-application-gateway.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#318636

**Comment by erjosito** [comment]
Hey @JayWitt Thanks for your feedback! However you wouldnt have had to check with the PG, that is what the document is saying. "The IP address 192.168.100.7 is one of the instances the Azure Firewall service deploys under the covers, here with the front-end IP address 192.168.100.4. These individual instances are normally invisible to the Azure administrator, but noticing the difference is useful in some cases, such as when troubleshooting network issues."

Where exactly have you seen the error?

**Comment by JayWitt** [comment]
There wasn't so much an error but I realize now how I got confused. Since there isn't a way for the customer to know what IPs are being used, they have to assign the whole subnet range to the NSG rule in order to allow the traffic to flow. I am going to mark this closed. Thanks.
