### ISSUE TITLE
suitable store for storing large datasets of CSV files that also support parallel operations?

### ISSUE THREAD

**Issue by dr-riz** [MicrosoftDocs/architecture-center#2436]
What might be a suitable store for storing large datasets of CSV files that also support parallel operations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ac957c-9568-b3f0-d79e-72a36439bee9
* Version Independent ID: e89413dd-8815-3d38-d7f0-6a6d0268db1e
* Content: [Processing CSV and JSON files - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/csv-and-json#feedback)
* Content Source: [docs/data-guide/scenarios/csv-and-json.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/csv-and-json.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#318658

**Comment by jocontr** [comment]
hi @dr-riz ; could you describe the parallel operations you are interested in pursuing?

**Comment by skabou** [comment]
It's unclear from this problem description which article this applies to, please re-open with additional details if help is still needed.
