### ISSUE TITLE
Reference guide or hint on how to use Rolemanager with Azure AD for Application Roles

### ISSUE THREAD

**Issue by superman-lopez** [MicrosoftDocs/architecture-center#2437]
The article lists 3 options on how to manage app roles.  2 of which are managed on the domain, rather than in the application.  For enterprise applications the developer would likely prefer the roles within the application rather than on its tenants domains.  The last paragraph (_Roles using an application role manager_) hints at using Rolemanager for this purpose, but no explanation is provided on what the approach should be when Azure AD is the identity provider.  It would be very useful to include a reference to a guide or a hint on how this implementation would work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#roles-using-an-application-role-manager)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#319126

**Comment by v-aangie** [comment]
@david-stanford — Possible articles with a solution for Azure AD as the identity provider for managing app roles on the tenant domains (not the app). Link to this?[https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps] OR  https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#common-issues [Common issues](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#common-issues)

**Comment by v-aangie** [comment]
@david-stanford — Possible articles with a solution for Azure AD as the identity provider for managing app roles on the tenant domains (not the app). Link to this? https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps OR  https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#common-issues

**Comment by ThomasPe** [comment]
I just came across this since I was looking for the same explanations as the OP (which I assume is also the OP of this SO post: https://stackoverflow.com/questions/63882343/how-to-add-custom-claims-to-azure-ad-authenticated-user-in-asp-net-core-applicat?rq=1)
Specifially how the RoleManager class can be used in combination with users from Azure Active directory where Roles are stored in a separate database. 
The provided links don't seem to reference this at all. Perhaps it's worth taking another look at this issue since it's specifically listed as an option but there aren't any examples around? @v-aangie @absheik
