### ISSUE TITLE
Need scalable e-commerce web app implementation details, pricing guidance and code examples using Azure serverless 

### ISSUE THREAD

**Issue by sivaraman27** [MicrosoftDocs/architecture-center#2439]
Need scalable e-commerce web app implementation details, pricing guidance and code examples using Azure serverless

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#320045

**Comment by MartinJaffer-MSFT** [comment]
@sivaraman27 issues raised here are generally for documentation feedback.  Is there a document this is in reference to?

**Comment by PramodValavala-MSFT** [comment]
@sivaraman27 Just following up here to see if there is a specific doc that you are referring to?

**Comment by PramodValavala-MSFT** [comment]
@sivaraman27 Since we have not heard back from you, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
