### ISSUE TITLE
Spoke-to-Spoke 

### ISSUE THREAD

**Issue by softcraftsman** [MicrosoftDocs/architecture-center#2440]
There is a lot of confusion around the fact that vnets are non-transitive. This statement about the VPN gateway adds to the confusion. I think it would best if it was expanded to explain how the VPN gateway will advertise the spoke vnets and route between them.

"You can also use a VPN gateway to route traffic between spokes, although this will have impacts in terms of latency and throughput. Also, Azure Firewall or a network firewall appliance provides an additional layer of security."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#spoke-connectivity)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#320647

**Comment by neilpeterson** [comment]
@softcraftsman thanks for opening this issue. We have added a link to clarifying documentation which should publish by tomorrow afternoon.

**Comment by Skmonkay** [comment]
Hi,

I have not had any luck in testing a simple vnet01-Hub-vnet02 spoke-to-spoke connection without a vNA involved.

I have tested options with peerings enabled with transit, routing tables etc. and no luck so far.

Google searches produce the same results i.e. without that vNA it's not a native solution.
