### ISSUE TITLE
Azure Synapse Analytics is mislabeled.  This should be Azure Synapse DW.

### ISSUE THREAD

**Issue by robertwood62** [MicrosoftDocs/architecture-center#2443]
I'm not sure the diagram shown on the page reflects the actual product features and capabilities correctly.  For a start, Azure Synapse Analytics seems to be in the "model and serve" zone, but I think that should be shown as Azure Synapse DW (not Analytics).  The diagram also shows Data Bricks and Data Factory which are now part of Azure Analytics.  So That seems to be wrong also.  Why would you have DB and DF if you have Azure Synapse Analytics.  My guess is that the article is from last year before the Azure Synapse branding and features were fully defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac60d9e-b851-afa6-beeb-74cdaa2a9146
* Version Independent ID: e300615f-1b32-df63-bc89-54b3b17dced5
* Content: [Modern Data Warehouse Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/modern-data-warehouse)
* Content Source: [docs/solution-ideas/articles/modern-data-warehouse.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/modern-data-warehouse.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#322643

**Comment by EdPrice-MSFT** [comment]
This article has been updated: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/enterprise-data-warehouse

Thank you!
