### ISSUE TITLE
HDInsight has got autoscale since this article was published

### ISSUE THREAD

**Issue by herkyjerky** [MicrosoftDocs/architecture-center#2444]
Looks like the text and matrix are outdated when it comes to autoscale features being available for the different technology.  since it's over a year old, there might be more inaccuracies.  here's the info for autoscale on HDI.

https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-autoscale-clusters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba35cbb-4160-0b5d-6829-103b25ad6ce9
* Version Independent ID: fa12ea8e-401a-9567-7b35-ffff532a99b6
* Content: [Choosing a batch processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing)
* Content Source: [docs/data-guide/technology-choices/batch-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/batch-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#322708
