### ISSUE TITLE
Workload	Heavy writes, moderate reads for OLTP?

### ISSUE THREAD

**Issue by djrdba** [MicrosoftDocs/architecture-center#2448]
I used to be a DBA and the normally the ratio of READS to WRITES ratio for any database is the other way i.e. typically 7 or more times reads I/O than write I/O
In your typically OLTP system a write will only be to put the details in once, however the record will be queried several times, even when going through the same screens. Not to mention over the years that data will exist.

Are you sure this statement is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af4555db-76bc-15c1-6b17-ddf5be651b70
* Version Independent ID: 3ec33db3-f67d-6786-aeb3-9737896088bf
* Content: [Online transaction processing (OLTP) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-transaction-processing)
* Content Source: [docs/data-guide/relational-data/online-transaction-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/relational-data/online-transaction-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#325033

**Comment by jocontr** [comment]
In the context of transactional operations; the article aims to identify certain IO behaviors. The context you are referring to where high reads occurs may be better described here: https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-analytical-processing
