### ISSUE TITLE
Error in Key icon in SVG icon set

### ISSUE THREAD

**Issue by lodivanelswijk** [MicrosoftDocs/architecture-center#2449]
The `xlink` namespace declaration is missing in the `<svg>` element in the file 00787-icon-service-Keys.svg in the Azure icon set. This leads to rendering and import failures, e.g. Google Chrome displays the error _'Namespace prefix xlink for href on linearGradient is not defined' and Microsoft Visio shows an error dialog with the message _'Import of image file failed'_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#325417

**Comment by absheik** [comment]
@lodivanelswijk, https://github.com/MicrosoftDocs/architecture-center-pr/pull/1999 will fix the image you have referred to.  Please wait for the pr to merge.
