### ISSUE TITLE
 Incorrect Visio diagram

### ISSUE THREAD

**Issue by samyperis** [MicrosoftDocs/architecture-center#2452]
The Visio diagram referenced for download is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#326243

**Comment by samyperis** [comment]
Sorry, I overlooked the diagrams... my bad

**Comment by AjayKumar-MSFT** [comment]
samyperis, No worries. Thanks for leveraging Azure docs feedback channel to raise this question. Much appreciate your feedback!
