### ISSUE TITLE
Visio is not valid

### ISSUE THREAD

**Issue by c84170ms** [MicrosoftDocs/architecture-center#2453]
[Enter feedback here]
Hi Team,

The reference architecture visio diagram doesnt contain anything. Please upload valid one.

https://archcenter.blob.core.windows.net/cdn/azure-stack-vm-dr.vsdx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7004da9f-5b68-9962-2bfb-628e66052c9e
* Version Independent ID: c2e11625-cc3a-2fe0-28c4-6ab2f26f227a
* Content: [Disaster Recovery for Azure Stack Hub virtual machines - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-stack-vm-dr)
* Content Source: [docs/hybrid/azure-stack-vm-dr.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/azure-stack-vm-dr.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#326646

**Comment by josevarela** [comment]
@c84170ms Thanks for reporting this issue. I uploaded a new file to the CDN and confirmed that it works properly.
