### ISSUE TITLE
Could not select "Download Button" even though selected checkbox for "agree to the above terms"

### ISSUE THREAD

**Issue by rkokomo** [MicrosoftDocs/architecture-center#2458]
[Enter feedback here]
I could not select "Download SVG icons" button even though selected "I agree to the above terms". I found, if locale is "ja-jp", URL is "https://docs.microsoft.com/ja-jp/azure/architecture/icons/", there are this issue. If locale is "en-us", URL is "https://docs.microsoft.com/en-us/azure/architecture/icons/" , there are no this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by rkokomo** [comment]
Thank you for your information. I'll close this issue.
