### ISSUE TITLE
Azure Functions

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/architecture-center#2461]
Hello,

"**Azure Functions** allows you to run code without managing the underlying infrastructure on where the code is run. **Azure functions** provide a cost-effective, scalable, and event-driven platform for building applications and running operational tasks. **Azure functions** support running code written in C#, Java, JavaScript, Python, and PowerShell."

"Azure Functions" is sometimes written without capitalized "functions". Is it the same solution? Or is it about "functions" from Azure?

Best regards,
François
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9729842-614a-55ca-7848-ea4c5f8ddfdc
* Version Independent ID: ea0cf873-04da-6fb8-1ca3-b087da4471f4
* Content: [Automated Tasks - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/automation-tasks)
* Content Source: [docs/framework/devops/automation-tasks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/automation-tasks.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @neilpeterson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#328098

**Comment by neilpeterson** [comment]
@FranNev thanks for opening this issue. You are correct the casing is not accurate and has been according to our style guide. Updates will be published later today.

```
Azure Functions is a solution for easily running small pieces of code, or "functions," in the cloud.

Guidelines

First mention: Microsoft Azure Functions

You can omit Microsoft if at least one of the following conditions applies:

The Microsoft logo appears in proximity to the Azure service name—like on the same screen or surface.
The word Microsoft has already been used in text earlier in the communication—like in an earlier reference to a product name.
Subsequent mentions: Azure Functions, Functions

Use Azure Functions as necessary to distinguish it as an Azure service. It's OK to use just Functions when the context makes it clear you're referring to the Azure service.

To refer to something built using Functions or in a generic reference, use lowercase function app.
```

In regards to your query, the instance Azure function is referring to the Azure service.

**Comment by neilpeterson** [comment]
PR has been merged, I will close this now. @FranNev if you need anythign else or want to re-open for any reason, feel free to do so.

![image](https://user-images.githubusercontent.com/7844635/97328811-9fe64880-1833-11eb-83d8-394067b2f514.png)
