### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/architecture-center#2463]
Hello, I think there is a typo here: "To see a Microsoft Incite video" => Should be: "To see a Microsoft Ignite video".

Best regards,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745e0224-7dde-67aa-eeb7-6a11a58cdf83
* Version Independent ID: 9258af0c-411c-210f-6efa-fd63e0c75f88
* Content: [Automation overview of goals, best practices, and types in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/automation-overview)
* Content Source: [docs/framework/devops/automation-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/automation-overview.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#328218

**Comment by neilpeterson** [comment]
Thanks, this has been update and will publish today or tomorrow.
