### ISSUE TITLE
Is this up-to-date, as GitHub response says the code base is in sustain?

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/architecture-center#2464]
Is this page up-to-date, as GitHub response says the code base is in sustain?
i.e. at  https://github.com/MicrosoftDocs/architecture-center/issues/2084#issuecomment-617326234

*@josem0287 Please don't use AZBB. The code base is in sustain and no further development is scheduled. *

It would be good to have at least an indication that it's no longer being developed

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c819aa-de8a-5fb2-72ae-78119e03345f
* Version Independent ID: 2b681a1d-c6f1-4926-a09f-7bfc45ec690b
* Content: [Extend Azure Resource Manager template functionality - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/building-blocks/extending-templates/)
* Content Source: [docs/building-blocks/extending-templates/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/building-blocks/extending-templates/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#328757
