### ISSUE TITLE
Link to Azure ML Experimentation Service seems to be pointing to wrong destination

### ISSUE THREAD

**Issue by mbellinasoUS** [MicrosoftDocs/architecture-center#2465]
[Enter feedback here]
The link for "Learn more about Azure Machine Learning Experimentation Service" is pointing to an article about virtual network isolation and privacy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 947848c1-c1a3-4241-4ce0-e8743d539d17
* Version Independent ID: f0c88a85-6601-0361-9bd0-d80092582d0b
* Content: [Information discovery with deep learning and NLP - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/information-discovery-with-deep-learning-and-nlp)
* Content Source: [docs/solution-ideas/articles/information-discovery-with-deep-learning-and-nlp.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/information-discovery-with-deep-learning-and-nlp.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#328811
