### ISSUE TITLE
Is any live demo available for this solution idea? from  billjin@microsoft.com

### ISSUE THREAD

**Issue by chinabilljin** [MicrosoftDocs/architecture-center#2469]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041da9ff-57a4-916d-ae12-8b1e4fe77d44
* Version Independent ID: a56ac57e-3796-559f-261f-76061e0e4810
* Content: [Blockchain Workflow Application - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/blockchain-workflow-application)
* Content Source: [docs/solution-ideas/articles/blockchain-workflow-application.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/blockchain-workflow-application.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#329287

**Comment by EdPrice-MSFT** [comment]
This is in progress.

**Comment by v-fearam** [comment]
The referenced content is not available any more. 
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
