### ISSUE TITLE
Link to the Komatsu Story is no longer valid at the bottom of this page

### ISSUE THREAD

**Issue by RyanTBerry** [MicrosoftDocs/architecture-center#2470]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5c2b717-8cbb-8794-3a5c-3086e76f1717
* Version Independent ID: 6d6ea7d8-05ec-7903-1df5-6d3fc248a123
* Content: [IoT and data analytics - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/big-data-with-iot)
* Content Source: [docs/example-scenario/data/big-data-with-iot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/data/big-data-with-iot.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#330113

**Comment by EdPrice-MSFT** [comment]
Got it. I removed the dead link and added in some other links we should have. Thanks!
