### ISSUE TITLE
This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.

### ISSUE THREAD

**Issue by db0mz** [MicrosoftDocs/architecture-center#2471]
C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows>azbb -s 80314534-8a20-4ecc-988a-f7ea09a45070 -g DanB -l westus2 -p n-tier-windows.json --deploy

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-01.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-02.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-03.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-04.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-05.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-06.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-07.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-08.json

  parameters written to C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-09.json

This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
Unable to parse parameter: @C:\Users\dbomgardner\Nexus

  error: error executing az
  status: 1
  arguments: group deployment create --name bb-01-vnet --subscription 80314534-8a20-4ecc-988a-f7ea09a45e70 --resource-group DanB --template-uri https://raw.githubusercontent.com/mspnp/template-building-blocks/v2.2.0/templates/buildingBlocks/virtualNetworks/virtualNetworks.json --parameters @C:\Users\dbomgardner\Nexus Technologies Inc\Azure RM Templates\ntier-windows\n-tier-windows-output-01.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c00d25f-b981-29e3-bd64-865fda0b0d33
* Version Independent ID: 36bcc6f0-0fa4-df9c-cff5-4fdfb3460432
* Content: [Windows N-tier application on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/n-tier-sql-server#deploy-the-solution)
* Content Source: [docs/reference-architectures/n-tier/n-tier-sql-server.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/n-tier-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @db0mz, Thank for reaching out. Can you please let me know the exact document where you found the issue mentioned above?

**Comment by db0mz** [comment]
This was script output from the command associated with the n-tier-windows deployment using azbb
azbb -s 80314534-8a20-4ecc-988a-f7ea09a45070 -g DanB -l westus2 -p **n-tier-windows.json** --deploy

**Comment by db0mz** [comment]
I'm trying to deploy the architecture here using the "Deploy this architecture" 
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/n-tier-sql-server#deploy-the-solution

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Thank you @db0mz . We have assigned this issue to the author to review further and take the next course of action.

**Comment by db0mz** [comment]
Many thanks!

**Comment by db0mz** [comment]
so is there a way to track if this gets resolved?

**Comment by skabou** [comment]
It appears this was resolved in early 2021, please re-open with additional details if help is still needed.
