### ISSUE TITLE
No mention of Azure Logic Apps

### ISSUE THREAD

**Issue by genarotre** [MicrosoftDocs/architecture-center#2473]
[Enter feedback here]
I didn't saw any mention of Azure Logic Apps a an option either to migrate o implement a new service. it is consider inside one of the other options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#330952

**Comment by dsk-2015** [comment]
Closing this issue as a note under the "Understanding the hosting model" addresses this.
