### ISSUE TITLE
Business Central on Azure Implementation Details

### ISSUE THREAD

**Issue by gchatira** [MicrosoftDocs/architecture-center#2474]
Good day Team Microsoft

I would love to get Dynamics Business Central on Azure implementation details with a good reference architecture too.
There seem to be a big demand for this solution here in Africa.
Will really appreciate your feedback.

Regards,

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#331229

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24406 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
