### ISSUE TITLE
Unable to view the three sample cost profiles

### ISSUE THREAD

**Issue by nvinod-net** [MicrosoftDocs/architecture-center#2477]
Unable to view the three sample cost profiles. The pricing calculator loads an empty view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5978df0f-98f5-f365-1912-48fc8c27566e
* Version Independent ID: 4f2b4216-1cc7-a267-eee4-d7716ce5ed03
* Content: [CI/CD pipeline for container-based workloads - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-with-aks)
* Content Source: [docs/example-scenario/apps/devops-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/devops-with-aks.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @iainfoulds
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#331608

**Comment by neilpeterson** [comment]
Looks like this was resolved, closing issue.
