### ISSUE TITLE
Warning changing FlipFlopProfileDirectoryName during Production required

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/architecture-center#2478]
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#best-practice-settings-for-enterprises
If you add **FlipFlopProfileDirectoryName** when in Production, it will create new profiles for all users, just not new users. Caused a SevA for one of our customers, as Users had a new profile instead of the original profile when login

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md)
* Service: **architecture-center**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#331758

**Comment by DavidTaig** [comment]
Please provide an update. Thanks
