### ISSUE TITLE
Seems like the labels on the LB's are reversed

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/architecture-center#2480]
Looking at the diagram on this page, it seems like the lb labels are reversed.
The "front" LB is labeled ILB, while the LBs in the tiers behind it are labeled "LB".
My understanding is that in Azure, we typically call la LB with a public IP a "Load Balancer", while a LB with a private IP is called an "Internal Load Balancer" or "ILB".   See:  https://docs.microsoft.com/en-us/azure/load-balancer/components#frontend-ip-configurations

Hence I believe the labels on this chart are reversed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2442849c-9e87-56b2-dffd-5c8089e8132c
* Version Independent ID: 828da465-186b-f819-9575-ee51e8c83306
* Content: [Multi-tier web application built for HA/DR - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/multi-tier-app-disaster-recovery)
* Content Source: [docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @sujayt
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#332004

**Comment by BryanLa** [comment]
@larryclaman - our apologies for the long delay on this, and thanks for this contribution. 

The diagram has been updated and will republish tomorrow morning, Pacific time.

#please-close
