### ISSUE TITLE
Render Cycle of a payload

### ISSUE THREAD

**Issue by anshuman-nath** [MicrosoftDocs/architecture-center#2481]
[Enter feedback here]
Under "Caching" subsection, there's a statement which goes "Every render cycle of a payload will consume Compute & Memory". What is meant by Render Cycle of a payload ? Can you point me to any resource where I can read more on this concept ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8826a1c7-1335-0bf1-26f9-8dc77fbdf20f
* Version Independent ID: 75fd4df2-2d30-ee46-8792-b3fc887eadbe
* Content: [Tradeoffs for costs - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/tradeoffs)
* Content Source: [docs/framework/cost/tradeoffs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/cost/tradeoffs.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#332033

**Comment by jocontr** [comment]
Hi @anshuman-nath, apologies for the confusion. After reading the passage I can see how it could lack context.

I am guessing the intend of the author was within the context of rending static content on the compute (server) tier. That could be translated to many forms of output. In the end the point the author is trying to convey is the use of caching for these binary outputs that may be static in nature or potentially do not change often (of course that depends on business needs).
