### ISSUE TITLE
Typo "Identify provider" should be "Identity provider"

### ISSUE THREAD

**Issue by msimecek** [MicrosoftDocs/architecture-center#2482]
In the **Use Identity based storage access controls** section there's probably a typo in the sentence beginning:

> Identify provider methods of authentication and authorization...

It should be:

> *Identity* provider methods of authentication and authorization...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34c47f2-1c90-5001-e848-6ac4ae9e33e6
* Version Independent ID: 4e9b11df-48b4-5eac-7bce-bb70ec91e384
* Content: [Storage, data, and encryption in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/Security/storage-data-encryption?source=docs#use-identity-based-storage-access-controls)
* Content Source: [docs/framework/security/storage-data-encryption.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/storage-data-encryption.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by BhargaviAnnadevara-MSFT** [comment]
@msimecek Thank you for catching that error in the docs. I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
