### ISSUE TITLE
Links need to be updated

### ISSUE THREAD

**Issue by meshayesh** [MicrosoftDocs/architecture-center#2484]
Hi Team, the links at the end of the article needs to be updated as it is giving me 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video)
* Content Source: [docs/solution-ideas/articles/digital-media-video.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-video.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#333890

**Comment by neilpeterson** [comment]
@meshayesh thanks for submitting this issue. These links have been updated and will publish later today.
