### ISSUE TITLE
Can't automatically generate code?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/architecture-center#2485]
> However, one disadvantage is that CQRS code can't automatically be generated from a database schema using scaffolding mechanisms such as O/RM tools.

This would be more correct to say "CQRS and Entity Framework are not comparable, but CQRS can be implemented atop the things that Entity framework generates". It's also possible (and preferred) to use code generation to generate entities and some related CQRS code from only a database table with proper keys defined and skip EF entirely.

_(Sorry for the multiple edits, was reaching for the apostrophe and kept hitting `Enter`)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [CQRS pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#334120

**Comment by StingyJack** [comment]
@absheik  - I had to edit it a bit in case you need to transfer any of the updated text.  

That link you posted is a 401.

**Comment by v-fearam** [comment]
#please close

**Comment by v-fearam** [comment]
#please-close
