### ISSUE TITLE
Missing icon for Azure Databricks

### ISSUE THREAD

**Issue by guruvonline** [MicrosoftDocs/architecture-center#2486]
Hi,
the example architecture diagram shows, Azure Databricks . But when I download all icons, i don't see icon for Azure databricks.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#334503

**Comment by absheik** [comment]
a new version of the Icon set is now available at https://docs.microsoft.com/en-us/azure/architecture/icons/ with Download file name Azure_Public_Service_Icons_V4.zip
Databricks is 3rd party.
