### ISSUE TITLE
Outdated security pillar pages?

### ISSUE THREAD

**Issue by RicardoNiepel** [MicrosoftDocs/architecture-center#2487]
Multiple links on this page link to pages which are not in the main navbar on the left side:
* https://docs.microsoft.com/en-us/azure/architecture/framework/security/role-of-security
* https://docs.microsoft.com/en-us/azure/architecture/framework/security/architecture-type
etc.

It is unclear if these pages are outdated or the navbar items are just missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55000863-6c61-319b-7d0d-5366c403e5e2
* Version Independent ID: 7bb9bb22-f939-6176-236f-79399b6ab2b4
* Content: [Overview of the security pillar - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/overview)
* Content Source: [docs/framework/security/overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/overview.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#334545

**Comment by hallihan** [comment]
I believe this links have been cleaned up in previous edits.
