### ISSUE TITLE
Can you expand on data flow item 8?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [MicrosoftDocs/architecture-center#2488]
I would like to know with more details how/if can Databricks output data to a CosmosDB that uses mongo API. Its the item number 8 on the architecture

Thank in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4bb287-fa40-af1d-0af9-e8bc30cfb33e
* Version Independent ID: 12ab4c06-2e95-bb73-f62a-2d1eb79bc735
* Content: [Real Time Analytics on Big Data Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics)
* Content Source: [docs/solution-ideas/articles/real-time-analytics.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/real-time-analytics.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#334859

**Comment by EdPrice-MSFT** [comment]
In progress.

**Comment by EdPrice-MSFT** [comment]
This scenario was updated, and a few of these aspects were changed so much that the request needs to be re-evaluated. Thank you!
