### ISSUE TITLE
Inconsistent presentation of content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#2491]
This discussion of hybrid identity for azure stack is not consistent with the other identity architecture writeups. It would good if address security and all of the other topics that are mentioned in the other architectures

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#335505

**Comment by neilpeterson** [comment]
@DeanGross thanks for opening this issue. I'm assuming this in reference to this article.

https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/hybrid-identity

We recognize that the solution ideas articles are lacking in information and have a team working on what the next steps should be for 'solution ideas'. This will not be a quick fix, but hopefully we can add some substance to this content in the future.

I am going to close this issue in favor of the larger effort.
