### ISSUE TITLE
Sample code incorrect

### ISSUE THREAD

**Issue by ian-barlow** [MicrosoftDocs/architecture-center#2492]
$hubPeerings = Get-AzVirtualNetworkPeering -ResourceGroupName $HubVNetRGName -VirtualNetworkName $HubVNetName

Generates an array but the following cmdlet requires a single input for -name parameter

Remove-AzVirtualNetworkPeering -VirtualNetworkName $HubVNetName -ResourceGroupName $HubVNetRGName -name $hubPeerings.Name -Force

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636aa53e-3ca0-7a30-fe16-7219f3e8d1a9
* Version Independent ID: c503b39a-cd8a-669a-0882-27d8c13d3570
* Content: [Add IP address spaces to peered virtual networks - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/prefixes/add-ip-space-peered-vnet)
* Content Source: [docs/networking/prefixes/add-ip-space-peered-vnet.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/networking/prefixes/add-ip-space-peered-vnet.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @randycampbell
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#336181

**Comment by Zimmergren** [comment]
A previous version of this article was using the array as opposed to an instance of a peering. It has since been corrected.

#please-close
