### ISSUE TITLE
ARM Template Deployment Fails

### ISSUE THREAD

**Issue by neilpeterson** [MicrosoftDocs/architecture-center#2493]
Assign to neilpeterson / nepeters.

Issue:

```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "You cannot create or modify classic metric alerts for this subscription as this subscription 3762d87c-ddb8-425f-b2fc-29e5e859edaf is being migrated or has been migrated to use new metric alerts. Learn more - aka.ms/alertclassicretirement"
    },
    {
      "code": "BadRequest",
      "message": "You cannot create or modify classic metric alerts for this subscription as this subscription 3762d87c-ddb8-425f-b2fc-29e5e859edaf is being migrated or has been migrated to use new metric alerts. Learn more - aka.ms/alertclassicretirement"
    },
    {
      "code": "BadRequest",
      "message": "You cannot create or modify classic metric alerts for this subscription as this subscription 3762d87c-ddb8-425f-b2fc-29e5e859edaf is being migrated or has been migrated to use new metric alerts. Learn more - aka.ms/alertclassicretirement"
    },
    {
      "code": "BadRequest",
      "message": "You cannot create or modify classic metric alerts for this subscription as this subscription 3762d87c-ddb8-425f-b2fc-29e5e859edaf is being migrated or has been migrated to use new metric alerts. Learn more - aka.ms/alertclassicretirement"
    }
  ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84bcf722-abb3-69b8-8073-15ae4a6890de
* Version Independent ID: 7b2010c6-696d-de66-8e56-8ac5d3e54526
* Content: [Basic web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app)
* Content Source: [docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/basic-web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#336316

**Comment by neilpeterson** [comment]
Fixed with this PR - https://github.com/mspnp/reference-architectures/pull/371
