### ISSUE TITLE
No Nest Step section in Data considerations page

### ISSUE THREAD

**Issue by pbuzulan** [MicrosoftDocs/architecture-center#2495]
Hi, 

Next Step section is missing in [Data Consideration page](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/data-considerations)
It should be connected to the next page which is [Design patterns for microservices](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/patterns)

Basically the follow lines are missing in the first document:

```
## Next steps
> [!div class="nextstepaction"]
> [Design patterns for microservices](./patterns.md)
```
It might be a stupid error but if someone doesn't pay attention, he/she will not read the next page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb25545c-958f-99b0-b321-74e556ad4557
* Version Independent ID: ebe36da6-a15f-f981-787d-8aa4307451a2
* Content: [Data considerations for microservices - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/data-considerations)
* Content Source: [docs/microservices/design/data-considerations.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/design/data-considerations.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#336588

**Comment by dsk-2015** [comment]
Thanks for point this out, the article is updated now. Closing this issue.
