### ISSUE TITLE
Visio images is old not same as what show on this page

### ISSUE THREAD

**Issue by khanzzirfan** [MicrosoftDocs/architecture-center#2496]
[Enter feedback here]
Downloaded the visio image, but it not the same one as shown on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#336971

**Comment by neilpeterson** [comment]
@khanzzirfan the included Visio file includes multiple tabs, one of which is multi-region, which includes this diagram. We are considering options for making this more obvious. Thanks for submitting the issue.
