### ISSUE TITLE
IoT in Field Services

### ISSUE THREAD

**Issue by squassina** [MicrosoftDocs/architecture-center#2498]
This document is great! It would be very useful it there is a similar document with samples regarding Field Service. 

Some example scenarios on Field services may be created taking this documentation as reference and also the example scenarios in [this link](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/iot/introduction-to-solutions).

Does it make sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34a1f576-5102-4751-776d-54d6fbc4516b
* Version Independent ID: 5f469a50-7a3c-4ab5-acda-0e803392b859
* Content: [Predictive Maintenance for Industrial IoT - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/iot-predictive-maintenance)
* Content Source: [docs/solution-ideas/articles/iot-predictive-maintenance.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/iot-predictive-maintenance.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **losampai**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#337329

**Comment by SumanthMarigowda-MSFT** [comment]
@squassina Thanks for the question! We are investigating and will update you shortly.

**Comment by EdPrice-MSFT** [comment]
Great feedback. Thank you!

**Comment by EdPrice-MSFT** [comment]
Working with @squassina and team to create the missing content.
