### ISSUE TITLE
Machine Learning model training with AKS

### ISSUE THREAD

**Issue by samuda2019** [MicrosoftDocs/architecture-center#2499]
Please provide code sample for this architecture.
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/machine-learning-with-aks

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#337472

**Comment by SumanthMarigowda-MSFT** [comment]
@samuda2019 Thanks for the question! We are investigating and will update you shortly.

**Comment by EdPrice-MSFT** [comment]
Thank you for the feedback!

**Comment by skabou** [comment]
https://docs.microsoft.com/en-us/azure/machine-learning/v1/how-to-deploy-azure-kubernetes-service?tabs=python#deploy-to-aks

If additional help is needed, please re-open with additional details.
