### ISSUE TITLE
Minor typo in "context and problem" section

### ISSUE THREAD

**Issue by crichthammer** [MicrosoftDocs/architecture-center#2500]
Hi,

I just wanted to make you aware of a minor typo (or editing mistake) in the "context and problem" section. In the last sentence of the first paragraph, it says: "... and is likely to **accesses** storage and other services on behalf of the client."

However, it should be "... is likely to **access** storage ..."

Cheers
Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428e4625-191f-a050-ec58-60fd2dddff86
* Version Independent ID: 3a4e385e-5761-3633-1ddf-46e1878b420d
* Content: [Gatekeeper pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/gatekeeper?source=docs)
* Content Source: [docs/patterns/gatekeeper.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/gatekeeper.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#
