### ISSUE TITLE
Request for more detailed information

### ISSUE THREAD

**Issue by KottosAdmin** [MicrosoftDocs/architecture-center#2504]
The links for further information at the end of the article ( https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/medium-umbraco-web-app ) lead to 404 Page Not found errors.  It would be nice if complete documentation was available.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#338187

**Comment by EdPrice-MSFT** [comment]
Thank you. We're identifying the newer articles.
