### ISSUE TITLE
Azure WebApp private database connectivity

### ISSUE THREAD

**Issue by sameer-kumar** [MicrosoftDocs/architecture-center#2506]
While looking for solution of my use case, I was brought into this page [here](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app).
However this is not exactly I have designed my architecture. I'm looking for accessing Azure SQL PaaS from Azure WebApp via Managed Identity and Private EndPoint but couldn't find any documentation or guidance.

I have an AspNetCore3.1 app hosted on Linux Azure WebApp with Private Endpoint. I have also enabled system assigned Managed Identity(MI) on the web app and added that as contained user to my Azure SQL PaaS. However, I could not establish sql connection and my app returns errors:

> Connection was denied since Deny Public Network Access is set to Yes (https://docs.microsoft.com/azure/azure-sql/database/connectivity-settings#deny-public-network-access). To connect to this server, use the Private Endpoint from inside your virtual network (https://docs.microsoft.com/azure/sql-database/sql-database-private-endpoint-overview#how-to-set-up-private-link-for-azure-sql-database). at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)

There is Private Endpoint configured for SQL PaaS too. This one is in different subnet but same VNet as webapp's private endpoint is in.

Is this design supported ? Any links/docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7499b146-3340-d7d1-6c5f-3ed508b773cb
* Version Independent ID: 61b10612-1136-3840-c7c1-804e63b23410
* Content: [Web app private connectivity to Azure SQL database - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app)
* Content Source: [docs/example-scenario/private-web-app/private-web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/private-web-app/private-web-app.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jelledruyts
* Microsoft Alias: **jelled**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#338573

**Comment by jelledruyts** [comment]
Hi @sameer-kumar, whether or not you are using a managed identity should have nothing to do with the error that you are seeing, as at this point you're still trying to _connect to SQL_ and not yet _authenticate_. The error message clearly calls out that you are coming in to SQL over its public IP address, not the private endpoint. So this looks like a networking problem which is indeed the core of the article, and the way you describe it should be supported indeed (as it's very similar to the setup in the article).

Have you ensured that you have configured all the necessary settings on the web app? Most of all, is App Service regional VNet integration setup to the VNet which holds the SQL private endpoint? Is the "WEBSITE_VNET_ROUTE_ALL" app setting set to 1? Do you have DNS configured on the VNet or via an app setting "WEBSITE_DNS_SERVER" set to "168.63.129.16" as per the article? I would suggest to follow the [Deploy this scenario](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app#deploy-this-scenario) walkthrough carefully and see if that solves the connectivity issue.

Thanks!

**Comment by sameer-kumar** [comment]
@jelledruyts After I tried all the steps as suggested in your [link](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app#deploy-this-scenario), my web app itself is not accessible now. 
To troubleshoot I used kudu console from webapp and tried to execute below commands which fails (no response):
```
tcpping mysqldb.database.windows.net
tcpping google.com
```

**Comment by sameer-kumar** [comment]
@jelledruyts I can confirm that when I followed the same steps in Windows App Service instead of Linux, it works like a charm. So looks like Linux is not fully baked yet.

**Comment by jelledruyts** [comment]
I have this running with Linux as well so can definitely confirm it should work. Next to possibly opening a support ticket, I would suggest to follow the exact same steps once more with a Linux app and for example use my [InspectorGadget](https://github.com/jelledruyts/InspectorGadget) container image which allows you to do DNS lookups, SQL connections, HTTP requests etc for easy troubleshooting. Just create a new Linux web app, use a custom Docker container from Docker Hub and simply set the image to "jelledruyts/inspectorgadget". Then you can use the web app to resolve the SQL's DNS to an IP address (which should return the private endpoint if all is well), and connect to SQL to execute a query. The default SQL query used by the app returns the client's IP address which in this case (the client being the VNet integrated web app) should come from within the VNet IP range as well. All of this is optional of course, but a very easy way to troubleshoot and play around with web apps.

**Comment by sameer-kumar** [comment]
@jelledruyts when I tried your image then SQL connection screen works after VNet integration. Strange! I'm thinking what is different in my web app which doesn't work in Linux after Vnet integration? I'm clueless here.

**Comment by sameer-kumar** [comment]
@jelledruyts this is what I can see from logs:

> 2020-11-20T23:28:48.174Z ERROR - Container create failed for abc02_0_941b2597 with System.Exception, Error in get or Add Endpoint: Failed to GetOrCreateNetwork e31c2d40-5e13-4be5-b0ac-147857827aab_Subnet-ABC-001: Failed pre-setup: Failed to create the NC(2c298cb9-7e4c-c1a3-40d8-983e1ca3fc3d) for subnet Subnet-ABC-001 in vnet e31c2d40-5e13-4be5-b0ac-147857827aab, err: NMAgent returned status code 401

**Comment by jelledruyts** [comment]
Good to hear it works with the InspectorGadget image. I'd definitely suggest to open a support ticket then (e.g. via the Portal), as the scenario is certainly supported, but looks like your app may be having an issue.

**Comment by sameer-kumar** [comment]
Got it. Thank you for your support.

**Comment by JasRobe** [comment]
@jelledruyts thank you for your engagement here.   and @sameer-kumar thank you for reaching out.
