### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by GeorgScholz** [MicrosoftDocs/architecture-center#2509]
In the picture, it is written "IDistrubutedTokenCache" instead of "IDistributedTokenCache".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab204a8d-c451-ef99-6610-139a0dee61ac
* Version Independent ID: 23a69ae2-70bc-aab5-bbe1-e9699d57558b
* Content: [Cache access tokens in a multitenant application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache)
* Content Source: [docs/multitenant-identity/token-cache.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/token-cache.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by SumanthMarigowda-MSFT** [comment]
@GeorgScholz Thanks for your question. We are checking on this and will respond to you soon.

**Comment by hallihan** [comment]
The graphic with the typo was removed during other edits on the article.
