### ISSUE TITLE
Wrong link to Microsoft Azure IoT Reference Architecture (PDF)

### ISSUE THREAD

**Issue by Marusyk** [MicrosoftDocs/architecture-center#2514]
Next steps section: Wrong link to Microsoft Azure IoT Reference Architecture (PDF)

It should be https://download.microsoft.com/download/A/4/D/A4DAD253-BC21-41D3-B9D9-87D2AE6F0719/Microsoft_Azure_IoT_Reference_Architecture.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#340146

**Comment by Marusyk** [comment]
Seems to be fixed.
