### ISSUE TITLE
Add JavaScript to General capabilities table for PostgreSQL

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [MicrosoftDocs/architecture-center#2515]
Capability matrix -> General capabilities 
There is also plv8 - PL/JavaScript (v8) trusted procedural language
which is an extension for Azure Database for PostgreSQL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af4555db-76bc-15c1-6b17-ddf5be651b70
* Version Independent ID: 3ec33db3-f67d-6786-aeb3-9737896088bf
* Content: [Online transaction processing (OLTP) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-transaction-processing)
* Content Source: [docs/data-guide/relational-data/online-transaction-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/relational-data/online-transaction-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#340513

**Comment by v-fearam** [comment]
#please-close
