### ISSUE TITLE
Visio stencil format ?

### ISSUE THREAD

**Issue by michwii** [MicrosoftDocs/architecture-center#2516]
Hi MS,

Could you please organize your icons into Visio Stencil format ?
As an Architect using Visio, it's easier to import stencil rather than SVG icons.

Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/?WT.mc_id=thomasmaurer-blog-thmaure)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@michwii Thank you for your feedback! We will review and update as appropriate.

**Comment by absheik** [comment]
**Are these icon assets available in Visio or as VSS files?**
Not yet, but they will be very soon. We are working with the Visio product team. In the meantime, you
can use the Import function in Visio. Learn more about importing icons to Visio. https://support.microsoft.com/en-us/office/import-or-insert-graphics-into-visio-drawings-f05e556d-a158-4e16-9bd8-5d45071c9b8c
