### ISSUE TITLE
Missing Icon for Azure Machine Learning

### ISSUE THREAD

**Issue by anisayari** [MicrosoftDocs/architecture-center#2517]
Hello, There is no icon for Azure Machine Learning ( https://azure.microsoft.com/en-us/services/machine-learning/ ). Thank you :-)

**Comment by MonikaReddy-MSFT** [comment]
@anisayari - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by absheik** [comment]
a new version of the Icon set is now available at https://docs.microsoft.com/en-us/azure/architecture/icons/ with Download file name Azure_Public_Service_Icons_V4.zip, this has a folder of icons for AI and machine learning
