### ISSUE TITLE
Information incorrect on trusts

### ISSUE THREAD

**Issue by ithurley** [MicrosoftDocs/architecture-center#2518]
"It is possible to create a two-way trust if cloud users also require access to on-premises resources."

It is not possible to create this kind of trust in Azure ADDS, please correct this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b605d93-ab34-f8f0-2c64-d38fc5b0ab51
* Version Independent ID: 6e418fbb-e9f8-fa03-ef0e-ab6940ab62ce
* Content: [Create an AD DS resource forest in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-forest)
* Content Source: [docs/reference-architectures/identity/adds-forest.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-forest.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by krish-gh** [comment]
@ithurley Thanks! We will have a look on it.

**Comment by magrande** [comment]
@ithurley @shashishailaj  Thank you. There is a correction already applied. It's going to be live soon.

**Comment by ithurley** [comment]
Hi Mariano,

Thanks for correcting that page, it looks much better, but please be aware that the highlights are not possible with AADDS;

Create an AD DS resource forest in Azure - Azure Reference Architectures | Microsoft Docs<https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-forest>

[cid:image001.png@01D6CF48.24183710]

Regards,


Ian Thurley
Specialist, vmware & Wintel Solutions
MacPeach, Inc.
PO Box 72904 Marietta GA 30007-2904
(770) 578-3775 Work
(770) 355-2553 Cell
ithurley@macpeach.com<mailto:ithurley@macpeach.com>

[cid:image002.png@01D6CF48.24183710][azure-fundamentals-600x600][cid:image006.png@01D6CF48.C17D2F10][azure-solutions-architect-expert-600x600]

**Comment by shashishailaj** [comment]
@ithurley . Thank you for your patience. We are closing this issue now.

**Comment by ithurley** [comment]
No problem, thank you. I see the page still has incorrect information regarding the ability to create two way trusts. I think maybe you are saying you are working on a correction? That would be great, because our customers are coming to us, asking for two way trusts to AADDS only to find it’s not possible, and then move to AWS, where it is.

This is a problem for Microsoft and is causing you to lose revenue to AWS. I hope you can correct soon, as my customers are losing faith in Microsoft’s ability to understand their own product.

[cid:image010.jpg@01D6D592.B5762A50]


Regards,


Ian Thurley
Specialist, vmware & Wintel Solutions
MacPeach, Inc.
PO Box 72904 Marietta GA 30007-2904
(770) 578-3775 Work
(770) 355-2553 Cell
ithurley@macpeach.com<mailto:ithurley@macpeach.com>

[cid:image003.png@01D6D592.9D241F20][azure-fundamentals-600x600][cid:image012.png@01D6D592.B5762A50][azure-solutions-architect-expert-600x600]
