### ISSUE TITLE
App Service Global Vnet Peering

### ISSUE THREAD

**Issue by kmkelly2015** [MicrosoftDocs/architecture-center#2519]
Is there a plan to enhance App Service VNet integration to utilise global vnet peering?
So that app services can access SQL Databases via private endpoints in different regions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7499b146-3340-d7d1-6c5f-3ed508b773cb
* Version Independent ID: 61b10612-1136-3840-c7c1-804e63b23410
* Content: [Web app private connectivity to Azure SQL database - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app#global-peering)
* Content Source: [docs/example-scenario/private-web-app/private-web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/private-web-app/private-web-app.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jelledruyts
* Microsoft Alias: **jelled**

**Comment by jelledruyts** [comment]
@kmkelly2015 yes global peering support is planned, but even without it you can connect to a SQL Database (or other dependency) in another region by publishing the private endpoint of the database in one region into the VNet of the other region where the app is deployed. You have to take care of properly setting up DNS for that to work correctly, but definitely possible.

**Comment by kmkelly2015** [comment]
@jelledruyts thanks for the tip, I have got that working.
