### ISSUE TITLE
Correction on Diagram

### ISSUE THREAD

**Issue by scotttcawley** [MicrosoftDocs/architecture-center#2520]
The reference diagram at the top has 2 workloads. The top one in the disconnected subscription is workload 2, the private endpoint, bastion, and public ip for that workload is labelled “wkld1” instead of “wkld2”

https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-dns-infra

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d19d00-c368-c49f-0b21-50004f05f2ef
* Version Independent ID: b0dd7137-6c32-84f5-d604-b6f9bca2768b
* Content: [Design a hybrid Domain Name System solution with Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-dns-infra)
* Content Source: [docs/hybrid/hybrid-dns-infra.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/hybrid-dns-infra.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@scotttcawley 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dsk-2015** [comment]
Fixed in https://github.com/MicrosoftDocs/architecture-center-pr/pull/3302 

Closing issue.
