### ISSUE TITLE
Order of pages in left side navigation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#2522]
The pages under the Architecture heading are not displayed in any meaningful order which makes it hard to scan the page titles. It would be helpful if these were displayed alphabetically 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce3b9c5-ef05-1ff3-a6fe-052f48a9b471
* Version Independent ID: f6d3e8e8-37c5-43e6-6185-58f8511dee7e
* Content: [Hybrid Security Monitoring using Azure Security Center and Azure Sentinel - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-security-monitoring)
* Content Source: [docs/hybrid/hybrid-security-monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/hybrid-security-monitoring.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@DeanGross 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by neilpeterson** [comment]
Thanks @DeanGross, yep good feedback, I agree. Ill look into it.

**Comment by neilpeterson** [comment]
@DeanGross thanks for the feedback. We have several initiatives underway to help make AAC content more discoverable. In addition to table of contents updates (we have alphabetized per your suggestion), we have also just released a new AAC browser which include search and filtering capabilities.

https://docs.microsoft.com/en-us/azure/architecture/browse/

Closing now, feel free to re-open if you have additional feedback.
