### ISSUE TITLE
Root Management Group Doc Conflict

### ISSUE THREAD

**Issue by wilbug1git1** [MicrosoftDocs/architecture-center#2526]
The following guidance conflicts with the Enterprise Scale Landing Zone guidance [here](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization)

The recommended approach is to use these management groups:

- Root management group for enterprise-wide resources.
Use the root management group to include identities that have the requirement to apply policies across every resource. For example, regulatory requirements, such as restrictions related to data sovereignty. This group is effective in by applying policies, permissions, tags, across all subscriptions.

We shouldn’t be recommending customer to assign policies at the root management group (at least as a blanket recommendation) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847ac2f6-75b1-bd29-334d-ac3cb18a7cd8
* Version Independent ID: 6043ad51-542e-9196-0028-7b7c633fcc49
* Content: [Security management groups - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/design-management-groups)
* Content Source: [docs/framework/security/design-management-groups.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/design-management-groups.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@wilbug1git1 Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by hallihan** [comment]
This appears to have been addressed in 0f144d4 and 00e43ba, please open a new feedback request with specifics if more clarification is needed.
