### ISSUE TITLE
Cannot find a general "Azure" icon

### ISSUE THREAD

**Issue by v-karbovnichy** [MicrosoftDocs/architecture-center#2528]
It would be very handy to have a general "Azure" (the blue A symbol) icon in the download pack.
For people doing multi-cloud-provider architectures.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@v-karbovnichy Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by ashhopkins** [comment]
+1 Agreed — I've downloaded elsewhere, but would preferably have an official logo from the MS team.

**Comment by Zimmergren** [comment]
Thank you for reporting this. 
We've started an internal thread about how we can get this icon (which isn't a service icon) into the bag. 

Meanwhile, as a workaround, you can get the Azure "A" logo from any of the [existing architecture diagrams],(https://learn.microsoft.com/en-us/azure/architecture/example-scenario/mainframe/modernize-mainframe-data-to-azure), represented in SVG format.

We'll work on understanding how we can get these icons bundled. Thanks.
#please-close

**Comment by Zimmergren** [comment]
Thank you for reporting this. 
We've started an internal thread about how we can get this icon (which isn't a service icon) into the bag. 

Meanwhile, as a workaround, you can get the Azure "A" logo from any of the [existing architecture diagrams](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/mainframe/modernize-mainframe-data-to-azure), represented in SVG format.

We'll work on understanding how we can get these icons bundled. Thanks.
#please-close
