### ISSUE TITLE
Useful resource ... BUT too limited 

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/architecture-center#2529]
[Enter feedback here]

The icons are a useful resource, and sorely needed for our Azure architecture designs

BUT it would be much better if they were provided as one or more Visio stencils, rather than individual SVG files

And the shapes should have consistent formatting, label positions, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@steveculshaw  Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by JasRobe** [comment]
I believe they are available as stencils on visio web, but I'll take your request as additional input.  Thank you.
