### ISSUE TITLE
App service Plan scale limits out of date

### ISSUE THREAD

**Issue by whomanGHA** [MicrosoftDocs/architecture-center#2530]
Under Scalability - App Service shows a scale limit value of 20 instances but Premium SKUs now support up to 30 instances.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@whomanGHA Thank you for your feedback! We will review and update as appropriate.

**Comment by neilpeterson** [comment]
@whomanGHA thanks for the issue. This has been fixed and should publish today.
