### ISSUE TITLE
Consider Renaming the pattern

### ISSUE THREAD

**Issue by cloudvaughan** [MicrosoftDocs/architecture-center#2531]
Hi
The original author of the pattern has renamed the pattern. Please see the notes at the bottom of his post that you reference: https://martinfowler.com/bliki/StranglerFigApplication.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b580bcd-bba9-0799-6f9f-4b0e2ae9739f
* Version Independent ID: 6603e60e-ad3b-9aec-0633-eed88c218561
* Content: [Strangler pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/strangler)
* Content Source: [docs/patterns/strangler.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/strangler.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by AjayKumar-MSFT** [comment]
@cloudvaughan, Thanks for bringing this to our attention! We are taking a look into this and will get back to you soon.

**Comment by PramodValavala-MSFT** [comment]
@cloudvaughan Looks like this has been addressed in #2391. So, closing this in favor of that.

@neilpeterson Could you share any details for when this might be published?

**Comment by neilpeterson** [comment]
It has been published and is available now.
