### ISSUE TITLE
Missing % at the start of ProgramFiles%\FSLogix\Apps\frxdrv.sys

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/architecture-center#2532]
Please update https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#antivirus-exclusions

Exclude files:
ProgramFiles%\FSLogix\Apps\frxdrv.sys

to

Exclude files:
**%**ProgramFiles%\FSLogix\Apps\frxdrv.sys

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@DavidTaig 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MarileeTurscak-MSFT** [comment]
Thank you! I made a pull request to add that https://github.com/MicrosoftDocs/architecture-center-pr/pull/2137
