### ISSUE TITLE
Teams exclusions - .txt files ??

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/architecture-center#2533]
Please provide the https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions in the format of https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt#structure-of-redirectionsxml-file

Saying .txt files is very vague!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@DavidTaig 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by christiaanbrinkhoff** [comment]
Approved. Please remove the .txt files under the Teams exclusions section.

**Comment by doodlemania2** [comment]
Can you send us a PR on this @christiaanbrinkhoff ?

**Comment by DavidTaig** [comment]
.txt files has been removed from https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions Thanks :)

**Comment by hallihan** [comment]
This looks to have been addressed in updates to the article.
