### ISSUE TITLE
onprem.json not exist

### ISSUE THREAD

**Issue by gvnshtn** [MicrosoftDocs/architecture-center#2534]
Looks like the script is looking for onprem.json in /identity-reference-architectures rather than under /identity-reference-architectures/adds-forest

<img width="842" alt="notexist" src="https://user-images.githubusercontent.com/8502046/101711472-84559b00-3a8b-11eb-887e-7c35662124b0.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b605d93-ab34-f8f0-2c64-d38fc5b0ab51
* Version Independent ID: 6e418fbb-e9f8-fa03-ef0e-ab6940ab62ce
* Content: [Create an AD DS resource forest in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-forest)
* Content Source: [docs/reference-architectures/identity/adds-forest.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-forest.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by gvnshtn** [comment]
My bad, running from incorrect folder.

**Comment by AjayKumar-MSFT** [comment]
gvnshtn, Thanks for leveraging Azure docs feedback channel to raise this question and sharing an update, Glad that you were able to figure out the issue, Appreciate the follow-up,
