### ISSUE TITLE
wrong flow in https://azure.microsoft.com/en-us/topic/kubernetes-vs-docker/ 

### ISSUE THREAD

**Issue by Michel-as** [MicrosoftDocs/architecture-center#2535]
in https://azure.microsoft.com/en-us/topic/kubernetes-vs-docker/ Kubernetes and Docker solution architectures in production, first example. Point **7** and **8** should be switched, they are right in the documentation, but wrong in the mentioned site

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/microservices-with-aks.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by AjayKumar-MSFT** [comment]
@Michel-as, Thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by PramodValavala-MSFT** [comment]
@Michel-as Thanks for catching that! I'm believe the content for the page you've shared is separate to this repo but nonetheless, I have assigned this issue to the content author to review and update accordingly.

**Comment by EdPrice-MSFT** [comment]
@Michel-as - The documentation and diagram look correct. 

On the site that you linked to, the diagram shown seems to also be correct now, where it doesn't include the numbers:

![image](https://user-images.githubusercontent.com/13895622/134722790-703645b9-d174-459c-90f3-b753487a8c5a.png)

This appears to be fixed. If you find additional issues, please file a new GitHub Issue. Thank you!
