### ISSUE TITLE
Anti-corruption layer pattern expressed in terms of services

### ISSUE THREAD

**Issue by jochenz** [MicrosoftDocs/architecture-center#2536]
I'm surprised to see the anti-corruption layer expressed as a physical service between other services. The pattern really has nothing to do with physical deployments. When I host multiple bounded contexts in a single process, I still want anti-corruption layers between these contexts.

**Then, a lot of the mentioned downsides, like latency, do not apply.**

Feels like devs are getting wrong-footed here and immediately are put in a multi-process mindset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b204d4-aa9e-127b-5d80-6b3a80128e7f
* Version Independent ID: 54ffc524-0c3a-b349-f89a-459271f6c980
* Content: [Anti-Corruption Layer pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer)
* Content Source: [docs/patterns/anti-corruption-layer.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/anti-corruption-layer.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by AjayKumar-MSFT** [comment]
@jochenz, Thanks for the feedback! Your feedback has been shared with the content owner for further review.

**Comment by v-fearam** [comment]
#please-close
