### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by thecpshah** [MicrosoftDocs/architecture-center#2537]
I cannot find cions for Machine Learning, Databricks. 

Can you please provide a complete set of icons. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by AjayKumar-MSFT** [comment]
@thecpshah, Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by absheik** [comment]
a new version of the Icon set is now available at https://docs.microsoft.com/en-us/azure/architecture/icons/ with Download file name Azure_Public_Service_Icons_V4.zip
Databricks is 3rd party
