### ISSUE TITLE
Performance and latency attributes needed

### ISSUE THREAD

**Issue by dynamodhiraj** [MicrosoftDocs/architecture-center#2539]
[Enter feedback here]
Needs more detailed explain action on the performance and latency criteria for each of the storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4931350d-0c12-00b2-64a8-112f67aba3f2
* Version Independent ID: eed89d06-7676-30e1-b801-2f67a09856f0
* Content: [Choosing a data storage technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-storage)
* Content Source: [docs/data-guide/technology-choices/data-storage.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/data-storage.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by dynamodhiraj** [comment]
Needs more detailed explain action on the performance and latency criteria for each of the storage

**Comment by MarileeTurscak-MSFT** [comment]
@dynamodhiraj 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JasRobe** [comment]
Thank you for the feedback, The product specific documentation is the most accurate place to find that information.
