### ISSUE TITLE
Out of date reference

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#2540]
The Security Considerations section has  link that points to a page that is no longer being maintained. Can this be updated?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@DeanGross 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PageWriter-MSFT** [comment]
Thank you for pointing this out. I have updated the links. It should be live shortly.
