### ISSUE TITLE
Missing Azure Repos

### ISSUE THREAD

**Issue by ndriyo** [MicrosoftDocs/architecture-center#2542]
Where is Azure Repos in this picture?
Does it mean that we have to have different accounts other than Azure DevOps account (another Github account) if we would like to implement DevSecOps?

Will it be the direction in the future from Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcaeba82-a634-d73a-77fd-a07258be2c17
* Version Independent ID: 4ba78d8a-60c9-9df8-1d2c-0a375a094acb
* Content: [DevSecOps in Azure - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-azure)
* Content Source: [docs/solution-ideas/articles/devsecops-in-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/devsecops-in-azure.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **asegala**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @ndriyo , thanks for the question! We are taking a look into this and will get back to you soon.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @ndriyo, 
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action. Apologies for the delay.

**Comment by EdPrice-MSFT** [comment]
@ndriyo - Here are a few resources...

1. https://docs.microsoft.com/en-us/azure/architecture/browse/?terms=devsecops - This is a view of all our DevSecOps architectures.
2. For Azure Repos, we currently have two architectures: https://docs.microsoft.com/en-us/azure/architecture/browse/?expanded=azure&products=azure-repos
3. Specifically, this architecture tells the end-to-end DevOps story, including Azure Repos (but note that it's light on the Security focus): https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp
  
Thank you for your feedback! We'll add a note that it would be valuable to include Azure Repo in our DevSecOps architectures.
