### ISSUE TITLE
Support for Visio Stencils

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/architecture-center#2543]
it would be helpful to provide guidance for people who are looking for visio stencils directly on this page .  there is text about it in the FAQ however it is buried in the download...

and also provide this email contact: 

If you can’t find an icon, please email CnESymbols@microsoft.com.

also might be helpful to provide the old Visio icons until the new ones are available to replace them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @jasonhorner , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by VitalyMCT** [comment]
@HarshitaSingh-MSFT , would it be possible to get an update please? Is there a timeline for releasing this guidance?

Many of us are in the same boat - i.e. trying to use this icon set with Visio.

**Comment by absheik** [comment]
Visio online stencils are available https://techcommunity.microsoft.com/t5/visio-blog/visually-represent-your-azure-architecture-using-the-latest/ba-p/1634509.  Desktop version support is in the roadmap.
