### ISSUE TITLE
404 German IoT Architecture Pages

### ISSUE THREAD

**Issue by oliversmuc** [MicrosoftDocs/architecture-center#2544]
This German page is not reachable from it's index, due to the ".yml" ending in the URL.

https://docs.microsoft.com/de-de/azure/architecture/

![image](https://user-images.githubusercontent.com/33893603/102331989-cd29ba00-3f8b-11eb-9b76-8bef87d0dce0.png)

Best

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/de-de/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @oliversmuc , thanks for the question! We are taking a look into this and will get back to you soon.

**Comment by neilpeterson** [comment]
@oliversmuc thanks for raising this issue. We have just migrated to a new architecture browser and it looks like there is an issue here with localized content for de-de. We are looking into the issue and will report back once resolved.

**Comment by neilpeterson** [comment]
Thanks again for raising this issue @oliversmuc, we have identified an issue with our automated localization process and have escalated. I will update once fixed.

**Comment by neilpeterson** [comment]
@oliversmuc this should now be fixed. Looks good to me and I will close this issue. If you need anything else or find any other issue please let us know.

Thanks again.
