### ISSUE TITLE
This flow doesn't looks correct

### ISSUE THREAD

**Issue by msrini-MSFT** [MicrosoftDocs/architecture-center#2545]
![image](https://user-images.githubusercontent.com/47132998/102347812-f4ea4380-3fc6-11eb-83b6-f44c50a14a2a.png)

The center decision has "Do you have non-web App" and for yes, "Do you have web Apps" which doesn't make sense. correct this doc to provide more clarity. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall and Application Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway#application-gateway-before-firewall)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/gateway/firewall-application-gateway.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **pnp**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @msrini-MSFT , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by erjosito** [comment]
Where is the confusion? The diagram is trying to make the point that if the customer has a combination of web and non-web apps the setup might be different to only web-apps or only non-web apps.

**Comment by PramodValavala-MSFT** [comment]
@msrini-MSFT I hope Jose's comment clears things up

**Comment by msrini-MSFT** [comment]
@erjosito , I understand that customer can have web or non-web App, but my question is the flow diagram has a center decision box where "Do you have non-web App ?" question is asked and then if yes, there is an another decision box which asks "Do you have web App?" which I feel is a conflict.

**Comment by PramodValavala-MSFT** [comment]
@msrini-MSFT I believe the confusion is due to the lack of arrows in the diagram. Flowcharts are conventionally always meant to be read from `left -> right` and/or `top -> bottom`.

@erjosito Could you share your thoughts? Would it be possible to update the image to include arrows to make the intended flow clearer?

**Comment by erjosito** [comment]
@PramodValavala-MSFT Ah good point, yes it seems @msrini-MSFT is reading the diagram in the wrong direction (correct @msrini-MSFT ?). I will see if I can add some arrow points.

**Comment by msrini-MSFT** [comment]
@PramodValavala-MSFT , @erjosito . Even if I read it from left to right. 

1. Do you have a web-App ? - Yes
2. Do you have a non-web App ? This seems irrelevant as I already choose that I have a Web-App. 

I understand the flow but it would be nice, if it can be revisited to provide more clarity.

**Comment by erjosito** [comment]
How would you ask the questions to cover the 3 possible cases?
* Customer has only web apps
* Customer has only nonweb apps
* Customer has a combination of web and nonweb apps

**Comment by msrini-MSFT** [comment]
I would say, the second box should have the question "Do you have combination of web and non-web app".

**Comment by PramodValavala-MSFT** [comment]
@msrini-MSFT the second query does imply a combination of both if answered **yes** (since the first was already answered **yes**) as its the same flow chart and context. I suppose the query could be more elaborate like you've suggested as it really won't alter the intent here.

@erjosito Thoughts?

**Comment by erjosito** [comment]
Yes, I guess the decision chart could spell it out more clearly. I wanted to revisit this chart anyhow, I will have a look on how to make it clearer

**Comment by PramodValavala-MSFT** [comment]
@erjosito Thanks! I'm assigning this issue to you to update and close as required.

**Comment by erjosito** [comment]
@msrini-MSFT I have just merged a new version of the doc with a simplified version of the chart. Does the new version address your concerns?

**Comment by erjosito** [comment]
@PramodValavala-MSFT Can we close this? I dont think I have the required privilege to close this...

**Comment by erjosito** [comment]
#close

**Comment by PramodValavala-MSFT** [comment]
@erjosito Yes. Thanks for the update!
