### ISSUE TITLE
why mount directly to /mnt instead of /mnt/resource?

### ISSUE THREAD

**Issue by picklesrein** [MicrosoftDocs/architecture-center#2546]
What was the impetus for this change? What technical expert signed off on mounting the temp disk directly to /mnt?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af3a0e6-6629-3044-4bdc-4f73a6f77861
* Version Independent ID: a93c0dc1-678d-2319-d850-ca3dca213b74
* Content: [Run a Linux VM on Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/linux-vm)
* Content Source: [docs/reference-architectures/n-tier/linux-vm.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/linux-vm.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by hallihan** [comment]
This article currently describes only the behavior of the linux agent, I would defer any feedback on that behavior to https://github.com/Azure/azure-linux-extensions - Current versions of the agent do default to `/mnt/resource` and this can be configured with the `ResourceDisk.MountPoint` [config value](https://docs.microsoft.com/azure/virtual-machines/extensions/agent-linux#configuration). I recall some older linux images that would mount directly on `/mnt` but I haven't seen that behavior for a while. If you know of any current images that have that behavior, please comment and reopen with more details.

**Comment by picklesrein** [comment]
I'm still seeing this behavior on the latest RHEL images and the others listed below:

- RedHat.RHEL-82gen2-20220923115411
- RedHat.RHEL-7-LVM-20220923135607
- RedHat.RHEL-8-LVM-20220923145501
- procomputers.centos-7-lvm-centos-7-lvm-20220923152836

They're also ignoring my cloud-init code so I'm doing something wrong there. But after creating fresh images I can confirm that the ephemeral resource disk is mounted directly to /mnt and not /mnt/resource

**Comment by picklesrein** [comment]
Yes, I'm familiar with how to contact the vendor. It seemed like you believed this issue was resolved and no longer present in the latest images and you asked for details. :shrug:

**Comment by hallihan** [comment]
The comment thread in this issue sheds some light on the different behaviors: https://github.com/Azure/WALinuxAgent/issues/1971

Appreciate the pointers to the specific images. It appears that it's still correct for the documentation to say "mounted at /mnt/resource or /mnt" since the mount point may be determined by cloud-init, or by waagent, depending on the image.

**Comment by Klaas-** [comment]
> For the Red Hat images, you could try contacting Red Hat, there's a link in the Help section of the VM view in the Azure Portal to connect to the Red Hat Customer Portal: <img alt="image" width="1213" src="https://user-images.githubusercontent.com/1796255/192285257-a62dd9ba-0597-42c8-822d-1920c0e0c009.png">

The Red Hat Azure images are built and maintained by Microsoft, not Red Hat

**Comment by Klaas-** [comment]
> The comment thread in this issue sheds some light on the different behaviors: ...
> 
> Appreciate the pointers to the specific images. It appears that it's still correct for the documentation to say "mounted at /mnt/resource or /mnt" since the mount point may be determined by cloud-init, or by waagent, depending on the image.

Yeah, that discussion has been ongoing since MS switched the defaults from /mnt/resource to /mnt, but the decision is final I was told :)
