### ISSUE TITLE
Predictive maintenance - implementation details for new services

### ISSUE THREAD

**Issue by DJPaulo** [MicrosoftDocs/architecture-center#2548]
Please could you update the design in the architecture documentation [here](https://docs.microsoft.com/en-gb/azure/architecture/solution-ideas/articles/predictive-maintenance) to include new services like Time Series Insights, Anomaly Detector, and Metrics Advisor?
It would be very useful to see exactly where these would fit into a predictive maintenance scenario.
Thanks

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by jocontr** [comment]
Thank you @DJPaulo, I have captured this as an architecture request for my team.
