### ISSUE TITLE
Teams exclusions - Format for redirections.xml

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/architecture-center#2549]
Please provide the https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions in the format of https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt#structure-of-redirectionsxml-file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by DavidTaig** [comment]
From:

Media-stack folder
meeting-addin\Cache (%appdata%\Microsoft\Teams\meeting-addin\Cache)

to:
Media-stack folder - <Exclude Copy="0">AppData\Roaming\Microsoft\Teams\media-stack\</Exclude>
meeting-addin\Cache folder - <Exclude Copy="0">AppData\Roaming\Microsoft\Teams\meeting-addin\Cache\</Exclude>

Many examples leave out the slash after the last folder name, however not clear this is correct as the example for Structure of redirections.xml file shows with (/Exclude) and without (/Include) - https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt#structure-of-redirectionsxml-file - What is correct?

**Comment by DavidTaig** [comment]
![2549](https://user-images.githubusercontent.com/38142528/102626185-983f8200-419a-11eb-986d-4f2d6be2cc48.PNG)

When submitting the above, it strip off most content, see picture, which is correct

**Comment by femsulu** [comment]
Thanks for the Comment. We are actively investigating and will get back to you soon.

**Comment by BryanLa** [comment]
@DavidTaig - our apologies for the long delay in responding to this, and thanks for your contribution.

The article has been revised and will republish tomorrow morning, Pacific time.

#please-close
