### ISSUE TITLE
Teams exclusions - Foward slash and backslash in section

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/architecture-center#2550]
In the section https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions using Foward slash and backslash

%appdata%/Microsoft/Teams
%appdata%\Microsoft\Teams\meeting-addin\Cache

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by femsulu** [comment]
Thanks for the Comment. We are actively investigating and will get back to you soon.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
As the requested changes were updated in the document, we will now proceed to close this issue out. Thank you!

**Comment by DavidTaig** [comment]
I still see foward slash and backslash

![image](https://user-images.githubusercontent.com/38142528/106550977-5612aa00-6568-11eb-90d0-14be7a616336.png)
