### ISSUE TITLE
Add addition Teams exclusions ?

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/architecture-center#2551]
Should these exclusions be added to the Teams section
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#teams-exclusions

<Exclude Copy="0">AppData\Roaming\Microsoft\Teams\Service Worker\</Exclude>
from: https://techcommunity.microsoft.com/t5/fslogix-blog/teams-setup-rapidly-grows-my-profile-disk/ba-p/1539064

<Exclude Copy="0">AppData\Roaming\Microsoft\Teams\Cache</Exclude>
<Exclude Copy="0">AppData\Roaming\Microsoft\Teams\Logs</Exclude>
from: https://techcommunity.microsoft.com/t5/windows-virtual-desktop/wvd-fslogix-reduce-profile-container-size-exclude-teams-cache/m-p/1503683
https://wvdlogix.net/complete-guide-teams-on-wvd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by DavidTaig** [comment]
![2551](https://user-images.githubusercontent.com/38142528/102633071-09cffe00-41a4-11eb-8603-d331a8d6fced.PNG)

When submitting the above, it strip off most content, see picture, which is correct

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by v-fearam** [comment]
Hi @DavidTaig 


Sorry for the delay. 


The document has changed since the ticket was open, including the exclusion sections. 

Please, check again and open a new ticket if you still have some concerns about it.

**Comment by v-fearam** [comment]
#please-close
