### ISSUE TITLE
Typo "Azure function apps"→"Azure Function Apps"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/architecture-center#2554]
Typo "Azure function apps"→"Azure Function Apps"

https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-functions-hybrid
![azure-functions-hybrid](https://user-images.githubusercontent.com/40815708/102689590-99c48500-4242-11eb-8746-df015bca45dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229cb7ce-81f0-4005-356e-66c73e6d257f
* Version Independent ID: 00100699-8feb-bba3-f6d3-001c6ea2a62f
* Content: [Azure Functions in a hybrid environment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-functions-hybrid)
* Content Source: [docs/hybrid/azure-functions-hybrid.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/azure-functions-hybrid.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @hyoshioka0128 , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by HarshitaSingh-MSFT** [comment]
@hyoshioka0128 , assigning this to author to work on these changes.

**Comment by absheik** [comment]
will be fixed when this pr is merged.
https://github.com/MicrosoftDocs/architecture-center-pr/pull/2239
