### ISSUE TITLE
AKS + ACI Solution

### ISSUE THREAD

**Issue by raisaurabh777** [MicrosoftDocs/architecture-center#2558]
Please expand this article with code, templates, and more explanation. It looks like this solution can be a possible candidate for many AKS deployments in various environments.

**Comment by raisaurabh777** [comment]
Created a duplicate by mistake.

**Comment by AjayKumar-MSFT** [comment]
raisaurabh777, No worries. Thanks for leveraging Azure docs feedback channel. Appreciate the update on this.
