### ISSUE TITLE
AKS + ACI Solution

### ISSUE THREAD

**Issue by raisaurabh777** [MicrosoftDocs/architecture-center#2559]
Please provide more explanation, code samples, templates of this solution. AKS + ACI looks promising. May be suitable for various use cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f8f943-7688-65e6-26c9-5d682a225306
* Version Independent ID: 18d298ba-be2b-bc4a-abac-5ea5a94fadca
* Content: [Bursting from AKS with ACI - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scale-using-aks-with-aci)
* Content Source: [docs/solution-ideas/articles/scale-using-aks-with-aci.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scale-using-aks-with-aci.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by AshokPeddakotla-MSFT** [comment]
@raisaurabh777 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by ckittel** [comment]
The Azure Architecture Center does not plan on adding additional AKS -> ACI burst content.  Please use the virtual nodes product documentation to help in bursting to ACI: <https://learn.microsoft.com/azure/aks/virtual-nodes> and the Virtaul Kubelet documentation: <https://github.com/virtual-kubelet/azure-aci/blob/master/README.md>.

#please-close
