### ISSUE TITLE
The Architecture Diagram representation

### ISSUE THREAD

**Issue by PRASADA1207** [MicrosoftDocs/architecture-center#2560]
[Enter feedback here]
The Architecture diagram can be represented  in much better way  I feel.
If I want to contribute in better architecture diagram representation how can I achieve that please advise .

Thanks and regards,
Avijit Prasad
Assc Consultant 
MS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca9b2be-df1b-e3e8-4380-88a622f33706
* Version Independent ID: 49df4ff5-fc53-427c-7fd0-6b5caf917837
* Content: [COVID-19 Safe Solutions with IoT Edge - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cctv-mask-detection)
* Content Source: [docs/solution-ideas/articles/cctv-mask-detection.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/cctv-mask-detection.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@PRASADA1207 Thank you for your feedback! We have assigned this issue to the content author to review further and take the next course of action. For your reference, the contribution guide is located at the following URL: https://review.docs.microsoft.com/en-us/help/contribute/?branch=master

**Comment by absheik** [comment]
taking offline
