### ISSUE TITLE
Text update

### ISSUE THREAD

**Issue by malindasuhash** [MicrosoftDocs/architecture-center#2561]
This statement "Stateless apps that are configured for autoscaling are more cost effective **that** stateful apps", shouldn't that replaced with "_than_"?

**Comment by AjayKumar-MSFT** [comment]
@malindasuhash, Thanks for leveraging Azure docs feedback channel to raise this question. Could you please share the Azure documentation for which this feedback is applicable to?

**Comment by neilpeterson** [comment]
Thanks for catching this @malindasuhash. I've submitted the updated which should publish tomorrow morning PST.
