### ISSUE TITLE
Change title to Reference Architecture or Create a new article for it!

### ISSUE THREAD

**Issue by ravisha22** [MicrosoftDocs/architecture-center#2562]
A number of my customers are looking for reference architecture and this article is the closest to it (https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop ) Can the title of this article be changed to reference arch. or have a new article written for it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Windows Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by KranthiPakala-MSFT** [comment]
@ravisha22  Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by absheik** [comment]
@ravisha22, please review https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/
This is the current published detailed WVD content that is close to a Reference Architecture.  Our team is working on an RA that includes deployment scripts and configurations for different scale and enterprise needs.   

The article you point to does not have all the pieces in place to be elevated to an RA.
