### ISSUE TITLE
Diagram image and Visio diagram do not match

### ISSUE THREAD

**Issue by pauldotyu** [MicrosoftDocs/architecture-center#2578]
In the WVD architecture center doc, the architecture diagram image does not match with what is downloaded when you click the "Download a copy of this Visio." link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Windows Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by neilpeterson** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/355657/>355657</a>

**Comment by absheik** [comment]
@pauldotyu, thanks for reporting the issue.  The updated Visio file matching the image in the article will be available once the CDN propagation is complete.
