### ISSUE TITLE
Claims identity schema

### ISSUE THREAD

**Issue by ashinzekene** [MicrosoftDocs/architecture-center#2581]
There is this list of identity schema on this page

  > oid > http://schemas.microsoft.com/identity/claims/objectidentifier
  tid > http://schemas.microsoft.com/identity/claims/tenantid
  unique_name > http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
  upn > http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn

Is it fine to replace with https as this causes codeql warnings?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d00031-82e8-a8ee-0a66-e9b84231e837
* Version Independent ID: 9a9da08f-83e2-c493-61af-c4b5316c6f8e
* Content: [Work with claim-based identities in multitenant applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/claims)
* Content Source: [docs/multitenant-identity/claims.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/claims.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/355890/>355890</a>

**Comment by ckittel** [comment]
No, sorry, these are schema identifiers and are not URLs.  They looks like URLs, but they are technically URIs and schemas do not need to resolve to a network location.  They are defined by the schema owner.  You can find the common schema ids at <https://learn.microsoft.com/azure/active-directory/develop/reference-saml-tokens>.  Please set your tooling to make an exception on these.
