### ISSUE TITLE
Remove Docker Desktop with WSL :)

### ISSUE THREAD

**Issue by jfmatth** [MicrosoftDocs/architecture-center#2582]
[Enter feedback here]
I have pulled Docker Desktop out of my workflow when using Windows / WSL, and instead use PODMAN from RedHat.

DD is so heavy on a windows machine, and if I'm already running WSL, I don't need all the parts for Docker, just PODMAN

There is one specific flag you need to use in your PodMan builds ``` podman build -t docker...``` to make sure it's the same as a docker build.  Otherwise, everything with Podman works better in WSL

HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a22c561-4aea-9d96-4578-726cf94dc178
* Version Independent ID: 750fa114-2a1c-c4ea-1930-b2f9fd930583
* Content: [Release Engineering Application Development - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/release-engineering-app-dev)
* Content Source: [docs/framework/devops/release-engineering-app-dev.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/release-engineering-app-dev.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @neilpeterson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/355945/>355945</a>

**Comment by neilpeterson** [comment]
@jfmatth thanks for this issue / tip. I will plat around with podman and see how we can work it in. It may take me a few days to carve out the time, but I will get to it and respond back here once done.

**Comment by jfmatth** [comment]
Neil, Thank you.  I moved from MultiPass to WSL 2 because I though Docker would be native, but in fact, it’s a huge install and everything wants to install Docker for Desktop.  With PodMan, one install, no daemons and viola, a working container platform for WSL 2.  Don’t forget the -f docker flag, that took up 4hrs of my life . J  Sent from Mail for Windows 10 From: Neil PetersonSent: Tuesday, January 5, 2021 8:29 PMTo: MicrosoftDocs/architecture-centerCc: John Flynn Matthew; MentionSubject: Re: [MicrosoftDocs/architecture-center] Remove Docker Desktop with WSL :) (#2582) @jfmatth thanks for this issue / tip. I will plat around with podman and see how we can work it in. It may take me a few days to carve out the time, but I will get to it and respond back here once done.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by neilpeterson** [comment]
@jfmatth I've added a other tools section to this docs with Podman in the list. This should publish soon, thanks for the suggestion.

**Comment by jfmatth** [comment]
@neilpeterson Thanks so much.  I feel great, I've contributed to something from MS, nice!
