### ISSUE TITLE
Link is to a blog post that is really out of date.

### ISSUE THREAD

**Issue by dgpoulet** [MicrosoftDocs/architecture-center#2584]
In the article is a link to this old blog post, referred to here:

"For a deeper understanding of the limits of the CRUD approach, see CRUD, Only When You Can Afford It."

The post is 17 years old and, frankly, not that well written: all text, rambling, full of half-explained examples without context - a sort of stream-of-consciousness brain dump. It would make sense informally as part of a conversation on reddit or something, but not as a clear discussion of a particular pattern / anti-pattern.

I think it might be better to include a link to a more professional-looking discussion such as Martin Fowler's: martinfowler.com/eaaDev/EventSourcing.html

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Cloud Design Patterns](https://docs.microsoft.com/en-gb/azure/architecture/patterns/event-sourcing)
* Content Source: [docs/patterns/event-sourcing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/event-sourcing.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/356481/>356481</a>

**Comment by dgpoulet** [comment]
I'm not sure where might be a good source for a CRUD take-down, but there are more links to potential deeper discussions by Fowler [here](https://martinfowler.com/articles/201701-event-driven.html).

**Comment by Zimmergren** [comment]
#please-close

The original issue no longer exists, and the content has already been updated. Thanks.
