### ISSUE TITLE
Additional missing icons

### ISSUE THREAD

**Issue by SvenAelterman** [MicrosoftDocs/architecture-center#2585]
The following services' icons are missing

- Integration Service Accounts
- WVD-related services:
    - Host pool
    - Application group
    - Workspace
- Access control (IAM)
- Private endpoint
- Subnet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/356546/>356546</a>

**Comment by absheik** [comment]
a new version of the Icon set is now available at https://docs.microsoft.com/en-us/azure/architecture/icons/ with Download file name Azure_Public_Service_Icons_V4.zip
