### ISSUE TITLE
Keep extending it

### ISSUE THREAD

**Issue by pedro-bonilla** [MicrosoftDocs/architecture-center#2587]
Please keep extending _Gaming using Azure Database for MySQL_ by adding implementation details, pricing guidance, and some code examples. Would there any change significant architecture change by changing the relational database engine? Eg: PostgreSQL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a99221-6683-e2ad-336e-2795ce944873
* Version Independent ID: 72c91293-38dd-24b1-7c72-8be7e8847f5d
* Content: [Gaming using Azure Database for MySQL - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/gaming-using-azure-database-for-mysql)
* Content Source: [docs/solution-ideas/articles/gaming-using-azure-database-for-mysql.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/gaming-using-azure-database-for-mysql.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/358068/>358068</a>

**Comment by skabou** [comment]
Closing out this issue as the article has been removed.

**Comment by skabou** [comment]
#please-close
