### ISSUE TITLE
Typo in Event Sourcing pattern doc

### ISSUE THREAD

**Issue by mtan429** [MicrosoftDocs/architecture-center#2588]
"if multiple instances of a consumer maintain **an** aggregate an entity's property"

should be

"if multiple instances of a consumer maintain **and** aggregate an entity's property"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing#feedback)
* Content Source: [docs/patterns/event-sourcing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/event-sourcing.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/358249/>358249</a>

**Comment by neilpeterson** [comment]
@mtan429 thanks for opening this issue. This should be fixed by end of day.
