### ISSUE TITLE
Sample diagram includes icons not in library

### ISSUE THREAD

**Issue by lowndesc** [MicrosoftDocs/architecture-center#2589]
Although your sample diagram includes icons for (eg.) Azure Databricks and Power BI, neither of these are included in the current icon library. More frequent updates and more comprehensive coverage could still be an improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/358289/>358289</a>

**Comment by absheik** [comment]
A new version Azure_Public_Service_Icons_V4.zip is available for downlead.  Databricks is 3rd party, it is now available under Analytics folder.  PowerBi is still missing, we are working on updating.  We plan on regularly updating these downloads.
