### ISSUE TITLE
Correct references to NetApp Files.

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#2590]
Please change all references to NetApp Files to "Azure NetApp Files", following the service official nomenclature:
https://azure.microsoft.com/en-us/services/netapp/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbf62e6-49ab-a499-f82e-e0ade93ce2e2
* Version Independent ID: 08bbadc2-c2f9-1c43-b541-e5e2554931fc
* Content: [Multiple forests with AD DS and Azure AD - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/multi-forest?source=docs)
* Content Source: [docs/example-scenario/wvd/multi-forest.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/multi-forest.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @nehalineogi
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/358466/>358466</a>

**Comment by dsk-2015** [comment]
Fixed in https://github.com/MicrosoftDocs/architecture-center-pr/pull/3299. Closing this issue.
