### ISSUE TITLE
Add Azure NetApp Files to diagram

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#2591]
Since Azure NetApp Files is a valid solution for this architecture, suggesting the following two changes:

Change

- Azure Files Premium or an equivalent network-attached storage (NAS) system stores media files like product images. Magento needs a Kubernetes-compatible file system that can mount a volume in ReadWriteMany mode, like Azure Files Premium or Azure NetApp Files.

to:

- [Azure Files Premium](https://azure.microsoft.com/services/storage/files/), [Azure NetApp Files](https://azure.microsoft.com/services/netapp/) or an equivalent network-attached storage (NAS) system stores media files like product images. Magento needs a Kubernetes-compatible file system that can mount a volume in ReadWriteMany mode, like Azure Files Premium or Azure NetApp Files.

Further, please incorporate Azure NetApp Files into the diagram as a similar valid option as Azure Files Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2edf62c9-d5c7-b4d0-99e7-f271ef0b629e
* Version Independent ID: d9ff7f72-3fbb-3bc6-e787-60b1ccecb698
* Content: [Magento e-commerce platform in Azure Kubernetes Service (AKS) - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/magento/magento-azure)
* Content Source: [docs/example-scenario/magento/magento-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/magento/magento-azure.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/358467/>358467</a>

**Comment by TimShererWithAquent** [comment]
Changes made, including visio version and thumbnail.
