### ISSUE TITLE
Azure symbols are useless

### ISSUE THREAD

**Issue by mosharafMS** [MicrosoftDocs/architecture-center#2592]
The new symbols are useless for two reasons 
1) SVG format is not opened by Visio (desktop & online) nor Microsoft whiteboard app. 
2) The new version is very tiny that are even after converting them to png are useless to use 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/359244/>359244</a>

**Comment by absheik** [comment]
@mosharafMS you can import SVG in to Visio by following these steps https://support.microsoft.com/en-us/office/import-or-insert-graphics-into-visio-drawings-f05e556d-a158-4e16-9bd8-5d45071c9b8c

We are working on making Visio templates available
 
You can batch convert SVG to PNG using Inkscape https://gallery.technet.microsoft.com/scriptcenter/Convert-SVG-to-PNG-e759387c
