### ISSUE TITLE
AWS CloudTrail equivalent service on Azure is not Azure Monitor, it should be Azure Activity log.

### ISSUE THREAD

**Issue by mbedford78** [MicrosoftDocs/architecture-center#2593]
AWS CloudTrail equivalent service on Azure is not Azure Monitor, it should be Azure Activity log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/359317/>359317</a>

**Comment by dsk-2015** [comment]
@mbedford78 thanks for providing the suggestion. Azure Activity log is a feature or service provided under the brand Azure Monitor. So, the documentation is correct in mentioning the umbrella term as equivalent to AWS CloudTrail. 

See here for more information: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log

Closing this issue with no change to documentation.
