### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by BenCoding** [MicrosoftDocs/architecture-center#2594]
I noticed that the comparison chart doesn't have SNS on it.  Seems like an odd omission
I think the older version of this doc did have SNS.  It's similar to Azure Notification Hubs:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/360008/>360008</a>

**Comment by dsk-2015** [comment]
SNS is present in the comparison chart under the "Messaging and eventing" header. Restructuring of the doc might have made this less obvious than before. Closing this issue without changing the content.
