### ISSUE TITLE
Business Logic for entire domain

### ISSUE THREAD

**Issue by rajshailesh** [MicrosoftDocs/architecture-center#2595]
[In the article you mentioned that API gateway shouldn't implement business logic. Each microservice is independent but there may scenario where one service need to call other service to fulfill the functionality or there may be service which will just call other services to fulfil the functionality in that case what is best practice to do so. If one service is calling other service then involving services can be tightly coupled?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7e7bd-23f3-a39f-9015-b77f14bb43e5
* Version Independent ID: 0ac34e7e-315f-2452-bf0a-74e9b1068c38
* Content: [Microservices architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices)
* Content Source: [docs/guide/architecture-styles/microservices.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/microservices.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/360207/>360207</a>

**Comment by hallihan** [comment]
I think this documentation addresses your question: https://docs.microsoft.com/azure/architecture/microservices/model/microservice-boundaries
