### ISSUE TITLE
This script requires a preview feature "Microsoft.Network/AllowMultipleAddressPrefixesOnSubnet"

### ISSUE THREAD

**Issue by smithers54** [MicrosoftDocs/architecture-center#2596]
It's because of this section of the script that realistically isn't needed as we shouldn't be trying to add the vnet address space as a prefix to the existing subnets:

#Add $IPAddressRange to subnet
$subnet = $HUBvnet.subnets[0]
$subnet.addressprefix.add($IPAddressRange)
#end

Please update the script to remove this section.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/360914/>360914</a>

**Comment by smithers54** [comment]
Also, subnets can be added while a peering is in place so this section is for sure not needed.

**Comment by ckittel** [comment]
Good point about the modification of the zeroth subnet in this script. I've made a change to this script to no longer modify any subnets as part of it, just simply add the added space.  Thanks for the report on this.

The change will go live in about 24 hours.
