### ISSUE TITLE
No scenarios explaining when to use Azure Databricks

### ISSUE THREAD

**Issue by hugobarona** [MicrosoftDocs/architecture-center#2597]
Azure Databricks is one of the options included to use NLP service. And the section below (Key selection criteria) mentions various scenarios about when picking Azure HDInsight with Spark or Cognitive Service, but does not explain when to use Azure Databricks.

I believe it would be beneficial to include a few scenarios explaining the criteria to use when selecting Azure Databricks as opposed to other options available.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/361013/>361013</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT Please close this PR. Content in OneNote

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
