### ISSUE TITLE
VOD architecture feedback

### ISSUE THREAD

**Issue by jigar288** [MicrosoftDocs/architecture-center#2598]
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video

The documentation below indicates the following:

`If you'd like to see us expand this article with more information, implementation details, pricing guidance, or code examples, let us know with GitHub Feedback!` 

It would be really helpful if more info was provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video)
* Content Source: [docs/solution-ideas/articles/digital-media-video.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-video.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/361437/>361437</a>

**Comment by EdPrice-MSFT** [comment]
Thank you for the feedback. We're noting this for future updates.
