### ISSUE TITLE
icon issues

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/architecture-center#2599]
All I emailed the the CNE team but never heard anything back maybe this will get a quicker response:

1) the icon for stretch db seems to be the old sql dw this is incorrect
Also note that the redis cached is likely mis-named (see attached)

2) there isn't currently an icon for Azure Synapse pipelines using the Azure Data Factory icon is confusing and misleading so we desperately need a synapse pipelines icon

3) there isn't an icon for the newly released Azure Purview service
4) there doesn't seem to be an ADLS gen2 storage icon this would be helpful
5) there is no azure databricks icon despite it being shown in the diagram

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/361921/>361921</a>

**Comment by absheik** [comment]
@jasonhorner, thank you for opening the issue.   A new version of the download file Azure_Public_Service_Icons_V4.zip is available.  Now Databricks is available, others in you request are being triaged.  Closing this issue, please feel free to open new for further questions.
