### ISSUE TITLE
Equivalent to AWS Service Catalog

### ISSUE THREAD

**Issue by imcdnzl** [MicrosoftDocs/architecture-center#2600]
AWS Service Catalog isn't listed in this page and I think it should be.

My feeling is that it would be in the marketplace section and that the equivalent would be Azure Managed Applications

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/362013/>362013</a>

**Comment by hallihan** [comment]
This was added with previous updates.
