### ISSUE TITLE
Cosmos DB Retry Guidance refers to old SDK Version

### ISSUE THREAD

**Issue by afscrome** [MicrosoftDocs/architecture-center#2601]
The CosmosDb section seems to be based on the V2 SDK, which has long since been superseded by the V3 SDK.   Can this be updated to account for the V3 sdk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#cosmos-db)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/362094/>362094</a>

**Comment by magrande** [comment]
This section has been updated in this PR:

https://github.com/MicrosoftDocs/architecture-center-pr/pull/2301#pullrequestreview-574377267

The issue can be closed.
