### ISSUE TITLE
Suggestion to add Azure Queue Storage as a technology choice option for a message broker

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftDocs/architecture-center#2602]
Suggestion to add Azure Queue Storage as a technology choice option for a message broker:
https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/messaging#technology-choices-for-a-message-broker

And to also add a link to this page
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4503ec57-36ef-8040-b6de-5b5a1fea1590
* Version Independent ID: 509de364-6faf-e11e-41e0-c2f6cb8583f6
* Content: [Asynchronous messaging options in Azure - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/messaging)
* Content Source: [docs/guide/technology-choices/messaging.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/messaging.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/362102/>362102</a>

**Comment by RobBagby** [comment]
Thanks for the suggestion. While Azure queue storage is an async option, the section in question is listing message brokers. I am closing this request. If you think I did this in error, please open a request.
