### ISSUE TITLE
SVG Version of architecture diagram

### ISSUE THREAD

**Issue by allanopen** [MicrosoftDocs/architecture-center#2603]
Please can we have SVG versions of architecture diagrams so that we can use that as a starting point to build out new components for customer architectures (editable in Visio). Today as  a PNG, there is a lot of extra work to recreate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6beac55-590d-a02d-3424-e766976acd44
* Version Independent ID: 40e5543f-8139-584f-5936-f0d77797ee9f
* Content: [Azure Data Explorer monitoring - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/monitor-azure-data-explorer)
* Content Source: [docs/solution-ideas/articles/monitor-azure-data-explorer.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/monitor-azure-data-explorer.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @orspod
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/362405/>362405</a>

**Comment by shashishailaj** [comment]
@allanopen Thank you for your suggestion. As suggested by @absheik currently this is under review internally . We will update the status on this thread.

**Comment by shashishailaj** [comment]
@allanopen We are working on an internal work item on this . Hence this issue is being closed and we will track this internally . 

Thank you.
