### ISSUE TITLE
Downloaded SVG is not scalable

### ISSUE THREAD

**Issue by cmargraff** [MicrosoftDocs/architecture-center#2605]
Download as SVG is a PNG embedded in an SVG file. It would be amazingly helpful if the included graphics were segregated into discrete vector images. 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced Analytics Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/advanced-analytics-on-big-data.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363239/>363239</a>

**Comment by cmargraff** [comment]
You can close bug #2605 as duplicate

**Comment by absheik** [comment]
these Icons are scalable SVG.  I am able to scale using Inkscape.
