### ISSUE TITLE
Modern Data Warehouse Architecture

### ISSUE THREAD

**Issue by Ttaboada** [MicrosoftDocs/architecture-center#2606]

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363279/>363279</a>

**Comment by david-stanford** [comment]
Hello, there doesn't seem to be any content for this issue.  If there is something we can help with please let us know.
