### ISSUE TITLE
PNG version of Icons

### ISSUE THREAD

**Issue by douglas-isaksson** [MicrosoftDocs/architecture-center#2607]
HI there,

While I do appreciate the fact that these icons are available it would be GREAT if you could supply them as PNG as well as SVG. Seeing as there are a lot of Devs and Architects on Mac and the SVG support there is so-so it's a bit of a pain every 6 months when you go back and need a new set of icons. The previews looks like shit in Finder and you always end up needing to figure out whatever script and tool you need to loop through the folders and convert each file to png. Then you need remember to escape the paths cause you included + signs in the paths and what not if you use "find". 
On top that something like Google Drawing doesn't support svg, which isn't your fault but still. 

This seems to be the smoothest on Mac
`brew install librsvg`

cd to Icons in the downloaded svg folder

`for i in */*.svg ; do rsvg-convert -h 512 "$i"> "$i".png ; done `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363588/>363588</a>

**Comment by absheik** [comment]
@douglas-isaksson thanks for the request, delivering these Icons in PNG is in the near roadmap.  Unfortunately not able to provide timeline. IN the mean time, you can use Inkscape to batch convert SVG to PNG.  https://gallery.technet.microsoft.com/scriptcenter/Convert-SVG-to-PNG-e759387c
