### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by terjevatle** [MicrosoftDocs/architecture-center#2608]
Hi! 
Great that you make the icons available. However, I miss a few icons under Analytics such as Azure Data Factory and Azure Data Lake Storage gen 2. Will this be added to the zip?

Complete list of services: 
https://azure.microsoft.com/en-us/services/#analytics 

Thanks and Best Regards
Terje Vatle
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363997/>363997</a>

**Comment by absheik** [comment]
Data Factory is now available, Data Lake Storage Gen 2 is not.  Will let the design team know
