### ISSUE TITLE
Request for Blockchain Workflow Application details

### ISSUE THREAD

**Issue by jabbermo** [MicrosoftDocs/architecture-center#2609]
Hi team,

can you please share more information such as  implementation details, pricing guidance, or code example for the below blockchain architecture.
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/blockchain-workflow-application

Thank you in advance.

Thanks and regards,
Jabbar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041da9ff-57a4-916d-ae12-8b1e4fe77d44
* Version Independent ID: a56ac57e-3796-559f-261f-76061e0e4810
* Content: [Blockchain Workflow Application - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/blockchain-workflow-application)
* Content Source: [docs/solution-ideas/articles/blockchain-workflow-application.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/blockchain-workflow-application.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/365414/>365414</a>

**Comment by jabbermo** [comment]
Thank you for the quick response, I would be grateful if you can share me step by step instructions as to how to implement this.

thanks and regards,
Jabbar

**Comment by jabbermo** [comment]
Hi Team,

Just wanted to follow up on this. I understand that requests like these take time, however I am participating in one hackathon within my firm and details about this blockchain implementation in Supply chain on Azure would be of great help to me. 

Thank you for your help!

**Comment by alexhart11** [comment]
@EdPrice-MSFT
Please close this PR; content in OneNote

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
