### ISSUE TITLE
Getting Buy In from Management for DDD

### ISSUE THREAD

**Issue by ChicagoDave** [MicrosoftDocs/architecture-center#2610]
I'm in my second DDD push and it's still extremely challenging to get alignment from the business to work from a DDD perspective. They see "features" and "existing systems". We need more discussion on getting management to understand and embrace DDD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3d720e-441b-16f6-a73d-d7a66f81fa32
* Version Independent ID: 8a923182-0020-db36-e896-0cf71d277c67
* Content: [Monoliths to microservices using domain-driven design - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/migrate-monolith)
* Content Source: [docs/microservices/migrate-monolith.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/migrate-monolith.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @lavann
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/365681/>365681</a>

**Comment by SatishBoddu-MSFT** [comment]
Hello @ChicagoDave, this issue is assigned to @absheik for providing further updates.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24411 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
