### ISSUE TITLE
Out of date reference to SQL DB for R programmer

### ISSUE THREAD

**Issue by predictiverye** [MicrosoftDocs/architecture-center#2612]
R is no longer supported in Azure SQL DB. R is now supported in Azure SQL MI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2808e74b-c325-7b50-093a-b777473864b5
* Version Independent ID: e1f632cb-92ef-958e-5bf4-d250108e1c8d
* Content: [R developer's guide to Azure - R programming - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/r-developers-guide)
* Content Source: [docs/data-guide/technology-choices/r-developers-guide.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/r-developers-guide.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @AnalyticJeremy
* Microsoft Alias: **jepeach**

**Comment by skabou** [comment]
It appears this was addressed some time ago.  If help is still needed, please feel free to re-open with additional details.
