### ISSUE TITLE
Diagram update

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/architecture-center#2613]
The diagram on this page is a few years old and is getting a little dated. Areas to update would include:

1. Replace SQL DW with Synapse Analytics
2. Update Power BI Icon
3. Update CosmosDB icon

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4f4c7c-f268-b75b-2486-5c4418e5b24e
* Version Independent ID: 5d28faa1-20bc-1727-05ab-0b18eba1ba7c
* Content: [Data warehousing and analytics - Azure Architecture Center](https://docs.microsoft.com/en-ca/azure/architecture/example-scenario/data/data-warehouse)
* Content Source: [docs/example-scenario/data/data-warehouse.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/data/data-warehouse.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/366099/>366099</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR. Content in OneNote

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
