### ISSUE TITLE
asking permision if i can use logo 

### ISSUE THREAD

**Issue by kartikbhatt1500** [MicrosoftDocs/architecture-center#2614]
sir i want to ask if i can use your logo in a thumbnail of video i made . that video one of its part shows offer provided by partner sites with github. so can i use your logo in youtube thumbnail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/366870/>366870</a>

**Comment by PramodValavala-MSFT** [comment]
@kartikbhatt1500 To quote the docs

> Microsoft permits the use of these icons in architectural diagrams, training materials, or documentation. You may copy, distribute, and display the icons only for the permitted use unless granted explicit permission by Microsoft. Microsoft reserves all other rights.

@doodlemania2 @absheik Could you share more details on others permissions required, if any?

**Comment by absheik** [comment]
This is the terms of use that is included as a pdf in the download zip file

Azure architecture icons
Helping our customers design and architect new solutions is core to the Azure Architecture Center’s
mission. Architecture diagrams like those included in our guidance can help communicate design
decisions and the relationships between components of a given workload. On this page you will find an
official collection of Azure architecture icons including Azure product icons to help you build a custom
architecture diagram for your next solution.
Do’s
• Use the icons to illustrate how products can work together
• In diagrams, we recommend to include the product name somewhere close to the icon
• Use the icons as they would appear within Azure
Don’ts
• Don’t crop, flip or rotate icons
• Don’t distort or change icon shape in any way
• Don’t use Microsoft product icons to represent your product or service
Terms
Microsoft permits the use of these icons in architectural diagrams, training materials, or documentation.
You may copy, distribute, and display the icons only for the permitted use unless granted explicit
permission by Microsoft. Microsoft reserves all other rights.
