### ISSUE TITLE
Grammatical error in statement

### ISSUE THREAD

**Issue by sachinb4u** [MicrosoftDocs/architecture-center#2620]
[Enter feedback here]
Grammatical error

> Also, the data in an RDBMS must **_be_** normalized, which isn't appropriate for every data set.

 
**_be_** is missing in above statement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40cb85c-ee53-7b49-0622-bed8ebedea81
* Version Independent ID: 896e0838-dfd1-c442-414d-ad9ea6dc8f7d
* Content: [Understand data store models - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/367810/>367810</a>

**Comment by SatishBoddu-MSFT** [comment]
@sachinb4u 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by dsk-2015** [comment]
This has been fixed. Closing this issue.
