### ISSUE TITLE
Wrong Azure Powershell command RM instead of Az

### ISSUE THREAD

**Issue by romulobrandino** [MicrosoftDocs/architecture-center#2622]
Hello Microsoft team,

Please update the command on this page, the command Get-AzureRmExpressRouteServiceProvider is not in use anymore, it is a legacy Azure RM, the correct should be Get-AzExpressRouteServiceProvider from Azure Az PowerShell module.

References: 
https://docs.microsoft.com/en-us/powershell/module/az.network/get-azexpressrouteserviceprovider?view=azps-5.4.0
https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-5.4.0#migrate-existing-scripts-from-azurerm-to-az

The page that should be updated: 
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute#connectivity-providers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Extend an on-premises network using ExpressRoute - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/368488/>368488</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@romulobrandino Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.
