### ISSUE TITLE
AWS Traffic Mirroring Equivalent

### ISSUE THREAD

**Issue by danielkon96** [MicrosoftDocs/architecture-center#2628]
The page is missing an Azure equivalent solution for AWS Traffic Mirroring.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b3207bf-471c-33f5-7fb1-0d0a8400e040
* Version Independent ID: f2dc9465-d889-7d8a-02b8-0c0d6125512c
* Content: [Comparing AWS and Azure networking options - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/networking)
* Content Source: [docs/aws-professional/networking.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/networking.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/369410/>369410</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
This PR can be closed; notes in OneNote

**Comment by EdPrice-MSFT** [comment]
This has been logged for a future improvement. Thank you!
