### ISSUE TITLE
Unable to download deployment content

### ISSUE THREAD

**Issue by brahmasky** [MicrosoftDocs/architecture-center#2631]
[Enter feedback here]
Getting the following error while trying to deploy the template from - https://raw.githubusercontent.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/master/allfiles/AZ-301T03/Module_02/LabFiles/Starter/azuredeploy.json

```
Unable to download deployment content from 'https://raw.githubusercontent.com/iainfoulds/architecture-center/aks-devops/docs/sample-solutions/app-modernization/templates/devops-with-aks/nested/grafana.json'. The tracking Id is '56deb704-7f00-4181-9181-f2de40167818'. 
```

Looks like the something is wrong with the URL concatenation. Haven't managed to find out the right path to the grafana.json yet.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5978df0f-98f5-f365-1912-48fc8c27566e
* Version Independent ID: 4f2b4216-1cc7-a267-eee4-d7716ce5ed03
* Content: [CI/CD pipeline for container-based workloads - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-with-aks)
* Content Source: [docs/example-scenario/apps/devops-with-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/devops-with-aks.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @iainfoulds
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/369624/>369624</a>

**Comment by SatishBoddu-MSFT** [comment]
@brahmasky 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @brahmasky, 
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by Zimmergren** [comment]
After a review, there's been quite some changes to this content since it was originally reported, and the deployable assets are pointing to more up to date resources now. I'll open an internal ticket to ensure they update any remaining broken links to these templates across the repositories.

#please-close
