### ISSUE TITLE
Virtual network peering - broken link

### ISSUE THREAD

**Issue by CyberBeerBrewer** [MicrosoftDocs/architecture-center#2633]
In the "Virtual network peering" section link to "Peering Overview" is broken(Markdown error).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli&source=docs#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @neilpeterson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/370289/>370289</a>

**Comment by PramodValavala-MSFT** [comment]
@CyberBeerBrewer Thanks for catching that! We have worked up a PR to address this, which once merged should reflect in a couple of hours.
