### ISSUE TITLE
Unable to see Azure Architecture image

### ISSUE THREAD

**Issue by dineshspatelms** [MicrosoftDocs/architecture-center#2637]
Hi Team,

 I am unable to see Azure Architecture image, could you please look into this.

Dinesh
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4f4c7c-f268-b75b-2486-5c4418e5b24e
* Version Independent ID: 5d28faa1-20bc-1727-05ab-0b18eba1ba7c
* Content: [Data warehousing and analytics - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/data-warehouse)
* Content Source: [docs/example-scenario/data/data-warehouse.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/data/data-warehouse.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/370781/>370781</a>

**Comment by neilpeterson** [comment]
Thanks for opening this issue. This has been updated and will publish today.
