### ISSUE TITLE
Asymmetrical routing

### ISSUE THREAD

**Issue by Chai-NED** [MicrosoftDocs/architecture-center#2642]
Two feedbacks for this important  paragraph:

_"Pay special attention to UDRs in the spoke networks. When the application server receives traffic from a specific Azure Firewall instance, like the .7 address in the previous examples, it should send return traffic back to the same instance. If a UDR in the spoke sends traffic addressed to the hub to the Azure Firewall IP address, like the .4 address in the previous examples, return packets might end up on a different Azure Firewall instance, causing asymmetric routing."_

1. Please spell out the full addresses of the .7 and .4 . App GW, FW and workload all use .4. It would make the paragraph much easier to follow.
2.  How about providing an example of UDR for the spoke networks? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall and Application Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/370987/>370987</a>

**Comment by SatishBoddu-MSFT** [comment]
@Chai-NED 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by erjosito** [comment]
Hey @Chai-NED thanks for the feedback. I have tried to clarify in https://github.com/MicrosoftDocs/architecture-center-pr/pull/2470, would you agree with the changes proposed?

**Comment by Chai-NED** [comment]
Hi Jose,

I got a 404 clicking on the link.

Thanks,

Chai
________________________________

**Comment by erjosito** [comment]
Hey @Chai-NED ah, sorry it must be because it is a PR on the private repo. The new text I put goes like this, is it better now?:

- Pay special attention to UDRs in the spoke networks: When an application server in a spoke receives traffic from a specific Azure Firewall instance, like the `192.168.100.7` address in the previous examples, it should send return traffic back to the same instance. If a UDR in the spoke sets the next hop of traffic addressed to the hub to the Azure Firewall IP address (`192.168.100.4` in the diagrams above), return packets might end up on a different Azure Firewall instance, causing asymmetric routing. Make sure that if you have UDRs in the spoke VNets to send traffic to shared services in the hub through the Azure Firewall, these UDRs do not include the prefix of the Azure Firewall subnet.
- The previous recommendation applies equally to the Application Gateway subnet and any other Network Virtual Appliances or reverse proxies that might be deployed in the hub VNet.
- Note that you cannot set the next hop for the Application Gateway or Azure Firewall subnets by means of static routes with a next hop type of `Virtual Network` in a spoke, since this next hop type is only valid in the local VNet, and not across VNet peerings. See more information about User Defined Routes and next hop types in [Virtual network traffic routing][udr].

**Comment by Chai-NED** [comment]
Hi Jose,

How would do this?

"Make sure that if you have UDRs in the spoke VNets to send traffic to shared services in the hub through the Azure Firewall, these UDRs do not include the prefix of the Azure Firewall subnet."


If the spoke network is peered to the hub network, the prefix of the hub would be the super set of my Azure Firewall subnet.   Says Hub VNET CIDR is 10. 71.0.0/24 and the subnet for AFW is 10.71.1.0/26 . How would I configure the UDR for the spoke to exclude 10.71.1.0/26?

I also think that a traffic flow diagram is needed to show how the UDR recommendation works to avoid asym routing.


Thanks,

Chai
________________________________

**Comment by erjosito** [comment]
You can go to my blog post here for the details: https://blog.cloudtrooper.net/2020/11/28/dont-let-your-azure-routes-bite-you/. I could include the image https://1138blog.files.wordpress.com/2020/11/image-22.png?w=376 in this doc, but I am afraid that will add too much detail for a design document and potentially turn it into a How-To.

**Comment by erjosito** [comment]
Merged, I finally decided to include a diagram

**Comment by Chai-NED** [comment]
Hi Jose,

Thank you for diagram!!  I think it will help many others.  There is another minor touch-up that I see in this important paragraph.


  *   Pay special attention to UDRs in the spoke networks: When an application server in a spoke receives traffic from a specific Azure Firewall instance, like the 192.168.100.7 address in the previous examples, it should send return traffic back to the same instance. If a UDR in the spoke sets the next hop of traffic addressed to the hub to the Azure Firewall IP address (192.168.100.4 in the diagrams above), return packets might end up on a different Azure Firewall instance, causing asymmetric routing. Make sure that if you have UDRs in the spoke VNets to send traffic to shared services in the hub through the Azure Firewall, these UDRs do not include the prefix of the Azure Firewall subnet.
  *   The previous recommendation applies equally to the Application Gateway subnet and any other Network Virtual Appliances or reverse proxies that might be deployed in the hub VNet.


I think replacing the highlighted with the below paragraph will add more clarity and help explain the new diagram.

"To avoid asymmetrical routing, add a new route to the Spoke's UDR. Configure the route for HUB VNET prefix, 192.168.0.0/16 to use the private IP address of the Azure Firewall, 192.168.100.4, as its next hop.  This is done in addition to the existing 0.0.0.0 -> 192.168.100.4. route"


What do you think?


Thanks,

Chai
________________________________

**Comment by erjosito** [comment]
Not sure I follow, the 192.168.0.0/16 UDR is what causes the asymmetric routing

**Comment by Chai-NED** [comment]
Hi Jose,

You are right. I am struggling to understand how Spoke traffic could be forced  to the firewall while the firewall prefix has to be excluded.  Could you give an example of a UDR that does not include the firewall subnet?


Thanks,

Chai

Thanks,

Chai

________________________________

**Comment by erjosito** [comment]
I have that in my blog listed above, but that is not the topic of the article.

**Comment by Chai-NED** [comment]
Hi Jose,


  1.  The link to your blog did not come through.
  2.  Can you explain the purpose of the highlighted route?

[cid:6885abab-2240-4cb9-8bc5-4ff4147aadae]
________________________________

**Comment by erjosito** [comment]
https://blog.cloudtrooper.net/2020/11/28/dont-let-your-azure-routes-bite-you/

This is exactly why I didnt want to put the diagram, otherwise I need to explain everything and deviate from the article's main topic. The route in red is the one causing the asymmetric routing.

**Comment by Chai-NED** [comment]
Hi Jose,

You have a great write up for the solution that should be incorporate in the official doc. I can see your point of view of not wanting to explain everything, but my opinion differs. Many thousands of people like me in pre-sales rely on Microsoft public doc (not blog) as a gold reference to our customers. We hold Microsoft to a very high standard and expect Microsoft to deliver so we can pass it on to our customers.


IMO You would not even have to mention the first approach as it is not practical to predict the next internal IP of AFW to keep this concise.

So, it may read like :
"The solution is to configure the UDR to use a smaller CIDR of the common services subnet as shown in the diagram."
[cid:d240da97-903c-4fde-b77f-abd44a8e4c06]



Thanks,

Chai

________________________________

**Comment by erjosito** [comment]
Just added a comment to explain that. Better?

**Comment by Chai-NED** [comment]
Yes! The explanation is concise and precise. I don't see the solution, using small CIDR for shared service, that you mentioned in the blog. Did I miss it on the MS doc?
________________________________

**Comment by erjosito** [comment]
Mmmh, the PR is merged (https://github.com/MicrosoftDocs/architecture-center-pr/pull/2582), but changes do not seem to appear in the docs yet... Here the text I added after the picture:

"The solution for this asymmetric routing problem is defining UDRs in the spoke that do not contain the Azure Firewall subnet, but only the subnets where the shared services are located. In the example of the previous diagram, the correct UDR in the spoke should only contain 192.168.1.0/24, and not the whole 192.168.0.0/16 as marked in red."

I would suggest to give it a couple of days...

**Comment by Chai-NED** [comment]
Very cool! That's strange. Perhaps, CDN has something to do with it.  I will keep checking.
________________________________
