### ISSUE TITLE
Source Visio Diagram files

### ISSUE THREAD

**Issue by cdotzenrod** [MicrosoftDocs/architecture-center#2645]
Is there a place or way to get the Visio diagram files for this architecture?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724a3b3-3c90-3f27-a51d-454819e88f37
* Version Independent ID: 0c1b3984-7fbd-70ab-98e1-a2bb7697876b
* Content: [Profisee master data management with Azure Data Factory - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-data-factory)
* Content Source: [docs/reference-architectures/data/profisee-master-data-management-data-factory.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/profisee-master-data-management-data-factory.yml)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/371452/>371452</a>

**Comment by SatishBoddu-MSFT** [comment]
@cdotzenrod 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR. Content in OneNote

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!

**Comment by EdPrice-MSFT** [comment]
We ended up adding the Visio download to the article: https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-data-factory#architecture
