### ISSUE TITLE
Question regarding "Performance acceleration"

### ISSUE THREAD

**Issue by AndyHerb** [MicrosoftDocs/architecture-center#2646]
The final decision asks "Do you require performance acceleration" and pushes towards Front Door + Application Gateway (as opposed to just App Gateway) if the answer is "yes".  There's no clear rational or explanation as to why this decision is there, as it's my understanding that Front Door doesn't provide any performance acceleration improvements over App Gateway, and instead the only appreciable benefit to Front Door over App Gateway is the prior is Global and currently can't pass traffic directly to resources with a Private IP.

Given that many will take this flow chart as gospel, it seems sensible to expand on the rational behind the decisions if at all possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#decision-tree-for-load-balancing-in-azure)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/372372/>372372</a>

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @AndyHerb, 
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by ckittel** [comment]
Thank you for bringing this up as a point of clarification we can make.  I've went ahead and added the definition of what is meant by that to the text below the flow chart.  Good point on the ambiguity that previous had.  This change should be live in about 24 hours.
