### ISSUE TITLE
Serverless apps using Cosmos DB - Architecure

### ISSUE THREAD

**Issue by solutionarchitech** [MicrosoftDocs/architecture-center#2655]
Hi,

The architecture of Serverless apps using Cosmos DB is impressing. Could you please share more information on that please?

Thanks
Mg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779b0c0e-591b-2a38-5076-1c3c046e662c
* Version Independent ID: d681f23c-1480-b49c-bbc6-f38d76958f7e
* Content: [Serverless apps using Cosmos DB - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/serverless-apps-using-cosmos-db)
* Content Source: [docs/solution-ideas/articles/serverless-apps-using-cosmos-db.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/serverless-apps-using-cosmos-db.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/373164/>373164</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR, as content in OneNote

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
