### ISSUE TITLE
Secure DevOps for AKS

### ISSUE THREAD

**Issue by harrchen88** [MicrosoftDocs/architecture-center#2656]
Love to see this article is expanded with labs and cost information:
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/secure-devops-for-kubernetes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc547e3a-5433-08eb-9bc2-c0a44e4280a5
* Version Independent ID: 3ab8ba71-f5c5-dcb4-c1be-cde8b61cda34
* Content: [Secure DevOps for AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/secure-devops-for-kubernetes)
* Content Source: [docs/solution-ideas/articles/secure-devops-for-kubernetes.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/secure-devops-for-kubernetes.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/373200/>373200</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR; content in OneNote

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
