### ISSUE TITLE
Can't download all the content when clicked on 'Download PDF' 

### ISSUE THREAD

**Issue by midhunkumarsingh** [MicrosoftDocs/architecture-center#2664]
Hi, Team.

Can't download all the content when clicked on 'Download PDF', mostly all white-pages are download from 'Internet of Things', below is the image for your reference.

![image](https://user-images.githubusercontent.com/7599305/107645353-97a90080-6c9e-11eb-989a-417a021c5966.png)
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94adfdf4-b37e-e66c-b20e-6d59a2777dff
* Version Independent ID: 65fd7e49-611f-f2d8-f794-27e37020f264
* Content: [IoT solutions conceptual overview - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/iot/introduction-to-solutions)
* Content Source: [docs/example-scenario/iot/introduction-to-solutions.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/iot/introduction-to-solutions.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @wamachine
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/374094/>374094</a>

**Comment by BryanLa** [comment]
@midhunkumarsingh - our apologies for the long delay on this, and thank you for reporting this. The issue has been resolved and PDFs published after 12/8 10am Pacific are now accurate.

#please-close
