### ISSUE TITLE
Missing comparison around Azure Databox Gateway

### ISSUE THREAD

**Issue by ElanShudnow** [MicrosoftDocs/architecture-center#2665]
Surprised this article doesn't mention Azure Databox Gateway

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e037b-a226-62cf-6e2b-2af8783b7add
* Version Independent ID: c666597e-52ae-ee51-474a-c4dd3a63941b
* Content: [Choosing a data transfer technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer)
* Content Source: [docs/data-guide/scenarios/data-transfer.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/data-transfer.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/375056/>375056</a>

**Comment by Zimmergren** [comment]
Great tip. The latest version of this article talks about Azure Data Box Gateway, too. Thanks for bringing this up. 

#please-close
