### ISSUE TITLE
I would like more info on implementation details and pricing for the Web and Mobile Front Ends architecture

### ISSUE THREAD

**Issue by Gizzmonauta** [MicrosoftDocs/architecture-center#2666]
I am looking at the web and mobile front ends architecture presented in https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/front-end, as it is exactly the architecture I need for a project I'm designing, and I would like some more inform on implementation details and some guidence on the pricing.

The same web site mentions: 
_Solution Idea
If you'd like to see us expand this article with more information, implementation details, pricing guidance, or code examples, let us know with GitHub Feedback!_

I would love any help you can give me on this.

Best regards

Carlos Lopez

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2418a3-cb9d-eb10-dc57-6a4f0ccfee73
* Version Independent ID: 6cb4ac49-e87b-1bd6-ca61-0a3fe8cfa2d5
* Content: [Web and Mobile Front Ends - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/front-end)
* Content Source: [docs/solution-ideas/articles/front-end.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/front-end.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/375256/>375256</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR, as content is in OneNote
