### ISSUE TITLE
Definition of Big Data is confusing

### ISSUE THREAD

**Issue by vibhatrehan** [MicrosoftDocs/architecture-center#2669]
In the Big Data section, the statement "Big data solutions typically involve a large amount of non-relational data" doesn't seem to be right. It is possible to ingest (say) structured CSV files in high volume on Hadoop cluster or stream CDC inputs from a relational database like Oracle. NoSQL is only a different structuring of data and may or may not come under "big data" category. Typically, big data's definition based on 4 Vs (Velocity, Volume, Variety and Veracity) stands out the most.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf39ec6-5a99-ca3d-8913-9021898dcfbb
* Version Independent ID: 7aa2e806-302b-23b3-7002-1dfed4b7dd28
* Content: [Azure Data Architecture Guide - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/)
* Content Source: [docs/data-guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/375583/>375583</a>

**Comment by PramodValavala-MSFT** [comment]
@vibhatrehan Thanks for the feedback! I suppose that is more of a statistic and perhaps semi-structured is a better way to put it. 

We have assigned this issue to the content author to further review.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24413 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
