### ISSUE TITLE
What is $ASSIGNEE?

### ISSUE THREAD

**Issue by deathgaze** [MicrosoftDocs/architecture-center#2673]
Article is not useful because it is missing information on how to obtain nescessary data to assign to $ASSIGNEE environment variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af2f117-85b5-b53e-b9b8-58c43a0aac71
* Version Independent ID: 0640e0e2-04d8-e056-78e8-977bb7a559dc
* Content: [AKS triage - container registry connectivity - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-triage-container-registry)
* Content Source: [docs/operator-guides/aks/aks-triage-container-registry.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/operator-guides/aks/aks-triage-container-registry.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @kevingbb
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/376296/>376296</a>

**Comment by deathgaze** [comment]
Missed some critical context.
