### ISSUE TITLE
Additional Issues and Considerations

### ISSUE THREAD

**Issue by lvalencia** [MicrosoftDocs/architecture-center#2675]
In _Queue-Based Load Leveling pattern_ under _issues and considerations_ I feel there are a couple more considerations that might be worth mentioning.

1) Depending on the load of the service, you can run into a situation where you're effectively always trailing behind. i.e. you're always queuing up more requests than you're burning down. So the kind of traffic of your application needs to be taken into consideration (aside from just handling spikes).

2) The pattern can lose information depending on the persistence of the Queue. If your queue crashes or drops information (due to system limits) there's a possibility that you don't have guaranteed delivery. So the behavior of your queue and system limits need to be taken into consideration based on the needs of your solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b2b229-0cae-3ba9-180c-5aab1a5a4897
* Version Independent ID: 85c2c9d6-cef4-9a7c-a512-ecdd69e1b456
* Content: [Queue-Based Load Leveling pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling)
* Content Source: [docs/patterns/queue-based-load-leveling.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/queue-based-load-leveling.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/377412/>377412</a>

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @dragon119, apologies for the delay, can you please have a look at the considerations made above? Thank you!

**Comment by v-fearam** [comment]
PR merged
#please-close
