### ISSUE TITLE
Azure Load Balance- Regional or Global

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftDocs/architecture-center#2676]
I see that this page has a chart that has reclassified the Azure Load Balancer as Global not Regional. It was listed as Regional before.  Why has this changed?  Traffic Manager and Front Door would be the Global items while Traffic Manager and Load Balancer as Regional.

Cheers,
Jeff Smalley MCT
Chicagoville

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/377614/>377614</a>

**Comment by JayaC2019** [comment]
@JeffSmalley Thank you for reaching out. You may refer to : https://docs.microsoft.com/en-us/azure/load-balancer/cross-region-overview . This might explain why it is marked as "Global". However, I will reconfirm the same at the earliest.

**Comment by JayaChatterjee-MSFT** [comment]
@JeffSmalley Thank you for reaching out. You may refer to : https://docs.microsoft.com/en-us/azure/load-balancer/cross-region-overview . This might explain why it is marked as "Global". However, I will reconfirm the same at the earliest.

**Comment by JayaChatterjee-MSFT** [comment]
@JeffSmalley Following up to understand whether my previous comment helps and works out for the mentioned problem statement. Also I have confirmed that the document I shared is the latest one and it explains why it is marked as "Global".

**Comment by skabou** [comment]
It appears this has been addressed.  Please re-open with additional details if help is still needed.
