### ISSUE TITLE
AzFW Premium link broken

### ISSUE THREAD

**Issue by erjosito** [MicrosoftDocs/architecture-center#2678]
The AzFW Premium link is broken, trying to fix it with https://github.com/MicrosoftDocs/architecture-center-pr/pull/2479

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall and Application Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/377976/>377976</a>

**Comment by PramodValavala-MSFT** [comment]
@erjosito Closing this since the PR has been merged. Thanks!

**Comment by erjosito** [comment]
Hey @PramodValavala-MSFT. The PR is merged, but the problem still exists. Could you please reopen this?

**Comment by PramodValavala-MSFT** [comment]
@erjosito Since the PR was in the private repo, it will reflect in the next sync between the repos. Rest assured, it should reflect by tomorrow.

**Comment by erjosito** [comment]
@PramodValavala-MSFT Still not there... Additionally, the localized web site versions I have tried (fr-fr, es-es) are even further behind.

This issue is not fixed yet.

**Comment by PramodValavala-MSFT** [comment]
@david-stanford Could you share insights on the deployment? Looks like the public repo has the change already but the public site doesn't seem to.

**Comment by erjosito** [comment]
FYI: it feels weird having a closed issue for a problem which is still happening

**Comment by PramodValavala-MSFT** [comment]
My bad. Thought I had reopened this.

**Comment by erjosito** [comment]
Everything is fine now!
