### ISSUE TITLE
Maximum pods per node is incorrect or outdated

### ISSUE THREAD

**Issue by daviddesmet** [MicrosoftDocs/architecture-center#2679]
Under _Configure compute for the base cluster_ it mentions "The maximum pods per node, is set to 30, which is also the default." but for CNI the maximum is currently 250 as stated in the docs found here:

https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#configure-maximum---new-clusters

The default varies depending on the method of cluster deployment which could be 30 for Azure CLI and Resource Manager template and 110 if using Portal.

https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#maximum-pods-per-node

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an Azure Kubernetes Service (AKS) cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/378215/>378215</a>

**Comment by PramodValavala-MSFT** [comment]
@daviddesmet Thanks for the feedback! As far as the default is concerned, 30 seems right except the portal which you've mentioned.

Do note that this recommendation is for system nodes which usually run lighter nodes and are best kept light to ensure smooth operation.

We have assigned this issue to the content author to further review and to update the doc if required.

**Comment by PageWriter-MSFT** [comment]
Thank you for opening this issue. What you have mentioned is indeed correct. We've updated the guidance about considerations on choosing a max pods values.
