### ISSUE TITLE
Seems really old

### ISSUE THREAD

**Issue by deltadan** [MicrosoftDocs/architecture-center#2680]
This article is from 2017? Should be retired or updated maybe?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e6cd92-676a-6d6f-2ea8-ebe9301f59a9
* Version Independent ID: edfbb571-5bcf-2339-2cce-5e6a22fd591c
* Content: [Autoscaling guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/auto-scaling)
* Content Source: [docs/best-practices/auto-scaling.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/auto-scaling.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/379639/>379639</a>

**Comment by hallihan** [comment]
Article has had many updates since this issue was reported.
