### ISSUE TITLE
Azure ML models training integration

### ISSUE THREAD

**Issue by Dacolo** [MicrosoftDocs/architecture-center#2681]
While the article is more related to ML models in general terms would be great to have this feature is Azure ML

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/380370/>380370</a>

**Comment by JayaChatterjee-MSFT** [comment]
@Dacolo Thank you for the question. We will review and get back to you.

**Comment by hallihan** [comment]
@Dacolo - can you add a link to the specific article and section?  Also, can you add some more details?  Is this a feature request specifically for Azure ML, or a request for clarification or more detail in the doc?  Thanks!

**Comment by Dacolo** [comment]
Hi Team

We get a lot of request on training ML/DL models on AKS. This is not yet a feature available in Azure ML. So what happens is that people will create a docker container themselves and put it on AKS and run it. However they get into performance problems on how to scale pods etc. So would be great to have a document that explains with examples how to train a scikit-learn model, a pyspark model, a tensorflow model. Best practices, suggestions, reference architecture.
Including also how to monitor the training in AKS, how to trigger it on an ML Ops process etc.
Both for CPU and GPU since suggestions might differ.

The ideal should be done via Azure ML, so all logs, experiments etc. lands in the Studio and also monitoring and MLOps can easily being done.
But since it is not a feature available is worth to have a document on how to do it yourself on AKS

Thanks
Daniela

Daniela Colombo
Machine Learning & AI Tech Lead
Global Partner Success Team
daniela.colombo@microsoft.com<mailto:daniela.colombo@microsoft.com> | +39 344-123-6611

[cid:image001.png@01D70B71.0D539370]
[cid:image002.png@01D70B71.0D539370]
This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.
Planned travel/leaves and working time zones:
