### ISSUE TITLE
Add reference to Multi-Region SQL AOAG deployment 

### ISSUE THREAD

**Issue by NWiddup** [MicrosoftDocs/architecture-center#2684]
Please consider adding a reference in the Related Resources section for [Configure a SQL Server Always On availability group across different Azure regions](https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/availability-group-manually-configure-multiple-regions), as this model for the data tier which is being presented in this architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Multi-region N-tier application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/multi-region-sql-server)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/multi-region-sql-server.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/381387/>381387</a>

**Comment by shashishailaj** [comment]
Thank you for responding @david-stanford . 

We will be closing this issue now as we have an internal bug already in our backlog related to this request .

Thank you.
