### ISSUE TITLE
Include CosmosDB Table API in the data store decision tree

### ISSUE THREAD

**Issue by reub-the-cube** [MicrosoftDocs/architecture-center#2686]
Could the data decision tree include CosmosDB Table API? I understand that it's preferred over the Azure Table Storage, but I haven't read that - for example - you should/could choose SQL API over Table API if you have simple key/value storage? It seems like it's forgotten, although I could be ignorant of some decision making.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88559925-9b9e-d9b3-ddb6-08306692c17b
* Version Independent ID: a25055cb-7cfe-28a0-1c66-06172c037128
* Content: [Data store decision tree - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)
* Content Source: [docs/guide/technology-choices/data-store-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/382421/>382421</a>

**Comment by neilpeterson** [comment]
@reub-the-cube thanks for opening this issue. The diagram has been updated, it may take a bit to propagate through our CDN, but it's on the way.
