### ISSUE TITLE
Update Cosmos DB  Partition Size Discussion

### ISSUE THREAD

**Issue by dgpoulet** [MicrosoftDocs/architecture-center#2687]
In the section talking about Cosmos DB it says: "If you store a separate document for every device message, using the device ID as a partition key would quickly exceed the 10-GB limit per partition"

The current logical partition size limit is now 20 GB. Also, the discussion makes it seem like you **have** to pick a particular attribute for a partition key, when it's quite common in these scenarios for customers to create a synthetic key composed of multiple attributes to help with data distribution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/383637/>383637</a>

**Comment by skabou** [comment]
It appears this was addressed some time ago.  If help is still needed, please feel free to re-open with additional details.
