### ISSUE TITLE
ADAL is being depreciated

### ISSUE THREAD

**Issue by neilpeterson** [MicrosoftDocs/architecture-center#2688]
ADAL is being depreciated and should be removed from this article. See this article for details:

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration 

Cc: @mmacy 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab204a8d-c451-ef99-6610-139a0dee61ac
* Version Independent ID: 23a69ae2-70bc-aab5-bbe1-e9699d57558b
* Content: [Cache access tokens in a multitenant application - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache)
* Content Source: [docs/multitenant-identity/token-cache.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/token-cache.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/384777/>384777</a>

**Comment by mmacy** [comment]
Also in relation to the following Microsoft-internal Azure DevOps work item:

ID | Title | Iteration Path
-- | -- | --
[1308698](https://identitydivision.visualstudio.com/Technical%20Content/_workitems/edit/1308698) | [ADAL] replace references of ADAL with MSAL in Azure Architecture Center | Technical Content\FY21 H2\FY21_03_Mar

Cc: @aiwangmicrosoft

**Comment by skabou** [comment]
It appears this has been addressed.  Please re-open with additional details if help is still needed.
