### ISSUE TITLE
SeatAvailability aggregate broken? 

### ISSUE THREAD

**Issue by saheemsiddiqi** [MicrosoftDocs/architecture-center#2689]
In the SeatAvailability example, how do we account for overbooking?  If two transactions are concurrently running, they may read the same event stream, determine the same number of available seats, and emit a Reservation event.  Consider if there is 1 seat remaining, and the two concurrently running transactions reserve 1 seat each.  

We don't have a central record that is being updated, so optimistic locking is out.  A single processor is possible, but that constrains scalability.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing)
* Content Source: [docs/patterns/event-sourcing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/event-sourcing.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/384891/>384891</a>

**Comment by ckittel** [comment]
You are correct, when you cannot single thread the processor, this doesn't eliminate concurrency issues.

Matter of fact, this is called out in the article:

> Even though event sourcing minimizes the chance of conflicting updates to the data, the application must still be able to deal with inconsistencies that result from eventual consistency and the lack of transactions. For example, an event that indicates a reduction in stock inventory might arrive in the data store while an order for that item is being placed, resulting in a requirement to reconcile the two operations either by advising the customer or creating a back order.

Your example is another situation of this. These solutions often do have remediation/reconciliation processes that need to happen to address situations like this.  If it's in a critical path, and this behavior would do more harm than good, you'd need to guard against it.  The example given in this case seems to always end up in this situation as seat numbers approach zero, so a business decision would need to be made on how to handle it.

I'm going to close as this is indeed addressed/called out, but like many patterns, this doesn't solve for everything.  Thank you for the insight and conversation, @saheemsiddiqi
