### ISSUE TITLE
typo of content

### ISSUE THREAD

**Issue by jeromeecho** [MicrosoftDocs/architecture-center#2693]
[Enter feedback here]
Mean Time Between Failures (MTBF) — The average time between failures of a particular component.
duplicated sentence in "Availability targets" section of the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60422eab-f284-4d0f-a856-3910e017b89b
* Version Independent ID: 05eebcc2-4193-def3-ee98-ae98e9729263
* Content: [Target and non-functional requirements - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/design-requirements)
* Content Source: [docs/framework/resiliency/design-requirements.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/resiliency/design-requirements.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/385595/>385595</a>

**Comment by ckittel** [comment]
Thank you for reporting.  This has been fixed (as of a few weeks ago), and is now published.
