### ISSUE TITLE
Test1

### ISSUE THREAD

**Issue by jeckad** [MicrosoftDocs/architecture-center#2694]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Building solutions for high availability using Availability Zones - High Availability](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/high-availability/building-solutions-for-high-availability.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Maggsl
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/385659/>385659</a>

**Comment by TravisCragg-MSFT** [comment]
@jeckad I am going to go ahead and close out this issue, let me know if you have any questions regarding your test.
