### ISSUE TITLE
Usage with pyspark

### ISSUE THREAD

**Issue by Kumar9676** [MicrosoftDocs/architecture-center#2695]
Is it possible to use this in pyspark notebooks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/386210/>386210</a>

**Comment by shashishailaj** [comment]
@Kumar9676 We have an internal request for checking on your query . We will update this thread once we have any update.

**Comment by PramodValavala-MSFT** [comment]
@Kumar9676 Based on [this comment](https://github.com/mspnp/spark-monitoring/issues/50#issuecomment-533778984), any logs generated by spark should be captured but custom logs require a couple of steps as described here.

We have assigned this issue to the content author to review and update accordingly.
