### ISSUE TITLE
How to get license for evaluation?

### ISSUE THREAD

**Issue by apusingh1967** [MicrosoftDocs/architecture-center#2696]
For step 'Deploy the scenario', how to obtain license for trial? Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724a3b3-3c90-3f27-a51d-454819e88f37
* Version Independent ID: 0c1b3984-7fbd-70ab-98e1-a2bb7697876b
* Content: [Profisee master data management with Azure Data Factory - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-data-factory)
* Content Source: [docs/reference-architectures/data/profisee-master-data-management-data-factory.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/profisee-master-data-management-data-factory.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/386218/>386218</a>

**Comment by shashishailaj** [comment]
@apusingh1967 We are checking this internally and will update the thread.

**Comment by apusingh1967** [comment]
thnku

**Comment by PramodValavala-MSFT** [comment]
@apusingh1967 like mentioned under the [pricing section](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-data-factory#pricing), this is something you will have to work with [profisee](https://profisee.com/contact/) directly.

**Comment by PramodValavala-MSFT** [comment]
@apusingh1967 Just following up here... Hope my previous comment clears things up.

Since there is no doc update required here, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
