### ISSUE TITLE
No mention of testing tools

### ISSUE THREAD

**Issue by jnimander** [MicrosoftDocs/architecture-center#2697]
The title of the page is "Testing tools" but I see no mention of any testing tools on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c67eba0-d85b-56e6-35bb-841a98cd1e38
* Version Independent ID: c2c66e14-b4c4-c3a4-343d-3e512d30a088
* Content: [Testing tools - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/scalability/test-tools)
* Content Source: [docs/framework/scalability/test-tools.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/scalability/test-tools.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/386461/>386461</a>

**Comment by psmanhas** [comment]
@jnimander 
Hope the provided information is helpful.

We will now close this issue. If there are further questions regarding this, please tag me in a comment. I will reopen it and we will continue the discussion.

**Comment by ckittel** [comment]
Thanks @jnimander, I've moved this observation to the WAF backlog @ MicrosoftDocs/well-architected#45
