### ISSUE TITLE
Which AWS App from the Gallery?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#2699]
There are several AWS apps in the App Gallery, which one are we supposed to use? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b08461-26fb-d148-a749-9b61217af0f8
* Version Independent ID: 1329c651-e8f6-cc68-4205-739dfbbcef4f
* Content: [Azure Active Directory security for AWS - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/aws/aws-azure-ad-security)
* Content Source: [docs/reference-architectures/aws/aws-azure-ad-security.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/aws/aws-azure-ad-security.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/387813/>387813</a>

**Comment by stephen-sumner** [comment]
Created this PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/8137
