### ISSUE TITLE
AWS SSO is confused with "setting up SSO in AWS"

### ISSUE THREAD

**Issue by richarddiver-ms** [MicrosoftDocs/architecture-center#2700]
There is a section in this document that states the user should setup "AWS SSO" with a link to another document that also says "AWS SSO". Both of these documents were written before the official AWS SSO approach and associated Azure AD Enterprise app for AWS SSO was a thing.

We need to change the wording to explain we are setting up SSO in AWS, we are not using the AWS SSO "feature" or the Azure AD AWS SSO Enterprise app - its a completely different approach and now causes confusion.

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/aws/aws-azure-ad-security#configure-azure-ad-sso-for-aws

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b08461-26fb-d148-a749-9b61217af0f8
* Version Independent ID: 1329c651-e8f6-cc68-4205-739dfbbcef4f
* Content: [Azure Active Directory security for AWS - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/aws/aws-azure-ad-security#configure-azure-ad-sso-for-aws)
* Content Source: [docs/reference-architectures/aws/aws-azure-ad-security.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/aws/aws-azure-ad-security.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/387839/>387839</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR, as content in OneNote

**Comment by EdPrice-MSFT** [comment]
@richarddiver-ms - Are you up for making this edit? Thanks!

**Comment by richarddiver-ms** [comment]
I believe the update is being done by @Luciana Blanchard ***@***.***>

Richard

**Comment by richarddiver-ms** [comment]
Yes, I’m working on the doc today, should be with you shortly 😊

From: Richard Diver (HE/HIM) ***@***.***>
Sent: 01 September 2021 21:15
To: MicrosoftDocs/architecture-center ***@***.***>; MicrosoftDocs/architecture-center ***@***.***>; Luciana Blanchard (SHE/HER) ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/architecture-center] AWS SSO is confused with "setting up SSO in AWS" (#2700)

I believe the update is being done by @Luciana Blanchard ***@***.***>

Richard
