### ISSUE TITLE
There it is, the nasty bug

### ISSUE THREAD

**Issue by funkitptent** [MicrosoftDocs/architecture-center#2703]

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/388043/>388043</a>

**Comment by neilpeterson** [comment]
@funkitptent can you provide more details?

Thanks

**Comment by hallihan** [comment]
No details provided, please re-open with specifics if there is still an issue.
