### ISSUE TITLE
Synapse

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/architecture-center#2704]
Where does Synapse fit in this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560fb3dc-3a89-aa28-f4c1-564f7920f5ca
* Version Independent ID: b5255403-369f-9324-fb16-02526b24dba6
* Content: [Online analytical processing (OLAP) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-analytical-processing)
* Content Source: [docs/data-guide/relational-data/online-analytical-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/relational-data/online-analytical-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/388341/>388341</a>

**Comment by PramodValavala-MSFT** [comment]
@thommck Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
Yes. Synapse has many more capabilities covering ones from OLAP and OLTP too. I am assigning this issue to one who can provide more insights on this and drive doc updates as required.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@thommck, Synapse is an OLAP repository.

Data Lake + SQL Pool + Spark Clusters, taken together, are a Big Data “Online Analytical Processing” solution.  It’s not an OLTP system.

But Synapse also contains the orchestration pieces from Data Factory.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
