### ISSUE TITLE
Predicting Leght stay at hospital

### ISSUE THREAD

**Issue by mejavier** [MicrosoftDocs/architecture-center#2705]
https://docs.microsoft.com/es-es/azure/architecture/solution-ideas/articles/predicting-length-of-stay-in-hospitals

Dear,

I would like to contact someone who can bring me the code of this, because it si needed by one customer. I am belonging to Avanade Spain and it is a good customer.
Kind regards.
Javier Morales.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfae374b-3f6b-1361-3640-57a266c92bfb
* Version Independent ID: 81267d9c-fa5a-930b-3d5e-ca4f01faec38
* Content: [Predicting Length of Stay in Hospitals - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/predicting-length-of-stay-in-hospitals)
* Content Source: [docs/solution-ideas/articles/predicting-length-of-stay-in-hospitals.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/predicting-length-of-stay-in-hospitals.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/388478/>388478</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR, as content is in OneNote

**Comment by EdPrice-MSFT** [comment]
Note that this is beyond our scope. We don't create new deployments.
