### ISSUE TITLE
Broken Link for Emotions API

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/architecture-center#2707]
I'm not sure if the API no longer is available or if the link is just broken but in [On this page](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#ai-and-machine-learning) in the AI and machine learning section it has a link to the [Emotions](https://azure.microsoft.com/services/cognitive-services/emotion/) that no longer exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#ai-and-machine-learning)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@nastassiar Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by neilpeterson** [comment]
Thanks for opening this issue. It looks like emotion detection if now a feature of facial detection. I've updated to doc to reflect and it should publish today.
