### ISSUE TITLE
This is terrific!

### ISSUE THREAD

**Issue by elvisboats** [MicrosoftDocs/architecture-center#2708]
Hey, wanted to express my thanks - this is a GREAT working solution architecture. I'm currently engaged with a company that is looking for something similar using APIM as a hub. I'd love a discussion with the architects involved. But - my main point- this was clear, went through the use of SAGA to compensate for the loss of ACID in a transactional world... very well written. Kudos!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4beca57-c757-f3cd-8c69-e9e87390d9bd
* Version Independent ID: 0034a0fb-2722-7f83-4d02-a0ebfee409a1
* Content: [Banking system cloud transformation on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/banking/banking-system-cloud-transformation)
* Content Source: [docs/example-scenario/banking/banking-system-cloud-transformation.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/banking/banking-system-cloud-transformation.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by neilpeterson** [comment]
@elviscoats - thanks for the feedback, really appreciate the Kudos and will share with the team.
