### ISSUE TITLE
aaaaa

### ISSUE THREAD

**Issue by JasperWoo** [MicrosoftDocs/architecture-center#2709]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1b8746-e961-0add-3f48-de5c6db487f1
* Version Independent ID: db9978bd-576b-a719-47a0-7c6ecb7361ac
* Content: [Comparing AWS and Azure accounts and subscriptions - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/accounts)
* Content Source: [docs/aws-professional/accounts.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/accounts.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/388783/>388783</a>
