### ISSUE TITLE
Services Bus icon is incorrect

### ISSUE THREAD

**Issue by epomatti** [MicrosoftDocs/architecture-center#2710]
Services Bus icon is incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/389238/>389238</a>

**Comment by JasRobe** [comment]
Thank you for pointing this out, I'll ensure it is updated in the next release.

**Comment by miqm** [comment]
Hello, I'd like to add that there are no icons for service bus queue and topic. They could be very handy when designing detailed architecture.

**Comment by v-fearam** [comment]
Hi @epomatti
Sorry for the delay.

I have just downloaded the icons, at this point in time , I found the Service Bus Icon (Azure_Public_Service_Icons\Icons\integration\10836-icon-service-Service-Bus.svg) and the icon is the same that it is used for Service Bus on Azure Portal.
I think the original bug is solved.

I will close the ticket, but feel free to re-open if additional clarification is needed.

By the way,  @miqm, we've passed along your feedback to the team responsible for the icons. Thanks.

**Comment by v-fearam** [comment]
#please-close
