### ISSUE TITLE
Sec instead of msec in background or batch section

### ISSUE THREAD

**Issue by mslot** [MicrosoftDocs/architecture-center#2712]
Here https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#retry-usage-guidance-2 you write msec in the 3. and 4. attempt in the "Background or batch", but doesn't you mean sec?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/389294/>389294</a>
