### ISSUE TITLE
Summary table zonal (Z) and zone-redundant (ZR) Azure services.

### ISSUE THREAD

**Issue by DigiFab** [MicrosoftDocs/architecture-center#2713]
Some services seem to be missing 
- Azure PostgreSQL Flexible Server (ZR)
- Azure MySQL Flexible Server (ZR)
- Azure Managed Disks (ZRS) in preview)

Some questions too 
- Should not ExpressRoute be both (Z, ZR)
- Should not Application Gateway v2 be both (Z, ZR)

This table is interesting but does not look up-to-date and fully accurate. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Building solutions for high availability using Availability Zones - High Availability](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/high-availability/building-solutions-for-high-availability.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Maggsl
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/389551/>389551</a>

**Comment by hallihan** [comment]
The change to address this was merged, #please-close
