### ISSUE TITLE
OMS link on DevOps checklist redirects to page not reflecting the links intention

### ISSUE THREAD

**Issue by timja** [MicrosoftDocs/architecture-center#2715]
Hi

> Microsoft Operation Management Suite also provides centralized monitoring and management for cloud or hybrid solutions.

Links to https://www.microsoft.com/cloud-platform/operations-management-suite which redirects to https://azure.microsoft.com/en-gb/services/virtual-machines/secure-well-managed-iaas/, I don't think the new content at the link reflects what was intended from the original link.

Possibly it should link here instead: https://azure.microsoft.com/en-gb/services/monitor/ and be renamed Azure Monitor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2bdcdc-80e6-c47a-dae6-0f1bc44b765b
* Version Independent ID: aec4e510-ca48-54ba-beda-82e6ac06bf11
* Content: [DevOps checklist - Azure Design Review Framework](https://docs.microsoft.com/en-us/azure/architecture/checklist/dev-ops)
* Content Source: [docs/checklist/dev-ops.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/checklist/dev-ops.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/390619/>390619</a>

**Comment by neilpeterson** [comment]
Thanks for opening this issue. This has been updated and should publish today.
