### ISSUE TITLE
Community Jury Link to Microsoft Community Jury Case Study Results in HITS Unauthorized Erorr

### ISSUE THREAD

**Issue by mikelor** [MicrosoftDocs/architecture-center#2717]
In the Next Steps section at the bottom of the page, there is a link to a Microsoft Case Study on Community Jury.

Clicking on the link results in
HITS
Unauthorized
Possible causes: You may not have sufficient permissions to view this page.

Click here to go to HITS homepage.
Sign out of HITS and sign in again.
Email HITS911@microsoft.com for additional support.

https://hits.microsoft.com/Error401.html?message=Object%20reference%20not%20set%20to%20an%20instance%20of%20an%20object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8aabd2d-267d-c6a0-cc1e-6a52eefedee0
* Version Independent ID: d9c53898-64f4-b13d-b8e3-518b405d8041
* Content: [Community Jury - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/responsible-innovation/community-jury/)
* Content Source: [docs/guide/responsible-innovation/community-jury/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/responsible-innovation/community-jury/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dcass
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/390926/>390926</a>

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017690

**Comment by JanetCThomas** [comment]
This issue has been resolved.
