### ISSUE TITLE
Azure Icons are in HTML vs. SNG format

### ISSUE THREAD

**Issue by Petrus1975** [MicrosoftDocs/architecture-center#2719]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/?WT.mc_id=thomasmaurer-blog-thmaure)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/391141/>391141</a>

**Comment by Petrus1975** [comment]
I can't download Azure icons in the proper format so I can use it. It kept giving me the HTML type instead of SNG!

Any idea?

**Comment by JasRobe** [comment]
Are you accepting the terms with the checkbox and then using the 'downlad SVG icons' button?  or are you using some context menu to 'save target as'?   You should be clicking on the button.   Otherwise, perhaps try using a different browser.  I was unable to reproduce your issue just now.
