### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by hendramarcos** [MicrosoftDocs/architecture-center#2720]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830e1782-9caa-3533-10a0-85a3d4483d24
* Version Independent ID: d66583fa-188c-9dce-b6fd-84b34c0bf315
* Content: [Real time processing - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/real-time-processing?WT.mc_id=AZ-MVP-4039873&source=docs)
* Content Source: [docs/data-guide/big-data/real-time-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/big-data/real-time-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/391348/>391348</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@hendramarcos Could you please elaborate on the feedback you intend to provide?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@hendramarcos Any further update here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@hendramarcos We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
