### ISSUE TITLE
a

### ISSUE THREAD

**Issue by MutazNase** [MicrosoftDocs/architecture-center#2723]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Microsoft Azure Well-Architected Framework - Microsoft Azure Well-Architected Framework introduction](https://docs.microsoft.com/en-us/azure/architecture/framework/)
* Content Source: [docs/framework/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/392407/>392407</a>

**Comment by PramodValavala-MSFT** [comment]
@MutazNase Looks like you've created the issue before sharing all the details here. Could you please update your original post?
