### ISSUE TITLE
multi region app with private database connectivity

### ISSUE THREAD

**Issue by Rajanavuluri** [MicrosoftDocs/architecture-center#2724]
[Enter feedback here]
It is better to add explanation with video content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0461064-5b0f-2722-c228-cc04aef150c9
* Version Independent ID: 705b8a1a-787e-c09f-dff3-c25373743d1d
* Content: [Multi-region web app with private connectivity to database - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/sql-failover/app-service-private-sql-multi-region)
* Content Source: [docs/example-scenario/sql-failover/app-service-private-sql-multi-region.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/sql-failover/app-service-private-sql-multi-region.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jelledruyts
* Microsoft Alias: **edprice**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/392964/>392964</a>

**Comment by jelledruyts** [comment]
Thanks for the suggestion but Azure Architecture Center is currently oriented at written content, there are no plans to record a video for this unfortunately.

**Comment by PageWriter-MSFT** [comment]
We cannot provide videos for reference architectures at this time. However, this is a great suggestion and we'll consider videos experiences in the future.

Thanks
