### ISSUE TITLE
Update around connecting ASC to sentinel

### ISSUE THREAD

**Issue by hanwesh** [MicrosoftDocs/architecture-center#2725]
Hi team,

I think this page need some updates around connect ASC to sentinel. There is no ASC in data connectors list in sentinel, instead, I think it should be Azure Defender. I also find this page to support my assumption.

https://docs.microsoft.com/en-us/azure/sentinel/connect-azure-security-center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce3b9c5-ef05-1ff3-a6fe-052f48a9b471
* Version Independent ID: f6d3e8e8-37c5-43e6-6185-58f8511dee7e
* Content: [Hybrid Security Monitoring using Azure Security Center and Azure Sentinel - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-security-monitoring)
* Content Source: [docs/hybrid/hybrid-security-monitoring.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/hybrid-security-monitoring.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/393730/>393730</a>

**Comment by KalyanChanumolu-MSFT** [comment]
@david-stanford Assigning this to the document author Derek
