### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SouthCrux** [MicrosoftDocs/architecture-center#2726]
Hello Team,
Great to have those Reference Architectures, would it be possible to get more information, implementation details, best practices and pricing guidance?
Thanks and regards,
Santiago

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/394406/>394406</a>

**Comment by neilpeterson** [comment]
@SouthCrux, thanks for opening this issue and for the feedback. 

We are always looking for suggestions for new solutions / architectural guidance. As well, appreciate any feedback on how we can improve content found in the Azure Architect Center. 

Are there **specific solutions** where you would like to see additional details, or do you feel that, **in general**, the content found in the Azure Architecture Center could use some of these additional details (implementation details, best practices, pricing)?

Thanks a bunch.

**Comment by neilpeterson** [comment]
@SouthCrux I am going to close this out. If you can provide feedback as suggested above, feel free to re-open.
