### ISSUE TITLE
Event Grid - now HITRUST compliant?

### ISSUE THREAD

**Issue by melvincanafranca** [MicrosoftDocs/architecture-center#2727]
The icon used in the solution blueprint is an Event Hub while the description below the blueprint described it as Event Grid. Can someone please confirm if Event Grid is now HITRUST compliant? As per the documentation from this [link](https://azure.microsoft.com/en-us/resources/microsoft-azure-compliance-offerings/), only Event Hub is HITRUST compliant.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34b4a06-1bc0-bd3c-60b6-1c78f3807640
* Version Independent ID: 0f02854b-44bb-978b-ebc8-b6313da37328
* Content: [HIPAA and HITRUST compliant health data AI - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/security-compliance-blueprint-hipaa-hitrust-health-data-ai)
* Content Source: [docs/solution-ideas/articles/security-compliance-blueprint-hipaa-hitrust-health-data-ai.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/security-compliance-blueprint-hipaa-hitrust-health-data-ai.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/395325/>395325</a>

**Comment by melvincanafranca** [comment]
Sorry my bad, I think I've looked at the Azure Government section of Appendix A. The non-government version has Event Grid as HITRUST compliant. Still, the icon is wrong if we really meant to use Event Grid.
