### ISSUE TITLE
Consider adding WAF to this reference architecture

### ISSUE THREAD

**Issue by kyleburnsdev** [MicrosoftDocs/architecture-center#2728]
The premise of this reference architecture is to be actionable guidance on secure connectivity, but Traffic Manager is resolving directly to App Service instances rather than using an Azure App Gateway in WAF mode or replacing Traffic Manager with Azure Front Door (WAF enabled). To better reflect how this scenario should be realized in the real world, please consider extending to include a WAF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0461064-5b0f-2722-c228-cc04aef150c9
* Version Independent ID: 705b8a1a-787e-c09f-dff3-c25373743d1d
* Content: [Multi-region web app with private connectivity to database - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/sql-failover/app-service-private-sql-multi-region)
* Content Source: [docs/example-scenario/sql-failover/app-service-private-sql-multi-region.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/sql-failover/app-service-private-sql-multi-region.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jelledruyts
* Microsoft Alias: **edprice**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/395507/>395507</a>

**Comment by RobBagby** [comment]
This was closed with the following PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/8779.
