### ISSUE TITLE
There is a different file under the Visio link

### ISSUE THREAD

**Issue by Kalaivin** [MicrosoftDocs/architecture-center#2729]
Good day,

I just noticed that the Visio file I get when clicking the "Download (https://arch-center.azureedge.net/dmz-reference-architectures.vsdx) a Visio file of this architecture." is different than the one displayed in the article: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/images/dmz-private.png

Regards,
Karlis
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz?tabs=portal#feedback)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/396759/>396759</a>

**Comment by BryanLa** [comment]
@Kalaivin  - our apologies for the delay in responding, and thanks for reporting this. 

I researched this and it appears that the image file was incorrect. This has since been corrected, along with a freshness review of the architecture and article content.

#please-close
