### ISSUE TITLE
How do I install the Azure Icons into Vision 2016 Pro?

### ISSUE THREAD

**Issue by JohnStraumann66** [MicrosoftDocs/architecture-center#2730]

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/396952/>396952</a>

**Comment by KalyanChanumolu-MSFT** [comment]
@JohnStraumann66 I believe you meant Microsoft Visio Professional.
 You can download the svg icons from [here](https://docs.microsoft.com/en-us/azure/architecture/icons/)

**Comment by KalyanChanumolu-MSFT** [comment]
@JohnStraumann66 
We will proceed to close this issue now. 
If there are further questions regarding this matter, please comment and we will gladly continue the discussion.

**Comment by JohnStraumann66** [comment]
> @JohnStraumann66 I believe you meant Microsoft Visio Professional.
> You can download the svg icons from [here](https://docs.microsoft.com/en-us/azure/architecture/icons/)

OK great, and then what? I cannot find any docs on how to import the icons into Vision as Stencils?
