### ISSUE TITLE
Invalid C# syntax in code sample

### ISSUE THREAD

**Issue by allison-silverpine** [MicrosoftDocs/architecture-center#2735]
Hello,
It appears that the code sample for the referenced documentation contains some invalid C# syntax, and given the code, it's not clear how to check if the device needs an SMS wakeup.  

`if (var == [DeviceNotConnected] && connTimeOut == 0)`
I'm not sure where "DeviceNotConnected" is coming from, and I don't believe the use of `var` here or later in the method is valid.  

Full code sample:
`TimeSpan connTimeOut = FromSeconds(0); // Period to wait for device to connect.
    TimeSpan funcTimeOut = FromSeconds(30); // Period to wait for method to execute.

    while (true) {
        // Send the command via direct method. Initially use a timeout of zero
        // for the connection, which determines whether the device is connected to
        // IoT Hub or needs an SMS wakeup sent to it.
        
        var method = new CloudToDeviceMethod("RemoteCommand", funcTimeOut, connTimeOut);
        methodInvocation1.SetPayloadJson(CommandPayload);

        var response = await serviceClient.InvokeDeviceMethodAsync(deviceId, method);
        if (var == [DeviceNotConnected] && connTimeOut == 0) {
            // The device is not currently connected and needs an SMS wakeup. This
            // device should wake up within a period of < 30 seconds. Send the wakeup
            // and retry the method request with a 30 second timeout on waiting for
            // the device to connect.

            connTimeOut = FromSeconds(30); // Set a 30 second connection timeout.
            SendAsyncSMSWakeUpToDevice(); // Send SMS wakeup through mobile gateway.
            continue; // Retry with new connection timeout.
        } else {
            // The method either succeeded or failed.
            ActOnMethodResult(var);
            break;
        }
    }`

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b2f7457-51f0-b9e0-04bd-dabbe3586b34
* Version Independent ID: 08b9268e-c8d1-5259-0f0d-3fc851f35dbe
* Content: [IoT application-to-device commands - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/iot/cloud-to-device)
* Content Source: [docs/example-scenario/iot/cloud-to-device.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/iot/cloud-to-device.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @wamachine
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/399688/>399688</a>

**Comment by RobBagby** [comment]
This bug was closed with PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/8766.
