### ISSUE TITLE
Visio Diagrams for Architecture Center

### ISSUE THREAD

**Issue by maglimedia** [MicrosoftDocs/architecture-center#2737]
It would be great to have access to the Visio Diagrams for all of the Architecture Center Azure patterns.
Where can a Microsoft employee access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724a3b3-3c90-3f27-a51d-454819e88f37
* Version Independent ID: 0c1b3984-7fbd-70ab-98e1-a2bb7697876b
* Content: [Profisee master data management with Azure Data Factory - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-data-factory)
* Content Source: [docs/reference-architectures/data/profisee-master-data-management-data-factory.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/profisee-master-data-management-data-factory.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/401032/>401032</a>

**Comment by JanetCThomas** [comment]
You can browse for specific architecture visio diagrams here:  https://learn.microsoft.com/en-us/azure/architecture/browse/
