### ISSUE TITLE
Intelligent apps using Azure Database for PostgreSQL

### ISSUE THREAD

**Issue by bruparel** [MicrosoftDocs/architecture-center#2738]
Implementation details, pricing guidance, or code examples would be most useful

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/401114/>401114</a>

**Comment by EdPrice-MSFT** [comment]
Note that this is regarding a solution idea: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/intelligent-apps-using-azure-database-for-postgresql

**Comment by v-fearam** [comment]
Hi @bruparel

Sorry for the delay and thanks for the suggestions. 
This current article is a  “Solution idea” which its goals is to keep it simple, here there is more information about Azure Database for PostgreSQL which would cover your concerns

Concepts, tutorials, options: [https://learn.microsoft.com/azure/postgresql/](https://learn.microsoft.com/en-us/azure/postgresql/)
 
About cost, I would suggest [Azure Price Calculator](https://azure.microsoft.com/pricing/calculator)

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by ckittel** [comment]
@tchristiani -- we've closed this issue, but consider this a signal please for content strategy.  A request to take a Solution Idea and uplevel it to an Example Workload.
