### ISSUE TITLE
Design pattern link 

### ISSUE THREAD

**Issue by Sohanrt** [MicrosoftDocs/architecture-center#2739]
[Enter feedback here]
Design pattern link is not correctly map it is takingus back to the same page ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Guide - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/401272/>401272</a>

**Comment by RobBagby** [comment]
This issue has been resolved. Please re-open the issue if you believe it was closed in error.
