### ISSUE TITLE
Container access

### ISSUE THREAD

**Issue by aerionTech** [MicrosoftDocs/architecture-center#2740]
[Enter feedback here]

Hi is there a pre-configured container to access this setup?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2edf62c9-d5c7-b4d0-99e7-f271ef0b629e
* Version Independent ID: d9ff7f72-3fbb-3bc6-e787-60b1ccecb698
* Content: [Magento e-commerce platform in Azure Kubernetes Service (AKS) - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/magento/magento-azure#feedback)
* Content Source: [docs/example-scenario/magento/magento-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/magento/magento-azure.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/402446/>402446</a>

**Comment by aerionTech** [comment]
Hi @david-stanford I found the ARM template earlier, it would useful to include the link  on the documentation page. 
https://github.com/Azure/azure-mysql/tree/master/Magento

**Comment by Zimmergren** [comment]
Hi. Unfortunately, we don't have any pre-configured containers for this setup. However, I would recommend checking out the public marketplace that includes container images for Magento: https://azuremarketplace.microsoft.com/en-US/marketplace/apps?search=magento

#please-close
