### ISSUE TITLE
Need detailed info on |How to create Power BI dashboard for ML Ops

### ISSUE THREAD

**Issue by radhakrishnang** [MicrosoftDocs/architecture-center#2741]
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/mlops/mlops-technical-paper

Need detailed info on |How to create Power BI dashboard for ML Ops - please find attached image... h
1) how to connect those metrics to power BI
2) if we want to save those metrics along with data drift and model fairless, and other features in Azure SQL how to achieve that ?

![ml-training-dashboard](https://user-images.githubusercontent.com/10942003/113006361-ebaa6e80-9192-11eb-8d18-74d8aef0a5d9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d13228b-be2e-8374-fbe9-b90b8a05e904
* Version Independent ID: ebd1326f-47ef-2cc6-bb62-ab2e2711558e
* Content: [Machine learning operations (MLOps) framework to upscale machine learning Lifecycle with Azure Machine Learning - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/mlops/mlops-technical-paper)
* Content Source: [docs/example-scenario/mlops/mlops-technical-paper.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/mlops/mlops-technical-paper.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/402859/>402859</a>

**Comment by mathjon248** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/visualize/powerbi

I think the AML metrics to Log Analytics or M on storage account destination from diagnostics log for long term storage. 

In Log Analytics you can download the m and pbit template.

**Comment by radhakrishnang** [comment]
Can you give additional detailed pointers / links

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24288 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
