### ISSUE TITLE
Azure Load Balancer is marked as global LB

### ISSUE THREAD

**Issue by FarhadJabiyev** [MicrosoftDocs/architecture-center#2742]
In table "Azure Load Balancer" is marked as "Global" load balancer. But, as I understand it is not global, but regional.

--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/402945/>402945</a>

**Comment by KurtSchenk** [comment]
cross-regional Load Balancer is in preview: https://docs.microsoft.com/en-us/azure/load-balancer/cross-region-overview. Can the documentation be updated to reflect this?
