### ISSUE TITLE
Awards?

### ISSUE THREAD

**Issue by mattborland** [MicrosoftDocs/architecture-center#2743]
What awards did it win. I can't find anything on the web....I didn't use Bing for searching, though...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06b04b15-1daa-44c9-6392-4743527ebd20
* Version Independent ID: d0fbe85f-6167-4f34-c2a0-6304e6b0cf9d
* Content: [Judgment Call - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/responsible-innovation/judgmentcall)
* Content Source: [docs/guide/responsible-innovation/judgmentcall.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/responsible-innovation/judgmentcall.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dcass
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/403174/>403174</a>

**Comment by EdPrice-MSFT** [comment]
This is being updated. Thanks.

**Comment by TimShererWithAquent** [comment]
The author may have had something in mind for the awards, but this seems to be a distraction. Removed the reference to awards.
