### ISSUE TITLE
Are Azure Container Instances and Kubernetes swapped in the picture. 

### ISSUE THREAD

**Issue by badrikannan1** [MicrosoftDocs/architecture-center#2744]
[Enter feedback here]

Azure Kubernetes Service was originally the solution proposed when one has to support full-fledged orchestration. Has that changed recently? Also, for microservices with short lived, event driven processes, Azure Functions were proposed. Has that changed recently with the Azure App Service being proposed for the microservices architecture even though Azure Functions are still proposed for short lived, event driven processes. There is definitely some confusion here compared to what was proposed before this latest version of the decision tree came through. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/403265/>403265</a>

**Comment by eric-camplin** [comment]
while looking at this issue please review the flow chart pointing to AKS for both **Yes** and **No** paths for "needs Full-fleged orchestration" 
![image](https://user-images.githubusercontent.com/12022944/113210439-13e4ac80-9229-11eb-8ad7-ae976e116b6b.png)

**Comment by badrikannan1** [comment]
Are we essentially saying that when it is a migrate and we need full orchestration, one should use AKS while if it is a brand new build with a similar set up, one should use ACI and not AKS. I don't understand why a migrate vs a build brand new makes a difference there. I just want to make sure I get the recommendations correct here.

**Comment by ckittel** [comment]
I think one good place to start would be with this:

![image](https://user-images.githubusercontent.com/671075/113913339-d2607e00-97a1-11eb-8924-cc0dd397492d.png)

I know the "No" -> "Yes" will be a little weird, but that's really for the other flow.  You'd answer the question the same both times you're asked it.

**Comment by ckittel** [comment]
The article has been updated to incorporate feedback like the items identified here, including Azure Functions for event driven work, and the "full-fledged orchestration" leading you to the same destination.  This chart of course has no context to your situation, outside of what it provides, so it can only be coarse grained, "it depends" can't make itself present here -- even though it often does.
