### ISSUE TITLE
Azure Batch

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/architecture-center#2746]
Can you include guidance for Azure Batch as well?

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/403385/>403385</a>

**Comment by david-stanford** [comment]
Hi, can you let us know where you'd like guidance for Azure batch? Is there a specific article you are interested in having it on? There are product docs for Azure Batch available here: https://docs.microsoft.com/en-us/azure/batch/batch-technical-overview.

**Comment by pisees** [comment]
I was referring to this article David: https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/batch-processing
