### ISSUE TITLE
OS disk caching can be disabled - data disk still needed?

### ISSUE THREAD

**Issue by MatthewGy** [MicrosoftDocs/architecture-center#2747]
"Create a separate virtual data disk for storing the database, logs, and sysvol folder for Active Directory. Do not store these items on the same disk as the operating system. By default, data disks that are attached to a VM use write-through caching. However, this form of caching can conflict with the requirements of AD DS. For this reason, set the Host Cache Preference setting on the data disk to None."
Shouldn't this the be revised? OS disks can have caching disabled now in Azure so having a data disk is not necessary...?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#vm-recommendations)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/403494/>403494</a>

**Comment by Mike-Crowley** [comment]
I would suspect this is now simply a question of capacity and IOPS. I would imagine most customers would be fine with their DC on Premium storage and the NTDS database, etc on the C: drive. It would be good to get official guidance to this effect.

**Comment by v-fearam** [comment]
Hi @MatthewGy
Thanks for your feedback. At this time we're going to keep the article as-is to maintain alignment with the AD-DS documentation at: https://learn.microsoft.com/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm. While it is true that you could meet the consistency requirements for the domain controller by disabling host caching on the OS disk, this would impact performance of the operating system disk. You could over-spec the performance of the OS disk to balance this out, but this would be an untested pattern. By keeping the AD-DS files off the OS Disk, we can manage the cache settings for consistency, and disk performance provisioning, separately.
#please-close
