### ISSUE TITLE
Link pointing to wrong page

### ISSUE THREAD

**Issue by jimhackney** [MicrosoftDocs/architecture-center#2748]
In the second paragraph of the "Working with CSV and JSON data in Azure" section of the web page found at the link https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/csv-and-json, there is an "import CSV files" link.  Instead of taking you to a page about importing CSV files it takes you to the "Import JSON documents into SQL Server" page.(https://docs.microsoft.com/en-us/sql/relational-databases/json/import-json-documents-into-sql-server?view=sql-server-ver15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ac957c-9568-b3f0-d79e-72a36439bee9
* Version Independent ID: e89413dd-8815-3d38-d7f0-6a6d0268db1e
* Content: [Processing CSV and JSON files - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/csv-and-json)
* Content Source: [docs/data-guide/scenarios/csv-and-json.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/csv-and-json.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/403563/>403563</a>

**Comment by TimShererWithAquent** [comment]
Removed link.
