### ISSUE TITLE
Deploy DCs between availability Zones

### ISSUE THREAD

**Issue by jurelab** [MicrosoftDocs/architecture-center#2750]
In the part: "Deploy at least two VMs running AD DS as domain controllers and add them to an availability set."=>If possible Availability Zone option should be advised..

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/404152/>404152</a>

**Comment by v-fearam** [comment]
Hi @jurelab 
Sorry for the delay.
It was already changed on VM Recomendacions
"Deploy at least two VMs running AD DS as domain controllers and add them to different [Availability Zones](https://learn.microsoft.com/en-us/azure/availability-zones/az-overview). If not available in the region, deploy in an [Availability Set](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-availability-sets)."

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
