### ISSUE TITLE
Link to: https://www.proxy-sniffer.com/en/doc/LoadTestKnowHowEN.pdf gets the Chrome scary warning to do with expired SSL cert. Think this company has been acquired?

### ISSUE THREAD

**Issue by ciarancolgan** [MicrosoftDocs/architecture-center#2751]
[Enter feedback here]
See title for broken-ish link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea464ce1-0548-e4d4-2160-a3829c959b93
* Version Independent ID: 9128607b-d441-cf29-b68b-55936d549690
* Content: [JMeter implementation reference for load testing pipeline solution - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/banking/jmeter-load-testing-pipeline-implementation-reference)
* Content Source: [docs/example-scenario/banking/jmeter-load-testing-pipeline-implementation-reference.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/banking/jmeter-load-testing-pipeline-implementation-reference.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/404156/>404156</a>

**Comment by ckittel** [comment]
Thanks for the report @ciarancolgan -- an updated URL has been found and the article will be published with it in the next 48 hours.
