### ISSUE TITLE
Front Door vs App Gateway

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/architecture-center#2753]
My understanding is that Front Door has all the load-balancing capabilities of App Gateway. Why couldn't you just use Front Door to do all the work and remove the need for a local app gateway?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d54fc4b-e066-f455-c6c4-34448a61bb50
* Version Independent ID: 3736237c-ae6a-18b8-aab1-d9c9ad031231
* Content: [Multitenant SaaS on Azure - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/example-scenario/multi-saas/multitenant-saas)
* Content Source: [docs/example-scenario/multi-saas/multitenant-saas.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/multi-saas/multitenant-saas.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by ram-msft** [comment]
@thommck Thanks for the question. We are investigating the issue and will update you shortly.

**Comment by v-fearam** [comment]
Hi @thommck 
Sorry for the delay. 

Azure Front Door is able to do Load Balancing and apply Web Application Firewall. It is possible to go directly to a set of app services and it would work. However, that solution is not as secure as the architecture which is proposed. Front Door is a global resource which is not able to be part of a Vnet.

Each region is inside a Virtual Network, and the traffic inside is private. The idea is to keep all app services private, and have only one entry point to the virtual network (only one Public IP). That entry point is the Application Gateway with WAF activated, so the ingress traffic to the private network is secure. 

For more details see: https://learn.microsoft.com/azure/frontdoor/front-door-faq#when-should-we-deploy-an-application-gateway-behind-front-door-

I will close the ticket, but feel free to re-open if you additional clarification is needed.

**Comment by hallihan** [comment]
#please-close
