### ISSUE TITLE
Missing reference to VGen2 Storage Account

### ISSUE THREAD

**Issue by gorankuk** [MicrosoftDocs/architecture-center#2754]
this is dated page since it is referencing only Blob Storage and Data Lake Gen1. With introduction of VGen 2 storage account it will be important to distinguish what use cases are a good fit for BlobStorage, Vgen 2 (specilay knowing that they support most of blob features - since it is merged ) and also to confirm if Data Lake Gen 1 is still playing any role or if it will be fully replaced with new architecture of VGen2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4931350d-0c12-00b2-64a8-112f67aba3f2
* Version Independent ID: eed89d06-7676-30e1-b801-2f67a09856f0
* Content: [Choosing a data storage technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-storage)
* Content Source: [docs/data-guide/technology-choices/data-storage.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/data-storage.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/404766/>404766</a>

**Comment by ckittel** [comment]
@josearper - Can the Data ARB please update this article accordingly?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24285 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
