### ISSUE TITLE
Couple of possible mistakes in the 1st flowchart on the page

### ISSUE THREAD

**Issue by krsanty** [MicrosoftDocs/architecture-center#2757]
On the right most side, pointers to couple of boxes ("Container Instances" and "App Service") should not be Yes. 
Architecturally, shouldn't it be connected by "No"?
Isn't this the right way to do:
1. Microservice architecture? ->No-> App Service
2. Needs full fledged orchestration? ->No->Container instances

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/405348/>405348</a>

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by jocontr** [comment]
Diagram has already been updated. Thank you.
