### ISSUE TITLE
Incorrect guidance

### ISSUE THREAD

**Issue by sideeksh** [MicrosoftDocs/architecture-center#2758]
Hi team

There is a note in this doc which states the following:
Availability Zones support high availability but are not an effective disaster recovery (DR) strategy. The distance between zones is too close. Typical DR regions should be at least 100 miles away from the primary region.

There are 2 issues with this:
1. It is impossible for our customers to know how many miles away our datacenters are from each other
2. We actually offer a inter-zone disaster recovery service for this use case. Please see https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-how-to-enable-zone-to-zone-disaster-recovery#using-availability-zones-for-disaster-recovery

Can we please remove or update this note? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009774ee-d1e4-1d7b-e53f-ecbcc4d56e5d
* Version Independent ID: d14a99bb-b4d5-21ce-dd72-5759a8284c42
* Content: [SAP S/4HANA in Linux on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/sap-s4hana?source=docs#deploy-virtual-machines-across-availability-zones)
* Content Source: [docs/reference-architectures/sap/sap-s4hana.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/sap-s4hana.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/405416/>405416</a>

**Comment by TimShererWithAquent** [comment]
Revisions made.
