### ISSUE TITLE
Possibly wrong category for scenario

### ISSUE THREAD

**Issue by anickelbagoffunk** [MicrosoftDocs/architecture-center#2759]
Should this scenario really be categorized/organized as "DevOps"? Perhaps Web or Mobile would be more fitting?

/C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cc3d81-d33a-bc9b-ab91-d7c4c8e26a95
* Version Independent ID: d3ce3924-f004-a61a-867c-b81fae8cf5f9
* Content: [Sharing location in real time using low-cost serverless Azure services - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/signalr/)
* Content Source: [docs/example-scenario/signalr/index.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/signalr/index.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @talhanaveed
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/406056/>406056</a>

**Comment by jocontr** [comment]
Thank you
