### ISSUE TITLE
Availability Options for AD DS is Availability Zones also supported

### ISSUE THREAD

**Issue by cbgermany** [MicrosoftDocs/architecture-center#2760]
[Enter feedback here]

Under the section Availability Considerations, the article states that the Domain Controllers should be placed in an Availability Set.  My question is whether Availability Zones are also supported, it is just the article needs updating or is there another technical reason for stating Availability Sets.  The region I would be looking to deploy the Domain Controllers does support Availability Zones.  Feedback greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/406077/>406077</a>

**Comment by v-fearam** [comment]
Hi @cbgermany


Sorry for the delay. 


In the article I found:


* [VM Recommendations sections]([https://learn.microsoft.com/azure/architecture/reference-architectures/identity/adds-extend-domain#vm-recommendations](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#vm-recommendations)) said “Deploy at least two VMs running AD DS as domain controllers and add them to different Availability Zones. If not available in the region, deploy in an Availability Set.”


* [Availability considerations](https://learn.microsoft.com/azure/architecture/reference-architectures/identity/adds-extend-domain#availability-considerations) said “Deploy the VMs running AD DS into at least two Availability Zones. If not available in the region, use availability set.”


If the region you would be looking to deploy the Domain Controllers does support Availability Zones, you should use it.


I think the document was updated between your comment time and now.


I will close the ticket, but feel free to re-open if additional clarification is needed.
