### ISSUE TITLE
mistake in flow chart

### ISSUE THREAD

**Issue by Nishco** [MicrosoftDocs/architecture-center#2762]
Selection flow chart has error
Selecting full flagged orchestration >> NO >> full flagged orchestration >> YES ?

![image](https://user-images.githubusercontent.com/56907911/114114270-e207d000-9923-11eb-9512-71c69e41011a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**
![image](https://user-images.githubusercontent.com/56907911/114114278-e633ed80-9923-11eb-8a42-d40e41d6536f.png)
![Screenshot 2021-04-09 111025](https://user-images.githubusercontent.com/56907911/114114519-58a4cd80-9924-11eb-861e-b25b2418d702.jpg)
![Screenshot 2021-04-09 111025](https://user-images.githubusercontent.com/56907911/114114527-5e021800-9924-11eb-801e-ac896a199025.jpg)

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/407841/>407841</a>

**Comment by jocontr** [comment]
Diagram has been updated. Thank you.
