### ISSUE TITLE
Request for cirrent implementation guide

### ISSUE THREAD

**Issue by 234sauravkumar** [MicrosoftDocs/architecture-center#2763]
I was trying to implement this.but it seems to be very old .Many things have changed. Could you please update to a recent guide .

Thanks ,
Saurav

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/408050/>408050</a>

**Comment by RohitMungi-MSFT** [comment]
@234sauravkumar Could you please post the link to the document you are referring to?

**Comment by 234sauravkumar** [comment]
Hi Rohit,
https://github.com/Azure/azure-ai-personalized-offers/tree/master/Manual%20Deployment%20Guide 
I have attached the link. In this the azure function app ui has changed. Its asks for the deployment or selection of programming  language which i not mentioned. I am not able to set it up. Kindly help in this.

Thanks,
Saurav

**Comment by RohitMungi-MSFT** [comment]
@234sauravkumar I think this refers to another Azure repo and not Azure docs where this issue is raised. It also looks like this repo is old and not maintained. Looking at the code files for azure function it looks like the language is C#.

**Comment by neilpeterson** [comment]
We have remove the reference to this repo from the Azure Architecture Center.
