### ISSUE TITLE
Create a paragraph dealing specifically with empty sets

### ISSUE THREAD

**Issue by brunowildhagen** [MicrosoftDocs/architecture-center#2764]
Hi,

My team is using the [api-design](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design) doc as a guideline to build our APIs and we had some disagreements on how to deal with empty sets, I think the documentation could be more clear about this specific scenario.

[This](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#910-empty-results) microsoft doc says that the proper response is 200 with the metadata and an empty set in the body, which I think is the way to do it as well, but the docs leave it up to interpretation, and [this](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#get-methods) section makes it a little more confusing.

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad651d6a-f8d8-2050-e7a7-adbae7326112
* Version Independent ID: 4fddd724-cabd-8623-7692-857088c1dccb
* Content: [API design guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design)
* Content Source: [docs/best-practices/api-design.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/api-design.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/408113/>408113</a>

**Comment by TimShererWithAquent** [comment]
Paragraph added.
