### ISSUE TITLE
ADLS information is outdated

### ISSUE THREAD

**Issue by Dirkgu01** [MicrosoftDocs/architecture-center#2767]
[Enter feedback here]
A paragraph on Data Lake Store references Data lake Analytics, which is no longer supported. 

the following text is also confusing: 'You may consider using this as an alternative to Azure Storage when your individual or combined file sizes exceed that which is supported by Azure Storage.'

Azure data lake storage v2 requires an azure storage account, so how can it be an alternative for a storage account?

The ADLS paragraphs also mixes the names 'Data Lake' (the concept) and 'Data Lake Store' , but does not use the official name 'Data Lake Storage', which adds to the confusion.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4931350d-0c12-00b2-64a8-112f67aba3f2
* Version Independent ID: eed89d06-7676-30e1-b801-2f67a09856f0
* Content: [Choosing a data storage technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-storage)
* Content Source: [docs/data-guide/technology-choices/data-storage.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/data-storage.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/409138/>409138</a>

**Comment by Zimmergren** [comment]
We reviewed this article, which is targeting Azure Data Lake Storage Gen1. We've made updates to reflect this and make sure it's clearer in the article. The article doesn't cover Azure Data Lake Storage Gen2 currently.

#please-close
