### ISSUE TITLE
Don’t use Microsoft product icons to represent your product or service

### ISSUE THREAD

**Issue by Scharnhusen** [MicrosoftDocs/architecture-center#2768]
Hi there, 
is there any source for an Azure Icon set which can be used for product presentational purpose? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/409769/>409769</a>

**Comment by JasRobe** [comment]
@Scharnhusen I believe the intent of the statement is that you should not use as specific Azure Service icon to represent your solution in part or in whole.   If you use the azure service icon to represent that specific azure service in the diagram, that is acceptable.  Does that help clarify?

**Comment by JasRobe** [comment]
closing as there has been no response.
