### ISSUE TITLE
Please add whenever IPv6 and Websocket can be used for App Services

### ISSUE THREAD

**Issue by grzchr15** [MicrosoftDocs/architecture-center#2771]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/411428/>411428</a>

**Comment by v-fearam** [comment]
Hi @grzchr15
Sorry for the delay
Load Balancer supports [ipv6](https://learn.microsoft.com/azure/load-balancer/load-balancer-ipv6-overview)
 
[IPv6 is still not supported on App Service]([https://learn.microsoft.com/answers/questions/676236/ipv6-for-app-services.html](https://learn.microsoft.com/en-us/answers/questions/676236/ipv6-for-app-services.html))
[WebSocket](https://en.wikipedia.org/wiki/WebSocket)[RFC-6455](https://www.rfc-editor.org/rfc/rfc6455) is a protocol that enables two-way persistent communication channels over TCP connections. It doesn't matter which ip version you are using. WebSocket is supported on [.Net](https://learn.microsoft.com/aspnet/core/fundamentals/websockets)
 
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
