### ISSUE TITLE
Clarifications about requesting Mesh permissions in multi-tenant environments.

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/architecture-center#2773]
Content deleted, moving to another location.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcd7d60-173f-66f6-8fe9-d8a188782d44
* Version Independent ID: 1729ad46-26a2-b1fb-5999-225888998449
* Content: [Authorization in multitenant applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/authorize)
* Content Source: [docs/multitenant-identity/authorize.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/authorize.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/411904/>411904</a>

**Comment by sloh-ms** [comment]
Moving content to another location, please ignore this.
