### ISSUE TITLE
New Azure Databricks logo

### ISSUE THREAD

**Issue by clintonwford** [MicrosoftDocs/architecture-center#2775]
Hi, could you help me update the Azure Databricks logo on the [Real Time Analytics on Big Data Architecture](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics) reference architecture diagram? I have created an [updated architecture diagram image](https://drive.google.com/file/d/1ij7lT4BKzMrOit3MlyGH7ySA1J6yWoL_/), using the [new SVG Databricks icon](https://drive.google.com/file/d/13z9cECUZsyu8ZjWzHErUZbAhuO_jXlUK/).

Thank you!

Clinton Ford
Principal Product Marketing Manager
Databricks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4bb287-fa40-af1d-0af9-e8bc30cfb33e
* Version Independent ID: 12ab4c06-2e95-bb73-f62a-2d1eb79bc735
* Content: [Real Time Analytics on Big Data Architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics)
* Content Source: [docs/solution-ideas/articles/real-time-analytics.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/real-time-analytics.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/412789/>412789</a>

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
This looks like it has been completed and could be closed.

**Comment by jocontr** [comment]
Solution ideas has been updated.
