### ISSUE TITLE
This article is missing thumbnail in Browse experience

### ISSUE THREAD

**Issue by ckittel** [MicrosoftDocs/architecture-center#2776]
![image](https://user-images.githubusercontent.com/671075/115448862-d055e080-a1df-11eb-9de0-05bc80c2c8ad.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd458c97-751a-2ea5-af06-771defec74f6
* Version Independent ID: 1a69b107-54d5-b910-c7ea-011edc380dd6
* Content: [Clinical insights with Microsoft Cloud for Healthcare - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/mch-health/medical-data-insights)
* Content Source: [docs/example-scenario/mch-health/medical-data-insights.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/mch-health/medical-data-insights.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/413309/>413309</a>

**Comment by ckittel** [comment]
Fixed now, thanks!

**Comment by jocontr** [comment]
Thumbnail is present as of this date. Thanks for reporting the issue.
