### ISSUE TITLE
A lot of Intune icons are missing, can these be added?

### ISSUE THREAD

**Issue by durrante** [MicrosoftDocs/architecture-center#2777]
As the title suggests, can the Intune icons be added to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/413974/>413974</a>

**Comment by FranklyFrivolous** [comment]
Just curious if MS is going to link up with this guy. 
His stencil range is updated by scrips routinely, grabs the SVG from Azure icons then generates the icons. 

[https://github.com/David-Summers/Azure-Design](url)

Scales, anchor points, and vision index searching work for his stencils.

**Comment by Zimmergren** [comment]
The current version of the Azure icons pack contains eighteen updated Intune icons. 
If you believe there are more missing icons, please create a new ticket and specify more details about the required icons. Thanks!

#please-close
