### ISSUE TITLE
Xamarin/Blazor  serverless client app with Cosmos DB

### ISSUE THREAD

**Issue by AnuragBhv** [MicrosoftDocs/architecture-center#2779]
**Ideas for Cosmos DB serverless Sample App**
1) A Client App using a Azure Cosmos DB with through Function App with/without API management.
2) A Client App directly using Azure Cosmos DB and for security it uses Azure Identity for token exchange.

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/414433/>414433</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24117 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
