### ISSUE TITLE
Several Security and Compliance Blueprints Link is dead

### ISSUE THREAD

**Issue by markmassad** [MicrosoftDocs/architecture-center#2780]
[Enter feedback here]

Several Security and Compliance Blueprints link goes to a broken page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fe47949-15a1-6073-0ac7-91a072ee4ff5
* Version Independent ID: f670a787-e68f-1216-8194-1472510c4525
* Content: [Governance, risk, and compliance in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/Security/governance#increase-automation-with-azure-blueprints)
* Content Source: [docs/framework/security/governance.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/governance.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/414813/>414813</a>

**Comment by BryanTrach-MSFT** [comment]
@markmassad Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by neilpeterson** [comment]
Thanks, we have updated the link.
