### ISSUE TITLE
Code examples and Sample Solution template

### ISSUE THREAD

**Issue by arashaga** [MicrosoftDocs/architecture-center#2782]
Code examples and Sample Solution template would be very helpful to extend this to other areas besides power and energy forecasting.

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/415428/>415428</a>

**Comment by JasRobe** [comment]
@arashaga Could you help share which article specifically you are referring to with this issue?

**Comment by jocontr** [comment]
Request will be considered. Thank you
