### ISSUE TITLE
Confirm if MbPS should read MBps 

### ISSUE THREAD

**Issue by RMITBLOG** [MicrosoftDocs/architecture-center#2783]
[Enter feedback here]

Hi Microsoft team. 

Under the following section of the document https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix?source=docs#performance-requirements

_**"For network bandwidth, depending on the type of utilization it is recommended to plan between 5 and 30 MbPS per user."**_

Should MbPS read MBps

It's causing confusion, this is why I'm seeking clarification. 

Best regards,

Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix?source=docs)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/416619/>416619</a>

**Comment by ckittel** [comment]
Talked it over with PG, and the number of variables that go into this range do not warrant having specificity (could cause more harm than good.)  We've updated the guidance (should go live by Tuesday), to change how that recommendation was presented.  Also, we're hoping to refresh this article, completely, by the end of the calendar year.  Thanks.  Have a great weekend.
