### ISSUE TITLE
Consolidation across other pages

### ISSUE THREAD

**Issue by santhoshbomma9** [MicrosoftDocs/architecture-center#2784]
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/data-options#identify-data-services-requirements
https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree

Should we make this two refer the same thing, I see go things in each we can be merged into one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88559925-9b9e-d9b3-ddb6-08306692c17b
* Version Independent ID: a25055cb-7cfe-28a0-1c66-06172c037128
* Content: [Data store decision tree - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)
* Content Source: [docs/guide/technology-choices/data-store-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/416641/>416641</a>

**Comment by santhoshbomma9** [comment]
Great, thank you!

**Comment by JasRobe** [comment]
Reopening this bug until the content has been updated to reflect the suggestion

**Comment by jocontr** [comment]
Thank you for your feedback. The team has taken this item as a feature request for further evaluation.
#please-close
