### ISSUE TITLE
Download a Visio file of this architecture points to wrong visio file

### ISSUE THREAD

**Issue by AliManouchehri** [MicrosoftDocs/architecture-center#2785]
[Enter feedback here]

Hi,

I would like to inform you that when you click on the download of the visio file for express route page (Extend an on-premises network using ExpressRoute), you get a wrong diagram, the one for Extend an on-premises network using VPN.

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/vpn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Extend an on-premises network using ExpressRoute - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/416941/>416941</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AliManouchehri The downloaded file actually contains 3 Visio diagrams: VPN, ExpressRoute and ER with VPN fallback, as in the screenshot below:

![image](https://user-images.githubusercontent.com/44050820/116188087-63dd6300-a744-11eb-91fd-cf1f29d2f936.png)

Please let us know if you see different.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AliManouchehri Any further update here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AliManouchehri We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by AliManouchehri** [comment]
My apologies for writing a late response.  Yes, the problem was between the chair and keyboard.  I noticed the separate tabs, so all is good.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@AliManouchehri Thanks for the confirmation.
