### ISSUE TITLE
What about backend Database decomposition?

### ISSUE THREAD

**Issue by pjainan** [MicrosoftDocs/architecture-center#2786]
After applying the Strangler pattern and decomposing the monolith bounding context to microservices, it is still shown that they are still accessing the same database source. Please suggest what is the reason? Also, how to decompose database for individual domain microservice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3d720e-441b-16f6-a73d-d7a66f81fa32
* Version Independent ID: 8a923182-0020-db36-e896-0cf71d277c67
* Content: [Monoliths to microservices using domain-driven design - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/migrate-monolith)
* Content Source: [docs/microservices/migrate-monolith.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/migrate-monolith.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @lavann
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/417024/>417024</a>
