### ISSUE TITLE
Pictures are TOO small!!!

### ISSUE THREAD

**Issue by p-bojkowski** [MicrosoftDocs/architecture-center#2787]
Could you PLEASE post the images in all articles so that you can also zoom?
Smaller always goes lately ;)
Pictures are TOO small!!! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c28146-b2a9-f734-f0f6-b1227296d7a3
* Version Independent ID: 709b2d47-6f11-88d9-6197-f0c5ca18af64
* Content: [Mining equipment monitoring - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/monitor-mining-equipment)
* Content Source: [docs/solution-ideas/articles/monitor-mining-equipment.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/monitor-mining-equipment.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @falloutxAY
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/417046/>417046</a>

**Comment by jocontr** [comment]
Zoom functionality feature is present on the lower right corner of the image. Thank you
