### ISSUE TITLE
Incorrect link for the ExpressRoute Visio

### ISSUE THREAD

**Issue by monikamac** [MicrosoftDocs/architecture-center#2789]
[The download Visio link download a different image than the showed on the page, it is currently downloading the hybrid one, not the express route one]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Extend an on-premises network using ExpressRoute - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/417798/>417798</a>

**Comment by JasRobe** [comment]
@monikamac the visio file that is linked has multiple tabs, you can find the architecture you are looking for on one of the other tabs  (the visio file itself has a default tab set).

Does that address your issue?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@monikamac The downloaded file actually contains 3 Visio diagrams: VPN, ExpressRoute and ER with VPN fallback, as in the screenshot below:

![image](https://user-images.githubusercontent.com/44050820/116188087-63dd6300-a744-11eb-91fd-cf1f29d2f936.png)

Please let us know if you see different.

**Comment by monikamac** [comment]
Thanks for the fast response. I see the tabs.

Best
Monika

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BhargaviAnnadevara-MSFT** [comment]
@monikamac Thanks for the confirmation. We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
