### ISSUE TITLE
Link for OpenFoam is missing (https://simulation.azure.com/casestudies/Team-182-ABB-UC-Final.pdf)

### ISSUE THREAD

**Issue by tekgnu** [MicrosoftDocs/architecture-center#2793]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing)
* Content Source: [docs/topics/high-performance-computing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/topics/high-performance-computing.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/418418/>418418</a>

**Comment by neilpeterson** [comment]
Thanks for the issue, a fix should publish shortly.
