### ISSUE TITLE
Diagram contains "Web Front End" instead of "Back End"

### ISSUE THREAD

**Issue by Hofls** [MicrosoftDocs/architecture-center#2797]
Logical diagram of Web-Queue-Worker contains "Web Front End" block. I think it should be "Back End" instead.

Reasoning: 
Let's say i have React on Frontend, Golang on Backend.
According to the diagram i should open connection to Database directly from Frontend(React). Doesn't sound good to me.
At the same time, connection to DB from Backend(Golang) is perfectly OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495b2ac1-3a9c-d1db-2b46-bbfbd0a4b538
* Version Independent ID: 2f6008fa-9b45-6ce1-13b5-74f82550f715
* Content: [Web-Queue-Worker architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/web-queue-worker)
* Content Source: [docs/guide/architecture-styles/web-queue-worker.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/web-queue-worker.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/419301/>419301</a>

**Comment by SaurabhSharma-MSFT** [comment]
@Hofls Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by Hofls** [comment]
Maybe diagram uses some alternative definition for "Front end", where it means "Server-side"?
But i am unable to find it. No matter where i look, i am finding only following definition:
Front end - client-side, UI/UX, Web-browser (HTML, CSS, JS, WebAssembly), etc

**Comment by v-fearam** [comment]
Hi @Hofls 

Sorry for the delay. 


Sorry for the confusion.  

Anyway, the last paragraph in the first section has an explanation:

 __The front end might consist of a web API. On the client side, the web API can be consumed by a single-page application that makes AJAX calls, or by a native client application.__

 It is web, uses http protocol, and it is the front end of a set of components behind scenes (queue, cache, database, etc). 

 

 I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
