### ISSUE TITLE
No reference to the Architecture Diagram visio file

### ISSUE THREAD

**Issue by lopezleandro03** [MicrosoftDocs/architecture-center#2799]
Other architecture diagrams allow downloading the visio file, this way the customer can make the required adjustements to reflect its own architecture.

Can this be added?

Thanks.

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/419509/>419509</a>

**Comment by JasRobe** [comment]
@lopezleandro03 is this a general request for all architecture diagrams, or is there a specific diagram you are looking at?

**Comment by lopezleandro03** [comment]
@JasRobe this request was in particular for this [diagram](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end) which I end up getting after reaching out to a MSFT consultant that I work with.

Having the source files available on all diagrams would be ideal, provides a good starting point! Would be nice if every diagram that is uploaded to the architecture center contains the source file.

**Comment by jocontr** [comment]
Fixed, Thank you
