### ISSUE TITLE
Not updated fully

### ISSUE THREAD

**Issue by dazfuller** [MicrosoftDocs/architecture-center#2800]
This page which used to include Azure Data Factory and Azure Databricks is still referencing Azure Databricks despite being updated to use Synapse for everything.

Also, the flow no longer makes sense as the connectivity from Power BI to Synapse Analytics Spark Pools doesn't exist, instead needing to use SQL pools. In that respect the 5th data flow should be removed or clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9a3b79-d9cd-ec55-2e4c-751e932a3dba
* Version Independent ID: 28c6b234-3905-ad1b-6a3f-6387a11f745f
* Content: [Architecture - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/enterprise-data-warehouse)
* Content Source: [docs/solution-ideas/articles/enterprise-data-warehouse.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/enterprise-data-warehouse.md)
* Service: **architecture-center**
* GitHub Login: @julieMSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/419519/>419519</a>

**Comment by julieMSFT** [comment]
Hi @dazfuller, thank you for contacting Microsoft and bring this to our attention. The fix is in process and should be visible later today. I will go ahead with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
