### ISSUE TITLE
We recommend you do not assign operations masters roles to the domain controllers deployed in Azure.

### ISSUE THREAD

**Issue by dooleydo** [MicrosoftDocs/architecture-center#2801]
Is there any rationale to support the statement "We recommend you do not assign operations masters roles to the domain controllers deployed in Azure."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/420767/>420767</a>

**Comment by Mike-Crowley** [comment]
What is the latest on this topic? FSMO holders are the most significant domain controllers. We need to understand why Microsoft is recommending that they stay on-premises.

**Comment by bwya77** [comment]
Any update on this? I see it's not included in the documentation anymore but I do not see the commit for it

**Comment by Mike-Crowley** [comment]
The sentence was removed by @jasonfritts  14 days ago:

https://github.com/MicrosoftDocs/architecture-center/commit/3d03390ca2cc08e6dc32086287e869d89aca962b

Jason, can you please elaborate on this change?

**Comment by jasonfritts** [comment]
@Mike-Crowley 
We confirmed with our Windows Active Directory SME teams that there are no issues with hosting FSMO master roles in Azure if the virtual machines themselves are properly managed.  The only recommendation that will remain in the docs that you should be aware of is the [Manageability considerations section](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#manageability-considerations) which discusses how to properly manage a domain controller hosted in Azure and some of the risks if they are improperly managed.

**Comment by Mike-Crowley** [comment]
Thanks. Somewhere I thought I read Azure did something that might stress the RID pool, but maybe I'm misremembering.

**Comment by jocontr** [comment]
Thank you.
