### ISSUE TITLE
AD FS Monitoring should include Azure AD Connect Health for AD FS

### ISSUE THREAD

**Issue by amasse3** [MicrosoftDocs/architecture-center#2802]
The AD FS Monitoring section references SCOM Management Pack. Azure AD Connect Health for AD FS is newer and a better choice for monitoring the AD FS service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67f48d5-1891-05be-e74f-d4003e9f8bea
* Version Independent ID: 5ac877a7-dce1-ca0a-4487-d0336a351581
* Content: [Extend on-premises AD FS to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adfs)
* Content Source: [docs/reference-architectures/identity/adfs.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adfs.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/420812/>420812</a>

**Comment by v-fearam** [comment]
#please-close
