### ISSUE TITLE
Is the Azure Load Balancer pinned or not..?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/architecture-center#2803]
Hi,
On your text you are saying:
"_...Because a zone-redundant load balancer is not pinned to a specific zone..._"
But when looking for the picture above of this, I'm understanding that LB is pinned to Zone 2. Even the arrows might give other indication.

If that is not the idea, then should you have similar grey box than Azure Application Gateway have:
![image](https://user-images.githubusercontent.com/43988151/117014977-00ca6e00-acfa-11eb-848c-6cb1c3a17abb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 363ebddf-0348-98e1-fd24-0eef444d383a
* Version Independent ID: e7da7820-925f-2092-c1a4-7a66db3f000d
* Content: [Multi-region load balancing with Traffic Manager and Application Gateway - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/high-availability/reference-architecture-traffic-manager-application-gateway)
* Content Source: [docs/high-availability/reference-architecture-traffic-manager-application-gateway.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/high-availability/reference-architecture-traffic-manager-application-gateway.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/420844/>420844</a>
