### ISSUE TITLE
Incorrect information.

### ISSUE THREAD

**Issue by PixelRobots** [MicrosoftDocs/architecture-center#2807]
You have a section that reads as:

Azure Load Balancer. An Azure Load Balancer is created when the NGINX ingress controller is deployed. The load balancer routes internet traffic to the ingress.

This is not true. An Azure Load Balancer is created when the AKS cluster is created. The NGINX Ingress will use it, but it will not create it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices#feedback)
* Content Source: [docs/reference-architectures/containers/aks-microservices/aks-microservices.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks-microservices/aks-microservices.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/421884/>421884</a>

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @PixelRobots, we have made the changes in the doc. We will now proceed to close this issue out, Please let us know if you have any further concerns.
