### ISSUE TITLE
Broken nav link "Secure access to IoT apps with Azure AD"

### ISSUE THREAD

**Issue by xbillyj** [MicrosoftDocs/architecture-center#2808]
Left nav broken link: Secure access to IoT apps with Azure AD
Used to point to this page (found on web archive): https://web.archive.org/web/20200825221210/https://docs.microsoft.com/en-us/azure/architecture/example-scenario/iot-aad/iot-aad

Please fix link (to original source on docs.microsoft.com obviously not web archive).

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/422162/>422162</a>

**Comment by xbillyj** [comment]
Adding interested parties for broken nav link.

**Comment by EdPrice-MSFT** [comment]
I'll get this one. Thanks!

**Comment by JanetCThomas** [comment]
It looks like this has been fixed.  Closing the issue. Thanks!
