### ISSUE TITLE
Data Lake Store Reference not really clear

### ISSUE THREAD

**Issue by gianlucadardia** [MicrosoftDocs/architecture-center#2810]
In the command line tools table "others", is not really clear "Copy to Data Lake Store" and "Copy from Data Lake Store" to what is referred. 
AzCopy is set to "Copy from Data Lake Store" -> "NO"

what does it means? you cannot read data from where? Data Lake Store is referred to third part Data Lake Store? someone could think that has not capabilities to copy from Azure Data Lake Storage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e037b-a226-62cf-6e2b-2af8783b7add
* Version Independent ID: c666597e-52ae-ee51-474a-c4dd3a63941b
* Content: [Choosing a data transfer technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer#key-selection-criteria)
* Content Source: [docs/data-guide/scenarios/data-transfer.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/data-transfer.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/423691/>423691</a>

**Comment by jocontr** [comment]
As stated today, the guidance shows the various capabilities and limitation of these tools given the different scenarios. Thank you.
