### ISSUE TITLE
Windows Defender has been renamed

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/architecture-center#2813]
If there is some other massive project to update all the places using the legacy name ignore this.

Current:
> Add exclusions for Windows Defender by using PowerShell

Proposed:
> Add exclusions for Microsoft Defender by using PowerShell

There is at least one other reference to Windows Defender in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/424598/>424598</a>

**Comment by JamesTran-MSFT** [comment]
@jonwbstr 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by neilpeterson** [comment]
Thanks for the issue, a fix will publish shortly.
