### ISSUE TITLE
Duplicated sentences

### ISSUE THREAD

**Issue by jaweekes** [MicrosoftDocs/architecture-center#2819]
One sentence has been duplicated.
The Windows N-tier application on Azure with SQL Server reference architecture uses DDoS Protection Standard because this option:

Uses adaptive tuning, based on the application's network traffic patterns, to detect threats.
Guarantees 100% SLA.
Can be cost effective. For example, during a DDoS attack, the first set of attacks cause the provisioned resources to scale out. For a resource such as a virtual machine scale set, 10 machines can grow to 100, increasing overall costs. With Standard protection, you don't have to worry about the cost of the scaled resources because Azure will provide the cost credit.
The Windows N-tier application on Azure with SQL Server reference architecture uses DDoS Protection Standard because this option:

Uses adaptive tuning, based on the application's network traffic patterns, to detect threats.
Guarantees 100% SLA.
Can be cost effective. For example, during a DDoS attack, the first set of attacks cause the provisioned resources to scale out. For a resource such as a virtual machine scale set, 10 machines can grow to 100, increasing overall costs. With Standard protection, you don't have to worry about the cost of the scaled resources because Azure will provide the cost credit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f78e284-fb28-8ac2-0ce6-590b48c74a45
* Version Independent ID: 3baed527-6023-bc26-d3f9-9fda0a43925e
* Content: [Network security and containment in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/network-security-containment)
* Content Source: [docs/framework/security/network-security-containment.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/network-security-containment.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/427545/>427545</a>

**Comment by NavtejSaini-MSFT** [comment]
@david-stanford Thank you for providing this information. @jaweekes Once the internal item is completed the changes will be applicable. For now we are going to close this feedback. Let us know if you need any further help.

**Comment by WilliamAntonRohm** [comment]
The article has been updated and is now live.

#please-close
