### ISSUE TITLE
Is there a set of dark mode icons ?

### ISSUE THREAD

**Issue by nikolaarnaudov** [MicrosoftDocs/architecture-center#2820]
[Enter feedback here]
I couldn't find a dark mode set of icons on the official page, link only shows one set. Is there a specific link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/427577/>427577</a>

**Comment by NavtejSaini-MSFT** [comment]
@david-stanford Thank you for confirming and providing this information. @nikolaarnaudov Thank you for the feedback. Once the bug is reviewed and action is taken the issue will be resolved.

**Comment by JasRobe** [comment]
There is not currently, I believe the icons should have transparent backgrounds, but there is not a dedicated set for darkmode.
