### ISSUE TITLE
Accessing Object Property through a Parameter as the property name

### ISSUE THREAD

**Issue by mlcooper** [MicrosoftDocs/architecture-center#2821]
I have read through this page a few times, but I am not sure that an important and powerful piece of functionality about accessing `Object` properties is discussed.  

I was looking to pass in a parameter to an ARM template to specify the `key` in the `key:value` pair in my object parameter.  I found that this is documented [on this page](https://stackoverflow.com/a/56469523).

Specifically the syntax I needed was:
```
"value": "[variables('objects')[parameters('propertyName')].color]"
```

I also had to modify the structure of my `key:value` object parameter and for every `key:value` pair I had to put it under a "heading" so that it could be called with this syntax.

If this isn't discussed specifically on this page, can it be added? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 928f1651-0e7e-9389-add5-120cf6ccf0dd
* Version Independent ID: 5399b529-92c2-ac3c-0f66-7cbcfef25c91
* Content: [Use an object as a parameter in an Azure Resource Manager template - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/azure-resource-manager/advanced-templates/objects-as-parameters)
* Content Source: [docs/guide/azure-resource-manager/advanced-templates/objects-as-parameters.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/azure-resource-manager/advanced-templates/objects-as-parameters.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/427600/>427600</a>
