### ISSUE TITLE
how to handle message from service bus queue via apim

### ISSUE THREAD

**Issue by manish-karn** [MicrosoftDocs/architecture-center#2823]
I don't know if there any solution of it, but here is my problem.

Working solution
1) I can push the queue from my application by ServiceBusClient and ServiceBusMessage
2) I can read the message via ServiceBusProcessor

but problems begin, if I want put service bus behind APIM, how can I use ServiceBusProcessor? please help me if there any work-around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e8312a-a2b2-c683-2bc5-ebadf37cfbfe
* Version Independent ID: 23ab5226-f35d-cb04-109d-a4e651785f8d
* Content: [Publisher-Subscriber pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/publisher-subscriber)
* Content Source: [docs/patterns/publisher-subscriber.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/publisher-subscriber.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/428100/>428100</a>

**Comment by jocontr** [comment]
@manish-karn each architecture and situation is unique. If you need support, please feel free to work with one of our local partners. Thank you
