### ISSUE TITLE
Azure firewall private IP mismatch

### ISSUE THREAD

**Issue by sakaldeepyadav** [MicrosoftDocs/architecture-center#2824]
Diagram under title 'Azure Firewall only' says private IP of firewall is **192.168.100.4** but in content (bullet point 2) says IP is **192.168.100.7**. It's a typo error and the same error is throughout the whole page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall and Application Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/428366/>428366</a>

**Comment by erjosito** [comment]
Hey @sakaldeepyadav , it is not a typo. As the document says:
"The IP address 192.168.100.7 is one of the instances the Azure Firewall service deploys under the covers, here with the front-end IP address 192.168.100.4"

**Comment by willam-gregoire** [comment]
The ApplicationGW has the same IP as the Firewall?

**Comment by sakaldeepyadav** [comment]
@erjosito I also saw that after raising the issue. As it is at the end of the topic so it looks like a typo error initially.
