### ISSUE TITLE
Need details

### ISSUE THREAD

**Issue by abymsft** [MicrosoftDocs/architecture-center#2826]
In the scenario covered for [this architecture](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video), would you please add/share more details on **how the mezzanine files are getting uploaded to blob storage**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video)
* Content Source: [docs/solution-ideas/articles/digital-media-video.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-video.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/429033/>429033</a>

**Comment by BryanLa** [comment]
@abymsft - apologies for the long delay, and thanks for your contribution.

The diagram has been updated and will republish around 10am Pacific today.

#please-close
