### ISSUE TITLE
Excalidraw Library for Cloud Design Patterns

### ISSUE THREAD

**Issue by michelcaradec** [MicrosoftDocs/architecture-center#2828]
Just to let you known that I created an [Excalidraw library](https://libraries.excalidraw.com/?sort=default#michelcaradec-cloud-design-patterns) inspired by these pages: <https://libraries.excalidraw.com/?sort=default#michelcaradec-cloud-design-patterns>.

Excellent documentation by the way!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [Cloud design patterns - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/)
* Content Source: [docs/patterns/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/index.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/431038/>431038</a>

**Comment by JasRobe** [comment]
Very cool work.  Thank you!
