### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by euchungmsft** [MicrosoftDocs/architecture-center#2830]
[Enter feedback here]

"Deploy LUIS resources using the Bot Framework LUIS CLI commands" link's broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46d80256-a174-3573-dc4b-2e20c0fb51b5
* Version Independent ID: 2ab0fffe-0a23-5d87-5a16-eb89cdeadb6b
* Content: [Build a chatbot for hotel booking - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/ai/commerce-chatbot)
* Content Source: [docs/example-scenario/ai/commerce-chatbot.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/ai/commerce-chatbot.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @iainfoulds
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/431675/>431675</a>

**Comment by neilpeterson** [comment]
Looks like this has been updated.
