### ISSUE TITLE
Better to have h3 included in the right-side TOC

### ISSUE THREAD

**Issue by cr1315** [MicrosoftDocs/architecture-center#2832]
#### feature request
Especially when reading `Technology choices for a message broker` section, I just thought it would be much better if h3 was also included in the right-side TOC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4503ec57-36ef-8040-b6de-5b5a1fea1590
* Version Independent ID: 509de364-6faf-e11e-41e0-c2f6cb8583f6
* Content: [Asynchronous messaging options in Azure - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/messaging#technology-choices-for-a-message-broker)
* Content Source: [docs/guide/technology-choices/messaging.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/messaging.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/432292/>432292</a>

**Comment by jocontr** [comment]
@cr1315 could you elaborate? Thank you.

**Comment by jocontr** [comment]
Thank you
