### ISSUE TITLE
Pricing - VMs need updating

### ISSUE THREAD

**Issue by nickmorgy** [MicrosoftDocs/architecture-center#2833]
I realise that the pricing is only to provide a rough guide, but we really should not still be proposing D_v2 or E_v3 VMs for SAP.  The D/Ea_v4 and D/Ed_v4 offer much better price performance and we should anyway promote new VM types, not ones that were superceded back in 2018.  We also now have M_v2 which again offers better performance.  Essentually all the VMs are obsolete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e700b9a2-8b1d-5d55-95ec-1bb123d2586a
* Version Independent ID: 7f4b8f89-a777-b03b-e0af-d3d890745088
* Content: [SAP deployment on Azure using an Oracle DB - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-production)
* Content Source: [docs/example-scenario/apps/sap-production.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/sap-production.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @DharmeshBhagat
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/432548/>432548</a>

**Comment by skabou** [comment]
It appears this has been addressed.  Please re-open with additional details if help is still needed.
