### ISSUE TITLE
No links to testing tools

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/architecture-center#2834]
The next button is even worse, testing tools, but doesn't list any testing tools.
https://docs.microsoft.com/en-us/learn/modules/load-test-web-app-azure-devop doesn't work as the tool has been retired for a long time.

I've used Apache JMeter years ago, but some docs on load testing would help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50729096-f717-225d-e37e-bc7af2be130d
* Version Independent ID: 57903353-57b5-3ed9-0b9d-59f85c5000c4
* Content: [Performance testing - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/scalability/performance-test)
* Content Source: [docs/framework/scalability/performance-test.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/scalability/performance-test.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/432777/>432777</a>

**Comment by v-aangie** [comment]
Sent Mayank an email to reassign.

**Comment by skabou** [comment]
The page in question has since been removed.  If assistance is still needed, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
