### ISSUE TITLE
medical

### ISSUE THREAD

**Issue by Shivahide** [MicrosoftDocs/architecture-center#2836]

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/432865/>432865</a>

**Comment by MayankBargali-MSFT** [comment]
@Shivahide Can you provide more information on what document you are following and the issue that you have observed.

**Comment by MayankBargali-MSFT** [comment]
@Shivahide As there was no response. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
