### ISSUE TITLE
SAP On Azure Reference Architecture : Standard Load Balancer missing in DR region.

### ISSUE THREAD

**Issue by jitandrasngh** [MicrosoftDocs/architecture-center#2837]
[Enter feedback here]
In general, we always have a Standard Load Balancer in the DR region for the DB node. On the reference architecture, Standard Load Balancers for (A)SCS, Web-Dispatcher & DB is missing as Standard Load Balancer cannot be replicated to DR using ASR.

Many thanks
Jitendra Singh

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9961de25-4a65-ef77-079e-cf0359ec5857
* Version Independent ID: 7b9bb7e7-ef88-a37f-5ca0-5f8a07f0f9d6
* Content: [Run SAP NetWeaver in Windows on Azure - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/reference-architectures/sap/sap-netweaver)
* Content Source: [docs/reference-architectures/sap/sap-netweaver.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/sap-netweaver.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/433277/>433277</a>

**Comment by v-fearam** [comment]
Hi @jitandrasngh


Sorry for the delay. 
The document has changed a lot since the issue was reported. Moreover, the document is not in the same location as when the issue was created.


I will close the ticket, but feel free to open a new one if you still have concerns.

#please-close
