### ISSUE TITLE
IOT section relation to lamda and kappa architecture

### ISSUE THREAD

**Issue by DataOx** [MicrosoftDocs/architecture-center#2838]
[Enter feedback here]

Please provide more details how the IOT section work with kappa and lamda architecture. When and how to represent them in the IOT scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953d7d0d-651f-a566-1d28-6946c824e1ae
* Version Independent ID: 8f5b4264-dcc9-ad28-36fe-45463d15f52a
* Content: [Big data architectures - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/)
* Content Source: [docs/data-guide/big-data/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/big-data/index.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/433513/>433513</a>

**Comment by EdPrice-MSFT** [comment]
UPDATE: The IoT Architecture Council is discussing this topic. Thank you!

You can find our content at http://aka.ms/IoTArchitecture
