### ISSUE TITLE
Group Policies not applicable for Linux VM's

### ISSUE THREAD

**Issue by karlgots** [MicrosoftDocs/architecture-center#2839]
Currently, the page recommends to "Use Group Policy settings on the VM to enable automatic system updates."

Group Policy settings are a feature of Windows, and as such not available for Linux. I would suggest to remove the specific suggestion, and to provide recommended auto-patching instructions for the supported Linux distributions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af3a0e6-6629-3044-4bdc-4f73a6f77861
* Version Independent ID: a93c0dc1-678d-2319-d850-ca3dca213b74
* Content: [Run a Linux VM on Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/linux-vm)
* Content Source: [docs/reference-architectures/n-tier/linux-vm.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/n-tier/linux-vm.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/434017/>434017</a>

**Comment by neilpeterson** [comment]
Thanks for the issue, a fix should publish shortly.
