### ISSUE TITLE
Feedback for Predictive Maintenance

### ISSUE THREAD

**Issue by Emmanuel-Eze** [MicrosoftDocs/architecture-center#2841]
I would like to see an article that shows more information on implementation details, pricing guidance, or code examples

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/434244/>434244</a>

**Comment by JasRobe** [comment]
@Emmanuel-Eze  could you be more specific with your request?

**Comment by JasRobe** [comment]
close due to no reply.
