### ISSUE TITLE
The pre/post script in architect image doesn't work like that

### ISSUE THREAD

**Issue by DuHuynh12** [MicrosoftDocs/architecture-center#2842]
[Enter feedback here]
Following the below document, the pre-script / post-script runs on Azure context, not locally.
https://docs.microsoft.com/en-us/azure/automation/update-management/pre-post-scripts

The architect images show that it runs on on-pre / Azure VM make misleading. 
there is a walk-around to able run pre/postscript on on-pre / Azure VM that uses pre/post-script to trigger another user hybrid worker group runbook, but it becomes more complex than this architect showing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d462e7b9-e8c2-7eb4-e288-f4bd0f348b78
* Version Independent ID: 976a3c4a-3d30-cc94-fcfa-352126ef970c
* Content: [Azure Automation Update Management - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-update-mgmt)
* Content Source: [docs/hybrid/azure-update-mgmt.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/azure-update-mgmt.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/434707/>434707</a>

**Comment by v-fearam** [comment]
Hi @DuHuynh12

Sorry for the delay. 

The document has changed a lot since the issue was reported and the architecture image updated. 
I will close the ticket, but feel free to open a new one if you still have concerns.

**Comment by v-fearam** [comment]
#please-close
