### ISSUE TITLE
Enchancement request

### ISSUE THREAD

**Issue by mmkmur** [MicrosoftDocs/architecture-center#2843]
[Enter feedback here]

Could you please provider direction on having this script without hybrid worker node for Windows and Linux ( For Cases where the systems that need Forensic remain in Azure itself.) 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7b130b0-a3fd-3fd7-900f-7bc900e23ef2
* Version Independent ID: 63bbdf46-1c0c-7d33-54d1-68cf2329c6cd
* Content: [Computer forensics Chain of Custody in Azure - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/forensics/)
* Content Source: [docs/example-scenario/forensics/index.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/forensics/index.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @simonesavi
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/434827/>434827</a>

**Comment by simonesavi** [comment]
@mmkmur you can execute the code within a Virtual machine with this configuration:

- VM must be hosted in the same subnet that grants access to the Storage account
- The VM must have a managed identity to which must be given grants to access the target VM's subscription

Inside this VM you can run the code without the 'if' at line 57

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
