### ISSUE TITLE
Could you expand video-on-demand pricing guidance?

### ISSUE THREAD

**Issue by tkane1azure** [MicrosoftDocs/architecture-center#2844]
Could you expand video-on-demand pricing guidance for comparison with AWS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video)
* Content Source: [docs/solution-ideas/articles/digital-media-video.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/digital-media-video.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/435234/>435234</a>

**Comment by JasRobe** [comment]
Is there a specific example you are referring to on this?

**Comment by JasRobe** [comment]
Close due to no response.
