### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nashahz** [MicrosoftDocs/architecture-center#2845]
[Enter feedback here]

"Synapse Mana private endpoints" link is misspelled, needs to be Synapse Manged Private endpoints 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cce4daf-bd8d-bd82-54a0-17e905a1c150
* Version Independent ID: 0dbc5354-031f-2d79-99da-68f9719e89d4
* Content: [Big data analytics with enterprise-grade security using Azure Synapse - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/big-data-analytics-enterprise-grade-security)
* Content Source: [docs/solution-ideas/articles/big-data-analytics-enterprise-grade-security.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/big-data-analytics-enterprise-grade-security.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **kikalyan**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/435864/>435864</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@nashahz Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@nashahz We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
