### ISSUE TITLE
"Azure Cosmos DB SQL API" is listed as a reference for section "Document Databases"

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/architecture-center#2847]
You may want to reconsider and link to a document-oriented API instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40cb85c-ee53-7b49-0622-bed8ebedea81
* Version Independent ID: 896e0838-dfd1-c442-414d-ad9ea6dc8f7d
* Content: [Understand data store models - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview#keyvalue-stores)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/436087/>436087</a>

**Comment by skabou** [comment]
It appears this was addressed some time ago.  If help is still needed, please feel free to re-open with additional details.
