### ISSUE TITLE
ADT icon in architecture diagram

### ISSUE THREAD

**Issue by jjadta** [MicrosoftDocs/architecture-center#2851]
Super small nit, but the architecture diagram is using an old icon for ADT. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 768f747a-0066-ede4-9373-5fa54ceb80cd
* Version Independent ID: c4d828a3-962e-2a44-7751-f871cd34eea0
* Content: [Facilities management powered by mixed reality and IoT - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/facilities-management-powered-by-mixed-reality-and-iot)
* Content Source: [docs/solution-ideas/articles/facilities-management-powered-by-mixed-reality-and-iot.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/facilities-management-powered-by-mixed-reality-and-iot.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/437851/>437851</a>

**Comment by Zimmergren** [comment]
The files are updated to reflect the latest ADT icons. 
#please-close
