### ISSUE TITLE
Need these in an easy to import format

### ISSUE THREAD

**Issue by dstinebaugh** [MicrosoftDocs/architecture-center#2852]
I should not have to add each icon manuall, then rename into a new stencil set in Visio. Azure and Visio have both been around long enough that these should: 
A. Already be an icon set in Visio nativly instead of having to download the zip file
B. At least have a stencil set available to ease the import of the hundreds of new icons into Visio.

Having to manually add and rename each icon is less than a productive use of my time and effort.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/437992/>437992</a>

**Comment by skabou** [comment]
It's unclear from this problem description which article this applies to, please re-open with additional details if help is still needed.
