### ISSUE TITLE
AWS AppMesh equivalent of OSM+Dapr

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#2853]
Service Fabric Mesh sound old, MSstrategy is now around Dapr+Open Service Mesh

Please update the docs accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ef54ba-28f9-bf3d-214d-d15ff2595a55
* Version Independent ID: 2c9fabc5-0288-ce98-a906-0dcc720f0c7f
* Content: [Comparing AWS and Azure compute services - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/compute)
* Content Source: [docs/aws-professional/compute.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/compute.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/438342/>438342</a>

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @ezYakaEagle442, 
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by TimShererWithAquent** [comment]
Updates made for this article.
