### ISSUE TITLE
Please add Azure Spring Cloud to this decision tree diagram

### ISSUE THREAD

**Issue by thoaingan** [MicrosoftDocs/architecture-center#2855]
Please add Azure Spring Cloud to this decision tree diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/438453/>438453</a>

**Comment by stephen-sumner** [comment]
@thoaingan - Thank you so much for the feedback. Sorry for the late closure. I believe we addressed this some time ago. The service is now Azure Spring Apps. It's represented there. I'm going to officially close this thread. 

Thank you again!
