### ISSUE TITLE
Patterns categorization issue ?

### ISSUE THREAD

**Issue by k110** [MicrosoftDocs/architecture-center#2859]
[Regarding [Patterns catalog](https://docs.microsoft.com/en-us/azure/architecture/patterns/#catalog-of-patterns), it seems that 2 patterns are missing in the page "Operational Excellence" : Geodes and Materialized View]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f922c02-5f01-a733-7553-8ef7d70bf78e
* Version Independent ID: 5db9d38a-fada-f3e3-3d63-21e27f4eaee0
* Content: [Operational Excellence patterns - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/devops-patterns)
* Content Source: [docs/framework/devops/devops-patterns.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/devops-patterns.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/438958/>438958</a>

**Comment by ckittel** [comment]
Thank you for your suggestion, @k110

We've included [Geodes](https://learn.microsoft.com/azure/architecture/patterns/geodes#when-to-use-this-pattern) in the Azure Well-Architected Framework's _Reliability_ patterns list for both [Availability](https://learn.microsoft.com/azure/architecture/framework/resiliency/reliability-patterns#availability) and [High availability](https://learn.microsoft.com/azure/architecture/framework/resiliency/reliability-patterns#high-availability).  But we probably won't put it in Operational Excellence as its primary use cases are not for automating or monitoring operations.

We've included [Materialized View](https://learn.microsoft.com/azure/architecture/patterns/materialized-view) in the Azure Well-Architected Framework's _Performance Efficiency_ [patterns list](https://learn.microsoft.com/azure/architecture/framework/scalability/performance-efficiency-patterns).  But we probably won't put it in Operational Excellence as its primary use cases are not for automating or monitoring operations.
