### ISSUE TITLE
Icon in Architecure schema

### ISSUE THREAD

**Issue by JGezels** [MicrosoftDocs/architecture-center#2860]
Hi

Just wondering, shouldn't the first load balancer (public facing behind traffic manager, with public IP) not be tagged as ELB (external) instead of ILB (internal)

regards

Jan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2442849c-9e87-56b2-dffd-5c8089e8132c
* Version Independent ID: 828da465-186b-f819-9575-ee51e8c83306
* Content: [Multi-tier web application built for HA/DR - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/multi-tier-app-disaster-recovery)
* Content Source: [docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @sujayt
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/438966/>438966</a>

**Comment by v-fearam** [comment]
Hi @PRMerger20 JGezels
Sorry for the delay.


I think there is a clear difference between the first load balancer (public facing behind traffic manager, with public IP)  and the others behind. The first label is only “Load Balancer”, and the others “Internal Load Balancer”. Maybe, It was modified after you reported.

![image](https://user-images.githubusercontent.com/62260324/211513965-09d979f5-c4bd-4d08-bee4-b69a41a85b05.png)

More information from [here](https://learn.microsoft.com/azure/load-balancer/load-balancer-overview)

A [public load balancer](https://learn.microsoft.com/en-us/azure/load-balancer/components#frontend-ip-configurations) can provide outbound connections for virtual machines (VMs) inside your virtual network. These connections are accomplished by translating their private IP addresses to public IP addresses. Public Load Balancers are used to load balance internet traffic to your VMs.

An [internal (or private) load balancer](https://learn.microsoft.com/en-us/azure/load-balancer/components#frontend-ip-configurations) is used where private IPs are needed at the frontend only. Internal load balancers are used to load balance traffic inside a virtual network. A load balancer frontend can be accessed from an on-premises network in a hybrid scenario.

  I will close the ticket, but feel free to re-open if additional clarification is needed.
