### ISSUE TITLE
Optimize Marketing with Machine Learning

### ISSUE THREAD

**Issue by Predictive-JT** [MicrosoftDocs/architecture-center#2863]
Hi there,

I'm interested in the solution of Optimize Marketing with Machine Learning (https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/optimize-marketing-with-machine-learning). It would be very helpful if you could me give more insides of this solution.

Kind regards,

Jerom
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e13d3bf-34e7-8c29-8281-65f5a2718bf1
* Version Independent ID: 1bb21591-5afb-612f-20b6-8a1c31d721f6
* Content: [Optimize Marketing with Machine Learning - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/optimize-marketing-with-machine-learning)
* Content Source: [docs/solution-ideas/articles/optimize-marketing-with-machine-learning.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/optimize-marketing-with-machine-learning.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @nfmoore
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/439419/>439419</a>

**Comment by mike-urnun-msft** [comment]
Of course, @Predictive-JT! Since this channel is for driving improvements towards Azure Architecture Center docs, could you make a post on [MS Q&A channel](https://docs.microsoft.com/en-us/answers/index.html) for your question?

**Comment by mike-urnun-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
