### ISSUE TITLE
Enterprise Dataware Strategy 

### ISSUE THREAD

**Issue by freespambox4eva** [MicrosoftDocs/architecture-center#2867]
Hi,

Can you highlight a detailed strategy for creating an Enterprise Data Warehouse on Azure?

What could be a reference architecture for the same?

Regards,

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/439977/>439977</a>

**Comment by JasRobe** [comment]
Thank you for this request, we will consider this for future content delivery
