### ISSUE TITLE
Subnet icon is missing

### ISSUE THREAD

**Issue by epomatti** [MicrosoftDocs/architecture-center#2868]
Can't find subnet icon...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

![image](https://user-images.githubusercontent.com/6530769/121789298-355c0000-cbab-11eb-8f88-df8771ec5f43.png)

![image](https://user-images.githubusercontent.com/6530769/121789308-50c70b00-cbab-11eb-813a-0c3fb650eec5.png)

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/440335/>440335</a>

**Comment by mike-urnun-msft** [comment]
Hi @epomatti - Thank you for sharing your feedback! Since this channel is for driving improvements towards MS Docs, could you provide us with a specific URL of the MS Doc that your feedback is most applicable to? That way, we're able to connect you with the right team that is best suited to address your feedback.

**Comment by epomatti** [comment]
@mike-urnun-msft updated question, don't know why it was missing.

**Comment by Zimmergren** [comment]
Thank you for reporting this, @epomatti.
We've made several updates to the Azure Icons recently, and there are hundreds of new icons added. 

The update is available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

The subnet icon is located in the `networking` folder with the name `02742-icon-service-Subnet.svg`

Thanks!
#please-close
