### ISSUE TITLE
URL - Access denied - under the scalability considerations section

### ISSUE THREAD

**Issue by daveRendon** [MicrosoftDocs/architecture-center#2870]
[Enter feedback here]
The URL under the scalability considerations section is not publicly available: 

"see Azure AD: Under the hood of our geo-redundant, highly available, distributed cloud directory." the URL redirects to: https://techcommunity.microsoft.com/t5/enterprise-mobility-security/bg-p/enterprisemobilityandsecurity

Error: "You do not have sufficient privileges for this resource or its parent to perform this action."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9383c21-9143-1559-c1a8-e6f6dc830159
* Version Independent ID: 37c6c659-a6bc-633e-2b3f-337deb01c215
* Content: [Integrate on-premises AD domains with Azure AD - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/azure-ad?source=docs)
* Content Source: [docs/reference-architectures/identity/azure-ad.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/azure-ad.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/440805/>440805</a>

**Comment by ckittel** [comment]
Until we get the article updated, here is a link to the post: <https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-under-the-hood-of-our-geo-redundant-highly-available/ba-p/243762>

**Comment by daveRendon** [comment]
Thank you @david-stanford @ckittel and reading the comments on the article looks like the blog post is also available as an MS doc - https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-architecture
