### ISSUE TITLE
Translation for this page is missing

### ISSUE THREAD

**Issue by discodandy** [MicrosoftDocs/architecture-center#2871]
This page is not translated in any language. Only the original English text is available.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fbbf8259-fef9-b02b-0b56-e24f95e04c6a
* Version Independent ID: 3d639f35-e1cd-caba-e8ba-4e778ad523b4
* Content: [Azure Automation State Configuration - Azure Architecture Center](https://docs.microsoft.com/de-de/azure/architecture/example-scenario/state-configuration/state-configuration?tabs=cli%2Cwindows)
* Content Source: [docs/example-scenario/state-configuration/state-configuration.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/state-configuration/state-configuration.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @neilpeterson
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/441437/>441437</a>

**Comment by ckittel** [comment]
@JasonCard -- IIRC, you own the loc content for `architecture-center` -- can you check in on this articles translation status?

**Comment by JasonCard** [comment]
Adding @SunnyDeng who is current loc owner for architecture-center. 
@ckittel please reassign to @SunnyDeng.

**Comment by SunnyDeng** [comment]
This file is in loc pipeline queue, the current ETA is July.

**Comment by jocontr** [comment]
Translation completed. Thank you.
