### ISSUE TITLE
Mentioning of Azure API Management is missing in this page

### ISSUE THREAD

**Issue by TestUser0811** [MicrosoftDocs/architecture-center#2872]
Why "Azure API Management" not included in this page?

Azure Application Gateway & Azure API Management are inter changeable though they are difference Azure Load balancing offering. 

Some documentation about when to choose what between Azure Application Gateway & Azure API Management would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**
*

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/442680/>442680</a>

**Comment by jocontr** [comment]
@TestUser0811 what aspect of Azure API Management would you consider relevant within the topic of load balancing?

**Comment by jocontr** [comment]
Please feel free to reopen the issue and provide additional context. Thank you
