### ISSUE TITLE
A command line (app) SignalR Client

### ISSUE THREAD

**Issue by bd-robert-dean** [MicrosoftDocs/architecture-center#2873]
I would like to see the example as a non web UI client.  I have been working for months to get a command line app that is the SignalR Client using Azure SignalR Service (ASRS). I have found nothing on step by step to scale with the ASRS. MS docs says to scale by adding App Service, by other documentation says that ASRS will scale for you. If adding App Services to Azure is needed then clients will need to open multiple and growing number of firewall rules to allow access to the ASRS and the Hubs.

Thanks you,
Robert Dean
robert.dean@bd.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608c01ec-d21f-7bdf-a700-7288222ad27c
* Version Independent ID: 94920b97-adc0-3899-f8bd-aff821f3435b
* Content: [Cross-platform Chat - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cross-platform-chat)
* Content Source: [docs/solution-ideas/articles/cross-platform-chat.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/cross-platform-chat.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/442761/>442761</a>

**Comment by ckittel** [comment]
This article is going to be deleted and our team does not have any plans of adding additional SignalR content at this time, but thank you for the suggestion.

#please-close
