### ISSUE TITLE
Bursting from AKS with ACI

### ISSUE THREAD

**Issue by Kundan9** [MicrosoftDocs/architecture-center#2876]
I'd like to see you expand this article with more information, implementation details, pricing guidance, or code examples

-------------------------------------

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f8f943-7688-65e6-26c9-5d682a225306
* Version Independent ID: 18d298ba-be2b-bc4a-abac-5ea5a94fadca
* Content: [Bursting from AKS with ACI - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scale-using-aks-with-aci)
* Content Source: [docs/solution-ideas/articles/scale-using-aks-with-aci.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scale-using-aks-with-aci.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443236/>443236</a>

**Comment by AjayKumar-MSFT** [comment]
@Kundan9, Thanks for leveraging Azure docs feedback channel to raise this question. Could you please share the Azure documentation for which this feedback is applicable to?

**Comment by neilpeterson** [comment]
Adding link to doc for easy access.

https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scale-using-aks-with-aci

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24475 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
