### ISSUE TITLE
External traffic points like app gateway and LB in the hub segment 

### ISSUE THREAD

**Issue by rp-msft** [MicrosoftDocs/architecture-center#2877]
[A lot of solutions use hub and spoke model. Within this concept, the public IPs that are receiving traffic from internet or private IPs receiving traffic from corporate network act as the Azure subscription hub ingress/egress points .While the Azure AKS App Gw documentation for brownfiled covers show to have App gw in a separate VNET and resource group, however same is not clear for Loadbalancers which might be internal or external.  These scenarios can be added to this document.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an Azure Kubernetes Service (AKS) cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443413/>443413</a>

**Comment by ckittel** [comment]
@rp-msft -- Azure Load Balancer is imperatively managed by the AKS cluster as its lifecycle is coupled directly to the instance of the cluster. I'm not sure I follow how that would be addressed further in this document.  You can already isolate what subnet the load balancers materialize in, but it needs to be in the cluster's vnet, and isn't a "hub" resource.  Your hub can certainly handle that ingress traffic with a inbound FW (if desired) and AppGW if desired to be managed at the hub level.  But the AKS-managed load balancer is conceptually an extension (or maybe even implementation detail if you look at it in that regard) of the AKS service itself and is spoke-bound. If you can elaborate a bit more on what additional guidance we might be able to add to address your question, that would be helpful.

**Comment by RobBagby** [comment]
Hi @rp-msft - Can you elaborate a bit more on what additional guidance we might be able to add to address your question, that would be helpful. Thanks.

**Comment by RobBagby** [comment]
@rp-msft - I am closing this, as we need more guidance from you. Please feel free to open a new issue when you have more guidance.
