### ISSUE TITLE
Change from "Can be contained?" to "Can be containerized?"

### ISSUE THREAD

**Issue by mattruma** [MicrosoftDocs/architecture-center#2878]
On the Choose a candidate service diagram, I think it should say "Can be containerized?" instead of "Can be contained?"

![image](https://user-images.githubusercontent.com/188079/122596055-5606d880-d037-11eb-9638-fa8441344525.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443468/>443468</a>

**Comment by v-fearam** [comment]
It was already changed on the document

**Comment by v-fearam** [comment]
#please-close
