### ISSUE TITLE
Rename Windows Virtual Desktop (WVD) to: Azure Virtual Desktop

### ISSUE THREAD

**Issue by lukemurraynz** [MicrosoftDocs/architecture-center#2881]
Rename Windows Virtual Desktop (WVD) to: Azure Virtual Desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbf62e6-49ab-a499-f82e-e0ade93ce2e2
* Version Independent ID: 08bbadc2-c2f9-1c43-b541-e5e2554931fc
* Content: [Multiple forests with AD DS and Azure AD - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/multi-forest)
* Content Source: [docs/example-scenario/wvd/multi-forest.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/multi-forest.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @nehalineogi
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443767/>443767</a>

**Comment by WilliamAntonRohm** [comment]
The article has been updated and is now live.

**Comment by WilliamAntonRohm** [comment]
#please-close
