### ISSUE TITLE
Rename Windows Virtual Desktop to: Azure Virtual Desktop

### ISSUE THREAD

**Issue by lukemurraynz** [MicrosoftDocs/architecture-center#2882]
Rename Windows Virtual Desktop to: Azure Virtual Desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115fe9d4-6876-b76b-c194-6dbe760f0131
* Version Independent ID: bd2dbb27-a069-8609-5421-33d223df06eb
* Content: [DevTest and DevOps for IaaS solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-iaas)
* Content Source: [docs/solution-ideas/articles/dev-test-iaas.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/dev-test-iaas.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443769/>443769</a>
