### ISSUE TITLE
"API Gateway" is referenced but that isnt an azure servivce

### ISSUE THREAD

**Issue by ts46235** [MicrosoftDocs/architecture-center#2883]
Shouldn't this wording either say "API Management" or maybe "Application Gateway" or make a note/link to the https://docs.microsoft.com/en-us/azure/architecture/microservices/design/gateway document and say that it could be any number of technologies....the impression to me is that there is an azure service called 'API Gateway'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fccd14ec-192a-ffd8-edec-4296998feb8b
* Version Independent ID: 2bac3769-2613-f739-4796-0737c7cd8919
* Content: [Building microservices on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/)
* Content Source: [docs/microservices/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/index.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443872/>443872</a>

**Comment by david-stanford** [comment]
Can you please let us know which specific words you are referencing; I don't see a reference to API Gateway in the document this is providing feedback on.

Thanks!

**Comment by ts46235** [comment]
@david-stanford my apologies, please disregard this....I put the wrong link in there; it should of been https://docs.microsoft.com/en-us/azure/architecture/microservices/ and after looking at it again I see that it doesnt show azure specific services and is just generic patterns...sorry for the churn!
