### ISSUE TITLE
Scalable web and mobile applications using Azure Database for MySQL - Require additional details

### ISSUE THREAD

**Issue by anshuls** [MicrosoftDocs/architecture-center#2884]
Dear Team,
I was reviewing the document describing Architecture for 'Scalable web and mobile applications using Azure Database for MySQL'
Could you please expand the article to provide more details on:
1. Implementation details
2. Brief description of the components 
3. Code examples

Thanking you in advance.

Edited: Added doc metadata

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b201901-4bec-64d6-994c-2c1522437c39
* Version Independent ID: dba7a5e1-388f-cadf-2f60-bf276986f679
* Content: [Scalable web and mobile applications using Azure Database for MySQL - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-mysql)
* Content Source: [docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-mysql.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-mysql.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443895/>443895</a>

**Comment by v-fearam** [comment]
Hi  @anshuls

Sorry for the delay and thanks for the suggestions. 

This current article is a  “Solution idea” which its goals is to keep it simple, here there is more information:

[Mobile Applications with C#](https://dotnet.microsoft.com/apps/xamarin)

[Create Api with C#](https://learn.microsoft.com/aspnet/core/web-api)

[App Service to host the API](https://learn.microsoft.com/azure/app-service/)

[MySQL as a Service](https://learn.microsoft.com/azure/mysql/))

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
