### ISSUE TITLE
good documentation

### ISSUE THREAD

**Issue by walfredocarneiro** [MicrosoftDocs/architecture-center#2885]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2418a3-cb9d-eb10-dc57-6a4f0ccfee73
* Version Independent ID: 6cb4ac49-e87b-1bd6-ca61-0a3fe8cfa2d5
* Content: [Web and Mobile Front Ends - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/front-end)
* Content Source: [docs/solution-ideas/articles/front-end.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/front-end.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443954/>443954</a>

**Comment by AjayKumar-MSFT** [comment]
@walfredocarneiro, Thanks for taking time to share your positive feedback. It's much appreciated. 
I have shared your feedback with the content owner (@doodlemania2).
