### ISSUE TITLE
Microsoft/SAP solution architecture documents

### ISSUE THREAD

**Issue by MedInc** [MicrosoftDocs/architecture-center#2886]
Please share Microsoft/SAP solution architecture documents

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/444144/>444144</a>

**Comment by david-stanford** [comment]
We have a bunch of SAP articles available here: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/sap-overview (and in that TOC node). 

If there is something else you need please let us know.
