### ISSUE TITLE
More examples on common Recovery Plans and also around retaining IP address

### ISSUE THREAD

**Issue by didier-danloy** [MicrosoftDocs/architecture-center#2887]
It would be great to have more details on this article. Especially with some common Recovery plans with some examples.
I would also love to see additional coverage when retaining IP addresses on top of what we already have in the existing documentation on this topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a69c921d-0f42-7b6c-88ef-e82ff2e2453b
* Version Independent ID: 9f8b73b2-fa6a-cb9c-d22e-67ec625ce3d7
* Content: [Connect to Azure VMs on-premises failover with Azure Site Recovery - Azure Site Recovery](https://docs.microsoft.com/en-us/azure/site-recovery/concepts-on-premises-to-azure-networking#retain-ip-addresses)
* Content Source: [articles/site-recovery/concepts-on-premises-to-azure-networking.md](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/site-recovery/concepts-on-premises-to-azure-networking.md)
* Service: **site-recovery**
* GitHub Login: @Harsha-CS
* Microsoft Alias: **harshacs**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/445138/>445138</a>

**Comment by HarshitaSingh-MSFT** [comment]
@didier-danloy, thank you for reaching out to us! Can you please share which article you are referring to?

**Comment by HarshitaSingh-MSFT** [comment]
Hello!
Just checking to see if you have had a chance to see the previous response. Kindly let us know if it answers your question and if you need further assistance on this issue.

**Comment by didier-danloy** [comment]
Hello!

Here the article I was referring to:
https://docs.microsoft.com/en-us/azure/site-recovery/concepts-on-premises-to-azure-networking#retain-ip-addresses

Regards,
Didier

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by HarshitaSingh-MSFT** [comment]
We acknowledge your feedback and just to inform you that we have already worked upon this and is in queue for deployment. Please stay tuned to see these changes.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
