### ISSUE TITLE
Would like to see implementation for Modern analytics architecture with Azure Databricks

### ISSUE THREAD

**Issue by SheikMohamed1987** [MicrosoftDocs/architecture-center#2888]
Would like to see implementation for this reference architecture

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254782d-e773-b542-73e8-f568d3bbee39
* Version Independent ID: 40d81223-f8ea-2eec-616e-5f6ee28c8206
* Content: [Modern analytics architecture with Azure Databricks - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture)
* Content Source: [docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @kacummis
* Microsoft Alias: **kacummis**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/445198/>445198</a>

**Comment by HarshitaSingh-MSFT** [comment]
@SheikMohamed1987, thank you for reaching out to us. Happy to help. To help you further, can you please share the document's link to which you are referring?

**Comment by HarshitaSingh-MSFT** [comment]
Hello!
Just checking to see if you have had a chance to see the previous response. Kindly let us know if it answers your question and if you need further assistance on this issue.

**Comment by SheikMohamed1987** [comment]
Link- https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by kacummis** [comment]
Hi,

I see the comment - what do you mean "would like to see implementation"? Are there questions around the legitimacy of this architecture?

**Comment by kacummis** [comment]
Hi,

Can you please explain more the ask here? I am not sure what supporting information to provide if you want to “see implementation”.

From: Sheik Mohamed ***@***.***>
Sent: Tuesday, June 22, 2021 10:54 PM
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Katie Cummiskey ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/architecture-center] Would like to see implementation for Modern analytics architecture with Azure Databricks (#2888)


Would like to see implementation for this reference architecture

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 7254782d-e773-b542-73e8-f568d3bbee39
  *   Version Independent ID: 40d81223-f8ea-2eec-616e-5f6ee28c8206
  *   Content: Modern analytics architecture with Azure Databricks - Azure Solution Ideas<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fsolution-ideas%2Farticles%2Fazure-databricks-modern-analytics-architecture&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7C64cf31be3fb24fb8381b08d9360b4574%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637600244312769405%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Lm9k%2BQYLgokb9%2F%2F41%2Fm84%2F6NOAJcGp306AINhhjBnL8%3D&reserved=0>
  *   Content Source: docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftdocs%2Farchitecture-center%2Fblob%2Fmaster%2Fdocs%2Fsolution-ideas%2Farticles%2Fazure-databricks-modern-analytics-architecture.yml&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7C64cf31be3fb24fb8381b08d9360b4574%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637600244312779404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Uh7Hxxqa7Y%2F5yRadALZwhdbx5joNxrV3dq2bIqMtE7c%3D&reserved=0>
  *   Service: architecture-center
  *   Sub-service: solution-idea
  *   GitHub Login: @kacummis<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkacummis&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7C64cf31be3fb24fb8381b08d9360b4574%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637600244312899350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oMoVX5tHRMk%2B8A0O7d2hF6vzMTPDa31lqSrbH7KpwqQ%3D&reserved=0>
  *   Microsoft Alias: kacummis

**Comment by SheikMohamed1987** [comment]
I meant code samples if any for this reference architecture. That would be really helpful. Thanks.

**Comment by kacummis** [comment]
Hi Sheik,

Here are some relevant code samples:

  *   Ingestion, ETL, and Stream Processing with Azure Databricks<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftechcommunity.microsoft.com%2Ft5%2Fanalytics-on-azure%2Fingestion-etl-and-stream-processing-with-azure-databricks%2Fba-p%2F1932258&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085094112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wJd6jpTcDQFs15VPVGbBGloa4LJiNajn%2BfXbIxRP988%3D&reserved=0>
     *   COPY INTO sample code<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdatabricks%2Fspark%2Flatest%2Fspark-sql%2Flanguage-manual%2Fdelta-copy-into&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085104105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XFPhSvDK7K5tSk0qZ%2FmB%2FvM9NGebEtKqZx0w3jddBmw%3D&reserved=0>
     *   Azure Databricks Auto Loader<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdatabricks%2Fspark%2Flatest%2Fstructured-streaming%2Fauto-loader&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085114108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6yxaoQGJ8aVPt%2BYXsL1eh4YNV3lTSPtyQtJdEIsdi%2Fo%3D&reserved=0>
     *   Azure Data Factory Copy Activity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdata-factory%2Fconnector-azure-databricks-delta-lake&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085124098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Bivll6DF74YQpm4kEtjk93QY0V5VptM%2BGFJXta2828c%3D&reserved=0>
  *   Batch and streaming ETL code samples<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrennerh1%2Fdatabricks-demos%2Ftree%2Fmain%2FCloud%2520Integration%2520Demos%2520-%2520Azure%2520Databricks&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085134092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LcShmaOFC1wBC5mS7lQG76VTXO8B%2Bk3inpuWCoxPKvs%3D&reserved=0> from the new Azure Databricks cloud integration demo<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdatabricks.com%2Fdiscover%2Fdemos%2Fazure-databricks-cloud-integration&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085134092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q%2BYmU%2FW5w700nnzYO6Xf27TOsKILA66n3s1CjXdX%2B5o%3D&reserved=0>
  *   ETL for EHR Data Analysis<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffieldengwebstore.z5.web.core.windows.net%2Fbruce.nelson%2Fnotebooks%2FHLS_Demos_save%2Fdashboard%2F00-etl-rwd.html&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085144092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qLFWiYoawu1XN7mZkdtFvdNpIzlE%2FfyxuMJNCbwT1xQ%3D&reserved=0> from this Tech Community post<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftechcommunity.microsoft.com%2Ft5%2Fanalytics-on-azure%2Fbuilding-a-real-world-health-condition-dashboard-with-azure%2Fba-p%2F1990746&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085154081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cJdSgMIDs1dUjTvNYwTmhSolsX6pcrCMAVL6mnu8kI0%3D&reserved=0>
  *   Video tutorials showing real-time ingestion of tweets from Twitter, specifically for COVID-19, through the stages of Bronze to Gold with Databricks and Delta Lake<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdatabricks.com%2Fblog%2F2020%2F09%2F25%2Fhow-relogix-reduced-infrastructure-costs-by-80-with-delta-lake-and-azure-databricks.html&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085164081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zhxbiJjGnMWxreMpZ7G4K748UN9d4hZsmnFl38r7jHs%3D&reserved=0>
     *   Video 1: Twitter Bronze Tables<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D6GPPuWlPM6M&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085174083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LdzVJ7iwK3GX96MdlfWTDjyf0%2BYUPqSMo%2BEkYSaDbiQ%3D&reserved=0>
     *   Video 2: Delta Silver Table Creation<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DgbOfKKFvMaU&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085184076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZZSxrGy2u0h2JIYny9Pd0Zj%2FY12S%2F0HutPe%2BOrpU1AQ%3D&reserved=0>
     *   Video 3: Gold Level Views Delta<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZLCob-DyPdA&data=04%7C01%7CKatie.Cummiskey%40microsoft.com%7Ceeaadc4e4395452b7d5f08d93bcf21b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637606583085184076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RK3BGOGSNPrRCVtf3gkAeO3fNR4O1G9QQSOLR6hzu1M%3D&reserved=0>

**Comment by SheikMohamed1987** [comment]
Thanks very much!

**Comment by jocontr** [comment]
Sample code provided.
