### ISSUE TITLE
48 cores not 32 cores for Azure NetApp Files

### ISSUE THREAD

**Issue by mchad1** [MicrosoftDocs/architecture-center#2889]
Azure NetApp Files is acceptable today for upto 48 cores based on the following note (please see the note added on 2/26/2021)
https://communities.sas.com/t5/Administration-and-Deployment/Azure-NetApp-Files-A-shared-file-system-to-use-with-SAS-Grid-on/td-p/579437

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1263da59-b247-1de4-1357-0a549c67d41e
* Version Independent ID: 9c43e47e-1336-bd17-780c-36e456778816
* Content: [SAS on Azure architecture guide - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/sas/sas-overview)
* Content Source: [docs/guide/sas/sas-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/sas/sas-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ranieuwe
* Microsoft Alias: **ronieuwe**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/445245/>445245</a>

**Comment by ranieuwe** [comment]
Will correct, but with statement that 48 cores are possible _if_ tuning is applied.

**Comment by mchad1** [comment]
Of course, if tuning is applied

**Comment by ranieuwe** [comment]
Merged upstream, will be on the docs site soon.

**Comment by ranieuwe** [comment]
@HarshitaSingh-MSFT you can go ahead and close this issue.
