### ISSUE TITLE
Misleading title

### ISSUE THREAD

**Issue by dpaiha** [MicrosoftDocs/architecture-center#2890]
There's also a service called "Azure Firewall" and the document is about 3rd party FWs/NVAs. Should be changed to something like "Azure advanced firewall architecture guide" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9f2509-a3f9-d8bf-e0bf-a9c970d5a423
* Version Independent ID: 62cbc02f-3a6a-2966-380d-af66737f8711
* Content: [Azure Firewall Architecture Guide - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/firewalls/)
* Content Source: [docs/example-scenario/firewalls/index.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/firewalls/index.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @RZomerman
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/445847/>445847</a>
