### ISSUE TITLE
Misleading title

### ISSUE THREAD

**Issue by josh-endries** [MicrosoftDocs/architecture-center#2891]
This page doesn't discuss any testing tools, only how to improve performance, which would be important _after_ testing takes place, but it doesn't mention _how_ to perform those tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c67eba0-d85b-56e6-35bb-841a98cd1e38
* Version Independent ID: c2c66e14-b4c4-c3a4-343d-3e512d30a088
* Content: [Testing tools - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/scalability/test-tools)
* Content Source: [docs/framework/scalability/test-tools.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/scalability/test-tools.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/446974/>446974</a>

**Comment by v-aangie** [comment]
Sent email to Grace to reassign.

**Comment by JanetCThomas** [comment]
Assigned to editor: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2034097

**Comment by ShawnKupfer** [comment]
This was fixed in https://github.com/MicrosoftDocs/well-architected-pr/pull/525
