### ISSUE TITLE
Azure NetApp Files section inaccuracies 

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#2892]
Please change the Azure NetApp Files section to mention 48 cores instead of the current 32 cores (as per this SAS comment https://communities.sas.com/t5/Administration-and-Deployment/Azure-NetApp-Files-A-shared-file-system-to-use-with-SAS-Grid-on/m-p/722261#M21648). 

Also please reword the first bullet by taking out the 'latency' statement. At this time it is just the throughput that is a limiting factor. We (ANF PG) would not want ANF to be portrayed as having latency issues.

Further, the recommendation on tiers is reverse. With small amounts of data Premium or Ultra would be needed, whereas with large amounts of data Standard might suffice. This is because ANF's performance is a function of service level x provisioned capacity. More capacity == more bandwidth, thus at large capacities standard will provide same max throughput as premium and ultra at smaller capacities respectively. Please contact me at b-gevant@microsoft.com for clarification where needed.

Suggesting following wording:

SAS tests have validated NetApp performance for SAS Grid. Specifically, tests show that Azure NetApp Files is a viable primary storage option for SAS Grid clusters of up to 48 physical cores across multiple machines.

Consider the following points when using this service:

- Azure NetApp Files works well with Viya 3.5 and Viya 4.0 deployments. But don't use Azure NetApp Files for the CAS cache in Viya, because the write throughput is inadequate at this time. If possible, use your VM's local ephemeral disk instead.
- On SAS 9 Foundation with Grid 9.4, the performance of Azure NetApp Files with SAS for SASDATA files is good for clusters up to 48 physical cores.
- To ensure good performance, select at least a Premium or Ultra service level when deploying Azure NetApp Files. with small to medium capacity volumes. You may choose the Standard service level for large volumes. Or start with the Premium level and switch to Ultra or Standard respectively later if needed. This can be done online without disruption or data migration.
- Read and write performance are different for Azure NetApp Files. Write throughput for SAS hits limits at around 1600MiB/s perf volume while read throughput goes beyond that, to around 4500MiB/s per volume. If you need continuous high write throughput, you may want to consider deploying multiple volumes or Azure NetApp Files may not be a good fit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1263da59-b247-1de4-1357-0a549c67d41e
* Version Independent ID: 9c43e47e-1336-bd17-780c-36e456778816
* Content: [SAS on Azure architecture guide - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/sas/sas-overview#azure-netapp-files-nfs)
* Content Source: [docs/guide/sas/sas-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/sas/sas-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ranieuwe
* Microsoft Alias: **ronieuwe**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/447095/>447095</a>

**Comment by ranieuwe** [comment]
@gvanteylingen also see #2889. Will combine and revise these issues and close jointly. @david-stanford can you please assign to me? Thanks.

**Comment by ranieuwe** [comment]
Merged upstream, will be on the docs site soon.
