### ISSUE TITLE
Great page!

### ISSUE THREAD

**Issue by skiddder** [MicrosoftDocs/architecture-center#2895]
This information is really helpful! Especially the "Considerations" section is awesome!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43da9bdf-a3d3-a65b-b555-60dcc5ac2c55
* Version Independent ID: 9913c705-aeb7-e154-4fdf-164ff1e7ff99
* Content: [AKS Day-2 Operations Guide - Patch and upgrade guidance - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-upgrade-practices)
* Content Source: [docs/operator-guides/aks/aks-upgrade-practices.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/operator-guides/aks/aks-upgrade-practices.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/449295/>449295</a>

**Comment by himanshusinha-msft** [comment]
Thanks @david-stanford for the update . We have assigned the issue to the author for now .

**Comment by neilpeterson** [comment]
Thanks for the feedback @skiddder, really appreciate it.
