### ISSUE TITLE
Complexity and risk scale

### ISSUE THREAD

**Issue by skhanweb** [MicrosoftDocs/architecture-center#2896]
Hi Microsoft Team,

I would like to ask regarding scoring pattern. On what scale did you find the complexity and risk.  How you you decide between 0 and 1 (a score of <0.3 = low, <0.7 = medium, >0.7 = high).

Thanks

Kind Regards,
Saud Khan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f4fbe7-4716-95ba-3a3a-858dc9ca77b5
* Version Independent ID: eb1f3aac-11d1-e4fc-6925-0574b4438ee0
* Content: [Application assessment - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/serverless-quest/application-assessment)
* Content Source: [docs/serverless-quest/application-assessment.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/serverless-quest/application-assessment.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @rogeriohc
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/449605/>449605</a>

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by RobBagby** [comment]
@rogeriohc - can you address the question?
