### ISSUE TITLE
Nice explanation

### ISSUE THREAD

**Issue by arunrajes** [MicrosoftDocs/architecture-center#2897]
[Enter feedback here]
Thanks for sharing such a wonderful article on how to do forecasting at scale using R. Might be some more detailed explanation can be provided for beginners and a video tutorial also can supplement this

Regards,
Arun Rajesh B.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab154f6-58af-5834-ae23-9824b21541e0
* Version Independent ID: bb8941b3-59fd-fae3-0cbb-f8c0307de62e
* Content: [Batch scoring with R models to forecast sales - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/batch-scoring-r-models)
* Content Source: [docs/reference-architectures/ai/batch-scoring-R-models.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/batch-scoring-R-models.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/450126/>450126</a>

**Comment by himanshusinha-msft** [comment]
Thanks @david-stanford . We have assigned this to you for now . Please do assign this to the correct author.

**Comment by hallihan** [comment]
Thank you @arunrajes for taking the time to provide feedback and suggestions for this article. #please-close
