### ISSUE TITLE
Microsoft Azure 

### ISSUE THREAD

**Issue by ChandanpaswanAI123** [MicrosoftDocs/architecture-center#2902]
This session is going to be most important session that you can't imagine really helpful for all of you those who want to gain knowledge of Microsoft Azure fundamental 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d100d43f-d48a-3d97-1aea-7a5409fdccc8
* Version Independent ID: 568dcd88-b93c-1d41-44d0-8643dd057a33
* Content: [Azure for AWS professionals - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/aws-professional/)
* Content Source: [docs/aws-professional/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/451051/>451051</a>

**Comment by neilpeterson** [comment]
@ChandanpaswanAI123 thanks for opening this issue. Did you find an issue with the document and if so can you provide more detail?

Thanks a bunch.

**Comment by neilpeterson** [comment]
Closing issue, feel free to re-open if still needed.
