### ISSUE TITLE
Isn't AZTK deprecated?

### ISSUE THREAD

**Issue by joappleMSFT** [MicrosoftDocs/architecture-center#2903]
When I contacted an engineer who was familiar with AZTK they recommended it not be used. Should it be listed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba35cbb-4160-0b5d-6829-103b25ad6ce9
* Version Independent ID: fa12ea8e-401a-9567-7b35-ffff532a99b6
* Content: [Choosing a batch processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing)
* Content Source: [docs/data-guide/technology-choices/batch-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/batch-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/451805/>451805</a>

**Comment by himanshusinha-msft** [comment]
@david-stanford  : We have assigned the issue to you for now .

**Comment by Zimmergren** [comment]
We've recently reviewed this, and the AZTK portion of this article was removed. Thank you for reporting it. 
#please-close
