### ISSUE TITLE
blob_service_client should be replaced by blob_service_client_instance 

### ISSUE THREAD

**Issue by AessamL** [MicrosoftDocs/architecture-center#2905]
[Enter feedback here]

blob_client_instance = **blob_service_client**.get_blob_client(CONTAINERNAME, BLOBNAME, snapshot=None)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647ed505-3e6e-3db7-63ee-025edf6e63f4
* Version Independent ID: d910ba75-6c86-6172-64be-e45ba2bf5a3d
* Content: [Explore data in Azure Blob Storage with pandas - Team Data Science Process - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-science-process/explore-data-blob)
* Content Source: [docs/data-science-process/explore-data-blob.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-science-process/explore-data-blob.md)
* Service: **machine-learning**
* Sub-service: **team-data-science-process**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/452612/>452612</a>

**Comment by marktab** [comment]
@david-stanford  I had made this correction when it was in docs/microsoft -- should I make another pull request?

**Comment by marktab** [comment]
@AessamL I made a correction which should show in the public web in the next 48 hours

**Comment by YutongTie-MSFT** [comment]
@marktab Thanks, I will close this issue.

@AessamL 
Thanks for the feedback! We are currently investigating and will update you shortly.
