### ISSUE TITLE
Missing Icon: Azure Machine Learning

### ISSUE THREAD

**Issue by epomatti** [MicrosoftDocs/architecture-center#2906]
Missing Icon: Azure Machine Learning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/452931/>452931</a>

**Comment by Zimmergren** [comment]
Thank you for reporting this, @epomatti.

We've made several updates to the Azure Icons recently, and there are hundreds of new icons added.
The update is available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

There are relevant Machine Learning icons added: 
- In the `iot` folder: 
  - `00030-icon-service-Machine-Learning-Studio-(Classic)-Web-Services.svg`
  - `10167-icon-service-Machine-Learning-Studio-Workspaces.svg`
  - `10168-icon-service-Machine-Learning-Studio-Web-Service-Plans.svg`

Please open a new ticket if there are still icons you believe should be in the Icons pack.

Thanks!
#please-close
