### ISSUE TITLE
Feature Request: Make Diagrams 'Whiteboard'able

### ISSUE THREAD

**Issue by prafullkotecha** [MicrosoftDocs/architecture-center#2907]
Let the readers open diagrams, on this page and other pages in **Architecture Center**, directly in Microsoft Whiteboard App, like a template. I couldn't find any way to create custom template, otherwise I would've loved to contribute that feature myself.

[Here](https://www.invisionapp.com/news/announcement/freehand-templates) are some links for the [inspiration](https://www.invisionapp.com/freehand/templates/detail/architecture-brainstorm-template).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a0c8e3-8abb-aa09-c746-ae94113f3c14
* Version Independent ID: 5b56b900-3c15-4392-dd73-85e496954dc7
* Content: [Identifying microservice boundaries - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/model/microservice-boundaries)
* Content Source: [docs/microservices/model/microservice-boundaries.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/model/microservice-boundaries.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/453007/>453007</a>

**Comment by RobBagby** [comment]
@prafullkotecha - The visio for the diagram is downloadable. Does that address your concern?

**Comment by prafullkotecha** [comment]
I was expecting a tool like this to be embedded or deep-linked from the architecture center pages - https://googlecloudcheatsheet.withgoogle.com/architecture
