### ISSUE TITLE
Awesome artical

### ISSUE THREAD

**Issue by nabilrifki** [MicrosoftDocs/architecture-center#2908]
I would like an SVG version of the architectural diagram.

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/453213/>453213</a>

**Comment by david-stanford** [comment]
Hello,

Which article are you referencing with this comment?

Thank you!
David

**Comment by JasRobe** [comment]
Closing as follow up went unanswered
