### ISSUE TITLE
Azure Files Premium too slow for kubernetes use

### ISSUE THREAD

**Issue by mahgo** [MicrosoftDocs/architecture-center#2909]
Azure Files Premium is way too slow for Kubernetes use, so it shouldn't be suggested to use it. See https://github.com/Azure/AKS/issues/223

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2edf62c9-d5c7-b4d0-99e7-f271ef0b629e
* Version Independent ID: d9ff7f72-3fbb-3bc6-e787-60b1ccecb698
* Content: [Magento e-commerce platform in Azure Kubernetes Service (AKS) - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/magento/magento-azure)
* Content Source: [docs/example-scenario/magento/magento-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/magento/magento-azure.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/453242/>453242</a>

**Comment by v-fearam** [comment]
#please-close
