### ISSUE TITLE
Wrong Visio Link

### ISSUE THREAD

**Issue by D3Troy** [MicrosoftDocs/architecture-center#2910]
The "Download a Visio file of this architecture." is referencing to the wrong file.
Please also check all other Sections unter "Architectures" since almost all of them reference to the same one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#feedback)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/453425/>453425</a>
