### ISSUE TITLE
Add ARO and remove Service Fabric

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#2911]
Hi,

The decision tree at [https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#choose-a-candidate-service](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#choose-a-candidate-service) should no more display Service-Fabric .... and should add Azure RedHat OpenShift aka ARO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/453521/>453521</a>

**Comment by SatishBoddu-MSFT** [comment]
Hello @ezYakaEagle442 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by skabou** [comment]
It appears this has been addressed.  If you are still experiencing issues, please re-open with additional information.
