### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by airestonia** [MicrosoftDocs/architecture-center#2917]
Below sentence under "Fault Injection" topic has a misspelled word: "pourposley" 
Shutting down infrastructure components, **pourposley** degrading performance, or introducing faults are ways of verifying that the application is going to react as expected when these situations occur.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d90d3cc-8d25-3331-0647-e93017a41548
* Version Independent ID: afa8af69-58b9-bcb6-5edc-34e0b12e7614
* Content: [Testing your application and Azure environment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/release-engineering-testing)
* Content Source: [docs/framework/devops/release-engineering-testing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/release-engineering-testing.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @Jose-Moreno
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/455065/>455065</a>

**Comment by ckittel** [comment]
Thank you @airestonia -- the typo has been fixed and will be published within 24 hours.

**Comment by Jose-Moreno** [comment]
Greetings, I was tagged here but I have no idea why. For some reason my login was used as part of this report, but I've never dabbled with azure pipelines. I'd kindly ask the OP (which looks like a new account? is this one of the new AI bots you're deploying?) to not tag me in unrelated bug reports.

Now I've taken a look at this article https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/release-engineering-testing.md at it also says that I authored it? Not even my github history has record of this and I don't have a fork of this repository nor permission to edit and couldn't find a PR for this. Can someone explain what is happening here? @david-stanford @ckittel

**Comment by ckittel** [comment]
@Jose-Moreno sorry about that, there is a typo in the document, another Jose Mareno was the other and their github alias was entered wrong.  No action needed from you, we'll get the right alias added and yours removed.

**Comment by Jose-Moreno** [comment]
@ckittel Thank you for letting me know, and thank you for taking such prompt action. I wish you and all your team the very best in these endeavours. Cheers.

**Comment by ckittel** [comment]
@Jose-Moreno updated the author to the correct Jose Moreno.  Sorry about that.  That fix will be published sometime in the next 24 hours.  I checked for other misattributions to you in this documentation set, and couldn't find any.
