### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by polorumpus** [MicrosoftDocs/architecture-center#2918]
There is a broken link in "[Design Pattern](https://docs.microsoft.com/en-us/azure/architecture/guide/#design-patterns)" section at word "here" which should have been linked to "https://docs.microsoft.com/en-us/azure/architecture/patterns/".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Guide - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/455277/>455277</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@polorumpus That's a good catch, thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.
