### ISSUE TITLE
Broken page / characters 

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/architecture-center#2919]
The page has this section where it possibly wanted to put a link but instead looks like escape characters. 

>Examples of Zero Trust networks as a concept are demonstrated in the implementation in a0005-i and a0005-o user-provided

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c9cfb32-2013-f31e-0209-d5194afc8d9e
* Version Independent ID: 9cabc767-9799-abcd-6ccd-11f164c30877
* Content: [AKS regulated cluster for PCI-DSS 3.2.1 - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets)
* Content Source: [docs/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/456054/>456054</a>

**Comment by MonikaReddy-MSFT** [comment]
@annerajb  - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by neilpeterson** [comment]
Thanks @annerajb. In this case, the escape characters are intentional to indicate the namespace. It does look like several should be removed, which I have done. The updated content should publish shortly and be a bit more easy to parse.

Thanks
