### ISSUE TITLE
Feedback for private Azure Bot Service

### ISSUE THREAD

**Issue by junczhu** [MicrosoftDocs/architecture-center#2920]
[Enter feedback here]
Hello Team,

I would really appreciate you insights.
if we have the app service resource in a private network how can the bot registry channel access the endpoint.
Please advice.

Best,
CharingJC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62849df7-a49c-f17e-6876-c3da5954789a
* Version Independent ID: a412df8a-f876-d501-6aec-5bc1f010deaa
* Content: [Securing your Microsoft Teams channel bot and web app behind a firewall - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/teams/securing-bot-teams-channel)
* Content Source: [docs/example-scenario/teams/securing-bot-teams-channel.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/teams/securing-bot-teams-channel.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ajafry
* Microsoft Alias: **aljafry**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/456443/>456443</a>

**Comment by MonikaReddy-MSFT** [comment]
@CharingJC  - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can review and update accordingly.

**Comment by CharingJC** [comment]
Thank you for the update.

**Comment by v-fearam** [comment]
Hi @junczhu,

Sorry for the delay. 

The first sentence of the document [Register a bot with Azure](https://learn.microsoft.com/azure/bot-service/bot-service-quickstart-registration) says “If you don't currently host your bot in Azure, you can still make it available in Azure and use Azure to connect your bot to channels. To do so, enter in Azure the web address where your bot is hosted.”

And [Configure bot registration settings](https://learn.microsoft.com/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0&tabs=userassigned#configuration)

Messaging endpoint -> The endpoint to communicate with your bot.

You need the web address where your bot is hosted. If you have the app service private, that becomes a networking issue. You need to put the hostname that resolves to that app service, in this case a private ip. 

In the document pointed out, the [app service is accessed by a private endpoint](https://learn.microsoft.com/azure/app-service/networking/private-endpoint). It creates a private dns that the app service name resolves to the private ip. If the bot is inside that vnet you could use the app service name, it will resolve correctly.

In the document the bot is outside:

* Azure Firewall exposes a single public IP address that clients can use to communicate with the underlying bot services.

* Route table defines the routes that traffic takes within the virtual network. It ensures that traffic coming to and from the bot passes through the firewall.

* Update DNS resolution: If you are using DNS names to access your App Service, update the DNS configuration to resolve the DNS name to the public IP address associated with the Azure Firewall. This allows external clients to resolve the DNS name and reach your App Service through the firewall. [The point 6 is creating a custom domain](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/teams/securing-bot-teams-channel#walkthrough)


I recommend leveraging the support options available in the Azure portal if you are still facing this issue.


I will close the ticket.
#please-close
