### ISSUE TITLE
Why the title has AWS in it?

### ISSUE THREAD

**Issue by krishnamk00** [MicrosoftDocs/architecture-center#2921]
[Enter feedback here]

Do not find any AWS information specific or comparison in this page and so wondering why the title has "AWS" in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42fd9ae-205d-042a-4d38-4ca356e27d17
* Version Independent ID: 694c671b-430e-31b6-9133-2324bb3a2efa
* Content: [Comparing AWS and Azure regions and zones - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/regions-zones)
* Content Source: [docs/aws-professional/regions-zones.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/regions-zones.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/456817/>456817</a>

**Comment by v-fearam** [comment]
#please-close
