### ISSUE TITLE
Update the compute decision tree

### ISSUE THREAD

**Issue by abKrazy** [MicrosoftDocs/architecture-center#2922]
Many customers are trying to decide when to choose Static Web Apps over App Service. Also, deciding between AKS & ARO. It would be good to incorporate these decision points into the flowchart. 

Q:
Should Service Fabric be removed as an option? I find our field guidance to be pushing customers to AKS/ARO for orchestration, not Service Fabric unless its truly an edge case. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/456820/>456820</a>

**Comment by ckittel** [comment]
There is an update to the decision tree that is landing soon (maybe within a week or so), but I'm not sure if it will address this specific question.  Let's keep this issue open and check back once that update is complete.

**Comment by stephen-sumner** [comment]
@abKrazy - please raise any other issues you have with this decision tree and we'll work to address it. I'm going to close this thread. Thank you so much!
