### ISSUE TITLE
Error in Microservices with AKS page

### ISSUE THREAD

**Issue by raicho81** [MicrosoftDocs/architecture-center#2927]
On the diagram the items on the left representing the users accessing the microservices by apps and web have a caption below, which reads "Admin access" but instead it should read "User access"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/microservices-with-aks.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/457489/>457489</a>

**Comment by RobBagby** [comment]
Closing, as the article was updated.
