### ISSUE TITLE
Broken link to [iac]

### ISSUE THREAD

**Issue by msimecek** [MicrosoftDocs/architecture-center#2929]
In the third paragraph, the link to Infrastructure as Code is not rendered properly:

![image](https://user-images.githubusercontent.com/9624293/125784777-133c6ec6-bd73-4053-b37a-abb678769b7d.png)

"As described in [Infrastructure as Code][iac], "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d90d3cc-8d25-3331-0647-e93017a41548
* Version Independent ID: afa8af69-58b9-bcb6-5edc-34e0b12e7614
* Content: [Testing your application and Azure environment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/release-engineering-testing#feedback)
* Content Source: [docs/framework/devops/release-engineering-testing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/release-engineering-testing.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @erjosito
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/458301/>458301</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@msimecek Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.
Meanwhile, please refer to this article for Infrastructure as Code: [Repeatable Infrastructure](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/automation-infrastructure)
