### ISSUE TITLE
The Code sample on the Valet-Key-Pattern page has a wrong property

### ISSUE THREAD

**Issue by Gerrilicious** [MicrosoftDocs/architecture-center#2930]
I guess the property in the method should be blobSasBuilder and not policy, took me a minute to figure out :D

private StorageEntitySas GetSharedAccessReferenceForUpload(string blobName)
  {          
      var blob = blobServiceClient.GetBlobContainerClient(this.blobContainer).GetBlobClient(blobName);

      var storageSharedKeyCredential = new StorageSharedKeyCredential(blobServiceClient.AccountName, ConfigurationManager.AppSettings["AzureStorageEmulatorAccountKey"]);

      var blobSasBuilder = new BlobSasBuilder

      {
          BlobContainerName = this.blobContainer,
          BlobName = blobName,
          Resource = "b",
          StartsOn = DateTimeOffset.UtcNow.AddMinutes(-5),
          ExpiresOn = DateTimeOffset.UtcNow.AddMinutes(5)
      };
      policy.SetPermissions(BlobSasPermissions.Write);
      var sas = policy.ToSasQueryParameters(storageSharedKeyCredential).ToString();
  
      return new StorageEntitySas
      {
          BlobUri = blob.Uri,
          Credentials = sas
      };
  }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d94a95d1-5371-4c6a-87d6-00fae7dfb401
* Version Independent ID: d9abac19-dfd7-18d7-2479-42fe5476b569
* Content: [Valet Key pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/valet-key)
* Content Source: [docs/patterns/valet-key.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/valet-key.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/458315/>458315</a>

**Comment by ckittel** [comment]
Hey there @Gerrilicious -- thanks for spotting this.  I've updated the article with the correct variable name usage and it will be published in the next 24 hours.
