### ISSUE TITLE
Components: Application Gateway Load balancing misleading

### ISSUE THREAD

**Issue by jakobfischer17** [MicrosoftDocs/architecture-center#2931]
In the doc the following is written:

Azure Application Gateway is a web traffic load balancer that manages traffic to web applications. Load balancers operate at the transport layer, OSI layer 4 TCP and UDP, and route traffic based on source IP address and port to a destination IP address and port.

Since Application Gateway is just a L7 HTTP/HTTPS load balancer, the sentence about load balancers generally operating at layer 4 might be misleading in this context.

Consider changing to "Web traffic load balancers operate at the application layer, OSI layer 7 (HTTP/HTTPS),...

Cheers, Jakob
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://review.docs.microsoft.com/en-us/azure/architecture/reference-architectures/apis/protect-apis?branch=main#feedback)
* Content Source: [docs/reference-architectures/apis/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/apis/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **fabriciosanchez**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/458414/>458414</a>

**Comment by v-fearam** [comment]
#please-close
