### ISSUE TITLE
Missing icon for "region"

### ISSUE THREAD

**Issue by alexangas** [MicrosoftDocs/architecture-center#2933]
I'm unable to find a suitable icon to represent an Azure region. There is a globe, however there's no indication of a particular location on the globe.

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/458810/>458810</a>
