### ISSUE TITLE
Missing icon for "region"

### ISSUE THREAD

**Issue by alexangas** [MicrosoftDocs/architecture-center#2934]
I'm unable to find a suitable icon to represent an Azure region. There is a globe, however there's no indication of a particular location on the globe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/458811/>458811</a>

**Comment by SatishBoddu-MSFT** [comment]
@alexangas 
I have assigned the issue to the content author for further review.

**Comment by Zimmergren** [comment]
Thank you for reporting this, @alexangas.
We've made several updates to the Azure Icons recently, and there are hundreds of new icons added. 
The update is available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

The region icon is in the `general` folder with the name `10116-icon-service-Region-Management.svg`

Thanks!
#please-close
