### ISSUE TITLE
Sql Server as Financial Data-Source

### ISSUE THREAD

**Issue by phougatv** [MicrosoftDocs/architecture-center#2935]
Hey guys, could you also create a page for this - Sql Server as Financial Data-Source, similar to - https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/finance-management-apps-using-azure-database-for-postgresql

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c98be6a-5d58-902d-e548-ca27b81b8bb8
* Version Independent ID: ef43cbcf-6ab0-4dd1-db4f-9eaebf7ae1f7
* Content: [Finance management apps using Azure Database for PostgreSQL - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/finance-management-apps-using-azure-database-for-postgresql)
* Content Source: [docs/solution-ideas/articles/finance-management-apps-using-azure-database-for-postgresql.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/finance-management-apps-using-azure-database-for-postgresql.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/459166/>459166</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24802 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
