### ISSUE TITLE
Typo in Bicep CLI command

### ISSUE THREAD

**Issue by ringoc** [MicrosoftDocs/architecture-center#2937]
Based on the steps defined in Bicep example. The Azure CLI command to spin up the example should be `hub-spoke` instead of `hub-spoke-three` 

az deployment group create --resource-group hub-spoke --template-file main.bicep

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=bicep#reference-deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @neilpeterson
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/459300/>459300</a>

**Comment by SatishBoddu-MSFT** [comment]
@ringoc 
I have assigned the issue to the content author for further review.

**Comment by neilpeterson** [comment]
Thanks for opening this @ringoc, this will be fixed by tomorrow.
