### ISSUE TITLE
Modern analytics architecture with Azure Databricks

### ISSUE THREAD

**Issue by sujitdel75** [MicrosoftDocs/architecture-center#2940]
Please expand this article with more information, implementation details, pricing guidance, or code examples.

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/459966/>459966</a>

**Comment by MayankBargali-MSFT** [comment]
@sujitdel75 Can you share the document you are referring to?

**Comment by JasRobe** [comment]
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24223 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
