### ISSUE TITLE
Does Discovery Hub support Delta Lake architecture?

### ISSUE THREAD

**Issue by frankhefner** [MicrosoftDocs/architecture-center#2941]
Dear Team,
I do have already queried a lot of information about your Discovery Hub. This product seems to be a real "game changer" in managing cloud scale analytics!
But what I did not find is whether Discovery Hub would also support for developing, managing and operating a Delta Lake architecture based upon Databricks and Data Lake Gen2. 
Would you have an answer to this?

Thanks for your feedback,
Frank

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/460332/>460332</a>

**Comment by skabou** [comment]
It is unclear which article this is in reference to.  If assistance is still needed, please re-open with additional information.
