### ISSUE TITLE
Architecture does not work in dark mode. How to solve? 

### ISSUE THREAD

**Issue by truongnhatbui** [MicrosoftDocs/architecture-center#2943]
Hi, when I am viewing architecture. Architecture does not work in dark mode. How to solve? 

![E6ueluFVcAEBbZZ.jpg](https://cdn.hashnode.com/res/hashnode/image/upload/v1626838933926/WhgSdApJQ.jpeg)

Thank you,
Truong

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/460885/>460885</a>

**Comment by skabou** [comment]
It is unclear what article this is referring to.  If assistance is still needed, please re-open with additional details.
