### ISSUE TITLE
know more about the world of artificial intelligence

### ISSUE THREAD

**Issue by digithergus** [MicrosoftDocs/architecture-center#2945]
its great have a look my blog on artificial intelligence http://digirgus.com/blog/ plz review 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d2db702-9c1b-2e97-21b9-341476060a26
* Version Independent ID: 5236464c-fc27-a122-8962-5d1b57c3447c
* Content: [Artificial intelligence (AI) - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/ai-overview)
* Content Source: [docs/data-guide/big-data/ai-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/big-data/ai-overview.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Maggsl
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/461443/>461443</a>

**Comment by JasRobe** [comment]
not content related
