### ISSUE TITLE
Page refers to Cognitive Services "Linguistic Analysis API" but I can't find this API

### ISSUE THREAD

**Issue by mikekistler** [MicrosoftDocs/architecture-center#2947]
This page has good information but it refers to the Cognitive Services "Linguistic Analysis API" and I can't find this API in the current Microsoft Cognitive Services Docs.

https://docs.microsoft.com/en-us/azure/cognitive-services/

In the "Language" category, there is "Language Understanding (LUIS)", "QnA Maker", Text Analytics" and "Translator" -- it's unclear which if any of these would be "Linguistic Analysis API".

devdivcodingdays

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a51dd9-65b7-5039-06d0-d096ad51d0bb
* Version Independent ID: 9c2c99ed-8d17-7865-e680-2107b7f0ebf1
* Content: [Choosing a natural language processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/natural-language-processing#feedback)
* Content Source: [docs/data-guide/technology-choices/natural-language-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/natural-language-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/461712/>461712</a>

**Comment by v-fearam** [comment]
Hi @mikekistler 


Sorry for the delay. 


The ticket was created some years ago, and the article was updated several times since then. The “Linguistic Analysis API” is not mentioned anymore.  You could use the new version.


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
