### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by riteshnegi** [MicrosoftDocs/architecture-center#2953]
The link for "**Asynchronous operations in REST**" in **Next Steps** is not available anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/async-request-reply.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @WillEastbury
* Microsoft Alias: **wieastbu**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/462207/>462207</a>

**Comment by WillEastbury** [comment]
That is indeed correct, let me get right on removing that.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@riteshnegi Thanks for the feedback. The doc has been updated with changes.

**Comment by WilliamAntonRohm** [comment]
This was fixed by commit https://github.com/MicrosoftDocs/architecture-center/commit/806a1fc59e5584307822db2f0c19197a27f6ccf5#diff-b8d0c7d5b18c4a8e73b6af95af3765b3d8511ac93abe74cc6845750bee6d048d
