### ISSUE TITLE
Incorrect caption in image

### ISSUE THREAD

**Issue by NichUK** [MicrosoftDocs/architecture-center#2957]
In the initial image on this page, section 5 is given in the key as "user access" but in the image is labelled as "admin access". Admin access is actually a separate section on the right hand side of the image, which is correctly labelled.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/microservices-with-aks.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/462676/>462676</a>

**Comment by DerekHerman-MSFT** [comment]
Thanks for reporting this. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
It is unclear what the issue is.  If assistance is still needed, please open with additional details.
