### ISSUE TITLE
Error in Ingress Traffic Diagram

### ISSUE THREAD

**Issue by toddwhitehead** [MicrosoftDocs/architecture-center#2960]
The ingress flow [diagram ](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks#deploy-ingress-resources) is missing the internal load balancer component. This causes confusion and also means the elements referenced in the detailed flow description below the diagram are incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an Azure Kubernetes Service (AKS) cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/462791/>462791</a>

**Comment by ckittel** [comment]
Hey there @toddwhitehead -- The Ingress traffic flow diagram is only showing the touch points with TLS.  But I agree the numbering doesn't line up.  I'm going to recommend we remove the numbers from the diagram so as to not cause confusion with the numbered list below.

**Comment by rorywoods** [comment]
Any updates on this? I was writing up the same issue. As stated, the ILB is missing while mentioned in the explanatory text and the numbers are off. But also, using an Azure Load Balancer icon labeled as Workload in the image adds to the confusion. Further, the link between the IC and Workload (pods?) is shown with a padlock icon whereas paragraph 4 says this traffic is not encrypted.

**Comment by ckittel** [comment]
@WendyRing can you please include this issue in our content dev planned refresh of this article?

**Comment by hallihan** [comment]
This was addressed in https://github.com/MicrosoftDocs/architecture-center/commit/482bbc9185d5985f307a1584cf5bc22f9f8495a2 #please-close
