### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by huye196788703** [MicrosoftDocs/architecture-center#2969]

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/463590/>463590</a>

**Comment by DerekHerman-MSFT** [comment]
@huye196788703 In order for us to assist you can you please link to the document you are facing issue with and describe the issue? This way we can assign it to the proper team to investigate. Thanks!

**Comment by neilpeterson** [comment]
@huye196788703 I am going to close this issue for new, please re-open with details if still needed. Thanks.
