### ISSUE TITLE
warm path

### ISSUE THREAD

**Issue by tervoju** [MicrosoftDocs/architecture-center#2973]
[Enter feedback here]
I assume you are meaning TSI instead of Azure Stream Analytics in the warm path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot?source=docs#feedback)
* Content Source: [docs/reference-architectures/iot.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/iot.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @mcosner
* Microsoft Alias: **mcosner**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/464219/>464219</a>

**Comment by DerekHerman-MSFT** [comment]
Thanks for reporting this. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by PramodValavala-MSFT** [comment]
@tervoju Looks like this has been now fixed. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
