### ISSUE TITLE
Additional Dynamics commentary

### ISSUE THREAD

**Issue by MathewBamford** [MicrosoftDocs/architecture-center#2974]
Its great to see a data pattern that shows dynamics both as a source and as a target.

My understanding is that its only Dynamics F&O that has direct integration to the data lake and does not include Dynamics CE. Should the diagram and commentary reflect that they are different and that the Dynamics CE export services is used to get data into a SQL database (as per Microsoft advice) and from them can be dealt with?

It would also be great to see specific reference to Dynamics Customer insight and suggested approach for ingestion. Currently it seems to have a basic transformation and matching engine in the app itself which does not really align to any medium/large enterprise pattern for data pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15bc531d-2f60-0d8d-986d-744cdafc3df6
* Version Independent ID: 3ad41ecd-203b-89b2-3d44-83b8d6c4276f
* Content: [Modern data warehouse for small and medium business - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/small-medium-data-warehouse)
* Content Source: [docs/example-scenario/data/small-medium-data-warehouse.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/data/small-medium-data-warehouse.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @galinagpolyakova
* Microsoft Alias: **gapolyak**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/464241/>464241</a>

**Comment by galinagpolyakova** [comment]
Good day Matthew,
Please check [Microsoft Dataverse](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-intro)  documentation on Dynamics 365
And this is the [Dataverse Link to Synapse](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/azure-synapse-link-synapse) Preview feature announced recently that allows you to export dataverse to ADLS and Synapse for exploration. 
I’ll consider putting together additional info on Dynamics integrations. 
Regards, Galina

**Comment by v-fearam** [comment]
#please-close

**Comment by hallihan** [comment]
This should be addressed by previous comment and links. #please-close
