### ISSUE TITLE
Sequence Diagram & Flow

### ISSUE THREAD

**Issue by am-ar-r** [MicrosoftDocs/architecture-center#2975]
[Enter feedback here]
Isn't it better if API endpoint redirects (302) to status endpoint instead of returning (202). This way client will not have to manage the status endpoint and call it explicitly.
<img width="396" alt="async-request" src="https://user-images.githubusercontent.com/88094025/127327801-ac3844fe-4784-41d1-a9e1-dd0dd17e6007.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply#feedback)
* Content Source: [docs/patterns/async-request-reply.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/async-request-reply.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @WillEastbury
* Microsoft Alias: **wieastbu**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/464317/>464317</a>

**Comment by am-ar-r** [comment]
On further thought, 202 will give the client flexibility to choose not to poll the Status endpoint once Accepted is received. The only disadvantage is client will have to handle the poll explicitly.

**Comment by WillEastbury** [comment]
am-ar-r. 

It certainly could be handled that way, but the semantics of the 202 do not dictate that the representation of the result is somewhere else like the 302 redirect would.

In practice there are a number of variants of this pattern.

**Comment by am-ar-r** [comment]
Thanks for the response @WillEastbury.

**Comment by ckittel** [comment]
I fully agree with @WillEastbury here (and your self response as well -- witch is a great point -- the client MIGHT want to fire-and-forget). Lots of options on how you do this, but it's really hard to say that the immediate redirect via a 302 is "better" unless you know that statistically your work goes so quick that it's likely the request will be 302'd once again from the status endpoint to the resource URI. More often than not, a process like this might take many seconds (or minutes) and checking right away would be unnecessary resource usage when statistically the response is going to be "Nope, try again later."
