### ISSUE TITLE
Errors running PowerShell & Bicep template in Gov Region

### ISSUE THREAD

**Issue by shbabylo** [MicrosoftDocs/architecture-center#2981]
[Enter feedback here]
I tried to run the bicep template in gov region, but it failed.  Looking through the deployment logs, I have errors on the firewall and bastion deployment.

When I ran the PowerShell template, it worked fine.

Both bicep and powershell templates error out on the "VMProtectionAlerts"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @neilpeterson
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/464803/>464803</a>

**Comment by shashishailaj** [comment]
@shbabylo David from our team is looking into this internally and we will update once we have more findings.

**Comment by v-fearam** [comment]
Hi @shbabylo 

Sorry for the delay. 


This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements


I don’t know what is going on in your environment. [There are differences between Azure Global and Azure Gov subscriptions](https://learn.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure)


I recommend leveraging the support options available in the Azure portal if you are still facing this issue.

I will close the ticket.
#please-close
