### ISSUE TITLE
"Subnet to host the ingress resources" section needs more detail

### ISSUE THREAD

**Issue by rajnemani** [MicrosoftDocs/architecture-center#2985]
The following section needs a bit more detail on
1. the meaning of " fulfill the Kubernetes ingress resources", especially what is being conveyed by 'fulfill'
2. on the existence of ALB in this subnet. First it is a single ALB not load balancers. Second it is a bit more explanation on its role in the network topology component

"Subnet to host the ingress resources
To route and distribute traffic, Traefik is the ingress controller that is going to fulfill the Kubernetes ingress resources. The Azure internal load balancers exist in this subnet."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an Azure Kubernetes Service (AKS) cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks?source=docs)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/464858/>464858</a>

**Comment by shashishailaj** [comment]
@rajnemani David from our team is internally working on this and will update the findings .

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Please close this PR as content in OneNote

**Comment by alexhart11** [comment]
@EdPrice-MSFT 
Update: **Do NOT close this PR yet. Pending possible doc edit**

**Comment by EdPrice-MSFT** [comment]
Adding a link for detailed steps.

https://github.com/MicrosoftDocs/architecture-center-pr/pull/9123
