### ISSUE TITLE
For onpremise section add information about production environments

### ISSUE THREAD

**Issue by goncrip** [MicrosoftDocs/architecture-center#2996]
It´s not clear if the alternatives to run azure function onpremise apply for production environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229cb7ce-81f0-4005-356e-66c73e6d257f
* Version Independent ID: 00100699-8feb-bba3-f6d3-001c6ea2a62f
* Content: [Azure Functions in a hybrid environment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-functions-hybrid)
* Content Source: [docs/hybrid/azure-functions-hybrid.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/azure-functions-hybrid.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/466657/>466657</a>

**Comment by v-fearam** [comment]
#please-close
