### ISSUE TITLE
Minor Typos

### ISSUE THREAD

**Issue by dstar30** [MicrosoftDocs/architecture-center#3004]
[Enter feedback here]
Hi,

Minor typos in the last bullet point under the "When to use this pattern" section (https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view#when-to-use-this-pattern):

- "Thefore, materialized views..." should be "Therefore, materialized views..."
- "If materialized views are not appropiate..." should be "If materialized views are not appropriate..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4ffec9b-27ef-0f8c-5fcf-58347950feaf
* Version Independent ID: 8dadd327-8781-e1ef-e2b3-f75f416524e6
* Content: [Materialized View pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view)
* Content Source: [docs/patterns/materialized-view.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/materialized-view.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/469805/>469805</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@dstar30 Thank you for catching that error in the docs. The fix for these errors has been merged internally and will go-live in the public docs shortly.
