### ISSUE TITLE
VWAN supports multiple VWAN Hubs in a region. 

### ISSUE THREAD

**Issue by mgodfre3** [MicrosoftDocs/architecture-center#3010]
VWAN supports multiple VWAN Hubs in a region.  This is incorrect in the documentation
https://docs.microsoft.com/en-us/azure/architecture/networking/hub-spoke-vwan-architecture
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ba53f7-4773-946c-fffc-cf51122973f8
* Version Independent ID: 802d7f2e-ee23-c3e1-0294-f3941d0c30c2
* Content: [Hub-spoke network topology with Azure Virtual WAN - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/hub-spoke-vwan-architecture)
* Content Source: [docs/networking/hub-spoke-vwan-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/networking/hub-spoke-vwan-architecture.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **yemrea**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/471047/>471047</a>

**Comment by v-fearam** [comment]
Thank you for the feedback. This article was updated to address the product change in 22f90366defa09ce92175733676f30170157b616

**Comment by v-fearam** [comment]
#please-close
