### ISSUE TITLE
vsd

### ISSUE THREAD

**Issue by v7v** [MicrosoftDocs/architecture-center#3012]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62849df7-a49c-f17e-6876-c3da5954789a
* Version Independent ID: a412df8a-f876-d501-6aec-5bc1f010deaa
* Content: [Securing your Microsoft Teams channel bot and web app behind a firewall - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/teams/securing-bot-teams-channel)
* Content Source: [docs/example-scenario/teams/securing-bot-teams-channel.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/teams/securing-bot-teams-channel.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ajafry
* Microsoft Alias: **aljafry**

**Comment by JasRobe** [comment]
this does not appear to be actionable feedback
