### ISSUE TITLE
Oracle Database Migration to Azure

### ISSUE THREAD

**Issue by Asha-Hiremath** [MicrosoftDocs/architecture-center#3015]
Below statement is not clear as to what for is this alternative. I am a Core oracle DBA move into Azure. Please provide clarity to this statement. 

Alternatives
If your database is over 2 TB, you can use Oracle Data Guard with Oracle Recovery Manager (RMAN), or use Data Pump to replicate changes after an initial bulk data transfer, which provides a minimal downtime migration.

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/471584/>471584</a>

**Comment by JasRobe** [comment]
@Asha-Hiremath  the alternative listed here is a suggestion for databases over 2TB, the initial recommendaiton above is suggest for databases under 2TB, does that address your question?

https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/reference-architecture-for-oracle-database-migration-to-azure

**Comment by Asha-Hiremath** [comment]
Thanks for clarifying, Jason!
