### ISSUE TITLE
Please clarify "bi-weekly"

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/architecture-center#3016]
I just recently found out that "bi-weekly" means both every other week and twice a week - so should we update the node OS images every other week or twice a week?

https://www.merriam-webster.com/words-at-play/on-biweekly-and-bimonthly
https://www.thefreedictionary.com/biweekly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43da9bdf-a3d3-a65b-b555-60dcc5ac2c55
* Version Independent ID: 9913c705-aeb7-e154-4fdf-164ff1e7ff99
* Content: [AKS Day-2 Operations Guide - Patch and upgrade guidance - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-upgrade-practices)
* Content Source: [docs/operator-guides/aks/aks-upgrade-practices.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/operator-guides/aks/aks-upgrade-practices.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/471595/>471595</a>

**Comment by ckittel** [comment]
Good point, we should clarify that in the documentation. Image updates typically release once every two weeks (+/- days). It's not a set/fixed schedule as far as I know, but it's usually close to that.

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017692

**Comment by JanetCThomas** [comment]
This issue has been resolved.
