### ISSUE TITLE
Wrong comparison

### ISSUE THREAD

**Issue by magakman** [MicrosoftDocs/architecture-center#3023]
Hi,

You have the wrong comparison in the Firewall section. The equivelent for Azure Firewall is not the web application firewall but rather the "AWS Network Firewall"

See more info here - https://aws.amazon.com/network-firewall/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @BrianQu
* Microsoft Alias: **yuanzhiqu**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/472837/>472837</a>

**Comment by v-fearam** [comment]
#please-close
