### ISSUE TITLE
Security of Azure Timer functions in .Net5

### ISSUE THREAD

**Issue by gopala000** [MicrosoftDocs/architecture-center#3024]
I intend to run scheduled jobs as Azure Timer function in .Net5 isolated process. What is the security model of the Azure timer functions? The questions I couldn't find answers in the documentation are:

1. What process triggers the timer function? How does this process get the access key & secret information of Azure function?
2. Is Azure timer function protected from someone outside the Azure data center running it?
3. I want to inject user context and add claims before invoking a timer function. How do I do this?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 005ff87d-aeb8-7c40-f736-84793b2a70cd
* Version Independent ID: 9053da92-bed6-4ec9-9786-6f8c270ea980
* Content: [Azure Functions security - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/serverless-quest/functions-app-security)
* Content Source: [docs/serverless-quest/functions-app-security.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/serverless-quest/functions-app-security.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @rogeriohc
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/473265/>473265</a>

**Comment by vipulsparsh** [comment]
@gopala000 Thanks for reaching out. We will investigate and update the thread accordingly.

**Comment by PramodValavala-MSFT** [comment]
@gopala000 Hope the following answer your queries

> What process triggers the timer function? How does this process get the access key & secret information of Azure function?

When the function app is scaled to at-least one instance, the instance would trigger itself. When scaled down to zero, the scale controller keeps track of the schedule and brings the function up to one instance when required.

> Is Azure timer function protected from someone outside the Azure data center running it?

It would just trigger based on the schedule and while you can [manually run it](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#manually-invoke-a-timer-trigger), this would require an admin key which is protected with Azure RBAC on the Function App Resource.

> I want to inject user context and add claims before invoking a timer function. How do I do this?

A timer triggered function is just run by the runtime directly. So, there is no context per se. You would have to store the required contexts in a database and have the timer triggered function fetch the data when triggered.

**Comment by JasRobe** [comment]
@gopala000  did the answers above address your questions and we can close this issue now?

**Comment by gopala000** [comment]
Yes. Thank you!!

**Comment by PramodValavala-MSFT** [comment]
@gopala000 Glad we could help!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
