### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3025]
The section that begins with "The Windows N-tier application on Azure with SQL Server reference architecture" is duplicated. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f78e284-fb28-8ac2-0ce6-590b48c74a45
* Version Independent ID: 3baed527-6023-bc26-d3f9-9fda0a43925e
* Content: [Network security and containment in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/network-security-containment)
* Content Source: [docs/framework/security/network-security-containment.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/network-security-containment.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/473280/>473280</a>

**Comment by vipulsparsh** [comment]
@DeanGross Thanks for reaching out. We will investigate and update the thread accordingly.

**Comment by MayankBargali-MSFT** [comment]
@DeanGross Thanks for reporting this item! I have updated the doc and it will be published soon. We appreciate the feedback!
