### ISSUE TITLE
Mention Occlum in this page?

### ISSUE THREAD

**Issue by ysminnpu** [MicrosoftDocs/architecture-center#3026]
[Enter feedback here]
Occlum is a popular open source OS for SGX (to my knowledge the most popular one till now). https://github.com/occlum/occlum
I wonder whether you would like to also mention Occlum in this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42627d53-e6b2-6bf1-321f-41c03dfa61ce
* Version Independent ID: 12cdc300-4b54-a5a1-fe1e-41b8d5a460f2
* Content: [Confidential computing on a healthcare platform - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/confidential/healthcare-inference#architecture)
* Content Source: [docs/example-scenario/confidential/healthcare-inference.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/confidential/healthcare-inference.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @agowdamsft
* Microsoft Alias: **amgowda**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/474145/>474145</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24214 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
