### ISSUE TITLE
Please update this page and the decision tree with more current Azure offerings (such as Azure Spring Cloud)

### ISSUE THREAD

**Issue by thoaingan** [MicrosoftDocs/architecture-center#3030]
Please update this page and the decision tree with more current Azure offerings (such as Azure Spring Cloud). This other page has a more correct and up-to-date services: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/compute-options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/476341/>476341</a>

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@thoaingan  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by ckittel** [comment]
This page should be updated within 24 hours to include more content in the diagram.  The sections below have not yet been updated to reflect the new items in the diagram.  That update will follow later.

**Comment by stephen-sumner** [comment]
@thoaingan - I responded to another thread you opened about this. I believe we've resolved the initial concern you raised. Thank you so much for your feedback!
