### ISSUE TITLE
Azure Performance Manager - missing link

### ISSUE THREAD

**Issue by KSchlobohm** [MicrosoftDocs/architecture-center#3032]
I think this section

```
* Network Performance Manager can generate synthetic traffic to measure the performance of network connections over multiple links, giving you a perspective on the evolution of WAN and Internet connections over time, as well as offering valuable monitoring information about Microsoft ExpressRoute circuits.
```

should link to [Network Performance Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/network-performance-monitor)

or provide a link to the Network Performance Manager feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3cc80c-ef02-227b-7c74-74ddf0b95acf
* Version Independent ID: e71017ca-18a9-a430-635a-14d86b8dbceb
* Content: [Monitoring for DevOps - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/monitoring)
* Content Source: [docs/framework/devops/monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/monitoring.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/477868/>477868</a>
