### ISSUE TITLE
SLA/HW configuration is incorrect in picture

### ISSUE THREAD

**Issue by ClementinoDeMendonca-msft** [MicrosoftDocs/architecture-center#3035]
SLA/HW configuration combination is incorrect in picture in section "SLA offered by Availability Zones".
The SLA for single VMs using **HDD** for the OS disk is 95%. The picture mentions Premium (which requires **SSD**). Easiest fix is to change the picture so that instead of HDD, it would say SSD.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Building solutions for high availability using Availability Zones - High Availability](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/high-availability/building-solutions-for-high-availability.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by v-albemi** [comment]
Resolved in [Build solutions with availability zones - Azure Architecture Center | Microsoft Learn](https://learn.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
