### ISSUE TITLE
Missing term "AKS"

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/architecture-center#3036]
The diagram in the middle of the page - which is great - uses the term "AKS" but I didn't see a definition for this term anywhere.

Thanks, other than that the page was very clear and links to more detailed pages, nice setup. 

== John ==

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by EdPrice-MSFT** [comment]
We're adding this definition. The short answer is that AKS is Azure Kubernetes Service. But we're also linking to our AKS architecture design article: http://aka.ms/AKSArchitecture

**Comment by jgwinner** [comment]
Thank you! This is why I like MS!
