### ISSUE TITLE
Feedback on Azure AD and on-premise AD DS integration

### ISSUE THREAD

**Issue by Bert-Proesmans** [MicrosoftDocs/architecture-center#3041]
The architecture diagram is probably the most interesting resource at the point of setting up a new AD from scratch. If you require on-premise control, assume the Azure AD to be an add-on rather than the core of your directory! Thankfully, hybrid configurations are blessed and will remain supported for some time.

Note that all components on the Azure cloud are brought under a SINGLE TENANT. This means;

- =single organization
- =single "on-premise AD domain", the onmicrosoft.com one
- =multiple routable web domains, but no re-use possible between different tenants
- =single container of Microsoft 365 data (SharePoint, Exchange, Teams/Skype)
- =Microsoft 365 and Azure cloud resources are isolated from other Azure tenants

All your different on-premise AD DS sites and domains get flattened while syncing to Azure AD, so don't make a too complex AD logical structure if you intend to move fully cloud-managed!  
Don't go fully managed cloud (yet) if you require Microsoft Endpoint Configuration Manager (SCCM).

EDIT; OOPS, sorry for the ping. 🙏 
It was my intention to leave a comment for the next reader(s). Not to provide feedback on the content. I figured this was a fully automated way of processing comments for the docs.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbf62e6-49ab-a499-f82e-e0ade93ce2e2
* Version Independent ID: 08bbadc2-c2f9-1c43-b541-e5e2554931fc
* Content: [Multiple forests with AD DS and Azure AD - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/multi-forest)
* Content Source: [docs/example-scenario/wvd/multi-forest.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/multi-forest.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @nehalineogi
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/480121/>480121</a>

**Comment by shashishailaj** [comment]
@Bert-Proesmans Thank you for explaining your intent and providing great inputs to share with the community . We have anyways created an internal item for the team to review and see if we need to restructure the content in any better way for our readers. 

It is great to know that the current content is helping you with your Azure Active directory scenarios. 

Thank you.
