### ISSUE TITLE
As a noun Front End is 2 words, not hyphenated. 

### ISSUE THREAD

**Issue by jenellea** [MicrosoftDocs/architecture-center#3043]
See https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/f/front-end

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7a0267-bb8f-7ae9-8c16-344ad4091b8b
* Version Independent ID: 2ae74da1-c048-995f-b3be-3c92e65c0979
* Content: [Adding a mobile front-end to a legacy app - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/adding-a-modern-web-and-mobile-frontend-to-a-legacy-claims-processing-application)
* Content Source: [docs/solution-ideas/articles/adding-a-modern-web-and-mobile-frontend-to-a-legacy-claims-processing-application.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/adding-a-modern-web-and-mobile-frontend-to-a-legacy-claims-processing-application.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/481765/>481765</a>

**Comment by jenellea** [comment]
Also in Azure Network Watcher Connections for endpoints (also one word), the UI uses 1 work for the subnet 
![image](https://user-images.githubusercontent.com/1796557/131752611-c210eb1d-9ddf-43bc-9727-07287f4933f7.png)
Documentation that accompanies our UI has (often) followed the MS Style Guide, which collides with the actual UI.
