### ISSUE TITLE
Please add comparisons

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3045]
Please add some comparison to this page like is done for the other component pages which actual comparison between the features in AWS and Azure and the Security page for GCP and Azure
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e75f345d-f208-d9c2-f80c-d93db505fab8
* Version Independent ID: 5684d2fa-2569-1c09-ba10-387c75ca7585
* Content: [Multi-cloud security and identity with Azure and AWS - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/security-identity)
* Content Source: [docs/aws-professional/security-identity.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/aws-professional/security-identity.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dougkl007
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/482156/>482156</a>

**Comment by shashishailaj** [comment]
@DeanGross As mentioned by David above , an internal item has ben created on this and we will be working on this internally  and we will close this issue for now. 

Thank you.
