### ISSUE TITLE
Regional failures or Data Center failures?

### ISSUE THREAD

**Issue by ghanique-pra** [MicrosoftDocs/architecture-center#3046]
https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/test-best-practices#plan-for-regional-failures

Does this paragraph intent to say "Plan for regional failures" or "Plan for data center failures"? Azure has Regions that have multiple Availability Zones. Should we plan for one of those Zones (= one data center) to go down, or should we really plan for an entire Region to go down (even when it has more than one Availability Zone)?

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f97257-6e02-a0d4-c428-65fcdfbbd46c
* Version Independent ID: bccfa781-32f2-7651-7c6e-45f241cbc92b
* Content: [Testing best practices for reliability in Azure applications - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/test-best-practices)
* Content Source: [docs/framework/resiliency/test-best-practices.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/resiliency/test-best-practices.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/482828/>482828</a>

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. We are actively investigating and will get back to you soon.

**Comment by v-fearam** [comment]
Hi @ghanique-pra

Sorry for the delay. 

In this case it means "Plan for regional failures" 

Each service  guide can cover both intra-regional resiliency with [availability zones](https://learn.microsoft.com/en-us/azure/reliability/availability-zones-overview) and information on [cross-region resiliency with disaster recovery](https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure). For a more detailed overview of reliability principles in Azure, see [Reliability in Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/architecture/framework/resiliency/).


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
