### ISSUE TITLE
a little girl by a river

### ISSUE THREAD

**Issue by chaugaialberteinstein** [MicrosoftDocs/architecture-center#3048]
interesting =))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0d6438-cac3-e9fb-1515-87a69d406b6b
* Version Independent ID: 50759805-20dd-9ec0-5488-38a9e465e017
* Content: [What is the Team Data Science Process? - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-science-process/overview)
* Content Source: [docs/data-science-process/overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-science-process/overview.md)
* Service: **machine-learning**
* Sub-service: **team-data-science-process**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/482995/>482995</a>

**Comment by femsulu** [comment]
closing since theres no action required or issue raised by OP.
