### ISSUE TITLE
wrong reference

### ISSUE THREAD

**Issue by mounirkam** [MicrosoftDocs/architecture-center#3051]
[Enter feedback here]
the menu item is pointing to a different article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c87f45-5249-92ca-c6e2-75d0d93d5419
* Version Independent ID: 6025ff46-9339-c92b-4a16-bf84d4c50f21
* Content: [Modern Customer Support Portal - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/modern-customer-support-portal-powered-by-an-agile-business-process)
* Content Source: [docs/solution-ideas/articles/modern-customer-support-portal-powered-by-an-agile-business-process.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/modern-customer-support-portal-powered-by-an-agile-business-process.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/484051/>484051</a>

**Comment by YutongTie-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
