### ISSUE TITLE
Update to ANF's best practices

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#3053]
Hi, ANF PM here:

Can you please include a reference to enabling SMB Continuous Availability shares on volumes to ANF's best practices?
A reference to the following pages would be appreciated:

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-create-volumes-smb#continuous-availability
https://docs.microsoft.com/en-us/azure/azure-netapp-files/enable-continuous-availability-existing-smb

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#azure-netapp-files-best-practices)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/484622/>484622</a>

**Comment by shashishailaj** [comment]
@gvanteylingen We have added an internal work item for our discussion on how best we can incorporate the details suggested . At this point we will close this issue and update the article as and how internal discussion goes .
