### ISSUE TITLE
Rewording key sentence in this document

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#3054]
Hi ANF PM here.

Please kindly reword this sentence from:
Azure NetApp Files has the SMB continuous availability shares option turned on. This feature makes SMB Transparent Failover possible, so you can do non-disruptive maintenance on Azure NetApp Files.

to:
Azure NetApp Files has the SMB continuous availability shares option turned on. This feature makes SMB Transparent Failover possible, so you can observe service maintenance events on Azure NetApp Files non-disruptively for your SQL server deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20d261a-2d5e-3a35-42ef-f7438e3dc015
* Version Independent ID: 7b2842eb-9511-d79c-92bb-38d984a97dd0
* Content: [SQL Server on Azure Virtual Machines with Azure NetApp Files - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/file-storage/sql-server-azure-netapp-files)
* Content Source: [docs/example-scenario/file-storage/sql-server-azure-netapp-files.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/file-storage/sql-server-azure-netapp-files.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **deannag**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/484860/>484860</a>

**Comment by EdPrice-MSFT** [comment]
Alex made this update!
