### ISSUE TITLE
visio file link is outdated and does not depict the diagram that is  on the page.

### ISSUE THREAD

**Issue by vikramhn** [MicrosoftDocs/architecture-center#3055]
[Enter feedback here]
visio file link https://arch-center.azureedge.net/app-service-reference-architectures.vsdx is outdated and does not depict the diagram that is  on the page. see attached
![image](https://user-images.githubusercontent.com/17201365/132711977-9f832bde-d0a7-45c0-b569-4bf4eed1d264.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web app - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/485571/>485571</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@vikramhn I believe the one you're looking at is the architecture for **Scalable web app**. Please note that the visio depicted in this document is available in the **Multi-region** tab of the vsdx file:

![image](https://user-images.githubusercontent.com/44050820/132793036-8670bbc3-2fbf-4780-8968-f9ea8e482916.png)

Please check and let us know if you don't find it within the downloaded vsdx.

**Comment by vikramhn** [comment]
My bad. Thanks for pointing that out.
