### ISSUE TITLE
404 Links in Deployment Section

### ISSUE THREAD

**Issue by rayhogan** [MicrosoftDocs/architecture-center#3056]
Under Deployment section there are two 404 links. 

"CluedIn with Docker" is pointing to https://documentation.cluedin.net/docs/00-gettingStarted/30-docker-local.html but it should be pointing to https://documentation.cluedin.net/deployment/docker-compose.

"CluedIn with Kubernetes" is pointing to https://documentation.cluedin.net/docs/00-gettingStarted/40-kubernetes.html but it should be pointing to https://documentation.cluedin.net/deployment/kubernetes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278e83ef-9b90-cb2d-9ff6-0dd8f5ff1b87
* Version Independent ID: 7e63fe30-9080-9207-ad0f-62263379de0c
* Content: [Master data management with Azure and CluedIn - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/cluedin)
* Content Source: [docs/reference-architectures/data/cluedin.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/data/cluedin.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **Oliver.Kaae**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@rayhogan Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review. The changes should reflect post the merge.

**Comment by rayhogan** [comment]
@bhraghun Thanks! Quick turnaround 😊
