### ISSUE TITLE
Update Link to Data Protection

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3057]
The link to data protection points to V1 of the controls, please update it to point to the current V2 documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7296ca61-0150-bb85-6c26-63877177672c
* Version Independent ID: e6093c03-ef4d-647a-3523-5128c6539300
* Content: [Data protection in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/design-storage)
* Content Source: [docs/framework/security/design-storage.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/design-storage.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/485886/>485886</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@DeanGross Thank you for the feedback. I have submitted a PR to point to V2 docs, the change is merged internally and will go-live in the public docs shortly.
