### ISSUE TITLE
Script will not work if multiple Peerings exist

### ISSUE THREAD

**Issue by bjoernhoefer** [MicrosoftDocs/architecture-center#3060]
Hi,

if you have multiple peerings this script will simply fail - as the remove-part will not handle an string-object.

You need a for-each loop

e.g.:
```
foreach ($ExistingvNetPeering in $hubPeerings)
{
	Remove-AzVirtualNetworkPeering -VirtualNetworkName $HubVNetName -ResourceGroupName $HubVNetRGName -name $ExistingvNetPeering.Name -Force
}
```
Also the script does not delete the peering on the other end - so there should be a pause or something else till you delete the other peerings. Otherwise you will run into an error an have to recreate the peering manually (as I did!)

Not the best code quality at all...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636aa53e-3ca0-7a30-fe16-7219f3e8d1a9
* Version Independent ID: c503b39a-cd8a-669a-0882-27d8c13d3570
* Content: [Add IP address spaces to peered virtual networks - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/prefixes/add-ip-space-peered-vnet)
* Content Source: [docs/networking/prefixes/add-ip-space-peered-vnet.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/networking/prefixes/add-ip-space-peered-vnet.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @randycampbell
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/486284/>486284</a>

**Comment by ckittel** [comment]
Thank you @bjoernhoefer  - you're spot on with your observation and your suggestions are very welcome.  I've opened a PR to address this issue and will let you know when that is merged in. Thanks for contributing and making our docs better.

**Comment by ckittel** [comment]
@bjoernhoefer -- after talking with a couple other peers, we are going to hold off on the update as proposed, and instead wrap in the new feature as described in https://azure.microsoft.com/blog/how-to-resize-azure-virtual-networks-that-are-peered-now-in-preview/.

That'll change the script to no longer drop (and re-add) the peerings, but instead check out an out of sync status and perform a sync on those peerings.

**Comment by bjoernhoefer** [comment]
@ckittel yeah, i know this feature - but it is not working in the customers environment (ends up with a error messages)...
Thats why I've ended up with this script - but it ended up in a disconnected peering :-(

**Comment by v-fearam** [comment]
Hi @bjoernhoefer

Sorry for the delay. 

The document has changed since the problem was reported.

The line requested is in the article at this point in time.

![image](https://github.com/MicrosoftDocs/architecture-center/assets/62260324/3ddbaeae-786d-4beb-85b0-c052b4114c7e)


By the way,  Azure virtual networks support adding and removing address space without the need to remove and restablish peerings; instead each remote peering needs a sync operation performed after the network space has changed. The sync can be performed using the Sync-AzVirtualNetworkPeering PowerShell command or from the Azure Portal.

I will close the ticket.


#please-close
