### ISSUE TITLE
Incomplete listings of pages and categories

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/architecture-center#3061]
Looking at the list of available patterns, the 'categories' sub-pages don't seem to list all available categories and the index on the overview page doesn't list all available patterns in the sidebar.

For example, 'Reliability' is a missing category and 'Saga' pattern isn't listed at all on the overview page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [Cloud design patterns - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/)
* Content Source: [docs/patterns/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/index.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/486643/>486643</a>

**Comment by akojo** [comment]
Bump. I was about to file a new report on "Saga" pattern missing from pattern catalog.

**Comment by v-fearam** [comment]
#please-close
