### ISSUE TITLE
Im not happy at what you just did 

### ISSUE THREAD

**Issue by DavidBergeron-eng** [MicrosoftDocs/architecture-center#3062]
I never once said I could supply that

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/487246/>487246</a>

**Comment by DavidBergeron-eng** [comment]
What are my standings

**Comment by DavidBergeron-eng** [comment]
Why would you say that I could scale up to 1000 vms

**Comment by BhargaviAnnadevara-MSFT** [comment]
@DavidBergeron-eng Thank you for the question. In order to best address your question, could you provide us with the URL of the MS Doc that you were following, if any?

**Comment by BhargaviAnnadevara-MSFT** [comment]
> In order to best address your question, could you provide us with the URL of the MS Doc that you were following, if any?

@DavidBergeron-eng Are there any further updates here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@DavidBergeron-eng We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
