### ISSUE TITLE
The "System architecture" diagram needs a fix

### ISSUE THREAD

**Issue by hosseinsarshar** [MicrosoftDocs/architecture-center#3064]
It seems that the "Scoring" and "Training" pipelines in DevOps pipelines are connected to incorrect Pipelines in AML:

![image](https://user-images.githubusercontent.com/4457205/133280981-255f4e38-26a4-485d-be39-5560afe72bee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d13228b-be2e-8374-fbe9-b90b8a05e904
* Version Independent ID: ebd1326f-47ef-2cc6-bb62-ab2e2711558e
* Content: [Machine learning operations (MLOps) framework to upscale machine learning lifecycle with Azure Machine Learning - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/mlops/mlops-technical-paper#basic-model-validation-tests)
* Content Source: [docs/example-scenario/mlops/mlops-technical-paper.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/mlops/mlops-technical-paper.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/488047/>488047</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24809 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
