### ISSUE TITLE
Newer SDKs for Event Hubs and Service Bus should be used in retry guidance

### ISSUE THREAD

**Issue by ramya-rao-a** [MicrosoftDocs/architecture-center#3066]
This page on retry guidance has sections for Event Hubs and Service Bus where the latest SDK is not listed.
Either replace the current content with that for the newer packages Azure.Messaging.EventHubs and Azure.Messaging.ServiceBus.
Or ensure both new and older packages are covered.
If we are covering both, then do emphasize that we recommend the use of the newer ones

@spelluru who is the content developer for these services should be able to help here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#feedback)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/488382/>488382</a>

**Comment by ramya-rao-a** [comment]
@jsquire, @JoshLove-msft Do we have any content on retries in the azure-sdk-for-net repo that we can link to from here for Event Hubs and Service Bus?

**Comment by jsquire** [comment]
Event Hubs has nothing dedicated, but we do discuss configuring retries and timeouts in our [Event Hubs clients](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#configuring-the-client-retry-thresholds) sample.   The [EventHubsRetryOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventhubsretryoptions) documentation covers the details around the individual options that can be tuned.

I don't know of a similar sample for Service Bus, but Josh may...

**Comment by v-fearam** [comment]
The document was updated.
Sorry for the delay.
#please-close
