### ISSUE TITLE
Newer SDK for Azure Search should be used in retry guidance

### ISSUE THREAD

**Issue by ramya-rao-a** [MicrosoftDocs/architecture-center#3067]
This page on retry guidance has a sections for Azure search where the latest SDK is not used.
The package Microsoft.Azure.Search is being used instead of the newer Azure.Search.Documents.

Either replace the current content with that for the newer packageor ensure both new and older packages are covered.
If we are covering both, then do emphasize that we recommend the use of the newer one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/488383/>488383</a>

**Comment by v-fearam** [comment]
#please-close
