### ISSUE TITLE
Translated pages shows markup instead of formatted text

### ISSUE THREAD

**Issue by cataniafran** [MicrosoftDocs/architecture-center#3068]
![image](https://user-images.githubusercontent.com/26816812/133436685-94070496-4ccd-4b2e-874e-0087001e1f69.png)

**Steps to reproduce:**
- Go to [CQRS pattern documentation page](https://docs.microsoft.com/it-it/azure/architecture/patterns/cqrs) in it-it or es-es languages
- Check the second h2 element in page
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [What is the CQRS pattern? - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/488552/>488552</a>

**Comment by hallihan** [comment]
This issue was previously fixed. #please-close
