### ISSUE TITLE
Pricing tier doesn't match the subscription's billing model.

### ISSUE THREAD

**Issue by snodnipper** [MicrosoftDocs/architecture-center#3069]
Unable execute: `az deployment group create --resource-group hub-spoke \
    --template-uri https://raw.githubusercontent.com/mspnp/samples/master/solutions/azure-hub-spoke/azuredeploy.json`

I get this error message:

```shell
$ az deployment group create --resource-group hub-spoke \
    --template-uri https://raw.githubusercontent.com/mspnp/samples/master/solutions/azure-hub-spoke/azuredeploy.json
Please provide string value for 'adminUserName' (? for help): admin
Please provide securestring value for 'adminPassword' (? for help): 
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Pricing tier doesn't match the subscription's billing model. Read http://aka.ms/PricingTierWarning for more details.\",\r\n    \"target\": \"PricingTier\"\r\n  }\r\n}"}]}}
```

Note: I was given a ~$200 "Visual Studio Enterprise Subscription"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/488992/>488992</a>

**Comment by shashishailaj** [comment]
@snodnipper We assume you are talking about the section - [**Deploy with VPN gateway**](https://github.com/mspnp/samples/tree/master/solutions/azure-hub-spoke#deploy-sample) . I think the VS enterprise subscription you have may be of old SKU when it used to have $200 allowance. I am not sure but now VS enterprise based subscription gets $150 allowance per month and many Azure services follow the [newer pricing model](https://azure.microsoft.com/en-us/blog/introducing-a-new-way-to-purchase-azure-monitoring-services/) so you may get some error like this. But we will verify this on our side and let you know further.

**Comment by PramodValavala-MSFT** [comment]
@snodnipper Looks like the problem is with the [legacy SKU](https://github.com/mspnp/samples/blob/master/solutions/azure-hub-spoke/azuredeploy.json#L130) set for the log analytics workspace. I worked up a PR to fix this. Could you give it a shot?

Click this to try deploying from Azure Portal
[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FPramodValavala-MSFT%2Fsamples%2Fpatch-1%2Fsolutions%2Fazure-hub-spoke%2Fazuredeploy.json)

or run the following using Azure CLI
```sh
az deployment sub create --location eastus \
    --template-uri https://raw.githubusercontent.com/PramodValavala-MSFT/samples/patch-1/solutions/azure-hub-spoke/azuredeploy.json
```

**Comment by snodnipper** [comment]
@PramodValavala-MSFT, thanks for that - I just ran it in my subscription and all is good now.  Thanks!
