### ISSUE TITLE
Update Azure Storage Guidance with v12 library

### ISSUE THREAD

**Issue by bdschaap** [MicrosoftDocs/architecture-center#3071]
I believe the the Azure Storage guidance is based on the v11 library.  Please update the guidance for the v12 library which uses the [RetryOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.core.retryoptions?view=azure-dotnet) class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry guidance for Azure services - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-storage)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/491047/>491047</a>

**Comment by skabou** [comment]
It appears the guidance has been updated.  If you are still experiencing an issue, please re-open with additional information.
