### ISSUE TITLE
Please replace **Azure Storage** by storage type in

### ISSUE THREAD

**Issue by kyryd** [MicrosoftDocs/architecture-center#3072]
"The primary landing place for these files is either **Azure Storage** or Azure Data Lake Store. "
**Azure Storage**  is a general definition and has number of implementation in Azure
**Azure Storage** should be replaced by correct storage type 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ac957c-9568-b3f0-d79e-72a36439bee9
* Version Independent ID: e89413dd-8815-3d38-d7f0-6a6d0268db1e
* Content: [Processing CSV and JSON files - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/csv-and-json)
* Content Source: [docs/data-guide/scenarios/csv-and-json.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/csv-and-json.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/491827/>491827</a>

**Comment by kyryd** [comment]
The comment relates to https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/csv-and-json

**Comment by shashishailaj** [comment]
This is being worked internally and we will update it once the internal review is complete .
