### ISSUE TITLE
Please add security monitoring 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3073]
The architecture would be more complete if it included the security monitoring functionality provided by Defender for IoT and Azure Sentinel
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5aff439-e4d1-dd0a-cf12-b86c48d396c6
* Version Independent ID: ab134dad-9a18-14cb-ee43-3910ed2c53b5
* Content: [Environment monitoring and supply chain optimization with IoT - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/environment-monitoring-and-supply-chain-optimization)
* Content Source: [docs/solution-ideas/articles/environment-monitoring-and-supply-chain-optimization.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/environment-monitoring-and-supply-chain-optimization.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @falloutxAY
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/492505/>492505</a>

**Comment by jocontr** [comment]
Thanks for your suggestion, my team has taken this as a feature request for further evaluation.
