### ISSUE TITLE
Add security to all of the architectures

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3074]
Many of the architectures do not contain any type of security monitoring, as such they would be more complete if they included Azure Security Center, Azure Sentinel, and/or Defender for IoT as appropriate

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/492507/>492507</a>
