### ISSUE TITLE
Hub-and-spoke topology

### ISSUE THREAD

**Issue by jracabrera** [MicrosoftDocs/architecture-center#3077]
Hello,

I think that virtual desktops should be in spokes, not in the hub.

Using a "Desktops subnet" in the hub vnet could be an anti-pattern, because the hub vnet is the place to put common services used in all spokes. A hub vnet is not the place to locate workloads.

One reason for the current design could be to highlight the concept of using a spoke vnet to extend capacity and avoid the limitation of Azure subscriptions. But this can be done using a hub-and-spoke model in subscription 1 and a spoke in subscription 2.

Please, consider to change the drawing.

Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Azure Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/493482/>493482</a>

**Comment by ckittel** [comment]
We should consider cross-linking into the multi-subscription variant as part of the review of the suggestion:

[Enterprise-scale support for the Azure Virtual Desktop construction set](https://docs.microsoft.com/azure/cloud-adoption-framework/scenarios/wvd/enterprise-scale-landing-zone)

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24206 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
