### ISSUE TITLE
append only store

### ISSUE THREAD

**Issue by rzurawski** [MicrosoftDocs/architecture-center#3078]
As Martin F. said any store could be used, the only thing you should keep  is properly stored sequece.
Append-only stores might be some kind of optimisation.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing#example)
* Content Source: [docs/patterns/event-sourcing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/event-sourcing.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/493512/>493512</a>

**Comment by skabou** [comment]
It is unclear what the issue is.  If assistance is still needed, please re-open with additional information.
