### ISSUE TITLE
How are apps deployed?

### ISSUE THREAD

**Issue by OneBlueBird** [MicrosoftDocs/architecture-center#3079]
[Enter feedback here]
If we have classic ASP.NET web site and want to deploy them on Dev/QA environment, we should spell out how that installations happen along with VM creation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115fe9d4-6876-b76b-c194-6dbe760f0131
* Version Independent ID: bd2dbb27-a069-8609-5421-33d223df06eb
* Content: [DevTest and DevOps for IaaS solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-iaas)
* Content Source: [docs/solution-ideas/articles/dev-test-iaas.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/dev-test-iaas.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/493969/>493969</a>

**Comment by RobBagby** [comment]
Hi @OneBlueBird - This is a solution idea. The goal of a solution idea is to provide a high-level idea of how an architecture might work, not an implementation. If you are interested in understanding how to deploy to DevTest Labs, please see the product documentation: https://learn.microsoft.com/en-us/azure/devtest-labs/
