### ISSUE TITLE
CI/CD for Azure Power Platform

### ISSUE THREAD

**Issue by srinuprty** [MicrosoftDocs/architecture-center#3081]
I'd like the article [here](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform)  to expand with more information, such as potential use cases, alternative services, implementation considerations, and pricing guidance. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4968f751-e9d6-6a37-c650-908531992510
* Version Independent ID: f9bf0889-546c-eb18-cfa5-72b42fae1fea
* Content: [CI/CD for Microsoft Power Platform - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform)
* Content Source: [docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @sarahparkes
* Microsoft Alias: **meparkes**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/494739/>494739</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24489 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
