### ISSUE TITLE
The method mentioned in this template no longer works

### ISSUE THREAD

**Issue by ajomathew** [MicrosoftDocs/architecture-center#3082]
[Enter feedback here]
ARM template sections mentioned in this no longer works, it's failing with the below errors.

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidJson","message":"Could not find member 'description' on object of type 'SecurityRule'. Path 'properties.securityRules[0].description', line 1, position 70."}]}`

[Github link](https://github.com/mspnp/template-examples) provided as reference in the document is updated with another set of [ARM templates](https://github.com/mspnp/template-examples/blob/master/example3-object-param/deploy.json).

Is this feature of `ARM copy values from object data types` is broken ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 928f1651-0e7e-9389-add5-120cf6ccf0dd
* Version Independent ID: 5399b529-92c2-ac3c-0f66-7cbcfef25c91
* Content: [Use objects as parameters in ARM template - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/azure-resource-manager/advanced-templates/objects-as-parameters)
* Content Source: [docs/guide/azure-resource-manager/advanced-templates/objects-as-parameters.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/azure-resource-manager/advanced-templates/objects-as-parameters.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/495006/>495006</a>

**Comment by ajomathew** [comment]
```
{
            "apiVersion": "2020-11-01",
            "type": "Microsoft.Network/networkSecurityGroups",
            "name": "NSG1",
            "location": "[resourceGroup().location]",
            "properties": {
                "copy": [
                    {
                        "name": "securityRules",
                        "count": "[length(parameters('networkSecurityGroupsSettings').securityRules)]",
                        "input": {
                            "name": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].name]",
                            "properties": {

                                "description": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].description]",
                                "priority": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].priority]",
                                "protocol": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].protocol]",
                                "sourcePortRange": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].sourcePortRange]",
                                "destinationPortRange": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].destinationPortRange]",
                                "sourceAddressPrefix": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].sourceAddressPrefix]",
                                "destinationAddressPrefix": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].destinationAddressPrefix]",
                                "access": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].access]",
                                "direction": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex('securityRules')].direction]"
                            }
                        }
                    }
                ]
            }
        }
```
If NSG section is modified to as above the template is getting deployed

**Comment by MonikaReddy-MSFT** [comment]
@ajomathew - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by v-fearam** [comment]
#please-close
