### ISSUE TITLE
Looking for permission to modify and publish a revision of your data science life cycle diagram, in a new article I would like to publish in Medium

### ISSUE THREAD

**Issue by rozmink** [MicrosoftDocs/architecture-center#3084]
Hello, I saw your data science life cycle picture in an article one of your staff published in Toward Data Science.  Here is that picture:

![image](https://user-images.githubusercontent.com/51712758/135332341-2288e824-2879-4de9-a796-368958cb8534.png)

I have revised the picture to add a focus on social determinants of health and health equity, as follows.  I would like to publish this one in an article I will submit to Medium.    Assuming it would be better to have your permission to revise and use the new picture, will you grant that permission in writing?   Medium requires written permission for borrowed images to be used.

![image](https://user-images.githubusercontent.com/51712758/135332708-87979852-1bd5-492b-b9ce-88f8056db004.png)

Please let me know if you cannot see either image; if you cannot I'd be happy to email both directly, if you send me an email address.

Ron Ozminkowski, PhD
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925cd64a-03a0-dc29-5b52-e51483782d3f
* Version Independent ID: f4ccbd9c-1bc2-c069-9ca8-a34bc61409e2
* Content: [The Team Data Science Process lifecycle - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-science-process/lifecycle)
* Content Source: [docs/data-science-process/lifecycle.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-science-process/lifecycle.md)
* Service: **machine-learning**
* Sub-service: **team-data-science-process**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/495213/>495213</a>

**Comment by EdPrice-MSFT** [comment]
@rozmink - Looks good. Thanks for checking!

Please credit and link to the original article.

**Comment by rozmink** [comment]
Will do, thank you
