### ISSUE TITLE
Title change

### ISSUE THREAD

**Issue by RZomermanMS** [MicrosoftDocs/architecture-center#3085]
[Enter feedback here]

Title needs to change to Azure NVA Firewalls
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9f2509-a3f9-d8bf-e0bf-a9c970d5a423
* Version Independent ID: 62cbc02f-3a6a-2966-380d-af66737f8711
* Content: [Azure Firewall architecture overview - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/firewalls/)
* Content Source: [docs/example-scenario/firewalls/index.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/firewalls/index.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @RZomerman
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/495438/>495438</a>

**Comment by TimShererWithAquent** [comment]
Title changed.
