### ISSUE TITLE
Azure Databricks 

### ISSUE THREAD

**Issue by AnjuPhil** [MicrosoftDocs/architecture-center#3086]
This link helped me to Ingest data into Azure Data bricks and then pushing the same into Delta lake

**Comment by AnjuPhil** [comment]
Done

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/495457/>495457</a>
