### ISSUE TITLE
ARM Template Deployment Fail

### ISSUE THREAD

**Issue by cengxiye** [MicrosoftDocs/architecture-center#3087]
I am deploying the template into my FTE subscription, below error occurs, no matter using Azure Portal or Azure CLI.

It looks like something wrong with:
1. subscription's billing model, is it something wrong with my FTE subscription?
2. workspaces/la-hvrfn3qjegj4s, I don't see there is a need for Log Analytics workspace.

I want to use this template to do a Hands on lab in an event, so attendees can deploy it fairly quick.
Appreciate your help~

```
sid@Azure:~$ az deployment sub create --location eastus \
>     --template-uri https://raw.githubusercontent.com/mspnp/samples/master/solutions/secure-hybrid-network/azuredeploy.json
Please provide string value for 'adminUserName' (? for help): sid
Please provide securestring value for 'adminPassword' (? for help):
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"NotFound\",\r\n         \"message\": \"{\\r\\n  \\\"code\\\": \\\"ResourceNotFound\\\",\\r\\n  \\\"message\\\": \\\"The resource '/subscriptions/6ebbc35d-021b-441a-9fc2-2baa2f94a332/resourcegroups/site-to-site-azure-network/providers/microsoft.operationalinsights/workspaces/la-hvrfn3qjegj4s' doesn't exist.\\\"\\r\\n}\"\r\n          },\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadRequest\\\",\\r\\n    \\\"message\\\": \\\"Pricing tier doesn't match the subscription's billing model. Read http://aka.ms/PricingTierWarning for more details.\\\",\\r\\n    \\\"target\\\": \\\"PricingTier\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz?tabs=portal)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/495889/>495889</a>

**Comment by PramodValavala-MSFT** [comment]
@cengxiye Looks like the problem is with the [legacy SKU](https://github.com/mspnp/samples/blob/master/solutions/secure-hybrid-network/nestedtemplates/azure-network-azuredeploy.json#L116) set for the log analytics workspace. I worked up a PR to fix this. Could you give it a shot?

Click this to try deploying from Azure Portal
[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FPramodValavala-MSFT%2Fsamples%2Fpatch-1%2Fsolutions%2Fsecure-hybrid-network%2Fazuredeploy.json)

or run the following using Azure CLI
```sh
az deployment sub create --location eastus \
    --template-uri https://raw.githubusercontent.com/PramodValavala-MSFT/samples/patch-1/solutions/secure-hybrid-network/azuredeploy.json
```

**Comment by hallihan** [comment]
The sample has been updated with the new Sku value: https://github.com/mspnp/samples/pull/172
