### ISSUE TITLE
Azure icons - Use in commercial books/articles

### ISSUE THREAD

**Issue by ssimsekler** [MicrosoftDocs/architecture-center#3090]
Hello

The Terms of Use for the official Azure icons are not clear on whether these icons could be used royalty-free in commercial books and articles. Can this be clarified?

Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/497135/>497135</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24487 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
