### ISSUE TITLE
Parallel Data Warehouse reference

### ISSUE THREAD

**Issue by theblair** [MicrosoftDocs/architecture-center#3096]
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/data-warehouse?source=docs

There is still a reference on this page to SQL Server Parallel Data Warehouse in the alternatives section... the name changed may years ago to Analytics Platform System and in any case is not something Microsoft is selling.

I would suggest the right on-premise alternative is SQL Server 2019 Big Data Clusters or just SQL Server 2019.

It's also confusing to have multiple Data Warehousing architecture patterns. I think at least this article should link to these 2 articles.

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/small-medium-data-warehouse

**Comment by v-fearam** [comment]
#please-close
