### ISSUE TITLE
Azure Static Web App

### ISSUE THREAD

**Issue by Floriszz** [MicrosoftDocs/architecture-center#3099]
I have seen several simple Azure Static Web App examples outside the MS sites.
Would like to see a more production ready architecture with Azure Static Web App that includes CMS(Like Umbraco 9+), Monitoring, additional Media content(>2Gb) with Azure DevOps Pipelines

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24490 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
