### ISSUE TITLE
Update AKS Monitoring guidance: OpenTelemetry, tracing, more customDimensions, more language examples

### ISSUE THREAD

**Issue by andrejpk** [MicrosoftDocs/architecture-center#3103]
Proposed revisions and additions to [this page](https://docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring):

- The "Structured Logging" session is text/MDC-focused. It seems like the industry is moving towards Spans for most of the use cases MDC was used for. We could rewrite this section with a more OT-focused approach. 
- The "Distributed tracing" section could use some adjustments. Things have moved along quickly in the OT world in the last 6 months and it would be good to talk OT and AI.
  -  The W3C distributed tracing headers are now usually managed automatically by http/messaging libraries and tools in cooperation with OpenTelemetry. Clarify what a typical app developer would do vs what a library/tool author would do.

Possible topics to add (some of these may be too detailed for this article in the AKS docs and could fit better in AI docs):
- Adding build-time telemetry attributes via build params, env vars and AI.json config [1]
- Adding run-time telemetry attributes via env vars in pod definitions (some of this is already in the article) [1]
- Add more language examples (node.js, Python?) (although we didn't get any of that from BD)
- Add a note about alternatives for storing payloads/data for tracing (ADX)

[1]: this is somewhat AI/Java-tailored but could be used with other tools that can read env vars

We'd like feedback before starting. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1160782c-3fd6-3236-1cbd-6ddecf56c3db
* Version Independent ID: cbcfb4e3-4fb5-9427-3a17-cb296339b1ad
* Content: [Monitor a microservices app in AKS - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring)
* Content Source: [docs/microservices/logging-monitoring.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/logging-monitoring.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by EdPrice-MSFT** [comment]
@andrejpk - Thanks for making the edits directly! We'll follow your edits there and review your PR when you're done. Thanks again!
