### ISSUE TITLE
ATP should be replaced with Defender

### ISSUE THREAD

**Issue by dominikhoefling** [MicrosoftDocs/architecture-center#3104]
Original article:
The Log Analytics Agent service collects event and performance data, executes tasks, and other workflows defined in a management pack. Security Center extends its cloud workload protection platforms by integrating with Microsoft Defender Advanced Threat Protection (ATP) for Servers. Together, they provide comprehensive endpoint detection and response (EDR) capabilities.

For more information about Microsoft Defender ATP, refer to Onboard servers to the Microsoft Defender ATP service.

Suggestion:
Replace "Microsoft Defender Advanced Threat Protection (ATP) for Servers" with "Azure Defender for Servers".
Replace "Microsoft Defender ATP" with "Azure Defender for Servers".

Thanks,
Dominik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce3b9c5-ef05-1ff3-a6fe-052f48a9b471
* Version Independent ID: f6d3e8e8-37c5-43e6-6185-58f8511dee7e
* Content: [Hybrid security monitoring with Sentinel - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-security-monitoring?source=docs)
* Content Source: [docs/hybrid/hybrid-security-monitoring.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/hybrid-security-monitoring.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by ShawnKupfer** [comment]
This was fixed in https://github.com/MicrosoftDocs/architecture-center-pr/pull/9727
