### ISSUE TITLE
API management scalability is not "quick"

### ISSUE THREAD

**Issue by jbm00n** [MicrosoftDocs/architecture-center#3108]
Hello,

In this document you say: "To support highly concurrent scenarios, turn on API Management autoscaling. Autoscaling quickly expands API Management capabilities in response to growing numbers of incoming requests".

By experience, API management takes roughly 2 hours to scale, therefore I wouldn't describe it as a way to support highly concurrent scenario if you expect it to "quickly" expand the capabilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/apis/protect-apis)
* Content Source: [docs/reference-architectures/apis/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/apis/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **fabriciosanchez**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/502301/>502301</a>
