### ISSUE TITLE
BlobRequestsOptions - some example involving Blobs would be good - I believe (and hope I'm wrong) that BlobRequestOptions is not actually available - or at least I can't find how to use this

### ISSUE THREAD

**Issue by johndhunter** [MicrosoftDocs/architecture-center#3109]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Azure service retry guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by v-fearam** [comment]
#please-close
