### ISSUE TITLE
Clarify if IoT Hub supports X509 auth over WebSockets

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/architecture-center#3110]
I read in this article:

> Web socket variants of AMQP and MQTT aren't supported with X.509 CA certificates in IoT Hub.

I've not been able to find this limitation in the product docs: 

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-amqp-support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c75be638-b3f3-b73d-fb10-34c91bb0edcd
* Version Independent ID: e4225e21-3462-b35c-21b5-df43fd253b5d
* Content: [Attestation, authentication, provisioning - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/iot/attestation-provisioning)
* Content Source: [docs/example-scenario/iot/attestation-provisioning.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/iot/attestation-provisioning.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @wamachine
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/502436/>502436</a>

**Comment by rido-min** [comment]
found it, X509 CA certs over HTTP is only available in Preview

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-protocols

> AMQP/MQTT/HTTPS over WebSockets is supported by IoT Hub for X.509 thumbprint authentication, but not GA for CA authentication. See: Azure IoT Hub communication protocols and ports | Microsoft Docs
