### ISSUE TITLE
Zonal vs Zone Redundant List seems inaccurate

### ISSUE THREAD

**Issue by Justin-DynamicD** [MicrosoftDocs/architecture-center#3113]
The list of zonal (z) vs zone redundant(zr) seems inaccurate

Example: AKs is listed as zonal, yet in when you deploy a AKS cluster you only select _1_ subnet and declare all the zones you want deployed to. This is a not a zone-isolated deployment. Instead a single subnet hosts a resource that spans multiple zones.  To me this is ZR. If this were zonal, I should be passing a list of subnets to AKS, and each subnet should have a NATGW assigned to it to create a zonal promise.  As of now, I can't self-architect the resiliency which is what I expect from a zonal deployment per the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Build solutions with Availability Zones - High Availability](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/high-availability/building-solutions-for-high-availability.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by v-fearam** [comment]
#please-change
