### ISSUE TITLE
Confusing statement - App Service - Seperate Plan for Production and Test

### ISSUE THREAD

**Issue by ANKGITDEMOS** [MicrosoftDocs/architecture-center#3114]
We used to say all deployment slots with default as Production and other slots like Pre-Prod etc. This brings good cost saving for customer - I can understand from security and management good to keep 2 seperate but can they be merged and we can configure authentication and authorization seperately.

I can understand to keep performance environment out because of common shared infra but can we just re-evaluate this statement.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14bdf5c-81b0-76df-4c61-3b4eca2435ae
* Version Independent ID: 433531d0-bedf-ce5c-a747-ce1d6b6bea5f
* Content: [Resiliency checklist for services - Azure Design Review Framework](https://docs.microsoft.com/en-us/azure/architecture/checklist/resiliency-per-service)
* Content Source: [docs/checklist/resiliency-per-service.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/checklist/resiliency-per-service.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/503563/>503563</a>
