### ISSUE TITLE
Missing word(s) in text

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftDocs/architecture-center#3117]
The text "Ensure all critical impact admins in are managed" misses a word or two

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8c1cdf3-e7a8-ccea-0f3e-e352124a06b9
* Version Independent ID: c014f157-45f9-6dde-9574-0443540bc1c1
* Content: [Administrative account security - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/security/design-admins)
* Content Source: [docs/framework/security/design-admins.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/security/design-admins.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/504686/>504686</a>

**Comment by skabou** [comment]
It appears this has been addressed.  Please re-open with additional details if assistance is still needed.
