### ISSUE TITLE
This page is almost the same as Virtual Machines and reliability, not sure why we need 2 page

### ISSUE THREAD

**Issue by pinyuko** [MicrosoftDocs/architecture-center#3121]
[Enter feedback here]
This page https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/compute/virtual-machines/operational-excellence?branch=pr-en-us-3747 is almost the same as the Virtual Machines and reliability page
https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/compute/virtual-machines/reliability?branch=pr-en-us-3747

Not sure whether it's beneficial for the customers to see this twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886a57e5-bb32-3a15-50e1-35508829aecd
* Version Independent ID: 886a57e5-bb32-3a15-50e1-35508829aecd
* Content: [Virtual Machines and operational excellence - Azure Architecture Center](https://review.docs.microsoft.com/en-us/azure/architecture/framework/services/compute/virtual-machines/operational-excellence?branch=pr-en-us-3747)
* Content Source: [docs/framework/services/compute/virtual-machines/operational-excellence.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/services/compute/virtual-machines/operational-excellence.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-stacywray
* Microsoft Alias: **pnp**

**Comment by skabou** [comment]
If you are still experiencing issues, please re-open with additional information.
