### ISSUE TITLE
Excellent section worthy of it's own page

### ISSUE THREAD

**Issue by jdvcDev** [MicrosoftDocs/architecture-center#3124]
This particular section related to considerations:

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aks-agic/aks-agic#considerations

is an exceptional best practices document for AKS and containerized applications in general.  I would reccommend promoting this guidance to a higher first order level guidance document.  It's hidden away in a very specific edge case'ish page but would be very valuable as a first order document.  I use and reference it in customer architecture conversations, regardless of AGIC/multi tenant AKS context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 869bcb5b-4828-adcd-98f8-fd4681d8110d
* Version Independent ID: 54aade79-aca5-deef-7d26-a7baa22c36c7
* Content: [Use Application Gateway Ingress Controller (AGIC) with a multi-tenant Azure Kubernetes Service (AKS) - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aks-agic/aks-agic#considerations)
* Content Source: [docs/example-scenario/aks-agic/aks-agic.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/aks-agic/aks-agic.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @paolosalvatori
* Microsoft Alias: **paolos**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/505652/>505652</a>
