### ISSUE TITLE
Product names are given for time series storage architecture, but details are missing

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/architecture-center#3127]
In the [Architecture](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/time-series#architecture) section, product names that could be used for storage of time series are mentioned but details are missing.

If possible, I'd like to see a table / comparison of those products
- pros
- cons
- some pointers how to best approach it - e.g. Blob Storage is mentioned but in that case the developer will be required to add some structure. Storing a JSON file with timestamp as filename? Other ideas?
- constraints to keep in mind
  - what data types is it suitable for?
  - what analytics products does it work with?
- best practices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bde15d-d343-b84d-b77f-55b8e3f12638
* Version Independent ID: 9d35a3eb-707b-47f6-68bc-3f22fee4c78c
* Content: [Time series data - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/time-series#feedback)
* Content Source: [docs/data-guide/scenarios/time-series.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/scenarios/time-series.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by hallihan** [comment]
This article has changes significantly since the original suggestion, and links to other articles that incorporate comparisons of storage options.  If you feel there is still a gap, please open a new feedback item with specifics. #please-close
