### ISSUE TITLE
Request for icons: Logic Apps Standard, and connectors

### ISSUE THREAD

**Issue by SvenAelterman** [MicrosoftDocs/architecture-center#3131]
Hi,
Please add the icons for Logic Apps Standard, such as:

- Schemas
- Maps
- Workflows

It would also be useful to have the icons for all connectors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by SvenAelterman** [comment]
@doodlemania2 Any update on the availability of those icons? Thanks!

**Comment by Zimmergren** [comment]
Thank you for reporting this, @SvenAelterman.

We've made several updates to the Azure Icons recently, and there are hundreds of new icons added.
The update is available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

- Relevant Logic Apps icons have been added to the `integration` folder: 
- `02631-icon-service-Logic-Apps.svg`
- `10363-icon-service-Logic-Apps-Custom-Connector.svg`

If you find there are more missing icons, feel free to file a new ticket and we'll get them addressed and updated. 

Thanks!
#please-close
