### ISSUE TITLE
Choice of Ingress Controller

### ISSUE THREAD

**Issue by hansarh** [MicrosoftDocs/architecture-center#3132]
It would be great if this article could reason more the choice of the traefik ingress controller. Especially why you are not using your own Application gateway ingress controller toghether with the application gateway? 
from an architecture standpoint it seems simpler to use as a starting point. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by v-fearam** [comment]
Hi @hansarh 

Sorry for the delay. 

[Here](https://github.com/mspnp/aks-baseline/issues/116#issuecomment-735832685) you will find the information.

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
