### ISSUE TITLE
Mismatched image / reference arch download on page

### ISSUE THREAD

**Issue by toddpliner** [MicrosoftDocs/architecture-center#3134]
Image on the page of the Reference Arch and Visio file download do not match. 
![image](https://user-images.githubusercontent.com/56549037/139140017-c9eaa3a1-f488-4a02-b809-598b02d8e938.png)
![image](https://user-images.githubusercontent.com/56549037/139140127-503cc5de-220b-4a86-84b6-4d371cf388ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84bcf722-abb3-69b8-8073-15ae4a6890de
* Version Independent ID: 7b2010c6-696d-de66-8e56-8ac5d3e54526
* Content: [Basic web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?tabs=cli)
* Content Source: [docs/reference-architectures/app-service-web-app/basic-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/basic-web-app.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by hallihan** [comment]
The image and Visio were updated for this architecture and now match. #please-close
