### ISSUE TITLE
The Picture on Batch processing needs to change

### ISSUE THREAD

**Issue by simonlid** [MicrosoftDocs/architecture-center#3135]
The picture on batch processing needs to be updated to current set, we need to remove references to USQL as an example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7552eb5d-ab91-185b-d6af-fa6aaa233e00
* Version Independent ID: 78d69947-f8c1-9978-476a-58b0763d9eb5
* Content: [Batch processing - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/batch-processing)
* Content Source: [docs/data-guide/big-data/batch-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/big-data/batch-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by skabou** [comment]
Thank you for your feedback.  This article has since been removed.

**Comment by skabou** [comment]
#please-close
