### ISSUE TITLE
Icon request for Storage accounts and API Management

### ISSUE THREAD

**Issue by M4UTR0NI1C** [MicrosoftDocs/architecture-center#3136]
Hi,
Please add the icons for Storage accounts and API Management, such as:

Storage accounts
- Containers
- Blobs
- Tables
- Pages

API Management
- APIs
- Products

It would also be useful to have the icons.

**Comment by MayankBargali-MSFT** [comment]
@M4UTR0NI1C Can you share the document that you are referring to?

**Comment by M4UTR0NI1C** [comment]
Hello @MayankBargali-MSFT, Thank you for your anwser, this request is for add few icons to Architecture pack. You can see the icons [here](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-add-products?tabs=azure-portal), aditionally, i attah 2 files to this thread.
![iconsAzureStorage](https://user-images.githubusercontent.com/93393881/139687683-58714f3a-829f-4ce0-acc1-25e221972e7e.png)
![iconsAPIManagement](https://user-images.githubusercontent.com/93393881/139687685-60431903-cb03-480b-948b-7fe574df7382.png)

Regards.

**Comment by David-Summers** [comment]
Hi @M4UTR0NI1C I have these icons in my non official collection https://github.com/David-Summers/Azure-Design

**Comment by Zimmergren** [comment]
Thank you for reporting this, @M4UTR0NI1C.

We've made several updates to the Azure Icons recently, and there are hundreds of new icons added. 
The update is available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

#please-close
