### ISSUE TITLE
Text would be better served if there were "sub-images" showing each described data flow.

### ISSUE THREAD

**Issue by lorrinferdinand** [MicrosoftDocs/architecture-center#3140]
The relationship between the impressive architecture diagram and the text gets lost since the architecture is all-encompassing and the text is specific to a pathway through the diagram. It might be useful to show a carve out for each text block establishing the linkage between which part of the diagram the text is referring to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f10895e-4e1d-1cdd-2d57-32880e0cc45a
* Version Independent ID: 3518d0a5-ffd1-dfa7-6d6b-de2a9ef170d6
* Content: [Analytics end-to-end with Azure Synapse - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end)
* Content Source: [docs/example-scenario/dataplate2e/data-platform-end-to-end.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/dataplate2e/data-platform-end-to-end.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @fabragaMS
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/509710/>509710</a>

**Comment by v-fearam** [comment]
Hi @lorrinferdinand
Sorry for the delay. 
I was reading the document. The scenarios are explained based on the source, and then follow the rows.
![image](https://github.com/MicrosoftDocs/architecture-center/assets/62260324/bea6349e-c123-4e16-9ec6-a601e4d946f0)

Each section has the name of the source in the title.
Example:
 * [the first section](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?tabs=portal#azure-data-services-cloud-native-htap-with-azure-cosmos-db-and-dataverse) starts with “Azure data services”, which is the last source.
* [the second section](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?tabs=portal#relational-databases) name is “Relational databases”, which is the second source from bottom to top. 
* [Semi-structured data sources](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?tabs=portal#semi-structured-data-sources). The middle source.
* [Non-structured data sources](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?tabs=portal#non-structured-data-sources). The second source from the top.
* [Streaming](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?tabs=portal#streaming). The top source.


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
