### ISSUE TITLE
What does the TDSP lifecycle have in common with the other Microsoft framework, the DSLP?

### ISSUE THREAD

**Issue by ecm200** [MicrosoftDocs/architecture-center#3143]
What is the relationship between the TDSP lifecycle and the DSLP (Data Science Lifecycle Process - https://github.com/dslp/dslp)?

Are these competing mantras on data science process or is one the parent of the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925cd64a-03a0-dc29-5b52-e51483782d3f
* Version Independent ID: f4ccbd9c-1bc2-c069-9ca8-a34bc61409e2
* Content: [The Team Data Science Process lifecycle - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-science-process/lifecycle)
* Content Source: [docs/data-science-process/lifecycle.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-science-process/lifecycle.md)
* Service: **machine-learning**
* Sub-service: **team-data-science-process**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/510713/>510713</a>

**Comment by marktab** [comment]
@ecm200 In the spirit of innovation, these two frameworks have been independently developed and used by different teams at Microsoft. To my knowledge, TDSP is the older and more well-established framework.  Both convey high level architectural ideas, which are of use during project scoping.  Feel free to use what you believe is helpful.

I work with the team supporting TDSP, and if you have any specific feedback on how to clarify its mission, feel free to open a Github request.  One area where we continue to provide latest relevance is when we link to Microsoft or external technologies -- and sometimes the links change or the names of sites change.  We will stay current when we learn of such evolutions.  Take care.

**Comment by marktab** [comment]
@david-stanford  this Github issue is a question rather than an issue, so you may close if you want.

@ecm200  You may connect with me on LinkedIn if you want to talk about TDSP -- happy to help.

**Comment by JasRobe** [comment]
closing as the inquiry was addressed by @marktab above.
