### ISSUE TITLE
‘times’ --> 'the time'

### ISSUE THREAD

**Issue by Lois-TW** [MicrosoftDocs/architecture-center#3145]
[Enter feedback here]
just one tiny thing:  

should the 'times' in the following sentence be changed to 'time' since the noun 'time' is uncountable, right? 

The application waits a short time before the first retry, and then exponentially increasing times between each subsequent retry.

(This sentence appears in 'Exponential back-off' and 'Incremental intervals' under "Determining the appropriate intervals between retries" 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ff3ea0-9b53-16bb-b81f-a12074ad75d0
* Version Independent ID: 4e37c8ba-cbb5-1e3d-6186-ccb2ed6553bd
* Content: [Retry general guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults)
* Content Source: [docs/best-practices/transient-faults.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/transient-faults.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/511148/>511148</a>

**Comment by JasRobe** [comment]
thank you for bringing this to our attention, the recommendation should now be addressed .
