### ISSUE TITLE
Include file markdown showing

### ISSUE THREAD

**Issue by asears** [MicrosoftDocs/architecture-center#3146]
Some markdown showing instead of the include on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2437c95-370a-8dfb-dce8-63628175c6db
* Version Independent ID: 5af86e89-9738-50cd-72a7-a907b5bdc107
* Content: [Vision classifier model with Azure Custom Vision Cognitive Service - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dronerescue/vision-classifier-model-with-custom-vision)
* Content Source: [docs/example-scenario/dronerescue/vision-classifier-model-with-custom-vision.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/dronerescue/vision-classifier-model-with-custom-vision.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jocontr
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/512248/>512248</a>

**Comment by AnuragSingh-MSFT** [comment]
@asears, Thanks for the feedback! We are currently investigating and will update you shortly.
