### ISSUE TITLE
Add ANF to diagram

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#3147]
Geert van Teylingen (ANF PM) here. While the document does describe Azure NetApp Files (ANF) as a valid storage option, the diagram does not show the icon. Can this be added for clarity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf87174-bde3-8399-28a1-124fbb2bb14b
* Version Independent ID: 308cc07d-ffe6-55df-4e21-439c78113f49
* Content: [General mainframe refactor to Azure - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/mainframe/general-mainframe-refactor)
* Content Source: [docs/example-scenario/mainframe/general-mainframe-refactor.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/mainframe/general-mainframe-refactor.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jjfrost
* Microsoft Alias: **jfrost**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/512656/>512656</a>

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
