### ISSUE TITLE
Add ANF to diagram

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#3148]
Geert van Teylingen (ANF PM) here. While the document described Azure NetApp Files (ANF) as a valid storage option, the diagram does not show the ANF icon. Can ANF be added to the diagram for clarity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26f6dbb7-80a3-9303-360d-28405ecee4e0
* Version Independent ID: 26f6dbb7-80a3-9303-360d-28405ecee4e0
* Content: [Refactor mainframe applications with Advanced - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/mainframe/refactor-mainframe-applications-advanced)
* Content Source: [docs/example-scenario/mainframe/refactor-mainframe-applications-advanced.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/mainframe/refactor-mainframe-applications-advanced.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @bhbandam
* Microsoft Alias: **bhbandam**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/512657/>512657</a>

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2034133

**Comment by JKirsch1** [comment]
@gvanteylingen: To address this issue, I'm adding the Azure NetApp Files icon to the diagram. Should it appear on the left side of the label for step 7, or the right side, or both sides?

Here's an image with the icon on both sides:
![refactor-mainframe-applications-advanced-post](https://user-images.githubusercontent.com/64430327/223149028-7e45506f-b0ba-4333-b16c-690da8a5f150.png)

**Comment by gvanteylingen** [comment]
Hi @JKirsch1 , ANF should be included in both sides under (7).

**Comment by JKirsch1** [comment]
> Hi @JKirsch1 , ANF should be included in both sides under (7).

@gvanteylingen: Thanks for getting right back to me! I appreciate your prompt response.

**Comment by JKirsch1** [comment]
[PR 9748](https://github.com/MicrosoftDocs/architecture-center-pr/pull/9748) addresses this issue by adding the Azure NetApp Files icon to the diagram.

**Comment by JKirsch1** [comment]
[PR 9748](https://github.com/MicrosoftDocs/architecture-center-pr/pull/9748) has now merged, and the updated diagram (and thumbnail) should go live at 10:30 a.m. Pacific Time today.
