### ISSUE TITLE
Use full service name for Azure NetApp Files

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#3149]
Geert van Teylingen (ANF PM) here. Can you rename 'NetApp' to the actual full service name 'Azure NetApp Files' in this sentence:  

Data services use a combination of high-performance storage on Ultra or Premium solid-state disks (SSDs), file storage on **Azure NetApp Files** or Azure Files, and standard blob, archive, and backup storage that can be locally redundant or geo-redundant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d151997c-4629-0167-3bb8-f14e35c119dc
* Version Independent ID: 2a7f8f92-e594-c6c1-07ce-a02d4d47af24
* Content: [Refactor IBM z/OS Coupling Facility - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/zos/refactor-zos-coupling-facility)
* Content Source: [docs/reference-architectures/zos/refactor-zos-coupling-facility.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/zos/refactor-zos-coupling-facility.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/512661/>512661</a>

**Comment by SamaraSoucy-MSFT** [comment]
I've put in a PR to update the doc. It will go live once the doc author has approved it.
