### ISSUE TITLE
Use full service name for Azure NetApp Files

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#3150]
Geert van Teylingen (ANF PM) here. Can you use the full service name for 'Azure NetApp Files' in this sentence:

Data services use a combination of high-performance storage on Ultra or Premium solid-state disks (SSDs), file storage on **Azure NetApp Files** or Azure Files, and standard blob, archive, and backup storage that can be locally redundant or geo-redundant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee474b78-4f66-bf85-33cc-59addf5e0c3d
* Version Independent ID: a381b3c3-ebad-86b4-56ff-133d2490e944
* Content: [Refactor mainframe applications to Azure with Raincode compilers - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-modernization/raincode-reference-architecture)
* Content Source: [docs/reference-architectures/app-modernization/raincode-reference-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-modernization/raincode-reference-architecture.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **jfrost**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/512662/>512662</a>

**Comment by SamaraSoucy-MSFT** [comment]
I've put in a PR to update the doc. It will go live once the doc author has approved it.
