### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by mashahmed** [MicrosoftDocs/architecture-center#3151]
Be good to see this solution using GitHub Actions rather than Azure DevOps. 
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-azure

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/512766/>512766</a>

**Comment by mashahmed** [comment]
Discovered: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-github

**Comment by AjayKumar-MSFT** [comment]
> mashahmed
> Discovered: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-github

It looks like you have found the doc that you're looking for. Thanks for the follow-up and update. If you have further questions on this topic, please let us know.
