### ISSUE TITLE
pre-configured cost profile not working

### ISSUE THREAD

**Issue by xjohnyknox** [MicrosoftDocs/architecture-center#3153]
[Enter feedback here]
The link you create is not working:
https://azure.com/e/a8c4809dab444c1ca4870c489fbb196b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5dbc36d-1197-0b73-d0fe-2c9dd5f1d17d
* Version Independent ID: b2285023-1f19-d037-e1c5-18b0b65009df
* Content: [Scalable and secure WordPress on Azure - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/wordpress)
* Content Source: [docs/example-scenario/infrastructure/wordpress.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/infrastructure/wordpress.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/513731/>513731</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@xjohnyknox Thanks for the feedback. Could you please let us know what is not working as expected?

I'm able to load the pre-configured cost profile and see respective estimates. When you open the link, you have the option to login with a Microsoft account that has access to the licensing program, or view the estimate with Microsoft Customer Agreement retail pricing. I've verified that it does work either way.

![image](https://user-images.githubusercontent.com/44050820/140599050-e71437be-7632-4031-8b84-9985cd9cf878.png)

**Comment by BhargaviAnnadevara-MSFT** [comment]
@xjohnyknox Any further update on this?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@xjohnyknox We will now proceed to close this thread, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
