### ISSUE TITLE
cqrs Sample From Microsoft

### ISSUE THREAD

**Issue by AhmadSaadat1399** [MicrosoftDocs/architecture-center#3154]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [What is the CQRS pattern? - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/513832/>513832</a>

**Comment by PramodValavala-MSFT** [comment]
@AhmadSaadat1399 Looks like you've closed this issue immediately. I hope you were able to find what it is you were looking for. 😃
