### ISSUE TITLE
Recommending the enterprise distribution of NiFi

### ISSUE THREAD

**Issue by dennisjaheruddin** [MicrosoftDocs/architecture-center#3157]
Please note that the patterns make sense from a technical view, but that the choice of which NiFi release to use deserves some attention.
The scenario here focuses on raw, unaudited and unsupported NiFi.
However, one of the largest Microsoft partners (Cloudera) provides support for NiFi, as well as surrounding functionality which is typically desirable in an enterprise setting.

As such, please also refer to this option, or perhaps recommend it as the Cloudera offering is in fact available through the Azure Marketplace: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/cloudera.cloudera-data-platform-public-cloud-contact?tab=overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0118fc84-ea7e-0c80-d2a3-ea9516a98516
* Version Independent ID: 0118fc84-ea7e-0c80-d2a3-ea9516a98516
* Content: [Apache NiFi on Azure - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/azure-nifi)
* Content Source: [docs/example-scenario/data/azure-nifi.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/data/azure-nifi.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @MuazmaZ
* Microsoft Alias: **muzahid**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/514604/>514604</a>

**Comment by v-fearam** [comment]
#please-close
