### ISSUE TITLE
Non-functioning verification step

### ISSUE THREAD

**Issue by scaswell-hirez** [MicrosoftDocs/architecture-center#3159]
The implementation guide in the linked github repo has a flaw.

Step 5 on https://github.com/mspnp/aks-secure-baseline/blob/main/09-workload.md

$> kubectl run curl -n a0008 -i --tty --rm --image=mcr.microsoft.com/azure-cli --limits='cpu=200m,memory=128Mi'11

This command does not produce a working terminal to verify the workload is performing as expected.

Expected output is a working terminal inside the private dns zone

Actual output:
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: error dialing backend: dial tcp 10.240.0.39:10250: i/o timeout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/514842/>514842</a>

**Comment by ckittel** [comment]
@scaswell-hirez, thank you for taking the time to report this.  I've moved this issue over to the repo related to the reference implementation.  We can carry the conversation forward there.  See: mspnp/aks-secure-baseline#257
