### ISSUE TITLE
Incomplete Choose Candidate Workflow for Lift+Shift  Containerised Decision path

### ISSUE THREAD

**Issue by quanster** [MicrosoftDocs/architecture-center#3165]
When following the Lift+Shift -> Can it be Containerised -> No Path I found this somewhat unclear/confusing and needing clarification.

Can it be Containerised = No
- we are already in a path of it can't be containerised;
- however the next decision point is "COTS App that can't be containerised"  then land this as install COTS on VM;
- the catchall alternative path is App Service; is this making assuming that it is a web/http app which may not be the case?
Should there be additional decision point for App Service or VM depending on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choosing an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/515405/>515405</a>

**Comment by SumanthMarigowda** [comment]
@quanster Thanks for your question. We are checking on this and will respond to you soon.

**Comment by PramodValavala-MSFT** [comment]
@quanster Yes. That is correct. To quote the doc

> The output from this flowchart is a starting point for consideration. Next, perform a more detailed evaluation of the service to see if it meets your needs.

So, while App Service would be a smart choice for many cases since it takes care of a lot of things except the application itself but it's not necessary that all scenarios should fit. You might have to deploy them to VM depending on limitations on App Service and/or specific requirements of your application.

**Comment by quanster** [comment]
Thanks Pranod; understand and noted is starting point of evaluation.

**Comment by PramodValavala-MSFT** [comment]
@quanster Glad we could help! Since there is no doc update required here, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
