### ISSUE TITLE
Slash before operations?

### ISSUE THREAD

**Issue by grayjeremy** [MicrosoftDocs/architecture-center#3167]
I'm not familiar with any mathematical nomenclature that uses a slash before an operand. 
Can we remove the leading slash or explain its meaning?  

I would expect this "((1 − N) \^ R)" to be "((1 − N) ^ R)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f7448a-64b8-4a45-607a-1a81792a4d96
* Version Independent ID: acfa6055-a2ac-2642-a7c7-a9da10473549
* Content: [Business Metrics - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/resiliency/business-metrics#composite-slas)
* Content Source: [docs/framework/resiliency/business-metrics.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/resiliency/business-metrics.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/515843/>515843</a>

**Comment by ckittel** [comment]
This change has been published. Closing.

Thanks @grayjeremy and @v-stacywray

**Comment by grayjeremy** [comment]
Should we also do it to these occurrences? 
"Web app and (database or queue) = 99.95% × 99.99999% = \~99.95%"
"The combined SLA for two regions = (1 − (1 − 0.9995) \^ 2) = 99.999975%"
"The combined SLA for four regions = (1 − (1 − 0.9995) \^ 4) = 99.999999%"
