### ISSUE TITLE
Typo - Repeated Word

### ISSUE THREAD

**Issue by gregharen** [MicrosoftDocs/architecture-center#3168]
Under Reference Architecture -> AKS baseline cluster -> Cluster Access -> Local Accounts 

The second sentence has the word "access" twice in a row. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/515867/>515867</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@gregharen Thank you for catching that error in the docs. The PR to fix this issue is merged internally and will go-live in the public docs shortly.
