### ISSUE TITLE
Add address space with peering script does not work

### ISSUE THREAD

**Issue by Candelit** [MicrosoftDocs/architecture-center#3170]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636aa53e-3ca0-7a30-fe16-7219f3e8d1a9
* Version Independent ID: c503b39a-cd8a-669a-0882-27d8c13d3570
* Content: [Add IP address spaces to peered virtual networks - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/prefixes/add-ip-space-peered-vnet)
* Content Source: [docs/networking/prefixes/add-ip-space-peered-vnet.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/networking/prefixes/add-ip-space-peered-vnet.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @randycampbell
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/516589/>516589</a>

**Comment by Candelit** [comment]
We tried this since it was impossible still to add an address space to a peered Vnet...I'm guessing that the resync in the portal is yet to come 100%...

We also have more than one peering, whick is considered in the 'reestablish' section in the script, but not in the 'remove' step.

We have all vNets in different subscriptions...so this also fails.

And, adding back the peering is not possible if a resync has not been done on the remote peering.

I have tried to make it work better here:

Please reuse if you want to:

$IPAddressRange = "10.12.0.0/16"
$HubVNetSubscriptionName = "Folitest"
$HubVNetRGName = "rg-folitest-infra"
$HubVNetName = "vn-folitest"
Connect-AzAccount
#Set context to Hub VNet Subscription
Get-AzSubscription -SubscriptionName $HubVNetSubscriptionName | Set-AzContext
#end

#Get All Hub VNet Peerings and Hub VNet Object
$hubPeerings = Get-AzVirtualNetworkPeering -ResourceGroupName $HubVNetRGName -VirtualNetworkName $HubVNetName
$hubVNet = Get-AzVirtualNetwork -Name $HubVNetName -ResourceGroupName $HubVNetRGName
#end

#Remove All Hub VNet Peerings
foreach ($vNetPeeringOld in $hubPeerings){
    Remove-AzVirtualNetworkPeering -VirtualNetworkName $HubVNetName -ResourceGroupName $HubVNetRGName -name $vNetPeeringOld.Name -Force
    Write-Host $vNetPeeringOld.Name
}
#end

#Add IP address range to the hub vnet
$hubVNet.AddressSpace.AddressPrefixes.Add($IPAddressRange)

#Apply configuration stored in $hubVnet
Set-AzVirtualNetwork -VirtualNetwork $hubVNet
#end

foreach ($vNetPeeringNew in $hubPeerings)
{
    # Get remote vnet name
    $RemotevNetFullId = $vNetPeeringNew.RemoteVirtualNetwork.Id
    Write-Host $RemotevNetFullId
    $RemotevNetName = $RemotevNetFullId.Substring($RemotevNetFullId.LastIndexOf('/') + 1)
    Write-Host $RemotevNetName
    $vNetSubscriptionId = ($RemotevNetFullId).Split("/")[2]
    Write-Host $vNetSubscriptionId

    # Pull remote vNet object
    Get-AzSubscription  -SubscriptionId $vNetSubscriptionId  | Set-AzContext
    $vNetObj = Get-AzVirtualNetwork -Name $RemotevNetName
    Write-Host $vNetObj.Name

    # Get the peering from the remote vnet object
    $peeringName = $vNetObj.VirtualNetworkPeerings.Where({$_.RemoteVirtualNetwork.Id -like "*$($hubVNet.Name)"}).Name
    $peering = Get-AzVirtualNetworkPeering -ResourceGroupName $vNetObj.ResourceGroupName -VirtualNetworkName $RemotevNetName -Name $peeringName
    Write-Host $peeringName
    Write-Host $peering.Id

    #Sync the remote peering with the new addressspace before reconnecting
    Sync-AzVirtualNetworkPeering $peering

    # Reset to initiated state
    Set-AzVirtualNetworkPeering -VirtualNetworkPeering $peering

    # Re-create peering on hub
    Add-AzVirtualNetworkPeering -Name $vNetPeeringNew.Name -VirtualNetwork $HubVNet -RemoteVirtualNetworkId $RemotevNetFullId -AllowGatewayTransit
}

**Comment by SumanthMarigowda** [comment]
@Candelit Thanks for your question. We are checking on this and will respond to you soon.

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!

**Comment by skabou** [comment]
It appears this issue has been resolved.  If you are still experiencing issues, please re-open with additional information.
