### ISSUE TITLE
Association table between ResourceType and icon

### ISSUE THREAD

**Issue by sintetico82** [MicrosoftDocs/architecture-center#3171]
Hello,

It's a great set of icons. Is there the possibility to add a CSV file with the association between ResourceType and icon? For example:

`
Microsoft.Compute/virtualMachines;icon-xxx.svg
`

I am trying to make a custom data representation exported from Azure and I would love to automatic connect resources with the corresponding icons.

Thank you 🎈

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/516603/>516603</a>

**Comment by SumanthMarigowda** [comment]
@sintetico82 Thanks for your question. We are checking on this and will respond to you soon.

**Comment by sintetico82** [comment]
Good morning,

Any update on this?

**Comment by hallihan** [comment]
@sintetico82 Thanks for the suggestion, it has been shared with the team that generates the icon file. I don't have anything to share regarding whether this will be implemented. #please-close

**Comment by sintetico82** [comment]
Ok, I hope the team that generates the icon file can do it. 

Anyway, thank you sintentico82 of 2021 for your suggestion from the sintetico82 of 2023! 
I appreciate the young sintentico82 and the love in what you were doing <3
