### ISSUE TITLE
Azure Notebooks

### ISSUE THREAD

**Issue by bsherwin** [MicrosoftDocs/architecture-center#3172]
Since Azure Notebooks is no longer available, should this be removed...not just redirected to VSCode support of notebooks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97abbeb4-6c20-4dfd-8a3f-3b448919679c
* Version Independent ID: d979d82d-2e80-5a1e-7928-7f8154ed34f3
* Content: [Choose a data analytics and reporting technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analysis-visualizations-reporting)
* Content Source: [docs/data-guide/technology-choices/analysis-visualizations-reporting.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/analysis-visualizations-reporting.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/516672/>516672</a>

**Comment by SumanthMarigowda** [comment]
@bsherwin Thanks for your question. We are checking on this and will respond to you soon.

**Comment by EdPrice-MSFT** [comment]
Yes, we just need to update the text. Even the link is still valid.

**Comment by v-fearam** [comment]
#please-close
