### ISSUE TITLE
article date missing, no definition of Ethereum PoA and no mention on deprecation

### ISSUE THREAD

**Issue by adileica** [MicrosoftDocs/architecture-center#3174]
The article is not dated.
There is no definition of PoA in Ethereum context.
And unclear whether the deprecation is already active

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f6b2cc-f78e-7b52-24f0-3d16bdfb2e1b
* Version Independent ID: 4c8a4727-ef28-d68c-2c1f-df3b9fb904ac
* Content: [Decentralized trust between banks - Azure Example Scenarios](https://docs.microsoft.com/en-gb/azure/architecture/example-scenario/apps/decentralized-trust)
* Content Source: [docs/example-scenario/apps/decentralized-trust.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/decentralized-trust.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @vitoc
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/517670/>517670</a>

**Comment by EdPrice-MSFT** [comment]
All our dates are missing from the architectures. Great points.

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
