### ISSUE TITLE
Recommend using AadIssuerValidator

### ISSUE THREAD

**Issue by jmprieur** [MicrosoftDocs/architecture-center#3176]
For https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/claims#issuer-validation, you might be interested in the new [Microsoft.IdentityModel.Validators](https://www.nuget.org/packages/Microsoft.IdentityModel.Validators/) NuGet package, which provides an issuer validator for AAD and AAD B2C single and multi-tenant apps for the public cloud and sovereign clouds:

See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/3eb940655dcf9f685fc3979bfd63185cb8a8bf55/src/Microsoft.IdentityModel.Validators/AadIssuerValidator/AadIssuerValidator.cs#L175-L178

```csharp
AadIssuerValidator aadIssuerValidator = AadIssuerValidator.GetAadIssuerValidator(authority, httpClient);
TokenValidationParameters.IssuerValidator = aadIssuerValidator.Validate;
```

Microsoft.Identity.Web is using it, btw

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d00031-82e8-a8ee-0a66-e9b84231e837
* Version Independent ID: 9a9da08f-83e2-c493-61af-c4b5316c6f8e
* Content: [Claim-based identities in multitenant apps - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/claims)
* Content Source: [docs/multitenant-identity/claims.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/claims.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/518417/>518417</a>

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
