### ISSUE TITLE
Recommend token cache serialization in MSAL.NET article

### ISSUE THREAD

**Issue by jmprieur** [MicrosoftDocs/architecture-center#3177]
[Enter feedback here]

You might be interested in the content (or link to) the following article:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab204a8d-c451-ef99-6610-139a0dee61ac
* Version Independent ID: 23a69ae2-70bc-aab5-bbe1-e9699d57558b
* Content: [Cache access tokens in a multitenant app - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache)
* Content Source: [docs/multitenant-identity/token-cache.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/token-cache.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/518419/>518419</a>

**Comment by EdPrice-MSFT** [comment]
Adding the link. 

https://github.com/MicrosoftDocs/architecture-center-pr/pull/4667
