### ISSUE TITLE
Protocol and client options - RDSTLS vs PKU2U 

### ISSUE THREAD

**Issue by michaelpace-bjss** [MicrosoftDocs/architecture-center#3178]
The "Protocol and client options" is somewhat confusing  and suggest breaking into two sections

First section RDSTLS protocol, as this handles the wider number of clients and does not require local computer to domain joined to the same tenant as the AVD session host, which I think norm. User on personal or organisation 'A' device connecting to organisation 'B' AVD infrastructure.

Second section PKU2U protocol, as this will only work with Windows Azure Virtual Desktop client and requires both local computer and session host to be domain joined to the same tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96947883-d52b-1ed8-7db2-915f025060af
* Version Independent ID: 96947883-d52b-1ed8-7db2-915f025060af
* Content: [Azure AD join for Azure Virtual Desktop - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join)
* Content Source: [docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/518821/>518821</a>

**Comment by KranthiPakala-MSFT** [comment]
Thank you for the feedback.

**Comment by EdPrice-MSFT** [comment]
We have this captured as an article to improve. Thank you for your feedback!
