### ISSUE TITLE
No Visio file ?

### ISSUE THREAD

**Issue by anjaneshbabu** [MicrosoftDocs/architecture-center#3182]
Great  resource but the link to download the Visio file is missing on this page.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/522131/>522131</a>

**Comment by skabou** [comment]
It appears the Visio diagram is available.  If assistance is still needed, please re-open with additional details.
