### ISSUE TITLE
Azure Public Service Icons V - Architecture Icons

### ISSUE THREAD

**Issue by lizzyhbell** [MicrosoftDocs/architecture-center#3183]
After submitting agreeing to the terms of use Icons are supposed to be available in SVG format- but the only thing that downloads is HTML files. I need a scalable set of icons for a diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/#more-icon-sets-from-microsoft)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/522391/>522391</a>

**Comment by PramodValavala-MSFT** [comment]
@lizzyhbell I can confirm the files present are indeed SVG files. Your browser might be the default application to handle the file type but you should be able to use them where ever SVG files can be imported.

![image](https://user-images.githubusercontent.com/43602528/142967947-7c6b3888-1802-48d9-9b13-216559db75b6.png)

**Comment by lizzyhbell** [comment]
Thanks- it was a list view thing, even if I select a detailed list, the .svg won't show in Explorer.
![Screenshot 2021-11-22 201404](https://user-images.githubusercontent.com/94881676/142970451-5077fb93-b273-46f7-8327-b0ca6d55cbdd.png)

**Comment by lizzyhbell** [comment]
Didn't realize that displaying .svg, or .pptx was an option on Windows 11.

**Comment by PramodValavala-MSFT** [comment]
@lizzyhbell Yes. Here is the option

![image](https://user-images.githubusercontent.com/43602528/142994941-724c2930-17c7-4e1c-aa38-6c71aa86776e.png)

This is just how explorer renders them. The files themselves are indeed SVGs.

**Comment by PramodValavala-MSFT** [comment]
@lizzyhbell Just following up here... Hope my previous comment clears things up.

**Comment by JasRobe** [comment]
It appears that this was addressed in the thread above. Closing as no-repro.
