### ISSUE TITLE
Link pages on queue based levelling

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/architecture-center#3185]
There should be links both ways between these pages, since one is really a specialisation of the other. 
- https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/web-queue-worker
- https://docs.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495b2ac1-3a9c-d1db-2b46-bbfbd0a4b538
* Version Independent ID: 2f6008fa-9b45-6ce1-13b5-74f82550f715
* Content: [Web-Queue-Worker architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/web-queue-worker)
* Content Source: [docs/guide/architecture-styles/web-queue-worker.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/architecture-styles/web-queue-worker.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/523065/>523065</a>

**Comment by v-fearam** [comment]
#please-close
