### ISSUE TITLE
Content Feedback

### ISSUE THREAD

**Issue by BlackRain70** [MicrosoftDocs/architecture-center#3186]
Great page and was very helpful to me. I noted however while column stores where defined wide column stores where referred to but not defined so the functionality matrix became confusing to a n00b like me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e643be6d-22a2-2b91-c370-edf83d694efe
* Version Independent ID: 770f2e51-9c53-e5ca-1107-9577369b15a6
* Content: [Choose an analytical data store - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analytical-data-stores)
* Content Source: [docs/data-guide/technology-choices/analytical-data-stores.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/analytical-data-stores.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/523920/>523920</a>

**Comment by JanetCThomas** [comment]
This issue has been addressed in PR https://github.com/MicrosoftDocs/architecture-center-pr/pull/9750
