### ISSUE TITLE
Video capture and analytics for retail

### ISSUE THREAD

**Issue by brataiv1** [MicrosoftDocs/architecture-center#3187]
I do have interest in solution described as idea here: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/video-analytics. 
As we start web research for solution components we address that Azure Video Analyzer and Spatial Analysis module are marked as "Preview".
Can we expect this module and services to be ordered officially and in what timeframe?

As we have interest in developing our own video analyzing solution are there other integration scenario that we can use in order to integrate with Azure platform. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3301cd9-73e2-6644-3b79-5be980428dcc
* Version Independent ID: 2f4a1081-5af9-09ad-9892-205e9732df32
* Content: [Video capture and analytics for retail - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/video-analytics)
* Content Source: [docs/solution-ideas/articles/video-analytics.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/video-analytics.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @niravi-msft
* Microsoft Alias: **niravi**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/524295/>524295</a>

**Comment by niravi-msft** [comment]
I didn't follow the comment. What service is marked as 'preview'. Looking at the ACOM page for Spatial Anchor and Azure Video Analyzer, neither of those are marked as preview.

**Comment by brataiv1** [comment]
> I didn't follow the comment. What service is marked as 'preview'. Looking at the ACOM page for Spatial Anchor and Azure Video Analyzer, neither of those are marked as preview.

Thank you for following this discussion up.
I am looking for a Live Video analysis solution.
Currently I am lookin after following documentation:
- [Spatial Analysis container](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/spatial-analysis-container?tabs=desktop-machine) 
-  [Azure Video Analyzer PREVIEW](https://azure.microsoft.com/en-us/pricing/details/video-analyzer/)

As I can see the Video Analyzer for Media is available bum I am looking for live video solution.

**Comment by skabou** [comment]
It is unclear what article is being referenced.  If you are still experiencing an issue, please re-open with additional information.
