### ISSUE TITLE
Use alternative to BinaryFormatter in example

### ISSUE THREAD

**Issue by jtlowe** [MicrosoftDocs/architecture-center#3189]
The code example within the [Implement Redis cache client applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching#implement-redis-cache-client-applications) section uses `BinaryFormatter`, which  the [BinaryFormatter Security Guide](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide) states is dangerous to use. 

Just mentioning in case the security concern applies to the code example and an alternative serializer should be used instead.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be785717-ca5e-f3d6-8e60-4005d9503d08
* Version Independent ID: 3ce414e5-d923-0488-ff11-3aa8bd4c2d1e
* Content: [Caching guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching#related-patterns-and-guidance)
* Content Source: [docs/best-practices/caching.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/caching.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/524626/>524626</a>

**Comment by v-fearam** [comment]
#please-close
