### ISSUE TITLE
Subscription logic 

### ISSUE THREAD

**Issue by mriseng** [MicrosoftDocs/architecture-center#3191]
Hi, 

Would like the documentation to reflect is how we peer the spoke vnets to the hub when they are located in different subscriptions.
Both in code and on the visio drawing.

We are trying to relate this to our environment, where we have 1 subscription where the hub is located, and the spokes consist of subscription and all the resources. eg: vnet, vms. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525100/>525100</a>

**Comment by himanshusinha-msft** [comment]
Assigned this to  @david-stanford  .
@mike-urnun-msft  : FYI

**Comment by jocontr** [comment]
@mriseng I wanted to reach out and recommend various articles on the subject that may help:

- https://learn.microsoft.com/en-us/azure/architecture/hybrid/deployments/solution-deployment-guide-connectivity
- https://learn.microsoft.com/en-us/azure/architecture/hybrid/deployments/solution-deployment-guide-cross-cloud-scaling
- https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cross-cloud-scaling
- https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/hybrid-connectivity
