### ISSUE TITLE
Proposed graphic and text updates Dev/Test for SAP

### ISSUE THREAD

**Issue by arntdg** [MicrosoftDocs/architecture-center#3192]
Hi!
Arnt de Gier here, TME for Azure NetApp Files with NetApp.
I have the following suggestions for updating this article:
In the architecture diagram, add a Azure NetApp Files icon to designate that Azure NetApp Files is a viable and valid storage option for the Spoke virtual machine. See the attached example file for a proposed placement of the ANF icon. Please either implement this change or send me or share with me the original graphic and I can insert the ANF icon for you and return the graphic. My email is **b-arntdegier@microsoft.com**.

In the same article, in the Components section, add this text:
**Storage. Azure Premium Managed disks or Azure NetApp Files provide the recommended storage for the SAP executables and the SAP HANA data and logs.**

In the same article, under considerations, add this text:
**Azure NetApp Files adds further benefits for test/dev environments by using the cloning feature, which allows developers to take near instant clones of production and test databases, which they can access independently from the production databases. Azure NetApp Files cloning is based on the snapshot feature, which produces copies of volumes nearly instantly by only copying the pointers to the data files, not the files themselves.**
In above text, hyperlink the words 'cloning' and 'snapshots' to https://docs.microsoft.com/en-us/azure/azure-netapp-files/snapshots-introduction

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8307bb37-3a4f-0073-c495-b2aaa4cc8797
* Version Independent ID: 60702144-7610-fda2-a68d-f9f05aff2921
* Content: [SAP workload development and test settings - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-dev-test)
* Content Source: [docs/example-scenario/apps/sap-dev-test.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/sap-dev-test.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @AndrewDibbins
* Microsoft Alias: **pnp*
![UpdatedArchitecture](https://user-images.githubusercontent.com/86350177/144049775-fadfac18-8275-43c8-a150-bd89c0e5bb94.png)
*

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525938/>525938</a>

**Comment by hallihan** [comment]
This was addressed in a previous update. #please-close
