### ISSUE TITLE
Graphic and text updates requested SAP BW/4HANA in Linux on Azure

### ISSUE THREAD

**Issue by arntdg** [MicrosoftDocs/architecture-center#3193]
Hi!
Arnt de Gier here, TME for Azure NetApp Files with NetApp.
I have the following suggestions for updating this article:

1. Per the attached image, please update the architecture graphic as follows:
Move the Azure Managed Disks icon up to just below the SAP HANA Database box.
2. Stretch the box containing Azure NetApp Files icon to the right so it also covers the SAP HANA Database.
3. Change the text underneath the Azure NetApp Files box from Dedicated storage subnet to **Delegated storage subnet**.

Text update:
4. In section 'SAP Central Services cluster', third sentence, replace NetApp Files with **Azure NetApp Files**.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90286914-6020-f118-a270-e33e3
![Updated Architecture SAP workload](https://user-images.githubusercontent.com/86350177/144052641-a86e75a9-f23d-41fc-99f9-e299d2e17271.png)
6629c22
* Version Independent ID: 3beba32d-41f6-27df-430c-cde024bc29b2
* Content: [Run SAP BW/4HANA with Linux VMs - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/run-sap-bw4hana-with-linux-virtual-machines)
* Content Source: [docs/reference-architectures/sap/run-sap-bw4hana-with-linux-virtual-machines.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/run-sap-bw4hana-with-linux-virtual-machines.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525946/>525946</a>

**Comment by arntdg** [comment]
Please insert the attached revised architecture image in place of the existing architecture image in the current article
![sapbw4hanaupd](https://user-images.githubusercontent.com/86350177/145580347-9422f4af-95a4-4123-b134-5a3db7702807.png).

**Comment by skabou** [comment]
It appears this has been addressed.  If you are still experiencing an issue, please re-open with additional information.
