### ISSUE TITLE
Graphic and text updates requested for SAP deployment on Oracle DB

### ISSUE THREAD

**Issue by arntdg** [MicrosoftDocs/architecture-center#3194]
Hi!
Arnt de Gier here, TME for Azure NetApp Files with NetApp.
I have the following suggestions for updating this article:

1. As per attached updated graphic, please add Azure NetApp Files icons in the boxes Oracle Database, SAP central server cluster and in the bottom box named Azure NetApp Files.
2. Add a box underneath the three pillars marked **Delegated storage subnet** containing the Azure NetApp Files icon to designate the feasibility of using Azure NetApp Files in this architecture.
3. In section 'Components', add: **Storage. Azure Premium managed disks or Azure NetApp Files (for Oracle 19C) provide the recommended storage for the SAP executables and the Oracle database.**
4. Update text 'Avoiding these outcomes requires an SAP infrastructure that is highly available and resilient when failures occur.' to **Avoiding these outcomes requires an SAP infrastructure that is highly available and resilient to failures.**
5. Update text 'Building a highly available SAP environment requires eliminating single points of failures in your system architecture and processes.' to **Building a highly available SAP environment requires eliminating single points of failure in your system architecture and processes.**

[Enter feedback here]

---
#### Document Details
![SAP deployment on OracleDB updates](https://user-images.githubusercontent.com/86350177/144055719-21a24ab0-77db-4a70-b70a-c69e119b0f5e.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e700b9a2-8b1d-5d55-95ec-1bb123d2586a
* Version Independent ID: 7f4b8f89-a777-b03b-e0af-d3d890745088
* Content: [SAP deployment on Azure using an Oracle DB - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-production)
* Content Source: [docs/example-scenario/apps/sap-production.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/sap-production.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @DharmeshBhagat
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525959/>525959</a>

**Comment by EdPrice-MSFT** [comment]
@arntdg - Can you add this scenario as an section in Alternatives? You can directly make the edit. Thanks!

**Comment by EdPrice-MSFT** [comment]
I also directly made the #4 edit. PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/4831

Thanks!

**Comment by arntdg** [comment]
> 

The link ending in 4831 is not working for me, getting a 404 not found error.
