### ISSUE TITLE
Proposed Graphics and text updates SAP HANA Scale-up

### ISSUE THREAD

**Issue by arntdg** [MicrosoftDocs/architecture-center#3195]
Hi!
Arnt de Gier here, TME for Azure NetApp Files with NetApp.
I have the following suggestions for updating this article:

1. Per the attached updated graphic, please insert Azure NetApp Files icons in the boxes HDB Node 1, HDB Node 2 and HDB Node (on the right hand side).
2. Underneath the current graphic below 'Primary Region' and 'DR Region', please add on each side a box marked Delegated storage subnet, containing the Azure NetApp Files icon.
3. Between above two boxes, draw a dotted line to connect the two boxes and text **Azure NetApp Files Cross Region Replication** to this dotted line.
4. Update the section 'Storage' to: **Storage. Azure Premium managed disks and Azure NetApp Files provide the recommended storage for the SAP executables and the SAP HANA data and logs. Other storage configurations are available, such as Ultra disk.**
5. Update the section 'Performance' to: 
![image](https://user-images.githubusercontent.com/86350177/144059492-2e9e4600-dc3f-4b94-8300-57b727f5442d.png)

[Enter feedback here]

![SAP HANA Scale-up](https://user-images.githubusercontent.com/86350177/144058149-ba7dc600-4c41-4dfa-ab3f-defb0b994e11.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fff09dc-014d-d685-881e-dc7d1ef353ff
* Version Independent ID: ca3d7830-d394-d280-dd35-19749ee53f6b
* Content: [SAP HANA for Linux VMs in scale-up systems - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines)
* Content Source: [docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525964/>525964</a>

**Comment by hallihan** [comment]
Azure NetApp Files was added in the storage section in previous updates, #please-close
