### ISSUE TITLE
Proposed Graphic and Text updates SAP-S4HANA

### ISSUE THREAD

**Issue by arntdg** [MicrosoftDocs/architecture-center#3196]
Hi!
Arnt de Gier here, TME for Azure NetApp Files with NetApp.
I have the following suggestions for updating this article:

1. As per the attached updated graphic, please insert Azure NetApp Files icons in the boxes Database subnet and Database Replica.
2. Update the 2 outdated Azure NetApp Files icons to the new (current) ones.
3. Replace the text Dedicated storage subnet to **Delegated storage subnet** (2x).
4. Add dotted lines from Azure NetApp Files in Region 1 to Region 2 and add text **Azure NetApp Files Cross Region Replication** (2x).
5. Text updates per 
![image](https://user-images.githubusercontent.com/86350177/144061121-beed3bd5-4a0d-4706-b858-468413b8e625.png)

6. In the “Performance” section add at the very bottom this sentence:

**ANF has unique performance features that allow for real time tuning that meet the needs of the most demanding SAP environments.  For performance considerations using ANF see here.**
In above sentence, hyperlink the last word 'here' to **https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-scale-out-standby-netapp-files-suse#sizing-for-hana-database-on-azure-netapp-files** 

![Updated graphic SAP-S4HANA](https://user-images.githubusercontent.com/86350177/144060267-330e150e-f087-4ccd-a091-7ed39b7fa092.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009774ee-d1e4-1d7b-e53f-ecbcc4d56e5d
* Version Independent ID: d14a99bb-b4d5-21ce-dd72-5759a8284c42
* Content: [SAP S/4HANA in Linux on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/sap-s4hana)
* Content Source: [docs/reference-architectures/sap/sap-s4hana.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sap/sap-s4hana.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525968/>525968</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24196 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
