### ISSUE TITLE
Article has broken links to Deployment Manager

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/architecture-center#3197]
This article has a number of links referencing Azure Deployment Manager.  These links are broken and should be fixed or removed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6e8b74-b3e5-8acd-f517-39d5137cffc4
* Version Independent ID: e1d6ffde-14d9-8502-2ff2-7a8399de86dc
* Content: [Deployment Stamps pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/deployment-stamp)
* Content Source: [docs/patterns/deployment-stamp.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/deployment-stamp.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @johndowns
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/526321/>526321</a>

**Comment by johndowns** [comment]
I will fix this in the next few days.

**Comment by johndowns** [comment]
Resolved in the private repo.

**Comment by skabou** [comment]
It appears your feedback has been addressed.  If you are still experiencing issues, please re-open with additional details.
