### ISSUE TITLE
Diagram is a hidden circle

### ISSUE THREAD

**Issue by Katzmann1983** [MicrosoftDocs/architecture-center#3199]
The diagram is actually the very same circle used in another website:
![image](https://user-images.githubusercontent.com/5080892/144447725-63785981-462f-44fc-8dca-2d18e59c4f12.png)
 Maybe aligning the images would make some sense?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64e76ff-1388-ed4d-4c8b-92bb4419cc61
* Version Independent ID: 3cdec53f-38ba-c0bb-3315-5ad8b357aabf
* Content: [MLOps for Python with Azure Machine Learning - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/mlops-python)
* Content Source: [docs/reference-architectures/ai/mlops-python.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/ai/mlops-python.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @praneet22
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/527134/>527134</a>

**Comment by EdPrice-MSFT** [comment]
Thank you for the feedback. 

@Katzmann1983,

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/_images/ml-ops-python.png

This image? It seems to be a different application of similar principles.

**Comment by Katzmann1983** [comment]
Yes

**Comment by ckittel** [comment]
Thanks @Katzmann1983, when this article was recently refreshed, we completely recreated the image and no longer have this image anymore.
