### ISSUE TITLE
Error in Defender exclusion PowerShell script

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/architecture-center#3200]
In the PowerShell for Defender exclusions, this line has an extra line break, which causes a syntax error. Also, the variable is not used in the script. Please correct it:
```
  $StorageAcct = "
  storageacct"  # Storage Account Name
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#antivirus-exclusions)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/527348/>527348</a>

**Comment by BhargaviAnnadevara-MSFT** [comment]
@JLambEJG Thank you for catching that error in the docs! I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
