### ISSUE TITLE
Sustainability pillar in well architected framework. 

### ISSUE THREAD

**Issue by sanjeevmagoo** [MicrosoftDocs/architecture-center#3202]
AWS has released a new tenant in their well-architected framework named Sustainability. Time to revisit this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d7b49-94b6-abd9-c21a-fb0bace59114
* Version Independent ID: 5d9aa212-cbb2-803c-2ea9-6da76c7a9394
* Content: [Microsoft Azure Well-Architected Framework - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/)
* Content Source: [docs/framework/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/index.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @david-stanford
* Microsoft Alias: **v-stacywray**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/527972/>527972</a>

**Comment by Zimmergren** [comment]
Hi @sanjeevmagoo. 

Thank you for mentioning this. In 2022, Microsoft released the [Azure Well-Architected Framework guidance for sustainable workloads](https://learn.microsoft.com/en-us/azure/architecture/framework/sustainability/sustainability-get-started), containing guidance on designing and architecting more sustainable workloads on Azure.

#please-close
