### ISSUE TITLE
The video on the page is Page Not Found (404)

### ISSUE THREAD

**Issue by tksh164** [MicrosoftDocs/architecture-center#3204]
The video on this page is Page Not Found (404)

![image](https://user-images.githubusercontent.com/1618784/144746435-6fae4705-d5c7-4ab6-b050-96a5bfdd3959.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79636ce-83ec-b5ba-fc6b-25c397516dd9
* Version Independent ID: 4f8cc5c2-4473-1ca8-b901-6329eb920e8c
* Content: [Performance efficiency pillar overview - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/scalability/overview)
* Content Source: [docs/framework/scalability/overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/scalability/overview.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @v-aangie
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/528189/>528189</a>

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by tksh164** [comment]
The document updated, so, the video has been gone in currently.

**Comment by v-aangie** [comment]
Sent email to Mayank to reassign.
