### ISSUE TITLE
Architecture image needs a little tweaks and NVA VNet 1 address space was wrong, which is supposed to be 10.1.255.0/24

### ISSUE THREAD

**Issue by GavinJin88** [MicrosoftDocs/architecture-center#3205]
[Enter feedback here]
Looking at the architecture from https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/performance-security-optimized-vwan#architecture, Are the connection between VNet1 and NVA VNet1, connection between VNet 2 and NVA VNET 1 supposed to be vnet peering? the line seems to be blue not orange.

![image](https://user-images.githubusercontent.com/95666229/144956033-84ed5940-edba-4050-af83-3c339de5e7ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2b8ca3-9ed8-532a-6ce6-3550c04d6c88
* Version Independent ID: 9e2b8ca3-9ed8-532a-6ce6-3550c04d6c88
* Content: [Virtual WAN architecture optimized for department-specific requirements - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/performance-security-optimized-vwan)
* Content Source: [docs/example-scenario/infrastructure/performance-security-optimized-vwan.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/performance-security-optimized-vwan.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **jopoetzi**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/528898/>528898</a>

**Comment by GavinJin88** [comment]
> Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # [528898](https://ceapex.visualstudio.com//pnp/_workitems/edit/528898/)

my apologies, udr in vnet 1 and vnet2 are correct. but still image has to be tweaked.

Architecture image needs a little tweaks(line on vnet 1 and vnet 2 are supposed to be orage) and NVA VNet 1 address space was wrong, which is supposed to be 10.1.255.0/24

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24560 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
