### ISSUE TITLE
Add details/decision-tree for Single Storage Account vs Multiple Storage Account

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/architecture-center#3206]
Currently working with an ISV and considering relying on Azure Storage Blob.
The first question that comes in mind was: "Should we use 1 storage account per customer or should we mutualize one storage for a pods of customer ? If we do so how to ensure the right level of performance for each customer of the pod ? And by the way what does that mean having several storage account instead of only one for the devs and the ops ?"

So my suggestion would be to put the "Isolation model" at first, renaming it "single vs multiple storage account" and highlighting the benefits and tradeoffs in both way and from multiple viewpoint:
- resource management: especially the overhead of managing multiple resource instead of one... (could be fixed by doing devops)
- dev & ops: deployment, policies, monitoring (service-level, instance-level...)
- security: isolation, RBAC, access, encryption and so on
- cost: no impact I believe, but good to highlight that
- performance: storage account limits
- features: list of features you already wrote about in the current article

I'm more than happy to help and bring my feedback
I'm happy to contribute if the door is open :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d569bede-58fd-5fd3-8766-45acac49c9d4
* Version Independent ID: d569bede-58fd-5fd3-8766-45acac49c9d4
* Content: [Azure Storage considerations for multitenancy - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/multitenant/service/storage)
* Content Source: [docs/guide/multitenant/service/storage.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/service/storage.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @johndowns
* Microsoft Alias: **jodowns**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/529375/>529375</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24561 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
