### ISSUE TITLE
AZ aligned subnet diagram could be confusing

### ISSUE THREAD

**Issue by youkhi-zz** [MicrosoftDocs/architecture-center#3207]
Hi Team,

From my knowledge, subnets are deployed across AZs but AZs are all aligned in each subnet in the diagram. I know that people will realize what it's trying to describe from the explanation, however, I think it can still confuse others who are new to Azure.
(Which just happened ;) )

Best,
Youkhi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65da02f0-6e9c-a2e9-c366-020873a082b7
* Version Independent ID: dd0f9267-4531-af13-dd06-93879c97fa14
* Content: [Azure Well-Architected Framework review of an Azure NAT gateway - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/guide/well-architected-network-address-translation-gateway)
* Content Source: [docs/networking/guide/well-architected-network-address-translation-gateway.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/networking/guide/well-architected-network-address-translation-gateway.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @jknightly
* Microsoft Alias: **ethaslet**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/529765/>529765</a>

**Comment by v-fearam** [comment]
#please-close
