### ISSUE TITLE
Multiple Virtual WAN Hubs per region

### ISSUE THREAD

**Issue by AzChrisMelendez** [MicrosoftDocs/architecture-center#3208]
Hey Team,

I sent some feedback for the Azure VWAN FAQ page yesterday regarding the same thing. It looks like some of this documentation needs to be updated now that it's possible to provision multiple VWAN hubs per region.

In the section **"Virtual WAN Hub"** it states _"There can only be one hub per Azure region."_

If you reference the VWAN FAQ page, there is a section that says you can have multiple VWAN Hubs per region.
https://docs.microsoft.com/en-us/azure/virtual-wan/virtual-wan-faq#is-it-possible-to-create-multiple-virtual-wan-hubs-in-the-same-region

Thanks for all your work!
Christopher Melendez
Microsoft Azure CSA
xxxxxx
xxxxxx
xxxxxx
(Edited PII)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ba53f7-4773-946c-fffc-cf51122973f8
* Version Independent ID: 802d7f2e-ee23-c3e1-0294-f3941d0c30c2
* Content: [Hub-spoke network topology with Azure Virtual WAN - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/hub-spoke-vwan-architecture)
* Content Source: [docs/networking/hub-spoke-vwan-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/networking/hub-spoke-vwan-architecture.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **yemrea**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/529873/>529873</a>

**Comment by hallihan** [comment]
This was addressed in previous updates. #please-close
