### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by KSchlobohm** [MicrosoftDocs/architecture-center#3210]
The image for the logical diagram is not shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495b2ac1-3a9c-d1db-2b46-bbfbd0a4b538
* Version Independent ID: 2f6008fa-9b45-6ce1-13b5-74f82550f715
* Content: [Web-Queue-Worker architecture style - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/web-queue-worker)
* Content Source: [docs/guide/architecture-styles/web-queue-worker.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/architecture-styles/web-queue-worker.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/530350/>530350</a>

**Comment by AjayKumar-MSFT** [comment]
@KSchlobohm, Thanks for taking time to share your valuable feedback! 

The doc aims at outlining Web-Queue-Worker architecture with all the key requisite components with two images one for generic architecture and another specific on Azure App Service with other integrating components/services. 
  'Web-Queue-Worker architecture style' and 'Web-Queue-Worker architecture that uses Azure App Service.'

Could you please share more information/insights on what specific logical diagram you would like to see in the doc?

**Comment by AjayKumar-MSFT** [comment]
KSchlobohm,   Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply (share the requested details), and we will gladly continue the discussion.

**Comment by KSchlobohm** [comment]
Thanks @AjayKumar-MSFT I don't think this needed a new diagram but when I reported the issue the image for https://github.com/MicrosoftDocs/architecture-center/raw/main/docs/guide/architecture-styles/images/web-queue-worker-logical.svg was not rendering properly.

Looking at this again today it seems there wasn't a problem to fix.

**Comment by AjayKumar-MSFT** [comment]
KSchlobohm, Understood. Thanks for the follow-up and update.
