### ISSUE TITLE
Broken link for Performance efficiency

### ISSUE THREAD

**Issue by KSchlobohm** [MicrosoftDocs/architecture-center#3212]
Under the header of `Availability` the link for performance efficiency is listed as a broken link.

```md

### Availability
- Consider leveraging the [typical design patterns for availability](../../framework/resiliency/reliability-patterns.md) when building your cloud application. azure/architecture/framework/scalability/performance-efficiency
- Review the availability considerations in the appropriate [App Service web application reference architecture][app-service-reference-architecture]
- For additional considerations concerning availability, see the [availability checklist][availability] in the Azure Architecture Center.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04d3a8e6-d525-cd5e-46b1-d28384fab8bc
* Version Independent ID: 442da3db-2ec4-9f0e-b485-459717c081d2
* Content: [E-commerce front end - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/ecommerce-scenario)
* Content Source: [docs/example-scenario/apps/ecommerce-scenario.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/ecommerce-scenario.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @chrismason
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/530539/>530539</a>

**Comment by AjayKumar-MSFT** [comment]
KSchlobohm, Thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by skabou** [comment]
It appears your feedback has been addressed.  If you are still experiencing issues, please re-open with additional details.
