### ISSUE TITLE
How do I download the slide?

### ISSUE THREAD

**Issue by Johns-305** [MicrosoftDocs/architecture-center#3214]
All this is great, but a waste of time if we can't download the slide.

How? Where?  Why hide this?  This isn't that hard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d6e5f5-f0b9-e667-45bf-806d26e48d42
* Version Independent ID: a3fa06b2-e141-c35d-6a72-a12c1ad653c1
* Content: [Integrate data with Logic App and SQL Server - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/integration/logic-apps-data-integration)
* Content Source: [docs/example-scenario/integration/logic-apps-data-integration.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/integration/logic-apps-data-integration.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ShantnuS
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/531155/>531155</a>

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
The Visio link of the architecture is found here: https://arch-center.azureedge.net/logic-apps-data-integration.vsdx

If you are still experiencing an issue, please re-open with additional information.
