### ISSUE TITLE
Dead link to scripts

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/architecture-center#3216]
There is a link on page 30 of **Managing Microsoft 365 in true DevOps style with Microsoft365Dsc and Azure DevOps** to [https://microsoft365dsc.com/Pages/Resources/Whitepapers/M365Automation.zip](https://microsoft365dsc.com/Pages/Resources/Whitepapers/M365Automation.zip) which now returns a 404.  It is not possible to complete the following steps in the solution without these files.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5235541-bce4-2057-81c0-0557fe8a196a
* Version Independent ID: d5235541-bce4-2057-81c0-0557fe8a196a
* Content: [Manage Microsoft 365 tenant configuration with Azure DevOps - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/manage-microsoft-365-tenant-configuration-microsoft365dsc-devops)
* Content Source: [docs/example-scenario/devops/manage-microsoft-365-tenant-configuration-microsoft365dsc-devops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/manage-microsoft-365-tenant-configuration-microsoft365dsc-devops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @desmay
* Microsoft Alias: **desmay**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/531359/>531359</a>

**Comment by desmay** [comment]
@danielfawcett1 Thanks for reporting working on getting whitepaper updated with new link location.

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by ykuijs** [comment]
This has been fixed.

FYI: The correct link is https://aka.ms/M365DSCWhitepaper/Scripts

This issue can be closed now.

**Comment by ckittel** [comment]
Confirmed this was fixed in the linked whitepaper, thank you @ykuijs for fixing this last year.
