### ISSUE TITLE
Add numbers to diagram

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3218]
there is a numerical listing below the diagram, it would be helpful if the diagram showed the numbers so that the text descriptions could be more easily correlated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c472ec-9be4-6e0e-eac6-0236e2e1044a
* Version Independent ID: d2c472ec-9be4-6e0e-eac6-0236e2e1044a
* Content: [Network-hardened web app - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/security/hardened-web-app)
* Content Source: [docs/example-scenario/security/hardened-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/security/hardened-web-app.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @damaccar
* Microsoft Alias: **damaccar**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/531407/>531407</a>

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by hallihan** [comment]
Numbers were added to the diagram in 9db0016cd65f8843bcd83460706aeebe1883f41d. #please-close
