### ISSUE TITLE
Incomplete page

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3219]
There is not very much content on this page, it looks like the primary section of the page may not have been published. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86da7d5a-f642-2f32-df67-7bfb766afbb9
* Version Independent ID: 86da7d5a-f642-2f32-df67-7bfb766afbb9
* Content: [Service-specific guidance for a multitenant solution - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/multitenant/service/overview)
* Content Source: [docs/guide/multitenant/service/overview.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/service/overview.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @johndowns
* Microsoft Alias: **jodowns**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/531416/>531416</a>

**Comment by johndowns** [comment]
@DeanGross Thanks for your feedback. This is the overview page for a much larger set of documentation. Do you see the links in the table of contents (usually on the left)? These are all part of the guidance in this set.

![image](https://user-images.githubusercontent.com/5916377/145734071-6de4f8b9-bdde-44c7-8eaa-de6b5e82d276.png)

**Comment by johndowns** [comment]
@DeanGross Also, we have many more pages still to come in this section.

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by DeanGross** [comment]
Yes, I see those. I think it would be helpful if the overview page listed out the services that we expect to learn about. It is currently so general that it does not let the reader know what to expect. The overview page should provide enough content so that the reader can determine if further time should be spent

**Comment by johndowns** [comment]
Thanks, @DeanGross. We will be pushing some updates soon to try to make this clearer.

#please-close
