### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3220]
One of the duplicate bullet items in the list should be removed:
Microsoft Defender for Cloud Security Recommendations
Microsoft Defender for Cloud Security Recommendations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce3b9c5-ef05-1ff3-a6fe-052f48a9b471
* Version Independent ID: f6d3e8e8-37c5-43e6-6185-58f8511dee7e
* Content: [Hybrid security monitoring with Sentinel - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-security-monitoring)
* Content Source: [docs/hybrid/hybrid-security-monitoring.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/hybrid-security-monitoring.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/531771/>531771</a>

**Comment by SatishBoddu-MSFT** [comment]
Hello [@DeanGross](https://github.com/DeanGross)
I have assigned the issue to the content author for further review.

**Comment by JasRobe** [comment]
This has been addressed and is published live
