### ISSUE TITLE
Enterprise integration using message broker and events

### ISSUE THREAD

**Issue by richorama** [MicrosoftDocs/architecture-center#3222]
Hi,

First  of all, thank you. These pages are a very useful reference, and I'm really pleased they exist!

In regards to this page:

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/queues-events

I see that a Service Bus Queue feeds into Event Grid. I am curious if this is still the best advice?

I assume that Event Grid is used to trigger the logic app. However, the Peek-Lock Service Bus trigger will trigger a Logic App without the need for Event Grid, and without the need for polling (I think).

https://docs.microsoft.com/en-us/azure/connectors/connectors-create-api-servicebus

I think directly coupling the Logic App to Service Bus provides a more simple and robust architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58f4706b-af61-c661-279d-05e9e9abb79a
* Version Independent ID: d5a4b726-4c50-0851-edc5-04b60ee5ce89
* Content: [Enterprise integration with message broker and events - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/queues-events)
* Content Source: [docs/reference-architectures/enterprise-integration/queues-events.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/enterprise-integration/queues-events.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MattFarm
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/532121/>532121</a>

**Comment by shashishailaj** [comment]
@richorama Thank you for your query . We will investigate and update the thread.

**Comment by PramodValavala-MSFT** [comment]
@richorama there are [differences between the different messaging services](https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fservice-bus-messaging%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json) available which is an informative read to consider for designs.

As for the polling aspect, while connecting to Service Bus via AMQP, there is a single consistent connection but for Logic App connectors, it polls for new messages.

Event Grid on the other hand requires no connection and the service makes requests to the configured endpoints when there is an event. There are feature differences covered in the doc that you should consider too.

Hope that helps clear things up.

**Comment by PramodValavala-MSFT** [comment]
@richorama Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@richorama Hope my previous comment clears things up.

Since there is no doc update required here, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
