### ISSUE TITLE
Management section - why not start with Azure Batch & Azure CycleCloud?

### ISSUE THREAD

**Issue by ltalirz** [MicrosoftDocs/architecture-center#3224]
The "Management" section of the "HPC on Azure" docs is currently ordered as follows:

 1. Do it yourself (discouraged, since complicated)
 1. Hybrid and cloud bursting (only relevant if you want to connect an existing hpc system to azure; likely not the first thing a new user will try to do(?))
 1. Marketplace solutions (good to include but should these be listed before the built-in ones?)
 1. Azure Batch (scheduler-as-a-service)
 1. Azure CycleCloud ("the simplest way to manage HPC workloads using any scheduler")
 1. Workload managers (not sure this section belongs at the top level)
 1. Containers (sub-item of "workload managers")

My suggestion would be to start with the simplest solution, and take it from there.
E.g. something like

 1. Azure Batch (scheduler-as-a-service; no need to set up slurm/... yourself)
 1. Azure CycleCloud (your own auto-scaling HPC cluster in the cloud with a scheduler of your choice)
 1. Azure Kubernetes Service (your own kubernetes cluster)
 1. Hybrid and cloud bursting (if you want to connect an existing hpc system to azure)
 1. Marketplace solutions
 1. Do it yourself (discouraged, since complicated)
    - Sub-item: workload managers you may want to use

I'm new to how HPC works on Azure, so I know very little at this stage, but if this suggestion makes sense (maybe after some further modifications), I'd be happy to prepare a pull request to the docs (I will anyhow need to familiarize myself with HPC@Azure as part of my work at MS).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High Performance Computing (HPC) on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing)
* Content Source: [docs/topics/high-performance-computing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/topics/high-performance-computing.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @SMBrook
* Microsoft Alias: **sibrook**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/532171/>532171</a>

**Comment by SatishBoddu-MSFT** [comment]
Hello [@ltalirz](https://github.com/ltalirz)
I have assigned the issue to the content author for further review.

**Comment by SatishBoddu-MSFT** [comment]
Hello @mike-urnun-msft Could you please help in assigning this to doc author?

**Comment by ltalirz** [comment]
Thanks for looking into this!

I also think the Azure CycleCloud section should link to https://docs.microsoft.com/en-us/azure/cyclecloud
Plus, there are several tools around Azure CycleCloud that do not seem to be mentioned anywhere - neither here, nor in the Azure CycleCloud documentation:

 - [AzureHPC cli `azhpc`](https://github.com/Azure/azurehpc/) for simplifying cyclecloud setup
 - [Azure HPC On-Demand Platform (`az-hop`)](https://azure.github.io/az-hop/)

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24190 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
