### ISSUE TITLE
Bad link to the cosmosdb etcd api

### ISSUE THREAD

**Issue by jbeuree** [MicrosoftDocs/architecture-center#3228]
Page contains a link for "etcd API (preview)", which no longer exists. Looks like the etcd preview api was pulled/removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40cb85c-ee53-7b49-0622-bed8ebedea81
* Version Independent ID: 896e0838-dfd1-c442-414d-ad9ea6dc8f7d
* Content: [Understand data store models - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by SatishBoddu-MSFT** [comment]
Hello [@jbeuree](https://github.com/jbeuree)
I have assigned the issue to the content author for further review.

**Comment by Marusyk** [comment]
The issue can be closed
