### ISSUE TITLE
IoT scenario should use IoT Hub or IoT Central

### ISSUE THREAD

**Issue by falloutxAY** [MicrosoftDocs/architecture-center#3229]
It is called out in the below that one of the use cases is IoT, instead of landing IoT telemetry to event hub, we should use IoT Hub or IoT central. 
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4bb287-fa40-af1d-0af9-e8bc30cfb33e
* Version Independent ID: 12ab4c06-2e95-bb73-f62a-2d1eb79bc735
* Content: [Real-time analytics on big data architecture - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics)
* Content Source: [docs/solution-ideas/articles/real-time-analytics.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/real-time-analytics.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/532804/>532804</a>

**Comment by SatishBoddu-MSFT** [comment]
Hello @falloutxAY Thanks for the feedback.

I have assigned the issue to the content author for further review.

![image](https://user-images.githubusercontent.com/62923178/146294029-50749e20-aea5-49ef-b09b-39b8a6370d70.png)

**Comment by v-fearam** [comment]
It was added IoT Hub as an alternative 
#please-close
