### ISSUE TITLE
Why not to use grpc for inter-pod communication

### ISSUE THREAD

**Issue by dzejsien** [MicrosoftDocs/architecture-center#3231]
Could you please comment, why grpc is not used for inter-pod communication?

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/533454/>533454</a>

**Comment by dzejsien** [comment]
forgot about link, will fix
