### ISSUE TITLE
Why not to use grpc for inter-pod communication

### ISSUE THREAD

**Issue by dzejsien** [MicrosoftDocs/architecture-center#3232]
Could you please comment, why grpc is not used for inter-pod communication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks#network-topology)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/533455/>533455</a>

**Comment by SatishBoddu-MSFT** [comment]
[@dzejsien](https://github.com/dzejsien)
Our SME will review this issue and get back soon.

**Comment by ckittel** [comment]
The "AKS baseline" reference architecture (and reference implementation) here is an _infrastructure_ architecture document; _application_ architecture (including protocol selection for service-to-service communication) is not addressed. Therefor the AKS baseline reference architecture does not take any opinions for or against gRPC.  Workloads that exist in your AKS cluster (based on the AKS Baseline or not) are free to use gRPC as your workload/team wishes.  Thanks for the question!

gRPC is a great choice when your team decides to use it. :)
