### ISSUE TITLE
DataProducts link is not working

### ISSUE THREAD

**Issue by ravkirn** [MicrosoftDocs/architecture-center#3233]
[Enter feedback here]
When clicking the link for 'data product' mentioned in the line 'Establish a data product architecture', it opens up a page with '404- Content not found'.

![image](https://user-images.githubusercontent.com/96313557/146596031-acd64bc5-7c37-4f25-bad9-b9906a030dca.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f10895e-4e1d-1cdd-2d57-32880e0cc45a
* Version Independent ID: 3518d0a5-ffd1-dfa7-6d6b-de2a9ef170d6
* Content: [Analytics end-to-end with Azure Synapse - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end)
* Content Source: [docs/example-scenario/dataplate2e/data-platform-end-to-end.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/dataplate2e/data-platform-end-to-end.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @fabragaMS
* Microsoft Alias: **fabraga**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/533579/>533579</a>

**Comment by SatishBoddu-MSFT** [comment]
@ravkirn 
I have assigned the issue to the content author for further review.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-landing-zone-data-products

![image](https://user-images.githubusercontent.com/62923178/146618936-9cf5b9ac-79ae-48cb-97d3-d8eaf092d4dd.png)

**Comment by fabragaMS** [comment]
PR submitted.
https://github.com/MicrosoftDocs/architecture-center-pr/pull/4945

**Comment by ckittel** [comment]
Thanks @fabragaMS for doing that last year.  Closing this down.
