### ISSUE TITLE
Visio Diagram Incorrectly Labelled "Azure Visual Desktop"

### ISSUE THREAD

**Issue by infratex** [MicrosoftDocs/architecture-center#3234]
Visio diagram is referencing "Azure Visual Desktop" instead of "Azure Virtual Desktop"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501f0332-8e54-1c06-4c47-128c88091862
* Version Independent ID: 501f0332-8e54-1c06-4c47-128c88091862
* Content: [Hybrid file share with disaster recovery for remote and local branch workers - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/hybrid/hybrid-file-share-dr-remote-local-branch-workers)
* Content Source: [docs/example-scenario/hybrid/hybrid-file-share-dr-remote-local-branch-workers.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/hybrid/hybrid-file-share-dr-remote-local-branch-workers.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @JohnPoetzinger
* Microsoft Alias: **jopoetzi**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/536370/>536370</a>

**Comment by BryanLa** [comment]
@infratex  - thanks for your contribution and our apologies for the delayed response.

The Visio diagram and related image files have been fixed. This will republish around 10am Pacific tomorrow.

#please-close
