### ISSUE TITLE
Add Azure Container Apps to decision tree

### ISSUE THREAD

**Issue by crisher0219** [MicrosoftDocs/architecture-center#3236]
Although Container Apps is in Public Preview and likely should be noted as such, can it be added to the decision tree to give additional light to where it falls here?

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/537064/>537064</a>

**Comment by hallihan** [comment]
Assuming that this was in reference to https://learn.microsoft.com/azure/architecture/guide/technology-choices/compute-decision-tree this was addressed in a previous update. #please-close
