### ISSUE TITLE
Missing URL's

### ISSUE THREAD

**Issue by blogero45** [MicrosoftDocs/architecture-center#3237]
The Visio document that I need is no longer listed in GitHub.
https://docs.microsoft.com/en-us/azure/architecture/browse/?products=azure&terms=Front%20Door

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2806b1-1264-2775-4cce-083303e75b49
* Version Independent ID: 68218fb5-2335-183a-8469-9101a2d8a0ef
* Content: [AKS baseline for multiregion clusters - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-multi-region/aks-multi-cluster)
* Content Source: [docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/537075/>537075</a>

**Comment by ckittel** [comment]
The _AKS baseline for multiregion clusters_ does not have a Visio artifact; only the architecture images included in the article are the only assets.  You also listed a link to a "Front Door" architecture search, so if you're looking for an architecture visio that appears to be missing that isn't related to the _AKS baseline for multiregion clusters_ article, please let us know what page specifically you're looking for.  Thanks for any additional clarification/details you can add here.

**Comment by ckittel** [comment]
I'm going to close this out, but feel free to reopen if you can address the question above.  Thanks.

**Comment by blogero45** [comment]
Chad,

The point was to correct the broken URL’s in the articles. That was all.



[A picture containing text  Description automatically generated]
BRENT LOGERO
Digital Solutions Area Specialist
U.S. Enterprise Digital Sales
Mobile: 720.296.4670 | VOIP: ‪720.441.2128

            [Graphical user interface, text, chat or text message  Description automatically generated] <https://www.linkedin.com/in/brentlogero/>

**Comment by ckittel** [comment]
Please let us know which article.  Your original post didn't make it clear.  And the title seemed to indicate a Vizio in specific was missing, but you provided a link to the architecture browser, and the github issue was pinned to an AKS article. We'll need more clarity on your ask.  Thank you.
