### ISSUE TITLE
The branching strategy does not allow independent microservice releases like the guide says it does

### ISSUE THREAD

**Issue by max-bowden** [MicrosoftDocs/architecture-center#3239]
**The issue**
Paraphrased, it says that once the release manager is ready a release/delivery/1.0.2 branch is created from main, deployed to QA environment, approved then deployed to prod. However assuming we are in a monorepo with, eg, 50 different microservices it's highly likely that other microservices have changed between the feature/8152 branch being merged and the creation of the release/delivery/ branch. Therefore the branch being called release/delivery/1.0.2 does not make sense, since it will not just include delivery service changes but also others that have been merged since the delivery change, e.g. "billing' microservice and "inventory" microservice. This means that when the QA env is created from the release/delivery/1.0.2 branch it will include other microservice changes, so QA might fail but it would be nothing to do with the changes to the delivery service, thus unnecessarily blocking the release of the delivery service and causing the guide to not meet one it's own goals: "Teams can build and deploy their services independently". 

**A possible solution?**
If the guide stated that each microservice should have it's own branch (not just it's own folder) then the problem I raised above (of not actually testing and deploying microservices independently) would go away. However, this would introduce other issues (like keeping all these branches in sync) hence I'm not sure that is the right solution or the intent of the author. 

**Another possible solution?**
Another way to resolve this would be to update the guide to state that microservices are not released or QA'd independently, and when a release is created it will include all changes to all microservices between the last release and the current state of main. However this would require removal of one of the stated goals of the guide (and microservices in general!): "Teams can build and deploy their services independently". I also don't think this was the intent of the author. 

**A third possible solution**
I think it is more likely that the guide is assuming that the reader has some unwritten insight that allows the issue I raised to be overcome and that this knowledge simply needs to be included in guide somewhere. 

**Finally**
If someone could at least point out to me what I am missing that, using the process defined in this guide, means that each microservice can be individually deployed along side the last known stable/tested versions of every other service in the repo that would be excellent!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f4d213-3eb1-5b4c-aa67-116e8fa36f7d
* Version Independent ID: 18199b5a-8f57-6574-c795-7540199ae49a
* Content: [Microservices CI/CD pipeline on Kubernetes - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes)
* Content Source: [docs/microservices/ci-cd-kubernetes.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/ci-cd-kubernetes.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/537851/>537851</a>

**Comment by jpocloud** [comment]
@max-bowden - 
Each microservice CI pipeline will be a unique pipeline and has path filters to specify code specifically for that microservice (example: /src/shipping/delivery/). This would be something like the "Delivery App CI" pipeline.

Then, there would be a unique release pipeline created for each microservice CI pipeline, such as "Delivery Release Pipeline". The pipeline would be configured to be triggered on completion of the corresponding CI pipeline ("Delivery App CI" pipeline). Thus, allowing you to deploy only the Delivery App to the desired environments.

**Comment by skabou** [comment]
I believe your question has been addressed. If you are still experiencing issues, please re-open with additional information.
