### ISSUE TITLE
Broken: Advanced Azure Kubernetes Service (AKS) microservices architecture

### ISSUE THREAD

**Issue by blogero45** [MicrosoftDocs/architecture-center#3240]
GitHub logo A reference implementation of this architecture is available on GitHub.
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices-advanced

Another URL to an architecture document, that i need, that is not there.  Where can I find the visio file?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e5ee22-d60b-7f75-5c7c-6527032f33f7
* Version Independent ID: 72c0059f-72e1-551b-b37b-0cbb09b52ebc
* Content: [Advanced Azure Kubernetes Service (AKS) microservices architecture - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices-advanced)
* Content Source: [docs/reference-architectures/containers/aks-microservices/aks-microservices-advanced.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-microservices/aks-microservices-advanced.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/538119/>538119</a>

**Comment by ckittel** [comment]
@blogero45 -- We're sorry, there is no visio artifact for this article.  The only assets are the images found in the article and in the GitHub repo.

@JasRobe -- FYI from a content strategy perspective, if there is any prioritization necessary around backfilling existing content with Visio.  At this point, we do not have the bandwidth to create them from scratch and maintain them.

**Comment by hallihan** [comment]
A Visio download link has been added to the article. #please-close
