### ISSUE TITLE
Global Accelerator - Front Door

### ISSUE THREAD

**Issue by CarlosJoseChaconChavarria** [MicrosoftDocs/architecture-center#3243]
hi guys

I would say this comparison is not correct AWS Global Accelerator (GA) / Front Door since Global Accelerator as per documentation "lobal Accelerator is a good fit for non-HTTP use cases, such as gaming (UDP), IoT (MQTT), or Voice over IP, as well as for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover. "

and I've used AWS Cloud Front and Front Door and I would these 2 are more similar than Global Accelerator and Azure Front Door.
AWS GA does not support http or https which why Front Door is used and AWS CloudFront as well

I would say FD is more versatile but it is not the same as Global Accelerator is more like AWS CloudFront

thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **yuanzhiqu**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the doc author to update appropriately.
