### ISSUE TITLE
Feedback or clarity

### ISSUE THREAD

**Issue by JohnMarlin-MSFT** [MicrosoftDocs/architecture-center#3244]
As the previous PM owner for Storage Replica and the Stretched HCI scenario, in you section, **Use stretched clusters to implement automated disaster recovery for virtualized workloads and file shares hosted on Azure Stack HCI**, you state:

For planned or expected downtimes at the primary site, you can use Hyper-V Live Migration to seamlessly transition workloads to the other site, avoiding downtime altogether.

You can move the VMs over, yes, but the storage is still on the original site.  Hyper-V Manager does not have the capabilites of reversing the replication and making the other site the active drive.  So if you just move teh VMs, you will have SiteA with the storage and SiteB with the VMs.  Meaning all traffic from the client goes to SiteB to the VM, must span the WAN to reach the storage in SiteA, come back over the WAN to the VM in SiteB, then get sent to the client.  This is going to incur some performance degration for the client.  You need to clarify that in order for planned/expected downtimes, reversing the replication direction for Storage Replica must be done first, then the Live Migration of the VMs.

Thanks
JohnMar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd80767-6e29-65b6-4b98-42d36bd3ad33
* Version Independent ID: 7fc8bbde-f74a-74f7-f93e-de7660df740c
* Content: [Use Azure Stack HCI stretched clusters for disaster recovery - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-stack-hci-dr?source=docs)
* Content Source: [docs/hybrid/azure-stack-hci-dr.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/azure-stack-hci-dr.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by SnehaAgrawal-MSFT** [comment]
@JohnMarlin-MSFT Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by v-fearam** [comment]
#please-close
