### ISSUE TITLE
Incorrect Use of HTTP Status Code in the documentation of Request-Reply Pattern

### ISSUE THREAD

**Issue by send2vinnie** [MicrosoftDocs/architecture-center#3246]
> The client sends an HTTP GET request to the status endpoint. The work is still pending, so this call also returns HTTP 202.

The statement of the above paragraph seen in the document doesn't seem match the diagram on top of this paragraph. The diagram shows HTTP 200 whereas the statement says HTTP 202 with regarding to the access of the status endpoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/async-request-reply.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @WillEastbury
* Microsoft Alias: **wieastbu**

**Comment by WillEastbury** [comment]
Hi @Send2Vinnie! 

We're in the middle of a couple of customer tweaks to this document to make the pattern match our prescribed vnext API guidance (where the operation status is a valid and separate REST resource in itself). 

The update will finally show that, the first response from the POST'ed resource should show 202, with a header pointing at the appropriate status operation resource, which when you then subsequently GET (if present) should always return a 200 when the operation status is queried with a status object embedded.

**Comment by hallihan** [comment]
This duplicates #3396 and we're working on an update to address it. Follow that issue for additional details. #please-close
