### ISSUE TITLE
Remove frxccd.exe from antivirus exclusion recommendation as it does not exist

### ISSUE THREAD

**Issue by takondo** [MicrosoftDocs/architecture-center#3249]
Under [Antivirus exclusions] section, the docs recommends that users add an exclusion for "%ProgramFiles%\FSLogix\Apps\frxccd.exe". However, this file does not actually exist. The correct process is frxccds.exe, which is listed right below. As frxccd.exe is not a part of FSLogix I suggest we remove it from the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#feedback)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by SnehaAgrawal-MSFT** [comment]
@takondo Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by msft-jasonparker** [comment]
Correct FSLogix exclusions can be found on the FSLogix documentation site.

https://learn.microsoft.com/en-us/fslogix/overview-prerequisites#configure-antivirus-file-and-folder-exclusions

**Comment by v-fearam** [comment]
#please-close
