### ISSUE TITLE
What about Azure Container Apps?

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftDocs/architecture-center#3251]
This decision chart is great to summarize all the choices available for Compute.
However with Azure Container Apps in GA, it will interesting to see in which category it will be placed.
Would be great if it can be added here.

https://techcommunity.microsoft.com/t5/apps-on-azure-blog/introducing-azure-container-apps-a-serverless-container-service/ba-p/2867265#:~:text=%20Introducing%20Azure%20Container%20Apps%3A%20a%20serverless%20container,management.%20Azure%20Container%20Apps%20streamlines%20the...%20More%20

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by James-Hamil-MSFT** [comment]
Hi, we are investigating your issue and will update you shortly.

Best,
James

**Comment by MayankBargali-MSFT** [comment]
@cdanvergara Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by cdanvergara** [comment]
> @cdanvergara Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

Sounds good, thanks for the update!

**Comment by hallihan** [comment]
Container apps was added over the summer, thanks for the feedback!
