### ISSUE TITLE
Guidance needs updating due to product deprecation

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/architecture-center#3253]
I realize I'm nitpicking a little, but I would like to see this page updated to remove reference to DC/OS.

DC/OS has been end of life'd as of 10/31/21 per https://d2iq.com/products/dcos.

Perhaps replace it with a reference to Hashicorp Nomad?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93139ee2-ff91-ee5e-a056-8d6b597a81f3
* Version Independent ID: 8b4436e0-094c-9602-2ead-43bb3b2f98f1
* Content: [Choose a compute option for microservices - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/compute-options)
* Content Source: [docs/microservices/design/compute-options.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/design/compute-options.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by shashishailaj** [comment]
@larryclaman Thank you for catching this and letting us know. We will engage the content team to see how best they can update the information here.

**Comment by v-fearam** [comment]
#please-close
