### ISSUE TITLE
Update the FlashGrid product name to FlashGrid Cluster from the old name FlashGrid SkyCluster

### ISSUE THREAD

**Issue by victoria-flashgrid** [MicrosoftDocs/architecture-center#3254]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d57b80f-9d93-fc7f-bc6d-c96430a06bd5
* Version Independent ID: 471d2970-917e-dace-4d54-6df8208d3d91
* Content: [Oracle database migration: Lift and shift - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/oracle-migrate/oracle-migration-lift-shift)
* Content Source: [docs/example-scenario/oracle-migrate/oracle-migration-lift-shift.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/oracle-migrate/oracle-migration-lift-shift.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @amberz
* Microsoft Alias: **amberz**

**Comment by shashishailaj** [comment]
@victoria-flashgrid Thank you for catching this. We will engage with the content team to have a change request initiated for this.

**Comment by shashishailaj** [comment]
@victoria-flashgrid We have initiated a change request for the content team . Once they approve this , the change will be live. 

Thank you.
