### ISSUE TITLE
Additional info under On-premises and hybrid considerations section

### ISSUE THREAD

**Issue by murthyla** [MicrosoftDocs/architecture-center#3255]
AATP should be renamed to Microsoft Defender for Identity. 

Include info about Azure App Proxy and Microsoft Defender for Cloud Apps integration - Use Microsoft Defender for Cloud Apps for real-time monitoring of on-prem application - https://docs.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-integrate-with-microsoft-cloud-application-security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7590665-2688-5da1-54ff-029be05c6376
* Version Independent ID: b1dfa5fa-537e-cf03-bb2f-4b9d79420169
* Content: [Azure Active Directory IDaaS in security operations - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aadsec/azure-ad-security)
* Content Source: [docs/example-scenario/aadsec/azure-ad-security.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/aadsec/azure-ad-security.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by James-Hamil-MSFT** [comment]
Hi, we are investigating your issue and will update you shortly.

Best,
James

**Comment by MayankBargali-MSFT** [comment]
@murthyla Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-albemi** [comment]
Resolved in https://github.com/MicrosoftDocs/architecture-center-pr/pull/10088
