### ISSUE TITLE
update product name

### ISSUE THREAD

**Issue by adanielov** [MicrosoftDocs/architecture-center#3257]
The page shows old product name "FlashGrid SkyCluster", which is now called "FlashGrid Cluster". Also, the references look confusing.

Please update the last paragraph in "Business continuity and disaster recovery" section to the following:

You can't use Oracle Real Application Cluster (RAC) by itself in Azure. If you use FlashGrid Cluster, then you can host RAC on Azure. Follow these links for more information:
 * Solution details: [FlashGrid Cluster for Oracle RAC on Azure](https://www.flashgrid.io/oracle-rac-in-azure/)
 * Azure Marketplace page: [FlashGrid Cluster for Oracle RAC](https://azuremarketplace.microsoft.com/en-US/marketplace/apps/flashgrid-inc.flashgrid-skycluster)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d57b80f-9d93-fc7f-bc6d-c96430a06bd5
* Version Independent ID: 471d2970-917e-dace-4d54-6df8208d3d91
* Content: [Oracle database migration: Lift and shift - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/oracle-migrate/oracle-migration-lift-shift)
* Content Source: [docs/example-scenario/oracle-migrate/oracle-migration-lift-shift.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/oracle-migrate/oracle-migration-lift-shift.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @amberz
* Microsoft Alias: **amberz**

**Comment by shashishailaj** [comment]
@adanielov Thank you for your feedback . We will investigate an update the thread.

**Comment by M2MFG** [comment]
Hi Amberz, I am now managing this issue on the FlashGrid side, pleased to e-meet you. Thanks for your help.
Do you have a target date in mind for when the documentation will be updated?
Best regards,
Matthias Miller matthias.miller@flashgrid.io

**Comment by M2MFG** [comment]
Hi Amberz,

I hope all is well. Do you have an update on this task? Thanks for your help.

**Comment by M2MFG** [comment]
Hi Amberz, Do you know when this task will be completed?

There is still one more correction:
"You can't use Oracle Real Application Cluster (RAC) by itself in Azure. If you use FlashGrid **SkyCluster,** then you can host RAC on Azure. Follow these links for more information:"
- "SkyCluster" needs to be replaced with "Cluster"
Thanks for your help. My executive leadership is looking for a target date for this to be done, please advise.

**Comment by M2MFG** [comment]
022322 - MM sent email today to Yolanda Woods <v-ywoods@microsoftsupport.com> asking for help

**Comment by M2MFG** [comment]
Hi Amberz,
I hope you are doing well. Do you have a target date for when you can update this last change? Thanks for your help.

**Comment by M2MFG** [comment]
Hi Amberz, Do you have an ETA as to when this final update will be completed? I reached out to you on LinkedIn today to see if I can get an update. Thanks for your help!  matthias.miller@flashgrid.io

**Comment by amberz** [comment]
@M2MFG sorry, I didn't get the notification, I will review it ASAP. Thanks.

**Comment by M2MFG** [comment]
Hi Amber,

Thanks for your help, we appreciate it!

Best regards,

Matthias Miller | Account Manager | FlashGrid Inc. | ***@***.******@***.***> | +1 (650) 641-2421 ext. 606

**Comment by amberz** [comment]
Updated the content, the PR merged now. 
https://github.com/MicrosoftDocs/architecture-center-pr/pull/5441

**Comment by M2MFG** [comment]
Hi Amber,

Thanks for your help, we look forward to you making the final correction. Please replace “SkyCluster” with “Cluster”

You can't use Oracle Real Application Cluster (RAC) by itself in Azure. If you use FlashGrid SkyCluster, then you can host RAC on Azure. Follow these links for more information:
·        Oracle RAC in Azure with FlashGrid Cluster: Oracle RAC in Azure with FlashGrid Cluster<https://www.flashgrid.io/oracle-rac-in-azure/>
·        Azure Marketplace Flashgrid Cluster for Oracle RAC VM image: Flashgrid Cluster for Oracle RAC<https://azuremarketplace.microsoft.com/marketplace/apps/flashgrid-inc.flashgrid-skycluster>


Best regards,

Matthias Miller | Account Manager | FlashGrid Inc. | ***@***.******@***.***> | +1 (650) 641-2421 ext. 606

**Comment by hallihan** [comment]
@amberz and @M2MFG - are further updates needed here, or have the edits from back in March addressed the outstanding issues?

**Comment by M2MFG** [comment]
All outstanding issues have been resolved, thanks.

**Comment by hallihan** [comment]
Thanks for confirming.
#please-close
