### ISSUE TITLE
Azure function in image is named as Azure Stack

### ISSUE THREAD

**Issue by OneBlueBird** [MicrosoftDocs/architecture-center#3259]
At point #6, the Azure function is named as Azure Stack. Can you rename to Azure function?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff2e7d6-9d81-3745-1e2e-c4ce9d9565ca
* Version Independent ID: d9b29d19-4325-e4ff-b15b-51dace1c11af
* Content: [Tier applications and data for analytics - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/tiered-data-for-analytics)
* Content Source: [docs/solution-ideas/articles/tiered-data-for-analytics.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/tiered-data-for-analytics.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by BryanTrach-MSFT** [comment]
@OneBlueBird Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by EdPrice-MSFT** [comment]
We've got this logged. Thank you!

**Comment by skabou** [comment]
It appears this has been addressed.  If you are still experiencing an issue, please re-open with additional information.
