### ISSUE TITLE
Visio Link does not exactly represent this Architecture diagram

### ISSUE THREAD

**Issue by LionelSlade** [MicrosoftDocs/architecture-center#3260]
Visio Link does not exactly represent this Architecture diagram.  Please Update or refresh this to correct Visio diagram. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84bcf722-abb3-69b8-8073-15ae4a6890de
* Version Independent ID: 7b2010c6-696d-de66-8e56-8ac5d3e54526
* Content: [Basic web application - Azure Reference Architectures](https://docs.microsoft.com/en-gb/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?tabs=cli)
* Content Source: [docs/reference-architectures/app-service-web-app/basic-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/basic-web-app.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@LionelSlade Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by hallihan** [comment]
The diagram and Visio download should now be in sync.
