### ISSUE TITLE
Availability Zones

### ISSUE THREAD

**Issue by Jennifer-CH** [MicrosoftDocs/architecture-center#3261]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Build solutions with availability zones - High Availability](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/high-availability/building-solutions-for-high-availability.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by BryanTrach-MSFT** [comment]
@Jennifer-CH There does not seem to be any question on your issue submission. Can you please update us with any feedback/question so we can assist you? We look forward to your response.
