### ISSUE TITLE
typo error should be application subnet

### ISSUE THREAD

**Issue by lbimsft** [MicrosoftDocs/architecture-center#3262]
[Enter feedback here]
Hi Team,

it's a great doc. but there is a typo in the doc regarding to this sentence “Application Gateway subnet redirects the packets to Azure Firewall Premium.” it should be "Application subnet redirects the packets to Azure Firewall Premium". I see other example also have this typo. could you please help correct it?

Regards,
Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f623b3a-09d7-d793-b007-85b59727c1df
* Version Independent ID: ec0506cd-cdba-784c-6832-ea59697dd39c
* Content: [Zero-trust network for web applications with Azure Firewall and Application Gateway - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/application-gateway-before-azure-firewall)
* Content Source: [docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by vipulsparsh** [comment]
@lbimsft Thanks for reaching out. We will investigate and update the thread accordingly.

**Comment by erjosito** [comment]
Thanks for the feedback @lbimsft! I have just corrected the typo, hopefully it is better now (it will take some time for the PR to propagate to the docs).

**Comment by erjosito** [comment]
Thanks for catching that @lbimsft !
