### ISSUE TITLE
MS Power Platform with GitHub

### ISSUE THREAD

**Issue by luwangshell** [MicrosoftDocs/architecture-center#3264]
Hi there!

From this article (https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform), it seems MS is promoting managing MS Power apps lifecycle using Azure DevOps (Azure git repo, azure pipelines, etc.) Could you clarify or elaborate the position of Power Apps lifecycle with GitHub as well? 

From organization point of view, we are trying to simplify our development lifecycle tools portfolio (including both no/low code and code environment) to be more efficient. It is difficult to govern and support multiple ALMs at the enterprise level, and not to mention that users need to jump between the systems and manage integration or transformation.  

thanks!
Lu Wang

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4968f751-e9d6-6a37-c650-908531992510
* Version Independent ID: f9bf0889-546c-eb18-cfa5-72b42fae1fea
* Content: [CI/CD for Microsoft Power Platform - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform)
* Content Source: [docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @sarahparkes
* Microsoft Alias: **meparkes**

**Comment by BryanTrach-MSFT** [comment]
@luwangshell Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by v-fearam** [comment]
Hi @luwangshell

Sorry for the delay. 

The document is a solution idea, and is not intended to cover all scenarios.
You could use [GitHub actions and GitHub repository](https://learn.microsoft.com/power-platform/alm/devops-github-actions)

I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
