### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by dicolanl** [MicrosoftDocs/architecture-center#3266]
This table needs updating
https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#miscellaneous

Workflow row - Logic Apps is closer to AWS Step Function
https://aws.amazon.com/step-functions/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#miscellaneous)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **yuanzhiqu**

**Comment by PramodValavala-MSFT** [comment]
@dicolanl Thanks for catching that! We have worked up a PR to address this, which once merged should reflect in a couple of hours.
