### ISSUE TITLE
this sentence does not make sense...

### ISSUE THREAD

**Issue by davesainmi** [MicrosoftDocs/architecture-center#3267]
[Enter feedback here]
From this article: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha

This sentence does not make sense / is not understandable - 
 Since HA Ports for inbound traffic every individual TCP/UDP port needs to be opened in a dedicated load-balancing rule.

You may have meant something like 
Since HA ports control (or restrict) inbound traffic, every individual TCP/UDP port needs to be opened in a dedicated load-balancing rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bab6a90-43a3-3d83-d680-26683a3d833d
* Version Independent ID: f8eea094-d297-93e6-06ac-7652d059734f
* Content: [Deploy highly available NVAs - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha)
* Content Source: [docs/reference-architectures/dmz/nva-ha.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/dmz/nva-ha.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the feedback! We will review and get back to you shortly.

**Comment by SamaraSoucy-MSFT** [comment]
I've submitted a pull request to make the change. It will go live once it has been reviewed by the doc author.

**Comment by davesainmi** [comment]
Thank Samara
