### ISSUE TITLE
Purview doesn't support Dynamics 365 as source

### ISSUE THREAD

**Issue by jorisaeles** [MicrosoftDocs/architecture-center#3268]
[Enter feedback here]
The diagram on this docs page includes Dynamics 365 as a data source for Purview but its not mentioned a source on the Purview docs pages https://docs.microsoft.com/en-us/azure/purview/manage-data-sources 

nor is it on the roadmap
https://microsoft.sharepoint.com/teams/ProjectBabylon/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FProjectBabylon%2FShared%20Documents%2FGeneral%2FPresentations%2FRoadmap%2FCurrent%20%2D%20Azure%20Purview%20NDA%20Roadmap%2Epdf&parent=%2Fteams%2FProjectBabylon%2FShared%20Documents%2FGeneral%2FPresentations%2FRoadmap&p=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae05f28-2c5d-8fa1-9e2f-bad478a60379
* Version Independent ID: 953c74fb-cc16-f171-b925-053b90f1be5a
* Content: [Data governance with Profisee and Azure Purview - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-purview)
* Content Source: [docs/reference-architectures/data/profisee-master-data-management-purview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/data/profisee-master-data-management-purview.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **gamal**

**Comment by PramodValavala-MSFT** [comment]
@jorisaeles Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24187 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
