### ISSUE TITLE
Add IPv6 into the comparison and decision tree

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/architecture-center#3269]
Would be great if IPv6 could be added to the comparison here. 

In Norway, public companies must support IPv6 by 1. january 2023.

* https://lovdata.no/dokument/SF/forskrift/2013-04-05-959/%C2%A712#%C2%A712

So I guess this question will come up a lot this year.

Front Door is the only real alternative here, for a public facing endpoint that supports IPv6?

* https://rkniyer999.medium.com/390a3d3e5e13

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@o-l-a-v Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by v-fearam** [comment]
Hi @o-l-a-v 

Sorry for the delay. 

At the current time

 [Azure Front Door supports ipv6](https://learn.microsoft.com/en-us/azure/frontdoor/front-door-overview#key-benefits)

[Azure Load Balancer also supports ipv6](https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-ipv6-overview)

Unfortunately,  [AzureApplication Gateway v2 doesn't currently support IPv6](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-faq#does-application-gateway-support-ipv6)

[Azure Traffic Manager supports in a special way](https://learn.microsoft.com/en-us/azure/traffic-manager/traffic-manager-faqs#does-traffic-manager-support-ipv6-endpoints)

we will also provide feedback to the content owners that addressing IPv6 capability in this article would be helpful.

I will close the ticket, but feel free to open a new one if you still have concerns

**Comment by v-fearam** [comment]
#please-close
