### ISSUE TITLE
Think you mean, Premium, not Production

### ISSUE THREAD

**Issue by robvet** [MicrosoftDocs/architecture-center#3270]
In the following sentence, think your referring to Development or 'Premium' API Management tiers:

The private, internal deployment model allows API Management to connect to an existing virtual network, making it reachable from the inside of that network context. To enable this feature, deploy either the Development or Production API Management tiers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/apis/protect-apis)
* Content Source: [docs/reference-architectures/apis/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/apis/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **fabriciosanchez**

**Comment by PramodValavala-MSFT** [comment]
@robvet Thanks for catching that! We have worked up a PR to address this, which once merged should reflect in a couple of hours.
