### ISSUE TITLE
Improvements on the Microsoft Docs - "Add IP address spaces to peered virtual networks"

### ISSUE THREAD

**Issue by shikanem** [MicrosoftDocs/architecture-center#3273]
[Enter feedback here]

The customer will and understand the risk/potential disruption and th eactions needed from the Docs to avoid any potential service down. 
For the end users to better understand and leverage/apply the Docs to their operations, this part of below Docs should articulate:

1) changes of address space extension operation via VNet peering;
2) the necessary setting-up steps in the new address space extension operation via VNet peering (for instance, sync operation needs to be completed when adding a new SpokeVNet address space without removing and reestablishing peers with the existing VNet);
3) the risks and potential disruption if sync operation is not performed.The contents should be organized in a more obvious and logical way for end users to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636aa53e-3ca0-7a30-fe16-7219f3e8d1a9
* Version Independent ID: c503b39a-cd8a-669a-0882-27d8c13d3570
* Content: [Add IP address spaces to peered virtual networks - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/prefixes/add-ip-space-peered-vnet)
* Content Source: [docs/networking/prefixes/add-ip-space-peered-vnet.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/networking/prefixes/add-ip-space-peered-vnet.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @randycampbell
* Microsoft Alias: **pnp**

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24181 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
