### ISSUE TITLE
Old product names in CA graphic

### ISSUE THREAD

**Issue by halligas** [MicrosoftDocs/architecture-center#3275]
Detailed Conditional Access graphic still refers to Azure ATP instead of Microsoft Defender for Identity and still calls Microsoft Defender for Cloud Apps MCAS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5034ddc5-077e-1541-9b3e-479d6e35dd76
* Version Independent ID: 5034ddc5-077e-1541-9b3e-479d6e35dd76
* Content: [Conditional Access design principles and dependencies - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/security/conditional-access-design)
* Content Source: [docs/guide/security/conditional-access-design.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/conditional-access-design.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @clajes
* Microsoft Alias: **clajes**

**Comment by AnuragSharma-MSFT** [comment]
@halligas Thank you for the feedback. We are actively investigating and will get back to you soon.

**Comment by hallihan** [comment]
This was addressed in #3278, #please-close
