### ISSUE TITLE
Customer story reference no longer available

### ISSUE THREAD

**Issue by jesusher** [MicrosoftDocs/architecture-center#3277]
Please update the customer story reference on the Next Steps section: Maritz Motivation Solutions customer story- https://customers.microsoft.com/story/maritz is no longer available on the Customer Stories site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4f4c7c-f268-b75b-2486-5c4418e5b24e
* Version Independent ID: 5d28faa1-20bc-1727-05ab-0b18eba1ba7c
* Content: [Data warehousing and analytics - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/data-warehouse)
* Content Source: [docs/example-scenario/data/data-warehouse.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/data-warehouse.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by ShaikMaheer-MSFT** [comment]
@jesusher Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by v-fearam** [comment]
#please-close
