### ISSUE TITLE
Query of Architecture decision tree.

### ISSUE THREAD

**Issue by tuckwelladev** [MicrosoftDocs/architecture-center#3280]
I have a query regarding one of the outcomes within the architecture decision tree below. The Statement of "Proximity Placement groups (PPG's) with optional availability sets (ASs) in availability zones (AZs)". How is it possible to use availability sets in availability zones? These availability options are mutually exclusive, and when deploying a VM or groups of VM's you choose either to deploy using availability sets OR availability zones. Are you able to clarify?

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/iaas-high-availability-disaster-recovery?source=docs#architecture

Many Thanks
Adam
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97211a88-4ce9-263f-4bd0-ae6d8b61447c
* Version Independent ID: 00570dc5-7b74-2906-1653-90d86b67c0bd
* Content: [High availability and disaster recovery for IaaS apps - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/iaas-high-availability-disaster-recovery?source=docs#architecture)
* Content Source: [docs/example-scenario/infrastructure/iaas-high-availability-disaster-recovery.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/iaas-high-availability-disaster-recovery.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @shcrouch
* Microsoft Alias: **pnp**

**Comment by shcrouch** [comment]
Hi Adam, yes you can do this today using PPG as the “anchor” for the AS and AZ, so you can effectively pin the PPG to a AZ and then use AS in the PPGs.

The process is covered here - Azure proximity placement groups for SAP applications - Azure Virtual Machines | Microsoft Docs<https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-proximity-placement-scenarios#combine-availability-sets-and-availability-zones-with-proximity-placement-groups>

Regards
Shaun

From: tuckwelladev ***@***.***>
Sent: 01 February 2022 11:24
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Shaun Croucher ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/architecture-center] Query of Architecture decision tree. (Issue #3280)


I have a query regarding one of the outcomes within the architecture decision tree below. The Statement of "Proximity Placement groups (PPG's) with optional availability sets (ASs) in availability zones (AZs)". How is it possible to use availability sets in availability zones? These availability options are mutually exclusive, and when deploying a VM or groups of VM's you choose either to deploy using availability sets OR availability zones. Are you able to clarify?

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/iaas-high-availability-disaster-recovery?source=docs#architecture<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fexample-scenario%2Finfrastructure%2Fiaas-high-availability-disaster-recovery%3Fsource%3Ddocs%23architecture&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734083547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1m87h2mWh%2BQ4qfhIdny41iHubmDyDgSzrSKIkjz01Hg%3D&reserved=0>

Many Thanks
Adam
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 97211a88-4ce9-263f-4bd0-ae6d8b61447c
  *   Version Independent ID: 00570dc5-7b74-2906-1653-90d86b67c0bd
  *   Content: High availability and disaster recovery for IaaS apps - Azure Example Scenarios<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fexample-scenario%2Finfrastructure%2Fiaas-high-availability-disaster-recovery%3Fsource%3Ddocs%23architecture&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734083547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1m87h2mWh%2BQ4qfhIdny41iHubmDyDgSzrSKIkjz01Hg%3D&reserved=0>
  *   Content Source: docs/example-scenario/infrastructure/iaas-high-availability-disaster-recovery.yml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftdocs%2Farchitecture-center%2Fblob%2Fmain%2Fdocs%2Fexample-scenario%2Finfrastructure%2Fiaas-high-availability-disaster-recovery.yml&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734083547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=J48jwO%2FmX3%2B7j3d7Q3JygZ0Ymlxx%2BgZhk0Lw08XbFCc%3D&reserved=0>
  *   Service: architecture-center
  *   Sub-service: example-scenario
  *   GitHub Login: @shcrouch<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshcrouch&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734133547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qFh0sQ5bp6DUlyfc%2FXFFbBPPWEFW4Zvobw9C3JTw0MM%3D&reserved=0>
  *   Microsoft Alias: pnp

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Farchitecture-center%2Fissues%2F3280&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734133547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qK8UUJlY%2FIoJaTXHdJc3lh7JoTOdxI3byFzgXOaTWZc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO3MCFTWFVLRMZNPJDJAZODUY67GVANCNFSM5NI3O3VQ&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734133547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=go4wjbfFS%2BewfycS1U0RfKNgeJZwQCFjbQ6jfAIJ1Uw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734133547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZLb4BpRnJLE3WbHFXjKMJn7B2Jc6Or4UWlhYkzDMwWw%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CShaun.Croucher%40microsoft.com%7Ca3678b5170e9407617cb08d9e57567f9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793114734133547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OeYspZFNWakv5nkxGbrowyN2z4MqDTw5in51EPgzCZY%3D&reserved=0>.

**Comment by shcrouch** [comment]
Question answered and closed by OP
