### ISSUE TITLE
Integrate AAD for the workload to be  be updated with Azure AD Workload Identity

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#3281]
Integrate Azure Active Directory for the workload section should be updated as Pod Identity V1 will not GA, should be updated with Azure AD Workload Identity which is the new name for Pod Identity V2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks#integrate-azure-active-directory-for-the-workload)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks/secure-baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by hallihan** [comment]
This is reflected in the latest version of the article.
