### ISSUE TITLE
Update diagram to reflect Defender & Sentinel naming

### ISSUE THREAD

**Issue by ckittel** [MicrosoftDocs/architecture-center#3284]
The copy on this page has been updated to reflect branding changes for Microsoft Defender, Microsoft Sentinel, etc.  But the diagram is not updated and uses "ASC" (Azure Security Center", etc.

Consider reviewing the related content, in addition to this specific article.

HT: @YuriDio @rayne-wiselman 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce3b9c5-ef05-1ff3-a6fe-052f48a9b471
* Version Independent ID: f6d3e8e8-37c5-43e6-6185-58f8511dee7e
* Content: [Hybrid security monitoring with Sentinel - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-security-monitoring)
* Content Source: [docs/hybrid/hybrid-security-monitoring.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/hybrid-security-monitoring.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MartinJaffer-MSFT** [comment]
Duplicate of #3283

**Comment by ckittel** [comment]
Yikes, sorry about the duplicates @MartinJaffer-MSFT  -- Github was throwing 500s when I was submitting them.  Apparently they all got queued up and submitted anyway. :(
