### ISSUE TITLE
Process to resize and Sync Peered VNET's

### ISSUE THREAD

**Issue by joteromontes** [MicrosoftDocs/architecture-center#3286]
We need a proper description for the process to resize one peered VNET and perform the sync action using the command: [Sync-AzVirtualNetworkPeering](https://docs.microsoft.com/en-us/powershell/module/az.network/sync-azvirtualnetworkpeering)

When you do this the remote side will show the old information of the Peered VNET that has been resized. 

The importance of this feature lies in the capability to adjust production environments without having any network disrupt. Making safe to increase network segments for Hub&Spoke setups when working with production loads.

At this moment the workaround is simple to delete/create the peering, by doing this we will have network downtime if you are working in the production state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636aa53e-3ca0-7a30-fe16-7219f3e8d1a9
* Version Independent ID: c503b39a-cd8a-669a-0882-27d8c13d3570
* Content: [Add IP address spaces to peered virtual networks - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/prefixes/add-ip-space-peered-vnet)
* Content Source: [docs/networking/prefixes/add-ip-space-peered-vnet.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/networking/prefixes/add-ip-space-peered-vnet.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @randycampbell
* Microsoft Alias: **pnp**

**Comment by ShaikMaheer-MSFT** [comment]
@joteromontes Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24179 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
