### ISSUE TITLE
Link on page not working

### ISSUE THREAD

**Issue by blaskoa** [MicrosoftDocs/architecture-center#3287]
Hi, the link https://azure.microsoft.com/en-us/resources/videos/ignite-2018-run-a-serverless-kubernetes-cluster-by-bridging-aks-and-aci-through-the-virtual-kubelet/ contained on this page is dead. It redirects to https://azure.microsoft.com/en-us/resources/videos/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f8f943-7688-65e6-26c9-5d682a225306
* Version Independent ID: 18d298ba-be2b-bc4a-abac-5ea5a94fadca
* Content: [Bursting from AKS with ACI - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scale-using-aks-with-aci)
* Content Source: [docs/solution-ideas/articles/scale-using-aks-with-aci.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/scale-using-aks-with-aci.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @uthappa123
* Microsoft Alias: **utkatte**

**Comment by ShaikMaheer-MSFT** [comment]
@blaskoa Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by uthappa123** [comment]
Thanks. Updated. Created a pull request - https://github.com/MicrosoftDocs/architecture-center/pull/3293
