### ISSUE TITLE
Code samples for IoT Hub w/ third-party token servers not rendered correctly

### ISSUE THREAD

**Issue by stewartadam** [MicrosoftDocs/architecture-center#3290]
Code snippets appears to have underscores escaped and is written in all-caps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c61bdcd-d090-e908-11cc-6328c7a147aa
* Version Independent ID: 8f22b36e-33ac-9535-6658-c7059da6b856
* Content: [Azure IoT client SDK support for third-party token servers - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/iot/azure-iot-client-sdk-support)
* Content Source: [docs/guide/iot/azure-iot-client-sdk-support.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/iot/azure-iot-client-sdk-support.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by v-fearam** [comment]
#please-close
