### ISSUE TITLE
7lowa lpage

### ISSUE THREAD

**Issue by solei90l** [MicrosoftDocs/architecture-center#3291]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02ce282-99fb-660f-5429-63464639425c
* Version Independent ID: f78d5883-88d5-091e-24b9-318aeea0f168
* Content: [AKS container CI/CD with Jenkins and Kubernetes - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/container-cicd-using-jenkins-and-kubernetes-on-azure-container-service)
* Content Source: [docs/solution-ideas/articles/container-cicd-using-jenkins-and-kubernetes-on-azure-container-service.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/container-cicd-using-jenkins-and-kubernetes-on-azure-container-service.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by MartinJaffer-MSFT** [comment]
@solei90l could you please provide some more information?  I'm not certain what you are trying to say by "7lowa lpage".

**Comment by skabou** [comment]
It is unclear how to assist.  If assistance is still needed, please open with additional details.
