### ISSUE TITLE
Please expand

### ISSUE THREAD

**Issue by wmstjean** [MicrosoftDocs/architecture-center#3292]
Great reference material, those of us in HIM would benefit greatly from more information, such as potential use cases, alternative services, implementation considerations, or pricing guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8be93cf-da00-d500-09fa-85388e8e9c4e
* Version Independent ID: abf64496-ef01-7b90-4819-8236621bde94
* Content: [Population health management for healthcare - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/population-health-management-for-healthcare)
* Content Source: [docs/solution-ideas/articles/population-health-management-for-healthcare.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/population-health-management-for-healthcare.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @krisbock
* Microsoft Alias: **pnp**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for bringing this to our attention.  To better assist you, could you please identify which document this is in reference to?

**Comment by v-fearam** [comment]
Hi @wmstjean


Sorry for the delay and thanks for the suggestions. 

This current article is a  “Solution idea” which its goals is to keep it simple, here there is more information about healthcare which would cover your concerns


https://learn.microsoft.com/en-us/industry/healthcare/



https://learn.microsoft.com/en-us/azure/architecture/industries/healthcare



I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close

**Comment by ckittel** [comment]
@ChrisCynefin -- Content signal to expand a solution idea into an example workload.
