### ISSUE TITLE
Public Preview of FSLogix profiles for Azure AD-joined VMs in Azure Virtual Desktop

### ISSUE THREAD

**Issue by ivratche** [MicrosoftDocs/architecture-center#3297]
Looks like this article needs an udpate? https://techcommunity.microsoft.com/t5/azure-virtual-desktop-blog/announcing-public-preview-of-fslogix-profiles-for-azure-ad/ba-p/3019855 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96947883-d52b-1ed8-7db2-915f025060af
* Version Independent ID: 96947883-d52b-1ed8-7db2-915f025060af
* Content: [Azure AD join for Azure Virtual Desktop - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join)
* Content Source: [docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by hallihan** [comment]
I believe the edits in 32c3885743130735ec94b24345a9861be09b3836 address this, please add more details if this is not the case. #please-close
