### ISSUE TITLE
First Visio Link is incorrect.

### ISSUE THREAD

**Issue by robvet** [MicrosoftDocs/architecture-center#3298]
First Visio link appears to be wrong. It's download Visio file to a single region example.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web app - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/multi-region.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Arvindboggaram
* Microsoft Alias: **arboggar**

**Comment by ShaikMaheer-MSFT** [comment]
@robvet Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by Arvindboggaram** [comment]
The Visio file has three tabs, select the multi-region tab for the reference diagram
