### ISSUE TITLE
Architecture Diagram does not load

### ISSUE THREAD

**Issue by Torgeir-Hansen** [MicrosoftDocs/architecture-center#3300]
![image](https://user-images.githubusercontent.com/58551036/153572596-f08d114e-c345-44e5-9724-80821d4654dc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df354e21-f263-30a9-1a5c-1460f2bf16a9
* Version Independent ID: 73d2f19b-00a0-fe4d-7042-15d27f586565
* Content: [Web application monitoring on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/app-monitoring)
* Content Source: [docs/reference-architectures/app-service-web-app/app-monitoring.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/app-monitoring.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @Torgeir-Hansen 
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by Marusyk** [comment]
Can be closed

**Comment by skabou** [comment]
It appears this issue has been addressed.  Please re-open with additional information if assistance is still needed.
