### ISSUE TITLE
Missing Decision Tree diagram

### ISSUE THREAD

**Issue by terrymandin** [MicrosoftDocs/architecture-center#3301]
This page appears to be broken.  It no longer includes the decision tree.  See attached.
![image](https://user-images.githubusercontent.com/833055/153634996-f4796154-1c0d-4910-9ae2-5f613030a3a9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88559925-9b9e-d9b3-ddb6-08306692c17b
* Version Independent ID: a25055cb-7cfe-28a0-1c66-06172c037128
* Content: [Data store decision tree - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)
* Content Source: [docs/guide/technology-choices/data-store-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/data-store-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by Marusyk** [comment]
The issue has fixed and can be closed

**Comment by hallihan** [comment]
#please-close
