### ISSUE TITLE
Schema or Free format landing zone with Data Ingestion for Databricks based Modern Analytics Platform

### ISSUE THREAD

**Issue by salavala** [MicrosoftDocs/architecture-center#3302]
Issue -1: Clarity on the Curated Layer
   It would be better to clarify which one from bronze, silver and gold indicates the curated layer. 
Issue-2: Schema based or Free form data ingestion 
  Do you recommend free form ingestion or schema forcing ingestion? 
  Would the free form data ingestion create a data swamp?
  How do you manage loading failures, data reconciliation if we enforce schema-based ingestion? 
Issue-3:  Update the diagram with Databricks Lake House
  Would be put all three layers (Bronze, Silver & Gold) in the Lake House in Delta Format? 
  Do we need to have pre-landing zone (Iron) to ingest schema free data?

**Comment by ram-msft** [comment]
@salavala Thanks for the question. Can you please share with us the URL of the document that you are having issues with?

**Comment by MayankBargali-MSFT** [comment]
@salavala Following up to see if you can provide more details on what document you have referred to?

**Comment by MayankBargali-MSFT** [comment]
@salavala As there was no response. We will now proceed to close this thread. If there are further questions regarding this matter, please share the document that you are referring to and we will gladly continue the discussion.
