### ISSUE TITLE
Model analysis

### ISSUE THREAD

**Issue by dutchmark888** [MicrosoftDocs/architecture-center#3304]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e55d3a73-7618-45ba-b281-bb70dd258842
* Version Independent ID: 7f5cd352-0998-a214-8dfc-c19898cecd21
* Content: [Domain analysis for microservices - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/model/domain-analysis)
* Content Source: [docs/microservices/model/domain-analysis.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/model/domain-analysis.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by Karishma-Tiwari-MSFT** [comment]
To help us understand your ask better, can you please share more details on what more information you would like to be added to this document? Thanks.

**Comment by Karishma-Tiwari-MSFT** [comment]
This azure-docs repository deals about feedback ((like correcting doc bugs, doc enhancements, product issues related to wrong doc instructions, etc.) related to particular Azure document page so if issue is intended to update / correct / enhance anything in an Azure document then please share Azure document link / URL and share the feedback related to it.

**Comment by Karishma-Tiwari-MSFT** [comment]
We will now close this issue. Please share the details when you get a chance and tag me in a comment. I will reopen it and we will gladly continue the discussion.
