### ISSUE TITLE
Bug - Table of Content Options

### ISSUE THREAD

**Issue by josephmcasey** [MicrosoftDocs/architecture-center#3305]
## Root Cause
Source Code: [docs/toc.yml](https://github.com/MicrosoftDocs/architecture-center/blob/c13102196d67c4c476dbc376e94d664a4fb5df4b/docs/toc.yml#L67)
Website: [azure/architecture/guide/technology-choices](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#:~:text=Choose%20a%20Kubernetes%20edge%20option)

## What Happens
0. Go to [Azure Architecture's Technology Choices Table of Content Panel](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#:~:text=Choose%20a%20Kubernetes%20edge%20option)
1. User selects `Choose a Kubernetes edge option` <sup>[1]</sup>
2. Users browser is directed to https://docs.microsoft.com/en-us/ <sup>[2]</sup>

## Browser Information

Google Chrome | 98.0.4758.80 (Official Build) (64-bit)
-- | --
Revision | 7f0488e8ba0d8e019187c6325a16c29d9b7f4989-refs/branch-heads/4758@{#972}
OS | Linux
JavaScript | V8 9.8.177.9
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --enable-crashpad --flag-switches-begin --sync-url=https://chrome-sync.sandbox.google.com/chrome-sync/alpha --enable-features=Vulkan --disable-features=HardwareMediaKeyHandling --flag-switches-end
Executable Path | /opt/google/chrome/google-chrome
Profile Path | /home/josephmcasey/.config/google-chrome/Profile 11
Variations | f475deb0-377be55a313957be-ca7d8d803e7d7783-ca7d8d807e184ca7-33c3eba590a7075b-362044e7a112f012-ca7d8d8016b16054-377be55a59b6f412-377be55a60d4b352-377be55a273268f8-17797c246cb5e962-377be55aa77166f2-ca7d8d806e08fc3e-ca7d8d80481fc7e7-12ede6a23e09e9b1-ca7d8d80eddd0d82-21e0edc789a16501-ca7d8d8087f33ad6-ca7d8d8074f8fa8f-ca7d8d803095aa95-3f4a17df34e1db5c-377be55a4662e1aa-ca7d8d80a257327f-ca7d8d806cbcf5b7-6edc92c76c5f69af-377be55a47bd2c48-377be55a1e940a7c-ca7d8d8044c2e2c0-ca7d8d804701a278-f23d1dea4749874c-fe2c00b67c2504d0-ca7d8d80ab544014-ca7d8d803f6e921e-377be55a7f122175-ca7d8d804e3ec83a-ca7d8d8065570806-20f58b6fb507d18e-ca7d8d8053fd5552-12ede6a2dd8d67e-1f8c5973f6f5c542-12ede6a2a582a1b8-ad75ce17fa659f2e-377be55ada2d8531-ca7d8d80e87da360-377be55a6a5f15b-377be55a1d606bb5-cdda86d5d89faab1-377be55a722b8030-874626a33042ad4b-5bbb3702ba47366-ca7d8d80248c3fbd-ca7d8d806668be8b-a22c9c1dd7a036b9-ca7d8d8073645b32-ca7d8d80e79de56c-ca7d8d80357a64de-ca7d8d808bccc03b-ca7d8d8029c62d4-ca7d8d80551dab91-ca7d8d8069d4ebd5-ca7d8d802b4e7fda-b80d0b98b012722b-6edc92c7727723f1-946682d3b75782da-ca7d8d808c8d8faf-1f8c5973ca51d624-ca7d8d80f7a3ec9-ca7d8d80ca5a2953-ca7d8d808bfdd36f-7ef85c8e5fe247df-ca7d8d80ad46906e-ca7d8d80234de0a0-ca7d8d80d3566fbd-377be55a4ea303a6-ecbb250efc7e4d22-ca7d8d802e0ef3d0-df7317d7c9e4cf65-12ede6a22d5bcfa8-377be55a950809af-377be55a77e44b8e-377be55a6de6716f-ca7d8d80fbe267b5-ca7d8d80e8c68789-ca7d8d8054410569-ca7d8d80ad4acdda-ca7d8d80931c5f72-5c0c1f00494d8760-52325d437b2873c2-f9e346373ac60855-486e2a9cf48c01d3-dccc52f863dcb6a3-75dc9252e706e746-eaceac83f296190c-2624949d4442aae2-6e597edef690cf64-75cb33fced1d377-e1cc0f1475f0f0a0-e1cc0f14e2b18481-a90023b1e7e71889-e1cc0f14b1ceb06f-d137233432d6b1fe-ca7d8d802d3dfd19-ca7d8d80762bb3b2-ca7d8d80e1368496-377be55a6becb1e-12ede6a2248e3a0-ca7d8d804ebfaf88-12ede6a2595f5eb0-ca7d8d809e91ce29-ca7d8d80e3969921-ca7d8d803673692f-ca7d8d80653036a-ca7d8d80bef5c006-ca7d8d80a16ee973-3a0600b9b4e05be7-9c7cf9bf662773da-39e85e9bc3859e82-a22067f8def27776-ca7d8d80733cb831-377be55ab53f3ef9-ca7d8d802856aa31-a6c00ad8

## Screenshots

**[1]**
![Technology-Choices](https://user-images.githubusercontent.com/5309910/153728835-83ef1acb-35d1-45b7-8723-46194dfc9e8b.png)

**[2]**
![technical-documentation](https://user-images.githubusercontent.com/5309910/153728837-4892a663-e0aa-48ee-93ad-d20cd0ac1375.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by josephmcasey** [comment]
I lack the necessary information to know the appropriate solution. My most educated guess would be that this tab might have been intended to direct to this URL? 

https://docs.microsoft.com/en-us/azure/architecture/operator-guides/aks/choose-kubernetes-edge-compute-option

**Comment by ram-msft** [comment]
@josephmcasey Thanks for the feedback! We will review and update accordingly.

**Comment by skabou** [comment]
It appears this has been addressed.  If you are still experiencing issues, please re-open with additional information.
