### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by rmc515** [MicrosoftDocs/architecture-center#3306]
In the "Application Gateway before Firewall" section, it says:

This design is appropriate for applications that need to know incoming client source IP addresses, for example to serve geolocation-specific content or for logging. Azure Firewall SNATs the incoming traffic, changing the original source IP address.

Then later, after the picture on step 3 it says:

Azure Firewall doesn't SNAT the traffic, because the traffic is going to a private IP address. It forwards the traffic to the application VM if rules allow it. For more information, see [Azure Firewall SNAT](https://docs.microsoft.com/en-us/azure/firewall/snat-private-range).

Just confused by this and wondering if the first section I put should read "Web Application Gateway" SNATs the incoming traffic rather than "Azure Firewall"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall, App Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **pnp**

**Comment by erjosito** [comment]
Hey @rmc515 thanks for that! Great catch, that sentence shouldnt be there. I have made a correction to the document, it is already merged and it should be online in a few hours. Could you let me know if that has fixed the issue?

Thanks!

**Comment by erjosito** [comment]
I think we can close this as fixed

**Comment by v-fearam** [comment]
#please-close
