### ISSUE TITLE
Need chat box kind of help to select suitable azure architecture solution

### ISSUE THREAD

**Issue by midhunkalaivasan** [MicrosoftDocs/architecture-center#3307]
Hi,

Need chat box kind of help to select suitable azure architecture solution.

It would be very helpful if introduce chat box type of user friendly session to select a suitable architecture for user needs.

Azure should propose some recommended architecture design in azure architecture center based on customer needs.

Thanks,
Midhun K

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Fundamentals - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by VikasPullagura-MSFT** [comment]
@midhunkalaivasan 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@EdPrice-MSFT 
Can you please check and add your comments on this request as applicable.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24176 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
