### ISSUE TITLE
Possible improvement to image on Solution section of the Claim-Check pattern page

### ISSUE THREAD

**Issue by reub-the-cube** [MicrosoftDocs/architecture-center#3308]
We were reviewing the diagram in the Solution section and felt that having arrows (1/2/3/4) might be beneficial for some readers, to make it clearer that the reference included in the middle message is a result of having stored the payload to the data store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1970e0cd-53ae-02f6-479b-9ca386a5220e
* Version Independent ID: 8a81baa3-61c2-a8f6-540c-9a239583b8d6
* Content: [Claim-Check pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check#feedback)
* Content Source: [docs/patterns/claim-check.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/claim-check.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @yorek
* Microsoft Alias: **pnp**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the feedback! We will review and get back to you shortly.

**Comment by v-fearam** [comment]
#please-close

**Comment by v-fearam** [comment]
PR was merge, it is going to be publish soon. Thanks for the suggestion.
