### ISSUE TITLE
Issue with deploying AVD VM with Azure AD Join

### ISSUE THREAD

**Issue by FallenHoot** [MicrosoftDocs/architecture-center#3309]
When Deploying AVD VM it fails to connect to Azure AD Join
![image](https://user-images.githubusercontent.com/19664186/154131461-05309200-f655-46c1-b018-1efe90d08618.png)
![image](https://user-images.githubusercontent.com/19664186/154131528-e5af58c4-c214-45ca-963a-533e76d3b94c.png)
![image](https://user-images.githubusercontent.com/19664186/154130858-3000f39e-a91e-4c03-a9ee-3553c812fe86.png)
The top one is following the steps below and the bottom one is the default one that comes when you add a session host. 
![image](https://user-images.githubusercontent.com/19664186/154139822-e50b0f13-39be-4d6e-bb8d-64d72ea12970.png)

To solve this, you must uninstall the extension provided and add "Azure AD based Windows Login"
![image](https://user-images.githubusercontent.com/19664186/154130949-dc80df93-0922-432a-9147-48c21de9aa86.png)
![image](https://user-images.githubusercontent.com/19664186/154131085-071177a2-3464-4307-b611-18c518f16714.png)

Before it works, you must restart the VM. 
![image](https://user-images.githubusercontent.com/19664186/154131839-d7546843-ad7f-4acf-8a4d-62ab27cff7c7.png)

Then check to see if it worked. 
![image](https://user-images.githubusercontent.com/19664186/154131637-bc53fcb8-55db-4ae9-b4bc-425404c4c956.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96947883-d52b-1ed8-7db2-915f025060af
* Version Independent ID: 96947883-d52b-1ed8-7db2-915f025060af
* Content: [Azure AD join for Azure Virtual Desktop - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join)
* Content Source: [docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by VikasPullagura-MSFT** [comment]
@FallenHoot 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@TomHickling 
Can you please check and add your comments on this doc update request as applicable.

**Comment by v-fearam** [comment]
Hi @FallenHoot

Sorry for the delay. 

The document has changed a lot since the issue was reported. 

 I recommend leveraging the support options available in the Azure DevOps portal if you are still facing this issue.


I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
