### ISSUE TITLE
Link is not working for "Managing Microsoft 365 in true DevOps style with Microsoft365DSC and Azure DevOps"

### ISSUE THREAD

**Issue by davidsrhans** [MicrosoftDocs/architecture-center#3311]
the link to the article at the end of the page for "[Managing Microsoft 365 in true DevOps style with Microsoft365DSC and Azure DevOps](https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf)" is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5235541-bce4-2057-81c0-0557fe8a196a
* Version Independent ID: d5235541-bce4-2057-81c0-0557fe8a196a
* Content: [Manage Microsoft 365 tenant configuration with Azure DevOps - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/manage-microsoft-365-tenant-configuration-microsoft365dsc-devops?source=docs)
* Content Source: [docs/example-scenario/devops/manage-microsoft-365-tenant-configuration-microsoft365dsc-devops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/manage-microsoft-365-tenant-configuration-microsoft365dsc-devops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @desmay
* Microsoft Alias: **desmay**

**Comment by desmay** [comment]
@davidsrhans Are you referring to a link in the PDF on managing [M365 with DevOps](https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf) or on the [docs site](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/manage-microsoft-365-tenant-configuration-microsoft365dsc-devops?source=docs) ? I looked through both and couldn't find a dead link.

**Comment by desmay** [comment]
Interesting that [link](https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf) works fine for me. 

<img width="835" alt="image" src="https://user-images.githubusercontent.com/43035577/154701673-42bf0952-4753-4c43-9b0c-037e953dd604.png">

**Comment by davidsrhans** [comment]
Hi Derek,

I have tested on 1 other PC and it worked.. but it did take a long time to load.

On my mobile phone it starts to load, but just sits there

on my main machine, it crashes out straigt away.  I will reboot and see if that makes a difference.  My machine (win 11) cant reach the actual website office365dsc.azurewebsites.net<https://office365dsc.azurewebsites.net/>!



Bit of a big screenshot - but I wanted to show you what I get:
[cid:6b60320b-4e6e-4ccf-8996-4fea10a94396]

regards,
David Hans

***@***.***

________________________________

**Comment by davidsrhans** [comment]
Good Morning Derek,

I tested again this morning, after a reboot, and all was working fine again.  I guess it was a DNS issue on my machine (Win11, wake up from hibernate)

Can you please close this issue? And I am sorry that this was an issue on my end.

regards,
David Hans

***@***.***

________________________________

**Comment by desmay** [comment]
@ChaitanyaNaykodi-MSFT Can be closed per author
