### ISSUE TITLE
"Secrets" section still erroneously points to AAD Pod Identity

### ISSUE THREAD

**Issue by msftnadavbh** [MicrosoftDocs/architecture-center#3312]
The "Secrets management" section still points to AAD Pod Identity.
Microsoft already does not recommend using this as it's being replaced by Azure AD Workload Identity : 
https://azure.github.io/azure-workload-identity/docs/

The document should reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on AKS - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices)
* Content Source: [docs/reference-architectures/containers/aks-microservices/aks-microservices.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-microservices/aks-microservices.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by msftnadavbh** [comment]
Hi - any updates on this?

**Comment by hallihan** [comment]
This should be addressed in the latest updates to the article.
