### ISSUE TITLE
Container Apps

### ISSUE THREAD

**Issue by bulentozkir** [MicrosoftDocs/architecture-center#3314]
[Enter feedback here]

Can you add Container Apps in to the diagram? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by SaurabhSharma-MSFT** [comment]
@bulentozkir Thanks for your feedback! We will investigate and update as appropriate.

**Comment by stephen-sumner** [comment]
@bulentozkir - Thank you so much for your feedback! I know it's been some time, but it looks like Azure Container App is in the diagram. I'm going to close this thread, but thank you again for you input!
