### ISSUE TITLE
DevTest

### ISSUE THREAD

**Issue by breval-dev** [MicrosoftDocs/architecture-center#3315]
Hello !

Can you please tell me : 

Where I can find all the PaaS services who a able to be use in DevTest Lab ?
It is possible to deploy IaaS services in DevTest Lab ?

Thanks !

**Comment by SaurabhSharma-MSFT** [comment]
@breval-dev To assist you better on your query could you provide us with the link to the document you are referring to ?
In case your query in not related to document content, open a new forum thread either Microsoft Q&A or StackOverflow as it could be better place to get help on your scenario where the community members could provide their expert guidance to you based on their experience.

**Comment by SaurabhSharma-MSFT** [comment]
@breval-dev We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
