### ISSUE TITLE
MDM integration

### ISSUE THREAD

**Issue by dpc2604** [MicrosoftDocs/architecture-center#3318]
It would be great to see a flavor of this that incorporated MDM (such as Profisee)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254782d-e773-b542-73e8-f568d3bbee39
* Version Independent ID: 40d81223-f8ea-2eec-616e-5f6ee28c8206
* Content: [Modern analytics architecture with Azure Databricks - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture)
* Content Source: [docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @kacummis
* Microsoft Alias: **kacummis**

**Comment by SaurabhSharma-MSFT** [comment]
@dpc2604 Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24174 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
