### ISSUE TITLE
Incorporating Purview and Profisee

### ISSUE THREAD

**Issue by dpc2604** [MicrosoftDocs/architecture-center#3319]
We're looking at this architecture but also with Purview and Profisee (MDM).
It would be great to see a digram of how that may fit together

**Comment by SaurabhSharma-MSFT** [comment]
@dpc2604 To assist you better on your query could you provide us with the link to the document you are referring to ?
In case your query in not related to document content, open a new forum thread either Microsoft Q&A or StackOverflow as it could be better place to get help on your scenario where the community members could provide their expert guidance to you based on their experience.

**Comment by SaurabhSharma-MSFT** [comment]
@dpc2604 We will now proceed to close this thread as we have not heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
