### ISSUE TITLE
Nice learning platform from Learn - Microsoft Docs

### ISSUE THREAD

**Issue by shashankspole** [MicrosoftDocs/architecture-center#3320]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Build solutions with availability zones - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/high-availability/building-solutions-for-high-availability.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@shashankspole Thanks for reaching out and providing feedback. Just want to confirm if the github request was opened for providing the feedback and there are no document bug before we close out this request.

**Comment by RobBagby** [comment]
@shashankspole  - I am closing this item. Please reopen if you believe I closed this in error.
