### ISSUE TITLE
Hope to engage with the creator/contributor of this document

### ISSUE THREAD

**Issue by pinyuko** [MicrosoftDocs/architecture-center#3322]
[Enter feedback here]

Hi,

I'm Penny Ko (kopenny) in Microsoft. Azure NetApp Files (ANF) team Arnt de Gier (b-arntdegier) would like to update below 2 documents, but there are no Contributor listed on those documents. Is it possible that you could help to identify the creator of that content and share with us? So Arnt would be able to share feedback and hopefully can reuse the existing Visio file instead of creating one from scratch. Thank you!
1.	https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-dev-test : It has no mention of ANF
2.	https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-production : ANF is only in one sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e700b9a2-8b1d-5d55-95ec-1bb123d2586a
* Version Independent ID: 7f4b8f89-a777-b03b-e0af-d3d890745088
* Content: [SAP deployment on Azure using an Oracle database - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-production)
* Content Source: [docs/example-scenario/apps/sap-production.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/sap-production.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @DharmeshBhagat
* Microsoft Alias: **pnp**

**Comment by SaurabhSharma-MSFT** [comment]
@pinyuko Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by skabou** [comment]
It appears this was resolved. If assistance is still needed, please re-open with additional information.
