### ISSUE TITLE
cortana-intelligence-call-center-solution project 

### ISSUE THREAD

**Issue by redhatpeter** [MicrosoftDocs/architecture-center#3324]
Hi 

it seems that the project (referred in this doc) is not working.  i am getting errors stating that I believe the dependency is no longer available, can someone help me with this? 

if this project is no longer working then it should be removed from the documentation. 

---------------------------- error ---------------
➜  cortana-intelligence-call-center-solution git:(master) npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: **shtg-call-center**@1.0.0
npm ERR! Found: botbuilder-calling@undefined
npm ERR! node_modules/botbuilder-calling
npm ERR!   botbuilder-calling@"https://chstone.blob.core.windows.net/public/botbuilder-calling-3.0.2-0.tgz" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer botbuilder-calling@"^3.0.1" from botbuilder-calling-speech@1.0.21
npm ERR! node_modules/botbuilder-calling-speech
npm ERR!   botbuilder-calling-speech@"^1.0.20" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/peterlee/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peterlee/.npm/_logs/2022-02-25T18_41_20_747Z-debug-0.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ec8051-dea1-e162-6856-4de1bba362aa
* Version Independent ID: 17661180-e55f-ee23-97b4-f910735fb90a
* Content: [Interactive voice response app with bot - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/interactive-voice-response-bot)
* Content Source: [docs/solution-ideas/articles/interactive-voice-response-bot.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/interactive-voice-response-bot.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by AnuragSharma-MSFT** [comment]
@redhatpeter Thank you for the feedback. We are actively investigating and will get back to you soon.
