### ISSUE TITLE
Missing explanation for NoSQL secondary indexes

### ISSUE THREAD

**Issue by parthik19** [MicrosoftDocs/architecture-center#3325]
There needs to be an explanation as to why NoSQL databases don't typically offer this feature to the extent the way SQL databases do.

https://github.com/MicrosoftDocs/architecture-center/blob/ea468dd927470a79edd7ce968918e6232e5f28e4/docs/patterns/index-table.md?plain=1#L34

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36982a55-b653-9f6b-6b51-f50105abde18
* Version Independent ID: 81ada183-46a5-9101-7f53-b008e83c7f68
* Content: [Index Table pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/index-table)
* Content Source: [docs/patterns/index-table.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/index-table.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by SaurabhSharma-MSFT** [comment]
@parthik19 Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by v-fearam** [comment]
#please-close
