### ISSUE TITLE
Expand example "CI/CD for containers"

### ISSUE THREAD

**Issue by JosiahParry** [MicrosoftDocs/architecture-center#3326]
Creating an issue as recommended via https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cicd-for-containers.

It would be great if this could be expanded further to include example pipeline yaml etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d04d315-a0de-8f52-7898-72fda344e924
* Version Independent ID: 5b7bd552-d3fc-0d94-ddee-bed399fd7232
* Content: [CI/CD for containers - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cicd-for-containers)
* Content Source: [docs/solution-ideas/articles/cicd-for-containers.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/cicd-for-containers.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MonikaReddy-MSFT** [comment]
@JosiahParry - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can review and update the document accordingly.

**Comment by ckittel** [comment]
FYI @mosabami & @jamcneil

**Comment by ckittel** [comment]
This article was abandoned and has since been deleted.

#please-close
