### ISSUE TITLE
Missing Azure Icon

### ISSUE THREAD

**Issue by OthmanBaalache** [MicrosoftDocs/architecture-center#3328]
Please add the icon for Azure Monitor Private Link Service!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/?source=docs)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@OthmanBaalache Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by Zimmergren** [comment]
Thank you for reporting this. We've added a request internally to add this icon to the next update of the icons pack. 
Meanwhile, the latest icon pack contain hundreds of new icons - please review and see if these meet your requirements. 

Thanks. 
#please-close
