### ISSUE TITLE
TPM.2.0

### ISSUE THREAD

**Issue by stszafa** [MicrosoftDocs/architecture-center#3331]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade8ea3-b02f-6c92-b7b1-8f37a5c9d701
* Version Independent ID: c0bde50c-5e28-5ff2-1507-5a8711ae3022
* Content: [Azure Application Architecture Fundamentals - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/)
* Content Source: [docs/guide/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MonikaReddy-MSFT** [comment]
@stszafa - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by hallihan** [comment]
It's not clear what the problem or suggestion is for the article.  Feel free to open another issue with more details if help is still needed.
