### ISSUE TITLE
Can sustainable coding practices or green coding also be available 

### ISSUE THREAD

**Issue by sandhyan21** [MicrosoftDocs/architecture-center#3332]
[Enter feedback here]
Can sustainable coding practices or green coding also be available under responsible coding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f1a7ed-041f-c313-9a25-facdc4aebea4
* Version Independent ID: 20908b14-6258-ae56-73bc-323e5c9ac75b
* Content: [Responsible Innovation toolkit - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/responsible-innovation/)
* Content Source: [docs/guide/responsible-innovation/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/responsible-innovation/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dcass
* Microsoft Alias: **pnp**

**Comment by RohitMungi-MSFT** [comment]
@sandhyan21 Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by skabou** [comment]
This looks like it has been addressed.  Please re-open with additional information if assistance is still needed.
