### ISSUE TITLE
Article and spreadsheet naming number differs

### ISSUE THREAD

**Issue by dogborne** [MicrosoftDocs/architecture-center#3333]
The CA-Persona-Internals is CA100 on the docs page but CA200 on the spreadsheet. I know these are examples but it might confuse people. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7fac997-1920-f24e-767a-13755b794f85
* Version Independent ID: a7fac997-1920-f24e-767a-13755b794f85
* Content: [Conditional Access framework and policies - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/security/conditional-access-framework)
* Content Source: [docs/guide/security/conditional-access-framework.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/conditional-access-framework.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @clajes
* Microsoft Alias: **clajes**

**Comment by RohitMungi-MSFT** [comment]
@dogborne Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by clajes** [comment]
thanks for the comment, I fully agree and will update and do a PR

**Comment by skabou** [comment]
It appears this was addressed. Please reopen with additional details if still experiencing issues.
