### ISSUE TITLE
Microsoft Graph Data Connect missing from Arch diagram

### ISSUE THREAD

**Issue by calvindrover** [MicrosoftDocs/architecture-center#3335]
Can we update the solution architecture to show the Microsoft Graph Data Connect ADF pipeline  connection to M365 for email attachment extract?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7bd654-4757-bdad-e821-5df35cdfd6e9
* Version Independent ID: 9e7bd654-4757-bdad-e821-5df35cdfd6e9
* Content: [Automate document processing by using Azure Form Recognizer - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/ai/automate-document-processing-azure-form-recognizer)
* Content Source: [docs/example-scenario/ai/automate-document-processing-azure-form-recognizer.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/ai/automate-document-processing-azure-form-recognizer.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jyravi
* Microsoft Alias: **jyravi**

**Comment by MarileeTurscak-MSFT** [comment]
@calvindrover thanks! @jyravi and @EdPrice-MSFT can you look into this?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24169 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
