### ISSUE TITLE
Not All Page Appears When Export To PDF

### ISSUE THREAD

**Issue by juandrn** [MicrosoftDocs/architecture-center#3337]
When I export to PDF some page doesn't appears for example:

 - Circuit Breaker Pattern
 - Claim Check
 - Compensating Transaction
 - Competing Consumers
 - Compute Resource Consolidation
 - CQRS
 - Deployment Stamps
 - Event Sourcing
 - External Configuration Store
 - Federated Identity

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [Cloud design patterns - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/)
* Content Source: [docs/patterns/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/index.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **masashin**

**Comment by RohitMungi-MSFT** [comment]
@juandrn Thanks for reporting this. @TimShererWithAquent It looks like the downloadable PDF format of the documentation is missing these sections. Could you please review and update as required?

**Comment by WilliamAntonRohm** [comment]
@RohitMungi-MSFT -- Rohit, I'm looking into this.

**Comment by hallihan** [comment]
@WilliamAntonRohm - did you ever find out what was going on here?  Is the issue resolved?
