### ISSUE TITLE
Wrong description of ML in ASA

### ISSUE THREAD

**Issue by rsk800** [MicrosoftDocs/architecture-center#3339]
"What you can do with it" for ASA looks just copied from upper row.

![image](https://user-images.githubusercontent.com/23612897/157604006-d307f460-61ad-4334-813c-aca79ed733b5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bdc71b-0a54-4cc4-1b79-f60e274e9a51
* Version Independent ID: 1783570c-3545-71c8-72d3-d5657f77c070
* Content: [Microsoft machine learning products - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning)
* Content Source: [docs/data-guide/technology-choices/data-science-and-machine-learning.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/data-science-and-machine-learning.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@rsk800 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MarileeTurscak-MSFT** [comment]
@rsk800 thanks for calling this out! I made a pull request to fix the text. https://github.com/MicrosoftDocs/architecture-center-pr/pull/5510
