### ISSUE TITLE
Woodgrove Bank/CNB.COM

### ISSUE THREAD

**Issue by Drewp2020** [MicrosoftDocs/architecture-center#3341]
`3888757064202255`
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97abbeb4-6c20-4dfd-8a3f-3b448919679c
* Version Independent ID: d979d82d-2e80-5a1e-7928-7f8154ed34f3
* Content: [Choose a data analytics and reporting technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analysis-visualizations-reporting)
* Content Source: [docs/data-guide/technology-choices/analysis-visualizations-reporting.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/analysis-visualizations-reporting.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by Drewp2020** [comment]
https://woodgrovefinance.com/Account/LogIn
https://bisprofiles.com/fl/credible-operations-f17000004595
KEY FACTS ABOUT CREDIBLE OPERATIONS, INC.

    US Businesses Companies in Florida Leon County Companies 

Company name
    CREDIBLE OPERATIONS, INC.
Status
    Active
Filed Number
    F17000004595
FEI Number
    822798528
Date of Incorporation
    October 12, 2017
    Age - 5 years 
Home State
    DE
Company Type
    Foreign for Profit

CREDIBLE OPERATIONS, INC. NEAR ME

Principal Address
    320 Blackwell Street,
    DURHAM,
    NC,
    27701,
    US
Mailing Address
    22 4TH ST., FL 8,
    SAN FRANCISCO,
    CA,
    94103,
    US 
https://www.credible.com/a/agents/?utm_source=agents&utm_medium=referral&utm_campaign=mort_purchase
https://www.facebook.com/crediblelabs
https://twitter.com/credible https://www.dominos.com/ https://www.jetblue.com/https://www.pnfp.com/https://www.credible.com/personal-loan-prequalification

**Comment by Drewp2020** [comment]
ss#412334610

**Comment by Drewp2020** [comment]
https://oasisband.net/https://account.microsoft.com/

**Comment by Drewp2020** [comment]
https://my.cnbtn.com/forgot CNBapp/login/#902300023329/password/Laserl2020

**Comment by MarileeTurscak-MSFT** [comment]
@Drewp2020 thanks for your feedback! If you have specific feedback on the document, please create a new issue detailing what you would like updated.
