### ISSUE TITLE
代替アクセスマッピングを利用する際にはL7レベルのAzure Application Gatewayが必要

### ISSUE THREAD

**Issue by keizom** [MicrosoftDocs/architecture-center#3344]
[フィードバックをこちらに入力してください]

SharePointの代替アクセスマッピングを利用する際には、
L7レベルの負荷分散が必要になるため、L４レベルのAzure Load Blancerではなく、L7レベルのAzure Application Gatewayが必要になります。

出来れば、条件付きで記載をお願いしたいです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6d93eb87-54cb-cf38-dfae-0ebe7579d608
* Version Independent ID: c7ac665e-d194-ab07-c1bb-5d5a3049c5ec
* Content: [Azure での高可用性 SharePoint Server 2016 ファームの実行 - Azure Reference Architectures](https://docs.microsoft.com/ja-jp/azure/architecture/reference-architectures/sharepoint/)
* Content Source: [docs/reference-architectures/sharepoint/index.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/sharepoint/index.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MarileeTurscak-MSFT** [comment]
@keizom thanks for the feedback! I ran a translation and this appears to be the same feedback as this issue: https://github.com/MicrosoftDocs/architecture-center/issues/3343

I have assigned the other issue to the author and am closing this out as a duplicate.
