### ISSUE TITLE
"Azure Virtual Desktop control plane" is there a typo about panel or plane?

### ISSUE THREAD

**Issue by nascar3000** [MicrosoftDocs/architecture-center#3345]
"Azure Virtual Desktop control plane" 
I coundt find sometnig called "control plane", is there a typo on this one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Azure Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by TomHickling** [comment]
"Control plane" refers to the Azure Virtual Desktop service provided as PaaS. THis is the service that manages all the connectivity/orchestration etc. Microsoft manages this fully

**Comment by nascar3000** [comment]
Thanks for information closing issue.
