### ISSUE TITLE
Diagram contains Azure Security Center instead of Defender for Cloud

### ISSUE THREAD

**Issue by DevSecNinja** [MicrosoftDocs/architecture-center#3346]
Diagram contains Azure Security Center (former name) instead of Defender for Cloud.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce3b9c5-ef05-1ff3-a6fe-052f48a9b471
* Version Independent ID: f6d3e8e8-37c5-43e6-6185-58f8511dee7e
* Content: [Hybrid security monitoring with Sentinel - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-security-monitoring#feedback)
* Content Source: [docs/hybrid/hybrid-security-monitoring.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/hybrid-security-monitoring.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@DevSecNinja 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by DevSecNinja** [comment]
Thank you @MarileeTurscak-MSFT! Feel free to reach out to me on Teams @EdPrice-MSFT, I have made some changes that might be useful.

**Comment by EdPrice-MSFT** [comment]
Looks like the image is updated now. Please review. Thanks!
