### ISSUE TITLE
Azure ServiceBus client SDKs are out of date

### ISSUE THREAD

**Issue by matt-richardson** [MicrosoftDocs/architecture-center#3348]
In the "Service Bus" section, under "Retry mechanism", it mentions to use the `Microsoft.Azure.ServiceBus` libary, as it is the "Azure Service Bus client library for .NET Standard".

That package is [listed](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus) as deprecated now:

> Please note, a newer package Azure.Messaging.ServiceBus is available as of November 2020. While this package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the migration guide at https://aka.ms/azsdk/net/migrate/sb for more details.

It's not clear where to find the retry policy implementations in the new world.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Azure service retry guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@matt-richardson Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by EdPrice-MSFT** [comment]
@ckittel - FYI

**Comment by ckittel** [comment]
@hallihan - something for the maint backlog.

**Comment by hallihan** [comment]
Tracked internally in: https://dev.azure.com/ceapex/pnp/_workitems/edit/603045

**Comment by v-fearam** [comment]
Hi @matt-richardson,

Sorry for the delay. 



The ticket was created some time ago, and the article has been updated several times since then. Now, the article includes Azure.Messaging.ServiceBus.



I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
