### ISSUE TITLE
Graphic icon is mislabeled

### ISSUE THREAD

**Issue by MS-Santi** [MicrosoftDocs/architecture-center#3349]
The SVG, the screen in step 5 stays "Admin Access" and should be "User Access"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS and Azure DevOps - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/microservices-with-aks.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@MS-Santi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by EdPrice-MSFT** [comment]
Logging it for an update. Thanks!
