### ISSUE TITLE
Feedback about event storms

### ISSUE THREAD

**Issue by tamusjroyce** [MicrosoftDocs/architecture-center#3350]
[Enter feedback here]
There is no mention of event storms?

or too hitting this with too many times, such as in a loop can clog up the event store?

Or sending too many event based on receiving an event can clog up the event store?

or cause recursion-like behaviors when reacting and sending events?

Also, determining eventual consistency before using the data is eventual-consistency locking. Very similar to distributed locking.

I have seen this being used without considering pitfalls (not that it shouldn’t be used there - but how it is used needed changed).

but yes. Regardless. Great article!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing)
* Content Source: [docs/patterns/event-sourcing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/event-sourcing.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by v-fearam** [comment]
#please-close
