### ISSUE TITLE
JBoss EAP on Azure Doc unclear

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#3352]
The [Architecture](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/jboss-deployment-red-hat#architecture) shows JBoss EAP on ARO whereas all the docs shows [JBoss EAP on App Service](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/jboss-eap-marketplace-image) through the azure [market place](https://azuremarketplace.microsoft.com/en-US/marketplace/apps/redhat.jboss-eap-rhel).

Why referencing AKS in the [components](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/jboss-deployment-red-hat#components) which has nothing to do there ?

Among the [components](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/jboss-deployment-red-hat#components) could you please add the [JBoss EAP setup on ARO guideline](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/index) ? see also issue #[738](https://github.com/MicrosoftDocs/azure-dev-docs/issues/738)

Also today the only way to integrate [Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-enable-arc-enabled-clusters) with ARO is to connect the [ARO cluster with Azure Arc](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-azure-redhat4-setup) adding the [Azure Monitor extension for Arc,](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/extensions#currently-available-extensions) Azure Arc should be then added to the  [Architecture](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/jboss-deployment-red-hat#architecture)

ARO runs CoreOS by default, not RHEL OS.

Finally Azure DevOps Pipelines are legacy and should be updated with [RedHat GitHub Action from the GH marketplace](https://github.com/marketplace?type=actions&query=redhat+).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0b2538b-e6fa-fc5e-b26d-ff2f32b7993e
* Version Independent ID: 91b38032-b389-a2c4-d6b1-d009f4c5b725
* Content: [JBoss deployment with Red Hat on Azure - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/jboss-deployment-red-hat#architecture)
* Content Source: [docs/solution-ideas/articles/jboss-deployment-red-hat.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/jboss-deployment-red-hat.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @YenChiHo
* Microsoft Alias: **yenchiho**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by ezYakaEagle442** [comment]
my bad, JBoss EAP is [available](https://docs.microsoft.com/en-us/azure/app-service/configure-language-java?pivots=platform-linux) in App Service only with Premium v3 & Isolated v2 App Service [Plan](https://docs.microsoft.com/en-us/azure/app-service/overview-hosting-plans) types
Verified with az webapp list-runtimes --linux | grep -i "JBOSSEAP" :
[
  "JBOSSEAP|7-java8",
  "JBOSSEAP|7.3-java8",
  "JBOSSEAP|7-java11",
  "JBOSSEAP|7.3-java11",
]

**Comment by EdPrice-MSFT** [comment]
> my bad, JBoss EAP is [available](https://docs.microsoft.com/en-us/azure/app-service/configure-language-java?pivots=platform-linux) in App Service only with Premium v3 & Isolated v2 App Service [Plan](https://docs.microsoft.com/en-us/azure/app-service/overview-hosting-plans) types Verified with az webapp list-runtimes --linux | grep -i "JBOSSEAP" : [ "JBOSSEAP|7-java8", "JBOSSEAP|7.3-java8", "JBOSSEAP|7-java11", "JBOSSEAP|7.3-java11", ]

Any changes to this article then?

**Comment by ezYakaEagle442** [comment]
@EdPrice-MSFT , yes the doc should be updated, the architecture diagram is not consistent with the text including the components section

**Comment by v-fearam** [comment]
#please-close
