### ISSUE TITLE
Page not translated to chinese

### ISSUE THREAD

**Issue by dantezhu** [MicrosoftDocs/architecture-center#3354]
Hi, page not translated to chinese

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a6710f29-66f3-f73c-6a90-6025ce6a5bd3
* Version Independent ID: a6710f29-66f3-f73c-6a90-6025ce6a5bd3
* Content: [Noisy Neighbor antipattern - Azure Architecture Center](https://docs.microsoft.com/zh-cn/azure/architecture/antipatterns/noisy-neighbor/noisy-neighbor)
* Content Source: [docs/antipatterns/noisy-neighbor/noisy-neighbor.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/antipatterns/noisy-neighbor/noisy-neighbor.yml)
* Service: **architecture-center**
* Sub-service: **anti-pattern**
* GitHub Login: @johndowns
* Microsoft Alias: **jodowns**

**Comment by johndowns** [comment]
@EdPrice-MSFT Are you able to confirm whether this page should be localized, please? It looks like other pages in the antipatterns section, and other pages we've authored for multitenancy, have been localized. The noisy neighbor page hasn't been localized into any language I can see.

**Comment by ckittel** [comment]
Interesting, yeah looks like `de-de` for example still shows en-us, while the `zh-cn` seems to now be translated.  @EdPrice-MSFT who is currently our point of contact on the localization team that we could ping?  Maybe it's still @SunnyDeng.

I've opened a ticket internally (CEINTL #578202)

**Comment by ckittel** [comment]
The rest of the translations have been verified to be in the localization queue and are expected to be back around 1-Apr.  Translation isn't done uniformally across all languages, and sometimes it can take a few weeks.  The loc team said there was nothing blocking, so I'll close out this issue as it will resolve itself like other articles also going through translation.
