### ISSUE TITLE
Error regarding blob name

### ISSUE THREAD

**Issue by abhijit-z** [MicrosoftDocs/architecture-center#3357]
[I want to read a csv file located in the blob storage. However, I am getting error that specified blob does not exist. I am confused what should be the blob name. I gave LOCALFILENAME as my csv file name seen in the blob container]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647ed505-3e6e-3db7-63ee-025edf6e63f4
* Version Independent ID: d910ba75-6c86-6172-64be-e45ba2bf5a3d
* Content: [Explore data in Azure Blob storage with pandas - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-science-process/explore-data-blob)
* Content Source: [docs/data-science-process/explore-data-blob.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-science-process/explore-data-blob.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by MayankBargali-MSFT** [comment]
@abhijit-z Thanks for reaching out. Please make sure that your CSV file exists and you are specifying the right value for STORAGEACCOUNTURL, CONTAINERNAME, BLOBNAME. If the blob file doesn't exist then you will get the error "_specified blob does not exist_"

**Comment by MayankBargali-MSFT** [comment]
@abhijit-z Blobname should be the CSV file name on your storage account. In the below image the container name is 'test' and the blob name is test.csv
![image](https://user-images.githubusercontent.com/67255909/160119013-6069b2e0-79cd-464f-bc70-a90a0d55b196.png)

**Comment by MayankBargali-MSFT** [comment]
@abhijit-z Hope the above helps and clears things up. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
