### ISSUE TITLE
Azure Analysis services and PowerBI at the same time?

### ISSUE THREAD

**Issue by dennisfinning** [MicrosoftDocs/architecture-center#3358]
I don't think Microsoft recommends anymore to use Azure Analysis services together with PowerBI. It seems that PowerBI Premium is nowadays a full superset of Azure Analysis services and probably should be used instead of Azure Analysis services for most enterprise-sized projects. At least that's what I have heard from my Microsoft representatives. Can you clarify that direction on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b68d40f-4b98-396b-f4c3-b8650fc4633f
* Version Independent ID: 26b362d7-b46a-fa03-c2aa-48b581b67bf0
* Content: [Advanced analytics - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/advanced-analytics-on-big-data)
* Content Source: [docs/solution-ideas/articles/advanced-analytics-on-big-data.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/advanced-analytics-on-big-data.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by v-fearam** [comment]
@dennisfinning,

Sorry for the delay. 


The document is a solution idea, not an architecture recommendation.

[PowerBI is still a possibility by Azure Analysis services](https://learn.microsoft.com/azure/analysis-services/analysis-services-overview)

Here is some information about [Azure Analysis Service vs Power BI Premium](https://powerbi.microsoft.com/blog/power-bi-premium-and-azure-analysis-services/).


I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
