### ISSUE TITLE
Why Data Lake Service Client can't be set Retry Options ? What is the alternative to do that ?

### ISSUE THREAD

**Issue by siva-sankaran** [MicrosoftDocs/architecture-center#3359]
I cant find any details about retry mechanism for Data Lake Service Client in this documentation.  I want to know  about alternative of doing retry 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Azure service retry guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#general-rest-and-retry-guidelines)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by GiftA-MSFT** [comment]
@siva-sankaran we'll review your feedback and get back to you shortly. Thanks!

**Comment by v-fearam** [comment]
#please-close
