### ISSUE TITLE
Feature comparison of stream analytics

### ISSUE THREAD

**Issue by Mansoormahfoud** [MicrosoftDocs/architecture-center#3360]
[Enter feedback here]
What about other features to look at when choosing a stream analytics technology, such as:
1- The data flow {bounded, unbounded) that the stream analytics can process
2- Stateful vs stateless
3- Does the stream analytics support a "reference" data, what technology in that case (SQL, blob, etc.)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957618b3-8d25-49c4-950c-0c044d68f443
* Version Independent ID: 2ab67665-066b-fb14-9763-a12693b19bec
* Content: [Choose a stream processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing)
* Content Source: [docs/data-guide/technology-choices/stream-processing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/stream-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@Mansoormahfoud Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24538 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
