### ISSUE TITLE
Durable functions/Logic apps/Power Platform

### ISSUE THREAD

**Issue by diberry** [MicrosoftDocs/architecture-center#3361]
This page doesn't seem to represent Azure Durable Functions: can it add the following concepts?

- serverless durable functions provide event orchestration
- serverless durable functions provide required state that can live forever but only runs at cost of consumption
- serverless durable functions provide highly requested orchestration patterns

Logic apps and power platform are missing - while not completely considered compute - they are compute adjacent and should be mentioned somewhere on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93139ee2-ff91-ee5e-a056-8d6b597a81f3
* Version Independent ID: 8b4436e0-094c-9602-2ead-43bb3b2f98f1
* Content: [Choose a compute option for microservices - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/compute-options)
* Content Source: [docs/microservices/design/compute-options.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/design/compute-options.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24539 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
