### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by AkioNuernberger** [MicrosoftDocs/architecture-center#3362]
Link to Azure Media Services Streaming Endpoints leads to a 404 page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video)
* Content Source: [docs/solution-ideas/articles/digital-media-video.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/digital-media-video.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @AkioNuernberger - Link appears to be working fine.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
