### ISSUE TITLE
Remove unneeded minus sign

### ISSUE THREAD

**Issue by banan314** [MicrosoftDocs/architecture-center#3364]
Minus `-` isn't needed in `-Compensation`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e6978f-1eb7-78ca-d785-441aef93cb38
* Version Independent ID: ade4b845-ce0d-f1e3-d1d0-b531318d9857
* Content: [Compensating Transaction pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/compensating-transaction)
* Content Source: [docs/patterns/compensating-transaction.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/compensating-transaction.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@banan314 Thanks for reporting this item! I have updated the doc and it will be published soon. We appreciate the feedback!
