### ISSUE TITLE
Logical flaw in "lift & shift" path

### ISSUE THREAD

**Issue by khaliddermoumi** [MicrosoftDocs/architecture-center#3365]
There is a logical flaw in the "lift & shift" path of the "Choose a candidate service" flowchart.
In the path following "lift & shift", there is a decision "can it be containaerized?". If you follow the "No" path, it leads to a decision "COTS app that can't be containerized?". This is the flaw: it is already decided at this point, that the app can't be containerized. So the decision that is left is basically "COTS app?" instead of "COTS app that can't be containerized?".
This should be fixed IMHO.

Further thoughts of mine:
if the app is a COTS app, the flowchart advises to use a VM. Now if it isn't a COTS app, you should use app services. But there are limitations for app services (such as the supported frameworks, etc.) which would not allow running any non-COTS app on app services.
Anyway, I find it great that there is some advice on which platform you should run COTS apps (here: VM). I already ran COTS apps on app services, which kind of worked, but I was left with the impression that this is rather an unusual usage for app services (as there was little documentation on this usage scenario). So I appreciate some official statement to this scenario very much.

Thanks for the architecture docs!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by GiftA-MSFT** [comment]
@khaliddermoumi we'll review your feedback and get back to you shortly. Thanks.

**Comment by RobBagby** [comment]
@khaliddermoumi - I am going to close this issue, as the flow chart was updated to address your issue. Your point about App Services having limitations, it is true. This is meant to be a high-level decision tree that does not take into account all cases.
