### ISSUE TITLE
Line of business extension - Dataverse Update

### ISSUE THREAD

**Issue by joaozorro** [MicrosoftDocs/architecture-center#3367]
This is a very common and useful pattern and should be released as not just an idea but the recommendation would be to use Azure Synapse Link for Dataverse (https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake) . CDS also needs to be replaced by Dataverse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7536d34-821e-e6ec-1acd-dda567ab7fb5
* Version Independent ID: 4aac2e73-8ac4-fa7d-676a-896e037f3cf3
* Content: [Line of business extension - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/lob)
* Content Source: [docs/solution-ideas/articles/lob.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/lob.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by SwathiDhanwada-MSFT** [comment]
@joaozorro Thanks for your comment. We will review the issue and get back to you shortly.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24167 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
