### ISSUE TITLE
Anthos Service Mesh should be mapped to OSM not Service Fabric Mesh

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#3368]
at [https://docs.microsoft.com/en-us/azure/architecture/gcp-professional/services#containers-and-container-orchestrators](https://docs.microsoft.com/en-us/azure/architecture/gcp-professional/services#containers-and-container-orchestrators) 

Anthos Service Mesh should be mapped to [Open Service Mesh](https://openservicemesh.io) (OSM) NOT Service Fabric Mesh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87304679-95c2-7dac-a2b5-4ce17d6967f3
* Version Independent ID: 8acbb5ee-230c-e23a-a315-0d969258bd8f
* Content: [Google Cloud to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/gcp-professional/services#containers-and-container-orchestrators)
* Content Source: [docs/gcp-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/gcp-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **petuton**[nthos Service Mesh](https://cloud.google.com/service-mesh/docs)	[Service Fabric Mesh](https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-overview)

**Comment by ckittel** [comment]
Agreed.  OSM is the closest match we have at this point, and even that isn't really that great a mapping since OSM is k8s-cluster-scoped specific where as Anthos is more broadly scoped.  Service Fabric Mesh is not the right mapping for sure.
