### ISSUE TITLE
Visio file not up to date with current schema

### ISSUE THREAD

**Issue by rvunen** [MicrosoftDocs/architecture-center#3371]
[Enter feedback here]
Hi 
The current schema is not taken into account in the referred Visio file. in fact the represented schema has nothing to do with what I found in the Visio file. 

Next to it: the schema is very small and it is not possible to make it larger. Normally it is possible to click on a schema and then you get it full screen but here that is not implemented. Schema is hard to read at this size. 

Thanks for taking into account

Roger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84bcf722-abb3-69b8-8073-15ae4a6890de
* Version Independent ID: 7b2010c6-696d-de66-8e56-8ac5d3e54526
* Content: [Basic web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?tabs=cli)
* Content Source: [docs/reference-architectures/app-service-web-app/basic-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/basic-web-app.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by EdPrice-MSFT** [comment]
We logged this one. Thanks!

**Comment by hallihan** [comment]
This should have been addressed with the update in May, please open another feedback item if more changes are needed.
