### ISSUE TITLE
Reccomendation on how to update a specific entity when the request is not idempotent

### ISSUE THREAD

**Issue by djcolonico** [MicrosoftDocs/architecture-center#3374]
[Enter feedback here]
Hi,

I'm looking at the table from [Define API operations in terms of HTTP methods](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#define-api-operations-in-terms-of-http-methods):
![image](https://user-images.githubusercontent.com/1730162/160959797-48c99c37-8c29-44af-aacb-8737f96c5dda.png)

The example suggests using `PUT /customers/1` to update a specific customer.

The documentation also says that PUT requests should be idempotent:
![image](https://user-images.githubusercontent.com/1730162/160960120-d80d29a1-6f7e-4d0e-bdfe-545387550f9c.png)

If I update a specific customer I should use `PUT /customers/1`, but if that customer contains a timestamp (based on the time the request was sent) then the request won't be a valid PUT request because it's not idempotent. 

```
public class Customer
{
    public int Id { get; set; }
    public DateTime LastUpdated { get; set; }
    ...
}
```

How should I define my API operation to update a specific customer when the request is not idempotent? 

In this case, should I be updating a specific customer with `POST /customers/1` instead? 

Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad651d6a-f8d8-2050-e7a7-adbae7326112
* Version Independent ID: 4fddd724-cabd-8623-7692-857088c1dccb
* Content: [Web API design best practices - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#define-api-operations-in-terms-of-http-methods)
* Content Source: [docs/best-practices/api-design.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/api-design.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@djcolonico Thanks for the feedback! I have assigned the issue to the content author to investigate further and update as appropriate.

**Comment by djcolonico** [comment]
Thank you : )

**Comment by v-fearam** [comment]
Hi @djcolonico,
Sorry for the delay,
The update is still  “PUT /customers/1” (the customer representation in the body)  and the idempotent definition is related to the business data. The value populated in LastUpdate is the result of dynamic processing by the origin server (https://www.rfc-editor.org/rfc/rfc9110#section-9.3.4)
 
Regards.

**Comment by v-fearam** [comment]
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close

**Comment by djcolonico** [comment]
Thanks for clarifying @v-fearam. That makes sense.
