### ISSUE TITLE
Time Series Insight being deprecated

### ISSUE THREAD

**Issue by fnicollier** [MicrosoftDocs/architecture-center#3375]
Time Series Insight is mentioned as an alternative for Time Series but it is deprecated with an EOL scheduled for 2025.
Perhaps the documentation should mention this?

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bde15d-d343-b84d-b77f-55b8e3f12638
* Version Independent ID: 9d35a3eb-707b-47f6-68bc-3f22fee4c78c
* Content: [Time series data - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/time-series)
* Content Source: [docs/data-guide/scenarios/time-series.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/scenarios/time-series.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@EdPrice-MSFT Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-fearam** [comment]
Hi @fnicollier,

Sorry for the delay.

I didn't see a specific mention of Time Series Insight as an alternative for Time Series inside the text.
I saw a link to Time Series Insight on “Recommended Content” section, and if you follow the [link](https://learn.microsoft.com/en-us/azure/time-series-insights/time-series-insights-overview?source=recommendations) a note about the deprecation is on the top of that file.

I will close the ticket, but feel free to re-open if additional clarification is needed.
