### ISSUE TITLE
What about Security - Defender for IoT

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3376]
Please add some information about how Defender for IoT fits into this architecture. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93ef5e9-3116-e5fc-c085-1ddfdd431b45
* Version Independent ID: f93ef5e9-3116-e5fc-c085-1ddfdd431b45
* Content: [Architectural approaches for IoT in a multitenant solution - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/multitenant/approaches/iot)
* Content Source: [docs/guide/multitenant/approaches/iot.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/approaches/iot.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @drcrook1
* Microsoft Alias: **dacrook**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by ckittel** [comment]
@asergaz - is this something the IoT ARB could help address?

**Comment by asergaz** [comment]
Working on it internally and forwarding to the right folks. Thanks for the feedback @DeanGross we will update you soon!

**Comment by asergaz** [comment]
#assign:MikeBazMSFT

**Comment by asergaz** [comment]
@MikeBazMSFT tank you for adding a security session to the article. @DeanGross thanks for the feedback, let us know if you have further suggestions!

#please-close.
