### ISSUE TITLE
Good job on the the AWS vs Azure storage page

### ISSUE THREAD

**Issue by th5** [MicrosoftDocs/architecture-center#3380]
Great job. I'm sold.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5500b1c4-f652-9424-ef6c-90bc5db04a90
* Version Independent ID: 83ed8709-d912-ede8-d115-82a49a274ac1
* Content: [Compare AWS and Azure storage services - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/storage)
* Content Source: [docs/aws-professional/storage.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/storage.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@th5 Thanks for your reaching out. Appreciates your feedback and we are glad to hear that you loved the Compare storage on Azure and AWS document. We will go ahead and close this issue. 
cc : @EdPrice-MSFT
