### ISSUE TITLE
Typo: pared --> paired

### ISSUE THREAD

**Issue by akanso** [MicrosoftDocs/architecture-center#3382]
[Enter feedback here]

For more information on pared regions, see [Azure Paired Regions](https://docs.microsoft.com/en-us/azure/best-practices-availability-paired-regions).

pared --> paired
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2806b1-1264-2775-4cce-083303e75b49
* Version Independent ID: 68218fb5-2335-183a-8469-9101a2d8a0ef
* Content: [AKS baseline for multiregion clusters - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-multi-region/aks-multi-cluster)
* Content Source: [docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@akanso Thanks for reporting this item! I have updated the doc and it will be published soon. We appreciate the feedback!
