### ISSUE TITLE
Azure Typical Data Lake Architecture

### ISSUE THREAD

**Issue by rizzl1** [MicrosoftDocs/architecture-center#3383]
Hopefully, Azure Support Team can advise what would the full Azure Data Lake architecture look like in the future. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60cbefa1-b1c1-0edc-cdf7-4cae8a8ca2f5
* Version Independent ID: c6850420-2cc7-d17a-6adb-b4e69399efd7
* Content: [Data lakes - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-lake)
* Content Source: [docs/data-guide/scenarios/data-lake.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/scenarios/data-lake.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@rizzl1Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by EdPrice-MSFT** [comment]
Check out some of our Data Lake architectures: https://docs.microsoft.com/en-us/azure/architecture/browse/?terms=data%20lake

I'm adding related resources to the article.

Internal PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/6037
