### ISSUE TITLE
Bulkhead pattern contains the content of the Cache-aside pattern

### ISSUE THREAD

**Issue by JacobGade** [MicrosoftDocs/architecture-center#3387]
When searching google for Bulkhead pattern this is the first hit, and it doesn't even describe the Bulkhead pattern. It looks like the page has the same contents as the Cache-Aside pattern instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4699b7a-fc21-817e-5a37-aa17b55f47a2
* Version Independent ID: 23efcd5d-11a5-c46f-a73e-5cc638591bcd
* Content: [Bulkhead pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead)
* Content Source: [docs/patterns/bulkhead.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/bulkhead.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by ckittel** [comment]
Thanks @JacobGade for catching this.  We did a content migration and ended up making a mistake on this article during that process.  I've just opened a PR to fix this issue and it should be live in about 24 hours.  I did a quick pass over the other cloud design patterns, and didn't spot any others -- but if you find another, just let us know!
