### ISSUE TITLE
Request to add more content 

### ISSUE THREAD

**Issue by Pachehra** [MicrosoftDocs/architecture-center#3389]
Hi Team,

Please add potential use cases, alternative services, implementation considerations, or pricing guidance.
Thanks!!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14acf440-88ed-186c-a3ab-5309bf7e363c
* Version Independent ID: d32e5eb7-5011-dc40-e978-c6bc9f6363a5
* Content: [DevTest and DevOps for microservice solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-microservice)
* Content Source: [docs/solution-ideas/articles/dev-test-microservice.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/dev-test-microservice.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by Grace-MacJones-MSFT** [comment]
thanks for bringing this to our attention. I have assigned the issue to the content author to evaluate and update as appropriate

**Comment by ckittel** [comment]
FYI @mosabami

**Comment by v-fearam** [comment]
Hi @Pachehra

Sorry for the delay and thanks for the suggestions. 

This current article is a  “Solution idea” which its goals is to keep it simple, here there is more information:

[Microservice reference example implementation with AKS](https://learn.microsoft.com/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices)

[Microservice Architecture](https://learn.microsoft.com/azure/architecture/guide/architecture-styles/microservices)

Microservice and dotnet, [Architecture](https://learn.microsoft.com/dotnet/architecture/microservices/) and [ASP]( 
https://dotnet.microsoft.com/learn/aspnet/microservices-architecture)

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
