### ISSUE TITLE
Adding my LinkedIn Profile

### ISSUE THREAD

**Issue by mrwalters1988** [MicrosoftDocs/architecture-center#3390]
LinkedIn Profile is missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab8ee6db-5605-16ea-ff3e-c710d11e521c
* Version Independent ID: ab8ee6db-5605-16ea-ff3e-c710d11e521c
* Content: [Troubleshoot network problems in AKS clusters - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/operator-guides/aks/troubleshoot-network-aks)
* Content Source: [docs/operator-guides/aks/troubleshoot-network-aks.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/operator-guides/aks/troubleshoot-network-aks.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @mosabami
* Microsoft Alias: **miwalters**

**Comment by mrwalters1988** [comment]
https://github.com/MicrosoftDocs/architecture-center/pull/3391

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by ckittel** [comment]
Closing, addressed in #3391 as @mrwalters1988 indicated.
