### ISSUE TITLE
Bulkhead page has the wrong content

### ISSUE THREAD

**Issue by xenoverse-us** [MicrosoftDocs/architecture-center#3392]
Bulkhead page has the cache-aside content, which is incorrect.

https://github.com/MicrosoftDocs/architecture-center/blob/fd92e626ad1a023f2ff723875c5eddedadb4a6bc/docs/patterns/bulkhead.yml#L20

**Comment by MayankBargali-MSFT** [comment]
@xenoverse-us Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.
