### ISSUE TITLE
Image bad quality

### ISSUE THREAD

**Issue by KamilZet** [MicrosoftDocs/architecture-center#3394]
Images are presented with low resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78da4041-7d2e-b142-6071-19890dd75164
* Version Independent ID: 2ec7cc06-bec2-9c91-143b-f2cbde86b925
* Content: [DataOps for the modern data warehouse - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data-warehouse/dataops-mdw)
* Content Source: [docs/example-scenario/data-warehouse/dataops-mdw.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data-warehouse/dataops-mdw.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by EdPrice-MSFT** [comment]
@KamilZet - do you mean the diagrams? We can add the zoom lens to them. 

Thanks!

**Comment by EdPrice-MSFT** [comment]
Fixing with this internal PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/6036
