### ISSUE TITLE
Solution section is internally inconsistent and mismatches the major use-case

### ISSUE THREAD

**Issue by endintiers** [MicrosoftDocs/architecture-center#3396]
In the "Solution" section of this page the **Diagram/Image** indicates:
1) Request => 202 Accepted (with location header set to status URL)
2) Status Query (in progress) => 200 OK      **_<== this is what is most obviously wrong_**
3) Status Query (completed) => 302 Found (with redirect to completed resource)

Meanwhile the **Text** underneath indicates:
1) Request => 202 Accepted (with location header set to status URL)
2) Status Query (in progress) => 202 Accepted
3) Status Query (completed) => 302 Found (with redirect to completed resource)

The Logic Apps HTTP shape (with default 'Asynchronous Pattern' = true setting) expects:
1) Request => 202 Accepted (with location header set to status URL)
2) Status Query (in progress) => 202 Accepted (with location header set to status URL)
3) Status Query (completed) => 200 OK (no redirect) (Errors if given a 302)

Further down the example code implements:
1) Request => 202 Accepted (with location header set to status URL)
2) Status Query (in progress) => 202 Accepted (with location header set to status URL)
3) Status Query (completed) => 200 OK (no redirect) OR 302 Found (with redirect to completed resource) - depending.

So what exactly IS the official pattern?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply?source=docs)
* Content Source: [docs/patterns/async-request-reply.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/async-request-reply.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @endintiers , thanks for bringing this to our attention. I have assigned the issue to the content author to evaluate and update as appropriate

**Comment by v-fearam** [comment]
#please-close
