### ISSUE TITLE
Article recommends TSI, although it is in a deprecation path

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/architecture-center#3397]
This article points to TSI, although the service has been declared as deprecated and will be out of support in 2025.

I was expecting this article to be updated to the latest guidance (ADX instead of TSI I guess)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad7a9a9b-3d4a-79fb-66fa-dd28361a77db
* Version Independent ID: ad7a9a9b-3d4a-79fb-66fa-dd28361a77db
  * Content: [Extract actionable insights from IoT data - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/industries/manufacturing/extract-insights-iot-data)
* Content Source: [docs/industries/manufacturing/extract-insights-iot-data.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/industries/manufacturing/extract-insights-iot-data.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Ercenk
* Microsoft Alias: **ercenk**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
It appears this was addressed some time ago.  If you are still experiencing issues, please re-open with additional information.
