### ISSUE TITLE
Minor typo in detailed description of diagram

### ISSUE THREAD

**Issue by tchristiani** [MicrosoftDocs/architecture-center#3401]
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-purview#architecture
In the diagram there are 7 steps. In the description there are 8 steps. #7 in the diagram corresponds to the description noted as #8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae05f28-2c5d-8fa1-9e2f-bad478a60379
* Version Independent ID: 953c74fb-cc16-f171-b925-053b90f1be5a
* Content: [Data governance with Profisee and Azure Purview - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-purview)
* Content Source: [docs/reference-architectures/data/profisee-master-data-management-purview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/data/profisee-master-data-management-purview.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **gamal**

**Comment by MayankBargali-MSFT** [comment]
@tchristiani Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by EdPrice-MSFT** [comment]
Got it resolved. See private PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/6032
