### ISSUE TITLE
Azure Purview is now Microsoft Purview

### ISSUE THREAD

**Issue by isdataninja** [MicrosoftDocs/architecture-center#3405]
Azure Purview is now Microsoft Purview, please change accordingly

https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254782d-e773-b542-73e8-f568d3bbee39
* Version Independent ID: 40d81223-f8ea-2eec-616e-5f6ee28c8206
* Content: [Modern analytics architecture with Azure Databricks - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture)
* Content Source: [docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @kacummis
* Microsoft Alias: **kacummis**

**Comment by EdPrice-MSFT** [comment]
Got it. 

Internal PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/6033

Thanks!
