### ISSUE TITLE
Missing installation instructions mentioned at download sites

### ISSUE THREAD

**Issue by Nosferatu-Dk** [MicrosoftDocs/architecture-center#3407]
[Its stated go to this site for install instructions.
Install Instructions
Go to https://docs.microsoft.com/en-us/azure/architecture/icons/ and follow the instructions there.
But it appears there is none :)
https://www.microsoft.com/en-us/download/details.aspx?id=41937]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by JasRobe** [comment]
Thank you for bringing this to our attention.   In the meantime, please accept the terms, and you will have an ability to download the file.
