### ISSUE TITLE
High availability enterprise deployment using App Services Environment needs updating

### ISSUE THREAD

**Issue by xstof** [MicrosoftDocs/architecture-center#3408]
The article "High availability enterprise deployment using App Services Environment" needs updating:
- ASE v3 supports zone-redundant deployments, no need for separate deployments
- Redis supports private endpoints, no need for svc endpoints
- Redis is also zone redundant, no need for separate deployments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4fdc9a3-db55-b6f9-0d36-33bd98be3194
* Version Independent ID: 572bf19f-773c-6362-5c43-c7a0db68c384
* Content: [HA enterprise deployment using ASE - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/ase-high-availability-deployment)
* Content Source: [docs/reference-architectures/enterprise-integration/ase-high-availability-deployment.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/enterprise-integration/ase-high-availability-deployment.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @dsk-2015
* Microsoft Alias: **dkshir**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by xstof** [comment]
Any updates please?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24545 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
