### ISSUE TITLE
Security - Microsoft Defenders - update icons name

### ISSUE THREAD

**Issue by damian-krawczyk** [MicrosoftDocs/architecture-center#3409]
Hi,
Can you update below icons according to new naming convention?

```
Security
├── 02247-icon-service-Azure-Defender.svg --> Microsoft Defender
└── 10241-icon-service-Security-Center.svg --> Microsoft Defender for Cloud
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by RobBagby** [comment]
We have renamed the above. Thanks.
