### ISSUE TITLE
Visio files do not match images

### ISSUE THREAD

**Issue by abeletkeman** [MicrosoftDocs/architecture-center#3410]
Hi.  The Visio files from the download links do not match the diagrams shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9961de25-4a65-ef77-079e-cf0359ec5857
* Version Independent ID: 7b9bb7e7-ef88-a37f-5ca0-5f8a07f0f9d6
* Content: [Run SAP NetWeaver in Windows on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/sap-netweaver)
* Content Source: [docs/reference-architectures/sap/sap-netweaver.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/sap/sap-netweaver.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @bqtrinh
* Microsoft Alias: **bentrin**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by skabou** [comment]
It is unclear where the issue is.  Please re-open with additional details if help is still needed.
