### ISSUE TITLE
Can we please add Terrform code to create the different Architecture infrastructure on Azure

### ISSUE THREAD

**Issue by LeakeyMaina** [MicrosoftDocs/architecture-center#3411]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6e327d-b280-a35c-2588-87a19ac2a4ba
* Version Independent ID: fa9b0713-771f-4792-979a-2f7a4f4445a2
* Content: [Microservices with AKS and Azure DevOps - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks)
* Content Source: [docs/solution-ideas/articles/microservices-with-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/microservices-with-aks.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24543 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
