### ISSUE TITLE
Update Prerequisite information

### ISSUE THREAD

**Issue by AlexCesarini** [MicrosoftDocs/architecture-center#3412]
I believe the Prerequisite information about "Only personal host pools are currently supported." and "Azure Files currently doesn't support Azure AD as a Kerberos realm, only Active Directory" are not accurate anymore, in fact there are other articles that says otherwhise like
https://docs.microsoft.com/en-us/azure/virtual-desktop/deploy-azure-ad-joined-vm#known-limitations
https://techcommunity.microsoft.com/t5/azure-virtual-desktop-blog/announcing-public-preview-of-fslogix-profiles-for-azure-ad/ba-p/3019855
and
https://techcommunity.microsoft.com/t5/itops-talk-blog/deep-dive-how-azure-ad-kerberos-works/ba-p/3070889

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96947883-d52b-1ed8-7db2-915f025060af
* Version Independent ID: 96947883-d52b-1ed8-7db2-915f025060af
* Content: [Azure AD join for Azure Virtual Desktop - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join)
* Content Source: [docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by SatishBoddu-MSFT** [comment]
@AlexCesarini 
I have assigned the issue to the content author for further review.

**Comment by HannahZhuSWE** [comment]
Thanks for reporting this! Closing as 6c3eeccdd403019541da07c5bba3461c2c4ade91 addresses this issue, #please-close.
