### ISSUE TITLE
HDInsight with Solr is this still relevant?

### ISSUE THREAD

**Issue by maxplyassunov** [MicrosoftDocs/architecture-center#3413]
When creating HDInsight cluster it doesn't have Solr option. Should this option be removed from the doc or i'm missing something from my end? Thank you!

<img width="583" alt="Screen Shot 2022-05-04 at 2 23 27 PM" src="https://user-images.githubusercontent.com/35612115/166828383-cc8d1120-c900-4add-8c03-8bda0302eb92.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc525ce2-d021-8e7a-2a88-10b84a2a37e6
* Version Independent ID: 53450f8d-f877-a903-2101-e4265ef6ec75
* Content: [Choose a search data store - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/search-options)
* Content Source: [docs/data-guide/technology-choices/search-options.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/search-options.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@maxplyassunov Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.
