### ISSUE TITLE
Updated Azure icon pack

### ISSUE THREAD

**Issue by frnk01** [MicrosoftDocs/architecture-center#3414]
It's been over a year since the last update to the icon pack. Can you update it will all of the latest services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by SatishBoddu-MSFT** [comment]
@frnk01 
I have assigned the issue to the content author for further review.

**Comment by Zimmergren** [comment]
Thank you for reporting this, @frnk01.
We've made several updates to the Azure Icons recently, and there are hundreds of new icons added. 

The update is available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

Thanks!
#please-close
