### ISSUE TITLE
Pricing Links appear to be wrong

### ISSUE THREAD

**Issue by navix-kziegler** [MicrosoftDocs/architecture-center#3415]
With the Medium and Large pricing links  - the price estimator for 500,000 and 50,000,000 images - puts those values in the S1 tier, but the estimator shows the price per 1,000 transactions, therefore I believe the pricing should dividing both the Medium and Large tier transactions by 1,000 - unless I'm not understanding. 

The small pricing tier does appear to show the correct values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8866b26b-b0e7-494e-48cf-491db44b3aeb
* Version Independent ID: bd1d10ff-39db-a6cb-1a63-805e19159561
* Content: [Image classification on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/ai/intelligent-apps-image-processing)
* Content Source: [docs/example-scenario/ai/intelligent-apps-image-processing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/ai/intelligent-apps-image-processing.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @aschauhan22
* Microsoft Alias: **Ashish.Chauhan**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by navix-kziegler** [comment]
I really appreciate your approach to managing documentation ! Thanks!
________________________________
