### ISSUE TITLE
Non internet facing applications 

### ISSUE THREAD

**Issue by pioardi** [MicrosoftDocs/architecture-center#3418]
Is still true that front door is only for internet facing applications ? I mean now ( based on my understanding, will try this out ) with Azure Front Door Premium is possible to reach app services and ILBs.
Is also possible to restrict Azure Front Door access to internal network ? 
If yes , should Front Door Premium be added to the  decision tree or at least as a note in this documentation ?

Thanks in advance, I can send a PR out to update the diagram ( not sure with which tool ) and the doc 

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Opzioni di bilanciamento del carico - Azure Architecture Center](https://docs.microsoft.com/it-it/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by pioardi** [comment]
A gentle reminder

**Comment by pioardi** [comment]
A gentle reminder

**Comment by RobBagby** [comment]
Hi @pioardi - In reviewing this issue, it appears that Azure Front Door is included in the document and diagram. Please let me know if there is still an issue.

**Comment by pioardi** [comment]
Hi @RobBagby  thanks for your reply. Yes it is included but if you see the diagram but I am talking about this particular case : 

- An http/https application
- Is NOT public facing, and should not be exposed publicly
- Need global load balancing

Which load balancing solution should I use in that case ? Cause looks like Azure Front Door still expose your application publicly. Should I use a private DNS zone ?

**Comment by ferantivero** [comment]
Thanks for your inquiry @pioardi, please let us dissect a bit your comments/questions below. 

> Is NOT public facing, and should not be exposed publicly

While Azure Front Door Premium provides with origin support for direct private endpoint connectivity that will be publicly delivering such content over 100+ points of presence. In other words, that is going to be exposed publicly and based on my understanding this is exact reason why the decision tree is not offering AFD as an alternative for this kind of scenarios. You could configure ip and/or geo restrictions, yet the content is publicly available.

Based on your following confirmation, you had already figured that out. But I have had to comment this to contextualize why I think the decision tree looks in good shape at the time of writing this. 

> Which load balancing solution should I use in that case ? Cause looks like Azure Front Door still expose your application publicly.

It seems you have a very specific requirement in your architecture which is that your app can not be exposed publicly. As a result, this will be allowing private connections to be established and those can be done regionally-only using Private Ips  (not globally). That being said, I think you could consider routing your clients to specific regional load balancers like Azure Application Gateways.

> Should I use a private DNS zone ?

You could consider resolving to those regional load balancers using some technique to add record A(s) in your clients and/or ensuring they query to specific DNS resolvers which might use private DNS zones.

Please let me suggest this issue to be closed, but feel free to ask for reopening this one or create new issues in case you have more questions or consider my answer is not accurate or not fulfilling your needs.

#please-close
