### ISSUE TITLE
Analytical Data Store Security Table Updated?

### ISSUE THREAD

**Issue by tfredjr** [MicrosoftDocs/architecture-center#3421]
The comparison table under security says ADX doesn't support RLS. Maybe time to update with a caveat/footnote?

https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/rowlevelsecuritypolicy?msclkid=86ebd3ffcf9811ecafb4589114cd3501

I didn't review the other tables on the page or entries in the security--just noticed that one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e643be6d-22a2-2b91-c370-edf83d694efe
* Version Independent ID: 770f2e51-9c53-e5ca-1107-9577369b15a6
* Content: [Choose an analytical data store - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analytical-data-stores)
* Content Source: [docs/data-guide/technology-choices/analytical-data-stores.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/analytical-data-stores.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
The content has been updated since this issue was opened.  If there is still an issue please reopen with additional details.
