### ISSUE TITLE
More information on tiering and pricing required.

### ISSUE THREAD

**Issue by MarkMcDonald** [MicrosoftDocs/architecture-center#3422]
What would be really useful is to expand on tiers and provide information or links to pricing of the package as a whole. 

At the moment a small business looking to understand a basic CMS website hosting is affordable, say £50 per month, this would leave them with no idea if this is the case.

It would be good to offer guidance based business size and budget for example. So a small local business of 5 people if going to have very different traffic needs and budgets to a medium or large size company.

Also currently clicking on the deploy from template option results in the error:
'There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/umbraco-cms-webapp-redis-cache/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below.'

I cannot stress how awkward and difficult you make things for your customers, whether direct clients or agencies, when you obfuscate costs. It makes it really difficult to recommend Azure to smaller businesses for whom that is a big concern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a2bfab3-1734-dc0d-74c1-319da054d591
* Version Independent ID: 46b135ba-49ef-7bc2-66cd-066959fca7e7
* Content: [Scalable Umbraco CMS web app - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/medium-umbraco-web-app)
* Content Source: [docs/solution-ideas/articles/medium-umbraco-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/medium-umbraco-web-app.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by v-fearam** [comment]
Hi @MarkMcDonald

Sorry for the delay. 



The document is only a solution idea

I have just checked [Deploy Scenarios](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/medium-umbraco-web-app#deploy-this-scenario) in the document, and both links are working at this point in time. A link was [fixed](https://github.com/MicrosoftDocs/architecture-center/commit/fce05da7872c8af4c9838a3d9eb042a4897e669d) in the past.



About the cost, I will send your suggestion to the proper team. Anyway, you always have the Azure Cost Available using the [Azure Pricing Calculator](https://azure.microsoft.com/en-us/pricing/calculator/). 



I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
