### ISSUE TITLE
Visio link not to picture shown 

### ISSUE THREAD

**Issue by gerrit68** [MicrosoftDocs/architecture-center#3423]
The Visio link is not for the architecture shown

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b605d93-ab34-f8f0-2c64-d38fc5b0ab51
* Version Independent ID: 6e418fbb-e9f8-fa03-ef0e-ab6940ab62ce
* Content: [Create an AD DS resource forest - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-forest)
* Content Source: [docs/reference-architectures/identity/adds-forest.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/identity/adds-forest.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
@gerrit68 The architecture is on page 2 of the Visio file.
