### ISSUE TITLE
outdated documentation. Needs to update with the latest services and solutions.

### ISSUE THREAD

**Issue by salavala** [MicrosoftDocs/architecture-center#3424]
Title Change: This title only helps who wants to learn Azure with AWS background. It should address the customer needs who wants to migrate to Azure. It would be useful to have a page with a title "Migration path and guidelines to migrate to Azure from AWS" to pull more workloads to Azure.

Content Chage:
It really needs to update with the latest services and solutions. Also good to create another page guiding the people with a path to migrate from AWS to Azure. Provide the tools to migrate and rate the migration efforts such as simple, medium and complex. 

HDInsights is an outdated technology, and we have Databricks and Synapse.  The following article on Machine Learning and campaign optimization are 3 years old and needs an update.

https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/predictive-marketing-campaigns-with-machine-learning-and-spark

https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/campaign-optimization-with-azure-hdinsight-spark-clusters

Need to update the following section talking about Data Lake Analytics which we don't support anymore.
https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#analytics-and-visualization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services?source=docs)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **yuanzhiqu**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24160 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
