### ISSUE TITLE
New Title to server Customer needs to migrate to Azure from AWS

### ISSUE THREAD

**Issue by salavala** [MicrosoftDocs/architecture-center#3425]
Title Change: This title only helps who wants to learn Azure with AWS background. We need another page to address the customer needs who wants to migrate to Azure. Most of the content is relevant but better to add tools to migrate and also effort rating to migrate each service would also be helpful. 

It would be useful to have a page with a title "Migration path and guidelines to migrate to Azure from AWS" to pull more workloads to Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **yuanzhiqu**

**Comment by skabou** [comment]
#please-close
