### ISSUE TITLE
Riesgo crediticio y modelo predeterminado PowerBi

### ISSUE THREAD

**Issue by jcsimancas** [MicrosoftDocs/architecture-center#3426]
Hi, I need more information about 

https://docs.microsoft.com/es-es/azure/architecture/solution-ideas/articles/loan-credit-risk-analyzer-and-default-modeling 

Riesgo crediticio y modelo predeterminado

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ed6476ec-ceb9-cb1a-92dd-5dbe50b729a0
* Version Independent ID: 0081a02f-b8d0-0945-51e7-a9a53c47f66d
* Content: [Riesgo crediticio y modelo predeterminado - Azure Solution Ideas](https://docs.microsoft.com/es-es/azure/architecture/solution-ideas/articles/loan-credit-risk-analyzer-and-default-modeling)
* Content Source: [docs/solution-ideas/articles/loan-credit-risk-analyzer-and-default-modeling.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/loan-credit-risk-analyzer-and-default-modeling.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by skabou** [comment]
It is unclear what the issue is.  Please re-open with additional information if assistance is still needed.
