### ISSUE TITLE
Typo when explaining status endpoint

### ISSUE THREAD

**Issue by eusebio-muley** [MicrosoftDocs/architecture-center#3428]
Hi team,

I found a typo in the paragraph explaining the status endpoint:

> ...For every successful call to the status endpoint, it returns HTTP 202. While the work is still pending...

The diagram and further paragraphs state that the status endpoint should return **HTTP 200** and not **HTTP 202**.

> ...The client sends an HTTP GET request to the status endpoint. The work is still pending, so this call returns HTTP 200...

Regards,
Eusebio

PD: Excelent article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/async-request-reply.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by mike-urnun-msft** [comment]
@eusebio-muley Sorry for the long delay in our responses. I've created a PR that fixes the typo and the change should be live after the PR is approved & merged by our content team.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
