### ISSUE TITLE
Remove false claim of open and transparent pricing for CluedIn

### ISSUE THREAD

**Issue by eavonius** [MicrosoftDocs/architecture-center#3430]
Please remove the statement about CluedIn's pricing being open and transparent.

Maybe they changed their website, but they require you to submit a "pricing inquiry". 

It's frustrating to research MDM vendors and they all want you to contact sales to even get a clue.

It doesn't help to offer false hope in this article. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278e83ef-9b90-cb2d-9ff6-0dd8f5ff1b87
* Version Independent ID: 7e63fe30-9080-9207-ad0f-62263379de0c
* Content: [Master data management with Azure and CluedIn - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/cluedin)
* Content Source: [docs/reference-architectures/data/cluedin.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/data/cluedin.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **Oliver.Kaae**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
The content has been updated with the correct link showing pricing details.  If you are still experiencing issues, please re-open with additional information.
