### ISSUE TITLE
Azure Purview to Microsoft Purview

### ISSUE THREAD

**Issue by Kiley724** [MicrosoftDocs/architecture-center#3431]
[This page does not have the new update brand from "Azure Purview to Microsoft Purview"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f10895e-4e1d-1cdd-2d57-32880e0cc45a
* Version Independent ID: 3518d0a5-ffd1-dfa7-6d6b-de2a9ef170d6
* Content: [Analytics end-to-end with Azure Synapse - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?tabs=portal)
* Content Source: [docs/example-scenario/dataplate2e/data-platform-end-to-end.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/dataplate2e/data-platform-end-to-end.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @fabragaMS
* Microsoft Alias: **fabraga**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
It appears this has already been addressed.  Please re-open with additional details if this is not the case.
