### ISSUE TITLE
There is no step mentioned for Virtual network creation before retrieval of VNET information after the resource group creation step. 

### ISSUE THREAD

**Issue by asukumar22** [MicrosoftDocs/architecture-center#3434]
There is no step mentioned for Virtual network creation before retrieval of VNET information after the resource group creation step. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/apis/protect-apis)
* Content Source: [docs/reference-architectures/apis/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/apis/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **fabriciosanchez**

**Comment by DerekHerman-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.
