### ISSUE TITLE
How to use network watcher tools efficiently troubleshooting networking issues

### ISSUE THREAD

**Issue by BGU035** [MicrosoftDocs/architecture-center#3435]
[Enter feedback here]

Would be efficient if we have step by step decision making graph of what network watcher tools to use in sequence to troubleshoot networking issues. for a particular use case lets say starting with connection troubleshooter --> IP flow verify --> NSG Flow verify.  I think it would be very handy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b53451-ced1-9654-b842-3839efcf2eb2
* Version Independent ID: 8034428e-8057-1b1f-b6af-59f0cfe1158f
* Content: [Troubleshoot a hybrid VPN connection - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/troubleshoot-vpn)
* Content Source: [docs/reference-architectures/hybrid-networking/troubleshoot-vpn.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/hybrid-networking/troubleshoot-vpn.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24156 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
