### ISSUE TITLE
Image example is incorrect.

### ISSUE THREAD

**Issue by jlkweb12** [MicrosoftDocs/architecture-center#3438]
The image on the page is wrong:

https://docs.microsoft.com/en-us/azure/architecture/patterns/_images/async-request.png

It shows 302 when it should be 202.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/async-request-reply.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by DerekHerman-MSFT** [comment]
Thanks for reporting this. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by Marusyk** [comment]
I think the image is correct. It should return 302 (Found) and redirect to the resource
