### ISSUE TITLE
Old Product Name - Azure ATP

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3439]
Azure ATP was renamed to Defender for Identity a long time ago. Please update the text on this page as appropriate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7590665-2688-5da1-54ff-029be05c6376
* Version Independent ID: b1dfa5fa-537e-cf03-bb2f-4b9d79420169
* Content: [Azure Active Directory IDaaS in security operations - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aadsec/azure-ad-security)
* Content Source: [docs/example-scenario/aadsec/azure-ad-security.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/aadsec/azure-ad-security.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by v-albemi** [comment]
Addressed in [Azure Active Directory IDaaS in security operations - Azure Architecture Center | Microsoft Learn](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/aadsec/azure-ad-security)
