### ISSUE TITLE
Defender for IoT relationship

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3440]
Please add some information about how Defender for IoT should be considered in this context
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042efcb2-6b9d-6bae-a83b-eea46d017bb4
* Version Independent ID: 0c68c9ab-3df6-cc2b-29af-9d791e5bfe44
* Content: [Azure industrial IoT guidance - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/iiot-guidance/iiot-architecture)
* Content Source: [docs/guide/iiot-guidance/iiot-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/iiot-guidance/iiot-architecture.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @khilscher
* Microsoft Alias: **kehilsch**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by asergaz** [comment]
#please-close this article was removed
