### ISSUE TITLE
Defender for IoT role

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3441]
Please add some information about how Defender for IoT should be included in this type of system
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7a08eee-5230-cccd-c3e5-40029a920276
* Version Independent ID: 7c3c1c2b-d1f1-4b40-8b79-2a828195bbbb
* Content: [Azure industrial IoT data analysis - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/iiot-guidance/iiot-data)
* Content Source: [docs/guide/iiot-guidance/iiot-data.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/iiot-guidance/iiot-data.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @khilscher
* Microsoft Alias: **kehilsch**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by asergaz** [comment]
#please-close this article was removed
