### ISSUE TITLE
Add Defender for IoT and other security products to the architecture diagram

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3442]
Please add security services such as Defender for IoT to the architecture diagram and description. This is needed to help make sure that security is included at the beginning of the project and does not get added on later. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/iot.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @mcosner
* Microsoft Alias: **mcosner**

**Comment by ckittel** [comment]
@asergaz - is this something the IoT ARB could help address?

**Comment by asergaz** [comment]
Working on it internally and forwarding to the right folks. Thanks for the feedback @DeanGross we will update you soon!

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24551 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
