### ISSUE TITLE
Sentinel Basic Logs

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3443]
Please add some information about how the new Basic Logs in Sentinel should be considered in this type of architecture

https://docs.microsoft.com/en-us/azure/sentinel/basic-logs-use-cases

#### Do. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cce1e234-bf77-9f76-ef22-16df2a86b2dc
* Version Independent ID: cce1e234-bf77-9f76-ef22-16df2a86b2dc
* Content: [Long-term security log retention with Azure Data Explorer - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/security/security-log-retention-azure-data-explorer)
* Content Source: [docs/example-scenario/security/security-log-retention-azure-data-explorer.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/security/security-log-retention-azure-data-explorer.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @DeepakAgrawalMS
* Microsoft Alias: **dagrawal**

**Comment by DeepakAgrawalMS** [comment]
***@***.*** ***@***.***>

From: Dean ***@***.***>
Sent: Tuesday, May 24, 2022 6:13 AM
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Deepak Agrawal ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/architecture-center] Sentinel Basic Logs (Issue #3443)


Please add some information about how the new Basic Logs in Sentinel should be considered in this type of architecture

https://docs.microsoft.com/en-us/azure/sentinel/basic-logs-use-cases<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fsentinel%2Fbasic-logs-use-cases&data=05%7C01%7Cdagrawal%40microsoft.com%7C6bce531252f04646966508da3d87202e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637889947813159814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W47fc6dbzh9pb3RzWJMj6JZgR7lrkpQCSA%2FS448p1zY%3D&reserved=0>

Do.
________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: cce1e234-bf77-9f76-ef22-16df2a86b2dc
  *   Version Independent ID: cce1e234-bf77-9f76-ef22-16df2a86b2dc
  *   Content: Long-term security log retention with Azure Data Explorer - Azure Example Scenarios<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fexample-scenario%2Fsecurity%2Fsecurity-log-retention-azure-data-explorer&data=05%7C01%7Cdagrawal%40microsoft.com%7C6bce531252f04646966508da3d87202e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637889947813159814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=isC031kQb291I86rYlO3uxeZPgr5uTlD2XWAcAYAS1w%3D&reserved=0>
  *   Content Source: docs/example-scenario/security/security-log-retention-azure-data-explorer.yml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftdocs%2Farchitecture-center%2Fblob%2Fmain%2Fdocs%2Fexample-scenario%2Fsecurity%2Fsecurity-log-retention-azure-data-explorer.yml&data=05%7C01%7Cdagrawal%40microsoft.com%7C6bce531252f04646966508da3d87202e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637889947813159814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JUauw0ot%2Fcfjm9JzEcT0RPoGdwFnGmU%2FTTnn2JfZ5rU%3D&reserved=0>
  *   Service: architecture-center
  *   Sub-service: example-scenario
  *   GitHub Login: @DeepakAgrawalMS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDeepakAgrawalMS&data=05%7C01%7Cdagrawal%40microsoft.com%7C6bce531252f04646966508da3d87202e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637889947813159814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fCHgfc5tGcgapKoXUlIf7G%2FaJT0OMSN5lki8JEFFR2U%3D&reserved=0>
  *   Microsoft Alias: dagrawal

**Comment by v-fearam** [comment]
Hi @lakshmikanthKGit

Sorry for the delay. 

[The basic log article](https://learn.microsoft.com/en-us/azure/sentinel/basic-logs-use-cases)  highlights log sources to consider and they will provide a lower cost option for ingestion of high-volume into your Log Analytic Workspace. The suggested basic logs and event data  (But you have other possibilities) are useful to correlate and draw conclusions when you investigate an incident or perform threat hunting.

[Microsoft Sentinel](https://learn.microsoft.com/en-us/azure/sentinel/overview) will consume those logs and it will enrich your investigation and detection with AI. [Microsoft Sentinel requires raise the Log Analytic Workspace retention to 90 days](https://learn.microsoft.com/en-us/azure/sentinel/quickstart-onboard#global-prerequisites)

The [current article](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/security/security-log-retention-azure-data-explorer) talk about how to store security logs in Azure Data Explorer on a long-term basis. [Sentinel uses Log Analytics as a data platform for exporting data to Event Hubs and Azure Data Lake](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/security/security-log-retention-azure-data-explorer#dataflow)

It is not worth including details about which Sentinel logs you are collecting for the purpose of the article. Long-term security data retention is critical for full-scale data investigations.


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
