### ISSUE TITLE
How to choose a TI feed

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3444]
Please add some additional guidance about how to determine which TI sources should be used in different scenarios. I'm looking for decision making assistance for different industries, risk profiles, regional locations etc. When should we use more than one, how many is too many, how to avoid duplication, etc are questions that would be good to see addressed in this type of document.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb40dd7-0e77-0f95-8070-95978cd4a90c
* Version Independent ID: 4476618b-beb5-c8c4-ec8b-787db30643fb
* Content: [Cyber threat intelligence in Microsoft Sentinel - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/sentinel-threat-intelligence)
* Content Source: [docs/example-scenario/data/sentinel-threat-intelligence.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/sentinel-threat-intelligence.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24155 to track and investigate this issue.

**Comment by skabou** [comment]
#plase-close
