### ISSUE TITLE
Security products are missing

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3445]
Please add information about how Defender for IoT and Defender for Cosmos DB should be included in this architecture. Security needs to be considered from the beginning and is missing from many of the architectural discussions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25c5d5cf-09ea-ed8f-11d3-b8c8e8a8c2b9
* Version Independent ID: 5050d13f-4976-58a2-2a49-0a1f43b67a9f
* Content: [Azure Cosmos DB in IoT workloads - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/iot-using-cosmos-db)
* Content Source: [docs/solution-ideas/articles/iot-using-cosmos-db.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/iot-using-cosmos-db.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @khilscher
* Microsoft Alias: **khilsch**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by v-fearam** [comment]
Hi @DeanGross 
Sorry for the delay. 
The document is a solution idea, not an architecture recommendation. It can be used as a starting point for building specific applications or solving common business challenges. 
The focus of the article is Cosmos DB capabilities in IoT scenarios. You may find some of the information at: https://learn.microsoft.com/azure/architecture/reference-architectures/iot#security useful.
I will close the ticket.
#please-close
