### ISSUE TITLE
Inconsistent/incomplete messaging and architectural guidance

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3446]
The text states that security is important, but many of the architectural discussions in the WAF do not explicitly show how the security apps/services should be integrated. I think that a thorough and comprehensive review needs to be done of every one of the architectural discussions and diagrams to ensure that the appropriate security tool is mentioned. 

Don't leave it up the application architects to know that they need key vault, defender or sentinel, make the references to all of the security products clear and unambiguous. The Security section should be pointing to the apps/services/resources architectures and those architectures should be pointing back to the dedicate security tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af1a2ef-614d-6594-9c1b-b7a3f8de691e
* Version Independent ID: 3af1a2ef-614d-6594-9c1b-b7a3f8de691e
* Content: [Security architecture design - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/security/security-start-here)
* Content Source: [docs/guide/security/security-start-here.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/security-start-here.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by hallihan** [comment]
Thanks for the feedback. Since this is a broad suggestion that won't be tied to a specific change, I'll go ahead and close this issue. I will pass the feedback along to the team managing this content. #please-close
