### ISSUE TITLE
Can we use Araciality Zone instead of Availability Set? 

### ISSUE THREAD

**Issue by pranabpaul-tech** [MicrosoftDocs/architecture-center#3451]
This article recommends Availability Set and Shared Disk. Can Availability Zone be used in this case? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5588aa-e002-cb1c-1d94-2e84de67cc6d
* Version Independent ID: f38351df-033e-eaab-aa8a-c56b5da534d4
* Content: [SQL Server 2008 R2 failover cluster in Azure - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/sql-failover/sql-failover-2008r2#feedback)
* Content Source: [docs/example-scenario/sql-failover/sql-failover-2008r2.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/sql-failover/sql-failover-2008r2.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by v-fearam** [comment]
Hi @pranabpaul-tech
Sorry for the delay
 
Always, when it is available, the [Availability zone](https://learn.microsoft.com/azure/reliability/availability-zones-overview) is a good option. 
[In the VM context](https://learn.microsoft.com/azure/virtual-machines/availability), by designing your solutions to use replicated VMs in zones, you can protect your apps and data from the loss of a data center. If one zone is compromised, then replicated apps and data are instantly available in another zone.
 
[[Azure virtual machine scale sets](https://learn.microsoft.com/en-us/azure/virtual-machines/flexible-virtual-machine-scale-sets)](https://learn.microsoft.com/azure/virtual-machine-scale-sets/overview) let you create and manage a group of load balanced VMs. The number of VM instances can automatically increase or decrease in response to demand or a defined schedule.
Virtual machines in a scale set can also be deployed into multiple availability zones, a single availability zone, or regionally. 
An [[availability set](https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview)](https://learn.microsoft.com/azure/virtual-machines/availability-set-overview) is a logical grouping of VMs that allows Azure to understand how your application is built to provide for redundancy and availability.

About disks  Premium SSD v1 and Standard SSD (See https://learn.microsoft.com/azure/virtual-machines/disks-shared#premium-ssd and https://learn.microsoft.com/azure/virtual-machines/disks-redundancy#zone-redundant-storage-for-managed-disks)
 
 
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
