### ISSUE TITLE
Potential use cases

### ISSUE THREAD

**Issue by flyinmryan** [MicrosoftDocs/architecture-center#3452]
The first sentence under **Potential user cases** says 

> These other uses cases have similar design patterns:

The second s in uses should be removed.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cc2d26-95f1-a809-8d21-251fa973b084
* Version Independent ID: d452c096-bbea-6b65-36d1-cd56337493ca
* Content: [Real-time asset tracking and management using IoT Central - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-asset-tracking-mgmt-iot-central)
* Content Source: [docs/solution-ideas/articles/real-time-asset-tracking-mgmt-iot-central.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/real-time-asset-tracking-mgmt-iot-central.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @ypriyay
* Microsoft Alias: **priyay**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by MayankBargali-MSFT** [comment]
@flyinmryan Thanks for reporting this item! I have updated the doc and it will be published soon. We appreciate the feedback!
