### ISSUE TITLE
Disable GW Propagation

### ISSUE THREAD

**Issue by ms-ishiyam** [MicrosoftDocs/architecture-center#3455]
"Disable GW Propagation" is not correct. In below document, "Disable GW Propagation of GatewaySubnet" is enable but it is wrong. Could fix the document ?

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha#load-balancer-design

![image](https://user-images.githubusercontent.com/37136042/171075525-f4738f6d-17a0-4c8e-8443-91b6d7f204e0.png)

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-udr-overview#border-gateway-protocol
Route propagation shouldn't be disabled on the GatewaySubnet. The gateway will not function with this setting disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bab6a90-43a3-3d83-d680-26683a3d833d
* Version Independent ID: f8eea094-d297-93e6-06ac-7652d059734f
* Content: [Deploy highly available NVAs - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha#load-balancer-design)
* Content Source: [docs/reference-architectures/dmz/nva-ha.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/dmz/nva-ha.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@ms-ishiyam Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by ckittel** [comment]
This is a good catch.  Whoever made the diagram used a ✔️  for enabled and a ✖️  for not selected.  

From the same image:
![image](https://github.com/MicrosoftDocs/architecture-center/assets/671075/b5cd5fb9-c989-43a8-b417-0aaa443ccff5)

That's not clear at all.  We'll get the image updated.

**Comment by ckittel** [comment]
A change for this should be live in about 24 hours.
