### ISSUE TITLE
HONOURED FOR DOING THIS COURSE.

### ISSUE THREAD

**Issue by NihanthB** [MicrosoftDocs/architecture-center#3456]
[Enter feedback here]

I'm very thankful for doing this course. This certification will help for my career growth and better placements. The course mainly gives me knowledge of Azure and how it functions.
     Thank you for Sponsoring this course Free.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Build solutions with availability zones - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/high-availability/building-solutions-for-high-availability.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@NihanthB Thanks for reaching out and providing feedback on Microsoft docs. Glad to know that it has helped you to understand azure services better and will be helping you in the near future.

I will go ahead and close this thread now.
