### ISSUE TITLE
"Moving data from on-premises to Azure is the backbone of migrating on-premises mainframe and midrange applications. "

### ISSUE THREAD

**Issue by annagross1** [MicrosoftDocs/architecture-center#3459]
["Moving data from on-premises to Azure is the backbone of migrating on-premises mainframe and midrange applications."   This doesn't make any sense to me.  What do you mean by 'backbone of migrating'? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2740bd-cd04-e1fc-b7ed-7c63ca7c38c3
* Version Independent ID: efaf9a1e-67b3-096e-fbaa-a5e6f4a84719
* Content: [Mainframe file replication and sync on Azure - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/mainframe-azure-file-replication)
* Content Source: [docs/solution-ideas/articles/mainframe-azure-file-replication.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/mainframe-azure-file-replication.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @ashish-khandelwal-ms
* Microsoft Alias: **askhande**

**Comment by JamesTran-MSFT** [comment]
@annagross1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MayankBargali-MSFT** [comment]
@ashish-khandelwal-ms Can you provide insights on this.

**Comment by ashish-khandelwal-ms** [comment]
Can I get the full page link so that I can review?

**Comment by hallihan** [comment]
This should be addressed by https://github.com/MicrosoftDocs/architecture-center/commit/f758f0c6b99c09ccecae26aa15f83cd2847f24ac #please-close
