### ISSUE TITLE
SSL is obsolete, do not recommend it

### ISSUE THREAD

**Issue by banan314** [MicrosoftDocs/architecture-center#3461]
Regarding the sentence

> Sensitive data delivered through the application will usually take place using SSL or TLS, and this should be enforced for clients accessing the data store directly.

SSL is obsolete and shouldn't be used anymore, see e.g. https://www.ssl2buy.com/wiki/ssl-vs-tls.

SSL shouldn't be recommended for the above reason. Please consider changing the sentence to _The delivery of sensitive data should be secured using TLS, and ..._.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d94a95d1-5371-4c6a-87d6-00fae7dfb401
* Version Independent ID: d9abac19-dfd7-18d7-2479-42fe5476b569
* Content: [Valet Key pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/valet-key)
* Content Source: [docs/patterns/valet-key.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/valet-key.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by BryanTrach-MSFT** [comment]
@banan314 Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by ckittel** [comment]
For sure, @banan314.  I've just updated this article to remove "SSL or " -- it'll be live in the next 24 hours.  Thank you for your dedication to improving Microsoft documentation!
