### ISSUE TITLE
Need to remove the note about SQL Ledger being preview - it has now shipped

### ISSUE THREAD

**Issue by x509cert** [MicrosoftDocs/architecture-center#3462]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a71d66e9-8380-2cff-a3c2-0a8ba5931d33
* Version Independent ID: a71d66e9-8380-2cff-a3c2-0a8ba5931d33
* Content: [Choose an Azure multiparty computing service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/multiparty-computing-service?source=docs#comparing-options)
* Content Source: [docs/guide/technology-choices/multiparty-computing-service.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/multiparty-computing-service.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by BryanTrach-MSFT** [comment]
@x509cert Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by EdPrice-MSFT** [comment]
Good update. Thanks, @x509cert 

Made the edit in this private PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/6649

ETA is noon, PST, 6/22.

**Comment by skabou** [comment]
It appears this was addressed awhile ago.  Please re-open with additional details if there is still an issue.
