### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Nishantsingh2023** [MicrosoftDocs/architecture-center#3463]
This is good for learning 👍 as a student i like this a lot.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Build solutions with availability zones - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/high-availability/building-solutions-for-high-availability.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by BryanTrach-MSFT** [comment]
@Nishantsingh2023 Thank you for sharing your feedback regarding @EdPrice-MSFT's document. We love to hear when customers find something helpful. If you have any questions in the future, please reach out by engaging us for doc issues on MicrosoftDocs via GitHub or for product questions, please engage with us via Microsoft Q&A.

Have a great week ahead!
