### ISSUE TITLE
Replace Time Series Insights with Azure Data Explorer

### ISSUE THREAD

**Issue by andresu13** [MicrosoftDocs/architecture-center#3465]
Time Series Insights is being retired and we are suggesting ADX as an alternative to our customers now. This diagram should be updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88559925-9b9e-d9b3-ddb6-08306692c17b
* Version Independent ID: a25055cb-7cfe-28a0-1c66-06172c037128
* Content: [Data store decision tree - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)
* Content Source: [docs/guide/technology-choices/data-store-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/data-store-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by JamesTran-MSFT** [comment]
@andresu13 
Thanks for your feedback! We will investigate and update as appropriate.
