### ISSUE TITLE
stream processing - architecture decision - stateful/stateless

### ISSUE THREAD

**Issue by czterocyty** [MicrosoftDocs/architecture-center#3466]
Hi,

I would add also stateful/stateless decision criteria. It would be very useful.

Thanks,
Adam D.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957618b3-8d25-49c4-950c-0c044d68f443
* Version Independent ID: 2ab67665-066b-fb14-9763-a12693b19bec
* Content: [Choose a stream processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing)
* Content Source: [docs/data-guide/technology-choices/stream-processing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/stream-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by JamesTran-MSFT** [comment]
@czterocyty 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24053 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
