### ISSUE TITLE
Contradicting advice on when to use the Choreography pattern

### ISSUE THREAD

**Issue by eyalroth** [MicrosoftDocs/architecture-center#3468]
The page on "Choreography pattern" seems to give contradicting advice on when to or not to use the pattern.

> [When to use this pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography#when-to-use-this-pattern)
> Use the choreography pattern if you expect to update, remove, or **add new services frequently**.

> [Issues and considerations](https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography#issues-and-considerations)
> ...
> The choreography pattern becomes a challenge if **the number of services grow rapidly**.

It may be that the intention in this first part is that overall changes (add/remove/update) are frequent, but that the overall number of services remains relatively unchanged.

If that's the intention, perhaps this wording would be less confusing:
> **When to use this pattern**
> Use the choreography pattern if you expect to update or replace services frequently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f568e9ac-4d16-5076-4863-5e007112b3db
* Version Independent ID: 9180ec47-aaf4-d811-d89d-437dd85fa878
* Content: [Choreography pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography)
* Content Source: [docs/patterns/choreography.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/choreography.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by MayankBargali-MSFT** [comment]
@eyalroth Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-fearam** [comment]
#please-close
