### ISSUE TITLE
Power platform custom business process article is confusing and needs expandsion

### ISSUE THREAD

**Issue by sdzhangtao** [MicrosoftDocs/architecture-center#3469]
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/custom-business-processes

I am not sure your description matches with the graph.
And in step 4, you probably meant stored instead of processed.
4. Azure Functions runs the Graph API calls, which are processed in Azure Storage
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe44a625-07a6-7d65-d16e-a8544c034261
* Version Independent ID: 54310bdb-1397-cd5a-688c-f8e5c042a3fb
* Content: [Custom business processes - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/custom-business-processes)
* Content Source: [docs/solution-ideas/articles/custom-business-processes.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/custom-business-processes.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@sdzhangtao Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by EdPrice-MSFT** [comment]
@sdzhangtao - Great catch.

Edit made on this private PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/6647

ETA is noon PST, 6/22.

**Comment by skabou** [comment]
It appears this was addressed some time ago.  If assistance is still needed, please re-open the issue with additional information.
