### ISSUE TITLE
Compute decision tree improvement

### ISSUE THREAD

**Issue by MarcoWesterink** [MicrosoftDocs/architecture-center#3473]
Hello, 

I think we can have an improvement on the flow chart.
On the left after `Lift and shift` -> `Can it be containerized`, if you choose yes you go immediately to `Need full-fleged orchestration?`.
I think it's still an option to go for App services or Container instances. 

Suggestion. If we reverse the order of Azure App Service and Azure functions the yes from `Can it be containerized?` could go to the decision `Microservice architecture?`
Like the following edited flow diagram:
![image](https://user-images.githubusercontent.com/17967753/172675729-43e42084-0240-4e58-b008-225171bc4a61.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
The diagram has changed since your suggestion was made.  If you are still experiencing issues, please re-open with additional information.
