### ISSUE TITLE
Copywrite question

### ISSUE THREAD

**Issue by zaalion** [MicrosoftDocs/architecture-center#3476]
[Enter feedback here]

Hello,

I need to clarify the icon copywrite please. As authors, and course creators, can we use these icons in Microsoft Azure courses, books, slides, and presentation diagrams?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by JamesTran-MSFT** [comment]
@zaalion 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by EdPrice-MSFT** [comment]
@zaalion - Yes.
