### ISSUE TITLE
Article needs expansion

### ISSUE THREAD

**Issue by ajaytak19** [MicrosoftDocs/architecture-center#3480]
Kindly elaborate the design and describe services used and the way various components interact with each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0086ec3a-1c25-966d-da07-7cf4258e187f
* Version Independent ID: f96d13e8-a5a2-b3c4-8c44-0d9e32a3ddf5
* Content: [Scalable web apps with Azure Redis Cache - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scalable-web-apps)
* Content Source: [docs/solution-ideas/articles/scalable-web-apps.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/scalable-web-apps.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@ajaytak19 Thanks for reaching out. Can you share the document you are referring to?

**Comment by ajaytak19** [comment]
> @ajaytak19 Thanks for reaching out. Can you share the document you are referring to?

https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/scalable-web-apps

**Comment by MayankBargali-MSFT** [comment]
@ajaytak19 Thanks for the confirmation. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by ajaytak19** [comment]
From beginners point of view, I believe some of the architecture examples would really do well with a bit more explanation. Below is the link I was referring to go thru ample architecture designs for educational purpose. 
https://docs.microsoft.com/en-us/azure/architecture/browse/

**Comment by Zimmergren** [comment]
This article has been deprecated. A more favorable article exists here: https://learn.microsoft.com/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app

#please-close
