### ISSUE TITLE
Support of automating the  Continuous delivery​ configuration via the ARM Template.

### ISSUE THREAD

**Issue by gaurav-mittal-helm** [MicrosoftDocs/architecture-center#3482]
Hi,

We are building the VM and installing the software using the ARM template as a Managed Application Solution. Now to support the upgrade of the software's installed we need to enable the Continuous delivery​ configuration option inside the VM. 

We need this to get auto configured when the VM is getting created via the ARM Template.

How can this be supported.

**Edited: Added doc metadata**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d688c8c-61d4-8fea-be5c-a97dd9159b5b
* Version Independent ID: 8a70a875-fd18-2600-6b86-a9fbd7e2960a
* Content: [CI/CD for Azure VMs - Azure Solution Ideas](https://docs.microsoft.com/en-in/azure/architecture/solution-ideas/articles/cicd-for-azure-vms)
* Content Source: [docs/solution-ideas/articles/cicd-for-azure-vms.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/cicd-for-azure-vms.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by AjayKumar-MSFT** [comment]
@gaurav-mittal-helm, Thanks for leveraging Azure docs feedback channel to raise this question. Could you please share the Azure documentation for which this feedback is applicable to?

-This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.

**Comment by gaurav-mittal-helm** [comment]
Hi,

This is for "CI/CD for Azure VMs" - https://docs.microsoft.com/en-in/azure/architecture/solution-ideas/articles/cicd-for-azure-vms

**Comment by AjayKumar-MSFT** [comment]
@gaurav-mittal-helm, Thanks for sharing the doc URL, I have updated the doc metadata info to this issue.

**Comment by AjayKumar-MSFT** [comment]
gaurav-mittal-helm, Your feedback has been shared with the content owner for further review.

**Comment by gaurav-mittal-helm** [comment]
Thanks @AjayKumar-MSFT , i will be available for discussion if there is some clarity on the use case is needed.

**Comment by v-fearam** [comment]
Hi @gaurav-mittal-helm  

Sorry for the delay. 


As @AjayKumar-MSFT said  

-This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.


I don’t know your environment.

I think you could use custom script extensions to install things at deploy time inside a VM. That allows you to do whatever you are able to execute by script on the VM, but at deploy time.

You have [Windows Custom Script Extension](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows) and [Linux Custom Script Extension](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux). 

[Here you have an example](https://github.com/microsoft/azure_arc/blob/main/azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep#L181-L200)


I recommend leveraging the support options available in the Azure portal if you are still facing this issue.


I will close the ticket.

**Comment by v-fearam** [comment]
#please-close
