### ISSUE TITLE
Explanation for Azure Container Apps

### ISSUE THREAD

**Issue by horihiro** [MicrosoftDocs/architecture-center#3483]
The explanation for understanding Azure Container Apps is same as Azure Virtual Machine.
```
Deploy and manage VMs inside an Azure virtual network.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#understand-the-basic-features)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@horihiro Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by horihiro** [comment]
Close because it seems to be already fixed.
