### ISSUE TITLE
Conatiner Apps are not in Preview any more

### ISSUE THREAD

**Issue by ShafeerAli** [MicrosoftDocs/architecture-center#3486]
Container Apps are mentioned as Preview which is not the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6244cf08-ed10-93fd-de01-56044cada33e
* Version Independent ID: 6244cf08-ed10-93fd-de01-56044cada33e
* Content: [Deploy microservices with Azure Container Apps and Dapr - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/serverless/microservices-with-container-apps-dapr?source=docs#feedback)
* Content Source: [docs/example-scenario/serverless/microservices-with-container-apps-dapr.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/serverless/microservices-with-container-apps-dapr.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @alicejgibbons
* Microsoft Alias: **algibbon**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by EdPrice-MSFT** [comment]
Thanks, @ShafeerAli!

Updated via this private PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/6644

ETA is noon PST, 6/22.
