### ISSUE TITLE
Alternative caching options

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/architecture-center#3489]
Are there alternatives to Redis (Azure Cache for Redis)? If yes, what are they and their pros & cons?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be785717-ca5e-f3d6-8e60-4005d9503d08
* Version Independent ID: 3ce414e5-d923-0488-ff11-3aa8bd4c2d1e
* Content: [Caching guidance - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching)
* Content Source: [docs/best-practices/caching.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/caching.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by v-fearam** [comment]
Hi @kmathewmk 
Sorry for the delay. 
Using c# you can configure several distributed cache, https://learn.microsoft.com/aspnet/core/performance/caching/distributed#establish-distributed-caching-services.
It includes options like SQL Database as cache.

Here the recommendations: https://learn.microsoft.com/aspnet/core/performance/caching/distributed#recommendations

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close

**Comment by kmathewmk** [comment]
Thanks for the useful pointer. I think that alternatives should be mentioned or linked in the [Caching guidance - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching) page. Having the information here in the git issue does not expose the info to all users. Also, are there caching alternatives suited for cloud/AKS services running of multiple compute instances? For eg we tried Varnish, Nginx for some of our needs.

**Comment by v-fearam** [comment]
Thanks for the suggestion, I will create a ticket for content development writers.

Even though you are looking for cache options, the best way to cache applications data on Azure is using Redis. It is cloud and as a service. The service manages the [high availability](https://learn.microsoft.com/azure/azure-cache-for-redis/cache-high-availability). Also, you could use SQL Server as a service and use it as cache. 

From AKS, you can use any azure service.


Varnish is a different kind of cache. [Here how to use it on Azure](https://azure.microsoft.com/blog/using-varnish-as-front-end-cache-for-azure-web-apps/)


[As far as you can run it on docker](https://www.varnish-software.com/developers/tutorials/running-varnish-docker/) you can use it inside AKS.  The same case for [nginx](https://learn.microsoft.com/azure/aks/ingress-basic?tabs=azure-cli).
