### ISSUE TITLE
Icons accessibility

### ISSUE THREAD

**Issue by amitmait** [MicrosoftDocs/architecture-center#3492]
We can use a Macro to populate the icons in an excle sheet. For each folder, a new sheet is added and all the icons in that folder are added per cell in the sheet with the label of the icon derived from the icon file name. 
Optionally, we can create an index sheet for all the sheets added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by hallihan** [comment]
@amitmait - Downloading the icons currently requires acceptance of the terms, which makes any automation problematic. If you want to provide more details on the scenario you are attempting to enable, feel free to open another feedback item with more details.
#please-close
