### ISSUE TITLE
Where is the same article for Azure DevOps

### ISSUE THREAD

**Issue by sdaytelefonicatechuk** [MicrosoftDocs/architecture-center#3495]
This page focusses on Github. What about Azure DevOps?
How are the same outcomes achieved using Azure DevOps Repos and extensions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcaeba82-a634-d73a-77fd-a07258be2c17
* Version Independent ID: 4ba78d8a-60c9-9df8-1d2c-0a375a094acb
* Content: [DevSecOps in Azure - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-azure)
* Content Source: [docs/solution-ideas/articles/devsecops-in-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/devsecops-in-azure.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **asegala**

**Comment by EdPrice-MSFT** [comment]
Hi @sdaytelefonicatechuk - Are you looking to secure your solution using Azure DevOps?

It's not the same architecture, but if we can identify the goal, we might have resources for the particular scenario.

Here are a few:
- Secure Azure DevOps with Microsoft Sentinel: https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/automate-sentinel-integration
- CI/CD pipeline with Azure DevOps: https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp
- Leverage Azure Pipelines with Azure DevOps to automate multistage pipelines: https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/automate-azure-pipelines
- Leverage Azure DevOps to migrate a .NET app to Azure: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/net-app-modernization
- Microservices with AKS and Azure DevOps: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/microservices-with-aks
- Similar to above, but leverages Azure Firewall for security on your AKS cluster: https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aks-firewall/aks-firewall

Thanks!

**Comment by sdaytelefonicatechuk** [comment]
My query is specifically related to the DevSecOps solutions architectures here: https://azure.microsoft.com/en-gb/solutions/devsecops/#overview

There is some focus on GitHub and GitHub advanced security with no apparent Azure DevOps equivalents.

What Azure DevOps capabilities can be leveraged as an alternative to GitHub advanced security?

Or is it the case that if security is important, customers should use GitHub repos, GitHub Advanced Security and GitHub Open Source Security?

**Comment by ckittel** [comment]
No changes to this article are planned wrt to Azure DevOps.

#please-close
