### ISSUE TITLE
CI/CD for Containers architecture

### ISSUE THREAD

**Issue by mitchell-land** [MicrosoftDocs/architecture-center#3496]
I'd like to see an architecture and documentation for deploying containers to on-prem Docker repositories.

**Comment by EdPrice-MSFT** [comment]
@mitchell-land - We don't have this specific scenario, unfortunately (as you know).

Were you able to browse through our existing architectures to see if there's a similar solution? https://docs.microsoft.com/en-us/azure/architecture/browse/?terms=docker 

We have a few interesting scenarios that are admittedly not exactly what you're looking for, but they might provide some ideas:
- https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-functions-hybrid
- https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-containers

Thanks!

**Comment by ckittel** [comment]
Azure Architecture Center likely will not be allocating time to this request.  But thank you for the idea.

#please-close
