### ISSUE TITLE
Clarification 10k network rules

### ISSUE THREAD

**Issue by samhodgkinson** [MicrosoftDocs/architecture-center#3498]
I have a /16 Internal network which is 65534 Ip address, this is placed within an IP Group. 

Does this count as a one rule ? 
Does this calculation only apply which IP address /ranges have been used over IP Groups.
Does this calculation work with both the source and destination, within the rule ? For example internal range /16 to internal range. /16  

Reference section 
"Do not exceed 10k network rules, and make sure you use IP Groups. When creating network rules, remember that for each rule, Azure actually multiples Ports x IP Addresses, so if you have one rule with four IP address ranges and five ports, you will be actually consuming 20 network rules. Always try to summarize IP ranges."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215d0a3c-ef5b-7581-dbdf-e418b4891276
* Version Independent ID: 3647b4bf-6a85-8257-5792-39c5eae6785f
* Content: [Azure Well-Architected Framework review of Azure Firewall - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/networking/guide/well-architected-framework-azure-firewall)
* Content Source: [docs/networking/guide/well-architected-framework-azure-firewall.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/networking/guide/well-architected-framework-azure-firewall.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @rohilla-shweta
* Microsoft Alias: **rosanto**

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.
