### ISSUE TITLE
Any guidance on how to implement lease management with Azure Functions and queue/eventhub/servicebus trigger

### ISSUE THREAD

**Issue by sadiqkhoja** [MicrosoftDocs/architecture-center#3499]
Thanks for this interesting document. Can you please share some guidance on how lease management pattern can be implemented using Azure Functions with queue/eventhub/servicebus trigger?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6fc9f60-d9fd-1dca-3641-be133d2dac82
* Version Independent ID: 812bd0d5-508c-37cb-2f26-9ea8c903a632
* Content: [Rate Limiting pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/rate-limiting-pattern)
* Content Source: [docs/patterns/rate-limiting-pattern.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/rate-limiting-pattern.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MughundhanRaveendran-MSFT** [comment]
@sadiqkhoja , Thanks for the feedback. We will review and get back to you accordingly

**Comment by MughundhanRaveendran-MSFT** [comment]
@sadiqkhoja , The lease management is taken care by the azure functions automatically when you use blob trigger and bindings. The storage queue function is based on polling and service bus trigger is based on locks, so its not applicable here. 

Hope this helps. Feel free to reopen if you have queries
