### ISSUE TITLE
Lower and consitent latency as a benefit of ExpressRoute

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftDocs/architecture-center#3501]
"ExpressRoute connections don't go over the public Internet. They offer higher security, reliability, and speeds, with lower and consistent latencies than typical connections over the Internet." is mentioned as an answer to the question "What are the benefits of using ExpressRoute and private network connections?" in the ExpressRoute FAQs 
https://docs.microsoft.com/en-us/azure/expressroute/expressroute-faqs

However, is not mentioned as a benefit in the "Azure ExpressRoute connection - Benefits" section of the following document
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/#benefits-1

Suggestion to add lower and consistent latency compared to typical connections over the Internet as a benefit of using ExpressRoute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c72e16-a607-68cc-4d47-7e6f16b546c1
* Version Independent ID: 897309eb-6e9b-1f5c-714b-b12c91e9091d
* Content: [Connect an on-premises network to Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/)
* Content Source: [docs/reference-architectures/hybrid-networking/index.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/hybrid-networking/index.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by GitaraniSharma-MSFT** [comment]
@rukasakurai , thank you for your feedback. We'll review this and get back to you shortly!

**Comment by EdPrice-MSFT** [comment]
Update was merged in here: https://github.com/MicrosoftDocs/architecture-center/pull/3502
