### ISSUE TITLE
No code provided on "modifications"

### ISSUE THREAD

**Issue by cpdohert** [MicrosoftDocs/architecture-center#3503]
>This scenario uses a modified version of the [Azure API Management DevOps Resource Kit](https://github.com/Azure/azure-api-management-devops-resource-kit)

There's no information provided on what was modified or how to implement the modifications ourselves.  No Azure PIpeline YAML files for examples, scripts or parameters for the extractor to "[change] the repository structure and [rename] the APIs to have friendlier names."

Did you forget a link to a git repo somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Version Independent ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Content: [Automated API deployments using APIOps - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops)
* Content Source: [docs/example-scenario/devops/automated-api-deployments-apiops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/automated-api-deployments-apiops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **risaha**

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-fearam** [comment]
#please-close
