### ISSUE TITLE
Alternatives section is confusing

### ISSUE THREAD

**Issue by davidhamsft** [MicrosoftDocs/architecture-center#3507]
Customers have asked about the following listed under alternatives,
_"However, in regulated industries in particular, some organizations can't use Azure Synapse for various reasons."_
 but there is no link or explanation of which industries cannot use Synapse, not great for a customer to read when we cannot explain it and they are also talking to Snowflake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d394d06c-9042-e12c-ad19-dd9f456e511d
* Version Independent ID: d394d06c-9042-e12c-ad19-dd9f456e511d
* Content: [Data analysis for regulated industries - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/data-analysis-regulated-industries)
* Content Source: [docs/example-scenario/data/data-analysis-regulated-industries.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/data-analysis-regulated-industries.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jbinko
* Microsoft Alias: **jbinko**

**Comment by djdean** [comment]
Fair point. Would this sentence make things more clear? 

However, in regulated industries in particular, some organizations can have longer adoption time for some services (e.g., Azure Synapse) for various reasons. For example, most organizations in a regulated industry require their security teams to 'whitelist' services before they can be used, which requires a deep technical, security-centric review of the service that can often take months to complete. As a result of this, services can be unavailable for use while undergoing this 'whitelisting' process.

**Comment by davidhamsft** [comment]
That or take it out completely, either one is an upgrade.
