### ISSUE TITLE
Blue Green Pattern for AKS

### ISSUE THREAD

**Issue by vimorra** [MicrosoftDocs/architecture-center#3508]
Add a dedicated content to describe the blue - green deployment pattern for AKS.
The content is a GAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5477a1d-f118-9771-e721-dde67ac8e40b
* Version Independent ID: a68fb7b0-c53d-2d79-0316-72babdc6cda2
* Content: [Azure Kubernetes Service (AKS) design - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-start-here)
* Content Source: [docs/reference-architectures/containers/aks-start-here.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-start-here.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @ckittel
* Microsoft Alias: **pnp**

**Comment by AshokPeddakotla-MSFT** [comment]
@vimorra Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by vimorra** [comment]
Hi @AshokPeddakotla-MSFT here where we want to publish the GAP pattern 
![image](https://user-images.githubusercontent.com/48756634/176113153-c0ad3520-f5c9-4f6a-98b2-187e8427bc11.png)
It is a new pattern to describe the blue green deployment for AKS with the related implementation with terraform.

**Comment by AshokPeddakotla-MSFT** [comment]
@vimorra I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by skabou** [comment]
Please see
https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/blue-green-deployment-for-aks/blue-green-deployment-for-aks?source=recommendations

It appears this issue has been resolved.  If you are still experiencing an issue please re-open with additional details.
