### ISSUE TITLE
Sample Price

### ISSUE THREAD

**Issue by veeranac** [MicrosoftDocs/architecture-center#3512]
It would be really great to have sample price calculator enabled for the architecture to accelerate our estimates and approval process for our projects

**Comment by AshokPeddakotla-MSFT** [comment]
@veeranac Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by AshokPeddakotla-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
