### ISSUE TITLE
AD DS Join No Longer Required

### ISSUE THREAD

**Issue by mbrat2005** [MicrosoftDocs/architecture-center#3513]
[Enter feedback here]
This document specifies that AVD session hosts must be AD DS joined, which is no longer true with AAD-join now supported. 

https://github.com/MicrosoftDocs/architecture-center/blob/a55bc8cac84bce0542f97154645bf0c412740fed/docs/example-scenario/wvd/windows-virtual-desktop-content.md?plain=1#L48

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Azure Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop?context=%2Fazure%2Fvirtual-desktop%2Fcontext%2Fcontext)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by AshokPeddakotla-MSFT** [comment]
@mbrat2005 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by hallihan** [comment]
This should be addressed in https://github.com/MicrosoftDocs/architecture-center/commit/ae22bbcf4fdb3fe6b35c6dcae8ee2c940dfb5221 #please-close
