### ISSUE TITLE
Request for Security in the diagram

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3514]
the text mentions Azure AD and Defender for IoT, but these don't show on the diagrams, please add security and monitoring services to the architecture diagram so that we can easily determine how the fit into the big picture
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf328b1f-6bc5-dff2-619f-82b95030c3cf
* Version Independent ID: 4c7bd8b7-5ebb-5b1e-010b-2acd7fdcec0f
* Content: [Azure IoT reference architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot)
* Content Source: [docs/reference-architectures/iot.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/iot.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @mcosner
* Microsoft Alias: **mcosner**

**Comment by SaurabhSharma-MSFT** [comment]
@DeanGross Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by mcosner** [comment]
@DeanGross thanks for filing the issue.  In this case, we have been trying to make these very complicated diagrams more readable, which means (deliberately) omitting some services used in all IoT solutions, such as Azure Active Directory, Keyvault, Defender for IoT, to focus on they key services required for the solution.

**Comment by DeanGross** [comment]
Given that a picture can be worth a thousand words, it would be helpful to have some additional graphics to indicate supporting services or arrow(s) pointing to additional diagrams

**Comment by v-fearam** [comment]
The authors made an intentional decision to omit certain details in order to simplify the diagrams.
