### ISSUE TITLE
download graphic ?

### ISSUE THREAD

**Issue by Fred-Huffman** [MicrosoftDocs/architecture-center#3515]
the Download an [SVG] graphic is a great idea. however my preference is for visio, or vsxds files. I think SVG is some kind of vector graphic, but not sure and no idea if visio will see it as a useful shape or image. Otherwise, good show on the article! I'm in early stage of work on planning, design and construction of web publishing site. 

This is not an "Issue" just a simple minded suggestion. "Submitting" anyway ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73dc00bc-c571-72c0-c3de-8e1a35b9e27a
* Version Independent ID: 424eb559-47a7-bcc5-e567-e428e59c11cb
* Content: [E-commerce website running in secured App Service Environment - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/ecommerce-website-running-in-secured-ase)
* Content Source: [docs/solution-ideas/articles/ecommerce-website-running-in-secured-ase.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/ecommerce-website-running-in-secured-ase.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by RobBagby** [comment]
The visio is now available for download. I am closing this bug.
