### ISSUE TITLE
Incorrect article title referenced

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#3518]
Hi, Azure NetApp Files PM here.

For positioning and branding purposes, please change / update the following:

Under Next Steps, last bullet:
Instead of:
[Running Oracle workloads on Azure using NetApp Files](https://techcommunity.microsoft.com/t5/azure-architecture-blog/run-your-most-demanding-oracle-workloads-in-azure-without/ba-p/3264545)

change to: 
[Run Your Most Demanding Oracle Workloads in Azure without Sacrificing Performance or Scalability](https://techcommunity.microsoft.com/t5/azure-architecture-blog/run-your-most-demanding-oracle-workloads-in-azure-without/ba-p/3264545)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a243df9f-09a1-3a54-c022-eb84e8d41ee5
* Version Independent ID: a243df9f-09a1-3a54-c022-eb84e8d41ee5
* Content: [Host a Murex MX.3 workload on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/finance/murex-mx3-azure)
* Content Source: [docs/example-scenario/finance/murex-mx3-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/finance/murex-mx3-azure.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **gansua**

**Comment by SaurabhSharma-MSFT** [comment]
@gvanteylingen Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by ShawnKupfer** [comment]
This has been fixed.
