### ISSUE TITLE
Guidance regarding global load balancing of Private Endpoints

### ISSUE THREAD

**Issue by JohnDelisle** [MicrosoftDocs/architecture-center#3520]
I'm concerned that Microsoft has released Private Endpoints without considering how customers will distribute load to those endpoints in multi-regional architectures.

Consider a multi-regional App Service based microservice - 

- If the App Svcs use Public Endpoints, it's simple using Azure Traffic Manager (and/or App Gateway, FrontDoor, etc.).
- If the App Svcs use Private Endpoints, I don't see a solution for multi-regional load balancing.

Can you please update your document to include guidance for load balancing a globally-distributed application with only Private Endpoint PaaS offerings and on-VNet origin servers, like IaaS VMs.  I'm not aware of an elegant solution in Azure for this problem.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@JohnDelisle Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24366 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
