### ISSUE TITLE
Broken BeeGFS Link

### ISSUE THREAD

**Issue by Merkelhub** [MicrosoftDocs/architecture-center#3521]
[Enter feedback here]
Unfortunately the BeeGFS is broken / false, it opening GlusterFS content 

All the best
Marco

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7cf67b7-8d94-d7a2-97ef-1387e252109c
* Version Independent ID: 0d3a72a7-6600-5682-6be1-6c333192bbd6
* Content: [High-performance computing (HPC) on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/topics/high-performance-computing)
* Content Source: [docs/topics/high-performance-computing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/topics/high-performance-computing.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @SMBrook
* Microsoft Alias: **sibrook**

**Comment by SaurabhSharma-MSFT** [comment]
@Merkelhub I am able to navigate to [BeeGFS](https://azure.microsoft.com/resources/implement-glusterfs-on-azure).  
![image](https://user-images.githubusercontent.com/38112130/178082545-94eb07c5-ea1b-4df6-b359-54437fe83dfe.png)

**Comment by SaurabhSharma-MSFT** [comment]
@Merkelhub We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by EdPrice-MSFT** [comment]
We have this whitepaper: https://azure.microsoft.com/en-us/resources/deploy-agisoft-photoscan-on-azure-with-azere-vfxt-for-azure-or-beegfs/

But I think the typo was on "BeeGFS", not the link. I'll change that. Thanks!

**Comment by EdPrice-MSFT** [comment]
PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/7627
