### ISSUE TITLE
Example in Reactjs

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/architecture-center#3522]
Hello team,

I want to create eCommerce application in Reactjs. I see the example for https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/ecommerce-scenario#deploy-this-scenario is in .NET. 

Can you provide another version of the sample application? In Reactjs. 

_Deploy this scenario
To deploy this scenario, you can follow this [step-by-step tutorial](https://github.com/Azure/fta-customerfacingapps/tree/master/ecommerce/articles) demonstrating how to manually deploy each component. This tutorial also provides a .NET sample application that runs a simple ticket purchasing application. Additionally, there is a Resource Manager template to automate the deployment of most of the Azure resources._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04d3a8e6-d525-cd5e-46b1-d28384fab8bc
* Version Independent ID: 442da3db-2ec4-9f0e-b485-459717c081d2
* Content: [E-commerce front end - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/ecommerce-scenario#deploy-this-scenario)
* Content Source: [docs/example-scenario/apps/ecommerce-scenario.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/ecommerce-scenario.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @chrismason
* Microsoft Alias: **chmason**

**Comment by VikasPullagura-MSFT** [comment]
@DavidPaf 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@chrismason 
Can you please check and add your comments on this doc update request as applicable.

**Comment by DavidPaf** [comment]
Thank you.
Hope it is in progress.

**Comment by ckittel** [comment]
No, sorry, we will not be providing the front end in another language.  The focus of this article is the component architecture, not the language in which the front end is written.  Hope you were able to learn reactjs and design your e-commerce workload successfully.

#please-close
