### ISSUE TITLE
Include table storage in the decision tree

### ISSUE THREAD

**Issue by skunani** [MicrosoftDocs/architecture-center#3524]
[Enter feedback here]
It will be helpful to include Azure table storage in the decision tree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88559925-9b9e-d9b3-ddb6-08306692c17b
* Version Independent ID: a25055cb-7cfe-28a0-1c66-06172c037128
* Content: [Data store decision tree - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)
* Content Source: [docs/guide/technology-choices/data-store-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/data-store-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@skunani Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback. It appears your suggestion has been addressed.  If you require further assistance, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
