### ISSUE TITLE
Azure Front Door as an example of a technology that can be considered an API Gateway

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftDocs/architecture-center#3525]
The page lists Azure Application Gateway as an example of a technology that can be considered an API Gateway in the "Choosing a gateway technology" section:
https://docs.microsoft.com/azure/architecture/microservices/design/gateway#choosing-a-gateway-technology

However, it does not list Azure Front Door here, even though it offer feature that the pages describes as characteristics of an API Gateway.

Suggestion is to add Azure Front Door as an example of a technology that can be considered an API Gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2a72bb-af6a-b0c3-ab10-7156e849def2
* Version Independent ID: a5ec9864-dce3-18e5-c774-15fb260b6cce
* Content: [API gateways - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/gateway)
* Content Source: [docs/microservices/design/gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/design/gateway.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@rukasakurai Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-fearam** [comment]
#please-close
