### ISSUE TITLE
Supply Chain - Carbon Footprint - A Suggestion

### ISSUE THREAD

**Issue by venuvedam** [MicrosoftDocs/architecture-center#3526]
Love this article on AAC about QBS and Azure coming together to transform the supply chain use case. Very timely and is a great addition to our blockchain knowledge base. This is a suggestion to extend this point of view further to meet the sustainability goals of an MFG/Retail/Process enterprise. Of late, we have been witnessing an increased focus on minimizing the carbon footprint of these massive, global supply chains so that the companies ESG dashboards look acceptable. 

A blockchain based transformation of supply chain already brings in a lot of efficiencies by cutting down on the trust enforcing mechanisms and thereby increasing the supply chain velocity and thus reducing the carbon footprint. However, the overall carbon footprint of a supply chain is still a mystery for the organizations and if a CSO (Chief Sustainabilty Officer) wants to know where in the supply chain is most carbon pumped into the environment or excess water used or landfills contributed, there is not an easy way today that guarantees data integrity, and data dissection capability. 

A follow up article or perhaps an additional section on this same article can provide more clarity on how one can integrate an ESG reporting mechanism with this article. For instance, how can this architecture be extended to feed data into MC4S - Sustainability Manager? 

The north star would be one where the CSO can

1. View the supply chain and its carbon footprint, in near-real time, on their dashboard. 
2. Dissect a particular leg of the chain to see more granular details of the carbon usage. 
3. Take follow up actions (Some of which can be automatically suggested to the CSO)

From an architecture point of view, a lot of this will be handled out of the box by MC4S. We just need to make sure that the supply chain carbon data is fed to the underlying Dataverse automatically. This can happen via an API that reads the data off QBS directly or, more likely, through the secure off-chain store - which can be SQL Database ledger so that there is no break in the data integrity as the ledger data traverses non-ledger stores before hitting the dashboards. 

Now, the challenge is the acquisition of sustainabiltiy data itself. For instance, we know that the product is in transit between China and the UK via Suez Canal. What could be the carbon footprint of that journey? This requires further thought but thankfully from an architecture perspective, it is just another dataset that needs to be merged with supply chain data from QBS before it is fed to MC4S. Hence, another architectural pattern is to put a Synapse instance between the ledger and MC4S. All the other ecosystem datasets can also be imported into Synapse and then the merged data can be fed to MC4S via a custom connector. 

Of course, I know this is too abstract or high level at this point and we need to invest a lot of effort to bring this a proper shape before it can be put on AAC. However, happy to work with you and your team on fleshing this out in case you feel this suggestion can be taken forward. 

Looking forward to reading more and more de-centralised strategies on AAC.

Regards
Venu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db15a586-a04b-e78e-276a-949d7a858958
* Version Independent ID: db15a586-a04b-e78e-276a-949d7a858958
* Content: [Supply chain management - Track and trace with Quorum Blockchain Service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/blockchain/quorum-blockchain-service)
* Content Source: [docs/guide/blockchain/quorum-blockchain-service.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/blockchain/quorum-blockchain-service.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @AdhikariSamrat
* Microsoft Alias: **sadhikari**

**Comment by venuvedam** [comment]
Sorry, this is regarding the article on AAC: https://docs.microsoft.com/en-us/azure/architecture/guide/blockchain/quorum-blockchain-service

**Comment by MonikaReddy-MSFT** [comment]
@venuvedam - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24061 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
