### ISSUE TITLE
Oracle migration to Azure using SharePlex or Data Guard or Active Data Guard

### ISSUE THREAD

**Issue by PRodas1** [MicrosoftDocs/architecture-center#3527]
In this section discussion: https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/reference-architecture-for-oracle-database-migration-to-azure

The terminology says Data Guard on the ARCH Slides. However, in the first sentence on the Link Microsoft uses the verbiage Active Data Guard. ADG is yet another product from Oracle. Active Data Guard, is different from Data Guard. Different from Golden Gate. MSFT should revise that sentence.  Data Guard is free if you own Oracle Enterprise Edition. If you own Oracle Standard Edition you have other choices as well.  www.Quest.com/shareplex is an option and flexible proven solution to eliminate risk and downtime associated to migration or replicating data from Oracle Enterprise Edition or Standard Edition to Azure on Oracle, SQL, PostgreSQL etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9837f109-e89c-621e-63fd-a9acd8a090dc
* Version Independent ID: ef17dd8c-6dae-bc06-5b19-8eea3bb53e63
* Content: [Oracle database migration to Azure - Azure Architecture](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/reference-architecture-for-oracle-database-migration-to-azure)
* Content Source: [docs/solution-ideas/articles/reference-architecture-for-oracle-database-migration-to-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/reference-architecture-for-oracle-database-migration-to-azure.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MayankBargali-MSFT** [comment]
@PRodas1 Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24329 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
