### ISSUE TITLE
SQL Server Availability Group Wording Fixes

### ISSUE THREAD

**Issue by kenjmartinii** [MicrosoftDocs/architecture-center#3535]
Within this [Workflow](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/multi-tier-app-disaster-recovery-experiment#workflow) section, the following bolded words and phrases are kinda/sorta not accurate and may confuse readers:

> The database tier can be configured to use Always On availability groups. With this SQL Server configuration, one primary **database** within **a cluster** is configured with up to eight secondary **databases**. If an issue occurs with the primary **database**, the **cluster fails** over to one of the secondary **databases**, allowing the application to remain available. For more information, see [Overview of Always On availability groups for SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server).

I would suggest the following edits to reflect the concept of primary and secondary 'replicas' within an Availability Group, removing the reference to a cluster failing over given Availability Groups are not true Failover Cluster Deployments of SQL Server, and minor other edits to ensure clarity. For reference, the official listing of Availability Group terms and conditions can be found [here](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-availability-groups-sql-server?view=sql-server-ver16#TermsAndDefinitions)

Proposed edits are _**bold and italic**_:

> The database tier can be configured to use Always On availability groups. With this SQL Server configuration, one primary read/write _**replica**_ within _**an availability group**_ is configured with up to eight secondary _**read-only replicas**_. If an issue occurs with the primary _**replica**_, the _**availability group fails over primary read/write activity**_ to one of the secondary _**replicas**_, allowing the application to remain available. For more information, see [Overview of Always On availability groups for SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6bcac8-81a4-74ef-8287-6a185c564e84
* Version Independent ID: 5e6bcac8-81a4-74ef-8287-6a185c564e84
* Content: [Multi-tier web application built for HA/DR - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/multi-tier-app-disaster-recovery-experiment)
* Content Source: [docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery-experiment.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery-experiment.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @sujayt
* Microsoft Alias: **sutalasi**

**Comment by MarileeTurscak-MSFT** [comment]
@kenjmartinii 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by BryanLa** [comment]
@kenjmartinii - our apologies for the long delay, and thanks very much for your contribution.

Your suggestions have been incorporated. The article will republish by around 10am Pacific on 11/21.

#please-close
