### ISSUE TITLE
Page content and title has (almost) nothing to do with each other

### ISSUE THREAD

**Issue by hagnas** [MicrosoftDocs/architecture-center#3537]
This page titled "Custom data sovereignty and data gravity requirements" does not contain anything about said title. The architecture drawing and description sounds like a placeholder for something else. 

Seems to me like the page should be added to have something useful or removed until content can be created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8eba9-9491-d76d-9690-151add45b30b
* Version Independent ID: b64f53cb-1421-050b-ec5c-b42ef49e7c86
* Content: [Custom data sovereignty and data gravity requirements - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/data-sovereignty-and-gravity)
* Content Source: [docs/solution-ideas/articles/data-sovereignty-and-gravity.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/data-sovereignty-and-gravity.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by MayankBargali-MSFT** [comment]
@hagnas Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-fearam** [comment]
#please-close
