### ISSUE TITLE
If you translate to hungarian use a good translator!

### ISSUE THREAD

**Issue by robozb** [MicrosoftDocs/architecture-center#3539]
[Ide írja be a visszajelzését]

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 57f4d213-3eb1-5b4c-aa67-116e8fa36f7d
* Version Independent ID: 18199b5a-8f57-6574-c795-7540199ae49a
* Content: [Mikroszolgáltatások CI/CD-folyamata a Kubernetesen - Azure Architecture Center](https://docs.microsoft.com/hu-hu/azure/architecture/microservices/ci-cd-kubernetes)
* Content Source: [docs/microservices/ci-cd-kubernetes.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/ci-cd-kubernetes.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **edprice**

**Comment by MarileeTurscak-MSFT** [comment]
@robozb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
@robozb This is a machine translated article.  It's unclear where issues exist with the content.  If there is still an issue can you re-open and provide more context/examples?  Thanks!
