### ISSUE TITLE
VPN speed is listed as 10Gbps, but should read 1Gbps?

### ISSUE THREAD

**Issue by measin** [MicrosoftDocs/architecture-center#3542]
In the details for VPN speed, the page lists the speed as up to 10Gbps, but shouldn't it read 1Gbps? 

Quote:
"VPN connection
A [VPN gateway](https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways) is a type of virtual network gateway that sends encrypted traffic between an Azure virtual network and an on-premises location. The encrypted traffic goes over the public Internet.

This architecture is suitable for hybrid applications where the traffic between on-premises hardware and the cloud is likely to be light, or you are willing to trade slightly extended latency for the flexibility and processing power of the cloud.

Benefits
Simple to configure.
Much higher bandwidth available; up to 10 Gbps depending on the VPN Gateway SKU."

Best regards
Alf

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 59c72e16-a607-68cc-4d47-7e6f16b546c1
* Version Independent ID: 897309eb-6e9b-1f5c-714b-b12c91e9091d
* Content: [Connect an on-premises network to Azure - Azure Architecture Center](https://docs.microsoft.com/nb-no/azure/architecture/reference-architectures/hybrid-networking/)
* Content Source: [docs/reference-architectures/hybrid-networking/index.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/hybrid-networking/index.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@measin Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by BryanLa** [comment]
@measin - our apologies for the delay on this, and thank you for your contribution.

Looking at the VPN Gateway doc referred to in this reference architecture, the [Gateway SKUs by tunnel, connection, and throughput table](https://learn.microsoft.com/azure/vpn-gateway/vpn-gateway-about-vpngateways#benchmark) indicates that the aggregate throughput is 10Gbps, specifically for the 'VpnGw5AZ' SKU. I've also noted this in the article you cited.

#please-close
