### ISSUE TITLE
"Migrate an Azure Cloud Services application to Azure Service Fabric" appears to contradict itself

### ISSUE THREAD

**Issue by andrewrondeau-optirtc** [MicrosoftDocs/architecture-center#3544]
"Migrate an Azure Cloud Services application to Azure Service Fabric" has some rather confusing statements. These statements appear to contract each other:

Under https://docs.microsoft.com/en-us/azure/architecture/service-fabric/migrate-from-cloud-services#deploying-the-application

> As mentioned, it's recommended to place the Kestrel web server behind a reverse proxy for security reasons. ... It acts as a reverse-proxy service, terminating the client connection and forwarding requests to back-end endpoints.

Then, a few paragraphs later, under https://docs.microsoft.com/en-us/azure/architecture/service-fabric/migrate-from-cloud-services#layer-7-routing

> One approach that we don't recommend is allowing external clients to send requests through the Service Fabric [reverse proxy](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy).

The above statements are confusing, and appear to contradict each other. **Do these sections refer to different reverse proxies?** What's the difference between the two?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19b08a2e-bd6c-5908-b03f-c1c711aee746
* Version Independent ID: f79fa09d-91c5-abb7-0758-16ca6a9d4f34
* Content: [Migrate a Cloud Services app to Service Fabric - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/service-fabric/migrate-from-cloud-services)
* Content Source: [docs/service-fabric/migrate-from-cloud-services.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/service-fabric/migrate-from-cloud-services.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by MarileeTurscak-MSFT** [comment]
@andrewrondeau-optirtc 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
The Azure Architecture Center article has been removed and redirected to the same article in product docs.  As such this is no longer in contradiction.

#please-close
