### ISSUE TITLE
Update Service Bus retry settings

### ISSUE THREAD

**Issue by bastyuchenko** [MicrosoftDocs/architecture-center#3550]
Currently, Service Bus retry best practice contains an example for packages
Microsoft.Azure.ServiceBus
WindowsAzure.ServiceBus 

Please change it to a new recommended package Azure.Messaging.ServiceBus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Azure service retry guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**Package	Description	Namespace
[Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus)	Azure Service Bus client library for .NET Standard.	Microsoft.ServiceBus
[WindowsAzure.ServiceBus](https://www.nuget.org/packages/WindowsAzure.ServiceBus)	T

**Comment by Givary** [comment]
@bastyuchenko Thank you for your feedback. We will investigate and update the thread further.
