### ISSUE TITLE
Linked to old Microsoft REST API Guidelines

### ISSUE THREAD

**Issue by scgbear** [MicrosoftDocs/architecture-center#3551]
The link on this page to the Microsoft REST API Guidelines takes you to the master branch of the repo, which hasn't been updated in 5 years.

Should look into updating the link to point to the vNext branch of the repo: https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad651d6a-f8d8-2050-e7a7-adbae7326112
* Version Independent ID: 4fddd724-cabd-8623-7692-857088c1dccb
* Content: [Web API design best practices - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design)
* Content Source: [docs/best-practices/api-design.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/api-design.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate
