### ISSUE TITLE
[VM extensions] and [Azure Automation] are not same funtions about [AWS Cloud Formation].

### ISSUE THREAD

**Issue by sysbtera** [MicrosoftDocs/architecture-center#3553]
[VM extensions] and [Azure Automation] are not same funtions about [AWS Cloud Formation].
[AWS Cloud Formation] is recovery tool for AWS setting.
Therefore,[VM extensions] and [Azure Automation] mistook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#devops-and-application-monitoring)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **yuanzhiqu**

**Comment by MayankBargali-MSFT** [comment]
@sysbtera Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by sysbtera** [comment]
thx for reply.
already closed.
