### ISSUE TITLE
Incorrect datetime parsing

### ISSUE THREAD

**Issue by mcollier** [MicrosoftDocs/architecture-center#3554]
I think the KQL queries showing parsing of the "Trigger Details" message with a datetime value may be incorrect.  The format of the message may have changed.

The example below shows the format I'm observing:
`Trigger Details: PartionId: 59, Offset: 124580099912-124580204288, EnqueueTimeUtc: 2022-08-02T11:10:19.4440000+00:00-2022-08-02T11:10:24.5380000+00:00, SequenceNumber: 122953-122972, Count: 20`

Notice the difference in the EnqueueTimeUtc field (changed from using "Z" to "+00:00".

The queries may need to be modified to parse the datetime values correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7372216a-3f05-c33d-5abc-568a5e9202b2
* Version Independent ID: 18a9cda7-ef12-2b9f-55b8-69784e988d47
* Content: [Monitor Azure Functions and Event Hubs - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/serverless/event-hubs-functions/observability)
* Content Source: [docs/serverless/event-hubs-functions/observability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/serverless/event-hubs-functions/observability.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @dbarkol
* Microsoft Alias: **dabarkol**

**Comment by MayankBargali-MSFT** [comment]
@mcollier Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-fearam** [comment]
#please-close
