### ISSUE TITLE
Across forest authentication to domain joined storage Accounts in your article "Multiple forests deployment

### ISSUE THREAD

**Issue by colingiles** [MicrosoftDocs/architecture-center#3563]
Hi Tom

I have been reading your article "https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/multi-forest-azure-managed" this morning which is very interesting, can you explain more detail on the storage account setup? I believe you can only join it to one forest, how does the authentication flow for CompanyA.com and CompanyB.com work for users access?

Thanks,

Colin Giles  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f491d2a8-2895-9075-29f2-fde88888b6b6
* Version Independent ID: d59e120b-9968-9212-571b-99345aa8fa83
* Content: [Multiple forests with AD DS, Azure AD, and Azure AD DS - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/multi-forest-azure-managed)
* Content Source: [docs/example-scenario/wvd/multi-forest-azure-managed.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/multi-forest-azure-managed.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @nehalineogi
* Microsoft Alias: **tmaher**

**Comment by MayankBargali-MSFT** [comment]
@colingiles Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by hallihan** [comment]
@tom-maher or @nehalineogi - Do you have anything to add regarding the question above?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24735 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
