### ISSUE TITLE
Updated article titles - visible codes

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3564]
The updated article tiles display some codes from GitHub, this is not helpful and does not look good. It would be nice if those could be hidden. 

Also, I notice that many of the pages are not showing the date they were updated. Most of the other Docs pages do show that information, which is very helpful. Please fix the publishing process so that the Update Date for the well architected framework pages is visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd7bc22-da10-1d3b-ba22-7d5e374be441
* Version Independent ID: 9f466c91-adc7-0489-5b1e-17633d27c98c
* Content: [What's New in Azure Architecture Center - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/changelog)
* Content Source: [docs/changelog.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/changelog.md)
* Service: **architecture-center**
* GitHub Login: @alexhart11
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by hallihan** [comment]
The Well Architected Framework articles should all be showing dates now.  If you see any that aren't, please provide specific links.

The codes from GitHub that are showing in the change list are actually the GitHub commit hash where a change was introduced, and they can be useful if you want to know specifically what has changed in a given article.

#please-close
