### ISSUE TITLE
Suggestion: Apache Flink

### ISSUE THREAD

**Issue by ivanthewebber** [MicrosoftDocs/architecture-center#3565]
I think it would be great if there was a tutorial or documentation on how to deploy Apache Flink over Kubernetes on Microsoft Azure. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633a5861-7d2d-34af-90a4-55fde85061a2
* Version Independent ID: 633a5861-7d2d-34af-90a4-55fde85061a2
* Content: [Apache scenarios on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/apache-scenarios)
* Content Source: [docs/guide/apache-scenarios.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/apache-scenarios.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by Sandeg-MSFT** [comment]
@ivanthewebber 

Thank you for bringing this to our notice. We will investigate this further and will get back to you.

**Comment by ivanthewebber** [comment]
I recently found this: https://github.com/microsoft/flink-on-azure/tree/main/flink-on-native-azure-kubernetes

It helped me get started with what I was trying to do

**Comment by ckittel** [comment]
Glad you found that content!

@nickwalkmsft / @dominicallen for content signal consideration.  Maybe consider reaching out to the authors of that repo to see if they if the story could/should be added to AAC?

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24049 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close

**Comment by ivanthewebber** [comment]
@skabou, I actually learned a lot doing it myself over the last two years and do work at Microsoft, so please feel free to reach out to me if you want input or inspiration for the tutorial.
