### ISSUE TITLE
Architecture Diagram - Interface Publishing

### ISSUE THREAD

**Issue by medran3** [MicrosoftDocs/architecture-center#3566]
Hi, 
In your diagram you show that interfaces are published on the Dev Portal from external Web Services and from LogicApps. 
I believe that LogicApps interfaces would be published from the API Gateway as this is where the interface for the Developer to consume sits as well as the required information e.g. Security, SLAs, etc.

Regards,
Marc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287bb9a4-a404-f75b-9bf5-ebd445245938
* Version Independent ID: 31d58fc1-cc2a-5458-ab0b-82b42d7697b2
* Content: [Basic enterprise integration on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/basic-enterprise-integration#feedback)
* Content Source: [docs/reference-architectures/enterprise-integration/basic-enterprise-integration.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/enterprise-integration/basic-enterprise-integration.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MattFarm
* Microsoft Alias: **mattfarm**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by v-fearam** [comment]
Hi @medran3
Sorry for the delay. 
I think it is a misunderstanding. 
[Developer Portal](https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts#developer-portal) gives your developers access to documentation and code samples for calling the APIs. You can also test APIs in the developer portal.The open-source [developer portal](https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts#developer-portal) is an automatically generated, fully customizable website with the documentation of your APIs.


The interfaces are published there, but for documentation proposals.

![image](https://user-images.githubusercontent.com/62260324/236798384-ad48f47b-4dbc-4f79-9066-1efae12c450b.png)
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
