### ISSUE TITLE
Unusable icons

### ISSUE THREAD

**Issue by dj51ngh** [MicrosoftDocs/architecture-center#3574]
[Enter feedback here]
azure icons are pretty unusable : why not make them available in easier to use formats such as ppt ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by Grace-MacJones-MSFT** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by lukemurraynz** [comment]
Just a note for anyone who comes across this Issue.

There is an external third-party extension for exporting the images directly from the Azure Portal: https://chrome.google.com/webstore/detail/amazing-icon-downloader/kllljifcjfleikiipbkdcgllbllahaob

And, of course: Azure-Design (Visio/PNG stencils) from David Summers here: https://github.com/David-Summers/Azure-Design

**Comment by Zimmergren** [comment]
Thank you for opening this ticket. There's been several updates to the download packs, and all icons are now high-quality SVG icons, available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

We have internal discussions where we're exploring other source formats than svg, too.

#please-close
