### ISSUE TITLE
Cosmos DB - not a data store for Analytics workloads

### ISSUE THREAD

**Issue by alpeles** [MicrosoftDocs/architecture-center#3578]
Hello
This architecture might be a bit confusing , since Cosmos DB is not designed to be a database for Analytics workloads. 
There should be some other DB instead, such as ADX, Synapse Dedicated SQL or Azure SQL Hyperscale
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42385d9e-bf16-c83f-4cc4-bc7819b7c72a
* Version Independent ID: 8ff90608-83ab-fe3f-c01a-5e4e288f28fc
* Content: [Stream processing with Databricks - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/stream-processing-databricks)
* Content Source: [docs/reference-architectures/data/stream-processing-databricks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/data/stream-processing-databricks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by Grace-MacJones-MSFT** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by jocontr** [comment]
Here is additional context to CosmosDB that you may find useful.
Intro - https://learn.microsoft.com/en-us/azure/cosmos-db/
Analytics - https://learn.microsoft.com/en-us/azure/cosmos-db/synapse-link
