### ISSUE TITLE
The behavior of this command has been altered by the following extension: aks-preview

### ISSUE THREAD

**Issue by guter1** [MicrosoftDocs/architecture-center#3579]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af2f117-85b5-b53e-b9b8-58c43a0aac71
* Version Independent ID: 0640e0e2-04d8-e056-78e8-977bb7a559dc
* Content: [AKS triage container registry connectivity - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-triage-container-registry)
* Content Source: [docs/operator-guides/aks/aks-triage-container-registry.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/operator-guides/aks/aks-triage-container-registry.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @kevingbb
* Microsoft Alias: **architectures**

**Comment by himanshusinha-msft** [comment]
Thanks for the ask  . At this time we are reviewing the ask and we will reply back as soon as we can .

**Comment by hallihan** [comment]
@guter1 Can you provide more details?  Is this causing an issue or error, if so please provide specifics.

**Comment by hallihan** [comment]
Please report a new feedback item with more detail if help is still needed. #please-close
