### ISSUE TITLE
Pricing guidance on Purview

### ISSUE THREAD

**Issue by raindropami** [MicrosoftDocs/architecture-center#3581]
Hi there

I have a customer who is looking at implementing Purview and needs to put budget and will appreciate receiving guidance on how to price for Purview.

Thanks
Ami

**Comment by RohitMungi-MSFT** [comment]
@raindropami This repo is primarily used to address issues related to azure services documentation. If you are following any document related to azure services could you please post the link as it would be easier for us to tag the issue and redirect to the correct team.

If you have any query regarding any service, then you could post the same on [MS Q&A forum](https://docs.microsoft.com/en-us/answers/index.html) with the appropriate service tag so all users and experts from community could help. Thanks!!

With respect to azure pricing, I would recommend checking the [azure pricing calculator](https://azure.microsoft.com/en-us/pricing/calculator/?service=purview) for approximating costs before its usage. Thanks!!
