### ISSUE TITLE
A sample project for the cloud design patterns

### ISSUE THREAD

**Issue by tahazayed** [MicrosoftDocs/architecture-center#3584]
Would you please provide a code sample that includes all the cloud design patterns?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e99886-d5c7-ca7c-6943-ee31cfc39902
* Version Independent ID: 04021af5-10a9-b600-5f44-354d0c0e50c9
* Content: [Ambassador pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/ambassador)
* Content Source: [docs/patterns/ambassador.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/ambassador.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by hallihan** [comment]
@tahazayed thanks for the suggestion. We know that code samples can useful, but we do not have plans to provide code samples to cover the entire breadth of cloud design patterns. The patterns are intended to be implementation-agnostic ideas that can be implemented using a wide variety of technologies. #please-close
