### ISSUE TITLE
Add a hyperlink to WebAuthn in Azure Active Directory IDaaS in security operations page

### ISSUE THREAD

**Issue by iSatishYadav** [MicrosoftDocs/architecture-center#3588]
Add a hyperlink to WebAuthn in following page:
[Azure Active Directory IDaaS in security operations](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aadsec/azure-ad-security) -> Architectue -> Components -> Credential management ->  Passwordless authentication

So readers can know more about WebAuthn. 

Current: 
> You can also enable passwordless authentication with [FIDO2-compatible security keys](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-passwordless-security-key), which use WebAuthn and the [FIDO Alliance's Client-to-Authenticator (CTAP) protocol](https://fidoalliance.org/specifications/download/).

Proposed:

> You can also enable passwordless authentication with [FIDO2-compatible security keys](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-passwordless-security-key), which use [WebAuthn](https://www.w3.org/TR/webauthn-2/) and the [FIDO Alliance's Client-to-Authenticator (CTAP) protocol](https://fidoalliance.org/specifications/download/).

_This is my first issue here, please ignore any rookie blunders, and tell me if some more details are required_

I want to contribute, and can create a PR for this. Let me know should I? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7590665-2688-5da1-54ff-029be05c6376
* Version Independent ID: b1dfa5fa-537e-cf03-bb2f-4b9d79420169
* Content: [Azure Active Directory IDaaS in security operations - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aadsec/azure-ad-security)
* Content Source: [docs/example-scenario/aadsec/azure-ad-security.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/aadsec/azure-ad-security.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by MayankBargali-MSFT** [comment]
@iSatishYadav Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.
