### ISSUE TITLE
Update to use Azure Machine Learning

### ISSUE THREAD

**Issue by flacidsnake** [MicrosoftDocs/architecture-center#3589]
Please, update this article and the templates to not use non-deprecated resources like Machine Learning Studio classic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42f5f6b4-e65b-eacd-10e4-a72c44375d96
* Version Independent ID: e39819f6-d71e-c586-7a16-a5cd4ae28ca3
* Content: [Demand forecasting for shipping and distribution - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/demand-forecasting-for-shipping-and-distribution)
* Content Source: [docs/solution-ideas/articles/demand-forecasting-for-shipping-and-distribution.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/demand-forecasting-for-shipping-and-distribution.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
Thank you for your feedback.  This has been addressed.
