### ISSUE TITLE
GitHub vulnerability management - Markdown link broken

### ISSUE THREAD

**Issue by faxg** [MicrosoftDocs/architecture-center#3590]
Broken Markdown - should be a link, but displays verbatim
`[Vulnerability management][GitHub vulnerability management] 
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e82337-21f1-4c3c-0a71-2436a96cf9ad
* Version Independent ID: 9fee3170-fd8b-dcb5-3bed-6858880f9337
* Content: [DevSecOps with GitHub Security - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-github?ocid=eml_pg356512_gdc_comm_az&mkt_tok=MTU3LUdRRS0zODIAAAGGbaXO_GMIPvW_dHnT8AdrZoY-2fM3XK-B5VCsSGvsZ5xUsswl2xLJ_V3Y04BPGo-PiMk7nipn4mH-iafDYhLdAW6Nn9k2pkPiuTEpypeIlG0-OhMWlTspuAtI)
* Content Source: [docs/solution-ideas/articles/devsecops-in-github.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/devsecops-in-github.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @fmigacz
* Microsoft Alias: **fmigacz**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
It appears this issue has been resolved.  If you are still experiencing an issue, please reopen with further details.
