### ISSUE TITLE
Add Visio download link to architecture diagrams

### ISSUE THREAD

**Issue by s4parke** [MicrosoftDocs/architecture-center#3592]
Most pages appear to have a link to "Download Visio file of this architecture", although several are missing the diagram download link. The ability to customize these diagrams for transformation plans is a game changer.

Many thanks for the excellent work on these guides. 

Steps to reproduce
1. First, go to the [Implement a hybrid network](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz) guide page.
2. Look in the space below the Architecture diagram (fig. 1).
3. Next, go to [Long-term security log retention with Azure Data Explorer](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/security/security-log-retention-azure-data-explorer) guide page.
4. Look in the space below the Architecture diagram (fig 2).

Fig. 1 - Yep
<img width="376" alt="image" src="https://user-images.githubusercontent.com/656510/186453345-951c4e19-f670-4d1f-bc22-24b21e709c24.png">

Fig. 2 - Nope
<img width="368" alt="image" src="https://user-images.githubusercontent.com/656510/186463323-66202a2f-6f65-4201-b4e5-43d3f3423e0a.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cce1e234-bf77-9f76-ef22-16df2a86b2dc
* Version Independent ID: cce1e234-bf77-9f76-ef22-16df2a86b2dc
* Content: [Long-term security log retention with Azure Data Explorer - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/security/security-log-retention-azure-data-explorer)
* Content Source: [docs/example-scenario/security/security-log-retention-azure-data-explorer.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/security/security-log-retention-azure-data-explorer.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @DeepakAgrawalMS
* Microsoft Alias: **dagrawal**

**Comment by mumurug-MSFT** [comment]
@s4parke Thanks for the feedback. I have assigned the issue to author, and we will review and update as appropriate.

**Comment by skabou** [comment]
It appears this issue has been addressed.  Please re-open with additional information if assistance is still needed.
