### ISSUE TITLE
Using log files instead of streaming sensor values

### ISSUE THREAD

**Issue by wernerzirkel** [MicrosoftDocs/architecture-center#3593]
[Enter feedback here]
In many cases you will not be able to use streaming mode for sensor values directly but you would need to extract sensor data from logfiles first. In this case it is possible to send the logfiles and start Azure Functions via Event Grid to extract sensor values. The values may be sent to Kusto for prediction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19c5cae-a67a-582a-94a5-4708b4508992
* Version Independent ID: 65757df2-366b-ad29-b1ef-e0de2b84b58f
* Content: [Predictive maintenance - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/predictive-maintenance?source=docs)
* Content Source: [docs/solution-ideas/articles/predictive-maintenance.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/predictive-maintenance.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.
