### ISSUE TITLE
Visio diagram download link is not working. on download it just opens the blank page. 

### ISSUE THREAD

**Issue by janitairfan** [MicrosoftDocs/architecture-center#3597]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec53963c-4c95-f6e7-90e0-d1e827df50b0
* Version Independent ID: 81cb35e8-e65d-41b7-f53d-5ddada2b6301
* Content: [Scalable web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app)
* Content Source: [docs/reference-architectures/app-service-web-app/scalable-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/scalable-web-app.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @ckittel
* Microsoft Alias: **chkittel**

**Comment by SwathiDhanwada-MSFT** [comment]
@janitairfan Thanks for your feedback. I have tested the download link from Edge. Its working as expected. Can you please try to access from different browser and check if you are still facing the issue?

**Comment by janitairfan** [comment]
@SwathiDhanwada-MSFT If I click on the download file link it says the file is downloaded and I can see the file in the downloads folder too. but when I click on the visio file its opening a blank edge page. I have tested it on the chrome and edge both same results I get.

**Comment by SwathiDhanwada-MSFT** [comment]
@janitairfan Can you please if you are able to view attached visio file ? Kindly unzip the file and access it.
[app-service-reference-architectures-scalable-webapp.zip](https://github.com/MicrosoftDocs/architecture-center/files/9469557/app-service-reference-architectures-scalable-webapp.zip)

**Comment by janitairfan** [comment]
thanks for your help.
