### ISSUE TITLE
Azure Firewall with Application Gateway - hub & spoke, application gateway placement

### ISSUE THREAD

**Issue by kamilzzz** [MicrosoftDocs/architecture-center#3599]
When considering filtering traffic with Application Gateway and Azure Firewall with hub & spoke topology, documentation mentions Application Gateways are often managed by application teams hence deployed in spoke virtual networks:

> The Azure Firewall is deployed in the central hub virtual network. Application teams often manage components such as Azure Application Gateways or Azure API Management gateways, though. These components are deployed in the spoke virtual networks.

However, the diagram shows Application Gateway deployed in Hub virtual network (alongside with Azure Firewall subnet and GatewaySubnet):
![image](https://user-images.githubusercontent.com/32141632/187170895-3ef1bb75-9c36-438b-993c-6798475c39e6.png)

Shouldn't the diagram be updated there to align with what is described?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall, App Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by SatishBoddu-MSFT** [comment]
> @kamilzzz 
I have assigned the issue to the content author for further review.

**Comment by v-fearam** [comment]
Hi @kamilzzz 



Sorry for the delay.

[The first consideration currently said](https://learn.microsoft.com/azure/architecture/example-scenario/gateway/firewall-application-gateway#considerations)

“The Azure Firewall is deployed in the central hub virtual network. The diagram above shows the practice of deploying the Application Gateway in the hub. Application teams often manage components such as Azure Application Gateways or Azure API Management gateways, though. In this case, these components are deployed in the spoke virtual networks.
”
Your concern was already addressed.

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
