### ISSUE TITLE
Incorrect information on auto upgrade status

### ISSUE THREAD

**Issue by carmodyquinnms** [MicrosoftDocs/architecture-center#3602]
Hi
Please fix the last 2 bullets on the page to show that auto upgrade for clusters and node images are fully GA now.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43da9bdf-a3d3-a65b-b555-60dcc5ac2c55
* Version Independent ID: 9913c705-aeb7-e154-4fdf-164ff1e7ff99
* Content: [AKS Day-2 - Patch and upgrade guidance - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-upgrade-practices)
* Content Source: [docs/operator-guides/aks/aks-upgrade-practices.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/operator-guides/aks/aks-upgrade-practices.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **pnp**

**Comment by SwathiDhanwada-MSFT** [comment]
@carmodyquinnms Thanks for your comment. We will review the issue and get back to you shortly.

**Comment by ckittel** [comment]
This update was made by @PixelRobots & @rishabhsaha and should be going live today yet - unless the publication process gets hung up for some reason (in that case it will be tomorrow). Thanks @carmodyquinnms.
