### ISSUE TITLE
Route All Setting can be Enabled or Disabled

### ISSUE THREAD

**Issue by nelroosevelt** [MicrosoftDocs/architecture-center#3604]
Route All Setting can be set to Enabled or Disabled.

To make DNS resolve the hostname to the SQL Database's private IP address, [enable the Route All setting on the web app's VNet integration](https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet#application-routing).
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app#dns-configuration

When testing using nameresolver from a web app with the vnet route all disabled, name resolves to the private IP address after a couple of attempts.  The article below states that "If no custom DNS is specified, it uses Azure default DNS and any private zones linked to the virtual network."
 
After your app integrates with your virtual network, it uses the same DNS server that your virtual network is configured with. If no custom DNS is specified, it uses Azure default DNS and any private zones linked to the virtual network.
https://docs.microsoft.com/en-us/azure/app-service/overview-vnet-integration#azure-dns-private-zones

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7499b146-3340-d7d1-6c5f-3ed508b773cb
* Version Independent ID: 61b10612-1136-3840-c7c1-804e63b23410
* Content: [Web app private connectivity to Azure SQL Database - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app)
* Content Source: [docs/example-scenario/private-web-app/private-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/private-web-app/private-web-app.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jelledruyts
* Microsoft Alias: **jelled**

**Comment by MayankBargali-MSFT** [comment]
@nelroosevelt Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by jelledruyts** [comment]
@nelroosevelt thanks for flagging this! The "Route All" setting used to be required to get DNS working but apparently App Service now proactively uses the DNS service of the VNet as the documentation you linked to calls out. So that's great! I've updated the article (as well as the [sibling multi-region version](https://docs.microsoft.com/azure/architecture/example-scenario/sql-failover/app-service-private-sql-multi-region)) to no longer mention "Route All". Thanks again!

**Comment by mumurug-MSFT** [comment]
@nelroosevelt We are closing this thread and feel free to reach out for any questions. Thanks again.
