### ISSUE TITLE
Private Endpoint and NSGs

### ISSUE THREAD

**Issue by atombravo** [MicrosoftDocs/architecture-center#3606]
(https://docs.microsoft.com/en-us/azure/architecture/guide/networking/private-link-hub-spoke-network#networking) 
On this section, the following is misleading:

> To restrict access from your hub or on-premises system to Private Endpoint, use a network security group in the subnet where you've deployed Private Endpoint. Configure appropriate inbound rules.

see https://docs.microsoft.com/en-us/azure/private-link/disable-private-endpoint-network-policy?tabs=network-policy-portal 

By default NSGs do NOT apply to subnets with private endpoints (it may still be a public preview feature? https://azure.microsoft.com/en-us/updates/public-preview-of-private-link-network-security-group-support/ ).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b5e1f6d-c45c-cb0f-f3d6-eedfdee9feff
* Version Independent ID: c55252c7-d117-024f-33ca-c1fd4e6c77ad
* Content: [Azure Private Link in a hub-and-spoke network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/networking/private-link-hub-spoke-network)
* Content Source: [docs/guide/networking/private-link-hub-spoke-network.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/networking/private-link-hub-spoke-network.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @jangelfdez
* Microsoft Alias: **josefern**

**Comment by SwathiDhanwada-MSFT** [comment]
@atombravo Thanks for your comment. We will review the issue and get back to you shortly.

**Comment by jangelfdez** [comment]
Hi! NSG for Private Endpoints is already GA. You can use it in production environments if needed. Here are the details: https://azure.microsoft.com/en-us/updates/general-availability-of-network-security-groups-support-for-private-endpoints/

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @atombravo 
As mentioned above by @jangelfdez the NSG feature for Private endpoints is now GA. Since we did not determine any documentation update here, we will now proceed to close this issue out. Thank you!
