### ISSUE TITLE
Azure DevOps and Power Platform

### ISSUE THREAD

**Issue by RKCS125** [MicrosoftDocs/architecture-center#3607]
I am considering using Azure DevOps and Power Platform to custom develop 3 modules, one of them being Case Management.

The modules should be scalable.
Integrations between different modules.
Each module should contain distinct user groups with some overlap across modules
Integrate with external systems.

What other tools would I need? 
How do I estimate the level of effort?
What else am I missing? API Connectivity, Database set up? anything else?

Thank you!

Ben R

**Comment by SatishBoddu-MSFT** [comment]
Hello @RKCS125,

Thanks for reaching out to us.

Could you please submit a question on [**Microsoft Q&A**](https://docs.microsoft.com/en-us/answers/index.html) forum and we will address it asap?

My apologies, the scope of Github issues is limited to the queries related with the document bugs or tutorial enhancements or product issues\blockers, so we would like to request you to submit Q&A forum query and it will be addressed as soon as possible.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
