### ISSUE TITLE
real-time API for ML applications?

### ISSUE THREAD

**Issue by QuetzalcoatlRosso** [MicrosoftDocs/architecture-center#3608]
Following this article, are there suggested articles or recommendations for connecting existing machine-learned models to an API that can be called for predictions in near-real-time? E.g. a process whereby a client can send data to the API and get back a prediction response from an existing ML model with sub-second latency?

Connecting this article with near-real time ML applications could be a good idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830e1782-9caa-3533-10a0-85a3d4483d24
* Version Independent ID: d66583fa-188c-9dce-b6fd-84b34c0bf315
* Content: [Real-time processing - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/real-time-processing)
* Content Source: [docs/data-guide/big-data/real-time-processing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/big-data/real-time-processing.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by SatishBoddu-MSFT** [comment]
@QuetzalcoatlRosso 
I have assigned the issue to the content SME for further review.

**Comment by jocontr** [comment]
@QuetzalcoatlRosso I would recommend the following articles for guidance on the various points you made above:

- https://learn.microsoft.com/en-us/azure/architecture/guide/ai/custom-speech-text
- https://learn.microsoft.com/en-us/azure/architecture/guide/ai/language-model-pipelines
- https://learn.microsoft.com/en-us/azure/machine-learning/concept-ml-pipelines?view=azureml-api-2&toc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Ftoc.json&bc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fbread%2Ftoc.json
- https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/commerce-chatbot?view=azureml-api-2
- https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/intelligent-apps-image-processing?view=azureml-api-2
- https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/deploy-real-time-machine-learning-model-application-ui?view=azureml-api-2
- https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/ai/real-time-recommendation?view=azureml-api-2
