### ISSUE TITLE
dox improvement to show firewall skus on decision tree

### ISSUE THREAD

**Issue by vigouredelaruse** [MicrosoftDocs/architecture-center#3610]
the document referenced is in the search space for 'decision tree + firewall' - however the decision tree in this document does not have nodes for firewall skus

the fact is that the load balancing decision is a cross cutting concern that impacts traffic flow and therefore firewall deployments - how many, and where, for what purpose

this suggestion is a way to decrease search time for 
- people looking for decision trees that show deployment scenarios, azure load balancing options, and the associated firewall options for each load balancing option

for extra points the tree could be inverted to show how a particular firewall decision scopes load balancing options

thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by SatishBoddu-MSFT** [comment]
@vigouredelaruse 
I have assigned the issue to the content SME for further review.

**Comment by hallihan** [comment]
@vigouredelaruse Thanks for the feedback. Can you provide details on what search tools you were using that landed you on this page for firewall information? This page serves its intended purpose for Load Balancing information, but if you provide some details we can see if there's something we can do to make sure folks land on the expected content.

**Comment by vigouredelaruse** [comment]
hi - it's been some time but i probably tried to be precise with the search term i used and voila - the first link in google now does have a flowchart so i think somebody got to this.. this is the flowchart from the first link
![image](https://user-images.githubusercontent.com/31052867/236584926-727ed042-2276-475d-99ad-94298f8a8beb.png)

the flowchart above is precisely the kind of thing i wanted to see so i'm comfortable if you went ahead and closed this

these are the current search results
![image](https://user-images.githubusercontent.com/31052867/236584832-443951a7-6eae-4f22-9c04-719c7096cf4b.png)

**Comment by v-fearam** [comment]
#please-close
