### ISSUE TITLE
Architecture flow diagram not correct

### ISSUE THREAD

**Issue by NielsFilter** [MicrosoftDocs/architecture-center#3611]
Looking at the architecture flow diagram, I have a few comments on things that don't look correct (see screenshot image)

1. Typo. "loud" should be "cloud"
2. "Build New" needs to connect up with containerized. The diagram, shows containerization only relevant for "Migrations" which isn't correct
3. This is not an error, but not great advice IMHO. ACI should be replaced with Container Apps. This diagram may lead some to use ACI for production workloads that don't need "full orchestration". I would suggest that in almost all cases for production apps, Container Apps is more suited for production use cases, given that ACI can't scale more than 1 instance

Thanks for the initiative with this diagram, it's useful as a basic tool to investigating services for right purpose

![image](https://user-images.githubusercontent.com/4918407/188393249-297be9f1-5d6a-4fb4-8d88-77556a197da5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree?WT.mc_id=javascript-74010-ninarasi)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree?WT.mc_id=javascript-74010-ninarasi)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@NielsFilter 
Thanks for your feedback! We have assigned the issue to author and he will update as appropriate.

**Comment by ckittel** [comment]
I know there is more in here than just the typo, but wanted to cross-link an issue that also identified the typo #3618

**Comment by RobBagby** [comment]
@NielsFilter - The following PR fixed the typeo: https://github.com/MicrosoftDocs/architecture-center-pr/pull/8135

The image has also been updated, such that if that choice is a no, the flow continues to ACI. ACI is a viable choice if we do nb

**Comment by RobBagby** [comment]
Hi @NielsFilter - This article has been updated to fix the typeo. It also now includes ACA along with ACI in the tree. ACI is chosen if orchestration is not needed. ACA falls under the path where orchestration is needed.
