### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mingdaoy** [MicrosoftDocs/architecture-center#3612]
[Enter feedback here]
**Customers** rely on certain partitions and the order of the events they contain.

Should it be "**Consumers**"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b605814-334f-8c2c-165d-050788d5636a
* Version Independent ID: 1b678e8e-4d7a-715c-1faf-96870e134a85
* Content: [Partitioning in Event Hubs and Kafka - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/event-hubs/partitioning-in-event-hubs-and-kafka)
* Content Source: [docs/reference-architectures/event-hubs/partitioning-in-event-hubs-and-kafka.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/event-hubs/partitioning-in-event-hubs-and-kafka.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @rasavant-ms
* Microsoft Alias: **rasavant**

**Comment by YashikaTyagi-MSFT** [comment]
@mingdaoy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MayankBargali-MSFT** [comment]
@mingdaoy Thanks for reporting this item! I have updated the doc and it will be published soon. We appreciate the feedback!

**Comment by MayankBargali-MSFT** [comment]
@mingdaoy Hope the above helps and clears things up. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
