### ISSUE TITLE
Missing product links

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/architecture-center#3613]
The page should include links to Azure Load Testing and Azure Chaos Studio product doc pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ded56014-b7da-2acd-6b38-e71611a50200
* Version Independent ID: ded56014-b7da-2acd-6b38-e71611a50200
* Content: [Continuous validation with Azure Load Testing and Azure Chaos Studio - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/testing/mission-critical-deployment-testing)
* Content Source: [docs/guide/testing/mission-critical-deployment-testing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/testing/mission-critical-deployment-testing.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @heoelri
* Microsoft Alias: **msimecek**

**Comment by RobBagby** [comment]
@algattik - we have added links to both.
