### ISSUE TITLE
Pricing not available

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/architecture-center#3614]
The sentence "The pricing for CluedIn is open and transparent. You can see the pricing on their [website](https://www.cluedin.com/)." does not seem to be correct. Pricing is not indicated on the website.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278e83ef-9b90-cb2d-9ff6-0dd8f5ff1b87
* Version Independent ID: 7e63fe30-9080-9207-ad0f-62263379de0c
* Content: [Master data management with Azure and CluedIn - Azure Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/cluedin)
* Content Source: [docs/reference-architectures/data/cluedin.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/data/cluedin.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **Oliver.Kaae**

**Comment by YashikaTyagi-MSFT** [comment]
@algattik 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by v-fearam** [comment]
PR was merged
#please-close
