### ISSUE TITLE
Confusion between billing zones and availability zones

### ISSUE THREAD

**Issue by kasimrehman** [MicrosoftDocs/architecture-center#3617]
[Enter feedback here]

Quote: "Data transfers across availability zones of a region are not free. If your workload is multi-region or there are transfers across billing zones, then expect additional bandwidth cost. For more information, see [Traffic across billing zones and regions](https://docs.microsoft.com/en-us/azure/architecture/framework/cost/design-regions?branch=master#traffic-across-billing-zones-and-regions)."

The first sentence seems to indicate that the rest of the paragraph applies to *availability* zones but the remaining paragraph and the link reference *billing* zone. These are completely different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks/baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by kasimrehman** [comment]
Also, data transfer between availability zones is currently free with plans to change this in the future. This should be documented accurately here.

**Comment by ckittel** [comment]
@kasimrehman - Please see the FAQ on what Availability Zone data charges exist today.  https://azure.microsoft.com/pricing/details/bandwidth/#faq - which does include ingress and egress between availability zones in the same virtual network.  There are billing (charge) boundaries, and availability zones represents one of those boundaries for specific flows.

**Comment by RobBagby** [comment]
Closed with pull request: https://github.com/MicrosoftDocs/architecture-center-pr/pull/8926
