### ISSUE TITLE
Azure Decision Tree - "loud optimized" .. should be "cloud optimized"

### ISSUE THREAD

**Issue by garyciampa** [MicrosoftDocs/architecture-center#3618]
Hey folks, 

looking at the doc, I think the decision title for one line is incorrect .. Start -> Migrate -> "loud optimized" I think should be "Cloud Optimized" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**
![Screenshot 2022-09-06 095614](https://user-images.githubusercontent.com/56933939/188654042-ee70b18e-3d1f-4a6b-83ae-4afecd356e44.png)

**Comment by mumurug-MSFT** [comment]
@garyciampa Thanks for the feedback. We will review and update as appropriate.

**Comment by stephen-sumner** [comment]
Tagging @seanli1988 for awareness

**Comment by stephen-sumner** [comment]
I pushed a PR fix: [AAC - compute decision tree by stephen-sumner · Pull Request #8135 · MicrosoftDocs/architecture-center-pr (github.com)](https://github.com/MicrosoftDocs/architecture-center-pr/pull/8135)
