### ISSUE TITLE
SAP Router for SAP Note Download - no longer applies

### ISSUE THREAD

**Issue by Darryl-G** [MicrosoftDocs/architecture-center#3622]
Hello,

Please check SAP note 3010412 - "SAP Support Backbone - Configuration Overview, Responsibilities and Troubleshooting".
SAP note download into SAP Netweaver ABAP has not required the SAP Router since January 2020.

Thanks

Darryl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf95a78-b354-11c7-de36-2bc0787c930c
* Version Independent ID: fdf95a78-b354-11c7-de36-2bc0787c930c
* Content: [Inbound and outbound internet connections for SAP on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/sap/sap-internet-inbound-outbound)
* Content Source: [docs/guide/sap/sap-internet-inbound-outbound.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/sap/sap-internet-inbound-outbound.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @msftrobiro
* Microsoft Alias: **robiro**

**Comment by msftrobiro** [comment]
Thank you for raising this Darryl. Absolutely agree and it was an oversight to keep that superfluous sentence about note download. Appreciate your raising this and PR on the way to correct this very soon. Will update once PR is live.

**Comment by v-fearam** [comment]
PR was merged. 
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
