### ISSUE TITLE
Missing link to the diagram

### ISSUE THREAD

**Issue by shailwx** [MicrosoftDocs/architecture-center#3624]
The article is missing a link to download the diagram in Visio or PowerPoint
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600321a5-3245-b82b-1fe7-76f9406d83b2
* Version Independent ID: 440ab4ea-39d4-bbcc-b54f-8d46b70fec44
* Content: [Integrate IBM mainframe and midrange message queues with Azure - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/mainframe/integrate-ibm-message-queues-azure)
* Content Source: [docs/example-scenario/mainframe/integrate-ibm-message-queues-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/mainframe/integrate-ibm-message-queues-azure.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **askhande**

**Comment by YashikaTyagi-MSFT** [comment]
@shailwx 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by lukemurraynz** [comment]
Just adding to this, the Storage image (https://learn.microsoft.com/en-us/azure/architecture/example-scenario/mainframe/integrate-ibm-message-queues-azure#storage) - has the old Azure logo.

**Comment by skabou** [comment]
Thank you for your feedback.  It appears the Visio link has been added.  If you still need assistance, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
