### ISSUE TITLE
Clarification about App Service free managed certificate with original host name preservation

### ISSUE THREAD

**Issue by kamilzzz** [MicrosoftDocs/architecture-center#3626]
In the **Implementation guidance for common Azure services** section we're told the recommendation is to preserve the original host name in the call between the reverse proxy and the back-end application server:
![image](https://user-images.githubusercontent.com/32141632/189078190-dc823709-972e-45b1-b713-a40e3ef3c228.png)

End-to-end TLS encryption is often required and is also recommended (especially for Azure Front Door) in other places in the documentation. 
Recommendation in the article is to import an existing certificate or use App Service free managed certificate.

Clarification about free managed certificate is needed as according to my knowledge it is not going to work in this scenario. From the documentation regarding App Service free managed certificate there are some prerequisites which have to be met in order to generate certificate (https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate?tabs=subdomain%2Cportal#create-a-free-managed-certificate):

For the Apex domain:

- **Must have an A record pointing to your web app's IP address.**
- Isn't supported on apps that are not publicly accessible.
- Isn't supported with root domains that are integrated with Traffic Manager.
- Must meet all the above for successful certificate issuances and renewals.

For the subdomain:

- **Must have CNAME mapped directly to <app-name>.azurewebsites.net. Mapping to an intermediate CNAME value blocks certificate issuance and renewal.**
- Must meet all the above for successful certificate issuance and renewals.

In the suggested architecture A or CNAME record is mapped to the address of reverse proxy and not backend app itself, hence App Service won't be able to generate certificate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5beaff9-80fa-3c91-f5c6-81c3fda8bbb6
* Version Independent ID: c5beaff9-80fa-3c91-f5c6-81c3fda8bbb6
* Content: [Host name preservation - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/best-practices/host-name-preservation)
* Content Source: [docs/best-practices/host-name-preservation.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/host-name-preservation.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @jelledruyts
* Microsoft Alias: **jelled**

**Comment by mumurug-MSFT** [comment]
@kamilzzz Thanks for the feedback. We will review and update as appropriate.

**Comment by jelledruyts** [comment]
@kamilzzz thanks a lot for flagging this, you make a really good point (unfortunately)! This seems to be a limitation of the free certificates which don't allow domain validation using TXT records for example. I am following this up with the App Service team internally to see if we can remove that limitation somehow. In the meantime, if you absolutely require end-to-end TLS then the only alternative is to use the paid App Service Certificate (which allows other validation mechanisms) or import a certificate which you purchased elsewhere (and renew it yourself). I've updated the article to call this out. Thanks again for reaching out!

**Comment by mumurug-MSFT** [comment]
@jelledruyts Thank you for updating the article.

 @kamilzzz We will proceed to close this thread and feel free to reach out if any further questions. Thanks again.
