### ISSUE TITLE
Please add link to download Visio file

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/architecture-center#3628]
[Enter feedback here]
The Visio diagram that is on this page does not have a link to download the file. The same issue is on 
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-paas 
https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-microservice

The other pages in the Azure solution architecture that these pages are in have Visio download links. 

Additional ask - I have a customer that is looking for the template, and if I could get a copy that I could share while the page is being updated, that would be very helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115fe9d4-6876-b76b-c194-6dbe760f0131
* Version Independent ID: bd2dbb27-a069-8609-5421-33d223df06eb
* Content: [DevTest and DevOps for IaaS solutions - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-iaas)
* Content Source: [docs/solution-ideas/articles/dev-test-iaas.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/dev-test-iaas.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@cchapin2020 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@cchapin2020 can you try downloading the visio file from [this link](https://arch-center.azureedge.net/dev-test-iaas.vsdx)
