### ISSUE TITLE
How can we use privateendpoint web app as backend of App Gateway + Firewall

### ISSUE THREAD

**Issue by omerzubair** [MicrosoftDocs/architecture-center#3632]
Hi MS, 

I wish to use your scenario "Application Gateway before Firewall". 
This will help us achieve requirement of TLS/IDPS/DDos by using Az firewall after the App Gateway. 
however instead of using the IaaS VM i wish to use my private end pointed Web apps/Function Apps. 

Reason is that all my PaaS resources (WebApp,FunctionApp, KV, Storage etc) are in my internal network with no public endpoint exposed. 
But I cannot find any article for it . When I set it up myself I do 404 error on Public IP of my App Gateway.

So to recap my setup is :

PublicIP -> AppGatewayv2 & WAF -> Subnet -> Az Firewall -> subnet -> Web App with Private Endpoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall, App Gateway for virtual networks - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway#application-gateway-before-firewall)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by Givary** [comment]
@omerzubair Thank you for your feedback . We will investigate and update the thread.

**Comment by omerzubair** [comment]
Hi @Givary , i was able to work with private endpoint + vnet injected web apps as backend of the app gateway. 
You can close this ticket. However it would be great to have a scenario documented to have PaaS as backend in Ms Docs. thanks

**Comment by ckittel** [comment]
@erjosito -- any thoughts on mentioning private endpoints a bit more in this venerable article?  I'm going to close, but wanted to give you an opportunity to consider it for the backlog.

**Comment by erjosito** [comment]
Thanks @ckittel ! Not a bad idea, I can add a short section with a link to the page where we describe gow to firewall traffic to private endpoints
