### ISSUE TITLE
Mixed Reality (VR) in warehouse management

### ISSUE THREAD

**Issue by BiplabGH** [MicrosoftDocs/architecture-center#3633]
Every Warehouse goes through lots of manual operations which includes organising racks, commodity pick up, voice controls etc. while these manual works are either done by human or robots in some case, but what if human are expensive and rarely available due to multiple factors, or the skill set is niche and needs huge effort for training people. 

It would be great if we can have training components added to hololens program, which can connect to WMS systems and guide every user what next to do through real time integrations and navigator system attached. Day 1 will be productive day, as we know with pandemics and all safety is always an issue, we can extend this feature for multiple use case. 

I did got a prototype work, if this excites you, please let me know and i can give more insights.

Thanks,
Biplab

**Comment by AjayBathini-MSFT** [comment]
@BiplabGH 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by AjayBathini-MSFT** [comment]
@BiplabGH 
Thanks for your contribution. Please add your ideas in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)
