### ISSUE TITLE
Loud optimized to Load optimized

### ISSUE THREAD

**Issue by rotorr** [MicrosoftDocs/architecture-center#3634]
On top/left of the decision tree, where it states "loud optimized", should this be load or workload optimized? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
Thanks for raising this. Looks like we had someone else detect this as well, so closing as a dup of #3618.  In their case "Cloud Optimized" instead of "(work)load optimized" -- which is probably what the author meant.
