### ISSUE TITLE
Link to Visio Diagram Broken

### ISSUE THREAD

**Issue by matthansen0** [MicrosoftDocs/architecture-center#3636]
The link to the Visio diagram download is broken.

![image](https://user-images.githubusercontent.com/23407342/189982596-9cdab9af-7fb6-433c-bcf9-c7a7932c6130.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 363ebddf-0348-98e1-fd24-0eef444d383a
* Version Independent ID: e7da7820-925f-2092-c1a4-7a66db3f000d
* Content: [Multi-region load balancing - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/high-availability/reference-architecture-traffic-manager-application-gateway)
* Content Source: [docs/high-availability/reference-architecture-traffic-manager-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/high-availability/reference-architecture-traffic-manager-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mumurug-MSFT** [comment]
@matthansen0 Thanks for your feedback. We have made the changes and it will be published soon after it is merged.

**Comment by mumurug-MSFT** [comment]
The link to the visio diagram works now. Sorry for the inconvenience caused. We will proceed to close this thread. Feel free to reach out if any questions.
