### ISSUE TITLE
Misleading with link for Azure Stack Hub

### ISSUE THREAD

**Issue by alexor-ms** [MicrosoftDocs/architecture-center#3641]
In the section Scalability is a link https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-containers#scalability for deploy Functions or App Services to Azure Stack Hub. This is really misleading, because Azure Stack Hub are completely incompatible with Azure Arc. Therefore, I would suggest to replace it with AKS on-prem e.g. on AsHCI https://docs.microsoft.com/en-us/azure-stack/aks-hci/overview AND the deployment guide for Azure Functions with Azure Arc https://docs.microsoft.com/en-us/azure/app-service/manage-create-arc-environment?tabs=bash.

Thanks Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c86282b-a2f2-d987-3562-c68e9f7aa317
* Version Independent ID: 3b035663-dfbc-9d76-b94d-11234ec1eaed
* Content: [Run containers in a hybrid environment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-containers)
* Content Source: [docs/hybrid/hybrid-containers.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/hybrid-containers.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @pdebruin
* Microsoft Alias: **pidebrui**

**Comment by mumurug-MSFT** [comment]
@alexor-ms Thanks for your feedback. We will review and update as appropriate.

**Comment by v-fearam** [comment]
Hi @alexor-ms 


Sorry for the delay.


The document was updated in Nov 2022. The section Scalability does not exist anymore.


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
