### ISSUE TITLE
Wrong IP value for the default DNS server used by spoke VNET 

### ISSUE THREAD

**Issue by mohijazi** [MicrosoftDocs/architecture-center#3645]
In the WorkFlow part for the private DNS resolver section, we have these lines : 
"All Azure spoke virtual networks use the default Azure DNS server at the IP address 192.63.129.16. All spoke networks are peered with the hub virtual network." 

The IP address 192.63.129.16 is not the Azure default DNS, this may confuse the client, we may need to replace this lime with the Azure default DNS "168.63.129.16"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Version Independent ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Content: [Azure DNS Private Resolver - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/networking/azure-dns-private-resolver)
* Content Source: [docs/example-scenario/networking/azure-dns-private-resolver.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/networking/azure-dns-private-resolver.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @moorthyannadurai
* Microsoft Alias: **moannadu**

**Comment by mumurug-MSFT** [comment]
@mohijazi Thanks for the feedback. We will review and update as appropriate.

**Comment by JKirsch1** [comment]
I've contacted the article contributor and will resolve this issue as soon as he advises me about this edit.

**Comment by ckittel** [comment]
Thank you for reporting this @mohijazi -- I've just made the update and it will go live later on Monday.
