### ISSUE TITLE
Image Gallery Regional BCDR

### ISSUE THREAD

**Issue by saminnes** [MicrosoftDocs/architecture-center#3657]
I'd like clarification on availability of Compute Galleries in the event of regional failure. 
According to this page _"You should store images in the Azure Compute Gallery and configure multiple image replicas in both the primary and the secondary locations."_

however in this article https://learn.microsoft.com/en-us/azure/virtual-machines/azure-compute-gallery 
it states "_1 The Azure Compute Gallery service is not a global resource. For disaster recovery scenarios, it is a best practice is to have at least two galleries, in different regions."_

It seems the solution, say for a UKW/UKS deployment would be to have a compute gallery in each region. However if two compute galleries are used it is not immediately clear to me how  we replicate images between them, once a machine is genaralised and committed to an image gallery it is deleted.

How can we replicate between compute galleries?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a02ac6f-a170-0558-faac-98f669d0e030
* Version Independent ID: 7a02ac6f-a170-0558-faac-98f669d0e030
* Content: [Multiregion BCDR for Azure Virtual Desktop - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-multi-region-bcdr#compute)
* Content Source: [docs/example-scenario/wvd/azure-virtual-desktop-multi-region-bcdr.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/azure-virtual-desktop-multi-region-bcdr.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @igorpag
* Microsoft Alias: **igorpag**

**Comment by mumurug-MSFT** [comment]
@saminnes Thanks for your feedback. We will review and update as appropriate.

**Comment by igorpag** [comment]
Working on this, will update as soon as possible.
Regards.

**Comment by igorpag** [comment]
Hi @saminnes,
You are absolutely right, the Azure Compute Gallery is not a global resource, then it is recommended to have at least a secondary gallery in the secondary region.
Once you have created in the primary region a Gallery, a VM Image Definition and a VM Image Version, you should create the same three objects also in the secondary region.
When creating the VM Image Version, there is the possibility to copy the VM Image Version created in the primary region. 
To achieve this, from the secondary region, you have to specify the Gallery, the VM Image Definition and VM Image Version used in the primary region, and Azure will copy the image and create a local VM Image Version.
It is possible to execute this operation using the Azure Portal or AZ CLI command as outlined below:

https://learn.microsoft.com/en-us/azure/virtual-machines/image-version 
https://learn.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest#az-sig-image-version-create

I tested the procedure, and it works perfectly. 
Thank you to have raised this issue, you contributed to enhance the quality of our documentation.
Regards.

**Comment by igorpag** [comment]
@mumurug-MSFT I willsubmit a PR with the required modification as soon as possible. 
Thanks.

**Comment by mumurug-MSFT** [comment]
@saminnes We have made the changes and it will be published soon after the merge. Thanks again for the feedback and proceeding to close the thread. Feel free to reach out for any questions.
