### ISSUE TITLE
Analytics Compute is missing

### ISSUE THREAD

**Issue by jugi92** [MicrosoftDocs/architecture-center#3666]
Analytics Compute Services such as Synapse Spark Pools and Databricks are unfortunately not considered in the decision tree, even though they are very valid targets for some very huge compute workloads. I would suggest to include them in the tree or mentioned that this is thought for OLTP kind of compute only.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@jugi92 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RobBagby** [comment]
Hi @jugi92 - There is a companion article that includes choosing an analytics solution that includes these tools: https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/analytical-data-stores.  I'm going to close this bug.
