### ISSUE TITLE
Dataverse should be included as a data store option

### ISSUE THREAD

**Issue by mattdot** [MicrosoftDocs/architecture-center#3667]
Dataverse should be included as a data store option

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e40cb85c-ee53-7b49-0622-bed8ebedea81
* Version Independent ID: 896e0838-dfd1-c442-414d-ad9ea6dc8f7d
* Content: [Understand data store models - Azure Application Architecture Guide](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)
* Content Source: [docs/guide/technology-choices/data-store-overview.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/data-store-overview.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **architectures**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37550 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
