### ISSUE TITLE
HA documents for web application explains about VM and not about app service?

### ISSUE THREAD

**Issue by umurugesan1234** [MicrosoftDocs/architecture-center#3674]
Refer below paragraphs - explains about VM and not app service or web app

There are several general approaches to achieve high availability across regions:

Active/Passive with hot standby: traffic goes to one region, while the other waits on hot standby. Hot standby means the **VM**s in the secondary region are allocated and running at all times.

Active/Passive with cold standby: traffic goes to one region, while the other waits on cold standby. Cold standby means the **VMs** in the secondary region are not allocated until needed for failover. This approach costs less to run, but will generally take longer to come online during a failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web app - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region?source=docs)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/multi-region.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Arvindboggaram
* Microsoft Alias: **arboggar**

**Comment by SaibabaBalapur-MSFT** [comment]
@umurugesan1234 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
