### ISSUE TITLE
To migrate an Oracle database to an Azure... 3rd point "Figure out how to archive business continuity and disaster recovery requirements.".. Should it not be "Achieve" instead of "Archive"

### ISSUE THREAD

**Issue by 17kumarrupesh** [MicrosoftDocs/architecture-center#3675]
To migrate an Oracle database to an Azure... 3rd point "Figure out how to archive business continuity and disaster recovery requirements.".. Should it not be "Achieve" instead of "Archive"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0676437-a746-19de-2df2-7919004a14f0
* Version Independent ID: 35cfce4b-fc76-f140-02fb-9ac605157313
* Content: [Overview of Oracle database migration - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/oracle-migrate/oracle-migration-overview)
* Content Source: [docs/example-scenario/oracle-migrate/oracle-migration-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/oracle-migrate/oracle-migration-overview.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @amberz
* Microsoft Alias: **amberz**

**Comment by SaibabaBalapur-MSFT** [comment]
@17kumarrupesh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
Thank you @17kumarrupesh.  This typo will be fixed with the next publication.  This should be by end of business on Monday.
