### ISSUE TITLE
Impossible recommendation "Use automatic failover but manual failback"

### ISSUE THREAD

**Issue by torumakabe** [MicrosoftDocs/architecture-center#3678]
The following recommendation is impossible.

```
Use automatic failover but manual failback. Use Traffic Manager for automatic failover, but not for automatic failback. Automatic failback carries a risk that you might switch to the primary region before the region is completely healthy. Instead, verify that all application subsystems are healthy before manually failing back. Also, depending on the database, you might need to check data consistency before failing back.
```

Traffic Manager does not have manual failback feature or config, so when the primary region or endpoint is online again, Traffic Manager route traffic automatically to the primary. In other words, Traffic Manager always do automatic failback.

Could you please confirm if my understanding is correct and if this recommendation is valid? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64a14304-4ef8-dc1b-b92d-b021fc169710
* Version Independent ID: 33ad8550-7676-2b43-f6cc-a9eb3d3f2093
* Content: [Make all things redundant - Azure Application Architecture Guide](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/redundancy)
* Content Source: [docs/guide/design-principles/redundancy.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/design-principles/redundancy.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by mumurug-MSFT** [comment]
@torumakabe Thanks for reaching out and sharing the feedback. We have assigned this to author for review and will update as appropriate.

**Comment by ckittel** [comment]
Hey there @torumakabe, you are correct in your assessment.  As this is written, it's highly misleading.  The only way you could prevent the failback would be to imperatively update the Traffic Manager profile to disable the primary endpoint, as part of the secondary endpoint starting to receive traffic.  Which, while possible, is not documented here in such a way or implied.  As you are an FTE, would you like to take a stab at helping improve this section of the docs?  If so, reach out to me on Teams and we can get you set up!
