### ISSUE TITLE
Pipelines don't trigger automatically on branch create with path includes

### ISSUE THREAD

**Issue by rubenaster** [MicrosoftDocs/architecture-center#3679]
Thanks for this very detailed article, it's exactly the information I needed!

Regarding the path includes in the YAML file: it seems like a pipeline doesn't trigger a run in Azure DevOps when you create a branch and use path includes. This is especially disappointing when you create a release-branch and want to automatically run a pipeline that does the full deployment.

Are you aware of that limitation and is there a known workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57f4d213-3eb1-5b4c-aa67-116e8fa36f7d
* Version Independent ID: 18199b5a-8f57-6574-c795-7540199ae49a
* Content: [Microservices CI/CD pipeline on Kubernetes with Azure DevOps and Helm - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes#feedback)
* Content Source: [docs/microservices/ci-cd-kubernetes.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/ci-cd-kubernetes.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @jpocloud
* Microsoft Alias: **johnpoole**

**Comment by mumurug-MSFT** [comment]
@rubenaster Thanks for the feedback. We will review and update as appropriate.

**Comment by rubenaster** [comment]
In the end, it works like documented:

> Continuous integration (CI) triggers cause a pipeline to run whenever you push an update to the specified branches or you push specified tags.

I was just expecting that it should also trigger when a branch is being created.

Thanks.
