### ISSUE TITLE
Is there a replacement for the free Anomali Limo TAXII 2.0 feed?

### ISSUE THREAD

**Issue by austinmccollum** [MicrosoftDocs/architecture-center#3680]
Anomali's free Limo TAXII 2.0 feed went end of life 8/14/2022. Their site indicates there will be a new version, but no estimate for when it will be available. Is there an alternative we can use in the meantime?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb40dd7-0e77-0f95-8070-95978cd4a90c
* Version Independent ID: 4476618b-beb5-c8c4-ec8b-787db30643fb
* Content: [Cyber threat intelligence in Microsoft Sentinel - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/data/sentinel-threat-intelligence?source=docs)
* Content Source: [docs/example-scenario/data/sentinel-threat-intelligence.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/sentinel-threat-intelligence.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@austinmccollum 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
@hallihan - FYI, this is being addressed by Content Strategy across the whole platform, in conjunction with @austinmccollum and his team.  This isn't the only place on learn impacted by this change.  So this will be addressed as part of a larger work item to address across the platform.

**Comment by ckittel** [comment]
I worked with @austinmccollum on a "warning message" while this issue is being addressed at a broader level, as to hopefully warn and deflect any customers running into the same thing.

Thanks @austinmccollum!
