### ISSUE TITLE
Updated articles - organization

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3683]
It would be helpful if the listing of updated articles was grouped/sorted/categorized to make it easier to look for articles of interest. The current presentation is quite random which makes it hard to find updated articles that are relevant to our interests.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd7bc22-da10-1d3b-ba22-7d5e374be441
* Version Independent ID: 9f466c91-adc7-0489-5b1e-17633d27c98c
* Content: [What's New in Azure Architecture Center - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/changelog)
* Content Source: [docs/changelog.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/changelog.md)
* Service: **architecture-center**
* GitHub Login: @alexhart11
* Microsoft Alias: **pnp**

**Comment by mumurug-MSFT** [comment]
@DeanGross Thanks for your feedback. We will review and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37544 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close

**Comment by DeanGross** [comment]
why was this closed without any action or explanation? my comment is still applicable
