### ISSUE TITLE
Replace Timeseries Insights with Azure Data Explorer in the decision tree

### ISSUE THREAD

**Issue by shahdevangp** [MicrosoftDocs/architecture-center#3685]
Microsoft has announced the retirement of Timeseries Insights. All TSI customers have been encouraged to migrate to Azure Data Explorer. Our documents and decision tree should also reflect this.

https://learn.microsoft.com/en-us/azure/time-series-insights/how-to-tsi-gen2-migration

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88559925-9b9e-d9b3-ddb6-08306692c17b
* Version Independent ID: a25055cb-7cfe-28a0-1c66-06172c037128
* Content: [Data store decision tree - Azure Application Architecture Guide](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)
* Content Source: [docs/guide/technology-choices/data-store-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/data-store-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @dsk-2015
* Microsoft Alias: **architectures**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by skabou** [comment]
Thanks for your feedback.  This has been addressed and will be updated on the next build.
