### ISSUE TITLE
Update the "release notes" and remove references to old ZIP filenames

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/architecture-center#3687]
There are at least 2 additional updates since January 2021:

![image](https://user-images.githubusercontent.com/503974/194120523-616f873e-376c-4434-9d5f-7e9090c5ab37.png)

Can someone please update the page itself to give the updates since January 2021?? 

It also does not make sense to refer to the filename if it is updated behind-the-scenes without additional context. Either update the page with release notes and file version... or just don't say anything about the version number at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by Zimmergren** [comment]
Thank you for reporting this, @eponerine.

We've made several updates to the Azure Icons recently, and there are hundreds of new icons added.
The update is available for download here: https://learn.microsoft.com/en-us/azure/architecture/icons/

The release notes are also updated and will be published shortly.

Thanks!
#please-close
