### ISSUE TITLE
DevOps section has malformed links

### ISSUE THREAD

**Issue by MarcosMMartinez** [MicrosoftDocs/architecture-center#3691]
![image](https://user-images.githubusercontent.com/29489962/194649857-fa5710b0-a36a-47cb-b77f-084f79d91939.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on AKS - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices)
* Content Source: [docs/reference-architectures/containers/aks-microservices/aks-microservices.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-microservices/aks-microservices.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@MarcosMMartinez 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@EdPrice-MSFT 
Can you please check and add your comments on this doc update request as applicable.
