### ISSUE TITLE
Subnets are redundant

### ISSUE THREAD

**Issue by MarcosMMartinez** [MicrosoftDocs/architecture-center#3692]
![image](https://user-images.githubusercontent.com/29489962/194652508-625e8ac6-b4da-4902-96f2-8c1cc25e739c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks/baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by ManoharLakkoju-MSFT** [comment]
@MarcosMMartinez 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
The name of those subnets is dictated by the services that are deployed into them.  Personally, I don't like the names of them either, but those delegated subnets must be named that for their respective deployments to work.  If you're speaking of something else, please clarify.  The Azure Bastion service cannot co-exist with the Azure Firewall service in the same subnet, so they must be separated.  The names of their respective subnets are checked at deployment time by the resource provider for each.  If this has answered your question/observation, feel free to close.  Thank you.

**Comment by MarcosMMartinez** [comment]
I'm referring to the subnet addresses. They're the same.

**Comment by ckittel** [comment]
Oh, yes! I see that now (I missed the obvious there). We'll get it fixed up.

**Comment by ckittel** [comment]
I've pushed an update to fix the typo, @MarcosMMartinez.  The change should be live within 30 hours.  The `BastionSubnet` will be showing `10.200.0.128/26`, as per the reference implementation.  Thanks for pointing out this mistake and clarifying my confusion at what was _redundant_.
