### ISSUE TITLE
Networking considerations need to take into account different network plugins/requirements for podIPs

### ISSUE THREAD

**Issue by MarcosMMartinez** [MicrosoftDocs/architecture-center#3693]
This section would need to take into account the kubenet network plugin option for pod IPs and the new network plugin set to replace Azure CNI which would remove the requirement to assign 1st-class IPs to pods. These points are also more relevant considering that the AppGW is not leveraged by the AGIC since there's a Traefik ingress controller. 

![image](https://user-images.githubusercontent.com/29489962/194652946-d1a7179b-406b-43fa-93d7-4660041c882b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks/baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by ManoharLakkoju-MSFT** [comment]
@MarcosMMartinez 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi  @MarcosMMartinez

Sorry for the delay. 

The article explains a reference implementation where it was decided to use CNI for [these reasons](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks#pod-to-pod-traffic).

That why the article is not taking into account kubenet network plugin option in that section.

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
