### ISSUE TITLE
Ambiguous statement when comparing Azure CNI to Kubenet

### ISSUE THREAD

**Issue by MarcosMMartinez** [MicrosoftDocs/architecture-center#3694]
This language sounds ambiguous. What are we implying here? Generally speaking, it's easier to deploy larger number of pods in a cluster leveraging the kubenet networkPlugin. We may want to be more specific here?

![image](https://user-images.githubusercontent.com/29489962/194670184-2810a96c-5f9e-4cac-82bd-4e455abbac9c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks/baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by ManoharLakkoju-MSFT** [comment]
@MarcosMMartinez 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi  @MarcosMMartinez

Sorry for the delay. 

Yes, kubenet is simpler. The size is the same based on https://learn.microsoft.com/azure/aks/configure-azure-cni#maximum-pods-per-node

![image](https://user-images.githubusercontent.com/62260324/214819503-df8ea9cc-0710-49c2-9e12-901e2e4be815.png)

I will create a PR to remove that sentence.

**Comment by v-fearam** [comment]
#please-close
