### ISSUE TITLE
Spelling mistake in Title

### ISSUE THREAD

**Issue by mathewjamesn** [MicrosoftDocs/architecture-center#3695]
Hi - The title of the Page is shown as "Queue-Based Load Leveling pattern". 

I believe the correct spelling for "Leveling" is "Levelling". Looks like one "L" is missing. 

Thanks!
-Mathew James 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0b2b229-0cae-3ba9-180c-5aab1a5a4897
* Version Independent ID: 85c2c9d6-cef4-9a7c-a512-ecdd69e1b456
* Content: [Queue-Based Load Leveling pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling)
* Content Source: [docs/patterns/queue-based-load-leveling.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/queue-based-load-leveling.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@mathewjamesn 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MayankBargali-MSFT** [comment]
@mathewjamesn Thanks for reaching out. Both Levelling (British English) and Leveling (American English) are correct and there is a preference. 

As we don't see any doc improvement, we will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by mathewjamesn** [comment]
oh ok. Sure. Thanks!
