### ISSUE TITLE
Tank Level, Tank Level Monitoring, Tank Level Analysis | Oil and Gas | Sotaog

### ISSUE THREAD

**Issue by sgowardipe** [MicrosoftDocs/architecture-center#3696]
Why is there a need for a smart solution for the process of tank level monitoring and analysis?
When handling large volumes of fluids, refineries, chemical plants, and bulk liquid storage terminal operators must know precisely how much product is in any given tank. When products change hands or move in or out of tanks, the monetary values and safety risks can be enormous. Despite this, the devices and systems used to gauge tank contents often receive insufficient attention.

One of the main reasons for this is that those responsible for inventory management and custody transfer often believe the technologies in these systems are static and there is little to gain from making improvements. As a result, they settle into familiar but ineffective work practices, believing the inefficiencies, safety risks, and uncertainties they deal with are part of their daily life.

Many facilities still depend on manual procedures and inefficient systems, and large numbers of devices don’t operate accurately or reliably enough. Making the complete process of Tank level analysis or monitoring operation cost and time expensive.
https://www.sotaog.com/blogs/1000s-of-tank-level-analysis-and-monitoring-tanks-using-ai-and-ml-models

**Comment by Naveenommi-MSFT** [comment]
@sgowardipe 
Thanks for your feedback! We will investigate and update as appropriate.
It would be great if you could add a link to the documentation information you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by Naveenommi-MSFT** [comment]
@sgowardipe 

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
