### ISSUE TITLE
Conflicting statement on patching AKS nodes

### ISSUE THREAD

**Issue by Osshaikh** [MicrosoftDocs/architecture-center#3699]
[As per current document security pacthes doesnt get automaticlly applied to nodes by default , in similar document its mentioned that each evening linux node in AKS get sec pacthes vai distro security update and that behaviour is automatically configured as nodes deployed to AKS cluster.

Refernce doc links: https://learn.microsoft.com/en-us/azure/aks/concepts-security#linux-nodes]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43da9bdf-a3d3-a65b-b555-60dcc5ac2c55
* Version Independent ID: 9913c705-aeb7-e154-4fdf-164ff1e7ff99
* Content: [AKS Day-2 - Patch and upgrade guidance - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-upgrade-practices)
* Content Source: [docs/operator-guides/aks/aks-upgrade-practices.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/operator-guides/aks/aks-upgrade-practices.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **pnp**

**Comment by Naveenommi-MSFT** [comment]
@Osshaikh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
It was already changed

**Comment by v-fearam** [comment]
#please-close
