### ISSUE TITLE
Containerized workloads are not only for lift and shift

### ISSUE THREAD

**Issue by olavt** [MicrosoftDocs/architecture-center#3700]
I think the decision tree is seriously flawed.

Cloud optimized applications are often containerized and will run on Kubernetes or Container Apps. I think the decision tree needs to be revised in order to better reflect reality.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@olavt 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by EdPrice-MSFT** [comment]
Hi @olavt - We're checking into this. Thanks!

**Comment by stephen-sumner** [comment]
This has been updated and PR merged.
