### ISSUE TITLE
Requesting you to upload a vlog on this topic

### ISSUE THREAD

**Issue by Lucifer12598** [MicrosoftDocs/architecture-center#3701]
[Enter feedback here]
Hello!
Can you please upload a working vlog or blog on this architecture so we can learn more about this process? if possible

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05053264-ed30-daa5-ac88-8d7d3798b9b0
* Version Independent ID: 242e667d-f98e-74f9-70b6-8247f4dc221e
* Content: [DevOps in a hybrid environment - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devops-in-a-hybrid-environment?source=recommendations)
* Content Source: [docs/solution-ideas/articles/devops-in-a-hybrid-environment.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/devops-in-a-hybrid-environment.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **asegala**

**Comment by mumurug-MSFT** [comment]
@Lucifer12598 Thanks for your feedback. We will review and update as appropriate.
