### ISSUE TITLE
Mislabeled arrow in sample architecture diagarm?

### ISSUE THREAD

**Issue by sfclimbers** [MicrosoftDocs/architecture-center#3708]
In the sample architecture diagram from an anonymous customer, it would appear that the final green arrow exiting the bottom of the left side should be labeled "Masked production data" as opposed to the current "Unmasked production data".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f64651d0-1885-248b-0d8c-6773f4b6ae1a
* Version Independent ID: f64651d0-1885-248b-0d8c-6773f4b6ae1a
* Content: [Data obfuscation using Delphix in Azure Data Factory and Synapse Analytics - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/data-obfuscation-with-delphix-in-azure-data-factory)
* Content Source: [docs/example-scenario/ai/data-obfuscation-with-delphix-in-azure-data-factory.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/ai/data-obfuscation-with-delphix-in-azure-data-factory.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @nabhishek
* Microsoft Alias: **abnarain**

**Comment by Naveenommi-MSFT** [comment]
@sfclimbers 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by paweenatongbai** [comment]
@EdPrice-MSFT , this article is from https://dev.azure.com/ceapex/pnp/_workitems/edit/652041
The feedback for the diagram to change from 'unmasked' to 'masked' seems valid. Who should I confirm with? 
There is no source file for this png, but maybe I can edit the png directly after the change is confirmed. Thanks!

![image](https://user-images.githubusercontent.com/97064168/197048535-06b16c1e-73b3-4464-ad99-0c6b8b251497.png)

**Comment by EdPrice-MSFT** [comment]
@nabhishek - Can you help verify this is the right change?
