### ISSUE TITLE
SRE acronym

### ISSUE THREAD

**Issue by jlperez01** [MicrosoftDocs/architecture-center#3715]
The acronym SRE is used a number of times in the article, but nowhere in the page is the acronym defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c9cfb32-2013-f31e-0209-d5194afc8d9e
* Version Independent ID: 9cabc767-9799-abcd-6ccd-11f164c30877
* Content: [Architecture of an AKS regulated cluster for PCI-DSS 3.2.1 - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets)
* Content Source: [docs/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by Naveenommi-MSFT** [comment]
@jiacfan 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017710
