### ISSUE TITLE
Grammatical error in Related resources section

### ISSUE THREAD

**Issue by shyamsundarb-arch** [MicrosoftDocs/architecture-center#3719]
![image](https://user-images.githubusercontent.com/6845982/196115127-d125a7c2-6b55-476b-8ec8-a83275d2b497.png)
There is a grammatical error in the highlighted sentence, which makes the description unclear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/event-sourcing)
* Content Source: [docs/patterns/event-sourcing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/event-sourcing.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by JananiRamesh-MSFT** [comment]
@shyamsundarb-arch Thanks for your feedback, we will review and update appropriately

**Comment by EdPrice-MSFT** [comment]
@shyamsundarb-arch 

The changes are live now. Please review.

https://learn.microsoft.com/en-us/azure/architecture/patterns/event-sourcing

**Comment by shyamsundarb-arch** [comment]
Done.
