### ISSUE TITLE
Business Central SaaS database architecture for reporting 

### ISSUE THREAD

**Issue by alexwiley** [MicrosoftDocs/architecture-center#3725]
Hello, I'm a MCP that has spent a large amount of time going through Learn resources, but haven't been able to get a complete confirmation on if my understanding of the architecture and request flow for reporting is correct. In my example below I'm focused on day to day business activity and access, omitting things like backups and fail safe duplicates which wouldn't be normally accessed.

Am I correct in my understanding that when a Business Central SaaS environment is created by either a Microsoft user, or a Partner for a user, the following happens:

A single Azure VM with a BC Server and web services is created ("A").
A single Azure VM with an Azure SQL Server is created ("B").
If the account has a Premium license (or certain level Office 365 license?), a read-only Managed Service type database copy is created in PowerApps Dataverse which reporting tools like PowerBI can call using a "read-only" request to save performance on "B" ("C").

If a reporting tool such as PowerBI/Jet queries a BC SaaS database and it either does not have a Premium license or the read-only parameter isn't used in the request, then it retrieves it from "B" and this can impact business performance for those users.

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfcc112-0a30-557c-bf69-738c45b325d8
* Version Independent ID: 9385c916-ec7c-2f12-390b-80d136a16cb7
* Content: [Dynamics Business Central as a service on Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/business-central)
* Content Source: [docs/solution-ideas/articles/business-central.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/business-central.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @altotovi
* Microsoft Alias: **altotovi**

**Comment by AjayBathini-MSFT** [comment]
@alexwiley 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by alexwiley** [comment]
Definitely. 
[The article which led me here](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/business-central). 

- Can we assume this is what happens when a US Microsoft user or Partner creates a new BC instance? 

- Also, in the section for Cost Optimization it states "It's important to note that the partner doesn't need a virtual machine for each customer. It can significantly reduce costs for middle-tier service (VM) by combining access and just changing ports." Where does a partner see and control this? 

For the reporting, in relation to the architecture above: 
[This page ](https://learn.microsoft.com/en-us/dynamics365/business-central/admin-data-access-intent)and [this page](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/database-read-scale-out-overview) discusses data access intent and read scale out saying "In the Business Central Online service, read scale-out is readily available and automatically enabled on the databases." However, none of these resources discuss where this replica exists. Is it a Dataverse database? Is it a copy within the SQL Server instance ("B" above)? How is the size of that database managed and what if any considerations are there for the GB data allowances from the licenses? What information is copied there and when is it updated? 

Thank you Ajay

**Comment by AjayBathini-MSFT** [comment]
@alexwiley 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by AjayBathini-MSFT** [comment]
@altotovi 
Can you please check and add your comments on this request as applicable.

**Comment by altotovi** [comment]
BC SaaS architecture is completely deployed and supported by Microsoft. This example is if you want to build your own BC on cloud environment, but not SaaS.




Regards,

Aleksandar Totovic



________________________________
From: AlexSocyl ***@***.***>
Sent: Wednesday, October 19, 2022 11:06
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Aleksandar Totovic ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/architecture-center] Business Central SaaS database architecture for reporting (Issue #3725)


Hello, I'm a MCP that has spent a large amount of time going through Learn resources, but haven't been able to get a complete confirmation on if my understanding of the architecture and request flow for reporting is correct. In my example below I'm focused on day to day business activity and access, omitting things like backups and fail safe duplicates which wouldn't be normally accessed.

Am I correct in my understanding that when a Business Central SaaS environment is created by either a Microsoft user, or a Partner for a user, the following happens:

A single Azure VM with a BC Server and web services is created ("A").
A single Azure VM with an Azure SQL Server is created ("B").
If the account has a Premium license (or certain level Office 365 license?), a read-only Managed Service type database copy is created in PowerApps Dataverse which reporting tools like PowerBI can call using a "read-only" request to save performance on "B" ("C").

If a reporting tool such as PowerBI/Jet queries a BC SaaS database and it either does not have a Premium license or the read-only parameter isn't used in the request, then it retrieves it from "B" and this can impact business performance for those users.

Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 8cfcc112-0a30-557c-bf69-738c45b325d8
  *   Version Independent ID: 9385c916-ec7c-2f12-390b-80d136a16cb7
  *   Content: Dynamics Business Central as a service on Azure - Azure Architecture Center<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fsolution-ideas%2Farticles%2Fbusiness-central&data=05%7C01%7CAleksandar.Totovic%40microsoft.com%7Ce31bc79e4d314dc8e38e08dab1b138cc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638017671992417347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B7eFpYFZhfMc0iNoqfeed5AKWmdllNkFxidibRxPzEY%3D&reserved=0>
  *   Content Source: docs/solution-ideas/articles/business-central.yml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftdocs%2Farchitecture-center%2Fblob%2Fmain%2Fdocs%2Fsolution-ideas%2Farticles%2Fbusiness-central.yml&data=05%7C01%7CAleksandar.Totovic%40microsoft.com%7Ce31bc79e4d314dc8e38e08dab1b138cc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638017671992417347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qZXQgKuyTYdLX7HosOaZ%2B3Dvbyv1%2BSSbsOAXUTx3ygU%3D&reserved=0>
  *   Service: architecture-center
  *   Sub-service: solution-idea
  *   GitHub Login: @altotovi<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltotovi&data=05%7C01%7CAleksandar.Totovic%40microsoft.com%7Ce31bc79e4d314dc8e38e08dab1b138cc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638017671992417347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BWR6uvZkL4IPTKZSCIs4Mmv4AnusS4h%2FwcVD%2FXUbSYw%3D&reserved=0>
  *   Microsoft Alias: altotovi

**Comment by alexwiley** [comment]
Thanks @altotovi , is there another resource somewhere for the SaaS architecture, or is that another thread/team? I'm trying to explain to upgrade customers how they can query and monitor their BC database; i.e. size of the replica database, can SQL queries be run against it, etc. I appreciate the guidance.

**Comment by altotovi** [comment]
Administration of Business Central Online - Business Central | Microsoft Learn<https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-administration>




Regards,

Aleksandar Totovic



________________________________

**Comment by alexwiley** [comment]
Thanks, I did read through at one point in my search. So is it then safe to assume based on all the resources here, I can tell customers with MS managed BC SaaS:
- It is not possible to perform a SQL query/report on the environment
- The replica database is a managed MS service, which goes towards their data usage, but it is not controlled or monitored by the customer or the partner, and is not accessible except through the prescribed read-only call to the exposed web service
