### ISSUE TITLE
Does enabling Auto-Upgrade for the node-image channel also automatically disable unattended-upgrade on Ubuntu nodes? 

### ISSUE THREAD

**Issue by lgodmer** [MicrosoftDocs/architecture-center#3726]
The Auto-Upgrade release channel for node-image upgrades is a great feature to be combined with planned maintenance scheduling to control image upgrades in a safe and timely manner. In order for this to be effective however, Azure Ubuntu image users need to also disable the default behavior of unattended-upgrades. Otherwise unattended-upgrades will continue to run outside the planned maintenance window and inhibit the safe and gradual rollout of image patches. The documentation is not clear on if the enablement of Auto-Upgrade of the node-image channel automatically disables unattended-upgrade or does the user need to take another step to add a vm extension to disable unattended-upgrade. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43da9bdf-a3d3-a65b-b555-60dcc5ac2c55
* Version Independent ID: 9913c705-aeb7-e154-4fdf-164ff1e7ff99
* Content: [AKS Day-2 - Patch and upgrade guidance - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-upgrade-practices)
* Content Source: [docs/operator-guides/aks/aks-upgrade-practices.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/operator-guides/aks/aks-upgrade-practices.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **pnp**

**Comment by mumurug-MSFT** [comment]
@lgodmer Thanks for the feedback. We will review and update as appropriate.

**Comment by ckittel** [comment]
@rishabhsaha -- can you please address this question on your article?

**Comment by v-fearam** [comment]
Hi @lgodmer

Sorry for the delay. 


[If using the node-image cluster auto-upgrade channel or the NodeImage node image auto-upgrade channel, Linux unattended upgrades will be disabled by default.](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-cluster#cluster-auto-upgrade-limitations)


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
