### ISSUE TITLE
API Manager

### ISSUE THREAD

**Issue by Escoto** [MicrosoftDocs/architecture-center#3727]
Is it possible to update this document to include API Manager?

I found this article coming from [this post](https://learn.microsoft.com/en-us/answers/questions/35787/what-is-difference-between-api-gateway-provided-by.html) where [Pramod Valavala Microsoft Employee](https://learn.microsoft.com/en-us/users/pramodvalavala-msft/) does a great job comparing these services and, I was hoping to get more details on that topic.

Maybe API Manager wouldn't fit within `Load-balancing`, but maybe a new article, with a deep dive on **Front Door** vs **API Manager** vs **Application Gateway** would be really nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mumurug-MSFT** [comment]
@Escoto Thanks for the feedback. We will review and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37521 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
