### ISSUE TITLE
Replace Windows Virtual Desktop with Azure Virtual Desktop 

### ISSUE THREAD

**Issue by kumarallamraju** [MicrosoftDocs/architecture-center#3729]
[Enter feedback here]

There are still some references to WVD.
Replace Windows Virtual Desktop with Azure Virtual Desktop 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Azure Virtual Desktop for the enterprise - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by YashikaTyagi-MSFT** [comment]
@kumarallamraju 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017709

**Comment by JanetCThomas** [comment]
This issue has been resolved.
