### ISSUE TITLE
Unclear phrasing

### ISSUE THREAD

**Issue by zissbilloutlook** [MicrosoftDocs/architecture-center#3730]
"Federated authentication provides a standards-based solution to the issue of trusting identities across diverse domains, and can support single sign-on. _It's becoming more common across all types of applications, especially cloud-hosted applications, because it supports single sign-on without requiring a direct network connection to identity providers._ "

Italicized sentence is desperately unclear.  Who/what doesn't need to directly connect to identity providers?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4943e185-fb94-576a-d0a1-2cfefd0d0f96
* Version Independent ID: a9a5a4b7-887c-c298-f720-49ed6abaa575
* Content: [Federated Identity pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/federated-identity)
* Content Source: [docs/patterns/federated-identity.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/federated-identity.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@zissbilloutlook 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017700

**Comment by JanetCThomas** [comment]
This issue has been resolved.
