### ISSUE TITLE
Contextually ambiguous use of pronoun.

### ISSUE THREAD

**Issue by zissbilloutlook** [MicrosoftDocs/architecture-center#3731]
"If there's more than one identity provider configured for the STS, **_it_** must detect which identity provider the user should be redirected to for authentication. "

What is "it"?  The STS, the first point of contact within the Federated Identity implementation, some other thing?

I strongly suggest that you hire professional editors to clarify your writing and strip off unneeded verbiage.  You make your readers work waaay to damned hard.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4943e185-fb94-576a-d0a1-2cfefd0d0f96
* Version Independent ID: a9a5a4b7-887c-c298-f720-49ed6abaa575
* Content: [Federated Identity pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/federated-identity)
* Content Source: [docs/patterns/federated-identity.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/federated-identity.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@zissbilloutlook 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017700

**Comment by JanetCThomas** [comment]
This issue has been resolved.
