### ISSUE TITLE
Horrid writing

### ISSUE THREAD

**Issue by zissbilloutlook** [MicrosoftDocs/architecture-center#3732]
"Applications expose their functionality to clients by accepting and processing requests. In cloud-hosted scenarios, applications expose endpoints clients connect to, and typically include the code to handle the requests from clients. **This code** performs authentication and validation, some or all request processing, and is likely to access storage and other services on behalf of the client."

The first two sentences are completely unneeded babble-wankery that distracts the reader and drains their energy.

Sentence three is almost useless because "This code" is ambiguous to all but the best guessers.  "This code" might refer to the Gatekeeper.......right?  Or is it client code, in that "client" is the closest specifier.  The cloud-hosted (as if it would be anywhere else) service is also a candidate.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 428e4625-191f-a050-ec58-60fd2dddff86
* Version Independent ID: 3a4e385e-5761-3633-1ddf-46e1878b420d
* Content: [Gatekeeper pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/gatekeeper)
* Content Source: [docs/patterns/gatekeeper.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/gatekeeper.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@zissbilloutlook 
Thanks for your feedback! We will investigate and update as appropriate.
