### ISSUE TITLE
"trusted hosts"

### ISSUE THREAD

**Issue by zissbilloutlook** [MicrosoftDocs/architecture-center#3733]
Why on earth are you introducing the phrase "trusted hosts" in this context?  Bad writing.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 428e4625-191f-a050-ec58-60fd2dddff86
* Version Independent ID: 3a4e385e-5761-3633-1ddf-46e1878b420d
* Content: [Gatekeeper pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/gatekeeper)
* Content Source: [docs/patterns/gatekeeper.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/gatekeeper.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@zissbilloutlook 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by hallihan** [comment]
@zissbilloutlook I believe "trusted hosts" was used to convey a generic idea that the hosts behind the gatekeeper have an elevated security posture, without locking in to any specific implementation. Is there something specific that you feel the term "trusted hosts" is implying here that adds confusion? Would it make more sense to call them "isolated hosts" or "protected hosts"?

**Comment by v-fearam** [comment]
I will close the ticket, but feel free to re-open

**Comment by v-fearam** [comment]
#please-close
