### ISSUE TITLE
The Front Door + Azure Load balancer doesn’t support HTTP/S protocol 

### ISSUE THREAD

**Issue by idakir** [MicrosoftDocs/architecture-center#3740]
In the flowchart, the option of Azure Front Door + Azure Load Balancer is wrong , the Azure load balancer doesn’t support HTTP/S protocol 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by idakir** [comment]
Azure Load Balancer is layer 4 support only TCP/UDP protocol

**Comment by v-fearam** [comment]
Hi @idakir

Sorry for the delay. 

On a network stack, each intermediate layer serves a class of functionality to the layer above it and is served by the layer below it. On the [TCP/IP stack](https://en.wikipedia.org/wiki/Internet_protocol_suite), the HTTPS is served by TCP. TCP is served by IP.

Azure load balancer works at TCP/IP level, but the HTTPS travels inside TCP packages. It is valid The Front Door + Azure Load balancer. What changes is the way to describe the rules.


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
