### ISSUE TITLE
incorrect "tradeoff" example

### ISSUE THREAD

**Issue by aihorko** [MicrosoftDocs/architecture-center#3741]
On page https://learn.microsoft.com/en-us/azure/architecture/reliability/architect there's a phrase: 
"there's a tradeoff between greater redundancy and reliability versus higher costs and complexity."
Tradeoff is used for opposites (thus the word versus), but opposites from this example "greater redundancy and reliability" and "higher costs and complexity" are not opposites, but vice versa - "greater redundancy and reliability" leads to "higher costs and complexity". For opposites need to use "lower costs and complexity". So that, we have either "greater redundancy and reliability" (with higher cost and complexity) or we have "lower cost and complexity" (with less redundancy and reliability)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7045e916-4244-f7fa-c147-fb4a0ddc15f6
* Version Independent ID: 78e0c541-b257-f253-e1ca-e9ea7c8e7a76
* Content: [Architecting for resiliency and availability - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reliability/architect)
* Content Source: [docs/reliability/architect.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reliability/architect.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.
