### ISSUE TITLE
Matriz de cosechas

### ISSUE THREAD

**Issue by lokuas15** [MicrosoftDocs/architecture-center#3751]
Como se podria hacer una matriz de cosechas en sql server?

**Comment by AjayBathini-MSFT** [comment]
@lokuas15 
Could you please elaborate you query.
And also, it would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by AjayBathini-MSFT** [comment]
@lokuas15 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
