### ISSUE TITLE
What devops pipeline task represents extractor workflow, are there any specific details on how this process is achieved?

### ISSUE THREAD

**Issue by michaelhui8** [MicrosoftDocs/architecture-center#3759]
What devops pipeline task represents extractor workflow, are there any specific details on how this process is achieved?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Version Independent ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Content: [Automated API deployments using APIOps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops)
* Content Source: [docs/example-scenario/devops/automated-api-deployments-apiops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/automated-api-deployments-apiops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **risaha**

**Comment by rishabhsaha** [comment]
Hi - a E2E implementation of this pattern can be found here. Have you taken a look at this?

https://azure.github.io/apiops/

**Comment by Naveenommi-MSFT** [comment]
@michaelhui8 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
@v-fearam has pushed an update to this article that should be live within 24 that will also include this information.
