### ISSUE TITLE
Exposing external API's to internal consumers

### ISSUE THREAD

**Issue by sayedimac** [MicrosoftDocs/architecture-center#3764]
I am a technical trainer with the ESI program and I always talk through two use cases with regards to APIM.

The one, which is what this architecture is about, is publishing internal API's for external consumption. 
The other, is protecting and wrapping external API's for internal consumption.
For example, if your org is using the Twitter API, you might not want to give the Twitter keys for the Twitter API to all internal departments that want to use the Twitter API so you can create the Facade for Twitter and expose it internally which is kind of the opposite of this architecture where the consumers are external. Now it might sound like it is very similar to this one, but in fact it is not the same use case at all.

This is a great use case because it allows you to manage the consumption of external API's and control that with the policies you might want to use. So for example, the Marketing DEPT might pay for Twitter API usage and hence requests from there might use the paid for API keys for Twitter, but the IT dept might not and might hence only be allowed to use the free API calls. You can control all that with APIM.
My suggestion is obviously not to change this page, but I think it would be worth creating another architecture for this scenario.
Let me know if you want me to help with that, I would be happy to! Alos happy to jump on a call to chat about this (jomyburg@microsoft.com).

 - Johan 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb14c845-07c9-0fe2-0108-119b7e913b35
* Version Independent ID: c3fdc7ba-6743-33a6-d41d-3328e2e22e93
* Content: [Publish internal APIs to external users - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/publish-internal-apis-externally)
* Content Source: [docs/example-scenario/apps/publish-internal-apis-externally.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/publish-internal-apis-externally.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ssarwa
* Microsoft Alias: **ssarwa**

**Comment by mumurug-MSFT** [comment]
@sayedimac Thanks for the feedback. Assigning to author to review and update.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37501 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
