### ISSUE TITLE
Azure File Sync / Use Case

### ISSUE THREAD

**Issue by johnwildes** [MicrosoftDocs/architecture-center#3765]
Specifically regarding this paragraph below.  Is the use case an EITHER / OR scenario.  Either I use direct mount OR I use Azure File Sync and cache the azure files?

For example, I have Azure Virtual Desktop environment, in Azure on same VNET as azure files account.  I can direct mount this from within Azure with no problem.  If I have an on prem set of workers, and I put an azure file sync in their office, and they connect to that.  Will they see files that are created directly at the file share (and have them synched down) or will they not see them because they didn't originate on the cache server? 

This seems to indicate that it is an OR scenario.  You want to do one OR the other, but not BOTH. 

> Azure Files usage and deployment
You store your files in the cloud in Azure file shares. You can use Azure file shares in two ways: by directly mounting these serverless Azure file shares (SMB) or by caching Azure file shares on-premises using Azure File Sync. The deployment option you choose changes what you need to consider as you plan for your deployment:

> Direct mount of an Azure file share. Because Azure Files provides SMB access, you can mount Azure file shares on-premises or in the cloud using the standard SMB client available in the Windows, macOS, and Linux operating systems. Azure file shares are serverless, so deploying for production scenarios doesn't require managing a file server or network-attached storage (NAS) device. This means you don't have to apply software patches or swap out physical disks.
Cache Azure file share on-premises with Azure File Sync. Azure File Sync enables you to centralize your organization's file shares in Azure Files, while keeping the flexibility, performance, and compatibility of an on-premises file server. Azure File Sync transforms an on-premises (or cloud) Windows Server into a quick cache of your Azure file share.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0c41223-d1f5-636c-3902-8d333543dd0e
* Version Independent ID: 3708ea4f-c677-a576-d088-7b096c24e415
* Content: [Hybrid file services - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/hybrid/hybrid-file-services)
* Content Source: [docs/hybrid/hybrid-file-services.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/hybrid-file-services.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by v-fearam** [comment]
Hi @johnwildes

Sorry for the delay. 

The document was changed after the time you had created the ticket. I feel the current paragraph is more clear. 

I will close the ticket, but feel free to open a new one if you still have concerns.

**Comment by v-fearam** [comment]
#please-close
