### ISSUE TITLE
Please give me java example 

### ISSUE THREAD

**Issue by abhinav-jain09** [MicrosoftDocs/architecture-center#3766]
[Enter feedback here]
The example for this page is only for .Net do you have example for Java as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/async-request-reply.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by RamanathanChinnappan-MSFT** [comment]
@abhinav-jain09
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
@abhinav-jain09 we do not currently have any java examples, nor is it in our backlog currently.  If you happen to come across any in the Microsoft content ecosystem, please let us know and we can link to it as a short term measure.

@dominicallen -- consider this a content request to cover java in some of our core architecture patterns, not just .NET.  This has been a request in the past as well.  Our engineers created many of the .NET ones, and creating java ones as well would be possible if deemed worth the creation and maintenance effort.
