### ISSUE TITLE
Gateway in front of APIM - why - what capability that Gateway has that APIM does not?

### ISSUE THREAD

**Issue by codeputer** [MicrosoftDocs/architecture-center#3767]
What is the purpose of the gateway in front of the APIM? I feel if its there to address a business reason than that should be stated in 
why that reason caused the gateway to be in front. Otherwise, I would give this diagram as two alternatives - one with the gateway, the other without and why both may be used for different purposes.

My understanding is that APIM has policies to apply when traffic arrives, while the gateway is perhaps a lower-level requirement in terms of the network topology.  As a cloud solution architect, I try to NOT think of my implementations at that level, as like I say, Serverless needs to be about thinking of servers (and low level infrastructure) less, and think of PaaS almost exclusively.

Regards,
Richard

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/apis/protect-apis)
* Content Source: [docs/reference-architectures/apis/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/apis/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **fabriciosanchez**

**Comment by RamanathanChinnappan-MSFT** [comment]
@codeputer 

Thanks for your feedback! We will investigate and update as appropriate.
