### ISSUE TITLE
What about Security Monitoring?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3769]
There is no mention of security event monitoring. Please add some content about how Microsoft Sentinel should be used to monitor AKS. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47583913-d1e3-7169-8a91-ac90281d4091
* Version Independent ID: 47583913-d1e3-7169-8a91-ac90281d4091
* Content: [Kubernetes monitoring and logging - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/aws-professional/eks-to-aks/monitoring)
* Content Source: [docs/aws-professional/eks-to-aks/monitoring.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/eks-to-aks/monitoring.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ketan-chawda-msft
* Microsoft Alias: **kechaw**

**Comment by Naveenommi-MSFT** [comment]
@DeanGross 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
