### ISSUE TITLE
This page is not linked to an entry in the TOC on the left hand side

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/architecture-center#3775]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f14bdf5c-81b0-76df-4c61-3b4eca2435ae
* Version Independent ID: 433531d0-bedf-ce5c-a747-ce1d6b6bea5f
* Content: [Resiliency checklist for services - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/checklist/resiliency-per-service)
* Content Source: [docs/checklist/resiliency-per-service.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/checklist/resiliency-per-service.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mumurug-MSFT** [comment]
@ciufudean Thanks for the feedback. We will review and update as appropriate.

**Comment by RobBagby** [comment]
Fixed issue.
