### ISSUE TITLE
This page is not linked to an entry in the TOC on the left hand side

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/architecture-center#3776]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7045e916-4244-f7fa-c147-fb4a0ddc15f6
* Version Independent ID: 78e0c541-b257-f253-e1ca-e9ea7c8e7a76
* Content: [Architecting for resiliency and availability - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reliability/architect)
* Content Source: [docs/reliability/architect.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reliability/architect.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by mumurug-MSFT** [comment]
@ciufudean Thanks for the feedback. We will review and update as appropriate.

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017698

**Comment by JanetCThomas** [comment]
This issue has been resolved.
