### ISSUE TITLE
Please share the VISIO file for this azure architecture

### ISSUE THREAD

**Issue by sm00823749** [MicrosoftDocs/architecture-center#3777]
[Enter feedback here]

Hi Team , Please share the VISIO file for this azure architecture.

Thanks and Regards,
 Shibnath Mukherjee

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14acf440-88ed-186c-a3ab-5309bf7e363c
* Version Independent ID: d32e5eb7-5011-dc40-e978-c6bc9f6363a5
* Content: [DevTest and DevOps for microservice solutions - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/dev-test-microservice)
* Content Source: [docs/solution-ideas/articles/dev-test-microservice.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/dev-test-microservice.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
Sure thing @sm00823749, you can find it at https://arch-center.azureedge.net/dev-test-microservice.vsdx and we've also included that link in the article itself for other folks like yourself looking for it.

#please-close
