### ISSUE TITLE
Virtual Network Info Is Outdated and Useless

### ISSUE THREAD

**Issue by SharmainePopov** [MicrosoftDocs/architecture-center#3778]
Hi the Virtual Network section links to docs from 2016 for CLASSIC vnet CREATION. What is required are docs for Resource Manager vNet deployment that show how to export/import vNet configuration. Additionally, vNets  have related components - eg route tables and user defined routes, vNet peering, private endpoints, DNS configs. The situation for those needs to be documented as well.  There also needs to be a specific section to address the case of the network hub in the platform landing zone.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b31c85c7-c25d-897f-e52d-789f7306457b
* Version Independent ID: 969106a5-df35-afef-5afc-96a26c970f44
* Content: [Recover from loss of an Azure region - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/resiliency/recovery-loss-azure-region)
* Content Source: [docs/resiliency/recovery-loss-azure-region.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/resiliency/recovery-loss-azure-region.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @adamglick
* Microsoft Alias: **pnp**

**Comment by SaibabaBalapur-MSFT** [comment]
@SharmainePopov 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
