### ISSUE TITLE
Architecture diagram: wrong visio file for MDM integration pipeline

### ISSUE THREAD

**Issue by praveenpb27** [MicrosoftDocs/architecture-center#3779]
Wrong visio file is getting downloaded for the Architecture diagram of MDM integration pipeline in the link https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-data-factory 
Even though the Visio diagram is linked, when downloaded it is not this diagram that is getting downloaded. Could you please upload the correct diagram for this section?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6724a3b3-3c90-3f27-a51d-454819e88f37
* Version Independent ID: 0c1b3984-7fbd-70ab-98e1-a2bb7697876b
* Content: [Profisee MDM and Azure Data Factory - Azure Architectures](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/data/profisee-master-data-management-data-factory)
* Content Source: [docs/reference-architectures/data/profisee-master-data-management-data-factory.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/data/profisee-master-data-management-data-factory.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **Sunil.Sabat**

**Comment by SaibabaBalapur-MSFT** [comment]
@praveenpb27 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by hallihan** [comment]
Both of the Visio links are to the same download.  The `MDM integration pipeline` diagram can be found on page 2 of the download.
