### ISSUE TITLE
Dados

### ISSUE THREAD

**Issue by moises77filipe** [MicrosoftDocs/architecture-center#3781]
Sensacional!
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: fcb3c6d7-aa3e-9a76-181b-d0963ac685b9
* Version Independent ID: da9c883b-93bf-8864-015a-a7b10a6fcb5f
* Content: [ETL (extrair, transformar e carregar) - Azure Architecture Center](https://learn.microsoft.com/pt-br/azure/architecture/data-guide/relational-data/etl)
* Content Source: [docs/data-guide/relational-data/etl.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/relational-data/etl.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @raunakjhawar
* Microsoft Alias: **rajhawar**

**Comment by ManoharLakkoju-MSFT** [comment]
@moises77filipe 
Thanks for your feedback! We will investigate and update as appropriate.

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by skabou** [comment]
It is unclear what is needed, if assistance is needed, please re-open with additional information.
