### ISSUE TITLE
Copy/paste error in Visio

### ISSUE THREAD

**Issue by HendrikTilleman** [MicrosoftDocs/architecture-center#3785]
The architecture Visio contains 2 SharePoint VMs in the source site, while the failover site only has 1 SharePoint VM but has an additional DNS server which is not visualized on-prem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 018a7aef-3117-17c5-8693-7455cefa54d3
* Version Independent ID: a6c4e7a0-3cfa-1c4c-bc48-6281c870b035
* Content: [Enterprise-scale disaster recovery - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/disaster-recovery-enterprise-scale-dr)
* Content Source: [docs/solution-ideas/articles/disaster-recovery-enterprise-scale-dr.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/disaster-recovery-enterprise-scale-dr.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@HendrikTilleman 
Thanks for your feedback! We will investigate and update as appropriate.
