### ISSUE TITLE
Images are blurry and not clear enough 

### ISSUE THREAD

**Issue by jayendranarumugam** [MicrosoftDocs/architecture-center#3786]
The Images provided in the [doc](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/teams/securing-bot-teams-channel) are blurry we cannot even zoom and see it through clearly . Especially 
[securing-bot-image-011.png](https://github.com/MicrosoftDocs/architecture-center/blob/main/docs/example-scenario/teams/media/securing-bot-image-011.png)
[securing-bot-image-010.png](https://github.com/MicrosoftDocs/architecture-center/blob/main/docs/example-scenario/teams/media/securing-bot-image-010.png)
[securing-bot-image-009.png](https://github.com/MicrosoftDocs/architecture-center/blob/main/docs/example-scenario/teams/media/securing-bot-image-009.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62849df7-a49c-f17e-6876-c3da5954789a
* Version Independent ID: a412df8a-f876-d501-6aec-5bc1f010deaa
* Content: [Secure your Microsoft Teams channel bot and web app behind a firewall - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/teams/securing-bot-teams-channel)
* Content Source: [docs/example-scenario/teams/securing-bot-teams-channel.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/teams/securing-bot-teams-channel.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ajafry
* Microsoft Alias: **aljafry**

**Comment by mumurug-MSFT** [comment]
@jayendranarumugam Thanks for the feedback and sorry for the experience. We have assigned this issue to doc author, and we will review and update as appropriate.

**Comment by skabou** [comment]
It appears this issue has been addressed.  If you are still experiencing an issue, please re-open with additional information.
