### ISSUE TITLE
Why move old records from Cosmos DB to Data Lake?

### ISSUE THREAD

**Issue by blodgettb** [MicrosoftDocs/architecture-center#3793]
You wrote, "The records don't need to stay in Azure Cosmos DB indefinitely. Older deliveries can be archived — say, after a month."
Please elaborate on why one would move old records from Cosmos DB to Data Lake. Is Data Lake storage less expensive? Is analysis less expensive in Data Lake? Does Data Lake have features lacking or less convenient in Cosmos DB?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb25545c-958f-99b0-b321-74e556ad4557
* Version Independent ID: ebe36da6-a15f-f981-787d-8aa4307451a2
* Content: [Data considerations for microservices - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/microservices/design/data-considerations)
* Content Source: [docs/microservices/design/data-considerations.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/design/data-considerations.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@blodgettb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close

**Comment by blodgettb** [comment]
I see no changes to the article. Please answer my questions:
Please elaborate on why one would move old records from Cosmos DB to Data
Lake. Is Data Lake storage less expensive? Is analysis less expensive in
Data Lake? Does Data Lake have features lacking or less convenient in
Cosmos DB?
Thank you,
Bruce Blodgett

**Comment by hallihan** [comment]
@blodgettb There can be a slight delay between when we make a change to the article, and when that change is reflected on the site.  The following text was added to the article section you referenced: "Archiving older data can reduce costs for Cosmos DB while still keeping the data available for historical reporting from the Data Lake."

**Comment by blodgettb** [comment]
1. I now see the additional sentence on the web site, thank you.
2. The implication now is that Data Lake is less expensive than Cosmos DB.
To save your readers from having to do the research, I would appreciate an
explicit statement to that effect.
For example: "Archiving older data can reduce costs for Cosmos DB *($0.25
GB/month)* while still keeping the data available for historical reporting
from the Data Lake*, where storage is less expensive ($0.15 GB/month)*."
Please correct my numbers if I got them wrong. Here are my sources:
a. The cost for storage in Azure Cosmos DB is $0.25 GB/month, see Pricing
page <https://azure.microsoft.com/pricing/details/cosmos-db/> for latest
updates.
b. Data Lake storage
PremiumHotCoolArchive
First 50 terabyte (TB) / month $0.15 per GB $0.0208 per GB $0.0152 per GB
$0.00099 per GB
Next 450 TB / month $0.15 per GB $0.02 per GB $0.0152 per GB $0.00099 per GB
Over 500 TB / month $0.15 per GB $0.0191 per GB $0.0152 per GB $0.00099 per
GB

**Comment by hallihan** [comment]
We generally try not to put specific pricing information in the Azure Architecture Center. The pricing can vary by region and change over time. Additionally, specific implementation details and access patterns can change the resulting pricing.  This article is intended to introduce the concepts that you need to consider, but settling on specifics will require looking at other details like product documentation and pricing information.

**Comment by blodgettb** [comment]
1. If you refuse to put pricing, at least explicitly say that Data Lake
storage is less expensive than Cosmos DB storage. Otherwise, there is no
point in going through the trouble of moving data from one to the other.
2. I still think you should follow the example of this other page where you
DO have specific pricing information and a link to the pricing page:
https://learn.microsoft.com/en-us/azure/cosmos-db/optimize-cost-storage

The cost for storage in Azure Cosmos DB is $0.25 GB/month, see Pricing page
<https://azure.microsoft.com/pricing/details/cosmos-db/> for latest updates.

Here are the pricing pages for Cosmos DB and Data Lake (which you could
reference):

   -
   https://azure.microsoft.com/en-us/pricing/details/cosmos-db/autoscale-provisioned/
   - https://azure.microsoft.com/en-us/pricing/details/storage/data-lake/

Bruce Blodgett
(603) 438-2267 <http://voice.google.com/calls?a=nc,%2B16034382267>
