### ISSUE TITLE
Page makes no mention of minimum Disk bandwidth requirements from SAS

### ISSUE THREAD

**Issue by cowhitley** [MicrosoftDocs/architecture-center#3794]
Per SAS documentation, they recommend at least 150 MBPS bandwidth https://communities.sas.com/t5/Administration-and-Deployment/Best-Practices-for-Using-Microsoft-Azure-with-SAS/m-p/676833#M19680

Our documentation makes no mention of this requirement which can only be achieved with using Premium P20 disks or greater.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1263da59-b247-1de4-1357-0a549c67d41e
* Version Independent ID: 9c43e47e-1336-bd17-780c-36e456778816
* Content: [SAS on Azure architecture - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/sas/sas-overview)
* Content Source: [docs/guide/sas/sas-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/sas/sas-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ranieuwe
* Microsoft Alias: **ronieuwe**

**Comment by ManoharLakkoju-MSFT** [comment]
@cowhitley 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ranieuwe** [comment]
The 150MB/s requirement as put down by Margaret refers to the part of the SAS system where data is being persisted. This would only be local in a single node SAS deployment. In that case, the guidance of Margaret applies and you need to stripe multiple P30 (or larger) disks to meet the requirements. 

In the architecture published on the architecture center we are not persisting any data on the machines instead opting to use an externalized file system such as Lustre, NFS or GPFS. 

Most architectures need that kind of approach. I agree with you though, that in case of a scale up scenario (vs out) it may be useful to have this documented and to make it clear our guidance applies to scale out. 

@grtn316 thoughts?

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2034091

**Comment by JanetCThomas** [comment]
This issue has been addressed in https://github.com/MicrosoftDocs/architecture-center-pr/pull/9695. 
Published URL" [SAS on Azure architecture - Azure Architecture Center | Microsoft Learn](https://learn.microsoft.com/en-us/azure/architecture/guide/sas/sas-overview)
