### ISSUE TITLE
Private endpoints wording

### ISSUE THREAD

**Issue by wenms1** [MicrosoftDocs/architecture-center#3795]
"There's no added cost for App Service regional VNet Integration in a supported pricing tier of Standard or higher. But Private Endpoints for Web Apps is supported only on Elastic Premium, Premium V2, and Premium V3 plans."

I think it supports all plans now. Is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5253ae20-9f16-817d-1a24-f4adae76abf4
* Version Independent ID: 5253ae20-9f16-817d-1a24-f4adae76abf4
* Content: [Improved-security access to multitenant web apps from an on-premises network - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/security/access-multitenant-web-app-from-on-premises?utm_source=pocket_reader)
* Content Source: [docs/example-scenario/security/access-multitenant-web-app-from-on-premises.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/security/access-multitenant-web-app-from-on-premises.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ansingha
* Microsoft Alias: **ansingha**

**Comment by YashikaTyagi-MSFT** [comment]
@wenms1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ansingha** [comment]
**This should be updated:**
_"There's no added cost for App Service regional VNet Integration in a supported pricing tier of Standard or higher. But Private Endpoints for Web Apps is supported only on Elastic Premium, Premium V2, and Premium V3 plans."_

**to the following:**
"There's no added cost of App Service regional VNet Integration feature:
- In a supported pricing tier of these App Service plans: Basic, Standard, Premium v2, or Premium v3 
- In the supported plan of Function Apps: Premium plan

Private Endpoint is available for Windows and Linux Web App, containerized or not, hosted on Basic, Standard, Premium v2, Premium v3 and Isolated v2 App Service Plans and also for Function apps deployed to a Premium plan."
