### ISSUE TITLE
https://aka.ms/tryworkbench is not valid

### ISSUE THREAD

**Issue by huangyingting** [MicrosoftDocs/architecture-center#3798]
The link in below is not valid anymore, when access it, it gives 404
Deploy this scenario
[Deploy to Azure](https://aka.ms/tryworkbench)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed7b54c-fe6b-4331-f6d4-1e369ebad0c1
* Version Independent ID: 70f614a9-153c-3a7e-107c-526ba68adad6
* Content: [Supply chain track and trace - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/supply-chain-track-and-trace)
* Content Source: [docs/solution-ideas/articles/supply-chain-track-and-trace.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/supply-chain-track-and-trace.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
Thank you for noticing this.  We have updated this link now to https://azuremarketplace.microsoft.com/marketplace/consulting-services/akvelon.azure_blockchain_workbench and removed the aka.ms link.

#please-close
