### ISSUE TITLE
Cluster set is not supported in Stack HCI

### ISSUE THREAD

**Issue by MikeWedderburn-Clarke** [MicrosoftDocs/architecture-center#3803]
Please remove the reference to 'cluster set' as this is not supported by Stack HCI. We have had clarification from PG that they do not support cluster set with Stack HCI and they have removed those references from the Stack HCI docs but it still exists in this one.

See the internal thread 'Does "Deploy a cluster set"  support  AS HCI ' in 'hcitalk' for reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd80767-6e29-65b6-4b98-42d36bd3ad33
* Version Independent ID: 7fc8bbde-f74a-74f7-f93e-de7660df740c
* Content: [Use Azure Stack HCI stretched clusters for disaster recovery - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/hybrid/azure-stack-hci-dr)
* Content Source: [docs/hybrid/azure-stack-hci-dr.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/azure-stack-hci-dr.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by EdPrice-MSFT** [comment]
@MikeWedderburn-Clarke - Please review.

https://github.com/MicrosoftDocs/architecture-center-pr/pull/9089/files

FYI @ckittel @josevarela

**Comment by EdPrice-MSFT** [comment]
Merged. Should be live tomorrow.
