### ISSUE TITLE
Azure Nov. 2022 icon is not up to date, are missing : ASA, ACA, ARO, Fleet

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#3804]
[https://arch-center.azureedge.net/icons/Azure_Public_Service_Icons_V10.zip](https://arch-center.azureedge.net/icons/Azure_Public_Service_Icons_V10.zip) Nov. 2022 is not up to date : 

- compute/10370-icon-service-Azure-Spring-Cloud.svg should be renamed Azure Spring Apps, see [https://github.com/MicrosoftDocs/azure-docs/issues/95119](https://github.com/MicrosoftDocs/azure-docs/issues/95119)

- Azure Container Apps icon should be added to Icons\containers
- Azure RedHat OpenShift icon should be added to Icons\containers
- [Azure Kubernetes Fleet Manager](https://azure.microsoft.com/products/kubernetes-fleet-manager/) icon should be added to Icons\containers
- ACA Env. is hidden at new icons\02989-icon-service-Container-App-Environments.svg
- There is 10024-icon-service-Mesh-Applications.svg wheras Open Service Mesh OSM icon should be added

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by SaibabaBalapur-MSFT** [comment]
@ezYakaEagle442 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by hallihan** [comment]
Hi @ezYakaEagle442  - I think some of these may have been fixed with the January update. If there are still omissions, there is an email address listed in the `Azure_Icons_FAQ.pdf` file where you can send feedback.
