### ISSUE TITLE
My computer screen is dim

### ISSUE THREAD

**Issue by walezbee** [MicrosoftDocs/architecture-center#3805]
I tried to open one of the icons. This turned my computer system to screenshot mode. The screen is dim and I can't work efficiently.

Kindly assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by SaibabaBalapur-MSFT** [comment]
@walezbee 
Thanks for your feedback! We will investigate and update as appropriate.
