### ISSUE TITLE
Article has no date :/

### ISSUE THREAD

**Issue by tobm** [MicrosoftDocs/architecture-center#3807]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@tobm 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MughundhanRaveendran-MSFT** [comment]
@tobm , Which date are you referring to? The date on which the article was published?

**Comment by MughundhanRaveendran-MSFT** [comment]
@tobm , Did you get a chance to look at my previous comment?

**Comment by tobm** [comment]
Sorry for the delay,
if you look at the "sibling article" at 
https://learn.microsoft.com/en-us/azure/architecture/microservices/design/compute-options
then it has a date at the top, thats what I'm missing. 

Motivation: Based on the pace that cloud moves in, where new services & major updates ect are happening on a quaterly (if not monthly) basis, when reading through an article like the on referreded to, its imho extremely important to know "Am I looking at an overview thats 14 months old or ????", _especailly_ since is an overview :)

**Comment by EdPrice-MSFT** [comment]
All our diagram articles have no date. Basically, everything on AAC that's listed here: http://aka.ms/Archirecture 

That's the limitation of the platform.
