### ISSUE TITLE
Stub out and save Azure Pricing Calculator estimates for all reference architectures and link to article

### ISSUE THREAD

**Issue by kinseymd** [MicrosoftDocs/architecture-center#3808]
I would love to have a sample Azure Pricing Calculator estimate available for each of the reference architectures. I love the Architecture Center and it's my first place to start when designing for a workload. Having even a starting point where I can tweak the settings for each would be a big timesaver. Just stub out a default entry for every resource on the reference architecture diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b04b7b7-e4dc-575e-135f-ccb3678badc6
* Version Independent ID: 0b04b7b7-e4dc-575e-135f-ccb3678badc6
* Content: [Highly available zone-redundant web application - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/zone-redundant)
* Content Source: [docs/reference-architectures/app-service-web-app/zone-redundant.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/zone-redundant.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @DanielLarsenNZ
* Microsoft Alias: **dalars**

**Comment by DanielLarsenNZ** [comment]
Hi @kinseymd, 

Thank you for your feedback. I assume you have already found the Azure pricing calculator estimate for Highly available zone-redundant web apps [here](https://azure.com/e/3aeac3eda5d44a85baea8d335ce23772)?

Including a pricing calculator estimate is now a requirement for new Azure reference architectures going forward, and I assume authors will be asked to add them as older references are refreshed.

**Comment by kinseymd** [comment]
Thanks for your email Daniel!
Is this link included in the respective article? Apologies if it is but I
couldn’t find it.
To be honest I didn’t read through the article in detail but I did skim it
and search for ‘price’ and ‘pric’ (like pricing) and didn’t find a link.

**Comment by SaibabaBalapur-MSFT** [comment]
@kinseymd 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by kinseymd** [comment]
This is my bad…I searched again this morning and found the “example bill of
materials…” near the bottom of this article.

Thanks for your prompt response!

**Comment by DanielLarsenNZ** [comment]
Glad you found it @kinseymd :)

@SaibabaBalapur-MSFT please close 👍
