### ISSUE TITLE
All links to application landing zones are broken

### ISSUE THREAD

**Issue by reduards** [MicrosoftDocs/architecture-center#3809]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75727ca9-f46f-24a6-3871-25cc45b61de8
* Version Independent ID: 75727ca9-f46f-24a6-3871-25cc45b61de8
* Content: [Deploy Azure landing zones - Azure Architecture Center](https://review.learn.microsoft.com/en-us/azure/architecture/landing-zones/landing-zone-deploy?branch=pr-en-us-8817)
* Content Source: [docs/landing-zones/landing-zone-deploy.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/landing-zones/landing-zone-deploy.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by SaibabaBalapur-MSFT** [comment]
@reduards 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
I reached out to @reduards on Teams to confirm the experience on the `review.` link that is referenced here, and expected behavior.  He'll close if he can confirm this was the problem.

**Comment by reduards** [comment]
Hello, yes review was the issue. Thanks, I will close the issue.
