### ISSUE TITLE
domain analysis - drone sharing in bounded context map

### ISSUE THREAD

**Issue by bhopkinson** [MicrosoftDocs/architecture-center#3811]
Reading through this document, it is not clear how drone sharing, which previously had a relationship with drone management, ended up with a relationship to accounts in the bounded context map.

Is the bounded context correct, and if so, it would be helpful to have some textual description to explain the rationale of this change of relationships.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e55d3a73-7618-45ba-b281-bb70dd258842
* Version Independent ID: 7f5cd352-0998-a214-8dfc-c19898cecd21
* Content: [Domain analysis for microservices - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/microservices/model/domain-analysis)
* Content Source: [docs/microservices/model/domain-analysis.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/model/domain-analysis.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by Naveenommi-MSFT** [comment]
@bhopkinson 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 62710 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
