### ISSUE TITLE
 Visio file of this architecture is incorrect

### ISSUE THREAD

**Issue by kalledog** [MicrosoftDocs/architecture-center#3812]
[Enter feedback here]

The Visio file is wrong
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@kalledog 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@kalledog When you download the .vdsx file from the [link](https://arch-center.azureedge.net/identity-architectures.vsdx) you will see multiple tabs in the bottom as shown in the below screenshot:

![image](https://user-images.githubusercontent.com/59500871/207380346-d16bb19f-3e6a-41c6-99d9-72326e6644b8.png)

Please choose the correct tab to look for the relevant architecture. In your case its `AD DS` tab.

Hope this helps!
