### ISSUE TITLE
Categorize items-improve presentation and organization

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3813]
The very long list of what's new items is difficult to use because it is random by month. Please add some type of categorization or grouping each month so that we can more easily find information about changes to specific services/topics/applications. 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd7bc22-da10-1d3b-ba22-7d5e374be441
* Version Independent ID: 9f466c91-adc7-0489-5b1e-17633d27c98c
* Content: [What's New in Azure Architecture Center - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/changelog)
* Content Source: [docs/changelog.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/changelog.md)
* Service: **architecture-center**
* GitHub Login: @alexhart11
* Microsoft Alias: **pnp**

**Comment by AjayBathini-MSFT** [comment]
@DeanGross 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by alexhart11** [comment]
@josevarela Feedback on Whats New page

**Comment by alexhart11** [comment]
@DeanGross Ownership of this page has been moved to someone else. I have passed on this feedback to the new owner, so no need to keep this open.

**Comment by DeanGross** [comment]
@alexhart11 how will I learn about the resolution?

**Comment by alexhart11** [comment]
@DeanGross I have passed on your feedback to the owner of the page. It will be taken into consideration along with other internal needs that that page provides in its present state. We can't make any guarantees that we can implement this change. Thanks again
