### ISSUE TITLE
Choose a candidate service flowchart corrections

### ISSUE THREAD

**Issue by waynemunro** [MicrosoftDocs/architecture-center#3817]
Hello maintainers,

The candidate selection graph is incorrect and is causing the Azure Service Fabrics usage is to be less than it should be as it does in fact support all of dotnet and java SDKs. SF should also be available for non-managed service. How does one update the diagram and publish amendments and so on? I will be glad to contribute. Thanks

Wayne

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @paolosalvatori
* Microsoft Alias: **paolos**

**Comment by paolosalvatori** [comment]
Hi @waynemunro, the role and weight of Azure Service Fabric was discussed in a meeting before publishing the article. Please, let's have this conversation offline, thanks. Adding @ckittel and @mosabami to the conversation.
