### ISSUE TITLE
Wront mention of route server name

### ISSUE THREAD

**Issue by gulzarshaikh** [MicrosoftDocs/architecture-center#3818]
[Enter feedback here]

The route server subnet name is mentioned incorrectly as "Route Server Subnet". It should "RouteServerSubnet" without any spaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3058f85a-d0d1-bc2e-0801-25c5150319cd
* Version Independent ID: 3058f85a-d0d1-bc2e-0801-25c5150319cd
* Content: [Update route tables by using Azure Route Server - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/manage-routing-azure-route-server)
* Content Source: [docs/example-scenario/networking/manage-routing-azure-route-server.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/networking/manage-routing-azure-route-server.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @priyshar
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@gulzarshaikh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mike-urnun-msft** [comment]
@gulzarshaikh Thanks for sharing this feedback and helping us drive improvements toward MS Docs! I've created a PR that removes the spacings and the change will be live shortly after a merge within the next 24hrs.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
