### ISSUE TITLE
Document running of background jobs in Azure Container Apps. 

### ISSUE THREAD

**Issue by danvanderboom** [MicrosoftDocs/architecture-center#3822]
[Enter feedback here]

Add info for running background jobs in Azure Container Apps. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50a65e47-b024-0c7c-0ee9-21ff095abafd
* Version Independent ID: a764689a-168d-dcef-a297-c47f84ea2d12
* Content: [Background jobs guidance - Best practices for cloud applications](https://learn.microsoft.com/en-us/azure/architecture/best-practices/background-jobs)
* Content Source: [docs/best-practices/background-jobs.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/background-jobs.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by NaveenOmmi** [comment]
@danvanderboom 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
