### ISSUE TITLE
Possible confusion over high cohesion definition.

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/architecture-center#3823]
This paragraph could be a little clearer to explain that the functions are in the service. (Some other languages call functions methods).
"High cohesion generally means that changes in one function will require changes in other related functions. If you find that updating a service requires coordinated updates to other services, it may be a sign that your services are not cohesive."

Is this a better wording?
"High cohesion generally means that changes in one function will require changes in other related functions, where all the related functions reside in one service. If you find that updating a service requires coordinated updates to other services, it may be a sign that your services are not cohesive."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f101fff7-32ae-ac87-387f-5cf6db8fda7c
* Version Independent ID: 19dc1fb7-29cc-e988-c670-a2814f4e28a0
* Content: [Design for change - Azure Application Architecture Guide](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/design-for-evolution)
* Content Source: [docs/guide/design-principles/design-for-evolution.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/design-principles/design-for-evolution.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by RamanathanChinnappan-MSFT** [comment]
@dombat 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
