### ISSUE TITLE
Typo in last sentence under "Scenario details"

### ISSUE THREAD

**Issue by dli9431** [MicrosoftDocs/architecture-center#3824]
"Containers easily other Azure resources like storage and database services."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc9f55da-2d42-5ae9-9998-0088aa523884
* Version Independent ID: fc9f55da-2d42-5ae9-9998-0088aa523884
* Content: [Lift and shift to containers with Azure App Service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/migrate-existing-applications-to-container-apps)
* Content Source: [docs/solution-ideas/articles/migrate-existing-applications-to-container-apps.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/migrate-existing-applications-to-container-apps.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @vmagelo
* Microsoft Alias: **v-gelorminom**

**Comment by RamanathanChinnappan-MSFT** [comment]
@dli9431 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JananiRamesh-MSFT** [comment]
@dli9431 We have updated the doc and it will be published soon. We appreciate the feedback!
