### ISSUE TITLE
App Gateway v2 compatibility unclear

### ISSUE THREAD

**Issue by matt-buchanan** [MicrosoftDocs/architecture-center#3826]
Just looking for clarification - are all of these scenarios equally applicable to both App Gateway v1 and v2? Specifically, the docs for v2 indicate that support for UDRs isn't as complete as it is for v1 (https://learn.microsoft.com/en-us/azure/application-gateway/configuration-infrastructure#supported-user-defined-routes) and the app gateway before firewall scenario seems to rely heavily on this.

Will all these scenarios work equally well with both app gateway SKUs?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall, App Gateway for virtual networks - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway#application-gateway-before-firewall)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by erjosito** [comment]
@matt-buchanan v2 has been the reccomended SKU for App GW for years now, hence that doc has only been validated with v2. It would still be valid for v1, or any other web proxy such as nginx.

**Comment by matt-buchanan** [comment]
@erjosito thanks for the quick response and clarification
