### ISSUE TITLE
Please provide examples for clarity in the get/post/put response body message.

### ISSUE THREAD

**Issue by kevyaugusto** [MicrosoftDocs/architecture-center#3827]
Please provide examples for clarity in the get/post/put response body message

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad651d6a-f8d8-2050-e7a7-adbae7326112
* Version Independent ID: 4fddd724-cabd-8623-7692-857088c1dccb
* Content: [Web API design best practices - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design)
* Content Source: [docs/best-practices/api-design.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/api-design.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by v-fearam** [comment]
Hi @kevyaugusto 


Sorry for the delay. 


[Api Design](https://learn.microsoft.com/azure/architecture/best-practices/api-design) is a large article with several references to http command examples. You have available another article with more implementation detail [here](https://learn.microsoft.com/azure/architecture/best-practices/api-implementation)


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
