### ISSUE TITLE
distribution in PNG/PPTX

### ISSUE THREAD

**Issue by mizti** [MicrosoftDocs/architecture-center#3830]
(This is not an Issue, but a request)

Currently, SVG icon sets are distributed, but I would like to see them distributed in png format if possible, or in pptx like AWS.
https://aws.amazon.com/en/architecture/icons/
(Some tools don't support SVG formats..)

I draw a lot of Azure architecture diagrams, so I would be super happy if you could support this!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by ManoharLakkoju-MSFT** [comment]
@mizti 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mizti** [comment]
Thanks so much!

**Comment by ckittel** [comment]
@dominicallen & @Zimmergren

**Comment by Zimmergren** [comment]
Thank you for submitting this request, @mizti. I've made a note of this to discuss internally via the appropriate channels and teams. Thanks!

#please-close
