### ISSUE TITLE
Link redirects to aka.ms

### ISSUE THREAD

**Issue by RafaelHinojosa** [MicrosoftDocs/architecture-center#3832]
https://learn.microsoft.com/en-us/azure/architecture/data-guide/big-data/baseball-ml-workload#next-steps
The first link of that section is:
View a [live demo of this solution](https://aka.ms/BaseballMLWorkbench) -> https://aka.ms/BaseballMLWorkbench

It is not reachable.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 492b442b-d5bf-7078-2776-fedc6c90ec77
* Version Independent ID: 7f92146e-7ada-7b7c-4065-c3dabae735bf
* Content: [Baseball decision analysis with ML.NET and Blazor - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/big-data/baseball-ml-workload#next-steps)
* Content Source: [docs/data-guide/big-data/baseball-ml-workload.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/big-data/baseball-ml-workload.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@RafaelHinojosa 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
