### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DavidKlempfner** [MicrosoftDocs/architecture-center#3833]
The following sentence doesn't make sense:
"For additional information on writing client applications that can the Azure Cache for Redis".
Should it be "...that can use the Azure Cache..." instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be785717-ca5e-f3d6-8e60-4005d9503d08
* Version Independent ID: 3ce414e5-d923-0488-ff11-3aa8bd4c2d1e
* Content: [Caching guidance - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/best-practices/caching)
* Content Source: [docs/best-practices/caching.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/caching.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by JananiRamesh-MSFT** [comment]
@DavidKlempfner Thanks for your feedback. We will review and update as appropriate.

**Comment by JananiRamesh-MSFT** [comment]
@DavidKlempfner We have updated the doc and it will be published soon. We appreciate the feedback!
