### ISSUE TITLE
No link to ApiOps on GitHub

### ISSUE THREAD

**Issue by jeroenmaes** [MicrosoftDocs/architecture-center#3835]
Somehow there is no link on this page to the actual GitHub project: https://github.com/Azure/apiops

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Version Independent ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Content: [Automated API deployments using APIOps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops)
* Content Source: [docs/example-scenario/devops/automated-api-deployments-apiops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/automated-api-deployments-apiops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **risaha**

**Comment by SaibabaBalapur-MSFT** [comment]
@jeroenmaes 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
