### ISSUE TITLE
DNS Settings for 2 domain controllers in the same vNET

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/architecture-center#3836]
It would be good to get official guidance from Microsoft on the recommended set up when you have two domain controllers\DNS servers in the same VNET. This is a very normal design for Azure customers and is not properly addressed in any documentation. See the example below for further clarification. So the question is really, to replicate the on premises set up below, should the DNS settings for DC\DNS servers in Azure be set at the NIC level rather than the vNET level. If, so, it would be good tosee this called out in the doucmentation.

ON prem set up of DC\DNS servers
 
DC\DNS Server A
IP Address:                         10.0.0.1
Preferred DNS Server:     10.0.0.1
Alternative DNS Server:  10.0.0.2
 
DC\DNS Server B
IP Address:                         10.0.0.2
Preferred DNS Server:     10.0.0.2
Alternative DNS Server:  10.0.0.1
 
In Azure with Custom DNS Set at the vNET level
DNS: 10.0.0.1
DNS: 10.0.0.2
 
DC\DNS Server A
IP Address:                         10.0.0.1
Preferred DNS Server:     10.0.0.1
Alternative DNS Server:  10.0.0.2
 
DC\DNS Server B
IP Address:                         10.0.0.2
Preferred DNS Server:     10.0.0.1
Alternative DNS Server:  10.0.0.2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Deploy AD DS in an Azure virtual network - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/identity/adds-extend-domain.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
@KumudD / @BrianBlanchard for this content signal

**Comment by Naveenommi-MSFT** [comment]
@gerrynicol 
I've delegated this to content author @martinekuan and @KumudD, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@ckittel 
Thank you for your Response.

**Comment by ckittel** [comment]
@lukemurraynz has added content for this topic a while ago.  As such we are going to close the issue.

#please-close
