### ISSUE TITLE
diagrams are confusing and make no sense. 

### ISSUE THREAD

**Issue by victorsj1** [MicrosoftDocs/architecture-center#3839]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4943e185-fb94-576a-d0a1-2cfefd0d0f96
* Version Independent ID: a9a5a4b7-887c-c298-f720-49ed6abaa575
* Content: [Federated Identity pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/federated-identity)
* Content Source: [docs/patterns/federated-identity.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/federated-identity.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@victorsj1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
#please-close
