### ISSUE TITLE
ERS stands for Enqueue Replication Server

### ISSUE THREAD

**Issue by zeropirateJP** [MicrosoftDocs/architecture-center#3840]
[
Below paragraph has a corrections 

"Standard Load Balancer supports multiple front-end virtual IPs. This support is ideal for cluster implementations that include these components:

Advanced Business Application Programming (ABAP) SAP Central Service (ASCS)
Evaluated receipt settlement (ERS)"

Here ERS stands for Enqeue Replication server instead of Evaluated receipt settlement (ERS)

]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 009774ee-d1e4-1d7b-e53f-ecbcc4d56e5d
* Version Independent ID: d14a99bb-b4d5-21ce-dd72-5759a8284c42
* Content: [SAP S/4HANA in Linux on Azure - Azure Architecture Center](https://learn.microsoft.com/en-in/azure/architecture/guide/sap/sap-s4hana)
* Content Source: [docs/guide/sap/sap-s4hana.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/sap/sap-s4hana.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @bqtrinh
* Microsoft Alias: **bentrin**
<img width="505" alt="2023-01-05 23_43_10-Clipboard" src="https://user-images.githubusercontent.com/46904588/210851058-d0bb3b25-f479-4b69-8dda-76444ffc746e.png">

**Comment by ckittel** [comment]
@bqtrinh can you please review this feedback in the SAP S/4HANA article.

**Comment by Naveenommi-MSFT** [comment]
@zeropirateJP
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@ckittel 
Thanks for your response.

**Comment by v-fearam** [comment]
#please-close
