### ISSUE TITLE
AKS mTLS example - why App Gateway and APIM?

### ISSUE THREAD

**Issue by supachris28** [MicrosoftDocs/architecture-center#3843]
Hi,

please could you add an explanation as to why both Application Gateway and APIM are chained in the design? My understanding is both can handle mTLS, Load Balancing and public/private network traversal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Version Independent ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Content: [Deploy AKS and API Management with mTLS - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/mutual-tls-deploy-aks-api-management)
* Content Source: [docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @saswatmohanty01
* Microsoft Alias: **samohant, rapencha, arazeem**

**Comment by antoineozenne** [comment]
Another question: is it possible to use AGIC as Ingress Controller in this case? My idea is to use AGIC, APIM and Application Gateway like this:

* The Ingresses of the backend (API) services (in AKS) use the annotation `appgw.ingress.kubernetes.io/use-private-ip: "true"`. The APIM can access backend services with this private IP.
* The Ingresses of the frontend services (in AKS) do not use the annotation `appgw.ingress.kubernetes.io/use-private-ip: "true"`. In this way, AGIC configures the Application Gateway directly.
* The Application Gateway publicly exposes the APIM endpoint.

So we could have:
Internet -> Application Gateway -> APIM -> AGIC -> backends.
Internet -> Application Gateway -> AGIC -> frontends.

All our services are the protected by the same Application Gateway, while we can use APIM to handle our APIs.

**Comment by YashikaTyagii** [comment]
@supachris28 
Thanks for your feedback! We have assigned the issue to author who will provide further updates.

**Comment by v-fearam** [comment]
Hi @supachris28 


Sorry for the delay. 


[Azure Application Gateway](https://learn.microsoft.com/azure/application-gateway/overview-v2) is also a Web Application Firewall (WAF), so it provides additional security.


[APi Management](https://learn.microsoft.com/azure/api-management/api-management-key-concepts#api-gateway) has features that are no included on Azure Application Gateway, for example: 

 * Acts as a facade to backend services by accepting API calls and routing them to appropriate backends

* Verifies API keys and other credentials such as JWT tokens and certificates presented with requests

* [Api Versioning](https://learn.microsoft.com/azure/api-management/api-management-versions)


The use depends on the requirements. For sure you could use [Application gateway as Ingress Controller](https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview) or any other ingress controller.


You could use the combination which works for you, the article is only a solution idea 


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
