### ISSUE TITLE
Kubeflow on AKS

### ISSUE THREAD

**Issue by smurli** [MicrosoftDocs/architecture-center#3844]
Active support of Kubeflow on Azure will be beneficial.

We are working on developing ML Enabled application that runs on Hybrid-Cloud Environment.

Our development is entirely based on Azure. But to enable the portability of our application a Kubeflow-based environment would be helpful.

It will be great if you could prioritise full support of Kubeflow on Azure at the earliest.

If you need any further details please feel free to get in touch.

Thanks,
Murli Sivashanmugam
Principal AI Architect
A5G Networks(a5gnet.com)

**Comment by YashikaTyagii** [comment]
@smurli 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!
