### ISSUE TITLE
Missing link in next steps

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftDocs/architecture-center#3847]
Under next steps

wrong formatting (i think) has been applied resulting in a non functioning link :
[In-Memory OLTP overview and usage scenarios](/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af4555db-76bc-15c1-6b17-ddf5be651b70
* Version Independent ID: 3ec33db3-f67d-6786-aeb3-9737896088bf
* Content: [Online transaction processing (OLTP) - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-transaction-processing#scalability-capabilities)
* Content Source: [docs/data-guide/relational-data/online-transaction-processing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/relational-data/online-transaction-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by YashikaTyagii** [comment]
@VEshelbyMTT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
Thank you for noticing this, I've fixed the broken link.  This change should be live within about 24 hours.

#please-close
