### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Raunak786Ansari** [MicrosoftDocs/architecture-center#3848]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f815c98d-c54b-a6cb-b77b-27c9fa99b3a3
* Version Independent ID: f78699f2-a847-f5cc-54bb-2730faf0b755
* Content: [Build solutions with availability zones - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/high-availability/building-solutions-for-high-availability)
* Content Source: [docs/high-availability/building-solutions-for-high-availability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/high-availability/building-solutions-for-high-availability.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by JananiRamesh-MSFT** [comment]
@Raunak786Ansari 
could you elaborate query it would help us redirect the issue to the appropriate team. Thanks!!

**Comment by JananiRamesh-MSFT** [comment]
@Raunak786Ansari We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
