### ISSUE TITLE
credit to the original content

### ISSUE THREAD

**Issue by abhi004** [MicrosoftDocs/architecture-center#3850]
The original article was written on TechNet Wiki and Medium in year 2018 .
Reference link: https://medium.com/@abhishekcskumar/logic-apps-large-audio-speech-to-text-batch-transcription-d71e93bbaeec
This GitHub Page does not give credit to the original content

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa4a3938-1142-4e18-1915-4dcee68d4c99
* Version Independent ID: aa4a3938-1142-4e18-1915-4dcee68d4c99
* Content: [Build a speech-to-text transcription pipeline to analyze recorded conversations - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/speech-to-text-transcription-analytics)
* Content Source: [docs/example-scenario/ai/speech-to-text-transcription-analytics.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/ai/speech-to-text-transcription-analytics.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @bdleavitt
* Microsoft Alias: **bleavitt, christinas**

**Comment by JananiRamesh-MSFT** [comment]
@abhi004 Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
