### ISSUE TITLE
docs/industries/retail/retail-data-management-overview.md references USQL

### ISSUE THREAD

**Issue by sasever** [MicrosoftDocs/architecture-center#3853]
The data management overview references USQL which is a gen1 ADLS feature which is not being updated, we are advising the customers to migrate to gen2, documentation shouldn't suggest a feature which will eventually be killed.

**Comment by YashikaTyagii** [comment]
@sasever 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by hallihan** [comment]
@sasever Do you have a link to the doc page you are referencing?

**Comment by YashikaTyagii** [comment]
@sasever 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!
