### ISSUE TITLE
More detail info needed 

### ISSUE THREAD

**Issue by jarvan-jiang** [MicrosoftDocs/architecture-center#3858]
For this document it mentioned using dynamics 365 as a service to manage product source, but as I know dynamics 365 using dataverse as it's storage which is not listed in the picture.
So could you please add more detail design in this document about dynamics 365 to azure microservice without involving dataverse?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34ed51e6-265e-aae0-f552-0900a345b3be
* Version Independent ID: 34ed51e6-265e-aae0-f552-0900a345b3be
* Content: [Scalable cloud applications and SRE - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/scalable-apps-performance-modeling-site-reliability)
* Content Source: [docs/example-scenario/apps/scalable-apps-performance-modeling-site-reliability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/scalable-apps-performance-modeling-site-reliability.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **subhajch**

**Comment by AjayBathini-MSFT** [comment]
@jarvan-jiang 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by ckittel** [comment]
@Subhajit

**Comment by ckittel** [comment]
@SubhajitChatterjee

**Comment by Subhajit-Chatterjee-MS** [comment]
@jarvan-jiang - You are correct in your understanding that Dynamics 365 Apps are built on top of Dataverse. 
Microsoft has released the Common Data Model (Schema) that encompasses the majority of the entities required for your business apps. 
https://microsoft.github.io/CDM/

It was not depicted in the diagram as the intent was to give a high-level view of the concept of Polyglot persistence using which you are able to bring in the best of all platforms for your solution architecture. Dynamics 365 offers a powerful suite of Apps that you can leverage out of the box for your business workflows. 
Refer here on the public documentation on how to setup a product catalogue: 
https://learn.microsoft.com/en-us/dynamics365/sales/set-up-product-catalog-walkthrough

Regarding your point on D365 without Dataverse, I believe you were referring to Power Platform. While it is possible to build standalone applications using the Power Platform, but having Dataverse in the mix gives you a lot of flexibility and extensibility that will be required in an enterprise context when building business applications. Refer below for the licensing differences. 
https://learn.microsoft.com/en-us/power-platform/admin/pricing-billing-skus

Hope I was able to clarify your query.

Thanks 
Subhajit

**Comment by ckittel** [comment]
Thank you @Subhajit-Chatterjee-MS and @jarvan-jiang.  I've asked @Subhajit-Chatterjee-MS to consider some updates to the article to help clarify this for all readers.  @jarvan-jiang, please confirm the information provided by @Subhajit-Chatterjee-MS helps clarifies your query.

 #please-close
