### ISSUE TITLE
Relevant to AVS?

### ISSUE THREAD

**Issue by robm82** [MicrosoftDocs/architecture-center#3859]
This page is under the CAF for AVS, but this page has nothing to do with AVS. Should these pages that compare Azure to AWS be replaced with some tips on the Well Architected Framework for AVS?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0ef54ba-28f9-bf3d-214d-d15ff2595a55
* Version Independent ID: 2c9fabc5-0288-ce98-a906-0dcc720f0c7f
* Content: [Compare AWS and Azure compute services - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/aws-professional/compute?bc=%2Fazure%2Fcloud-adoption-framework%2F_bread%2Ftoc.json&toc=%2Fazure%2Fcloud-adoption-framework%2Fscenarios%2Fazure-vmware%2Ftoc.json)
* Content Source: [docs/aws-professional/compute.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/compute.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @kobile70
* Microsoft Alias: **kobilevi**

**Comment by mike-urnun-msft** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by stephen-sumner** [comment]
@robm82 - this has been fixed. Thanks for your input

**Comment by stephen-sumner** [comment]
#please-close
