### ISSUE TITLE
Innacurate depication of firewall

### ISSUE THREAD

**Issue by hurtn** [MicrosoftDocs/architecture-center#3861]
I don't believe Serverless has firewall protection, certainly not at database level, although the storage account which Serverless uses may indeed be secured by a firewall.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1914293-dced-7bee-6b4f-e144007a9dcc
* Version Independent ID: d1914293-dced-7bee-6b4f-e144007a9dcc
* Content: [Secure a data lakehouse on Synapse - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/analytics/secure-data-lakehouse-synapse)
* Content Source: [docs/example-scenario/analytics/secure-data-lakehouse-synapse.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/analytics/secure-data-lakehouse-synapse.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @Herman-Wu
* Microsoft Alias: **hermanwu**

**Comment by AjayBathini-MSFT** [comment]
@hurtn 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MughundhanRaveendran-MSFT** [comment]
@hurtn , Firewall and networking rules/options are available for Azure synapse analytics which is also applicable for the Serverless sql pools associated with the workspace. So the document is correct.

https://learn.microsoft.com/en-us/azure/synapse-analytics/guidance/security-white-paper-network-security

https://learn.microsoft.com/en-us/azure/synapse-analytics/security/synapse-workspace-ip-firewall

**Comment by hurtn** [comment]
> @hurtn , Firewall and networking rules/options are available for Azure synapse analytics which is also applicable for the Serverless sql pools associated with the workspace. So the document is correct.
> 
> https://learn.microsoft.com/en-us/azure/synapse-analytics/guidance/security-white-paper-network-security
> 
> https://learn.microsoft.com/en-us/azure/synapse-analytics/security/synapse-workspace-ip-firewall

You are correct to a degree however it is not a database level firewall as was available for the sqldw, it is a workspace level firewall, which is actually IP filtering, only available when public network access is chosen.

**Comment by MughundhanRaveendran-MSFT** [comment]
@hurtn , Yes. If you look at the architecture diagram, the firewall is connected to the network level and not the individual sql pool.

![image](https://user-images.githubusercontent.com/56299140/213975369-9034991f-e738-46f2-952b-be94323183a3.png)
 
I think the doc doesn't need correction.

**Comment by MughundhanRaveendran-MSFT** [comment]
@hurtn , I will be closing this issue. Please feel free to reopen if needed
