### ISSUE TITLE
Wrong link for Martin Tile Server

### ISSUE THREAD

**Issue by 2Dews** [MicrosoftDocs/architecture-center#3862]
I think you meant to link to https://github.com/maplibre/martin

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1aaa7e-6d26-b593-2d5e-c2058635d065
* Version Independent ID: 94294d08-2922-b5b8-0333-161bc36997bc
* Content: [Geospatial data processing and analytics - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/data/geospatial-data-processing-analytics-azure)
* Content Source: [docs/example-scenario/data/geospatial-data-processing-analytics-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/geospatial-data-processing-analytics-azure.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ribumann
* Microsoft Alias: **ribumann**

**Comment by AjayBathini-MSFT** [comment]
@2Dews 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MughundhanRaveendran-MSFT** [comment]
@2Dews , I have made changes to the document and it will be published soon

**Comment by MughundhanRaveendran-MSFT** [comment]
@2Dews , Changes are reflected in the main site. I will close this issue.
