### ISSUE TITLE
Broken link to Visio Stencils

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/architecture-center#3863]
The link to https://aka.ms/AzureDiagrams does not appear to be working giving a 502 error when clicked

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by AjayBathini-MSFT** [comment]
@ld0614 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MayankBargali-MSFT** [comment]
@ld0614 Thanks for reaching out. I have reached out to the owner of the short link to fix the issue.

**Comment by MayankBargali-MSFT** [comment]
@ld0614 As per the internal discussion the link has been removed from the document. 
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
