### ISSUE TITLE
Contradicting statement on limits

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/architecture-center#3867]
The section called Pre-requisites should be split out to limitations and pre-reqs to avoid confusion (and also make it easier to see when a limit has been removed)
https://learn.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join#prerequisites

The 1st 2 points seem to contradict eachother, or the 1st one needs expansion to say what the consequences are:

> - Azure Virtual Desktop supports Azure AD join for both personal and pooled host pools, except when using FSlogix with an Azure Files account that is also joined to the same Azure AD.
> - Azure Files now supports Azure AD as a [Kerberos](https://en.wikipedia.org/wiki/Kerberos_(protocol)) realm. This allows you to create an Azure Files share to store the FSLogix profiles and to configure it to support Azure AD authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96947883-d52b-1ed8-7db2-915f025060af
* Version Independent ID: 96947883-d52b-1ed8-7db2-915f025060af
* Content: [Azure AD join for Azure Virtual Desktop - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join)
* Content Source: [docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@thommck 
I've delegated this to @TTomHickling, a content author, to review and share their valuable insights.
