### ISSUE TITLE
Link to Azure Sponsorship for ISVs program is broken.

### ISSUE THREAD

**Issue by mmast-msft** [MicrosoftDocs/architecture-center#3870]
Link to Azure Sponsorship for ISVs program is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe9676d7-afd3-3123-2aed-9f554bf653af
* Version Independent ID: fe9676d7-afd3-3123-2aed-9f554bf653af
* Content: [Microsoft partner and third-party scenarios on Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/partner-scenarios)
* Content Source: [docs/guide/partner-scenarios.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/partner-scenarios.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by RamanathanChinnappan-MSFT** [comment]
@mmast-msft 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
