### ISSUE TITLE
Population health management for healthcare

### ISSUE THREAD

**Issue by ExplorerGF23** [MicrosoftDocs/architecture-center#3871]
I am looking for the "manual deployment guide for the solution." Please let me know where I would find it. I did not see a link to the guide in the original source. Thanks.

**Comment by ExplorerGF23** [comment]
Disregard. I found it...in a place I wasn't expecting. No worries. Peace

**Comment by ckittel** [comment]
Glad you found it.

#please-close

**Comment by Naveenommi-MSFT** [comment]
@ExplorerGF23 
It looks like your issue is resolved since closed this thread.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.

**Comment by Naveenommi-MSFT** [comment]
@ckittel 
Thank you for your response.
