### ISSUE TITLE
Improvement: Add CycleCloud to this Page

### ISSUE THREAD

**Issue by Jeya888** [MicrosoftDocs/architecture-center#3872]
https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree

In that specific page, we should enhance the decision tree doc to include Azure CycleCloud
 for HPC workload.  Note:  CycleCloud and Batch adoption are roughly 50%/50%.

I do not mind to refine the diagram if there is a Visio or PowerPoint version of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @paolosalvatori
* Microsoft Alias: **paolos**

**Comment by ckittel** [comment]
@BrianBlanchard / @dominicallen - content signal on update for HPC content in our compute decision tree

**Comment by RamanathanChinnappan-MSFT** [comment]
@Jeya888 

I've delegated this to @paolosalvatori, a content author, to review and share their valuable insights.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 62676 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
