### ISSUE TITLE
ETL Versus ELT for Power BI Datamarts

### ISSUE THREAD

**Issue by Didierma92** [MicrosoftDocs/architecture-center#3873]
Datamart should be positionned in this article : is Datamart an ETL or an ELT or both ? CAN WE SAY that the transformation happens in the target store that is Azure db ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcb3c6d7-aa3e-9a76-181b-d0963ac685b9
* Version Independent ID: da9c883b-93bf-8864-015a-a7b10a6fcb5f
* Content: [Extract, transform, and load (ETL) - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/relational-data/etl)
* Content Source: [docs/data-guide/relational-data/etl.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/relational-data/etl.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @raunakjhawar
* Microsoft Alias: **rajhawar**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Didierma92 

I've delegated this to @raunakjhawar, a content author, to review and share their valuable insights.

**Comment by v-fearam** [comment]
#please-close
