### ISSUE TITLE
404 Issue with documents

### ISSUE THREAD

**Issue by lg4** [MicrosoftDocs/architecture-center#3874]
This page https://learn.microsoft.com/en-us/azure/architecture/landing-zones/landing-zone-deploy is missing a valid link to documents

I get 404 from MS and Github. 

Example - https://github.com/MicrosoftDocs/architecture-center/blob/main/azure/cloud-adoption-framework/organize/cloud-strategy.md

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75727ca9-f46f-24a6-3871-25cc45b61de8
* Version Independent ID: 75727ca9-f46f-24a6-3871-25cc45b61de8
* Content: [Deploy Azure landing zones - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/landing-zones/landing-zone-deploy)
* Content Source: [docs/landing-zones/landing-zone-deploy.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/landing-zones/landing-zone-deploy.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by RamanathanChinnappan-MSFT** [comment]
@lg4

I've delegated this to @RobBagby, a content author, to review and share their valuable insights.

**Comment by skabou** [comment]
It appears this has been addressed.  If you are still experiencing an issue, please re-open with additional information.
