### ISSUE TITLE
Please add Azure Arc-related icons to the icon .svg file download package

### ISSUE THREAD

**Issue by twright-msft** [MicrosoftDocs/architecture-center#3880]
It would be really great to add the Azure Arc-related service icons .svg files to the download package.
Azure Arc-enabled Kubernetes
Azure Arc-enabled machines/servers
Azure Arc-enabled data services
Azure Arc-enabled SQL Managed Instance
Azure Arc-enabled PostgreSQL
Azure Arc-enabled SQL Server
Azure Arc-enabled Machine Learning
......

There are many such services now.  We often have to draw architectural diagrams connecting on-premises, edge, and multi-cloud to Azure.  This would make it much easier!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by SaibabaBalapur-MSFT** [comment]
@twright-msft 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Zimmergren** [comment]
Hey, thank you @twright-msft for reporting this. 
I've routed the request internally for an update. When there's an updated icon pack, I'll update this issue with the link.

Thanks,
Tobias

**Comment by Zimmergren** [comment]
We've just incorporated the Azure Arc-related icons into the latest download pack. These updates will roll out today.
The icons pack contains these relevant icons: 

- "management + governance/01710-icon-service-Arc-Machines.svg"
- "other/01088-icon-service-Arc-Kubernetes.svg"
- "other/01848-icon-service-Arc-PostgreSQL.svg"
- "other/01849-icon-service-Arc-SQL-Managed-Instance.svg"
- "other/01850-icon-service-Arc-SQL-Server.svg
- "other/02356-icon-service-Arc-Data-services.svg"

#please-close
