### ISSUE TITLE
aPaaS is not a well used term

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/architecture-center#3881]
I have never heard aPaaS ever mentioned in Azure before (or any cloud computing contect). 
I think it would be much clearer to the reader if you used SaaS - that is how I hear all internal Microsoft and external people describe IoT central.

If you think it doesn't quite count as SaaS you should link to what Microsoft means when it describes something as aPaaS rather than PaaS as I don't think anywhere else in Microsoft uses that term?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30009d60-b907-fa0d-b2f9-a6dd7e414259
* Version Independent ID: 377f9495-ed09-bd1f-2f62-58007097d338
* Content: [Choose an Internet of Things (IoT) solution in Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/iot/iot-central-iot-hub-cheat-sheet)
* Content Source: [docs/example-scenario/iot/iot-central-iot-hub-cheat-sheet.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/iot/iot-central-iot-hub-cheat-sheet.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@thommck 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi @thommck ,

Sorry for the delay. 


The term “application platform as a service (aPaaS) ” is used by Microsoft. Examples:


https://learn.microsoft.com/en-us/azure/iot-central/core/overview-iot-central
https://learn.microsoft.com/en-us/azure/iot-fundamentals/
https://azure.microsoft.com/en-us/resources/gartner-apaas-magic-quadrant-es-es/

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
