### ISSUE TITLE
icons for Data Collection Endpoints and Data Collection Rules

### ISSUE THREAD

**Issue by dannystaple** [MicrosoftDocs/architecture-center#3887]
Can the following icons be added:
- Data Collection Endpoints 
- Data Collection Rules
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by AjayBathini-MSFT** [comment]
@dannystaple 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Zimmergren** [comment]
Hey, @dannystaple , thank you for reporting this.

I've routed the request internally for an update. When there's an updated icon pack, I'll update this issue with the link.

Thanks,
Tobias

**Comment by Zimmergren** [comment]
We've updated the Azure Icons download page with the latest package. It will roll out during the day today. 
The latest pack includes a new relevant icon for: 

- "new icons/01857-icon-service-Data-Collection-Rules.svg"

We've requested the Endpoint icon, too. When we have that in the package it will get updated automatically. 
Feel free to open a new ticket for any other missing icons and we'll get them addressed. 

Thanks!
#please-close
