### ISSUE TITLE
typo "to reduced"

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/architecture-center#3888]
in this sentence *Use Azure SQL Database to reduced management overhead.*

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84bcf722-abb3-69b8-8073-15ae4a6890de
* Version Independent ID: 7b2010c6-696d-de66-8e56-8ac5d3e54526
* Content: [Basic web application - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?tabs=cli)
* Content Source: [docs/reference-architectures/app-service-web-app/basic-web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/basic-web-app.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @josevarela
* Microsoft Alias: **josev**

**Comment by Naveenommi-MSFT** [comment]
@ciufudean 
It looks like your issue is resolved.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.

@ckittel 
Thank you for your response.
