### ISSUE TITLE
KV and SA servcie endpoints fro DevOPs 

### ISSUE THREAD

**Issue by davidjia1** [MicrosoftDocs/architecture-center#3890]
[Enter feedback here]
Hi, I have a question about the part of the security diagram on DevoPS where Synpase service endpoints are via PEPs however the KV and data lake are via service endpoints. Why is it the case, can the KV and DL be brought in also as PEPs?

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1914293-dced-7bee-6b4f-e144007a9dcc
* Version Independent ID: d1914293-dced-7bee-6b4f-e144007a9dcc
* Content: [Secure a data lakehouse on Synapse - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/analytics/secure-data-lakehouse-synapse)
* Content Source: [docs/example-scenario/analytics/secure-data-lakehouse-synapse.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/analytics/secure-data-lakehouse-synapse.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @Herman-Wu
* Microsoft Alias: **hermanwu**

**Comment by SaibabaBalapur-MSFT** [comment]
@davidjia1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 62656 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
