### ISSUE TITLE
Gateway After Firewall Architecture

### ISSUE THREAD

**Issue by bogdansava1** [MicrosoftDocs/architecture-center#3891]
Hello Microsoft,

It's not an Issue, it's more or less a suggestion to improve documentation and to help other colleagues that face the same issue with this architecture. 

For the Gateway After Firewall Architecture, one statement is not entirely true and can be obtain if you correlate logs from the Firewall with the logs from the Web Application firewall: 

- The application can't see the original source IP address of the web traffic; the Azure Firewall SNATs the packets as they come in to the virtual network. To avoid this problem, use [Azure Front Door] in front of the firewall. Azure Front Door injects the client's IP address as an HTTP header before it enters the Azure virtual network.

In the AzureDiagnostics table you can correlate the logs from Firewall with the logs from WAF by the TimeStamp and by the Source Client Port information which is present and carried forward by the Firewall in the SNAT further to the WAF in this Architecture. By looking at this is you are able to track back the Public source IP of the client. 
Example: 
AzureDiagnostics on AzureFirewall 
msg_s : TCP request from 91.209.8.29:15919 to x.x.x.x:443 was DNAT'ed to 10.x.x.x:443

AzureDiagnostics on WAF/AppGateway
clientPort_d 15919 ; 

Same as the Public IP source port above; because it's carried by the static NAT further. Correlate this with the TimeStamp (between 2-3 seconds around the area where the log appears) and you are able to track the public IPs. 

Regards,
Bogdan SAVA 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb4e04dc-fc84-e958-89a8-e144ed5564b0
* Version Independent ID: 795ef2fa-a126-8ded-d75d-3eb8811f4a23
* Content: [Firewall, App Gateway for virtual networks - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/gateway/firewall-application-gateway)
* Content Source: [docs/example-scenario/gateway/firewall-application-gateway.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/firewall-application-gateway.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by ManoharLakkoju-MSFT** [comment]
@bogdansava1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by erjosito** [comment]
Thanks @bogdansava1 ! That is an excellent suggestion. The doc is not entirely true, since the source IP is not present in the packet any more, so the application would have to do that correlation between SNAT and AppGW access logs, which cannot be done at real time.

I have added your remark in https://github.com/MicrosoftDocs/architecture-center-pr/pull/9546

**Comment by bogdansava1** [comment]
Yes, for the application is true; but I'm referring to the fact that you are still able to track back to the public IP from the Logs. Let's say via Sentinel if in place. And, by analyzing lots of possibilities, logs, fields, etc - I see that we can do that on the Timeframe and Source Client Port.

Bogdan
