### ISSUE TITLE
Unclear description

### ISSUE THREAD

**Issue by Tsubasanut** [MicrosoftDocs/architecture-center#3893]
"Azure Synapse Analytics, Azure Data Explorer, HBase, Spark, or Hive. Processed real-time data can be stored in a relational database **such** Synapse Analytics, Azure Data Explorer, a NoSQL store such as HBase, or as files in distributed storage over which Spark or Hive tables can be defined and queried."
There is probably an error here. Maybe "by" should be in place of "such"? Still, the phrase is not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 830e1782-9caa-3533-10a0-85a3d4483d24
* Version Independent ID: d66583fa-188c-9dce-b6fd-84b34c0bf315
* Content: [Real-time processing - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/big-data/real-time-processing)
* Content Source: [docs/data-guide/big-data/real-time-processing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/big-data/real-time-processing.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@Tsubasanut 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MughundhanRaveendran-MSFT** [comment]
@Tsubasanut , Thanks for the feedback! I have made changes to the document and it will be published soon.
