### ISSUE TITLE
Azure Disk Encyption

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/architecture-center#3894]
In the document, under security considerations, it mentions using encryption for the disk that hosts the AD database. Is the guidance therefore not to encrypt the OS disk? 

Thanks

**Comment by ManoharLakkoju-MSFT** [comment]
@gerrynicol 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@gerrynicol 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@gerrynicol 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
