### ISSUE TITLE
More on Security 

### ISSUE THREAD

**Issue by wenms1** [MicrosoftDocs/architecture-center#3898]
John,

Great work! Want to learn more about Security for the multitenant solution. e.g. Sentinel, MD for Cloud

Wenshuo Han

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c251cb1-6f09-e84b-3432-75fa2760bff2
* Version Independent ID: 4c251cb1-6f09-e84b-3432-75fa2760bff2
* Content: [Azure Key Vault considerations for multitenancy - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/service/key-vault)
* Content Source: [docs/guide/multitenant/service/key-vault.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/service/key-vault.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @johndowns
* Microsoft Alias: **jodowns**

**Comment by ManoharLakkoju-MSFT** [comment]
@MughundhanRaveendran-MSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by johndowns** [comment]
Thank you, @wenms1! We're happy to consider additional documentation but it's helpful to get a more specific idea of what you're looking for. I'm certainly not an expert in Sentinel or Defender for Cloud, so maybe you can help me to understand. What kinds of multitenancy-specific guidance would you like to see on these topics?

**Comment by MughundhanRaveendran-MSFT** [comment]
@wenms1 , Could you please respond to @johndowns 's question?

**Comment by MughundhanRaveendran-MSFT** [comment]
@wenms1 Closing this as there is no response. Feel free to reopen whenever required
