### ISSUE TITLE
Needs to be updated: Serverless web application

### ISSUE THREAD

**Issue by RicardoNiepel** [MicrosoftDocs/architecture-center#3908]
This page needs to be updated to reflect the current Azure services and features:
- use of **Azure Static Web Apps** for these kind of web applications ([GA in 2021](https://azure.microsoft.com/en-us/updates/azure-static-web-apps-is-now-generally-available/))
- use of [API integration](https://learn.microsoft.com/en-us/azure/static-web-apps/apis-overview) inside SWA

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 524d1f97-ce37-f9ac-cf05-d33665eb34df
* Version Independent ID: fe4cc63f-a4b1-c30e-f39f-f4c3de1c57be
* Content: [Serverless web application - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app)
* Content Source: [docs/reference-architectures/serverless/web-app.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/serverless/web-app.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@RicardoNiepel 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 70469 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
