### ISSUE TITLE
Links to the Excel files not present 

### ISSUE THREAD

**Issue by hanakon** [MicrosoftDocs/architecture-center#3910]
Links to Excel files should be provided as described, but non present in the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab9d2cf-5ff8-59c9-34fd-014f0dfcef6a
* Version Independent ID: 3ad7b162-7fa2-ef08-8c1d-5343b1bebf4e
* Content: [Team Data Science Process project planning - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-science-process/team-data-science-process-project-templates?source=recommendations#related-resources)
* Content Source: [docs/data-science-process/team-data-science-process-project-templates.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-science-process/team-data-science-process-project-templates.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by Naveenommi-MSFT** [comment]
@hanakon 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by marktab** [comment]
@hanakon Thanks for reporting -- that mention is a legacy offering, no one is maintaining a template today

**Comment by marktab** [comment]
Address in this PR  https://github.com/MicrosoftDocs/architecture-center-pr/pull/9687

**Comment by marktab** [comment]
@MughundhanRaveendran-MSFT  closing this request

**Comment by ckittel** [comment]
#please-close
