### ISSUE TITLE
Update on availability?

### ISSUE THREAD

**Issue by DanFeltonMorgan** [MicrosoftDocs/architecture-center#3911]
Is Alliance Connect Virtual now GA? We're now into 2023 but the banner message still states it's expected for GA in 2022. 
If it is GA where can I find more information on how to implement? 
Quote text from banner:

"This article provides an overview with reference architecture for deploying SWIFT's Alliance Connect Virtual solution on Azure. Please note that the new Alliance Connect Virtual solution is not yet available for SWIFT production traffic. The solution is currently being tested with SWIFT customers and will become generally available throughout 2022 as part of a phased launch. For more information about the general availability of the product, refer to [SWIFT.com](https://www.swift.com/our-solutions/interfaces-and-integration/alliance-connect-virtual)". 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ddcc2a5-2d06-5195-1c13-7b55e1584e01
* Version Independent ID: 6ddcc2a5-2d06-5195-1c13-7b55e1584e01
* Content: [SWIFT's Alliance Access with Alliance Connect Virtual in Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/finance/swift-alliance-access-vsrx-on-azure)
* Content Source: [docs/example-scenario/finance/swift-alliance-access-vsrx-on-azure.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/finance/swift-alliance-access-vsrx-on-azure.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @Mahesh-MSFT
* Microsoft Alias: **maksh**

**Comment by Mahesh-MSFT** [comment]
@Ravi Sharma (HE / ***@***.***> & @Gansu ***@***.***>

From: DanFeltonMorgan ***@***.***>
Sent: Monday, February 20, 2023 4:24 PM
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Mahesh Kshirsagar ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/architecture-center] Update on availability? (Issue #3911)


Is Alliance Connect Virtual now GA? We're now into 2023 but the banner message still states it's expected for GA in 2022.
If it is GA where can I find more information on how to implement?

This article provides an overview with reference architecture for deploying SWIFT's Alliance Connect Virtual solution on Azure. Please note that the new Alliance Connect Virtual solution is not yet available for SWIFT production traffic. The solution is currently being tested with SWIFT customers and will become generally available throughout 2022 as part of a phased launch. For more information about the general availability of the product, refer to SWIFT.com<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.swift.com%2Four-solutions%2Finterfaces-and-integration%2Falliance-connect-virtual&data=05%7C01%7Cmaksh%40microsoft.com%7Cea293c0636f54121225008db135ed511%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638125070277547648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f9DEl7jUMkwTH5RIkerZA%2FN6L36sQEVL5sDjIeZj81o%3D&reserved=0>.

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 6ddcc2a5-2d06-5195-1c13-7b55e1584e01
  *   Version Independent ID: 6ddcc2a5-2d06-5195-1c13-7b55e1584e01
  *   Content: SWIFT's Alliance Access with Alliance Connect Virtual in Azure - Azure Architecture Center<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fexample-scenario%2Ffinance%2Fswift-alliance-access-vsrx-on-azure&data=05%7C01%7Cmaksh%40microsoft.com%7Cea293c0636f54121225008db135ed511%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638125070277547648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C%2FJsMWkEvTrXXcRMFhWUmOoPgxCIFc%2BXzvcEtABkkkM%3D&reserved=0>
  *   Content Source: docs/example-scenario/finance/swift-alliance-access-vsrx-on-azure.yml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftdocs%2Farchitecture-center%2Fblob%2Fmain%2Fdocs%2Fexample-scenario%2Ffinance%2Fswift-alliance-access-vsrx-on-azure.yml&data=05%7C01%7Cmaksh%40microsoft.com%7Cea293c0636f54121225008db135ed511%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638125070277547648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mLayY4Vn5Q0MHqdhgagGcwGd7DdWx11EcaN9U%2B5nQow%3D&reserved=0>
  *   Service: architecture-center
  *   Sub-service: example-scenario
  *   GitHub Login: @Mahesh-MSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMahesh-MSFT&data=05%7C01%7Cmaksh%40microsoft.com%7Cea293c0636f54121225008db135ed511%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638125070277547648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KplAKQXNp7PleiIW43Vny9a97AVWvaqjlRmAe8notrM%3D&reserved=0>
  *   Microsoft Alias: maksh

**Comment by ckittel** [comment]
As @Mahesh-MSFT mentioned, we are indeed working on publishing a refresh of this article.  It's currently in review.  It will be an update to the existing page, so in about a week or so, you should see it refreshed.  You're just a few days ahead of us :)

#please-close
