### ISSUE TITLE
Article Title says AWS but does not mention AWS

### ISSUE THREAD

**Issue by RaphaelUlysses** [MicrosoftDocs/architecture-center#3912]
Article Title says AWS but the article itself does not mention AWS at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d42fd9ae-205d-042a-4d38-4ca356e27d17
* Version Independent ID: 694c671b-430e-31b6-9133-2324bb3a2efa
* Content: [Comparing AWS and Azure regions and zones - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/aws-professional/regions-zones)
* Content Source: [docs/aws-professional/regions-zones.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/regions-zones.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by YashikaTyagii** [comment]
@RaphaelUlysses 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
It was already changed

**Comment by v-fearam** [comment]
#please-close
