### ISSUE TITLE
Webserver missing in "Real-time asset tracking and management" architecture?

### ISSUE THREAD

**Issue by jugi92** [MicrosoftDocs/architecture-center#3918]
https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-asset-tracking-mgmt-iot-central

The architecture "real time asset tracking" shows an arrow from SQL Database to Azure API Management to the Browser.
My question is where is the webserver that is hosting the API and querying the data for API Requests from the database? Is API Management capable of that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4cc2d26-95f1-a809-8d21-251fa973b084
* Version Independent ID: d452c096-bbea-6b65-36d1-cd56337493ca
* Content: [Real-time asset tracking and management using IoT Central - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-asset-tracking-mgmt-iot-central)
* Content Source: [docs/solution-ideas/articles/real-time-asset-tracking-mgmt-iot-central.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/real-time-asset-tracking-mgmt-iot-central.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @ypriyay
* Microsoft Alias: **priyay**

**Comment by AjayBathini-MSFT** [comment]
@jugi92 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MughundhanRaveendran-MSFT** [comment]
@jugi92 , APIM is an Azure PAAS offering and infrastructure is not exposed. It acts as the request endpoint for the outbound requests in this architecture

**Comment by MughundhanRaveendran-MSFT** [comment]
@jugi92 Closing this issue. Please feel free to reopen if required
