### ISSUE TITLE
Platform Types not listed

### ISSUE THREAD

**Issue by jackedwards97** [MicrosoftDocs/architecture-center#3923]
Under Platform Types, the options in the table are:
+ AnyPlatform
+ iOS
+ Android
+ WindowsPhone
+ macOS
+ iOSAndroid
+ Unknown

However in the CAP list there is 
+ Android
+ iOS
+ Windows Phone
+ Windows
+ MacOS
+ Linux
+ + Any Device
+ + Any Platform

I advise amending the table to include Windows and Linux.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7fac997-1920-f24e-767a-13755b794f85
* Version Independent ID: a7fac997-1920-f24e-767a-13755b794f85
* Content: [Conditional Access framework and policies - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/security/conditional-access-framework)
* Content Source: [docs/guide/security/conditional-access-framework.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/conditional-access-framework.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @clajes
* Microsoft Alias: **clajes**

**Comment by clajes** [comment]
thanks for the feedback. I have done edits and submitted PR to adjust as suggested

**Comment by AjayBathini-MSFT** [comment]
@jackedwards97 
Thanks for reporting this! Author has created a PR for this issue and the changes should go live soon.

Closing.
