### ISSUE TITLE
feedback for ci/cd pipeline using azure devops

### ISSUE THREAD

**Issue by yakkantisravs** [MicrosoftDocs/architecture-center#3927]
[Enter feedback here]
nice

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 507afae4-129d-4da3-b559-fbd5f93c2a06
* Version Independent ID: 507afae4-129d-4da3-b559-fbd5f93c2a06
* Content: [CI/CD baseline architecture with Azure Pipelines - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-baseline)
* Content Source: [docs/example-scenario/apps/devops-dotnet-baseline.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/devops-dotnet-baseline.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by ckittel** [comment]
Thank you @yakkantisravs for the positive feedback.  Hope you have a wonderful week.

#please-close

**Comment by Naveenommi-MSFT** [comment]
Resolved
