### ISSUE TITLE
DMS does not currently support migration from Oracle to PostgreSQL.

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/architecture-center#3931]
DMS does not currently support migration from Oracle to PostgreSQL. Please fix this document.

References
https://learn.microsoft.com/en-us/azure/dms/dms-tools-matrix
https://learn.microsoft.com/en-us/azure/dms/resource-scenario-status

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0676437-a746-19de-2df2-7919004a14f0
* Version Independent ID: 35cfce4b-fc76-f140-02fb-9ac605157313
* Content: [Oracle database migration decision process - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/oracle-migrate/oracle-migration-overview)
* Content Source: [docs/example-scenario/oracle-migrate/oracle-migration-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/oracle-migrate/oracle-migration-overview.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @amberz
* Microsoft Alias: **amberz**

**Comment by AjayBathini-MSFT** [comment]
@LifeRyuto 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 70514 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
