### ISSUE TITLE
Broken links in Resilience by Design whitepaper

### ISSUE THREAD

**Issue by jwillebrands** [MicrosoftDocs/architecture-center#3933]
We've used your Failure Mode Analysis templates in the past, and I would like to do so again.
Unfortunately, the links in the Resilience by Design document no longer work.

The CID sample link, http://aka.ms/CID,  redirects to a sharepoint site I don't have access to:
```
Correlation ID: 9df49aa0-70e9-0000-f63b-4bb17547946d
Date and Time: 3/1/2023 4:19:30 AM
URL: https://microsoft.sharepoint.com/teams/CloudPOD/SitePages/DCom.aspx
User: ***
Issue Type: User not in directory.
```

The sample RMA Workbook link, http://aka.ms/RMAworkbook, no longer works at all. It redirects to Bing without any results.

Are these documents still available somewhere? If so, could these be provided on this documentation page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b1bb22b-9a56-0cbd-36c5-5f31d571900a
* Version Independent ID: 6a5b36aa-c051-c519-d6cf-61c77c3acb48
* Content: [Failure mode analysis - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/resiliency/failure-mode-analysis)
* Content Source: [docs/resiliency/failure-mode-analysis.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/resiliency/failure-mode-analysis.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by v-fearam** [comment]
We decided to delete the reference.
#please-close
