### ISSUE TITLE
Video surveillance

### ISSUE THREAD

**Issue by Hermann002** [MicrosoftDocs/architecture-center#3935]
I want help to design simple video surveillance achitecture

**Comment by AjayBathini-MSFT** [comment]
@Hermann002 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by Hermann002** [comment]
https://learn.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/cloud/connect-cameras-to-cloud

**Comment by AjayBathini-MSFT** [comment]
@Hermann002 
We are not able to open the doc link you provided its getting 404 error. 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/111562794/222663225-7266e606-1a34-4a8d-a9d0-5b67650ad49b.png">
