### ISSUE TITLE
applications not hosted in azure: getting errors about access

### ISSUE THREAD

**Issue by figuerres** [MicrosoftDocs/architecture-center#3944]
we have an application that runs on a local iis server. in testing the app with an azure app registration and configuration the app returns error messages that it can not access the azure data.
we need details on what settings and or permissions are needed for this case.

here is an example of the error:

Microsoft.Extensions.Configuration.AzureAppConfiguration.KeyVaultReferenceException:
'Key vault error. ErrorCode:Forbidden,
Key:mars-wex-payments:clientId, 
 Label:,
Etag:eI3n************,
SecretIdentifier:https://***********.vault.azure.net/secrets/***********'

RequestFailedException: The user, group or application 
'appid=**************************;iss=https://sts.windows.net/**************************/'
does not have secrets get permission on key vault 't***********1;location=centralus'. 
 
 For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287
Status: 403 (Forbidden)
ErrorCode: Forbidden

Content:
{"error":{"code":"Forbidden","message":
"The user, group or application 'appid=*************;oid=24**************ed;numgroups=19;iss=https://sts.windows.net/b************/' does not have secrets get permission on key vault '*********;location=centralus'. For help resolving this issue, please see [https://go.microsoft.com/fwlink/?linkid=2125287","innererror":{"code":"AccessDenied"}}](https://go.microsoft.com/fwlink/?linkid=2125287%22,%22innererror%22:%7b%22code%22:%22AccessDenied%22%7d%7d)}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: centralus
x-ms-client-request-id: e********************
x-ms-request-id:*******************
x-ms-keyvault-service-version: 1.9.713.1
x-ms-keyvault-network-info: conn_type=Ipv4;addr=************;act_addr_fam=InterNetwork;
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Date: Fri, 03 Mar 2023 16:27:18 GMT
Content-Length: 449
Content-Type: application/json; charset=utf-8
Expires: -1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 336f0bcf-8699-ed68-82e6-e0b2ee103680
* Version Independent ID: eaa88128-433a-09eb-7ff8-0b65e3f6afb6
* Content: [Centralized app configuration and security - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/appconfig-key-vault)
* Content Source: [docs/solution-ideas/articles/appconfig-key-vault.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/appconfig-key-vault.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @sowmyans
* Microsoft Alias: **sowmyans**

**Comment by RamanathanChinnappan-MSFT** [comment]
@figuerres 

I've delegated this to @sowsan , a content author, to review and share their valuable insights.

**Comment by v-fearam** [comment]
Hi @figuerres 


I don’t know your environment. I'm assuming that you have an [app registration](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app), and your web app is using that identity. 

It seems that you need to give [permissions](https://learn.microsoft.com/en-us/azure/key-vault/general/assign-access-policy?tabs=azure-portal

) to your identity to operate with your secrets.

I recommend leveraging the support options available in the Azure Portal if you are still facing this issue.


I will close the ticket.
