### ISSUE TITLE
Incorrect capability listed twice here

### ISSUE THREAD

**Issue by identityshell** [MicrosoftDocs/architecture-center#3948]
PIM / JIT access is not supported for AWS.  As per this article:
https://learn.microsoft.com/en-us/azure/active-directory/saas-apps/amazon-web-service-tutorial

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6b08461-26fb-d148-a749-9b61217af0f8
* Version Independent ID: 1329c651-e8f6-cc68-4205-739dfbbcef4f
* Content: [Azure AD security for AWS - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/aws/aws-azure-ad-security)
* Content Source: [docs/reference-architectures/aws/aws-azure-ad-security.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/aws/aws-azure-ad-security.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by RamanathanChinnappan-MSFT** [comment]
@identityshell 

Thanks for your feedback! We will investigate and update as appropriate.

I've delegated this to @martinekuan , a content author, to review and share their valuable insights.

**Comment by identityshell** [comment]
Hi, I've since found out that there is a way of using PIM for AWS with groups:

This article references PIM for Groups - Privileged Identity Management (PIM) for Groups (preview) - Azure Active Directory - Microsoft Entra | Microsoft Learn<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Fprivileged-identity-management%2Fconcept-pim-for-groups&data=05%7C01%7CShelley.Hill%40microsoft.com%7C6367753841ab4631cd9e08db211cf427%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638140180514139019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Bwz2%2BUlC2uVAwBorTmTOkJP8r07dBlHjUixKcx2tuS4%3D&reserved=0>


This article therefore remains valid but could be updated to reference the above article - https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/aws/aws-azure-ad-security<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2Fnam06.safelinks.protection.outlook.com%2F%3Furl%3Dhttps*3A*2F*2Flearn.microsoft.com*2Fen-us*2Fazure*2Farchitecture*2Freference-architectures*2Faws*2Faws-azure-ad-security%26data%3D05*7C01*7Ccolincha*40microsoft.com*7C637e582ff10e45a3ff5f08db1fdeebc3*7C72f988bf86f141af91ab2d7cd011db47*7C1*7C0*7C638138814555153318*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C%26sdata%3DB7NZrN5QrTmfLJxshoR8fkiN*2BBOn6AZdeyESscIo2S0*3D%26reserved%3D0__%3BJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSU!!OK3MsjU!xDrmZr1jNS1Qgpn0JFokSgFWuo6bluqw4FMbe5n3u61c_Pd4GvL7okfj5zik74Cs7mfZ5F-OHOkZf363CCXb%24&data=05%7C01%7CShelley.Hill%40microsoft.com%7C6367753841ab4631cd9e08db211cf427%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638140180513982821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=77Jz0NbJx49wfUgt6xiDUisAllcR%2BzJ5mz1PM2bUAyY%3D&reserved=0>


Kind regards

Shelley

Shelley Hill
***@***.***

**Comment by v-fearam** [comment]
#please-close
