### ISSUE TITLE
Number sceme numbering does not align with the numbering in the spreadsheet

### ISSUE THREAD

**Issue by Didlexify** [MicrosoftDocs/architecture-center#3951]
The number scheme numbering does not align with the numbering in the "Microsoft Conditional Access for Zero trust persona based policies" spreadsheet linked on the page under Recommended Conditional Access policies. This is easy to solve, but this is probably one of the best documentation documents I have seen so why shame it with this flaw? Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7fac997-1920-f24e-767a-13755b794f85
* Version Independent ID: a7fac997-1920-f24e-767a-13755b794f85
* Content: [Conditional Access framework and policies - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/security/conditional-access-framework)
* Content Source: [docs/guide/security/conditional-access-framework.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/conditional-access-framework.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @clajes
* Microsoft Alias: **clajes**

**Comment by SaibabaBalapur-MSFT** [comment]
@Didlexify 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by clajes** [comment]
will start working on it
