### ISSUE TITLE
Custom business processes

### ISSUE THREAD

**Issue by wesleyfang** [MicrosoftDocs/architecture-center#3954]
Dataflow
The data flows through the solution as follows:

The airline system communicates with a custom API hosted in [Azure API Management](https://learn.microsoft.com/en-us/azure/api-management).
A custom API coordinator receives notifications and handles incoming messages from the airline system, assigning flights to Microsoft Teams channels and sending them to [Power Apps]

my question is how custom API coordinator assigning flights to Microsoft Teams channels and sending them to [Power Apps]?

**Comment by SaibabaBalapur-MSFT** [comment]
@wesleyfang 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dlepow
please review it .

**Comment by dlepow** [comment]
Thanks for the question @wesleyfang. This aricle is intentionally a very high level solution so it shows high level data flows and services.

Adding @Zimmergren if more info should be considered in this article: https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/custom-business-processes

**Comment by v-albemi** [comment]
This is resolved by https://github.com/MicrosoftDocs/architecture-center-pr/pull/10092
