### ISSUE TITLE
Conditional Forwarders

### ISSUE THREAD

**Issue by devan10** [MicrosoftDocs/architecture-center#3956]
Hi,

Why does the document specify the on-premises Conditional Forwarder zone is database.windows.net when using a DNS forwarder VM and the Conditional Forwarders zone is privatelink.database.windows.net when using the Azure DNS Private DNS resolver?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Version Independent ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Content: [Azure DNS Private Resolver - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/azure-dns-private-resolver)
* Content Source: [docs/example-scenario/networking/azure-dns-private-resolver.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/networking/azure-dns-private-resolver.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @moorthyannadurai
* Microsoft Alias: **moannadu**

**Comment by Naveenommi-MSFT** [comment]
@devan10 
Thank you for bringing this to our attention.
I've delegated this to content author @alexbuckgit, who will review it and offer their insightful opinions.

**Comment by jocontr** [comment]
Dup of https://github.com/MicrosoftDocs/architecture-center/issues/3958
