### ISSUE TITLE
Why on-premise servers need to resolve names in private dns zones???

### ISSUE THREAD

**Issue by Jarsenal** [MicrosoftDocs/architecture-center#3958]
In the section "Traffic flow for an on-premises DNS query", why the on-premise servers would try to resolve names in private dns zones? 
In "Use a DNS forwarder VM" section, conditional forwarders are for normal PaaS zone like database.windows.net and it is a good example of how split-brain DNS is achieved in Azure. Why with private DNS resolver, the devices that need to resolve the names, have to know they need to resolve names in private zones???

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Version Independent ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Content: [Azure DNS Private Resolver - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/azure-dns-private-resolver)
* Content Source: [docs/example-scenario/networking/azure-dns-private-resolver.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/networking/azure-dns-private-resolver.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @moorthyannadurai
* Microsoft Alias: **moannadu**

**Comment by SaibabaBalapur-MSFT** [comment]
@Jarsenal 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JKirsch1** [comment]
Revisions to the article are underway in [PR 10164](https://github.com/MicrosoftDocs/architecture-center-pr/pull/10164), but an update request and a user story need to be set up before the work can continue.

**Comment by JKirsch1** [comment]
Assigning this issue to the author, who is in the process of making updates to the article in [PR 10164](https://github.com/MicrosoftDocs/architecture-center-pr/pull/10164).

**Comment by moorthyannadurai** [comment]
This issue has been addressed in below PR
https://github.com/MicrosoftDocs/architecture-center-pr/pull/10164

**Comment by jocontr** [comment]
Closing issue per above comment and PR
