### ISSUE TITLE
What about if we use more than 1 app services as backend (Geo)?

### ISSUE THREAD

**Issue by Esteban775** [MicrosoftDocs/architecture-center#3960]
[Enter feedback here]

What about if we use more than 1 app service as a backend (Geo)? because we need to put the same domain in two (or more) different app services and this is not allowed (same tenant/subscription).

Example:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/77030662/225963334-efff7457-78b7-4789-a645-5e02a2a8874c.png">

How can we get one app service with geo-redundancy in East US, Central US, and West US behind an Application Gateway and apply this recommendation about hostnames?

<img width="511" alt="image" src="https://user-images.githubusercontent.com/77030662/225964761-4bef3b89-c371-4312-a2de-13e35dbcd898.png">

Thanks as always!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5beaff9-80fa-3c91-f5c6-81c3fda8bbb6
* Version Independent ID: c5beaff9-80fa-3c91-f5c6-81c3fda8bbb6
* Content: [Host name preservation - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/best-practices/host-name-preservation)
* Content Source: [docs/best-practices/host-name-preservation.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/host-name-preservation.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @jelledruyts
* Microsoft Alias: **jelled**

**Comment by jelledruyts** [comment]
@Esteban775 thanks for reaching out! You can have the same custom host name in multiple App Service web apps - as long as they are in different Azure regions. And technically speaking, even as long as they are in different deployment stamps (aka webspaces - see [note here](https://learn.microsoft.com/azure/app-service/manage-custom-dns-migrate-domain#how-do-i-migrate-a-domain-from-another-app))! So a geo-distributed scenario with multiple apps all carrying the same host name should work just fine :-)

**Comment by Esteban775** [comment]
That's awesome! Thanks so much!, I haven't tested with two different regions, because our dev environment is just in East US.

**Comment by v-fearam** [comment]
#please-close
