### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by dvicari-fedcap** [MicrosoftDocs/architecture-center#3961]
This page was extremely helpful for us to understand and plan our Azure Front Door implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddfaa14a-8031-7723-7687-2c4bdbbfb003
* Version Independent ID: ddfaa14a-8031-7723-7687-2c4bdbbfb003
* Content: [Use Azure Front Door in a multitenant solution - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/service/front-door)
* Content Source: [docs/guide/multitenant/service/front-door.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/service/front-door.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @rajnemani
* Microsoft Alias: **ranema**

**Comment by SaibabaBalapur-MSFT** [comment]
@dvicari-fedcap 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
