### ISSUE TITLE
The documentation for Azure Storage Table's retry policy is out of date.

### ISSUE THREAD

**Issue by takekazuomi** [MicrosoftDocs/architecture-center#3964]
The information below is out of date.

> [!NOTE]
> WindowsAzure.Storage Nuget Package has been deprecated. For Azure table support, see [Microsoft.Azure.Cosmos.Table Nuget Package](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table)

https://github.com/MicrosoftDocs/architecture-center/blob/fbc1759aeeb419d85f1022e6a246e45dd3deb138/docs/best-practices/retry-service-specific.md?plain=1#L809-L810

Azure.Data.Tables is now recommended.
https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table

As always, thanks for the detailed documentation.

**Comment by SaibabaBalapur-MSFT** [comment]
@takekazuomi 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by takekazuomi** [comment]
@SaibabaBalapur-MSFT 
The link to the published document is below.
https://learn.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#table-support
The current recommendations are listed in the first entry.

**Comment by SaibabaBalapur-MSFT** [comment]
@martinekuan
please eview it.

**Comment by v-fearam** [comment]
#please-close
