### ISSUE TITLE
No guide on metrics on clusters in Azure Databricks 11.0

### ISSUE THREAD

**Issue by C0DK** [MicrosoftDocs/architecture-center#3965]
I've been reading through a variety of different documentation pages but cannot find *any* way of getting actual metrics out of Azure Databricks in the newest version.

What is officially recommended? Is it simply out of scope? We need to figure out how to know the health of the different clusters in LogAnalytics. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3db4a7e-3958-b1dc-c1db-9761cf15f9cf
* Version Independent ID: 4d673510-6eae-464b-9d19-3d81e8160f5f
* Content: [Monitor Azure Databricks - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/databricks-monitoring/)
* Content Source: [docs/databricks-monitoring/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/databricks-monitoring/index.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@C0DK 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by C0DK** [comment]
@Naveenommi-MSFT On top of improving the documentation I would, more urgently, know if this is in any way supported :smile:

**Comment by hallihan** [comment]
@C0DK Please see the new note on these articles pointing to a branch of the repo supporting Azure Databricks 11.x+ (https://github.com/mspnp/spark-monitoring/tree/l4jv2) - There is an email contact in the note in our documentation, and in the README for that branch, to reach out to Databricks for information on the roadmap for observability. #please-close
