### ISSUE TITLE
10GB Partition key limit is incorrect. It's 20GB

### ISSUE THREAD

**Issue by griffinbird** [MicrosoftDocs/architecture-center#3969]
Look under the Cosmos DB section (https://learn.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning-strategies#partitioning-azure-cosmos-db) There are a few places where 10GB should be updated to 20GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef578ecf-7b41-cac8-ba5d-2e132c337b1e
* Version Independent ID: f325ab09-f55d-42ce-5892-a116d4958d6c
* Content: [Data partitioning strategies - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning-strategies#partitioning-azure-cosmos-db)
* Content Source: [docs/best-practices/data-partitioning-strategies.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/data-partitioning-strategies.yml)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@griffinbird 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MayankBargali-MSFT** [comment]
@griffinbird Thanks for reporting this item! I have updated the doc and it will be published soon. We appreciate the feedback!
