### ISSUE TITLE
IP address for outbound endpoint in Private DNS resolver

### ISSUE THREAD

**Issue by sven5** [MicrosoftDocs/architecture-center#3977]
Hi,

in the example we see the ip address 10.0.0.19 for the outbound endpoint. Where can we gather this ip address in Azure portal?
Does this example represent a real-world scenario or is this just for documentary purposes?
I'm asking because officially there is no way to get the ip address for the outbound endpoint. In network traffic we have seen that the DNS requests originate from 5 different ip addresses from the subnet. There is no documentation for this.
Would be really helpful if you can add it to the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Version Independent ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Content: [Azure DNS Private Resolver - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/azure-dns-private-resolver)
* Content Source: [docs/example-scenario/networking/azure-dns-private-resolver.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/networking/azure-dns-private-resolver.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @moorthyannadurai
* Microsoft Alias: **moannadu**

**Comment by v-fearam** [comment]
Hi @sven5 

Sorry for the delay. 

That is just a documentary proposal. 

Outbound endpoints are also part of the private virtual network address space where the private resolver is deployed. [An outbound endpoint is associated with a subnet, but isn't provisioned with an IP address like the inbound endpoint.](https://learn.microsoft.com/en-us/azure/dns/private-resolver-endpoints-rulesets#outbound-endpoints)

[Here a simple complete example, here is not needed to configure that](https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-get-started-portal)


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close

**Comment by sven5** [comment]
Hi @v-fearam 
Great news. Thank you, now it's very clear.
