### ISSUE TITLE
It isn't clear how "Use asynchronous parallel processing" helps with minimized coordination

### ISSUE THREAD

**Issue by lets-data** [MicrosoftDocs/architecture-center#3979]
From the article: 

"Use asynchronous parallel processing. If an operation requires multiple steps that are performed asynchronously (such as remote service calls), you might be able to call them in parallel, and then aggregate the results. This approach assumes that each step does not depend on the results of the previous step."

It isn't clear to me how this helps with minimizing coordination - I do understand that the parallel call approach is efficient but it is also more complex than serial calls.  I may be missing something that the author wanted to convey - do look into this and see if an update might help clarify this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de5c202d-cbea-a99e-c9c0-d4688121d797
* Version Independent ID: 712375b6-5116-f734-3bcc-0466184ec885
* Content: [Minimize coordination - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/minimize-coordination)
* Content Source: [docs/guide/design-principles/minimize-coordination.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/design-principles/minimize-coordination.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by ManoharLakkoju-MSFT** [comment]
@lets-data 
Thanks for your feedback! We will investigate and update as appropriate.
