### ISSUE TITLE
PowerApps CICD Information

### ISSUE THREAD

**Issue by vammatm** [MicrosoftDocs/architecture-center#3981]
Hello, 

Could you please share more info of the architecture that you guys propose to implement a CI/CD Pipeline for PowerApps, such as:
potential use cases, alternative services, implementation considerations, or pricing guidance

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4968f751-e9d6-6a37-c650-908531992510
* Version Independent ID: f9bf0889-546c-eb18-cfa5-72b42fae1fea
* Content: [CI/CD for Microsoft Power Platform - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform)
* Content Source: [docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @sarahparkes
* Microsoft Alias: **meparkes**

**Comment by AjayBathini-MSFT** [comment]
@vammatm 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by vammatm** [comment]
This is the link I was reading:
https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 84803 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
