### ISSUE TITLE
What about Defender for Cloud

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3983]
Is there a reason that Defender for Cloud is not included in this architecture?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f20e9f5-36cd-041c-4e75-b0a29552587b
* Version Independent ID: 9f20e9f5-36cd-041c-4e75-b0a29552587b
* Content: [Azure landing zones - Bicep modules design considerations - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/landing-zones/bicep/landing-zone-bicep)
* Content Source: [docs/landing-zones/bicep/landing-zone-bicep.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/landing-zones/bicep/landing-zone-bicep.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by YashikaTyagii** [comment]
@DeanGross 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by jtracey93** [comment]
@ckittel this part of the table? 
![image](https://github.com/MicrosoftDocs/architecture-center/assets/41163455/0842a0c0-1c69-4c45-9b2e-6ba951721aef)

**Comment by ckittel** [comment]
That might work.

Is there room in the table for

| Core | Security or "Defender for Cloud" or something | .... | .... |

that would give you a bit of room to talk a bit about this topic and point folks to those specific assignments?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 84801 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
