### ISSUE TITLE
> [`master333-ui-web

### ISSUE THREAD

**Issue by ETCorps** [MicrosoftDocs/architecture-center#3984]
> [`name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...`]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
> * Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
> * Content: [Publish a Microsoft Edge extension - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension)
> * Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/publish-extension.md)
> * Product: **microsoft-edge**
> * Technology: **extensions**
> * GitHub Login: @MSEdgeTeam
> * Microsoft Alias: **msedgedevrel**

_Originally posted by @ETCorps in https://github.com/MicrosoftDocs/edge-developer/issues/2537#issuecomment-1500653559_

**Comment by ETCorps** [comment]
name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

**Comment by mike-urnun-msft** [comment]
@ETCorps Not sure if there's anything we can address on this doc.

We will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
