### ISSUE TITLE
AVS as a compute-technology choice???

### ISSUE THREAD

**Issue by micrileyatx** [MicrosoftDocs/architecture-center#3987]
Love the flowchart, but why isn't AVS (VMWare Solution) included as potential choice?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @paolosalvatori
* Microsoft Alias: **paolos**

**Comment by AjayBathini-MSFT** [comment]
@micrileyatx 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by paolosalvatori** [comment]
@AjayBathini-MSFT @micrileyatx I'm not the author of the article, I'm just the one who made the last change 😄 there are a few compute services that miss in the flowchart like Azure Batch or Azure CycleCloud.

**Comment by stephen-sumner** [comment]
@micrileyatx - I know it's been a while. After review, AVS is currently outside the scope of this current article, but it's still on our radar for future improvements.

**Comment by stephen-sumner** [comment]
#please-close
