### ISSUE TITLE
Large-scale custom natural language processing yes please!

### ISSUE THREAD

**Issue by mjturtora** [MicrosoftDocs/architecture-center#3988]
I've been building a FAX to NLP solution for health EMR data (millions of documents). I have the OCR working and am considering using Batch to process all my files in advance of downstream NLP. But I just found this architecture to do something similar with a Spark framework. 

https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/large-scale-custom-natural-language-processing

It might be a better way to go. The "pre-amble" says, "This article is a solution idea. If you'd like us to expand the content with more information, such as potential use cases, alternative services, implementation considerations, or pricing guidance, let us know by providing [GitHub feedback].

So, Yes please!?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01b1e6db-9ea1-a8ce-439e-c78c2af49cf8
* Version Independent ID: 01b1e6db-9ea1-a8ce-439e-c78c2af49cf8
* Content: [Large-scale custom natural language processing - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/large-scale-custom-natural-language-processing)
* Content Source: [docs/solution-ideas/articles/large-scale-custom-natural-language-processing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/large-scale-custom-natural-language-processing.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @msteller-Ai
* Microsoft Alias: **msteller**

**Comment by AjayBathini-MSFT** [comment]
@mjturtora 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 84796 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
