### ISSUE TITLE
The link to Compare services seems broken

### ISSUE THREAD

**Issue by lanicolas** [MicrosoftDocs/architecture-center#3989]
The link to compare services redirects you to asynchronous messaging options

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4503ec57-36ef-8040-b6de-5b5a1fea1590
* Version Independent ID: 509de364-6faf-e11e-41e0-c2f6cb8583f6
* Content: [Asynchronous messaging options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/messaging?toc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Ftoc.json&bc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fbread%2Ftoc.json)
* Content Source: [docs/guide/technology-choices/messaging.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/messaging.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by PageWriter-MSFT** [comment]
Thanks for the feedback. This is now fixed and should be live within 24 hours.
