### ISSUE TITLE
Visio has Handoop and should be hadoop

### ISSUE THREAD

**Issue by pierowman** [MicrosoftDocs/architecture-center#3990]
Visio has Handoop and should be hadoop

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9deb5142-8bb3-bfec-1775-bbb7f49364ed
* Version Independent ID: c1de3271-22f4-d472-f4ba-697e398c1dfa
* Content: [Disconnected AI at the edge with Azure Stack Hub - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/ai-at-the-edge-disconnected)
* Content Source: [docs/solution-ideas/articles/ai-at-the-edge-disconnected.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/ai-at-the-edge-disconnected.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@pierowman 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by JKirsch1** [comment]
[PR 10124](https://github.com/MicrosoftDocs/architecture-center-pr/pull/10124) corrects this issue, and the updates are now live in [Disconnected AI at the edge with Azure Stack Hub](https://learn.microsoft.com/azure/architecture/solution-ideas/articles/ai-at-the-edge-disconnected).

The diagram component that was marked *Handoop* is the icon for an Azure HDInsight cluster. Also, the diagram steps don't mention Hadoop. Instead, they discuss HDInsight, which is service that's based on Apache Hadoop. For these reasons, PR 10124 changes the label to *Azure HDInsight cluster* in the main diagram, the thumbnail, and the CDN Visio file.
