### ISSUE TITLE
Sample Code link is broken

### ISSUE THREAD

**Issue by andrewperis** [MicrosoftDocs/architecture-center#3991]
Unable to access the sample code zip file. Can you please update the link?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67cc1961-626e-f10c-18e6-bff804c1d4e5
* Version Independent ID: 70a0df7d-9990-a3f5-8812-918b9a7f1039
* Content: [Homomorphic encryption with SEAL - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/homomorphic-encryption-seal)
* Content Source: [docs/solution-ideas/articles/homomorphic-encryption-seal.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/homomorphic-encryption-seal.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @jocontr
* Microsoft Alias: **jocontr**

**Comment by AjayBathini-MSFT** [comment]
@andrewperis 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by v-fearam** [comment]
#please-close
