### ISSUE TITLE
Do not understand sentence

### ISSUE THREAD

**Issue by tjimnetapp** [MicrosoftDocs/architecture-center#3994]
Not certain what this sentence means: 
"Azure DCsv2-series VMs have built-in high-performance, all-flash ONTAP enterprise systems. "

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abe01137-1818-bf97-2ad1-cbb5e308f020
* Version Independent ID: c853c2cf-9456-28aa-687f-1b95c9e5ca14
* Content: [Oracle Database with Azure NetApp Files - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/file-storage/oracle-azure-netapp-files)
* Content Source: [docs/example-scenario/file-storage/oracle-azure-netapp-files.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/file-storage/oracle-azure-netapp-files.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **deannag**

**Comment by AjayBathini-MSFT** [comment]
@tjimnetapp 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by BryanLa** [comment]
@tjimnetapp , @lukemurraynz - thanks for your contributions. The PR has been approved for merge so this will be updated and republish within the next 24 hours.

#please-close
