### ISSUE TITLE
Compare Messaging Services Gets Routed to incorrect page

### ISSUE THREAD

**Issue by firrasaltaher** [MicrosoftDocs/architecture-center#3995]
Compare Messaging Services link forces users to instead land on this page.  The hyper link no longer references the architecture-center space, but instead Event Hubs, and routes users back to this page using this url: https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/messaging instead of https://learn.microsoft.com/en-us/azure/technology-choices/compare-messaging-services

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4503ec57-36ef-8040-b6de-5b5a1fea1590
* Version Independent ID: 509de364-6faf-e11e-41e0-c2f6cb8583f6
* Content: [Asynchronous messaging options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/messaging)
* Content Source: [docs/guide/technology-choices/messaging.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/messaging.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by AjayBathini-MSFT** [comment]
@firrasaltaher 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by hallihan** [comment]
@firrasaltaher Can you provide more specifics as to what isn't linked as expected? It's not uncommon for the Azure Architecture Center to link to product documentation for content like that found at: https://learn.microsoft.com/azure/service-bus-messaging/compare-messaging-services

**Comment by skabou** [comment]
It appears this is now linking properly.
If you are still experiencing an issue please re-open with additional information.
