### ISSUE TITLE
Authentication is not considered

### ISSUE THREAD

**Issue by rogerknecht** [MicrosoftDocs/architecture-center#3997]
Hello, when choosing between those services in my opinion a key component, the authentication is not considered. Does the app needs to have Kerberos, NTLM, OAuth, OpenID? AAD / AD etc.

kind regards
Roger

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @paolosalvatori
* Microsoft Alias: **paolos**

**Comment by paolosalvatori** [comment]
Thanks @rogerknecht, will consider this aspect in the next permutation of the article. However, authentication is more an aspect that pertains to the workloads than the hosting platform. We have several customers using Azure Active Directory as well as third-party identity providers.

**Comment by RamanathanChinnappan-MSFT** [comment]
@rogerknecht 

Thanks for your feedback! We will investigate and update as appropriate.

I've delegated this to @paolosalvatori  a content author, to review and share their valuable insights.

**Comment by paolosalvatori** [comment]
Hi @RamanathanChinnappan-MSFT The Azure Architecture Center team decided to add me as the author of the article, but I'm not the author of the article, I'm just the last updater. The article was created and updated over time by several people.  cc: @ckittel

**Comment by stephen-sumner** [comment]
@rogerknecht - Thank you so much for the feedback. As @paolosalvatori, noted this is about platform decisions, and for now, authentication isn't a primary driver at the platform level. We will remain cognizant of this in future iterations of the article and potentially create additional guidance for authentication decisions.

I'm going to close this thread. Thank you so much for the feedback! Please let us know if you have any other questions.
