### ISSUE TITLE
Using default domains will break the AppGw-APIM connectivity without warning

### ISSUE THREAD

**Issue by hugodamiaodias** [MicrosoftDocs/architecture-center#3998]
Section: https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/apis/protect-apis#update-an-existing-application-gateway-via-the-portal

On point 2 we refer that "If you're using the default domain name of the API management service, you don't need a certificate. Application Gateway will be able to use the default certificate."

Although the above is true, APIM will eventually switch the certificates (even before expiry dates) and no warning will be given to the user.
=> This will result in all connectivity between Application Gateway and APIM being broken, without warning.

We should place the Domain Certificate Options (https://learn.microsoft.com/en-us/azure/api-management/configure-custom-domain?tabs=custom#domain-certificate-options) warning in the article, advising the user to use custom domains, so that he can control the validity of the required certificates:

Warning
If you require certificate pinning, please use a custom domain name and either a custom or Key Vault certificate, not the default certificate or the free, managed certificate. We don't recommend taking a hard dependency on a certificate that you don't manage.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/apis/protect-apis#update-an-existing-application-gateway-via-the-portal)
* Content Source: [docs/reference-architectures/apis/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/apis/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **robbag**

**Comment by RamanathanChinnappan-MSFT** [comment]
@hugodamiaodias 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 87903 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
