### ISSUE TITLE
Async pattern does not support Application Insight logging

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/architecture-center#4007]
Can you confirm that for async functions, Application Insight logging works? We are working with a Java codebase and it appears that when we implement an async function, Application Insight logging no longer works.

Seems to be the same issue with Python https://github.com/Azure/azure-functions-python-worker/issues/898

We are only implementing async due to the hard 230 second timeout from Azure Load Balancer, this issue was our first suprising disappointment.

Now that we have implemented async, we discover that Application Insights doesn't work. For a "headless" function it's critical to have back end logging to see what's going in.

If Application Insights doesn't work for the async pattern, please make it clear in the doco
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/async-request-reply.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@ElectricLlama 
Thank you for bringing this to our attention.
I've delegated this to content author @martinekuan, who will review it and offer their insightful opinions.
