### ISSUE TITLE
Azure Front Door doesn't support WebSockets

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/architecture-center#4011]
The prior issue on this, [Azure Front Door doesn't support Web Sockets (MicrosoftDocs/architecture-center #1891)](https://github.com/MicrosoftDocs/architecture-center/issues/1891) was closed without resolution, and no further responses are being provided by the team on that issue. People are still asking for information there. 

In the [Azure feedback site feature request (*Support WebSocket connections on Azure Front Door*, 4 years old, 40 comments, 2,371 upvotes)](https://feedback.azure.com/d365community/idea/c8b1d257-8a26-ec11-b6e6-000d3a4f0789), there's no update from the team as to what's going on with it. Devs are still posting comments there without updates from the team.

There was an indication [from a team member (@gball14) on the GH issue (October, 2022)](https://github.com/MicrosoftDocs/architecture-center/issues/1891#issuecomment-1284754716) that it might reach public preview last month (March, 2023). That doesn't seem to have occurred.

I'm still [maintaining a remark in the official Blazor docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-7.0#client-connections) on WebSockets support in AFD. I'd like to update that remark to let devs know where the feature is on the roadmap.

What's the current status on WebSockets for AFD?

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 936c85d9-c953-2def-c399-77cbda32b24d
Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#feedback)
Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
Service: architecture-center
Sub-service: reference-architecture
GitHub Login: @sharad4u
Microsoft Alias: pnp

**Comment by Naveenommi-MSFT** [comment]
@guardrex 
Thank you for bringing this to our attention.
I've delegated this to content author @sharad4u, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@sharad4u 
Could you please review add comments on this, update as appropriate.

**Comment by guardrex** [comment]
@Naveenommi-MSFT ... Can you ping someone from the product unit to respond? If @sharad4u is a product unit member, can you ping someone else?

This question has been asked by (apparently) ***thousands*** of developers over several years, and I'd like to resolve it in the Blazor docs because it bears on using AFD with Blazor Server apps that rely upon SignalR with a default/suggested WebSockets connection.

Even if the answer is 'no comment' 😆, even that would be ***an answer*** 😄 that I work off of for official Blazor doc coverage along the lines of 'AFD *may* support WebSockets in the future.'

**Comment by Naveenommi-MSFT** [comment]
@Rick-Anderson
Could you please review add comments on this, update as appropriate.

**Comment by guardrex** [comment]
I work with @Rick-Anderson, and he's not going to know the answer to this question.

I'll inquire internally via management.

**Comment by guardrex** [comment]
I did inquire internally on it, and when I half-jokingly wrote earlier ...

> Even if the answer is 'no comment' 😆, even that would be an answer 😄

... that turned out ***to be the answer***. The answer from management ***IS*** "no comment" at this time. That's all I'm permitted to say.

**Comment by aiakubovich** [comment]
any updates?

**Comment by JoshJarabek7** [comment]
AFD WebSockets when

**Comment by sagarjain13** [comment]
> Guys don't worry, I'm going to switch from Front Door to Application Gateway.
> 
> And I know that the moment I finish switching will be the day they decide to launch AFD WebSockets. 👍

You won't be alone, I am also starting now.
