### ISSUE TITLE
Explaining the how is missing in this documentation

### ISSUE THREAD

**Issue by khalilCodeX** [MicrosoftDocs/architecture-center#4012]
[Enter feedback here]
Many incoming links to this page is highlighted on how does competing consumer pattern works. However, the explanation is void of it rather generic in telling the why it is good. How does smart consumer work here. Who manages which consumer for which message and what if more consumers needed to be spun up, which service assesses the need? Is there a service discovery node and is there a zookeeper.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9425297d-8ddb-c092-5c2a-79015f4e8954
* Version Independent ID: 95fcd443-8a9f-0838-e73a-c6578f2d57f8
* Content: [Competing Consumers pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/competing-consumers)
* Content Source: [docs/patterns/competing-consumers.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/competing-consumers.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@khalilCodeX 
Thank you for bringing this to our attention.
I've delegated this to content author @martinekuan, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@martinekuan 
Could you please review add comments on this, update as appropriate.

**Comment by v-fearam** [comment]
Hi @khalilCodeX

Sorry for the delay. 


[Competing Consumers pattern](https://learn.microsoft.com/en-us/azure/architecture/patterns/competing-consumers) enables multiple concurrent consumers to process messages received on the same messaging channel (it is usually implemented using a queue system).

   

   It is a generic idea, and it depends on implementation details. 

Each consumer asks for a message to the queue, processes it and asks for the next message. The queue is FIFO, so when a consumer asks for a message, it is going to get the oldest at that moment. There is not a service discovery, each consumer has the connection string to the queue and starts pulling-processing data.

   In this approach all the consumers are able to handle all messages.  If you like to create some consumer for same messages and some for others, you could use something like [Priority Queue pattern](https://learn.microsoft.com/en-us/azure/architecture/patterns/priority-queue) and some technology like [Service Bus Topic](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions) as messaging manager.
 
   How many consumers. In Azure, you could manage the [way to scale](https://learn.microsoft.com/en-us/azure/architecture/best-practices/auto-scaling), for example, [Event-Diven scaling Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/event-driven-scaling). An interesting measure for scaling in this context is the size of the queue ([example](https://learn.microsoft.com/en-us/azure/azure-functions/functions-target-based-scaling?tabs=v5%2Ccsharp#event-hubs)For Azure Event Hubs, Azure Functions scales based on the number of unprocessed events distributed across all the partitions in the event hub).

The [solution section](https://learn.microsoft.com/en-us/azure/architecture/patterns/competing-consumers#solution) has a good set of benefits. You could provide some suggestions if you find something interesting to add.

I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
