### ISSUE TITLE
Missing list of official Azure Landing Zone accelerators

### ISSUE THREAD

**Issue by oliverlabs** [MicrosoftDocs/architecture-center#4017]
Some of the types are collated here: https://aka.ms/alz/aac. This list is a good start, but it is not a comprehensive list of official Azure Landing Zones (e.g. the ones published in GitHub _Azure_ organisation) according to my research. I collated a more comprehensive list in my repo [here](https://github.com/oliverlabs/alz-catalogue). I'd be happy to contribute to the https://aka.ms/alz/aac list to make it more comprehensive.

Proposal:
1. Add more Application ALZ accelerators (e.g. Data (Cloud-analytics), Spring Apps, Azure Container Apps).
2. Add a table about Scenario-specific Landing Zones
3. Add a table about Custom Purpose Landing Zones

**Comment by Naveenommi-MSFT** [comment]
@oliverlabs 
Thank you for bringing this to our attention.
I've delegated this to content author @, who will review it and offer their insightful opinions.

**Comment by oliverlabs** [comment]
Any comments @RobBagby ?

**Comment by oliverlabs** [comment]
bump

**Comment by oliverlabs** [comment]
closing as no response.

**Comment by ckittel** [comment]
@oliverlabs, feel free to reach out to Rob directly on Teams.  He might be able to share a bit of the roadmap for ALZ accelerators in AAC.
