### ISSUE TITLE
Azure Data Lake Analytics

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/architecture-center#4018]
It may be worth mentioning on this page that this service is about to be retired. It's thus not suitable as a technology choice for any new solutions.

https://azure.microsoft.com/en-us/updates/migrate-to-azure-synapse-analytics/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60cbefa1-b1c1-0edc-cdf7-4cae8a8ca2f5
* Version Independent ID: c6850420-2cc7-d17a-6adb-b4e69399efd7
* Content: [Data lakes - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-lake)
* Content Source: [docs/data-guide/scenarios/data-lake.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/scenarios/data-lake.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @PRASADA1207
* Microsoft Alias: **prasada**

**Comment by ManoharLakkoju-MSFT** [comment]
@VitalyMCT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 87891 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
