### ISSUE TITLE
Azure AD workload identity is not in Preview

### ISSUE THREAD

**Issue by jvargh** [MicrosoftDocs/architecture-center#4019]
Azure AD workload identity is not in Preview

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9e5ee22-d60b-7f75-5c7c-6527032f33f7
* Version Independent ID: 72c0059f-72e1-551b-b37b-0cbb09b52ebc
* Content: [Advanced Azure Kubernetes Service (AKS) microservices architecture - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices-advanced)
* Content Source: [docs/reference-architectures/containers/aks-microservices/aks-microservices-advanced.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-microservices/aks-microservices-advanced.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@jvargh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
Thanks! I've pushed a change that should go live within about 24 hours to remove the two preview notices from this article.
