### ISSUE TITLE
Re-write of non-finetuned in-context learning sections

### ISSUE THREAD

**Issue by nicholasdbrady** [MicrosoftDocs/architecture-center#4026]
Can we guide developers away from fine-tuning since it is largely unavailable and maturity of generative AI approaches with later models are steering us toward using turbo for in-context learning and better system messaging to improve model steerability. It is important to share how gpt-35-turbo can even be used for non-conversational tasks too such as summarization.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3026912b-cf94-e0fb-0b83-6f78219b24e0
* Version Independent ID: 3026912b-cf94-e0fb-0b83-6f78219b24e0
* Content: [Query-based document summarization - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/ai/query-based-summarization)
* Content Source: [docs/guide/ai/query-based-summarization.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/ai/query-based-summarization.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @raniabayoumy
* Microsoft Alias: **rabayoum**

**Comment by AjayBathini-MSFT** [comment]
@nicholasdbrady 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 88755 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
