### ISSUE TITLE
to much detail that is a repeat of other information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#4028]
Given that this is a page about architecture, all of the step by step instructions for adding a TI indicator are unnecessary and a repeat of what is already available in the Sentinel documentation, it would be better to just have a link over to that documentation so that this page could stay focused on the architectural topics of WHAT can and should be done, not necessarily HOW to do the implementation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb40dd7-0e77-0f95-8070-95978cd4a90c
* Version Independent ID: 4476618b-beb5-c8c4-ec8b-787db30643fb
* Content: [Cyber threat intelligence in Microsoft Sentinel - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/data/sentinel-threat-intelligence)
* Content Source: [docs/example-scenario/data/sentinel-threat-intelligence.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/sentinel-threat-intelligence.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
Hey there @DeanGross -  Thanks for that feedback (and all the others that you have provided recently!).  This is a genuine question, not an "ask" or a "deflection" -- but would you be interested at all in learning how to contribute for ideas like these?  The team that works on this stuff has a lot of priorities, and honestly a work item like this would have a really hard time getting prioritized.  Not saying it won't, just historically, might not be one that rises to the top.  But, we are open sourced, which does allow folks with great ideas to jumpstart the process for us.  Again, this isn't an "ask" of you, but instead just a offer if you'd like to learn more!

**Comment by Naveenommi-MSFT** [comment]
@DeanGross 
Thank you for bringing this to our attention. I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@martinekuan 
Could you please review add comments on this, update as appropriate.

**Comment by skabou** [comment]
#please-close
