### ISSUE TITLE
Link to Visio is broken

### ISSUE THREAD

**Issue by vestergaardj** [MicrosoftDocs/architecture-center#4033]
Hi 

The link provided for the architecture Visio file is broken:
https://arch-center.azureedge.netazure-near-realtime-data-processing.vsdx/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3699e353-3a93-fd94-3d88-884558f83635
* Version Independent ID: 3699e353-3a93-fd94-3d88-884558f83635
* Content: [Near real-time lakehouse data processing - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/data/real-time-lakehouse-data-processing)
* Content Source: [docs/example-scenario/data/real-time-lakehouse-data-processing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/real-time-lakehouse-data-processing.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @pratimav0420
* Microsoft Alias: **prvalava**

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.
