### ISSUE TITLE
Would be good to provide guidance on how to increase Circuit Breaker sensitivity by partitioning invocations appropriately.

### ISSUE THREAD

**Issue by kalyanaj** [MicrosoftDocs/architecture-center#4041]
Currently, the documentation talks about "Resource Differentiation" (with the example of different shards) which is good. However, one related situation that would be good to cover in the guidance is about "sensitivity": e.g., failures in one invoked RPC method (say the "cancel order" operation) shouldn't affect the circuit breaker state for other RPC methods in the same service (say the "place order" or "update order" operations). 

For this, to increase sensitivity, it would be good to give guidance that developers must refactor code to partition RPC invocations that need separate circuit breaking. When partitioning to increase sensitivity, partitioning must be performed with respect to the scope of the circuit breaker, at minimum: for example, the callsite, the method, or the client.

This is based on the learnings from the paper at: https://dl.acm.org/doi/pdf/10.1145/3542929.3563466

(From the paper)
**Sensitivity**. Sensitivity is the property that indicates how the circuit breaker state — the counters that determine state transitions between open, closed, and half-open — is partitioned with respect to the RPC that is being invoked. For example, whether that circuit breaker is sensitive to the invoked service, the RPC method, or the arguments provided to the RPC when invoked.
**Partitioning**: To increase sensitivity, developers must refactor code to partition RPC invocations that need separate circuit breaking.
**Scope Partitioning**: When partitioning to increase sensitivity, partitioning must be performed with respect to the scope of the circuit breaker, at minimum: for example, the callsite, the method, or the client

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16660c68-2989-3b3b-21cb-1cf0d325070e
* Version Independent ID: e65d705e-3a0a-9ea9-382e-1ed25a704fb7
* Content: [Circuit Breaker pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker)
* Content Source: [docs/patterns/circuit-breaker.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/circuit-breaker.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@kalyanaj 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 90162 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
