### ISSUE TITLE
Inconsistencies of Information

### ISSUE THREAD

**Issue by IkanBilis** [MicrosoftDocs/architecture-center#4044]
The following pattern category in catalog of patterns, particularly Geodes and Materialized View is inconsistent with information in
-[Operational Excellence patterns](https://learn.microsoft.com/en-us/azure/well-architected/devops/devops-patterns)
-[Performance Efficiency patterns](https://learn.microsoft.com/en-us/azure/well-architected/scalability/performance-efficiency-patterns)

Rate Limit Pattern is categorized as Reliability but it is not categorized in [Reliability patterns](https://learn.microsoft.com/en-us/azure/well-architected/resiliency/reliability-patterns)

[Security patterns](https://learn.microsoft.com/en-us/azure/well-architected/security/security-patterns) is not included in side navigation [Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [Cloud design patterns - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/)
* Content Source: [docs/patterns/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/index.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@IkanBilis 
Thanks for your feedback! We will investigate and update as appropriate.
