### ISSUE TITLE
from PyQt5 import QtWidgets, uic import sys from PIL import Image from PyQt5.QtGui import QPixmap from PyQt5.QtWidgets import QFileDialog import cv2 from gray import rgb_to_gray import numpy as np import keras from keras.models import load_model from keras.preprocessing.image import load_img,img_to_array import matplotlib

### ISSUE THREAD

**Issue by Bouzian29** [MicrosoftDocs/architecture-center#4045]
from PyQt5 import QtWidgets, uic import sys from PIL import Image from PyQt5.QtGui import QPixmap from PyQt5.QtWidgets import QFileDialog import cv2 from gray import rgb_to_gray import numpy as np import keras from keras.models import load_model from keras.preprocessing.image import load_img,img_to_array import matplotlib

**Comment by Naveenommi-MSFT** [comment]
@Bouzian29 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!
