### ISSUE TITLE
SQL Database is not a SaaS offering

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftDocs/architecture-center#4048]
In the decision tree, the "Relational Data" option currently points to "SQL Database," which I believe refers to Azure SQL Database. However, it's important to note that **Azure SQL Database and Azure SQL Managed Instance** are both **Platform as a Service (PaaS)** offerings. Therefore, I suggest modifying the decision tree to **categorize "Relational Data" under PaaS** and **include** both **Azure SQL Database and Azure SQL Managed Instance** as possible data store options.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88559925-9b9e-d9b3-ddb6-08306692c17b
* Version Independent ID: a25055cb-7cfe-28a0-1c66-06172c037128
* Content: [Data store decision tree - Azure Application Architecture Guide](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)
* Content Source: [docs/guide/technology-choices/data-store-decision-tree.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/data-store-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 92055 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
