### ISSUE TITLE
Azure B2B should be Azure AD External Identities, Current Link Wrong

### ISSUE THREAD

**Issue by Pawel-IT** [MicrosoftDocs/architecture-center#4050]
The AWS Cognito / Azure B2B entry under **"Mobile services**  is no longer correct. It takes you to regular Azure AD which is not what people want. It should take you to what Microsoft now calls Azure AD External Identities:
https://azure.microsoft.com/en-us/pricing/details/active-directory/external-identities/

Also why is this under Mobile Services anyway? Shouldn't this be identity? And the Azure AD page needs to be designed better to make this feature easier to find. It was quite the chore to find basic pricing on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/aws-professional/services#security-identity-and-access)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @martinekuan
* Microsoft Alias: **yuanzhiqu**

**Comment by YashikaTyagii** [comment]
@Pawel-IT 
Thanks for your feedback! We will investigate and update as appropriate.
