### ISSUE TITLE
SYSTEM DESIGN ROADMAP 👉🏻EDITED

### ISSUE THREAD

**Issue by NEAT2023** [MicrosoftDocs/architecture-center#4052]
![SYSTEM DESIGN](https://github.com/MicrosoftDocs/architecture-center/assets/134240554/5bd30189-479f-4a4d-b6d7-bc7f3f4416b7)

**Comment by ckittel** [comment]
It is unclear what is being asked or communicated.  @NEAT2023, I can sense your enthusiasm, but please describe more, in text, what you'd like to communicate. I'm going to close this issue as it's currently unactionable, but please do open a new one with some complete thoughts on how to improve Microsoft Learn content in this area.
