### ISSUE TITLE
Application volume group is in GA (ie no longer preview)

### ISSUE THREAD

**Issue by gvanteylingen** [MicrosoftDocs/architecture-center#4053]
Application volume group is in GA (i.e. no longer preview). Also, the full service name is Azure NetApp Files so please reword:
NetApp application volume group (preview)

to 

Azure NetApp Files application volume group

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fff09dc-014d-d685-881e-dc7d1ef353ff
* Version Independent ID: ca3d7830-d394-d280-dd35-19749ee53f6b
* Content: [SAP HANA for Linux VMs in scale-up systems - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines#storage)
* Content Source: [docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Robiro
* Microsoft Alias: **robiro**

**Comment by ckittel** [comment]
<img width="392" alt="image" src="https://github.com/MicrosoftDocs/architecture-center/assets/671075/53f1a86d-9110-480b-9181-b1a808d92a51">

Fixed.  Should be going live in about 24 hours.
