### ISSUE TITLE
SYSTEM DESIGN => PATTERNS !?

### ISSUE THREAD

**Issue by NEAT2023** [MicrosoftDocs/architecture-center#4054]
https://roadmap.sh/system-design

**Comment by ckittel** [comment]
It is unclear what is being asked or communicated. @NEAT2023, I can sense your enthusiasm (especially in #4052), but please describe more, in text, what you'd like to communicate. I'm going to close this issue as it's currently unactionable, but please do open a new one with some complete thoughts on how to improve Microsoft Learn content in this area.
