### ISSUE TITLE
Bad design,another high level bad design

### ISSUE THREAD

**Issue by leonardobravo-utilities** [MicrosoftDocs/architecture-center#4057]
Bad design,another high level bad design

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa701706-8a8a-c498-78e4-55db03e77cda
* Version Independent ID: fa701706-8a8a-c498-78e4-55db03e77cda
* Content: [Model loan credit risk and default probability - Azure Architecture Center](https://learn.microsoft.com/en-au/azure/architecture/example-scenario/ai/loan-credit-risk-analyzer-default-modeling)
* Content Source: [docs/example-scenario/ai/loan-credit-risk-analyzer-default-modeling.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/ai/loan-credit-risk-analyzer-default-modeling.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @CharithaBasani
* Microsoft Alias: **chbasani**

**Comment by AjayBathini-MSFT** [comment]
@leonardobravo-utilities 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
We'll need more specifics to act on this feedback.  Please let us know what you'd like to see changed.

**Comment by hallihan** [comment]
Without more specifics we can't really route this feedback. Closing this issue, please open another with more details if you have concerns with this architecture. #please-close
