### ISSUE TITLE
What about cloud only accounts?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#4059]
The Internals persona definition does not mention cloud only accounts for employees which appears to be an oversight, am I missing something? If so, please add this, if not, how do you recommend we handle accounts that don't get synced from Windows AD?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e956b9ba-8d95-ddae-221d-090ebbedacf2
* Version Independent ID: e956b9ba-8d95-ddae-221d-090ebbedacf2
* Content: [Conditional Access architecture and personas - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/security/conditional-access-architecture)
* Content Source: [docs/guide/security/conditional-access-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/conditional-access-architecture.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @clajes
* Microsoft Alias: **clajes**

**Comment by clajes** [comment]
@DeanGross valid comment that will be taken into considerations in a future update of this guidance. The sample personas for now represents the hybrid setup that most companies have today where most employees have their identity in an on-premises AD synced to the Azure AD. The idea with the guidance is to suggest a starter set of personas with associated policies that can/should be adjusted according to your needs.

**Comment by v-fearam** [comment]
#please-close
