### ISSUE TITLE
Please check the link under "Certificates"

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/architecture-center#4060]
Hello,

kindly check the link under "**Certificates**" on this page:

For information about other CAs that Front Door supports, see [Allowed certificate authorities for enabling custom HTTPS on Azure Front Door](https://learn.microsoft.com/en-us/azure/frontdoor/front-door-faq#does-front-door-support-self-signed-certificates-on-the-backend-for-https-connection-).

Should the link be to this page? https://ccadb.my.salesforce-sites.com/microsoft/IncludedCACertificateReportForMSFT

The currently linked page does not contain information about other CAs that Front Door supports.

Kind regards,
Anne

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af2806b1-1264-2775-4cce-083303e75b49
* Version Independent ID: 68218fb5-2335-183a-8469-9101a2d8a0ef
* Content: [AKS baseline for multiregion clusters - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-multi-region/aks-multi-cluster)
* Content Source: [docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@QueryCoordinator 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.
