### ISSUE TITLE
"APIM repository for pull request" value

### ISSUE THREAD

**Issue by Alexey-Zheltov** [MicrosoftDocs/architecture-center#4061]
Documentation not saying what value should be entered in "APIM repository for pull request".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Version Independent ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Content: [Automated API deployments using APIOps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops)
* Content Source: [docs/example-scenario/devops/automated-api-deployments-apiops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/automated-api-deployments-apiops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **risaha**

**Comment by AjayBathini-MSFT** [comment]
@Alexey-Zheltov 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.
