### ISSUE TITLE
Persona Card Example

### ISSUE THREAD

**Issue by Torxsmind** [MicrosoftDocs/architecture-center#4063]
Having a downloadable file / examples of the Persona card would help.  The embedded image is hard to read, and you have to zoom in.  Lastly examples for each suggested personal would go a long way has considering different triggers would be more visually represents.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e956b9ba-8d95-ddae-221d-090ebbedacf2
* Version Independent ID: e956b9ba-8d95-ddae-221d-090ebbedacf2
* Content: [Conditional Access architecture and personas - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/security/conditional-access-architecture)
* Content Source: [docs/guide/security/conditional-access-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/conditional-access-architecture.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @clajes
* Microsoft Alias: **clajes**

**Comment by clajes** [comment]
thanks for your feedback, - much appreciated. I have uploaded a template for personas that should be easier to work with. ref: https://github.com/microsoft/ConditionalAccessforZeroTrustResources/tree/main/Presentations

**Comment by SaibabaBalapur-MSFT** [comment]
@Torxsmind 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
