### ISSUE TITLE
AWS Control Tower is analogous to Azure Blueprints, or Azure Lighthouse?  (templating phase -vs- orchestration phase)

### ISSUE THREAD

**Issue by micrileyatx** [MicrosoftDocs/architecture-center#4065]
The page mentions Azure Blueprints as being the analogous asset to AWS Control Tower, but seems like that misses the aspect of orchestration across multiple environments - which seems more like it aligns to Azure lighthouse.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @martinekuan
* Microsoft Alias: **yuanzhiqu**

**Comment by SaibabaBalapur-MSFT** [comment]
@micrileyatx 
Thanks for your feedback! We will investigate and update as appropriate.
