### ISSUE TITLE
Implementation guidance

### ISSUE THREAD

**Issue by donk-msft** [MicrosoftDocs/architecture-center#4070]
[Enter feedback here]
The document describes at a higher level how to implement the ALZ provisioning automation. I would be very interested to learn how to implement this architecture in an Azure DevOps environment. Maybe provide a sample setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2da310dc-1543-c9c9-9863-4606afd20ba1
* Version Independent ID: 2da310dc-1543-c9c9-9863-4606afd20ba1
* Content: [Subscription vending implementation guidance - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/landing-zones/subscription-vending)
* Content Source: [docs/landing-zones/subscription-vending.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/landing-zones/subscription-vending.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ssumner
* Microsoft Alias: **ssumner**

**Comment by Naveenommi-MSFT** [comment]
@GitHubUser1339 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@mumurug-MSFT
Please review it.

**Comment by stephen-sumner** [comment]
@GitHubUser1339 - Thank you for you feedback! Just a quick question. Did you happen to check out our Bicep or Terraform modules?
- [Bicep modules](https://aka.ms/lz-vending/bicep)
- [Terraform modules](https://registry.terraform.io/modules/Azure/lz-vending/azurerm/latest).

I imagine you have and are looking for an end-to-end example implementation.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 97790 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
