### ISSUE TITLE
Drop Rstudio from DSVM  section

### ISSUE THREAD

**Issue by jsearcy1** [MicrosoftDocs/architecture-center#4077]
Hi All,

I think the section on the Data Science Virtual Machine is out of date. As far as I can tell RStudio Desktop and RStudio Server are no longer included with this virtual machine. It would be great if this was updated or alternatives to use these tools added.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2808e74b-c325-7b50-093a-b777473864b5
* Version Independent ID: e1f632cb-92ef-958e-5bf4-d250108e1c8d
* Content: [R developer's guide - R programming - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/r-developers-guide)
* Content Source: [docs/data-guide/technology-choices/r-developers-guide.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/r-developers-guide.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @AnalyticJeremy
* Microsoft Alias: **jepeach**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jsearcy1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
This article was so significantly out of date, that we are removing it from azure architecture center and have added an item to the backlog for the future to revisit what R content belongs in the architecture center.  The article will be removed by EOB on Monday.

I don't know when the larger refresh is landing but removing the "wrong" content is the highest priority now to remove direct contraction with product truth.

#please-close
