### ISSUE TITLE
"The solution" = "This article"?

### ISSUE THREAD

**Issue by FRFR-LO** [MicrosoftDocs/architecture-center#4079]
Please check the page here: https://learn.microsoft.com/en-us/azure/architecture/example-scenario/manufacturing/teamcenter-plm-netapp-files

The beginning of the first sentence sounds confusing: "**The solution** demonstrates how to use [Azure NetApp Files](https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-introduction) as a storage solution for Siemens Teamcenter product lifecycle management (PLM)."

Could it rather be "**This article** demonstrates how to use [Azure NetApp Files](https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-introduction) as a storage solution for Siemens Teamcenter product lifecycle management (PLM)." ?

Best regards,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29a0e1ee-1e2a-9e03-db3f-904ce0b382de
* Version Independent ID: 29a0e1ee-1e2a-9e03-db3f-904ce0b382de
* Content: [Use Teamcenter PLM with Azure NetApp Files - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/manufacturing/teamcenter-plm-netapp-files)
* Content Source: [docs/example-scenario/manufacturing/teamcenter-plm-netapp-files.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/manufacturing/teamcenter-plm-netapp-files.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @gvanteylingen
* Microsoft Alias: **b-gevant**

**Comment by RamanathanChinnappan-MSFT** [comment]
@FRFR-LO

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by gvanteylingen** [comment]
I approve of this change. Please implement.
