### ISSUE TITLE
The samples could be better

### ISSUE THREAD

**Issue by 1AUS-Technology** [MicrosoftDocs/architecture-center#4081]
The samples could be better if the project names were not "Sample 1", "Sample 2", etc..
The code should be clean and contain proper implementation.

Sample 4 has not contained all code related to claim checks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1970e0cd-53ae-02f6-479b-9ca386a5220e
* Version Independent ID: 8a81baa3-61c2-a8f6-540c-9a239583b8d6
* Content: [Claim-Check pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/claim-check)
* Content Source: [docs/patterns/claim-check.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/claim-check.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @yorek
* Microsoft Alias: **damauri**

**Comment by RamanathanChinnappan-MSFT** [comment]
@1AUS-Technology 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by yorek** [comment]
@MayankBargali-MSFT I'm not working on this things anymore, not sure who is working on this now

**Comment by hallihan** [comment]
@1AUS-Technology can you provide more detail on exactly what is missing from the linked samples?

**Comment by 1AUS-Technology** [comment]
@hallihan I had put the comments when I opened the ticket. For your reference, here they are:

_The samples could be better if the project names were not "Sample 1", "Sample 2", etc..
The code should be clean and contain proper implementation.

Sample 4 has not contained all code related to claim checks._

The link to the samples is here 
https://github.com/mspnp/cloud-design-patterns/tree/master/claim-check/code-samples

If you could, could you please make the code like you would write in production apps? That would help newbies to learn more.

Thanks.

**Comment by hallihan** [comment]
@1AUS-Technology Thanks for the feedback.  Updating these samples is not on our roadmap currently.  Since they are intended to illustrate a concept, they are intentionally simplified. We'll keep your feedback in mind the next time these are scheduled for a refresh. #please-close
