### ISSUE TITLE
Cost optimization using old H series

### ISSUE THREAD

**Issue by omarnun** [MicrosoftDocs/architecture-center#4085]
On the Cost Optimization section there are some examples using VM H-series: https://learn.microsoft.com/en-gb/azure/architecture/example-scenario/infrastructure/video-rendering?source=docs#cost-optimization

This series were retired on August 2022: https://azure.microsoft.com/en-us/updates/hseries-azure-virtual-machines-will-be-retired-by-31-august-2022/

Please update https://learn.microsoft.com/en-gb/azure/architecture/example-scenario/infrastructure/video-rendering?source=docs#cost-optimization with an active VM size.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd6ec10-1905-b2c8-8e85-896351daa502
* Version Independent ID: 55ab6cc5-1b8c-d59b-77b9-1e6d11a9e07c
* Content: [3D video rendering - Azure Architecture Center](https://learn.microsoft.com/en-gb/azure/architecture/example-scenario/infrastructure/video-rendering?source=docs)
* Content Source: [docs/example-scenario/infrastructure/video-rendering.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/video-rendering.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@omarnun 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
The code for this has also been deleted, so the deploy button doesn't work.

@RobBagby, should we get HPC content team involved to do a maintenance pass?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 100215 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
