### ISSUE TITLE
Question on the Architecture diagram

### ISSUE THREAD

**Issue by randolphnz** [MicrosoftDocs/architecture-center#4088]
In the step 2 of the Dataflow, it says "Continuous integration exports the solution from the development environment and commits files to Azure Repos". 

So for the step 2 in the Architecture diagram, I wonder if the direction of the arrow is from Power Platform DEV environment to Build Pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4968f751-e9d6-6a37-c650-908531992510
* Version Independent ID: f9bf0889-546c-eb18-cfa5-72b42fae1fea
* Content: [CI/CD for Microsoft Power Platform - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform?WT.mc_id=M365-MVP-5003693)
* Content Source: [docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @sarahparkes
* Microsoft Alias: **meparkes**

**Comment by ManoharLakkoju-MSFT** [comment]
@randolphnz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
I've reached out to Sarah Parkes internally to see if she can assist.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 100213 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
