### ISSUE TITLE
Missing diagrams

### ISSUE THREAD

**Issue by harold-reed-deloitte** [MicrosoftDocs/architecture-center#4089]
https://learn.microsoft.com/en-us/azure/architecture/guide/ai/compliance-risk-analysis
There are missing diagrams from the PPTX.
https://learn.microsoft.com/en-us/azure/architecture/guide/ai/media/compliance-risk-analysis-diagram-solution-architecture.png#lightbox : is not in the PPTX
Are they in another location?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d9c082a-2e3d-2590-cebe-07ed385fbe4a
* Version Independent ID: 2d9c082a-2e3d-2590-cebe-07ed385fbe4a
* Content: [Compliance risk analysis by using Azure Cognitive Search - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/ai/compliance-risk-analysis)
* Content Source: [docs/guide/ai/compliance-risk-analysis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/ai/compliance-risk-analysis.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @andreaskopp
* Microsoft Alias: **akopp, cfernandesdo, joamart**

**Comment by ManoharLakkoju-MSFT** [comment]
@harold-reed-deloitte 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi @harold-reed-deloitte
In the section [Solution Overview](https://learn.microsoft.com/azure/architecture/guide/ai/compliance-risk-analysis#solution-overview), all the pictures point out the same pptx.

The link is https://arch-center.azureedge.net/US-1989213-compliance-risk-analysis.pptx, and it is working for me. The image that you pointed out is in slide 3.


I'll close the ticket, but feel free to open a new one if you still have questions.

#please-close
[US-1989213-compliance-risk-analysis.pptx](https://github.com/MicrosoftDocs/architecture-center/files/11916544/US-1989213-compliance-risk-analysis.pptx)
