### ISSUE TITLE
out of date

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/architecture-center#4090]
This content applies to the App Service Environment v2 which is out of date. A Zone redundant ASEv3 has improved this deployment pattern. This design should warn it is for the ASEv2 until it is updated to cater for a zone redundant ASEv3

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4fdc9a3-db55-b6f9-0d36-33bd98be3194
* Version Independent ID: 572bf19f-773c-6362-5c43-c7a0db68c384
* Content: [HA enterprise deployment using ASE - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/enterprise-integration/ase-high-availability-deployment)
* Content Source: [docs/reference-architectures/enterprise-integration/ase-high-availability-deployment.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/enterprise-integration/ase-high-availability-deployment.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ManoharLakkoju-MSFT** [comment]
@iaasazure 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  It appears it has been addressed.  If you are still experiencing an issue, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
