### ISSUE TITLE
No queue?

### ISSUE THREAD

**Issue by clemensv** [MicrosoftDocs/architecture-center#4092]
It is a bit disappointing that you don't have a temporal decoupling option on the flow path, at all, but model the system as synchronous all the way through to the databases. A system that needs robustness and high reliability will typically decouple the frontend (API) from the backend (DB) using a messaging layer, for instance using Azure Service Bus and/or Azure Event Hubs. 

A cache layer should probably also feature a bit more prominently in the diagram since product catalog browsing makes up 75% of the presented scenario's traffic.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34ed51e6-265e-aae0-f552-0900a345b3be
* Version Independent ID: 34ed51e6-265e-aae0-f552-0900a345b3be
* Content: [Scalable cloud applications and SRE - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/scalable-apps-performance-modeling-site-reliability)
* Content Source: [docs/example-scenario/apps/scalable-apps-performance-modeling-site-reliability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/scalable-apps-performance-modeling-site-reliability.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **subhajch**

**Comment by ckittel** [comment]
@Subhajit-Chatterjee-MS

**Comment by Subhajit-Chatterjee-MS** [comment]
@clemensv - 
Thank you for sharing your feedback. Maybe it’s not covered explicitly in the article, but asynchronous message-based communication is pivotal to building highly available applications and the links within the next steps section had been provided for the reader to explore and understand more about it (as it can be accomplished in a few different ways based on the context). The caching layer was depicted, but I agree that it must be highlighted for better readability.  
The scope of the original article was to evangelize on the importance of applying SRE principles and practices when building solutions / products. Hence, to maintain some brevity, the diagram presented didn't dig into the specifics of all the components / Azure resources that may be necessary for the complete solution. I will add references to articles that cover patterns using Azure Service Bus, Event Hubs, and Event Grids in greater details.   
regards
Subhajit

**Comment by v-fearam** [comment]
#please-close
