### ISSUE TITLE
Would love to see a Network Planning section included as well

### ISSUE THREAD

**Issue by jharbieh-microsoft** [MicrosoftDocs/architecture-center#4095]
[Enter feedback here]

Awesome work on this architectural reference. I was looking for a Networking planning section where it lists any network addressing requirements and was able to find it in the bicep implementation example on GitHub, however, was not present within the doc itself. 

Doc ref. https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/baseline-zone-redundant?source=docs

I would have loved to see it included in the doc. A quick list of what is required would be great to have. Such as

var vnetAddressPrefix = '10.0.0.0/16'
var appGatewaySubnetPrefix = '10.0.1.0/24'
var appServicesSubnetPrefix = '10.0.0.0/24'
var privateEndpointsSubnetPrefix = '10.0.2.0/27'
var agentsSubnetPrefix = '10.0.2.32/27'

Taken from: https://github.com/Azure-Samples/app-service-baseline-implementation/blob/main/infra-as-code/bicep/network.bicep

Thanks!

Johnny Harbieh
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b40adb2-53a0-55ac-e18b-de8cb18cb8c8
* Version Independent ID: 3b40adb2-53a0-55ac-e18b-de8cb18cb8c8
* Content: [Baseline highly available zone-redundant app services web application - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/baseline-zone-redundant?source=docs)
* Content Source: [docs/reference-architectures/app-service-web-app/baseline-zone-redundant.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/app-service-web-app/baseline-zone-redundant.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by Naveenommi-MSFT** [comment]
@jharbieh-microsoft 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
#please-close
