### ISSUE TITLE
Several methods mentioned in this doc appear to be archived or unsupported

### ISSUE THREAD

**Issue by silverl** [MicrosoftDocs/architecture-center#4100]
I'm attempting to find the best way to batch R scripts in Azure in support of our data scientists' efforts and to scale out part of an ETL pipeline.

I've been running down dead ends. Several of the methods discussed on this page are no longer possible or supported, or the repos are archived.

https://github.com/Azure/aztk/ is archived.

https://github.com/Azure/aztk/wiki/SparklyR-on-Azure-with-AZTK is archived.

https://github.com/Azure/rAzureBatch is archived.

It would be nice if the R documentation were updated to reflect the current reality and help newcomers understand the supported ways that Microsoft is "fully embracing" the R programming language.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2808e74b-c325-7b50-093a-b777473864b5
* Version Independent ID: e1f632cb-92ef-958e-5bf4-d250108e1c8d
* Content: [R developer's guide - R programming - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/r-developers-guide)
* Content Source: [docs/data-guide/technology-choices/r-developers-guide.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/r-developers-guide.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @AnalyticJeremy
* Microsoft Alias: **jepeach**

**Comment by Naveenommi-MSFT** [comment]
@silverl 
Thank you for bringing this to our attention.
I've delegated this to content author @AnalyticJeremy, who will review it and offer their insightful opinions.

**Comment by ckittel** [comment]
@silverl thank you for bringing this to our attention.  We've met with @AnalyticJeremy and agreed that the article is so far out of date, that it's probably more confusing than beneficial.  We are going to remove the article and put an item in our backlog to rebuild a modern story around this.

**Comment by ckittel** [comment]
The article is removed (along with a few other confusing references in AAC).  This will likely be live today yet, if not Monday.  We've got a backlog item now to decide what AAC content should have an R developer focus.
