### ISSUE TITLE
Hi there. You should avoid using flags to represent languages. Doing so could trigger geopolitical issues.

### ISSUE THREAD

**Issue by agustd** [MicrosoftDocs/architecture-center#4101]
Hi there. You should avoid using flags to represent languages. Doing so could trigger geopolitical issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8a51dd9-65b7-5039-06d0-d096ad51d0bb
* Version Independent ID: 9c2c99ed-8d17-7865-e680-2107b7f0ebf1
* Content: [Natural language processing technology - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/natural-language-processing)
* Content Source: [docs/data-guide/technology-choices/natural-language-processing.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/natural-language-processing.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @msteller-Ai
* Microsoft Alias: **msteller**

**Comment by Naveenommi-MSFT** [comment]
@agustd 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JKirsch1** [comment]
[PR 10510](https://github.com/MicrosoftDocs/architecture-center-pr/pull/10510) address this issue by removing the flags from the architecture diagram and thumbnail of [Natural language processing technology](https://learn.microsoft.com/azure/architecture/data-guide/technology-choices/natural-language-processing).

That PR has already merged, and the changes are live: [Natural language processing technology](https://learn.microsoft.com/azure/architecture/data-guide/technology-choices/natural-language-processing)
