### ISSUE TITLE
Why is this article listed under AI/ML architectures?

### ISSUE THREAD

**Issue by krisbock** [MicrosoftDocs/architecture-center#4103]
Why is this article listed under AI/ML architectures?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7f45c3e-6598-f423-adf1-6a43ed590e2f
* Version Independent ID: f7f45c3e-6598-f423-adf1-6a43ed590e2f
* Content: [Analyze observational patient data by using OHDSI with the OMOP CDM - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/digital-health/patient-data-ohdsi-omop-cdm)
* Content Source: [docs/example-scenario/digital-health/patient-data-ohdsi-omop-cdm.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/digital-health/patient-data-ohdsi-omop-cdm.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @plooploops
* Microsoft Alias: **angee**

**Comment by Naveenommi-MSFT** [comment]
@krisbock 
Thank you for bringing this to our attention.
I've delegated this to content author @plooploops, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@plooploops 
Could you please review add comments on this, update as appropriate.

**Comment by ckittel** [comment]
@krisbock, since you're MSFT FTE, and so is Andy, you might want to ask him directly on Teams.  Not everyone has github notifications configured.

**Comment by plooploops** [comment]
Based on my understanding, once you can ETL data into the Azure SQL CDM, you can then use [Atlas](https://github.com/OHDSI/Atlas/wiki) / [Achilles](https://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:achilles) to perform analysis on your patient data sets.

Atlas does include a section for [prediction](https://github.com/OHDSI/Atlas/wiki/Prediction), which can be helpful for the clinical researchers.

**Comment by krisbock** [comment]
[like]  Kris Bock reacted to your message:
________________________________
