### ISSUE TITLE
Zero-Trust hub and spoke not possible with App Gateway V2

### ISSUE THREAD

**Issue by cfBrianMiller** [MicrosoftDocs/architecture-center#4106]
Hello,

It appears the hub and spoke architecture using a firewall and an application gateway does not support V2. V2 app gateway limitations https://learn.microsoft.com/en-us/azure/application-gateway/configuration-infrastructure#supported-user-defined-routes specifically call out the desired UDR in the hub and spoke design.

> Application Gateway intercepts the client packets and examines them. If the packets pass inspection, the Application Gateway would send the packet to the backend VM. When the packet hits Azure, a user-defined route (UDR) in the Application Gateway subnet forwards the packets to Azure Firewall Premium.

What is the recommended approach for the zero trust design?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f623b3a-09d7-d793-b007-85b59727c1df
* Version Independent ID: ec0506cd-cdba-784c-6832-ea59697dd39c
* Content: [Zero-trust network for web applications with Azure Firewall and Application Gateway - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/gateway/application-gateway-before-azure-firewall)
* Content Source: [docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by erjosito** [comment]
AppGW v2 does support UDRs. What it doesn't support is the specific UDR of 0.0.0.0/0 with a next hop other than Internet. The UDR you need in this design is for the backend subnet, not for 0.0.0.0/0.

**Comment by Naveenommi-MSFT** [comment]
@cfBrianMiller 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by erjosito** [comment]
> AppGW v2 does support UDRs. What it doesn't support is the specific UDR of 0.0.0.0/0 with a next hop other than Internet. The UDR you need in this design is for the backend subnet, not for 0.0.0.0/0.

Any other clarification required?

**Comment by ckittel** [comment]
Going to close, @cfBrianMiller please re-open if @erjosito's answer doesn't help you out.

#please-close
