### ISSUE TITLE
Jupyter Notebook link not working

### ISSUE THREAD

**Issue by PieQua** [MicrosoftDocs/architecture-center#4143]
Jupyter Notebook link not working

(404 error)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa815b05-e4be-75fd-04bb-9136b6228502
* Version Independent ID: aa815b05-e4be-75fd-04bb-9136b6228502
* Content: [Conversation summarization - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/ai/conversation-summarization)
* Content Source: [docs/guide/ai/conversation-summarization.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/ai/conversation-summarization.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @mejani
* Microsoft Alias: **mejani**

**Comment by YashikaTyagii** [comment]
@PieQua 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-albemi** [comment]
I notified Meghna Jani about this work item.

**Comment by mejani** [comment]
Hi @PieQua - making sure I understand, Are you unable to view the jupyter notebook?

**Comment by mSarts** [comment]
Closing as link appears to be working.

**Comment by PieQua** [comment]
> Closing as link appears to be working.

This link gives me a 404: https://github.com/Azure/openai-solutions/tree/conversational-summarization-v0/Solution_Notebooks/Conversational%20Summarization

**Comment by ckittel** [comment]
@mSarts and @mejani - that repo has been moved to archived and _private_ status, we will need the link removed, as those without a MSFT associated identity cannot access it.

**Comment by skabou** [comment]
It appears this issue has been resolved.  If you are still experiencing an issue with this article, please feel free to re-open with additional information.
