### ISSUE TITLE
SAP HANA on Azure Large Instances - Sunset

### ISSUE THREAD

**Issue by eric-camplin** [MicrosoftDocs/architecture-center#4144]
SAP HANA on Azure Large Instances is in sunset mode and should include the note - Suggestion that all HLI topic pages should include some version of the note

<img width="459" alt="image" src="https://github.com/MicrosoftDocs/architecture-center/assets/12022944/b20849a8-ac8a-4a05-8909-e0d9e6a94e09">

Note found on https://learn.microsoft.com/en-us/azure/sap/large-instances/hana-overview-architecture

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 297fe58b-8232-9b2a-c92e-9f7f94ec3e4e
* Version Independent ID: 3da45f17-e475-f23e-c77f-465933ed02f4
* Content: [Run SAP HANA Large Instances - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/sap/hana-large-instances)
* Content Source: [docs/reference-architectures/sap/hana-large-instances.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/sap/hana-large-instances.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @bqtrinh
* Microsoft Alias: **bentrin**

**Comment by YashikaTyagii** [comment]
@eric-camplin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by stephen-sumner** [comment]
@eric-camplin - We've added a note to the top of this page. Thank you!

**Comment by stephen-sumner** [comment]
#please-close
