### ISSUE TITLE
Duplicate obsolete page

### ISSUE THREAD

**Issue by vjirovsky** [MicrosoftDocs/architecture-center#4148]
Hello @huypub,
reg. publishing bulk of updates about WordPress section from Friday - this page is to be removed:
https://learn.microsoft.com/en-us/azure/architecture/web-apps/hosting-applications/wordpress

and got replaced with the rest pages in the last bulk. 
Please set up the redirection from this page to: 
https://learn.microsoft.com/en-us/azure/architecture/guide/infrastructure/wordpress-overview

thanks 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5dbc36d-1197-0b73-d0fe-2c9dd5f1d17d
* Version Independent ID: b2285023-1f19-d037-e1c5-18b0b65009df
* Content: [Scalable and secure WordPress on Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/web-apps/hosting-applications/wordpress)
* Content Source: [docs/web-apps/hosting-applications/wordpress.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/web-apps/hosting-applications/wordpress.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @huypub
* Microsoft Alias: **huypub**

**Comment by AjayBathini-MSFT** [comment]
@vjirovsky 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by vjirovsky** [comment]
Hi @AjayBathini-MSFT, me and @snobu are the new document authors - we have created a whole new section replacing this page (the section has been published last week) - but this page needs to be removed

**Comment by mSarts** [comment]
This request is being handled by the Aquent editorial team.

**Comment by jmart1428** [comment]
This issue has been resolved in [this PR](https://github.com/MicrosoftDocs/architecture-center-pr/pull/10632).
