### ISSUE TITLE
Document understanding

### ISSUE THREAD

**Issue by marcomameli1992** [MicrosoftDocs/architecture-center#4149]
[Enter feedback here]

The documentation is not very clear. It is not complete, some function definition is not defined and there is not an example of how the dataset is composed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3026912b-cf94-e0fb-0b83-6f78219b24e0
* Version Independent ID: 3026912b-cf94-e0fb-0b83-6f78219b24e0
* Content: [Query-based document summarization - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/ai/query-based-summarization)
* Content Source: [docs/guide/ai/query-based-summarization.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/ai/query-based-summarization.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @raniabayoumy
* Microsoft Alias: **rabayoum**

**Comment by AjayBathini-MSFT** [comment]
@marcomameli1992 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by raniabayoumy** [comment]
Could you please assign this to @noabenefraim? (principle author)

**Comment by noabenefraim** [comment]
Hello,

Thanks for your feedback. After review, please provide more specific feedback on which function definitions are missing. Additionally, please refer to the Dataset section for information on how to download the dataset and the relevant schema used. (https://learn.microsoft.com/en-us/azure/architecture/guide/ai/query-based-summarization#dataset)

#please-close
