### ISSUE TITLE
Implementation Consideration,  pricing guidance

### ISSUE THREAD

**Issue by kwamePhilip** [MicrosoftDocs/architecture-center#4150]
Hi,
I am interested in getting more information about implementation and pricing guide for this use case

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df3242be-f301-2de4-c5d6-3fbda852ed89
* Version Independent ID: 6c05f422-5e71-4c2a-7c5c-d333e9aa0fc1
* Content: [Defect prevention with predictive maintenance - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/defect-prevention-with-predictive-maintenance)
* Content Source: [docs/solution-ideas/articles/defect-prevention-with-predictive-maintenance.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/defect-prevention-with-predictive-maintenance.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@kwamePhilip 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by kwamePhilip** [comment]
https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/defect-prevention-with-predictive-maintenance

**Comment by AjayBathini-MSFT** [comment]
@kwamePhilip 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by kwamePhilip** [comment]
@AjayBathini-MSFT 
Thanks.  Will I be notified when it's updated?

**Comment by skabou** [comment]
Thank you for your feedback.  This article has been removed.

**Comment by skabou** [comment]
#please-close
