### ISSUE TITLE
Incorrect URL behind link "Create a fully qualified domain name in the Azure portal"

### ISSUE THREAD

**Issue by dtrac** [MicrosoftDocs/architecture-center#4151]
The link titled "Create a fully qualified domain name in the Azure portal" - takes you to an article that describes building a Linux VM in Azure, but does not include any details on DNS.

[Create a fully qualified domain name in the Azure portal](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-portal).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8af3a0e6-6629-3044-4bdc-4f73a6f77861
* Version Independent ID: a93c0dc1-678d-2319-d850-ca3dca213b74
* Content: [Run a Linux VM on Azure - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/linux-vm)
* Content Source: [docs/reference-architectures/n-tier/linux-vm.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/n-tier/linux-vm.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@dtrac 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
@dtrac Thank you for your feedback.  I've updated the document with a more relevant link.  If still are experiencing issues, please feel free to re-open.
