### ISSUE TITLE
Expanding the diagram to include DR

### ISSUE THREAD

**Issue by DavidPattersonAHEAD** [MicrosoftDocs/architecture-center#4152]
It would be great to see a more detailed design around AVS including stretch clusters across zones and DR across regions.

**Comment by ckittel** [comment]
Can you please provide a link to the article that you're providing feedback on?  It'll help make sure we get this directed toward the right authors here.

**Comment by DavidPattersonAHEAD** [comment]
Apologies, I followed the link from the article here and forgot to paste back in the URL.

https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-vmware-solution-foundation-networking

**Comment by ckittel** [comment]
I've contacted the author, @Mahesh-MSFT, to let them know of your request.

**Comment by Mahesh-MSFT** [comment]
Thanks for the feedback @DavidPattersonAHEAD.

[Networking considerations for Azure VMware Solution](https://learn.microsoft.com/azure/architecture/solution-ideas/articles/azure-vmware-solution-foundation-networking) as name suggests - focuses on networking :-)

Including availability and DR considerations will probably make lengthy article even more lengthy.

Topics you are interested in are already covered in following articles.

1. [Azure VMware Solution Availability Design Considerations](https://techcommunity.microsoft.com/t5/azure-migration-and/azure-vmware-solution-availability-design-considerations/ba-p/3682915)
2. [Network considerations for Azure VMware Solution dual-region deployments](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-dual-region-network-topology)

Do you want to take a look at these articles which are more aligned to your request?

Thanks!

CC: @ckittel

**Comment by DavidPattersonAHEAD** [comment]
Thank you, Mahesh.  Those links are very helpful, I appreciate the quick reply.

**Comment by ckittel** [comment]
Thank you, Mahesh and @DavidPattersonAHEAD.  I'm going to close this issue, but if there are items you'd like to see improved on those more DR-focused articles, be sure to open up a suggestion against them :)

#please-close
