### ISSUE TITLE
Need info on IPv6 support

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/architecture-center#4154]
[Enter feedback here]
I have been trying to find documentation that AFD supports IPv6 but only have found third party posts about it, the most informative being from 2018/2019. Those would apply to the classic version. 

Please add to the overview or if necessary create a new page that covers IPv6 support and any configuration requirements, and if needed any limitations like WAF does not support IPv6. That was from a very old post and may not be accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview?toc=%2Fazure%2Ffrontdoor%2Fstandard-premium%2Ftoc.json)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@cchapin2020 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 143324 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
