### ISSUE TITLE
SAGA - requires eventual consistency logic, distributed locking

### ISSUE THREAD

**Issue by tamusjroyce** [MicrosoftDocs/architecture-center#4155]
SAGA pattern requires eventual consistency logic, which is a type of distributed lock, handled in the backend.

Otherwise, it isn't SAGA. Rather, it is Durable Pattern, Event Sourcing, or maybe Application Sourcing pattern. SAGA was very specific. And has recently (within the last 5 years) been broadened. Extremely confusing, I know.

https://microservices.io/patterns/data/saga.html - I am not sure if Chris Richardson invented SAGA. But this was my first introduction to it. And we had a few discussions online. Until Chris added this distributed locking to the pattern. It was seen by tiny squares. But now the only reference is "transaction". You can't have a transaction without a lock.

The lack of eventual consistency checking locks can data corruption. So it is a critical knowledge for this pattern.

Durable pattern should be listed too. Or maybe it is called Event Sourcing or Application Sourcing pattern  [https://microservices.io/patterns/data/event-sourcing.html](https://microservices.io/patterns/data/event-sourcing.html). SAGA is different from these patterns. Azure Durable Functions utilizes a single database technology. Where a single transaction is held in the database (azure blob storage, sql server, cosmos, or netherite). SAGA, each service has its own database. So Durable Functions are not SAGA

Hopefully helpful!
-Tamus JRoyce

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28115bf1-a411-eeff-28b2-1caabaecc2f0
* Version Independent ID: 27d63984-99a6-fd06-c67f-b6226042cee8
* Content: [Saga pattern - Azure Design Patterns](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/saga/saga)
* Content Source: [docs/reference-architectures/saga/saga.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/saga/saga.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@tamusjroyce 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 143222 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
