### ISSUE TITLE
PowerPoint find need extra permission after download 

### ISSUE THREAD

**Issue by MahdiSheikhi** [MicrosoftDocs/architecture-center#4157]
Architecture PowerPoint file that mentioned for download needed extra permission after download!

https://arch-center.azureedge.net/conversation-summarization-overview.pptx

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa815b05-e4be-75fd-04bb-9136b6228502
* Version Independent ID: aa815b05-e4be-75fd-04bb-9136b6228502
* Content: [Conversation summarization - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/ai/conversation-summarization)
* Content Source: [docs/guide/ai/conversation-summarization.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/ai/conversation-summarization.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @mejani
* Microsoft Alias: **mejani**

**Comment by AjayBathini-MSFT** [comment]
@MahdiSheikhi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mSarts** [comment]
Addressed by @huypub.
