### ISSUE TITLE
Bot Framework, Teams channel and firewall setting

### ISSUE THREAD

**Issue by pui30576** [MicrosoftDocs/architecture-center#4161]
This documentation does not fully compatible with [Microsoft Bot Framework](https://www.botframework.com/)
Bot Framework requires whitelist the outbound traffic which is missing in this tutorial document.
https://learn.microsoft.com/en-us/azure/bot-service/bot-service-resources-faq-security?view=azure-bot-service-4.0#which-specific-urls-do-i-need-to-allowlist-in-my-corporate-firewall-to-access-bot-framework-services

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62849df7-a49c-f17e-6876-c3da5954789a
* Version Independent ID: a412df8a-f876-d501-6aec-5bc1f010deaa
* Content: [Secure your Microsoft Teams channel bot and web app behind a firewall - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/teams/securing-bot-teams-channel)
* Content Source: [docs/example-scenario/teams/securing-bot-teams-channel.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/teams/securing-bot-teams-channel.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @ajafry
* Microsoft Alias: **aljafry**

**Comment by SaibabaBalapur-MSFT** [comment]
@pui30576 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ajafry** [comment]
@pui30576 curious if you ran into an issue while configuring the bot as per the article? There are two service tags that are used in the firewall configuration, which should cover the whitelist you pointed out. Please let us know what specific issue you ran into without explicitly whitelisting the URLs mentioned in the other article. Thanks.

**Comment by pui30576** [comment]
Hi @ajafry 

For example, I went into an issue that the Bot Framework connect initialize the login handshake with this url https://login.botframework.com/v1/.well-known/openidconfiguration

The Bot Framework I am using is Node.js version, [botbuilder-4.20.0](https://www.npmjs.com/package/botbuilder)

I explicitly add those missing outbound domains using the FQDNs (of coz need to enable DNS proxy too...)

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 143218 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
