### ISSUE TITLE
Use Azure file shares in a hybrid environment

### ISSUE THREAD

**Issue by jersoltech** [MicrosoftDocs/architecture-center#4162]
By integrating them with Active Directory **Directory**(the second Directory should be replaced with **Domain**) Services (AD DS), you can control and limit access to AD DS users. Azure file shares then can replace traditional file servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d20e646f-ab65-35af-4eb1-2d3e96070a81
* Version Independent ID: 36462251-e273-3b97-1754-98178aa46e92
* Content: [Azure file shares in a hybrid environment - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/hybrid/azure-file-share)
* Content Source: [docs/hybrid/azure-file-share.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/azure-file-share.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @raunakjhawar
* Microsoft Alias: **ancoughl**

**Comment by navba-MSFT** [comment]
@jersoltech Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will file a PR to fix this.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 143216 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
