### ISSUE TITLE
Secure multi-tenant configuration management required

### ISSUE THREAD

**Issue by RaynaLT** [MicrosoftDocs/architecture-center#4163]
We have had to implement a custom-built external configuration store, as the Azure offerings do not allow fine-grained security configurations or different hierarchies of configuration management e.g. global, tenant-level, per portal, per database, per branch etc. The managed offerings in the Azure store e.g. Hashicorp Vault were also quite expensive. It was cheaper to simply build what we needed, but performant, secure, multi-tenant configuration management is an area where Azure could stand to improve. Given the fact that we have to cater for 1000's of B2B tenants, it is not viable to implement 1000's of single-tenanted deployments, therefore the multi-tenanted single component offering could do with some improvements.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ac5a455-0fdc-5059-cb13-2cbc554d7804
* Version Independent ID: 0ac5a455-0fdc-5059-cb13-2cbc554d7804
* Content: [Azure App Configuration considerations for multitenancy - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/service/app-configuration)
* Content Source: [docs/guide/multitenant/service/app-configuration.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/service/app-configuration.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @johndowns
* Microsoft Alias: **jodowns**

**Comment by SaibabaBalapur-MSFT** [comment]
@RaynaLT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by johndowns** [comment]
Hi @RaynaLT, thanks for sharing your experiences. I'd be interested to know a little more about how you'd ideally like to store hierarchies of configuration. Are you able to share some more details and/or examples about how you'd like to see this work, please?

**Comment by RaynaLT** [comment]
@johndowns I need to support configuration settings for multiple clients who buy our software which we run on Azure on a single AD tenant. Azure assumes that 1 AD tenant = 1 business/organization, perhaps with multiple departments, whereas our actual situation is 1 AD tenant = 1000's of businesses/organizations, which means that creating 1 Azure resource for each business/organization we support is unmaintainable operationally and from a cost perspective. 

The configuration hierarchies that I would look to use on a single Azure resource that supports potentially 100's (but not 1000's of organizations, as I can't see even a very large resource supporting that much traffic) are:
1. Global - static configuration data that all organizations we support need access to, which can then be split into publicly available vs private global data (private data can be used, but not viewed).
2. Organization level (config data that all Organization Instances can access/use)
3. Organizational Instance Level - this is a tricky one, as we have had to make this configurable due to organizational instance being either department or branches or buildings or technical instances e.g. websites or databases or a combination of all of these.

Of course, to manage the above securely on a single Azure resource will require advanced security options so that the multiple Organizations cannot ever access each others configuration data and to protect the Organizational Instances from accessing each others data (but allowing them to access each other's data if required, since they belong to the same organization).

It's a pretty tricky requirement and it goes against the grain for how Azure seems to flow naturally. We started looking at Hashicorp Vault, but ended up using a combination of Azure resources + custom code to achieve what we needed.

**Comment by johndowns** [comment]
Thanks for the extra information, @RaynaLT.

I think going with a custom approach here does sound like the right way to go, especially with the multiple layers of configuration that can potentially be overridden by more specific layers, in addition to the custom security requirements. In principle I can imagine writing some code to do this with App Configuration, but if it's working for you already then I'm sure there's no reason to change!

One side comment is that Azure AD tenants might be a red herring here. It's very common for SaaS providers who host resources on behalf of their customers to use a single Azure AD tenant, and to keep all of their resources in subscriptions linked to that tenant. In fact, we even [published some guidance on how to do this](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/isv-landing-zone). You might have different requirements, of course, but I just want to make sure there's no confusion - Azure definitely doesn't mandate that you keep each of your tenants' data in a separate Azure AD tenant or Azure subscription. Within that, you can also create either [shared or tenant-specific App Configuration stores](https://learn.microsoft.com/azure/architecture/guide/multitenant/service/app-configuration#isolation-models), but each approach has tradeoffs and it sounds like for your scenario neither fits quite right.

Thanks again for the extra information. I'll close this thread now but let me know if you have additional questions related to the article.

#please-close
