### ISSUE TITLE
SVG are just jpeg's embedded into SVG format

### ISSUE THREAD

**Issue by Pher0ah** [MicrosoftDocs/architecture-center#4167]
Please update the SVG files to be actual SVG shapes instead of fake ones with jpeg's embdded inside the SVG format. We need actual shapes so we can colour and explain concepts to customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5034ddc5-077e-1541-9b3e-479d6e35dd76
* Version Independent ID: 5034ddc5-077e-1541-9b3e-479d6e35dd76
* Content: [Conditional Access design principles and dependencies - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/security/conditional-access-design)
* Content Source: [docs/guide/security/conditional-access-design.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/security/conditional-access-design.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @clajes
* Microsoft Alias: **clajes**

**Comment by ManoharLakkoju-MSFT** [comment]
@Pher0ah 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 143208 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close

**Comment by Pher0ah** [comment]
You did not fix the issue. The svg link still goes to a jpeg.
