### ISSUE TITLE
WAF_v2

### ISSUE THREAD

**Issue by simonguertin** [MicrosoftDocs/architecture-center#4168]
I saw that the WAF has just been deprecated last week (could create one July 14 2023, but as of yesterday July 25, I get an error about the WAF being deprecated and we must use WAF_v2

Is it possible to update the article with WAF_v2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/web-apps/api-management/architectures/protect-apis)
* Content Source: [docs/web-apps/api-management/architectures/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/web-apps/api-management/architectures/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **robbag**

**Comment by ManoharLakkoju-MSFT** [comment]
@simonguertin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mike-urnun-msft** [comment]
related: https://learn.microsoft.com/en-us/answers/questions/1337527/issues-implementing-protect-apis-with-application

**Comment by ckittel** [comment]
@fabriciosanchez -- can you please address this on your article?

**Comment by ckittel** [comment]
This would be a good one for maint scope @RobBagby.  I don't think the original author is with the company anymore.

**Comment by simonguertin** [comment]
Thank you all !Envoyé de mon iPhoneLe 8 sept. 2023 à 12:18, James Barnett ***@***.***> a écrit :﻿
Closed #4168 as completed.
