### ISSUE TITLE
No mention of Static Web Apps on your web hosting comparison page

### ISSUE THREAD

**Issue by Neutrino-Sunset** [MicrosoftDocs/architecture-center#4170]
No mention of Static Web Apps on your web hosting comparison page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Choose an Azure compute service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/compute-decision-tree.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by ManoharLakkoju-MSFT** [comment]
@Neutrino-Sunset 
Thanks for your feedback! We will investigate and update as appropriate.
