### ISSUE TITLE
Undefined variables, failing code

### ISSUE THREAD

**Issue by mrochon** [MicrosoftDocs/architecture-center#4175]
The following PS code used in the article has undefined variables:

`# Assign subnet to variables
$appgatewaysubnetdata = $vnet.Subnets[subnet-index]
$apimsubnetdata = $vnet.Subnets[subnet-index]`

I assume values 0 and 1 should be used. However, even then following code references Ids of these two objects and these are null!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d61c0c47-bb1e-5bd4-55ed-92058c3c1e2b
* Version Independent ID: 09757b3e-205b-4263-fada-4d0224048f6f
* Content: [Protect APIs with Azure Application Gateway and Azure API Management - Azure Reference Architectures](https://learn.microsoft.com/en-us/azure/architecture/web-apps/api-management/architectures/protect-apis)
* Content Source: [docs/web-apps/api-management/architectures/protect-apis.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/web-apps/api-management/architectures/protect-apis.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @fabriciosanchez
* Microsoft Alias: **robbag**

**Comment by Naveenommi-MSFT** [comment]
@mrochon 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by Brownie9** [comment]
@Naveenommi-MSFT 
Hello, I have the same problem. This is this documentation : [https://learn.microsoft.com/en-us/azure/architecture/web-apps/api-management/architectures/protect-apis#deployment-with-powershell](url)

**Comment by Naveenommi-MSFT** [comment]
@mrochon 
Thanks for your feedback! We will investigate and update as appropriate.
