### ISSUE TITLE
Request for content expansion on Speech Services Solution Idea

### ISSUE THREAD

**Issue by ralphZ1952** [MicrosoftDocs/architecture-center#4177]
This article is a solution idea. If you'd like us to expand the content with more information, such as potential use cases, alternative services, implementation considerations, or pricing guidance, let us know by providing [GitHub feedback](https://github.com/MicrosoftDocs/architecture-center/issues/new).

Alternative services: Looking for a real-time translation of speech. Input and output being audio - conversational speech
Using microphone and speakers. as primary input output equipment. 
Pricing Guidance if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0271f0d-ca56-3d97-ab7c-0fe9d00ec87d
* Version Independent ID: 03f511ba-8989-b644-ca09-f00b7594a81f
* Content: [Speech services - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/speech-services)
* Content Source: [docs/solution-ideas/articles/speech-services.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/speech-services.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@ralphZ1952 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ralphZ1952** [comment]
https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/speech-services

**Comment by Naveenommi-MSFT** [comment]
@ralphZ1952 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thanks for your feedback.  This article no longer exists.
