### ISSUE TITLE
New Fabric Icons

### ISSUE THREAD

**Issue by David-Summers** [MicrosoftDocs/architecture-center#4178]
The new Fabric Icons are not very useable. The SVG versions do not import into Visio correctly due to some of the Alpha shading layers. The ones inside the visio stencil are not raster objects either, they are bitmap images. So we cannot reconfigure them based on usage for example and when scaled up they do not render very well. Please be consitent. Visio stencils should always be raster objects. Best to resolve the core issue for how the SVGs were made in the first place. I am guessing that when the updated stencil was created, it was too hard to fix the source SVG's so Bitmaps were used instead.

<img width="953" alt="image" src="https://github.com/MicrosoftDocs/architecture-center/assets/53208734/47cbcfa5-8597-4507-bcf2-fdd5c2bd2b43">

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by ManoharLakkoju-MSFT** [comment]
@David-Summers 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Zimmergren** [comment]
Thank you for reporting this, @David-Summers. I've looped in the team creating the icon pack to investigate. I'll come back with any updates here as I learn more.

**Comment by Zimmergren** [comment]
@David-Summers , we heard back on this. It doesn't seem like this icon comes from the Azure Architecture icons pack. Can you share where you found the icon and the name of the file?

**Comment by Zimmergren** [comment]
No reply on this. #please-close
