### ISSUE TITLE
Entra ID icon(s)

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/architecture-center#4180]
We're missing some Entra ID icons after the great rename from "Azure AD" to "Entra ID".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by Zimmergren** [comment]
Hey @o-l-a-v . When you say "_some_ Entra ID icons", do you have any details about which ones are missing so we can address this quicker and get a new release?

Meanwhile I'll ping internally to see if we have updated or new icons to add to the pack for Entra ID.

Thanks!

**Comment by o-l-a-v** [comment]
@Zimmergren 

The Entra icon to be able to replace Azure AD in architecture diagrams is the one I can think of right now.

**Comment by David-Summers** [comment]
<img width="213" alt="Untitled" src="https://github.com/MicrosoftDocs/architecture-center/assets/53208734/c6f1a5bb-ca5c-406a-9403-c2480cd2c040">

As a design idea, I created new Entra ID icons for my Periodic table refresh for B2B, B2C and DDS based on the same theme and style of the old icons. Happy to share the SVG versions for your team to use @Zimmergren

**Comment by Zimmergren** [comment]
Hey @o-l-a-v,

We recently updated the [Azure Icons](https://learn.microsoft.com/en-us/azure/architecture/icons/) download pack with the official Microsoft Entra ID icon.

#please-close
