### ISSUE TITLE
Expand on this

### ISSUE THREAD

**Issue by asir1997** [MicrosoftDocs/architecture-center#4184]
Expand on this
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe44a625-07a6-7d65-d16e-a8544c034261
* Version Independent ID: 54310bdb-1397-cd5a-688c-f8e5c042a3fb
* Content: [Custom business processes - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/custom-business-processes)
* Content Source: [docs/solution-ideas/articles/custom-business-processes.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/custom-business-processes.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @Zimmergren
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@asir1997 
Could please elaborate your query for better understanding. Thanks!!!

**Comment by Naveenommi-MSFT** [comment]
@asir1997 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
