### ISSUE TITLE
YouTube video 

### ISSUE THREAD

**Issue by habdelfattah** [MicrosoftDocs/architecture-center#4186]
[Enter feedback here]
Great document!

Just wanted to share that I've recorded a video on building this for three envs on YouTube https://youtu.be/8ZIt_DlNCoo

If you'd like you could put a reference to it in this page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Version Independent ID: 6fe11cd6-407f-3dd5-ba44-6a3a51e32943
* Content: [Automated API deployments using APIOps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops?toc=%2Fazure%2Fapi-management%2Ftoc.json&bc=%2Fazure%2Fapi-management%2Fbreadcrumb%2Ftoc.json)
* Content Source: [docs/example-scenario/devops/automated-api-deployments-apiops.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/devops/automated-api-deployments-apiops.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @rishabhsaha
* Microsoft Alias: **risaha**

**Comment by ckittel** [comment]
Thank you Hussein for creating community content!  It's great to see folks taking content like this and repackaging and retelling the story in other mediums.  We have an editorial policy that prevents us from linking to content like this, but please feel free to share in your network on LinkedIn or even on places like Microsoft Q&A if you can find a question that can benefit from your video as an answer.

Cheers

#please-close
