### ISSUE TITLE
Question for High Availability Cost Optimization

### ISSUE THREAD

**Issue by Andy989824** [MicrosoftDocs/architecture-center#4190]
Hello, can someone explain for the quoted information below? 

_Cost optimization_
_There's no additional cost for VMs deployed in AZs. There might be additional inter-AZ VM-to-VM data transfer charges_

Does this means that when deploy 1 VM in AZ 1 and another VM in AZ 2, there will be no cost inccured? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97211a88-4ce9-263f-4bd0-ae6d8b61447c
* Version Independent ID: 00570dc5-7b74-2906-1653-90d86b67c0bd
* Content: [High availability and disaster recovery for IaaS apps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/iaas-high-availability-disaster-recovery)
* Content Source: [docs/example-scenario/infrastructure/iaas-high-availability-disaster-recovery.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/iaas-high-availability-disaster-recovery.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @shcrouch
* Microsoft Alias: **shcrouch**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Andy989824 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
@Andy989824 - Great question. What this is saying, is the usage of Availability Zones doesn't have an inherit premium on them.  Meaning you don't "pay more" for the rights to land the VM you purchased into a specific availability zone.  Also zones are all priced the same, unlike regional variations where the price of a resource could be different from one region to another.

Thanks for asking!
