### ISSUE TITLE
Clarification needed for limits of logged requests and responses length for OpenAI in APIM

### ISSUE THREAD

**Issue by maciej-skorupka** [MicrosoftDocs/architecture-center#4191]
I just created API Management + OpenAI service and it seems that we can only log up to 8192 bytes of requests and responses. Can you clarify that in the docs (especially in the table with comparison between Default and This solution)? Reading this makes people think that you can log the whole message which is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59e64035-d0cb-d2cf-0848-4153b5cfe876
* Version Independent ID: 59e64035-d0cb-d2cf-0848-4153b5cfe876
* Content: [Implement logging and monitoring for Azure OpenAI large language models - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/log-monitor-azure-openai)
* Content Source: [docs/example-scenario/ai/log-monitor-azure-openai.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/ai/log-monitor-azure-openai.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jakeatmsft
* Microsoft Alias: **jacwang**

**Comment by RamanathanChinnappan-MSFT** [comment]
@maciej-skorupka
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
I've requested @jakeatmsft to assist with this issue.

**Comment by ckittel** [comment]
@RamanathanChinnappan-MSFT, @jakeatmsft created a PR to clarify this in the doc.  It MIGHT ship today yet, or might instead ship on Tuesday.  US holiday may delay the release.  If you see the PR get closed, just know that it'll then be on the next release train of the content. :)  Thanks for your feedback.

**Comment by ckittel** [comment]
Hit a bit of a bump, we just moved this file, so the PR that @jakeatmsft opened needs to be repointed to the new file.  Might not hit the Tuesday release train.
