### ISSUE TITLE
Grammar correction (Microservice architecture style in Microsoft Learn)

### ISSUE THREAD

**Issue by c0dz** [MicrosoftDocs/architecture-center#4192]
Grammar Correction:
location: Microservice architecture style -> Challenges -> Development and testing:

> Writing a small service that relies on other dependent services requires a different approach than **a** writing a traditional monolithic or layered application.

No need for "a" here: ... different approach than **_a_** writing ...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7e7bd-23f3-a39f-9015-b77f14bb43e5
* Version Independent ID: 0ac34e7e-315f-2452-bf0a-74e9b1068c38
* Content: [Microservice architecture style - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices)
* Content Source: [docs/guide/architecture-styles/microservices.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/architecture-styles/microservices.yml)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by RamanathanChinnappan-MSFT** [comment]
@c0dz
Thanks for your feedback! We will investigate and update as appropriate.
