### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tim-myth** [MicrosoftDocs/architecture-center#4196]
The link to "Boost equipment reliability with IoT-enabled predictive maintenance" is broken. https://www.microsoft.com/internet-of-things/predictive-maintenance?WT.mc_id=pdmsolution-docs-ercenk redirects to https://azure.microsoft.com/en-us/products/iot-central/.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0a5a9cc-6fad-ec82-bf32-b4ef7aa3caf8
* Version Independent ID: f0a5a9cc-6fad-ec82-bf32-b4ef7aa3caf8
* Content: [Predictive maintenance solution - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/industries/manufacturing/predictive-maintenance-solution)
* Content Source: [docs/industries/manufacturing/predictive-maintenance-solution.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/industries/manufacturing/predictive-maintenance-solution.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @Ercenk
* Microsoft Alias: **ercenk**

**Comment by SaibabaBalapur-MSFT** [comment]
@tim-myth 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by asergaz** [comment]
@ercenk can you please take a look? Thanks,

**Comment by skabou** [comment]
This issue appears to have been resolved.  If you are still experiencing an issue, please re-open with additional information.
