### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tim-myth** [MicrosoftDocs/architecture-center#4197]
The link https://github.com/Azure/Industrial-IoT/blob/master/docs/architecture.md goes to a 404 page on Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34a1f576-5102-4751-776d-54d6fbc4516b
* Version Independent ID: 5f469a50-7a3c-4ab5-acda-0e803392b859
* Content: [Predictive maintenance for industrial IoT - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/iot-predictive-maintenance)
* Content Source: [docs/solution-ideas/articles/iot-predictive-maintenance.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/iot-predictive-maintenance.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@tim-myth 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by asergaz** [comment]
@tim-myth thanks for catching this one. I have fixed it and it will soon be live. 

Here's the correct link: https://github.com/Azure/Industrial-IoT/blob/2.8.2/docs/architecture.md
