### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by venkat1122** [MicrosoftDocs/architecture-center#4202]
There is a spelling mistake in this page. It is mentioned as Platform at a service instead of Platform as a service (Paas)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e352b811-8cf9-ea60-8552-9ca46d93821c
* Version Independent ID: e352b811-8cf9-ea60-8552-9ca46d93821c
* Content: [Architectural approaches for networking in multitenant solutions - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/approaches/networking)
* Content Source: [docs/guide/multitenant/approaches/networking.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/approaches/networking.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @johndowns
* Microsoft Alias: **jodowns**

**Comment by navba-MSFT** [comment]
@venkat1122 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@venkat1122 The above PR has been filed and it is currently under review.
