### ISSUE TITLE
Fabric and OneLake

### ISSUE THREAD

**Issue by SMHolck** [MicrosoftDocs/architecture-center#4206]
With the release of Fabric and OneLake, should this diagram be updated to reflect even newer options?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7254782d-e773-b542-73e8-f568d3bbee39
* Version Independent ID: 40d81223-f8ea-2eec-616e-5f6ee28c8206
* Content: [Modern analytics architecture with Azure Databricks - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture)
* Content Source: [docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@SMHolck 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177450 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
