### ISSUE TITLE
Can we extend this architecture for D365 Performance Scripts written for CRM

### ISSUE THREAD

**Issue by sugnick004** [MicrosoftDocs/architecture-center#4207]
Can we extend the architecture for D365 Performance Scripts written for CRM?

https://learn.microsoft.com/en-us/azure/architecture/example-scenario/banking/jmeter-load-testing-pipeline-implementation-reference

I have a question on the Jmeter-docker-build to azure container registry do we need to include the jmx file or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea464ce1-0548-e4d4-2160-a3829c959b93
* Version Independent ID: 9128607b-d441-cf29-b68b-55936d549690
* Content: [JMeter implementation for a load testing pipeline - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/banking/jmeter-load-testing-pipeline-implementation-reference)
* Content Source: [docs/example-scenario/banking/jmeter-load-testing-pipeline-implementation-reference.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/banking/jmeter-load-testing-pipeline-implementation-reference.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@sugnick004 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  The article for which your suggestion was for has been removed.
