### ISSUE TITLE
Contradictory and misleading architecture recommendation

### ISSUE THREAD

**Issue by troyha** [MicrosoftDocs/architecture-center#4208]
The following paragraph seems contradictory and misleading, unless I am misunderstanding something:

When you create a logic app to consume Service Bus messages, we recommend using the proxied push model with Event Grid integration. It's often more cost efficient, because the logic app doesn't need to poll Service Bus. For more information, see [Azure Service Bus to Event Grid integration overview](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-to-event-grid-integration-concept). Currently, Service Bus [Premium tier](https://azure.microsoft.com/pricing/details/service-bus/) is required for Event Grid notifications.

1. It's often more cost efficient, because the logic app doesn't need to poll Service Bus.
2. Currently, Service Bus [Premium tier](https://azure.microsoft.com/pricing/details/service-bus/) is required for Event Grid notifications.

You have to use premium to integrate with Event Grid, however Service Bus Premium does not charge for operations or connections, just a flat fee per hour. Therefore using Premium it doesn't matter if you poll so there is no need to integrate with Event Grid. T

The only advantage of reducing polling is on Basic or Standard to reduce the operations/connections, however Event Grid is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58f4706b-af61-c661-279d-05e9e9abb79a
* Version Independent ID: d5a4b726-4c50-0851-edc5-04b60ee5ce89
* Content: [Enterprise integration with message broker and events - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/integration/queues-events#service-bus)
* Content Source: [docs/example-scenario/integration/queues-events.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/integration/queues-events.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @MattFarm
* Microsoft Alias: **mattfarm**

**Comment by Naveenommi-MSFT** [comment]
@troyha 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-albemi** [comment]
I have no input into this. ecfan might be able to help.

**Comment by ecfan** [comment]
I've asked the product team to help clarify.

**Comment by wsilveiranz** [comment]
@troyha  the cost improvement in this case comes from Logic Apps, not from Service Bus. Each polling action in Logic Apps Consumption is an action that is charged. For customers that want close to real time processing of messages, those logic apps are running on 30 second interval, to keep the long polling alive. Moving to an event grid proxy model means that the logic apps will only be triggered when new messages arrive on the Service Bus. Let me know if that helps answering the question.

**Comment by ecfan** [comment]
#assign @wsilveiranz

**Comment by ecfan** [comment]
#assign:wsilveiranz

**Comment by josevarela** [comment]
@troyha You make a valid point about Service Bus Premium having flat fee charge model, but as @wsilveiranz already clarifies, the comment is missing the point of the paragraph being about savings in Logic Apps. The savings are achieved by changing the Logic App trigger to a push model.

Closing the issue at this point. Please, let us know if you'd like to reopen it.

#please-close
