### ISSUE TITLE
Include scenario with DC/DNS server in Azure only leveraging private resolver for private endpoints

### ISSUE THREAD

**Issue by mahia127** [MicrosoftDocs/architecture-center#4211]
Include scenario with DC/DNS server in Azure only leveraging private resolver for private endpoints

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Version Independent ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Content: [Azure DNS Private Resolver - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/azure-dns-private-resolver)
* Content Source: [docs/example-scenario/networking/azure-dns-private-resolver.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/networking/azure-dns-private-resolver.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @moorthyannadurai
* Microsoft Alias: **moannadu**

**Comment by Naveenommi-MSFT** [comment]
@mahia127 
Thank you for bringing this to our attention.
I've delegated this to content author @moorthyannadurai, who will review it and offer their insightful opinions.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177444 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
