### ISSUE TITLE
Contradictory application design principles recommandations

### ISSUE THREAD

**Issue by opportus** [MicrosoftDocs/architecture-center#4221]
> [**Design for operations**](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/design-for-operations). Design your application so that the operations team has the tools they need.

contradicts

> [Build for the needs of business](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/build-for-business). **Every design decision must be justified by a business requirement**.

The first design recommandation is OK. The second design recommandation needs much more nuances and corrections...

As architects should know, we don't design **only for business** but for stakeholders of an entire value stream among which operations stakeholders (IT).

Can we reasonably expect to get operational quality attributes such as maintainability or scalability from business requirements (yet potentially yielding to an expensive microservices architecture)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb507d50-57ff-115b-f19f-8e7e8e255763
* Version Independent ID: 8b46d95d-e49b-342c-dd2e-df49f39b175f
* Content: [Design principles for Azure applications - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/)
* Content Source: [docs/guide/design-principles/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/design-principles/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@opportus 
Thank you for bringing this to our attention.
I've delegated this to content author @martinekuan, who will review it and offer their insightful opinions.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177442 to track and investigate this issue.
