### ISSUE TITLE
Azure Media Services retiring

### ISSUE THREAD

**Issue by joshmouch** [MicrosoftDocs/architecture-center#4223]
According to [this page](https://learn.microsoft.com/en-us/azure/media-services/latest/encode-concept), Azure Media Services will be retiring in less than a year.  Will this solution be updated to use a different service?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd6efdd9-5b74-3186-a8f9-ac482f1215f2
* Version Independent ID: e262bd4f-11f1-ab1c-ffb1-61361287464c
* Content: [Video-on-demand digital media - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/digital-media-video)
* Content Source: [docs/solution-ideas/articles/digital-media-video.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/digital-media-video.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **johndeu, inhenkel**

**Comment by AjayBathini-MSFT** [comment]
@joshmouch 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by akucer** [comment]
Unfortunately, no. Customers need to move to partner or other service by June 30, 2024. https://aka.ms/ams-retirement has list of partners that we have worked with on solutions for customers to migrate to. For workflows just needing on-demand streaming capabilities Media Services assets can be converted to CMAF format using the open-source [Azure Media Services Migration Tool](https://github.com/Azure/azure-media-migration).

**Comment by skabou** [comment]
#please-close
