### ISSUE TITLE
Clarification on APIM network configuration

### ISSUE THREAD

**Issue by neilpeterson** [MicrosoftDocs/architecture-center#4224]
The diagram shows APIM inside a VNET. In this case is APIM configured inside the VNET (internal)? 

If I understand [this doc](https://learn.microsoft.com/en-us/azure/frontdoor/private-link#limitations) correctly, there is a current limitation that would prevent AFD > APIM over private link. If that is the case, how can we route traffic from AFD > APIM while APIM is internal to the VNET?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34ed51e6-265e-aae0-f552-0900a345b3be
* Version Independent ID: 34ed51e6-265e-aae0-f552-0900a345b3be
* Content: [Scalable cloud applications and SRE - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/scalable-apps-performance-modeling-site-reliability)
* Content Source: [docs/example-scenario/apps/scalable-apps-performance-modeling-site-reliability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/apps/scalable-apps-performance-modeling-site-reliability.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **subhajch**

**Comment by AjayBathini-MSFT** [comment]
@neilpeterson 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by neilpeterson** [comment]
I think the answer to my architectural question is that at this time, for this config to work, APIM must be in the 'external' networking mode, and available on the internet. Access can be limited using both an NSG rule + header matching (on front door id).

Hopefully, at some point, we will be able to keep APIM in internal mode and utilize a private link.

Closing issue, but perhaps some clarification in the doc that the APIM must be in external mode would be helpful?
