### ISSUE TITLE
Clarification on the physical separation of Availability Zones

### ISSUE THREAD

**Issue by akki-s** [MicrosoftDocs/architecture-center#4226]
> However, using a different AZ doesn't guarantee that the datacenters in each AZ will be located physically far apart.

The above text in the [Disaster Recovery section](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/iaas-high-availability-disaster-recovery#disaster-recovery), is confusing and contradicts with what an Availability Zone would normally mean i.e. physically separate datacenters.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97211a88-4ce9-263f-4bd0-ae6d8b61447c
* Version Independent ID: 00570dc5-7b74-2906-1653-90d86b67c0bd
* Content: [High availability and disaster recovery for IaaS apps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/iaas-high-availability-disaster-recovery)
* Content Source: [docs/example-scenario/infrastructure/iaas-high-availability-disaster-recovery.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/iaas-high-availability-disaster-recovery.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @shcrouch
* Microsoft Alias: **shcrouch**

**Comment by AjayBathini-MSFT** [comment]
@akki-s 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/architecture-center-pr/pull/11904

**Comment by stephen-sumner** [comment]
@akki-s - Thanks for your feedback. We've updated the section to improve clarity. You should see the updated guidance shortly. Thank you!

**Comment by stephen-sumner** [comment]
#please-close
