### ISSUE TITLE
Data is cached in Azure from the on-premises NFS server. NOt mentioned 

### ISSUE THREAD

**Issue by balagcpcloud** [MicrosoftDocs/architecture-center#4229]
6.Data is cached in Azure from the on-premises NFS server. is not motioned in the diagram

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9db8f590-d98b-ecec-9fce-ff4f8b1ce292
* Version Independent ID: 913a4485-3c82-6bc4-b9ad-f2d3c0940afc
* Content: [Run CFD simulations - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/hpc-cfd)
* Content Source: [docs/example-scenario/infrastructure/hpc-cfd.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/hpc-cfd.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @mikewarr
* Microsoft Alias: **mike.warrington**

**Comment by AjayBathini-MSFT** [comment]
@balagcpcloud 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
#please-close
