### ISSUE TITLE
Service Request Automation for Microsoft Modern Workspace

### ISSUE THREAD

**Issue by neerajks77** [MicrosoftDocs/architecture-center#4231]
### What is Service Request Automation and Why is it Needed

Organizations of all sizes have been struggling with their Cloud Operations request management for years. The frequently raised similar kind of service requests contributes to higher service costs and unhappy customer. To pursue the digital aspirations of the enterprise, automation solutions hold the key. Fully automated platforms can be leveraged for end-to-end automation of service requests, thereby, reducing a lot of manual effort, which in-turn reduces the operational expenses of the organization.

Service request automation is, therefore, increasingly essential in today's fast-paced, digital-centric world. Automating service requests can help organizations streamline operations, improve response times, and optimize resource allocation. Let us break down the importance of service request automation as below:

- **Boosting Productivity:** Instead of manually sifting through requests one by one, automation tools can manage and sort multiple requests at once, allowing staff to attend to more critical tasks.

- **Cost Efficiency:** Think of automation as a one-time investment that pays off in the long run. With fewer manual processes, you'll often spend less on labor over time.

- **Handling Growth:** As a business expands, the number of service requests can surge. Automation ensures you're prepared to manage this growth without constantly hiring more staff or expanding teams.

- **Always-On Service:** While humans need breaks, an automated system doesn't. This means service requests can be acknowledged or even resolved anytime—day or night.

- **Consistent Quality:** Automation follows specific rules and guidelines. This means every service request is tackled the same way, ensuring that all users get a consistent experience.

- **Immediate Responses:** Instead of waiting for a human to acknowledge a service request, automated systems can provide instant confirmations, letting users know their request is being processed.

- **Better Use of Human Talent:** By removing routine tasks from their plates, staff can focus on complex problems or tasks that require a personal touch.

- **Valuable Insights:** With automation, you can easily collect data about the service requests you receive. This data can offer insights into user needs, peak times for requests, and areas that might need improvement.

- **Speedy Solutions:** For standard issues, automation can provide quick fixes, meaning users don't have to wait long for solutions.

- **Reliability:** Humans can occasionally overlook details or make mistakes, especially when overloaded. Automated systems, being rule-driven, reduce these oversights.

- **Transparent Tracking:** Many automated systems log their activities. This not only offers insights into system performance but can also be crucial for keeping records for regulatory or quality purposes.

In essence, service request automation is like having a reliable assistant that handles routine chores swiftly and accurately, allowing the rest of the team to focus on more significant challenges and ensuring users get timely and consistent responses.

### Reference architecture

Below is the reference architecture for the same.

![HighLevelArchitecture](https://github.com/MicrosoftDocs/architecture-center/assets/38447673/5e65a14c-74b3-49a2-9f96-8bf03b595352)
![workflow](https://github.com/MicrosoftDocs/architecture-center/assets/38447673/595f4e23-eb1d-46e7-8e00-376cc65f321f)

Below is the process flow for the solution.
![ProcessFlow](https://github.com/MicrosoftDocs/architecture-center/assets/38447673/87b648fc-7fce-45fc-b525-f380e1d5635b)

### Pre-requisites and Steps required for Automation Framework Setup

To setup the automation framework, following are the pre-requisites and steps required to set up the service request automation process flow.

**1. Application Registration**
- [ ] OAuth Provider - With details from Azure App Registration. Provide Client ID and Secret for authorization using Azure AD. Also provide the authorization as well as the token endpoints. This is used for triggering PowerShell Runbooks
- [ ] OAuth API Script – This script is required to configure the OAuth Provider and is specifically
used to make a connection to Azure.
[OAuth API Script.txt](https://github.com/MicrosoftDocs/architecture-center/files/12708896/OAuth.API.Script.txt)

**2. Catalog Details**
This will be needed only when the catalogs are not defined within the ServiceNow. In case the catalog items already exists, this step can be skipped.
- [ ] Catalogs - High level request catalogs for requests and incidents. Catalogs represent area.
- [ ] Category - Catalogs are created under Catalogs.
- [ ] Catalog Items - Items are created under Category. They are the actual forms using which the requests are raised
- [ ] Variables - They are part of Catalog Items and act as form fields

**3. Workflows**
Workflows are the business processes that are attached to the Requests, RITMs, SCTasks etc. for the business process flow. If the workflows are not defined, new workflow needs to be created for each service request, or existing workflow needs to be modified in case there is an existing workflow in place for end-to-end automations.

**4. Users**
Create User with Web Service Access Only and as Internal Integration User type only. This user will be required to access ServiceNow for request updates after the processing is done from Azure Automation

**5. Outbound Rest Message**
- Endpoint -
https://management.azure.com/subscriptions/${​​​sub_id}​​​​​​​​​​/resourceGroups/${​​​​​​​​​​rg_name}​​​​​​​​​​/providers/Microsoft.Automation/automationAccounts/${​​​​​​​​​​automationAcct_name}​​​​​​​​​​/jobs/${​​​​​​​​​​job_id}​​​​​​​​​​?api-version=2019-06-01
- Http Method – Put method. Will be used to trigger the PowerShell Runbook
- Authentication - OAuth 2.0
- OAuth Profile - Select the OAuth Provider Profile created earlier

6. Scripted Rest API
After the process has been completed on the Azure Automation side, it sends back the updates to SNOW via the REST method. This REST URI is for the Scripted Rest API to perform updates to the requested item the corresponding and task.

### Azure Configuration

**1. Azure Active Directory App Registration for SNOW**
Register app in Azure AD for SNOW request authorization. This is needed for communication between ServiceNow and Azure Automation

2. Azure Active Directory App Registration for Exchange Online
Register an application in Azure AD for Exchange Online. Provide this app ‘Exchange.ManageAs’ permissions within the API permissions.
![image](https://github.com/MicrosoftDocs/architecture-center/assets/38447673/08de4442-b59c-48f5-8fd6-0f4c69fc555c)

Also, under Roles and Administrator, give this application “Exchange Administrator” role.

Under certificates and secrets, upload the .cer certificate

**3. Create an Azure Automation Account**
Create an Azure Automation Account for the Service Request Automation

**- PowerShell Runbook**
PowerShell Runbooks will be used for service request processing and post processing, it will send the updates back to

**- Create shared resources**
Create variables, and under certificates, upload the .pfx certificate created earlier as a part of the self-signed certificate. In production environment, however, we will need a valid certificate from the certificate authority.
![image](https://github.com/MicrosoftDocs/architecture-center/assets/38447673/eae6955d-50bb-4865-9795-256a9a04b275)
![image](https://github.com/MicrosoftDocs/architecture-center/assets/38447673/96fef5d9-c89d-4a73-a0e8-a2f53c8c6949)

**4. Create Azure Key Vault**
Create an Azure Key Vault and add the following secrets. Azure key vault is used to secure the credentials and other secrets and enables secure access. The key vaults can be used in cases where the scripts are run on Azure within the runbooks. In case of hybrid, we can use the encrypted feature of the runbook shared variables.
![image](https://github.com/MicrosoftDocs/architecture-center/assets/38447673/42e4cc12-e794-4045-92a0-c69603ada0fb)
This is optional and the values within the Key Vault can be created as encrypted variables within
Shared Resources under Variables.

**Comment by RamanathanChinnappan-MSFT** [comment]
@neerajks77 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@neerajks77
We are going to close this thread . if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by neerajks77** [comment]
Hi Ramanathan,

Good Morning!

I am really not sure as to the outcome of this submission. I got the
reference link to this page after I reported that I wanted to submit an
architecture in the Microsoft Architecture Center, but the page and the
links were not working. After I received the link, I created this
documentation as well as uploaded all the artefacts for review and
approval.

Having said that, please let me know if the submission has been approved or
needs further clarifications. Please let me know if you have any questions
or need further information.

Regards,
Neeraj
