### ISSUE TITLE
End to End architecture design - LLM Based Recommendation Engine

### ISSUE THREAD

**Issue by BalaramUOA** [MicrosoftDocs/architecture-center#4233]
Hi Team, 
I have been working on Recommendation system and have developed some solution using LLM embeddings. 
I would like to contribute a End-to-end recommendation engine based on all Azure Component, LLM and Vector DB. 
I would like to contribute end to end architecture. 

Previous work in architecture: 
I have recently published LLM based Search Engine Architecture. 
https://medium.com/@balarampanda.ai/build-your-own-e-commerce-search-engine-with-azure-ai-94faa29cf6b7

Please let me know if you need more information from my end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e211beeb-11d0-8bde-03d0-e67ef56dbd39
* Version Independent ID: e211beeb-11d0-8bde-03d0-e67ef56dbd39
* Content: [Contribute to Patterns and Practices content - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/architecture-center/aac-contribute)
* Content Source: [Contribute/content/architecture-center/aac-contribute.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/architecture-center/aac-contribute.md)
* Product: **non-product-specific**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by SaibabaBalapur-MSFT** [comment]
@BalaramUOA 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by BalaramUOA** [comment]
Hi @SaibabaBalapur-MSFT, Thanks for your response. Sorry I missed the context. could you please specify what documents and steps you are referring to ?

**Comment by SaibabaBalapur-MSFT** [comment]
@BalaramUOA 
It would be great if you could add the documentation link, which your following?

**Comment by BalaramUOA** [comment]
I don’t have any specific documentation link which I can specifically refere. This is a general architecture designed from my experience and learning from Google, Azure and AWS architecture focum and contents. Are you looking for any references for this ?  FYI: The proposed architecture for LLM base Rco will be somewhat like this: https://medium.com/@balarampanda.ai/generative-ai-based-recommendation-engine-on-azure-cloud-54f742d58e22

**Comment by SaibabaBalapur-MSFT** [comment]
@BalaramUOA 
Please Note, GitHub forum is dedicated for Microsoft documentation related issues. So kindly share Microsoft document link which you are following for these steps.

**Comment by BalaramUOA** [comment]
@SaibabaBalapur-MSFT 
I would like to propose new content and I route to this page based on Microsoft Document Link : https://learn.microsoft.com/en-us/contribute/content/architecture-center/aac-contribute

**Comment by SaibabaBalapur-MSFT** [comment]
@martinekuan 
Please review it.

**Comment by BalaramUOA** [comment]
@martinekuan @SaibabaBalapur-MSFT any update please ?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177431 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
