### ISSUE TITLE
A duplicate item in the component list

### ISSUE THREAD

**Issue by adammazouz** [MicrosoftDocs/architecture-center#4235]
A duplicate item in the component list: 

Azure ExpressRoute: extends your on-premises networks to Microsoft cloud services, including Azure and Office 365, over a private connection facilitated by a connectivity provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69687474-c1aa-d3ce-62b8-2361e303cd77
* Version Independent ID: 69687474-c1aa-d3ce-62b8-2361e303cd77
* Content: [Migrate IBM i series to Azure with Skytap - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/mainframe/migrate-ibm-i-series-to-azure-with-skytap)
* Content Source: [docs/example-scenario/mainframe/migrate-ibm-i-series-to-azure-with-skytap.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/mainframe/migrate-ibm-i-series-to-azure-with-skytap.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **Ricardo.Galvan**

**Comment by AjayBathini-MSFT** [comment]
@adammazouz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MayankBargali-MSFT** [comment]
@adammazouz Thanks for reporting this item! I have updated the doc and it will be published soon. We appreciate the feedback!
