### ISSUE TITLE
No content related to project planning in page

### ISSUE THREAD

**Issue by timo-schuerg** [MicrosoftDocs/architecture-center#4236]
The page consists of

- a summary, which is almost the same as the https://learn.microsoft.com/en-us/azure/architecture/data-science-process/lifecycle on the life cycle of a data science project
- a contributor section
- suggestions for further reading.

In summary, there is zero content related to the heading of the page, namely project planning.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab9d2cf-5ff8-59c9-34fd-014f0dfcef6a
* Version Independent ID: 3ad7b162-7fa2-ef08-8c1d-5343b1bebf4e
* Content: [Team Data Science Process project planning - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-science-process/team-data-science-process-project-templates)
* Content Source: [docs/data-science-process/team-data-science-process-project-templates.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-science-process/team-data-science-process-project-templates.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by AjayBathini-MSFT** [comment]
@timo-schuerg 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by marktab** [comment]
@timo-schuerg  I will be reviewing in the coming week:  I'll add (or add back) any missing content

**Comment by marktab** [comment]
@timo-schuerg At one point in the past, previous owners had made primitive Excel and Microsoft Project templates for this page -- they have been removed some time ago, and there is no plan to produce similar directions.

Please see https://learn.microsoft.com/en-us/azure/architecture/data-science-process/agile-development for ideas.

Both Excel and Microsoft Project have documentation on how to use those technologies.

This page has been entered for deletion.

**Comment by marktab** [comment]
@AjayBathini-MSFT  feel free to close this request
