### ISSUE TITLE
How to obtain permission to reuse Microsoft Arc reference architecture diagrams in a report?

### ISSUE THREAD

**Issue by cjliu20152** [MicrosoftDocs/architecture-center#4237]
Hello,

Could the Microsoft Arc authority provide instructions on 
"How to obtain permission to reuse Microsoft Arc reference architecture diagrams in a report?"

Thanks.

Dr. CJ Liu
cjliu@mitre.org

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 479a91c4-715f-4742-b143-79675e201dfb
* Version Independent ID: 0749863b-9afc-28f5-4df4-181fde552d94
* Content: [Manage and deploy Kubernetes in Azure Arc - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/hybrid/arc-hybrid-kubernetes)
* Content Source: [docs/hybrid/arc-hybrid-kubernetes.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/hybrid/arc-hybrid-kubernetes.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @pdebruin
* Microsoft Alias: **pidebrui**

**Comment by RamanathanChinnappan-MSFT** [comment]
@cjliu20152 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by pdebruin** [comment]
@RobBagby maybe?

**Comment by cjliu20152** [comment]
We'd like to use the three Azure Arc reference architecture diagrams with little adaption in a report with Microsoft permission. Could you provide instructions on whether or not this can be authorized? And then how, if yes is the answer. We don't have much time left to wait. Thanks.

**Comment by cjliu20152** [comment]
> We'd like to use the three Azure Arc reference architecture diagrams with little adaption in a report with Microsoft permission. Could you provide instructions on whether or not this can be authorized? And then how, if yes is the answer. We don't have much time left to wait. Thanks.

@RobBagby and @pdebruin 
Hello,
Still hoping you guys could assist on this request.
We are still working on the report to finalize it.
Thanks.
V/R
Dr. CJ Liu

**Comment by ckittel** [comment]
@cjliu20152, the file is governed under this LICENSE: https://github.com/MicrosoftDocs/architecture-center/blob/main/LICENSE

I am not a lawyer, so I do not know how to interpret this license, but being a Creative Commons, Attribution 4.0 International license, I assume you follow the guidelines at: https://creativecommons.org/licenses/by/4.0/
