### ISSUE TITLE
AKS Baseline Architecture suggest adding NSG to azure firewall subnet

### ISSUE THREAD

**Issue by abengtss-max** [MicrosoftDocs/architecture-center#4240]
[Enter feedback here]
It is not possible to add an NSG to a AzureFirewallSubnet, recommendation is to highlight this in the documentation and visually illustrate it in the solution diagram where AzureFirewall does not have an NSG associated to its subnet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an AKS cluster - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/baseline-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks/baseline-aks.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by RamanathanChinnappan-MSFT** [comment]
@abengtss-max 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
That is a really good catch.  I don't know how that got onto the diagram.

@CAC1127 can you queue up an editor task to remove the NSG logo from the image here on the Azure Firewall subnet.

<img width="112" alt="image" src="https://github.com/MicrosoftDocs/architecture-center/assets/671075/fc66e53e-4430-4cec-b1d4-2731ec6796e3">

**Comment by mSarts** [comment]
@ckittel @CAC1127 brought this to my attention. I've opened up a work item with Beyondsoft for them to edit the diagram.

**Comment by mSarts** [comment]
Addressed in the following PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/11183.
