### ISSUE TITLE
HDInsight on AKS icons to be added in the inventory list

### ISSUE THREAD

**Issue by snehalsonwane** [MicrosoftDocs/architecture-center#4241]
Hi,

How to add the icons to new services in the list. Can you please help me with this?
You can contact me and I will share it with you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by RamanathanChinnappan-MSFT** [comment]
@snehalsonwane 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by snehalsonwane** [comment]
On this link https://learn.microsoft.com/en-us/azure/architecture/icons/ , there is a downloadable file for azure services icons and my question is how to add the icons for new services which are not in the list.

<img width="929" alt="image" src="https://github.com/MicrosoftDocs/architecture-center/assets/99327040/9d9d5444-2479-4f1f-a05f-797fe513b5cb">

**Comment by RamanathanChinnappan-MSFT** [comment]
@snehalsonwane 
I've delegated this to @Zimmergren, a content author, to review and share their valuable insights.

**Comment by Zimmergren** [comment]
Thank you for submitting this request - we're discussing offline now. #please-close
