### ISSUE TITLE
WebSocket Shpport

### ISSUE THREAD

**Issue by coreydeli** [MicrosoftDocs/architecture-center#4246]
As per #1891 and #4011 there hasnt been an update. The last communication said March 2023 and we are well past this. When is this going live and can we get some ongoing updates on such a crucial web feature?
---
Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 936c85d9-c953-2def-c399-77cbda32b24d
Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
Content: [Overview of Azure load-balancing options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#feedback)
Content Source: [docs/guide/technology-choices/load-balancing-overview.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/guide/technology-choices/load-balancing-overview.md)
Service: architecture-center
Sub-service: reference-architecture
GitHub Login: @sharad4u Sharad Agrawal (ENERGY) FTE
Microsoft Alias: pnp

**Comment by SaibabaBalapur-MSFT** [comment]
@coreydeli 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
I'm sorry, but the Azure Architecture Center content team does not ship features in Azure Front Door, nor does this GitHub issues list route to the team that does.  I'm sorry you don't yet have an answer to this (I'm curious myself!), but we only use this to track content updates, not product updates unfortunately.

If there are upcoming previews of this feature, I'm also not in a position personally to share that information.  I'd watch the Ignite announcements and follow any of the Azure networking team announcements for the rest of the year though.

**Comment by coreydeli** [comment]
> I'm sorry, but the Azure Architecture Center content team does not ship features in Azure Front Door, nor does this GitHub issues list route to the team that does. I'm sorry you don't yet have an answer to this (I'm curious myself!), but we only use this to track content updates, not product updates unfortunately.
> 
> If there are upcoming previews of this feature, I'm also not in a position personally to share that information. I'd watch the Ignite announcements and follow any of the Azure networking team announcements for the rest of the year though.

Then where in earth should we ask?? Everyone asks here because the uservoice site hasn't been updated in 2 years with information after being told it was to be released by now.

We need answers and we have no way to get them as no one responds with any reasonable information on any public forum.

**Comment by ckittel** [comment]
I honestly wish I knew; I feel your frustration.  I know our team cannot help directly and this GitHub issue list isn't on the radar of anyone who can, nor should it be -- since this is for content bugs for the architecture center content team.  Sorry, I hope you understand.
