### ISSUE TITLE
Add Apache Flink

### ISSUE THREAD

**Issue by yeturis** [MicrosoftDocs/architecture-center#4247]
The same idea can be exteneded to have Apache Flink with Kafka, Please reach out for further details

**Comment by SaibabaBalapur-MSFT** [comment]
@yeturis 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by SaibabaBalapur-MSFT** [comment]
@yeturis 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
