### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by jeffmurr** [MicrosoftDocs/architecture-center#4250]
It may be helpful to understand the RBAC assignment requirements and tenancy assumptions involved in these writeups. It would appear this is for a 1:1 API-M to solution architecture (AKS, Cosmos DB, SQL, Key Vault, ACR). Missing are those assumptions spelled out, resource groups involved/network and permissions access boundaries, roles assignments, assignment locations, deployment architecture, and day-2 tasks. Those are some common items left up to the reader it may make sense to include in the writeup. Would it make sense to add these?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Version Independent ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Content: [Deploy AKS and API Management with mTLS - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/mutual-tls-deploy-aks-api-management)
* Content Source: [docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @saswatmohanty01
* Microsoft Alias: **samohant, rapencha, arazeem**

**Comment by AjayBathini-MSFT** [comment]
@jeffmurr 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177427 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
