### ISSUE TITLE
Please check this sentence: "Register a service principal for the UI and API using Microsoft Entra Directory in the Azure portal."

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/architecture-center#4251]
Hello,

please check if 'Directory' is correct wording in this sentence: "Register a service principal for the UI and API using Microsoft Entra **Directory** in the Azure portal." under "Register your application in Azure" chapter.

Should it be "Microsoft Entra **ID**" instead? Could it be an search-and-replace issue caused by 'Azure Active Directory"?

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 663d2b7f-9fff-5b20-5952-651f88a61608
* Version Independent ID: 39d4e455-b817-a338-f459-8b35d2cb458c
* Content: [Secure development with single-page apps - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/resilience/azure-ad-secure-single-page-application)
* Content Source: [docs/guide/resilience/azure-ad-secure-single-page-application.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/resilience/azure-ad-secure-single-page-application.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @lanallai
* Microsoft Alias: **lanallai**

**Comment by lanallai** [comment]
Hi Anne,

Yes, it should.

Can I run a PR and amend to Microsoft Entra ID and submit?

Thanks,
________________________________
From: QueryCoordinator ***@***.***>
Sent: 17 October 2023 11:08
To: MicrosoftDocs/architecture-center ***@***.***>
Cc: Lavan Nallainathan ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/architecture-center] Please check this sentence: "Register a service principal for the UI and API using Microsoft Entra Directory in the Azure portal." (Issue #4251)


Hello,

please check if 'Directory' is correct wording in this sentence: "Register a service principal for the UI and API using Microsoft Entra Directory in the Azure portal." under "Register your application in Azure" chapter.

Should it be "Microsoft Entra ID" instead?

Kind regards,
Anne H., QC

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 663d2b7f-9fff-5b20-5952-651f88a61608
  *   Version Independent ID: 39d4e455-b817-a338-f459-8b35d2cb458c
  *   Content: Secure development with single-page apps - Azure Architecture Center<https://learn.microsoft.com/en-us/azure/architecture/guide/resilience/azure-ad-secure-single-page-application>
  *   Content Source: docs/guide/resilience/azure-ad-secure-single-page-application.yml<https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/resilience/azure-ad-secure-single-page-application.yml>
  *   Service: architecture-center
  *   Sub-service: azure-guide
  *   GitHub Login: @lanallai<https://github.com/lanallai>
  *   Microsoft Alias: lanallai

**Comment by QueryCoordinator** [comment]
Hi @lanallai,

yes please. I'm just reporting issues I see the content :)

Kind regards,
Anne

**Comment by lanallai** [comment]
[like]  Lavan Nallainathan reacted to your message:
________________________________

**Comment by Naveenommi-MSFT** [comment]
@QueryCoordinator 
Thank you for bringing this to our attention.
I've delegated this to content author @lanallai, who will review it and offer their insightful opinions.

**Comment by stephen-sumner** [comment]
This page appears to have been moved and updated. Closing.

**Comment by stephen-sumner** [comment]
#please-close
