### ISSUE TITLE
Outdated StorSimple reference

### ISSUE THREAD

**Issue by nedlowe** [MicrosoftDocs/architecture-center#4252]
This page still refers to StorSimple, which is out of service. Should this be replaced with Azure File Sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5500b1c4-f652-9424-ef6c-90bc5db04a90
* Version Independent ID: 83ed8709-d912-ede8-d115-82a49a274ac1
* Content: [Compare AWS and Azure storage services - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/aws-professional/storage)
* Content Source: [docs/aws-professional/storage.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/storage.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@nedlowe 
Thank you for bringing this to our attention.
I've delegated this to content author @martinekuan, who will review it and offer their insightful opinions.

**Comment by ckittel** [comment]
Thanks for pointing this out.  An update will be live in one or two business days for this.
