### ISSUE TITLE
All of the architectural diagram downloads link to the same diagram. Each diagram should be downloadable.

### ISSUE THREAD

**Issue by eggShells** [MicrosoftDocs/architecture-center#4268]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d03feee-694b-5ffc-d930-1067afdb85dd
* Version Independent ID: 0d03feee-694b-5ffc-d930-1067afdb85dd
* Content: [Azure Communication Services architecture design - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/mobile/azure-communication-services-architecture)
* Content Source: [docs/guide/mobile/azure-communication-services-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/mobile/azure-communication-services-architecture.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @tophpalmer
* Microsoft Alias: **chpalm**

**Comment by Naveenommi-MSFT** [comment]
@eggShells 
It looks like your issue is resolved since you closed this thread.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
