### ISSUE TITLE
Quorum Blockchain Service is now deprecated 

### ISSUE THREAD

**Issue by kevinthill** [MicrosoftDocs/architecture-center#4270]
Hello, Consensys deprecated Quorum Blockchain Service in February 2023 and partnered with Kaleido to support all their QBS customers moving forward. More info here: https://consensys.io/blog/consensys-partners-with-kaleido-to-support-qbs-customers

With that, Kaleido is now a [Microsoft partner](https://azure.microsoft.com/en-us/solutions/web3/#partners) for Web3, and supports all the functionality of the old QBS service, so I'd suggest updating this article to reflect that. Microsoft customers are able to create a free Kaleido trial to deploy Quorum networks at https://www.kaleido.io/blockchain-platform/quorum

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db15a586-a04b-e78e-276a-949d7a858958
* Version Independent ID: db15a586-a04b-e78e-276a-949d7a858958
* Content: [Supply chain management - Track and trace with Quorum Blockchain Service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/blockchain/quorum-blockchain-service)
* Content Source: [docs/guide/blockchain/quorum-blockchain-service.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/blockchain/quorum-blockchain-service.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @AdhikariSamrat
* Microsoft Alias: **sadhikari**

**Comment by ManoharLakkoju-MSFT** [comment]
@kevinthill 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by kevinthill** [comment]
Sounds good, let us know if you need any support from our end. I'd be happy to connect you with one of our technical resources

**Comment by ckittel** [comment]
Just for visibility, @AdhikariSamrat has been contact with Kaleido and hope to see a refresh of this article in the next month or two.

**Comment by skabou** [comment]
Thank you for your feedback. It appears this has been addressed. If further assistance is needed, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
