### ISSUE TITLE
what if we include Network policies into the diagram

### ISSUE THREAD

**Issue by giltecz** [MicrosoftDocs/architecture-center#4271]
I was participating in a linkedin discussion , here is the[ link](https://www.linkedin.com/posts/chenjd_azuretips-apigateways-azure-activity-7122780764689100800-RHpV?utm_source=share&utm_medium=member_desktop)  and I noticed this is a great diagram for end to end encryption and the use of app gateway and APIs, I'd like to suggest to incorporate Network policies for a robust design from a cybersecurity perspective. Network policies provide namespace and pod traffic segregation that mitigate the risk of containers' common attacks such as ransomware, exposure of sensitive data PHI, Malware, or crypto mining

Network policies are part of the CIS Benchmark standard recommendation for Kubernetes deployment, this is the control number 4.4.1	Ensure latest CNI version is used, Microsoft uses Azure CNI for network policies.  https://learn.microsoft.com/en-us/azure/aks/use-network-policies

If there is something I can help with, please let me know, Ill be glad to contribute. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Version Independent ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Content: [Deploy AKS and API Management with mTLS - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/mutual-tls-deploy-aks-api-management?WT.mc_id=DT-MVP-5001664)
* Content Source: [docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @saswatmohanty01
* Microsoft Alias: **samohant, rapencha, arazeem**

**Comment by ManoharLakkoju-MSFT** [comment]
@giltecz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177417 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
