### ISSUE TITLE
Include details on setup and how token usage is calculated / inferred / estimated

### ISSUE THREAD

**Issue by ryanspletzer** [MicrosoftDocs/architecture-center#4273]
This page is lacking detailed steps on how to actually setup this architecture, beyond just a diagram and some explanatory notes; no setup steps or sample IaC is provided.

Beyond that, I am failing to see how tokens are calculated / inferred / estimated at the APIM layer in this diagram, because Azure OpenAI itself doesn't provide token consumption metrics in response headers for the APIM gateway to know -- so really, how is that being accomplished for logging here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59e64035-d0cb-d2cf-0848-4153b5cfe876
* Version Independent ID: 59e64035-d0cb-d2cf-0848-4153b5cfe876
* Content: [Implement logging and monitoring for Azure OpenAI large language models - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/ai-ml/openai/architecture/log-monitor-azure-openai)
* Content Source: [docs/ai-ml/openai/architecture/log-monitor-azure-openai.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/ai-ml/openai/architecture/log-monitor-azure-openai.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jakeatmsft
* Microsoft Alias: **jacwang**

**Comment by ManoharLakkoju-MSFT** [comment]
@ryanspletzer 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ryanspletzer** [comment]
Update: My mistake, I see that "usage" is part of the Azure OpenAI response body which includes tokens consumed -- that said, it would be helpful if there was an example of how this is captured and logged at the APIM layer.

**Comment by ryanspletzer** [comment]
Ok so closing the loop here, I think this repo referenced at the bottom of the page has the fine-grained details to actually set this up: https://github.com/Azure-Samples/openai-python-enterprise-logging

So that answered my remaining question, likely can close the issue. :)

**Comment by ckittel** [comment]
#please-close
