### ISSUE TITLE
409 response on retry

### ISSUE THREAD

**Issue by hqaffesha13** [MicrosoftDocs/architecture-center#4274]
[Enter feedback here]
Under General REST and retry guidelines we need to add the following point need to update to include 500 Operation Timeout:

The HTTP status code returned from the service can help to indicate whether the failure is transient. You may need to examine the exceptions generated by a client or the retry framework to access the status code or to determine the equivalent exception type. The following HTTP codes typically indicate that a retry is appropriate:

408 Request Timeout
429 Too Many Requests
500 Internal Server Error **\Operation Timeout**
**500 Operation Timeout**
502 Bad Gateway
503 Service Unavailable
504 Gateway Timeout

Additionally, a new point needs to be added indicating the following: 

- In certain scenarios, when retrying a failed request, the retry request may return a 409 error indicating that the blob already exists. This situation can occur when the blob was actually successfully created during the initial request. However, the server may have encountered a 500 error while attempting to acknowledge the successful creation of the blob, leading to 409 responses during the retry. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Azure service retry guidance - Best practices for cloud applications](https://learn.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-storage)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/best-practices/retry-service-specific.md)
* Service: **architecture-center**
* Sub-service: **best-practice**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by ManoharLakkoju-MSFT** [comment]
@hqaffesha13 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
#please-close
