### ISSUE TITLE
Wrong Icon in the diagram

### ISSUE THREAD

**Issue by vietphamh** [MicrosoftDocs/architecture-center#4275]
I found out that we use the Azure Application Gateway icon instead of Active Directory in the On-premises container.
The content is great. Just help it to be more accurate.

Happy coding!
<img width="153" alt="Screenshot 2023-10-27 at 22 11 47" src="https://github.com/MicrosoftDocs/architecture-center/assets/8035996/ab5289eb-6ba4-4e50-a89b-8d39a0617694">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7b130b0-a3fd-3fd7-900f-7bc900e23ef2
* Version Independent ID: 63bbdf46-1c0c-7d33-54d1-68cf2329c6cd
* Content: [Computer forensics chain of custody in Azure - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/forensics/)
* Content Source: [docs/example-scenario/forensics/index.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/forensics/index.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @simonesavi
* Microsoft Alias: **sisavi**

**Comment by ManoharLakkoju-MSFT** [comment]
@vietphamh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
I pinged, @simonesavi to see if he can fix this up, thanks for noticing, @vietphamh

**Comment by mSarts** [comment]
Resolved in https://github.com/MicrosoftDocs/architecture-center-pr/pull/11258.
