### ISSUE TITLE
2nd cluster neccessary?

### ISSUE THREAD

**Issue by alleje02** [MicrosoftDocs/architecture-center#4276]
I would love to see a similar option to this that doesn't require spinning up an entire separate cluster. 

I'd mutch rather use 2 distinct deployments within the same cluster. With proper resource management,  node selectors, taints, tolerations you can achieve very high level of control which ensures they do not interfere with each other if you need that level of segregation. 

I simply don't see the benefit here to having the 2nd cluster , I only see additional cost and complexity and longer deployment times due to the new Cluster Nodes having no container image cache/history for the bloated and slow Windows Container Images used for my deployment. 

This would be mitigated by an option that doesn't include a 2nd cluster. 

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75b93b83-916c-f871-a4a8-3bd9d637d586
* Version Independent ID: 75b93b83-916c-f871-a4a8-3bd9d637d586
* Content: [Blue-green deployment of AKS clusters - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/aks/blue-green-deployment-for-aks)
* Content Source: [docs/guide/aks/blue-green-deployment-for-aks.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/aks/blue-green-deployment-for-aks.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @vimorra
* Microsoft Alias: **vimorra**

**Comment by ManoharLakkoju-MSFT** [comment]
@alleje02 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by vimorra** [comment]
The guidance is driven by the approach to treat  AKS as a cat and not a pet, this means that every major or relevant change in the Cluster requires to perform a dedicated deployment of new cluster and validate that everything is working fine before promote the change. This still remain the most reliable process to perform changes/updated to the AKS infra/paas. Logical segregation if not applied correctly can still create unwanted issues, and also create an overhead of complexity regarding the resource assignment for the scaling.
Regarding cost and complexity I don't think that they are higher if you use the same cluster, nodes provisioning, scheduling and related costs are quite the same. For a cost point of view, anyhow, the mitigation is that the two clusters need to run in parallel only for a short period of time

**Comment by ckittel** [comment]
🐈?  🤣
