### ISSUE TITLE
connected-fleet-refarch repo isn't avaliable

### ISSUE THREAD

**Issue by JEFFERSON-FERREIRA-LIMA** [MicrosoftDocs/architecture-center#4277]
I would like to access it for implementation consultation. This material will serve as support for my personal project.

(https://github.com/microsoft/connected-fleet-refarch)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: 8ae3b33d-548d-d52e-5ca7-06ce43f5e3ec
* Version Independent ID: 8ae3b33d-548d-d52e-5ca7-06ce43f5e3ec
* Content: [Frotas automotivas conectadas - Azure Architecture Center](https://learn.microsoft.com/pt-br/azure/architecture/industries/automotive/automotive-connected-fleets)
* Content Source: [docs/industries/automotive/automotive-connected-fleets.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/industries/automotive/automotive-connected-fleets.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Marioo
* Microsoft Alias: **marioo**

**Comment by RamanathanChinnappan-MSFT** [comment]
@JEFFERSON-FERREIRA-LIMA 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by msmarioo** [comment]
The repository will be made public this week.
