### ISSUE TITLE
New TAXII Threat Intel Feeds Required

### ISSUE THREAD

**Issue by jeffrywu28** [MicrosoftDocs/architecture-center#4279]
I want new documentation about free and easy to use TAXII Threat Intel feeds.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb40dd7-0e77-0f95-8070-95978cd4a90c
* Version Independent ID: 4476618b-beb5-c8c4-ec8b-787db30643fb
* Content: [Cyber threat intelligence in Microsoft Sentinel - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/data/sentinel-threat-intelligence)
* Content Source: [docs/example-scenario/data/sentinel-threat-intelligence.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/sentinel-threat-intelligence.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jeffrywu28
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
#please-close
