### ISSUE TITLE
The content of this page is outdated

### ISSUE THREAD

**Issue by antsok** [MicrosoftDocs/architecture-center#4285]
Multiple features were added to Synapse Analytics since the article was written, so the feature comparison table is outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bba35cbb-4160-0b5d-6829-103b25ad6ce9
* Version Independent ID: fa12ea8e-401a-9567-7b35-ffff532a99b6
* Content: [Choose a batch processing technology - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing)
* Content Source: [docs/data-guide/technology-choices/batch-processing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/batch-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by SaibabaBalapur-MSFT** [comment]
@antsok 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 183333 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
