### ISSUE TITLE
Suggestion: replace `Azure NetApp Files` with `Azure Files`

### ISSUE THREAD

**Issue by jfbilodeau** [MicrosoftDocs/architecture-center#4286]
As a Microsoft Technical Trainer, I don't see much activity with Azure NetApp Files. Instead, Azure Files seem more common.

To that end, may I suggest that under the table at https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/managed-services#paas-alternatives-to-iaas-solutions, we replace `Azure NetApp Files` with `Azure Files` (https://azure.microsoft.com/en-ca/products/storage/files)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 952ee382-9a9e-0f79-807b-1f7c2b819a42
* Version Independent ID: 82f16168-5f05-f8e3-8971-fa9c7cbb828f
* Content: [Use platform as a service (PaaS) options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/managed-services)
* Content Source: [docs/guide/design-principles/managed-services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/design-principles/managed-services.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
Thank you for pointing this out. This has been updated and should be live within one or two business days.
