### ISSUE TITLE
Diagram has a mispelling on CosmosDB

### ISSUE THREAD

**Issue by danielkon96** [MicrosoftDocs/architecture-center#4287]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 779b0c0e-591b-2a38-5076-1c3c046e662c
* Version Independent ID: d681f23c-1480-b49c-bbc6-f38d76958f7e
* Content: [Serverless apps using Azure Cosmos DB - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/databases/idea/serverless-apps-using-cosmos-db)
* Content Source: [docs/databases/idea/serverless-apps-using-cosmos-db.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/databases/idea/serverless-apps-using-cosmos-db.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@danielkon96 
Thanks for your feedback! We will investigate and update as appropriate.
