### ISSUE TITLE
MS Entra Cloud Sync Description Missing

### ISSUE THREAD

**Issue by evoke-gsmith** [MicrosoftDocs/architecture-center#4291]
[Enter feedback here]

This page makes no mention of MS Entra Cloud Sync, which I had thought represented MS's desired direction for Entra ID (formerly Azure AD) integration. It is confusing not seeing MS Entra Cloud Sync mentioned here as part of a potential reference architecture. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd6463b2-ccca-e0f5-ed8e-ed239541a5c7
* Version Independent ID: 3f497c55-e522-476c-8e63-37de63ff0603
* Content: [Integrate on-premises AD with Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/identity/)
* Content Source: [docs/reference-architectures/identity/index.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/identity/index.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by SaibabaBalapur-MSFT** [comment]
@evoke-gsmith 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 183324 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
