### ISSUE TITLE
Link to artifact titled "Guide to migrating Big Data workloads to Azure HDInsight" is broken

### ISSUE THREAD

**Issue by arnabganguly** [MicrosoftDocs/architecture-center#4294]
The link to the artifact titled "Guide to migrating Big Data workloads to Azure HDInsight" in the "Lift and Shift to HDInsight" section is broken. Could you please fix this link? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c269dec-85ae-1519-e309-ae710fff30f4
* Version Independent ID: 7c269dec-85ae-1519-e309-ae710fff30f4
* Content: [Hadoop migration to Azure - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/hadoop/overview)
* Content Source: [docs/guide/hadoop/overview.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/hadoop/overview.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **namratam**

**Comment by SaibabaBalapur-MSFT** [comment]
@arnabganguly 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 183323 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
