### ISSUE TITLE
el certificate authority services y los certifiados ca, client, servet: son certificados externos o van al key vault??????

### ISSUE THREAD

**Issue by Darwin261082** [MicrosoftDocs/architecture-center#4296]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Version Independent ID: 62170efa-4c46-b1ac-92c5-d2e71c144811
* Content: [Implementación de AKS y API Management con mTLS - Azure Architecture Center](https://learn.microsoft.com/es-es/azure/architecture/solution-ideas/articles/mutual-tls-deploy-aks-api-management)
* Content Source: [docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/mutual-tls-deploy-aks-api-management.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @saswatmohanty01
* Microsoft Alias: **samohant, rapencha, arazeem**

**Comment by SaibabaBalapur-MSFT** [comment]
@Darwin261082 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by Darwin261082** [comment]
EL CAS Y LOS CERTIFICADOS CERT,CA,CLIENT SON EXTERNOS A LA REGION AZURE?

**Comment by SaibabaBalapur-MSFT** [comment]
@Darwin261082 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
