### ISSUE TITLE
Make Azure Icons downloads more accessible (edited)

### ISSUE THREAD

**Issue by JohnRobertN** [MicrosoftDocs/architecture-center#4297]
(Edited: Added body here from the original title):
It seems insanely difficult to get a page in microsoft.com or on github with the list of Microsoft's icons for designing high level overviews or to understand them. Every single page about this is bla bla bla! These are webpages, come on folks, publish the free...in icons simple clear central with names so others can recognize them. Why all the nonsense with download zip files which are seeminly empty and to go somewhere and further and log into github and yadayada. Don't the productmanager's have any ownership? Why not publish the icons so that everybody can read the articles which are full of MS icons and their partner's icons. Graphically of course!! It is about icons, not text. - Sorry about the mood between the letters, no understanding why people keep 'providing guidance' instead of answers. Any search on or with microsoft to find the list of icons leads to click click clickbait, seemingly, never to graphics, seemingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by navba-MSFT** [comment]
@JohnRobertN Thanks for the reaching out to us and sharing this feedback. This issue has been assigned to content-author to look into this.

**Comment by Zimmergren** [comment]
@JohnRobertN , thank you for taking the time to submit a ticket on this topic.

- You don't need to sign into GitHub to download the icons.
  - Simply visit the page, tick the box that you agree to the usage terms, and then hit the download button.
- The Zip file you download contains more than six hundred Azure Icons used for building architecture diagrams, etc. It's not empty.

I will make an internal note of the fact that you want to be able to _browse the icons visually_, as opposed to just a download file with all the svg icons. Is that the takeaway from your comment, @JohnRobertN?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 183318 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
