### ISSUE TITLE
Pipeline Example

### ISSUE THREAD

**Issue by thepaulmacca** [MicrosoftDocs/architecture-center#4299]
What would really compliment this I feel, is an example pipeline for Azure Pipelines/GitHub Actions. Is there one available that can be added as a reference to this doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57f4d213-3eb1-5b4c-aa67-116e8fa36f7d
* Version Independent ID: 18199b5a-8f57-6574-c795-7540199ae49a
* Content: [Microservices CI/CD pipeline on Kubernetes with Azure DevOps and Helm - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes)
* Content Source: [docs/microservices/ci-cd-kubernetes.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/ci-cd-kubernetes.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @jpocloud
* Microsoft Alias: **johnpoole**

**Comment by ManoharLakkoju-MSFT** [comment]
@thepaulmacca 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by thepaulmacca** [comment]
Sorry I thought that would be auto linked to this. This is the page https://learn.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes

Thanks

**Comment by ManoharLakkoju-MSFT** [comment]
@thepaulmacca 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 183314 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
