### ISSUE TITLE
PowerAutomate 202 Clients != Azure Logic App 202 Clients 

### ISSUE THREAD

**Issue by endintiers** [MicrosoftDocs/architecture-center#4307]
Regarding access control for the Status endpoint, the documentation mentions:

"This URL could be a SAS token with the [Valet Key Pattern](https://github.com/MicrosoftDocs/architecture-center/blob/main/docs/patterns/valet-key.yml) being appropriate if this location needs access control. The valet key pattern is also valid when response polling needs offloading to another backend"

The client implementations of Async 202 in  PowerAutomate and Azure Logic Apps are different. Azure Logic Apps passes the token used on the initial 202 call to the status endpoint. PowerAutomate does not (and so requires the Valet Key Pattern).

The Valet Key Pattern could work for either, but it is confusing in that it is not required for Azure Logic Apps.

So can the documentation be updated to indicate that standard Microsoft Identity/Bearer token security can be used in Status endpoints for Azure Logic Apps but Valet Key needs to be used for APIs that have PowerAutomate clients (if security is required on the status endpoint).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d94a95d1-5371-4c6a-87d6-00fae7dfb401
* Version Independent ID: d9abac19-dfd7-18d7-2479-42fe5476b569
* Content: [Valet Key pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/valet-key)
* Content Source: [docs/patterns/valet-key.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/valet-key.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
This is great feedback. I just pushed an update to the async request response article, and it should be live in a few business days.
