### ISSUE TITLE
mTLS termination

### ISSUE THREAD

**Issue by ucantravel** [MicrosoftDocs/architecture-center#4309]
I wonder if the same pattern can be applied to the mTLS traffic, not just regular TLS traffic.
The mTLS connection would be terminated at the Azure Gateway level, then the Gateway would initiate a regular TLS connection to the Azure Firewall, which can easily be inspected by it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f623b3a-09d7-d793-b007-85b59727c1df
* Version Independent ID: ec0506cd-cdba-784c-6832-ea59697dd39c
* Content: [Zero-trust network for web applications with Azure Firewall and Application Gateway - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/gateway/application-gateway-before-azure-firewall)
* Content Source: [docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by erjosito** [comment]
Yes, having mTLS between the client and AppGW doesnt affect to the rest of the communication.

**Comment by ucantravel** [comment]
Thanks. Will test and confirm if indeed mTLS for the front end, translates to regular TLS in the backend.

**Comment by Naveenommi-MSFT** [comment]
@ucantravel 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
This request appears to have been addressed. If additional assistance is needed, please re-open with additional information.
