### ISSUE TITLE
iot and camera data pipeline arhcitecture

### ISSUE THREAD

**Issue by Mouadbenaou** [MicrosoftDocs/architecture-center#4310]
in insdustrial sector , i want to create a a system that allows us to inference AI models on cameras data and iot censors. the cameras and iot are installed in the field , for that camera we already have the nx-vms solution as video manager system runing on a field_local_server and iot is shared to influxdb cloud via gateway. we want to make sure that the inference is done on real time and processed data can be saved on a storage pool on azure. historical data ( viode and iot data ) also to be stored but not entirely ( videos of mulitple camera can cost many Tb we want torun script that flters data before sending it ) .
also we have an analytics cluster ( of jupyterhub and gpu empowered machines , not yet created ) that have to acces the data and run some model training there ( how this connection is made and does consume money ... ) and also we want to be able to deply our model in aesy way . 
know that we arleady have azure devops license .

**Comment by Naveenommi-MSFT** [comment]
@Mouadbenaou 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Mouadbenaou** [comment]
@Naveenommi-MSFT  here's the link i started with :https://learn.microsoft.com/en-us/azure/architecture/ai-ml/architecture/analyze-video-computer-vision-machine-learning

but steps i described are the functional requirement of the data team
