### ISSUE TITLE
No Potential Use Cases in "Potential Use cases" section

### ISSUE THREAD

**Issue by aniatmicrosoft** [MicrosoftDocs/architecture-center#4317]
The Potential Use cases section only states the security features of this architecture. But does not mention potential use cases of Big Data Analytics itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cce4daf-bd8d-bd82-54a0-17e905a1c150
* Version Independent ID: 0dbc5354-031f-2d79-99da-68f9719e89d4
* Content: [Big data analytics with enterprise-grade security using Azure Synapse - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/big-data-analytics-enterprise-grade-security)
* Content Source: [docs/solution-ideas/articles/big-data-analytics-enterprise-grade-security.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/big-data-analytics-enterprise-grade-security.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **kikalyan**

**Comment by AjayBathini-MSFT** [comment]
@aniatmicrosoft 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196643 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
