### ISSUE TITLE
Private DNS Resolver with ExpressRoute VNG problem

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/architecture-center#4322]
[Enter feedback here]
On the documentation for ExpressRoute Virtual Network Gateways, there is a note that Private DNS Resolver should not be put in the vNet with the gateway. 

Linking an Azure DNS private resolver to the virtual network where the ExpressRoute virtual network gateway is deployed may cause management connectivity issues and is not recommended.

https://learn.microsoft.com/en-us/azure/expressroute/expressroute-about-virtual-network-gateways#gwsub

The architecture on this document is showing the Private DNS Resolver in the hub vNet with the ExpressRoute. There is an inconsistency in the two recommendations.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Version Independent ID: 6ce03940-eeb4-98b6-4624-1615715beec4
* Content: [Azure DNS Private Resolver - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/azure-dns-private-resolver)
* Content Source: [docs/example-scenario/networking/azure-dns-private-resolver.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/networking/azure-dns-private-resolver.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @moorthyannadurai
* Microsoft Alias: **moannadu**

**Comment by AjayBathini-MSFT** [comment]
@cchapin2020 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by moorthyannadurai** [comment]
Made changes to the Article to accommodate the new ER gw recommendation. Awaiting for the review & approval for the Pull Request..

**Comment by ckittel** [comment]
@moorthyannadurai - can you link to that PR? Is it merged? Can this be closed now?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196640 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
