### ISSUE TITLE
Feedback: Provided RDP Property "enabledsaadauth:i:1" as required for Entra ID

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/architecture-center#4326]
Hey Team -- I feel this often gets overlooked by many customers where they do not set the `Microsoft Entra single sign-on` option for their RDP properties in a Host Pool.  This should also be suggested to be added:

`enablerdsaadauth:i:1`

![image](https://github.com/MicrosoftDocs/architecture-center/assets/26752719/14e32dcc-e3a8-4d46-a232-a10eb1ac6014)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96947883-d52b-1ed8-7db2-915f025060af
* Version Independent ID: 96947883-d52b-1ed8-7db2-915f025060af
* Content: [Microsoft Entra join for Azure Virtual Desktop - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join)
* Content Source: [docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@brmcmill 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196634 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
