### ISSUE TITLE
文件內容已經過時了

### ISSUE THREAD

**Issue by richardlfs** [MicrosoftDocs/architecture-center#4327]
[請在此輸入您的意見]
現在QnA maker 和LUIS已經要退休了，取而代之的是QuestionAnswering和Conversational Language Understanding. 請更新文件資訊。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 learn.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: f3d6aeb8-ec6a-4d27-2d10-1b404de450b7
* Version Independent ID: 65b165e4-a2e4-7f57-19eb-884fce7bf880
* Content: [企業級對話式 Bot - Azure Architecture Center](https://learn.microsoft.com/zh-tw/azure/architecture/ai-ml/architecture/conversational-bot)
* Content Source: [docs/ai-ml/architecture/conversational-bot.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/ai-ml/architecture/conversational-bot.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @roalexan
* Microsoft Alias: **roalexan, mithal**

**Comment by ckittel** [comment]
This article does need to be updated to reflect these product changes. @RobBagby, can you get the AI ARB to assist?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196632 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
