### ISSUE TITLE
Missing Import Directives in Python Code

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/architecture-center#4330]
The code is missing where to get functions like normalize_text and splitter.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3026912b-cf94-e0fb-0b83-6f78219b24e0
* Version Independent ID: 3026912b-cf94-e0fb-0b83-6f78219b24e0
* Content: [Query-based document summarization - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/query-based-summarization)
* Content Source: [docs/ai-ml/guide/query-based-summarization.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/ai-ml/guide/query-based-summarization.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @raniabayoumy
* Microsoft Alias: **rabayoum**

**Comment by ckittel** [comment]
@asocorro there was not enough information provided to act on this. We need to know which article you're talking about.  Please help us help you by providing enough information to act on.

**Comment by asocorro** [comment]
Sorry, I just clicked on the feedback icon.  This is the page:

https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/query-based-summarization
[https://learn.microsoft.com/en-us/media/open-graph-image.png]<https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/query-based-summarization>
Query-based document summarization - Azure Architecture Center<https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/query-based-summarization>
Implement query-based document summarization by using the Azure OpenAI GPT-3 model. Review two example use cases.
learn.microsoft.com


Thanks,
Adolfo

________________________________

[cid:e7baae91-efb8-4c14-976f-2050b33d977f]



Adolfo J. Socorro, Ph.D.
President
eSolutions, Inc.



eSolutionsPR.com<http://www.esolutionspr.com/>
LinkedIn Profile<https://www.linkedin.com/in/adolfosocorro/>

787-553-3200 (Mobile)

.:. Business Intelligence and SQL Server Solutions .:.













The information contained in this message is a private interchange between the sender and the recipient.
Business ideas, proposals, and other such matters may not be disclosed to third parties without prior mutual consent.



________________________________

**Comment by ckittel** [comment]
@noabenefraim can you update the document with some information about what python packages are referenced for this, or in a prereq section link off to some other place that has it listed?

**Comment by SaibabaBalapur-MSFT** [comment]
@asocorro 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196630 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
