### ISSUE TITLE
Provide Solution/Pattern Using Just Databricks for both Streaming & Batch

### ISSUE THREAD

**Issue by adaptiv-rsarangan** [MicrosoftDocs/architecture-center#4337]
Re. modern analytics architecture using Databricks: https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture

The existing solution idea utilises both Databricks and Synapse Analytics for streaming and batch data loads respectively. We have come across customers who would prefer a single platform and given Databricks' capability to handle both streaming and batch processes, it would help to have a reference architecture that purely makes use of Databricks' data warehousing layer.

In the case of link above, Step 8 (Synapse Analytics) is entirely superfluous and the same business use-cases can be achieved without it.

Proposed Solution: Split this into two (or three) solution patterns - 
1. One using just Databricks.
2. One as a hybrid of Databricks + Synapse Analytics (current solution). 
3. As an alternative, there could also be a third solution idea with just Synapse Analytics.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7254782d-e773-b542-73e8-f568d3bbee39
* Version Independent ID: 40d81223-f8ea-2eec-616e-5f6ee28c8206
* Content: [Modern analytics architecture with Azure Databricks - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-databricks-modern-analytics-architecture)
* Content Source: [docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-databricks-modern-analytics-architecture.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by adaptiv-rsarangan** [comment]
Happy to fork and PR with suggested changes if that would help :)

**Comment by ManoharLakkoju-MSFT** [comment]
@adaptiv-rsarangan 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by adaptiv-rsarangan** [comment]
Hey team, any updates here? @ManoharLakkoju-MSFT , @martinekuan 

Thanks!

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196628 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
