### ISSUE TITLE
Use Identify Service should be level 1 header as the rest of 9 principles. 

### ISSUE THREAD

**Issue by forresthu** [MicrosoftDocs/architecture-center#4338]
Use Identify Service should be level 1 header as the rest of 9 principles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb507d50-57ff-115b-f19f-8e7e8e255763
* Version Independent ID: 8b46d95d-e49b-342c-dd2e-df49f39b175f
* Content: [Design principles for Azure applications - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/)
* Content Source: [docs/guide/design-principles/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/design-principles/index.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by ManoharLakkoju-MSFT** [comment]
@forresthu 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
I've opened a PR to remediate this.  Once reviewed and merged (this issue will automatically close when the merge happens), it'll be published within a business day.
