### ISSUE TITLE
It would be great to find either in azure docs or in portal.azure.com a list of all PAAS, list of all SAAS and IAAS options

### ISSUE THREAD

**Issue by mukundkatpatal** [MicrosoftDocs/architecture-center#4340]
The list here does not seem to be complete. 
It would be great to find either in azure docs or in portal.azure.com a list of all PAAS, list of all SAAS and IAAS options. Is it possible to give the entire list?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 952ee382-9a9e-0f79-807b-1f7c2b819a42
* Version Independent ID: 82f16168-5f05-f8e3-8971-fa9c7cbb828f
* Content: [Use platform as a service (PaaS) options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/design-principles/managed-services)
* Content Source: [docs/guide/design-principles/managed-services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/design-principles/managed-services.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@mukundkatpatal 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196626 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
