### ISSUE TITLE
ICollector / IAsyncCollector information out of date

### ISSUE THREAD

**Issue by aelij** [MicrosoftDocs/architecture-center#4343]
It looks like those interfaces can only be used in the old runtime. What's the alternative in the latest runtime?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 979dcd3b-c606-22f0-0b2e-f46235a59d4d
* Version Independent ID: 25033a72-1b42-524f-4efa-bed2f9e43fee
* Content: [Performance and scale guidance for Event Hubs with Azure Functions - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/serverless/event-hubs-functions/performance-scale)
* Content Source: [docs/serverless/event-hubs-functions/performance-scale.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/serverless/event-hubs-functions/performance-scale.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @dbarkol
* Microsoft Alias: **dabarkol**

**Comment by Naveenommi-MSFT** [comment]
@aelij
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbarkol** [comment]
For output to Event Hubs, the recommendation for the isolated worker model would be to use the SDK types. Reference: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#sdk-types. 

We can update the document to reference this and make not of the differences between the isolated worker and in-process models.

**Comment by skabou** [comment]
#please-close
