### ISSUE TITLE
Service "Azure Disk Storage" missing for Block storage

### ISSUE THREAD

**Issue by pratmeht** [MicrosoftDocs/architecture-center#4344]
[Enter feedback here]
The equivalent service for "AWS EBS", I believe, should be "Azure Disk Storage", however the page says "Azure Blob Storage" (which is an object store). In case if I am wrong, kindly help me understand what point am I missing  ?

Regards,
Pratik Mehta

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/aws-professional/services.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @martinekuan
* Microsoft Alias: **yuanzhiqu**

**Comment by Naveenommi-MSFT** [comment]
@pratmeht 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196622 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
