### ISSUE TITLE
[Icon Request] Icon "Device" for IoT Hub Service missing

### ISSUE THREAD

**Issue by az38** [MicrosoftDocs/architecture-center#4346]
Icon "Device" for IoT Hub Service is missing
Menu "Device Management -> Devices"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by Naveenommi-MSFT** [comment]
@az38
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Zimmergren** [comment]
Hey @az38 , I've reviewed the icons package and found the Device icon for the IoT Hub Service: 

- icons/other/02475-icon-service-Device-Update-IoT-Hub.svg

I'll make a note in the backlog for the icons team to consider moving this into a more relevant folder. Thanks for reporting!

**Comment by az38** [comment]
Hi @Zimmergren 
Provided icon differs from actual Azure Portal icons (see attached).
The icon icons/other/02475-icon-service-Device-Update-IoT-Hub.svg is the same as "Device Management - Update" icon (see attached)
![device](https://github.com/MicrosoftDocs/architecture-center/assets/59407868/f2f8686d-09c2-41f3-acd1-5772ac6922b9)

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 214796 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
