### ISSUE TITLE
Icons "Container", "File Share", "Queue" and "Table" for Storage Account are missing

### ISSUE THREAD

**Issue by az38** [MicrosoftDocs/architecture-center#4347]
Icons "Container", "File Share", "Queue" and "Table" for Storage Account are missing

Document Details
⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
Service: architecture-center
GitHub Login: @Zimmergren
Microsoft Alias: tozimmergren

**Comment by Naveenommi-MSFT** [comment]
@az38 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by az38** [comment]
Hi @Naveenommi-MSFT 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by Zimmergren** [comment]
Thank you for reporting this, @az38. We'll look into this.

**Comment by Naveenommi-MSFT** [comment]
@az38 
Thank you for bringing this to our attention.
I've delegated this to content author @Zimmergren, who will review it and offer their insightful opinions.

**Comment by Zimmergren** [comment]
@az38, the icons do exist in the current icons package: 

- icons/general/10838-icon-service-Storage-Azure-Files.svg
- icons/general/10839-icon-service-Storage-Container.svg
- icons/general/10840-icon-service-Storage-Queue.svg
- icons/general/10841-icon-service-Table.svg

I'll make a note in the backlog for the icons team to consider moving them into the "Storage" service folder instead for future updates. Thanks! #please-close

**Comment by az38** [comment]
Hi @Zimmergren 
Provided icons differ from actual Azure Portal icons (see attached)
![container](https://github.com/MicrosoftDocs/architecture-center/assets/59407868/11cebeab-3988-459e-b326-8d60bfb8b86f)

**Comment by ckittel** [comment]
@az38 the portal now uses
<img width="126" alt="image" src="https://github.com/MicrosoftDocs/architecture-center/assets/671075/1ab4771f-f491-44a1-b9d3-68aa42fa743d">

which is still different than the icon shipped in this pack.  I'm opening a request with the icon team to see if they can reconcile.

**Comment by ckittel** [comment]
The icon shipped in the zip file is considered the correct one to use.  The icon team will be working with the product team to get their portal experience aligned.

**Comment by ckittel** [comment]
> I'll make a note in the backlog for the icons team to consider moving them into the "Storage" service folder instead for future updates.

The icon team rejected the request to move these files. Reason: "[We] will not be relocating these icons. The icons are not exclusive to services that fall under the 'Storage' category. They are generic and can be used in other experiences throughout Azure."  - I don't personally agree with that decision, but will not be following it up further.
