### ISSUE TITLE
HDInsight Storm is deprecated

### ISSUE THREAD

**Issue by yeturis** [MicrosoftDocs/architecture-center#4351]
[Enter feedback here]

HDInsight Storm is deprecated and needs to be replaced with HDInsight on AKS - Apache Flink - https://learn.microsoft.com/en-us/azure/hdinsight-aks/flink/flink-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 957618b3-8d25-49c4-950c-0c044d68f443
* Version Independent ID: 2ab67665-066b-fb14-9763-a12693b19bec
* Content: [Choose a stream processing technology - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing)
* Content Source: [docs/data-guide/technology-choices/stream-processing.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/technology-choices/stream-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by AjayBathini-MSFT** [comment]
@yeturis 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 200831 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
