### ISSUE TITLE
No link for Sample queries

### ISSUE THREAD

**Issue by arunlouie** [MicrosoftDocs/architecture-center#4352]
The list of saved queries of Spark metrics, not sure where to find. No link or reference is added. Please add the actual queries of all those listed metrics.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53478500-e539-fc72-18c0-84d9f2a75b14
* Version Independent ID: 8b08572c-574b-be37-7511-3b52c998bd81
* Content: [Observability patterns and metrics - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/databricks-monitoring/databricks-observability)
* Content Source: [docs/databricks-monitoring/databricks-observability.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/databricks-monitoring/databricks-observability.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @drmcghee
* Microsoft Alias: **davidmcg**

**Comment by AjayBathini-MSFT** [comment]
@arunlouie 
Thanks for your feedback! We will investigate and update as appropriate.
