### ISSUE TITLE
Clarify Statement

### ISSUE THREAD

**Issue by doyinosin** [MicrosoftDocs/architecture-center#4353]
The below statement right after the Lookup Strategy image is unclear to me:

**_The mapping between the shard key and the physical storage can be based on physical shards where each shard key maps to a physical partition_**

- I presume the 'mapping' here is the indication of which physical storage contains the data associated with respective distinct shard key values. Please confirm.
- Are 'shard', 'partition' and 'storage' used interchangeably? If so, consistent use within the same statement would make it easier to understand. Switching terms might suggest separate concepts are being referenced.
- If interchangeable, I understand:
  - The mapping is between the shard key (distinct value) and a physical shard where each shard key (distinct value) is associated with a physical shard
- Why I specify **shard key (distinct value)**
- I understand the shard key to be the basis of the scheme by which data is distributed among shards. In certain contexts, it makes more sense to distinguish the shard key (the column/field) from its values. I fail to see how the shard key itself maps to a physical partition. Am I right to think this refers to distinct **shard key values** instead (not the shard key itself)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 050bb1fd-56ca-63bc-b105-17a56e3b0362
* Version Independent ID: ce84d0a7-3596-e259-dfc3-a9789efd9948
* Content: [Sharding pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/sharding)
* Content Source: [docs/patterns/sharding.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/sharding.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@doyinosin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
Great feedback!  We've pushed an update that should be live in a few business days to help clarify. You're right that adding "value" into shard key helps tie this together better.  The distinction between the shard key and its value is critical here, and "value" was the target for this section.  This issue will auto close due to the PR merging.
