### ISSUE TITLE
The Providence Health link does not work anymore

### ISSUE THREAD

**Issue by sagarmj-cloud** [MicrosoftDocs/architecture-center#4354]
The Providence Health link does not work anymore and is no longer present under the customer stories.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bc2d027-a2ca-cacf-0a0e-baacb39971ba
* Version Independent ID: 112a0f01-67cd-d1ce-4af3-47e4e89848e1
* Content: [Build ETL pipelines with Azure Databricks and Delta Lake - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/ingest-etl-stream-with-adb)
* Content Source: [docs/solution-ideas/articles/ingest-etl-stream-with-adb.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/ingest-etl-stream-with-adb.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @kpistor
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@sagarmj-cloud 
Thanks for your feedback! We will investigate and update as appropriate.
