### ISSUE TITLE
Solution idea question: Forecast energy and power demand with machine learning

### ISSUE THREAD

**Issue by jego9130** [MicrosoftDocs/architecture-center#4355]
I saw this 'solution idea': https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/forecast-energy-power-demand

I work at a distribution network company and we're interested in knowing more about this solution idea. It would be great if you can expand the content with more information, such as potential use cases, alternative services, implementation considerations, or pricing guidance

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90981e8d-b753-e389-1569-c544fe1c58e6
* Version Independent ID: 10c830e2-8257-2ee2-aae0-0a6e7df69695
* Content: [Forecast energy and power demand - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/forecast-energy-power-demand)
* Content Source: [docs/solution-ideas/articles/forecast-energy-power-demand.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/forecast-energy-power-demand.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @carlosasantos
* Microsoft Alias: **cfernandesdo**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jego9130
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 200822 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
