### ISSUE TITLE
Query Regarding The Doc

### ISSUE THREAD

**Issue by RockingThor** [MicrosoftDocs/architecture-center#4356]
[What do you mean by "An alternative language is better suited for the backend of a different user interface." ]

<img width="761" alt="Screenshot 2024-01-11 at 2 37 31 PM" src="https://github.com/MicrosoftDocs/architecture-center/assets/121621183/95781148-b18b-4721-9d07-3be21427f74a">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 064550fc-3915-2d6f-5ed1-9ee8f022a418
* Version Independent ID: ae425b05-6281-325f-28b9-e0de00877589
* Content: [Backends for Frontends pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/backends-for-frontends)
* Content Source: [docs/patterns/backends-for-frontends.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/backends-for-frontends.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
That looks like a typo.  I'll fix it.  What it means is this pattern is useful when one user interface (out of multiple) could benefit from having a backend in a specific programming language, relative to the other user interfaces.

**Comment by ckittel** [comment]
I've pushed a change for this and it likely will be live within the next business day or two.  Thank you for asking for clarity.
