### ISSUE TITLE
Doc enhancement on web and mobile apps

### ISSUE THREAD

**Issue by cguramir** [MicrosoftDocs/architecture-center#4359]
I would like to see this article expanded: Scalable web and mobile apps using Azure Database for PostgreSQL, with use cases, alternative services, deployment considerations, and pricing guide. Thank you!
Link to the article: https://learn.microsoft.com/es-es/azure/architecture/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: e325f722-cf4e-9e25-a612-3f832c1be677
* Version Independent ID: 7c43cd20-badd-7585-a7e9-8e1787f62def
* Content: [Aplicaciones web y móviles escalables mediante Azure Database for PostgreSQL - Azure Solution Ideas](https://learn.microsoft.com/es-es/azure/architecture/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql)
* Content Source: [docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @mootpointer
* Microsoft Alias: **anharvey**

**Comment by RamanathanChinnappan-MSFT** [comment]
@cguramir 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 200820 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
