### ISSUE TITLE
Expand on CICD in power platform

### ISSUE THREAD

**Issue by shefali-bedi** [MicrosoftDocs/architecture-center#4361]
Would love to have more in dept best practice to achieve CICD with developing power platform. Developers working on different branches for example for in a normal development process. I am missing the CI part. I would love to use Azure Devops for extendibility purpose. More info on this article would help https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4968f751-e9d6-6a37-c650-908531992510
* Version Independent ID: f9bf0889-546c-eb18-cfa5-72b42fae1fea
* Content: [CI/CD for Microsoft Power Platform - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform)
* Content Source: [docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/azure-devops-continuous-integration-for-power-platform.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @sarahparkes
* Microsoft Alias: **meparkes**

**Comment by AjayBathini-MSFT** [comment]
@shefali-bedi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 206030 to track and investigate this issue.txt

**Comment by skabou** [comment]
#please-close
