### ISSUE TITLE
"Azure Cognitive Search" is now "Azure AI Search"

### ISSUE THREAD

**Issue by mmonsma** [MicrosoftDocs/architecture-center#4362]
Azure Cognitive Search was renamed Azure AI Search in Nov 2023. Can you please update mentions the name here? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27e84411-8952-b723-928b-7643ffcc47b2
* Version Independent ID: 27e84411-8952-b723-928b-7643ffcc47b2
* Content: [Index file content and metadata by using Azure Cognitive Search - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/ai-ml/architecture/search-blob-metadata)
* Content Source: [docs/ai-ml/architecture/search-blob-metadata.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/ai-ml/architecture/search-blob-metadata.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jelledruyts
* Microsoft Alias: **jelled**

**Comment by navba-MSFT** [comment]
@mmonsma Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
