### ISSUE TITLE
I request Microsoft to provide details about the Delivery History service. It has been mentioned, 'We did use Azure Functions for one service, namely the Delivery History service.'

### ISSUE THREAD

**Issue by suchitrab** [MicrosoftDocs/architecture-center#4368]
I request Microsoft to provide details about the Delivery History service. It has been mentioned, 'We did use Azure Functions for one service, namely the Delivery History service.'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93139ee2-ff91-ee5e-a056-8d6b597a81f3
* Version Independent ID: 8b4436e0-094c-9602-2ead-43bb3b2f98f1
* Content: [Choose a compute option for microservices - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/microservices/design/compute-options)
* Content Source: [docs/microservices/design/compute-options.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/microservices/design/compute-options.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@suchitrab 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 206028 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
