### ISSUE TITLE
Correction in the Mutual TLS section

### ISSUE THREAD

**Issue by darrellnorton** [MicrosoftDocs/architecture-center#4370]
[Enter feedback here]
Regarding this content here:
Another alternative for restricting incoming traffic is mutual TLS (mTLS). _Manual_ TLS is a security protocol that ensures that both the client and server in communication are authenticated.

I believe the "Manual TLS" at the beginning of the second sentence should be "Mutual TLS"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6a78e94-c4d5-b382-7774-3fb3f1f7077d
* Version Independent ID: d6a78e94-c4d5-b382-7774-3fb3f1f7077d
* Content: [General considerations for choosing an Azure container service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/container-service-general-considerations)
* Content Source: [docs/guide/container-service-general-considerations.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/container-service-general-considerations.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @MarcosMMartinez
* Microsoft Alias: **julng**

**Comment by MarcosMMartinez** [comment]
Good catch, Darrell. We'll take care of this.

**Comment by AjayBathini-MSFT** [comment]
@darrellnorton 
Thanks for your feedback! We will investigate and update as appropriate.
