### ISSUE TITLE
UDR section needs to be updated

### ISSUE THREAD

**Issue by MarcosMMartinez** [MicrosoftDocs/architecture-center#4371]
UDR are compatible with Workload profiles not dedicated tier within workload profile exclusively. This needs to be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6a78e94-c4d5-b382-7774-3fb3f1f7077d
* Version Independent ID: d6a78e94-c4d5-b382-7774-3fb3f1f7077d
* Content: [General considerations for choosing an Azure container service - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/container-service-general-considerations)
* Content Source: [docs/guide/container-service-general-considerations.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/container-service-general-considerations.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @MarcosMMartinez
* Microsoft Alias: **julng**

**Comment by AjayBathini-MSFT** [comment]
@MarcosMMartinez 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MarcosMMartinez** [comment]
Ref: https://github.com/MicrosoftDocs/architecture-center-pr/pull/11633
