### ISSUE TITLE
Add modified timestamp for architecture diagram.

### ISSUE THREAD

**Issue by mackleyd** [MicrosoftDocs/architecture-center#4373]
[Enter feedback here]
It would great to add a modified timestamp for the architecture diagram or a current as of to give a perspective how the diagram fits into the Microsoft roadmap and current guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4bb287-fa40-af1d-0af9-e8bc30cfb33e
* Version Independent ID: 12ab4c06-2e95-bb73-f62a-2d1eb79bc735
* Content: [Real-time analytics on big data architecture - Azure Solution Ideas](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/real-time-analytics)
* Content Source: [docs/solution-ideas/articles/real-time-analytics.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/real-time-analytics.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by AjayBathini-MSFT** [comment]
@mackleyd 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
At this time, Azure Architecture Center doesn't have plans to put timestamps or changelogs on architecture articles. We will consider it in future information architecture conversations. 

#please-close
