### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by fedeformento** [MicrosoftDocs/architecture-center#4374]
Would be really helpful to have this SVG icons with the service name in powerpoint, also with some reference architecture slides that can be used as template for building a proposal for our joint customers. This is how google shares it...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by AjayBathini-MSFT** [comment]
@fedeformento 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by Zimmergren** [comment]
Hey ,@fedeformento , we've got an item on the backlog to review this. Thanks!
#please-close
