### ISSUE TITLE
Article date.

### ISSUE THREAD

**Issue by BlairLawrence** [MicrosoftDocs/architecture-center#4377]
Please add publishing dates to articles. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98d4988b-5130-8b26-0c11-6ed1c35b40dc
* Version Independent ID: 8a622cdb-9ca9-25b1-ed73-02595807d958
* Content: [Power Automate deployment at scale - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/power-automate/power-automate?source=docs)
* Content Source: [docs/example-scenario/power-automate/power-automate.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/power-automate/power-automate.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @svarukala
* Microsoft Alias: **svarukal**

**Comment by AjayBathini-MSFT** [comment]
@BlairLawrence 
Thanks for your feedback! We will investigate and update as appropriate.
