### ISSUE TITLE
Considerations

### ISSUE THREAD

**Issue by tjav** [MicrosoftDocs/architecture-center#4378]
Are the considerations correct. Seems like they swapped.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67f58625-4e97-1fc6-197b-8b25341f5a4f
* Version Independent ID: bdabf990-9a18-ec7f-a948-3fc79dc255e0
* Content: [Cache-Aside pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/cache-aside)
* Content Source: [docs/patterns/cache-aside.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/cache-aside.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ManoharLakkoju-MSFT** [comment]
@tjav 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
Hey there Tim.  Can you give an example of something that is swapped?  We will be reviewing the cloud design pattern content in 2024, and would like to have a specific example to include in our user story.

**Comment by skabou** [comment]
#please-close
