### ISSUE TITLE
More Detail

### ISSUE THREAD

**Issue by Premdeep95** [MicrosoftDocs/architecture-center#4379]
Hello There,

Can you please provide Low level details on this - https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/migrate-cloud-workloads-across-security-tenants

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1a4ae0a-9296-ba9b-8e5e-f695bbb6aeac
* Version Independent ID: b1a4ae0a-9296-ba9b-8e5e-f695bbb6aeac
* Content: [Migrate cloud workloads across security tenants - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/migrate-cloud-workloads-across-security-tenants)
* Content Source: [docs/solution-ideas/articles/migrate-cloud-workloads-across-security-tenants.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/migrate-cloud-workloads-across-security-tenants.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @martinekuan
* Microsoft Alias: **lapate**

**Comment by ManoharLakkoju-MSFT** [comment]
@Premdeep95 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
@lapate Can you please work with @Premdeep95 on learning more about your architecture?  Based on what additional details are shared, please update the article with the same.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 208986 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
