### ISSUE TITLE
[Icon Request] Application Gateway for Containers icon is missing

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/architecture-center#4386]
[https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview) icon is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure icons - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/icons/)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @Zimmergren
* Microsoft Alias: **tozimmergren**

**Comment by Naveenommi-MSFT** [comment]
@ezYakaEagle442 
Thank you for bringing this to our attention.
I've delegated this to content author @Zimmergren, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@Zimmergren 
Please review it.

**Comment by Zimmergren** [comment]
For awareness, and to add to the next batch of icons: @RobBagby , @ckittel

**Comment by ckittel** [comment]
I've opened a request with our icon design team.  @Naveenommi-MSFT, please be aware that we ship icons only a couple times a year, and ad-hoc requests to the icon team are not prioritized over other planned work happening by that team.  We'll keep this issue open, and I'll update it once I've verified it's in a future icon drop.

**Comment by ezYakaEagle442** [comment]
But that did not answer my requirement, how to get the AGC blue icon, could you please share it ?

**Comment by lukemurraynz** [comment]
Hi, @ezYakaEagle442  - Application Gateway for Containers. Hopefully, this is what you are after: ![Application Gateway for Containers](https://github.com/MicrosoftDocs/architecture-center/assets/24467442/d2dae2d6-9604-4374-9d50-820b41d78c74)

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 212835 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
