### ISSUE TITLE
Missing reference to Container Apps Landing Zone Accelerator

### ISSUE THREAD

**Issue by jvalteren** [MicrosoftDocs/architecture-center#4388]
The table containing application landing zone accelerators is missing the Azure Container Apps Landing Zone Accelerator: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/container-apps/landing-zone-accelerator

Please add it for completeness. Perhaps other (application) landing zone accelerators are missing as well, I haven't checked others.

Kind regards,
Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75727ca9-f46f-24a6-3871-25cc45b61de8
* Version Independent ID: 75727ca9-f46f-24a6-3871-25cc45b61de8
* Content: [Deploy Azure landing zones - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/landing-zones/landing-zone-deploy#application)
* Content Source: [docs/landing-zones/landing-zone-deploy.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/landing-zones/landing-zone-deploy.md)
* Service: **architecture-center**
* Sub-service: **guide**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by Naveenommi-MSFT** [comment]
@jvalteren 
Thanks for your feedback! We will investigate and update as appropriate.
