### ISSUE TITLE
is it based on the new AVM ? 

### ISSUE THREAD

**Issue by kikofarad** [MicrosoftDocs/architecture-center#4389]
[Enter feedback here]

is IaaC code here based on the new AVM ? 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2da310dc-1543-c9c9-9863-4606afd20ba1
* Version Independent ID: 2da310dc-1543-c9c9-9863-4606afd20ba1
* Content: [Subscription vending implementation guidance - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/landing-zones/subscription-vending)
* Content Source: [docs/landing-zones/subscription-vending.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/landing-zones/subscription-vending.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ssumner
* Microsoft Alias: **ssumner**

**Comment by ckittel** [comment]
It doesn't appear to be yet, but I'm sure it's on their backlog as the primary author of this repo <https://github.com/Azure/bicep-lz-vending> is also part of the AVM team.

Anyhow, this question is best put to the repo I linked above -- the actual example implementation, and not the Microsoft Learn content.  Going to need to close it here, but please do continue the conversation at the repo linked!  Jack will know for sure the plan there.

#please-close

**Comment by kikofarad** [comment]
Thanks alot will do
