### ISSUE TITLE
Typo in the hyperlink text "- RE:05 Redumdancy"

### ISSUE THREAD

**Issue by Manjunath-Bhavi** [MicrosoftDocs/architecture-center#4392]
[There seems to be typo in the hyperlink text "- [RE:05 Redumdancy](https://learn.microsoft.com/en-us/azure/well-architected/reliability/redundancy)" ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67f58625-4e97-1fc6-197b-8b25341f5a4f
* Version Independent ID: bdabf990-9a18-ec7f-a948-3fc79dc255e0
* Content: [Cache-Aside pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/cache-aside)
* Content Source: [docs/patterns/cache-aside.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/cache-aside.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by navba-MSFT** [comment]
@Manjunath-Bhavi Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by ckittel** [comment]
There sure was!  And I put it there, how embarrassing.  The change has been made and should be live in about 24 hours.  Thanks for letting us know and thanks for the PR @navba-MSFT.

**Comment by Manjunath-Bhavi** [comment]
Fix is live. Thank you @ckittel
