### ISSUE TITLE
Missing hyperlink

### ISSUE THREAD

**Issue by Manjunath-Bhavi** [MicrosoftDocs/architecture-center#4393]
Looks like a hyperlink expected for the word "Example" in the section "Issues and considerations" sentence "In that case, consider using a retry and, or time out mechanism to recognize that operation as a failure. For an example, see the Example section."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f568e9ac-4d16-5076-4863-5e007112b3db
* Version Independent ID: 9180ec47-aaf4-d811-d89d-437dd85fa878
* Content: [Choreography pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/choreography)
* Content Source: [docs/patterns/choreography.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/choreography.yml)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by navba-MSFT** [comment]
@Manjunath-Bhavi Thanks for reaching out to us and reporting this issue. The above PR has been filed and it is currently under review.

**Comment by Manjunath-Bhavi** [comment]
Just verified, fix is live, thank you @ckittel
