### ISSUE TITLE
Database tier replication via disk?

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/architecture-center#4394]
On the diagram it shows that DB1 and DB2 in Region 1 uses Disks and Replica Disks in Region 2 are used by DB1 & DB2. What is the mechanism used to make DB servers (can they be MS SQL on a VM?) to replicate via Disks and how the failover and failback is done. 
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2442849c-9e87-56b2-dffd-5c8089e8132c
* Version Independent ID: 828da465-186b-f819-9575-ee51e8c83306
* Content: [Multi-tier web application built for HA/DR - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/infrastructure/multi-tier-app-disaster-recovery)
* Content Source: [docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/infrastructure/multi-tier-app-disaster-recovery.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @sujayt
* Microsoft Alias: **sutalasi**

**Comment by Naveenommi-MSFT** [comment]
@ctahok 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by skabou** [comment]
Hey there ctahok,
This article you left a comment on describes SQL Server installed on Windows Virtual Machines, so "yes" is the answer to your question "Can they be MS SQL on a VM?"

How to setup disaster recovery with SQL Server and Azure Site Recovery:
https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-sql

Here is a tutorial demonstrating how failover and failback is done:
https://learn.microsoft.com/en-us/azure/site-recovery/azure-to-azure-tutorial-failover-failback

**Comment by skabou** [comment]
#please-close
