### ISSUE TITLE
Azure Operator Insights icon - wrong category

### ISSUE THREAD

**Issue by ThePants999** [MicrosoftDocs/architecture-center#4396]
The February update for the icon set added a bunch of new "Azure Operator" services, all under a "hybrid + multicloud" category. That's not a bad categorisation of most of them, but Azure Operator Insights is nothing to do with hybrid/multicloud; it's an analytics service and belongs in that category.

**Comment by ckittel** [comment]
Thank you @ThePants999, I will share this feedback with the team that creates the .zip file.  Since we only release a few times a year, we won't be able to adjust until the next release.  I'm okay keeping this issue open to track.

**Comment by ThePants999** [comment]
Thanks Chad, much appreciated - I hadn't spotted it was miscategorized there too, I'll go see if I can get that fixed as well.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 217076 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
