### ISSUE TITLE
Route Table Diagram

### ISSUE THREAD

**Issue by zukakosan** [MicrosoftDocs/architecture-center#4397]
I think this Diagram needs route table icon on Subnet AppGwSubnet
![image](https://github.com/MicrosoftDocs/architecture-center/assets/25217308/790d2e76-5140-414b-a49a-86abc26b4c88)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f623b3a-09d7-d793-b007-85b59727c1df
* Version Independent ID: ec0506cd-cdba-784c-6832-ea59697dd39c
* Content: [Zero-trust network for web applications with Azure Firewall and Application Gateway - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/gateway/application-gateway-before-azure-firewall)
* Content Source: [docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by AjayBathini-MSFT** [comment]
@zukakosan 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 217074 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
