### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by ismt123mba** [MicrosoftDocs/architecture-center#4399]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aca5ad7e-2611-198b-6327-d253f5519964
* Version Independent ID: 19059344-22ca-3103-efb8-df3820d92c9e
* Content: [Non-relational data and NoSQL - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/data-guide/big-data/non-relational-data)
* Content Source: [docs/data-guide/big-data/non-relational-data.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-guide/big-data/non-relational-data.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by navba-MSFT** [comment]
@ismt123mba Thanks for reaching out to us. Could you please elaborate the issue and share the feedback about this docs ? So that we can look into this and address it.

**Comment by ckittel** [comment]
#please-close

due to lack of actionable feedback for Architecture Center content.
