### ISSUE TITLE
(Feedback) Multilayered protection for Azure virtual machine access

### ISSUE THREAD

**Issue by ryand423** [MicrosoftDocs/architecture-center#4408]
Dear Azure Architecture Center Team,

I recently came across your article on multilayered protection for Azure virtual machines ("Multilayered Protection for Azure VMs") and found it to be a valuable starting point for understanding the security frameworks applicable to Azure VMs. However, I believe the article would greatly benefit from further expansion in several key areas. Detailed information in these areas would be particularly useful for users looking to implement robust security practices in their Azure environments.

Potential Use Cases:
The current article outlines the concept of multilayered protection but stops short of detailing specific, real-world scenarios where this approach is most beneficial. For instance, providing use case scenarios for different industries such as finance, healthcare, or e-commerce, where data sensitivity and compliance are paramount, would illustrate the practical applications of multilayered protection.

Also, Maybe even add in some examples of a threat protection or Incident response scenarios where the breach has already taken place. For example, an attacker is conduction Account Enumeration post breach and has switch activity from enumerating fake accounts to real accounts that exist in our system.

Alternative Services:
While Azure offers a suite of security features, there are third-party services that can be integrated for enhanced security postures. A comparison of native versus third-party services, along with guidance on when and why to consider alternatives, would be invaluable for decision-makers.

Implementation Considerations:
Step-by-step implementation guides are incredibly useful for IT professionals. Additional content outlining common pitfalls to avoid during the setup and deployment of security layers, as well as best practices for maintaining security over time, would greatly enhance the utility of the article.

Pricing Guidance:
Understanding the cost implications is crucial for any organization. Adding a section on pricing models for the various security services mentioned, including how they may impact the overall cost of operation for an Azure VM, would help organizations plan and budget accordingly.

I believe that expanding on these topics would not only enrich the content but also empower users to more effectively utilize Azure's security features for their virtual machines. Thank you for considering this feedback as part of your ongoing efforts to improve the Azure documentation.

**Comment by ckittel** [comment]
Article link: <https://learn.microsoft.com/azure/architecture/solution-ideas/articles/multilayered-protection-azure-vm>

I've reached out to the author, @husamhilal to advise.

**Comment by husamhilal** [comment]
Thanks a lot for this solid feedback @ryand423 ! You are right, I started drafting a new update, as this article hasn't been updated for a while now. I will be looking forward to publishing the latest updates in two weeks (as I'm on personal leave).

There are great points you mentioned that I will definitely consider and try to make it in the April's updates, such as:
Use cases, Pricing Guidance.

In May (hopefully sooner), I will work on adding Implementation guide (most probably video).

Can you please tell me more on the **Alternative Services** (3rd party) that you consider beneficial? Can you give me a couple of examples, please?

Thanks a lot!

Best regards,
Husam Hilal

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 232808 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
