### ISSUE TITLE
Addition of Azure Open AI

### ISSUE THREAD

**Issue by kSinglaVikas** [MicrosoftDocs/architecture-center#4419]
Add Azure OpenAI to talk to AI search to provide LLM capability.
Article : https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/cognitive-search-with-skillsets

**Comment by PesalaPavan** [comment]
@kSinglaVikas 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by ckittel** [comment]
The author of this article no longer works at Microsoft, @PesalaPavan.

@ShannonLeavitt

**Comment by ShannonLeavitt** [comment]
I sent email to @HeidiSteen to see if she can take ownership of the article and issue.

**Comment by mSarts** [comment]
Assigning to @gmndrg per email thread with @HeidiSteen.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 242234 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
