### ISSUE TITLE
Load Balancing Overview Does not Discuss "Azure Front Door + Azure Load Balancer"

### ISSUE THREAD

**Issue by cancan101** [MicrosoftDocs/architecture-center#4422]
On the [Load-balancing options](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#reference-architecture-examples) page, the docs do not discuss [how / why you would use "Azure Front Door + Azure Load Balancer"](https://github.com/MicrosoftDocs/architecture-center/blob/66d7706df39657f96f11746930376b9f835f4cdb/docs/guide/technology-choices/load-balancing-overview-content.md?plain=1#L64-L75). However, the [Decision tree for load balancing in Azure](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#decision-tree-for-load-balancing-in-azure) DOES show this combination as being a valid architecture option under certain circumstances.
![image](https://github.com/MicrosoftDocs/architecture-center/assets/51059/39fed745-8951-4bc0-9492-f4a7f6c044ec)

It would be great to get the use case documented in the table:

|Services |Article |Description |
|---------|---------|---------|
|Azure Front Door + Application Gateway     | [Multitenant SaaS on Azure](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/multi-saas/multitenant-saas)       |   Use a multitenant solution that includes a combination of Azure Front Door and Application Gateway. Azure Front Door helps load balance traffic across regions. Application Gateway routes and load-balances traffic internally in the application to the various services that satisfy client business needs.  |
|Azure Front Door + AzureLoad Balancer     | |  ???? |

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#reference-architecture-examples)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **pnp**

**Comment by Naveenommi-MSFT** [comment]
@cancan101 
Thank you for bringing this to our attention.
I've delegated this to content author @martinekuan, who will review it and offer their insightful opinions.

**Comment by ckittel** [comment]
@Naveenommi-MSFT, in the future could you please not assign things to @martinekuan, as he is not a content developer nor in a position to directly add this content.

**Comment by RyanHill-MSFT** [comment]
Hi [@RobBagby](https://github.com/RobBagby), can you have a look at this?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 245636 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
