### ISSUE TITLE
You need dates on your reference architectures

### ISSUE THREAD

**Issue by BillmanH** [MicrosoftDocs/architecture-center#4423]
I'm sure that all MicrosoftDocs content is 100% accurate and up to date. However, this is not possible to validate without a stated date of release on the pages. 

Sometimes Microsoft & Azure deprecates a product or framework and it takes some time for that information to make it to every document. For this reason it is important to know when a document was last updated so that we can verify that the document is still relevant. I'm sure this will never be an issue with you, but the ecosystem changes fast and we need to be able to verify that a document is current.

**Comment by PesalaPavan** [comment]
@BillmanH 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by BillmanH** [comment]
Sure, I assumed. I thought this repository was the same as it is linked from the page. 

https://learn.microsoft.com/en-us/azure/architecture/browse/

I haven't looked at all of them, but I'm sure that none of them have publish dates.

**Comment by ckittel** [comment]
Thank you for your feedback on this. Azure Architecture Center used to have dates, and it caused confusion as well.  Fresh looking date, but stale content. Fresh content (evergreen) with old dates.  It's a weird dilemma to be in.  There technically is a date available on every article that you can see in the metadata of the article. Our research has concluded that it causes a misinterpretation of the freshness (in either direction) of the article.  Interestingly, some of our articles still have a date on them.

At this point in time, we do not have any plans on going back and adding dates back in.  I do understand your concern and desire (personally, I share it as well), but it was made as a platform decision based on data.  To change that would require another data study, which isn't planned.

I'm going to close this issue, but I do really appreciate your concern in this matter, and know that you've been heard.

**Comment by BillmanH** [comment]
Bummer

**Comment by ckittel** [comment]
I know it's asking a lot and it's not a learner-friendly way, but if you are interested in any of the various "dates" that are available, you can find them through the following ways:

- You can find the .md file in github (here in this repo) and look at the git history on the file to see when it was created and how it's changed over time.
- In the `<head>` section of the HTML, you'll find a `<meta>` field of `ms.date` which is the date a human made a choice that the article was considered fresh as of.  Sometimes that date was agressively set, sometimes a fresh article just hasn't been reviewed to get a updated date.  Sometimes it's actually right.
