### ISSUE TITLE
база данных управления финансами

### ISSUE THREAD

**Issue by JahongirKadirbaev** [MicrosoftDocs/architecture-center#4442]

**Comment by TPavanBalaji** [comment]
@JahongirKadirbaev 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ckittel** [comment]
@JahongirKadirbaev, I don't know what financial management database article you're looking for help with.  Please re-open with more information in the future.

#please-close
