### ISSUE TITLE
```suggestion

### ISSUE THREAD

**Issue by Hayzlee11** [MicrosoftDocs/architecture-center#4482]
```suggestion
> You need to deploy two or more Virtual Machines to different availability zones in the same region to get the highest possible [SLA connectivity percentage](https://www.microsoft.com/licensing/docs/view/Service-Level-Agreements-SLA-for-Online-Services?lang=1).
```

_Originally posted by @Court72 in https://github.com/MicrosoftDocs/azure-docs/pull/122980#discussion_r1626272690_

**Comment by PesalaPavan** [comment]
@heyams 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by PesalaPavan** [comment]
@Hayzlee11 
We are going to close this thread but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
