### ISSUE TITLE
Article needs to be updated to include Standard Load Balancer guidance

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/architecture-center#660]
This article seems outdated given the (newish) capabilities available with Load Balancer Standard & HA ports.  The article should align with the guidance provided here: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-configure-ha-ports

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bab6a90-43a3-3d83-d680-26683a3d833d
* Version Independent ID: f8eea094-d297-93e6-06ac-7652d059734f
* Content: [Deploy a high availability network virtual appliances](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha#pip-udr-switch-with-layer-4-nvas)
* Content Source: [docs/reference-architectures/dmz/nva-ha.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/dmz/nva-ha.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @larryms 

Thank you for your feedback, and apologies for delay in response. We will investigate and make any necessary changes.

**Comment by doodlemania2** [comment]
Merging with backlog. #please-close

**Comment by kiwibayer** [comment]
can we please include the guidance from: 
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ha-ports-overview

**Comment by absheik** [comment]
AB#160265 - Thanks for reporting - this issue is under review

**Comment by absheik** [comment]
@larryclaman , @kiwibayer , updated table to include Standard Load Balancer HA Ports. https://github.com/MicrosoftDocs/architecture-center-pr/pull/1046.  If you feel further changes are needed please create a pr with your proposed changes.
