### ISSUE TITLE
DNS Settings for the NIC and VNET

### ISSUE THREAD

**Issue by jlee-vi** [MicrosoftDocs/architecture-center#686]
Hi Team,

Would it be possible for the article to be updated with official advice on the DNS settings for the NIC and VNets. 

E.g., two domain controllers in an availability set in a dedicated ADDS subnet. Then separate subnets within the same VNET. Using custom DNS servers for the NICs of the domain controllers, what would the settings be primary, secondary, tertiary. What about the VNET. What about in a hybrid environment with DCs on-prem.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by ragedrk** [comment]
+1 for jlee-vi request, it would be awesome to have your best practics in one place

**Comment by doodlemania2** [comment]
Merging to backlog. Thank you all for the feedback. We'll get this updated soon. #please-close
