### ISSUE TITLE
Doc to walk through the example

### ISSUE THREAD

**Issue by Zenocolo** [MicrosoftDocs/architecture-center#747]
Hi, I think this is execellent DevOps example, but what I'm missing is a description how to run once through the DevOps pipeline, things like EndPoints, username and passwords are missing. Did I miss something? Just deploying is not as useful for me when I cannot login and process a DevOps cycle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5978df0f-98f5-f365-1912-48fc8c27566e
* Version Independent ID: 4f2b4216-1cc7-a267-eee4-d7716ce5ed03
* Content: [CI/CD pipeline for container-based workloads](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-with-aks#related-resources)
* Content Source: [docs/example-scenario/apps/devops-with-aks.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/apps/devops-with-aks.md)
* Service: **guidance**
* GitHub Login: @iainfoulds
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @Zenocolo 

Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by doodlemania2** [comment]
#please-close as guidance updated on product post GA. Will backlog to update example scenario.
