### ISSUE TITLE
Need a deployment ARM for HUB HUB Spoke

### ISSUE THREAD

**Issue by dcallagh** [MicrosoftDocs/architecture-center#801]
I have implemented the HUB  HUB Spoke,  with ONsite and an ER gateway
ONsite-ER-HUB-HuB with NVA-Spoke
Routes to Spoke are not available in Onsite, Spoke cannot tick use remote gateway

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementing a hub-spoke network topology in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @dcallagh 

Thank you for your feedback, and apologies for delay in response! Were you able to locate an answer to your question via different means and make further progress? Please let us know, otherwise, we'll proceed to close this issue.

**Comment by dcallagh** [comment]
Apparently not possible

Sent: Friday, December 07, 2018 at 9:49 AM

**Comment by doodlemania2** [comment]
#pleaseclose

**Comment by doodlemania2** [comment]
#please-close
