### ISSUE TITLE
Management Considerations Windows Server Versions

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/architecture-center#826]
Hello.  Does this apply to all versions of Windows Server?  If not, which versions does this apply to with Windows Server 2016 and 2019 being released to GA soon?  

> Do not shut down a domain controller VM using Azure portal. Instead, shut down and restart from the guest operating system. Shutting down through the portal causes the VM to be deallocated, which resets both the VM-GenerationID and the invocationID of the Active Directory repository. This discards the AD DS relative identifier (RID) pool and marks SYSVOL as nonauthoritative, and may require reconfiguration of the domain controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#manageability-considerations)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @adrianwells 

Thank you for your feedback, and apologies for delay in response! Were you able to locate an answer to your question via different means and make further progress? Please let us know, otherwise, we'll proceed to close this issue.

**Comment by adrianwells** [comment]
@mike-urnun-msft Thank you for the reply.  This document does not specific if it applies to a specific version of Windows Server, might that be added? The question is - do these recommendations still apply to Windows Server 2019 or are they changed?

**Comment by doodlemania2** [comment]
This is applicable to all versions of Windows. Great feedback though! #please-close

**Comment by adrianwells** [comment]
@doodlemania2 might you add verbiage to help others in the future? It appears this is closed without adding wording.

**Comment by doodlemania2** [comment]
@adrianwells oh yes most definitely - I've sent a note over to the AD team to confirm it holds for all versions and  includes specific language for 2019.
