### ISSUE TITLE
Azure DevOps Instructions?

### ISSUE THREAD

**Issue by CloudLassoUK** [MicrosoftDocs/architecture-center#846]
Hi guys -

First off this is great work.  Exactly what I was hoping to find.  However, in the field we are preaching the use of Azure DevOps to manage and deploy IaC and I was hoping someone could provide instructions on how to deploy this with the Dev tool suite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implementing a hub-spoke network topology with shared services in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services?WT.mc_id=email#deploy-the-solution)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by grdhenderson** [comment]
I am so happy I found this article. I rushed to download the Visio file but it is out of date with the website graphics.

**Comment by mike-urnun-msft** [comment]
Hello @CloudLassoUK 

Thanks for the KUDOS, and apologies for the delay in response! Were you able to locate an answer to your question and make further progress? Please let us know, otherwise, we'll proceed to close this issue.

**Comment by CloudLassoUK** [comment]
Hi @mike-urnun-msft -

You're welcome, but sadly no.   Looking for guidance on how to wrap up the project, build, and deploy it through Azure DevOps.   Ideally looking for a way to run it as a CI/CD job   

I know thats a big ask, but something small yet critical is a way to Tim's the submissions of the JSON templates.  For example, how can I *automatically* kick off hub-vnet once onprem-net has finished?  Almost like a WAIT function.  Any idea?  The goal being to turn the deployment into a 'one click operation.

Thanks in advance

**Comment by doodlemania2** [comment]
@Mike-Ubezzi-MSFT -- did this get addressed by recent product announcements on hooking up CI-CD and therefore just needing to make some tuning to both the doc and the graphics?

**Comment by Mike-Ubezzi-MSFT** [comment]
@doodlemania2 Yes, I did finally see that the lower left of the interface allows for navigation to the desired settings:

![Screenshot (91)](https://user-images.githubusercontent.com/37126106/59716120-39c2cd80-91ca-11e9-8637-52e1e6184d3e.png)

**Comment by Mike-Ubezzi-MSFT** [comment]
@doodlemania2 Different issue.

**Comment by doodlemania2** [comment]
Thank you for submitting this issue. We've taken this to our internal backlog for consideration.
