### ISSUE TITLE
Can you use S2S VPN static routing for implementing hub

### ISSUE THREAD

**Issue by vicperdana** [MicrosoftDocs/architecture-center#860]
If we establish S2S VPN with static routing, to the hub vnet - can I then use VNET peering to connect multiple VNETs from the hub?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementing a hub-spoke network topology in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by CloudLassoUK** [comment]
hi @vicperdana - technically there should be no issue with this.  in fact, that is what is being done with the 'on-prem' datacentre in the example Hub and Spoke with Shared Services.  Or I am misunderstanding your goal?

**Comment by vicperdana** [comment]
The example in https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke shows an expressroute connection.

Can the same network topology be applied to a s2s vpn using policy based (static routing)?

Thanks, Vic.
Sent from my iPhone
________________________________

**Comment by CloudLassoUK** [comment]
Ahhhh…..I’d have to dig it up, but I’m pretty sure there is a requirement for dynamic routing.  And if I recall the requirement was due to the underlying network of the platform and how it can interact with the overlay.

Mind you this was over a year ago when I last visited it so who knows if its changed since then.

But if you want a definitive answer keep looking…..sorry.

Are you having trouble getting it to work?

**Comment by mike-urnun-msft** [comment]
Hello @vicperdana 

Thank you for your question, and apologies for the delay in response. Were you able to locate an answer to your question via different means and make progress? Please let us know, otherwise, we'll proceed to close this issue.

**Comment by vicperdana** [comment]
Hi,

Yes, I managed to find it here.

https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-ipsecikepolicy-rm-powershell#2-add-or-update-an-ipsecike-policy-for-a-connection

**Comment by mike-urnun-msft** [comment]
Hi @vicperdana Glad to hear that you've located the solution. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
