### ISSUE TITLE
Traffic flow explained vs template file?

### ISSUE THREAD

**Issue by saif-chaudhry** [MicrosoftDocs/architecture-center#864]
Hi, hope you can clarify this for me? it doesn't appear the explanation given in the architecture is completely accurate looking at the template file i.e. "Public DMZ outbound subnet. Requests that are approved by the NVA pass through this subnet to the internal load balancer for the web tier" ....  the two nics that were assigned to the NVA's in your json template file (in public dmz ) shows one is primary (e.g. public dmz-in nic) and one is not so only the primary nic will get subnet gateway ip address via azure dhcp and able to route traffic out of the subnet as per azure design. The template doesn't configure anything to change this behavior (unless i'm missing something ??) so how does using this template you are able to achieve the above stated flow i.e. dmz-in accept traffic and dmz-out route to ILB for web? To me using this template; the dmz-in nic will always route the traffic and pub-dmz-out is not used at all for anything here. Can you please clarify and correct me if I'm wrong. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132f3909-1efc-e58a-7d58-8d378046f43a
* Version Independent ID: c94ad8d8-49c8-f47d-cf33-956f85b10ab1
* Content: [Implementing a DMZ between Azure and the Internet](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by Weatwagon** [comment]
I've used the ARM template to spin up the resources. I believe your assumptions are correct. Can anyone direct me to how to properly set the second nic up as designed in the diagram to forward traffic through the dmz-in and dmz-out?

**Comment by cheungderek** [comment]
If you look at the secure-vnet-hybrid.json, int-dmz VM has the following JSON settings:

"settings": {
                              "fileUris": [
                                "https://raw.githubusercontent.com/mspnp/template-building-blocks/v1.0.0/templates/resources/Microsoft.Compute/virtualMachines/extensions/linux/enable-iptables-routes/enable-iptables-routes.sh"
                              ],
                              "commandToExecute": "bash enable-iptables-routes.sh internal 10.0.1.100"

The above script setup the iptables of the VMs to do iptables' POSTROUTING processing to change destination IP 10.0.0.20 (int-dmz-lb) to 10.0.1.100, which is the frontend address of the web load balancer.

**Comment by saif-chaudhry** [comment]
Thanks @cheungderek. 

My question is which vm nic is involved in routing the packet to the Lb? The explanation on the MSFT web site is misleading. Simply put if I'm putting a UDR for whatever reason which subnet I should attached it to?  it's always going to be the primary nic and the secondary nic that is attached to this linux vm is not doing anything.

**Comment by doodlemania2** [comment]
Merged to backlog #please-close
