### ISSUE TITLE
WebJobs vs Functions

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#882]
In this article covered WebJob as a service to process compute intensive requests. 
But in an referenced article https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/scalable-web-app recommended service is Azure functions. 
I think we should either in a diagram add an option "WebJob or Functions" or follow the referenced article and replace WebJobs with Azure Functions.

Btw, https://docs.microsoft.com/en-us/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs#compare-functions-and-webjobs we may find only 2 reasons to use webjobs instead of functions 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495b2ac1-3a9c-d1db-2b46-bbfbd0a4b538
* Version Independent ID: 2f6008fa-9b45-6ce1-13b5-74f82550f715
* Content: [Web-Queue-Worker architecture style](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/web-queue-worker)
* Content Source: [docs/guide/architecture-styles/web-queue-worker.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/architecture-styles/web-queue-worker.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @SychevIgor 

Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.
