### ISSUE TITLE
ARM template

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#884]
This guide can be improved, if ARM templates will be mentioned. Key idea is: usage of ARM template will help to deploy applications to multiple regions in a repetitive way 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a14304-4ef8-dc1b-b92d-b021fc169710
* Version Independent ID: 33ad8550-7676-2b43-f6cc-a9eb3d3f2093
* Content: [Make all things redundant](https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/redundancy)
* Content Source: [docs/guide/design-principles/redundancy.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/design-principles/redundancy.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks - I believe that falls more under [Design for operations](https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/design-for-operations) although I agree it's a best practice
