### ISSUE TITLE
Ubunto

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#889]
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/big-data-with-iot
If'm I didn't miss anything, instead of Ubunto on a diagram should be Ubuntu. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5c2b717-8cbb-8794-3a5c-3086e76f1717
* Version Independent ID: 6d6ea7d8-05ec-7903-1df5-6d3fc248a123
* Content: [IoT and data analytics in the construction industry](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/big-data-with-iot)
* Content Source: [docs/example-scenario/data/big-data-with-iot.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/data/big-data-with-iot.md)
* Service: **guidance**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
#sign-off

**Comment by SychevIgor** [comment]
interesting. 5 people participating in this issue. to fix 1 symbol. it takes already 9 months.

**Comment by doodlemania2** [comment]
#please-close per merge to live
