### ISSUE TITLE
Azure SQL Elastic Pools client library

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#896]
Maybe this article will have benefits from https://docs.microsoft.com/en-us/azure/sql-database/sql-database-elastic-database-client-library as an example of sharding in SAAS application
It's not a bug, it's a proposition to improve content and make it closer to practice 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050bb1fd-56ca-63bc-b105-17a56e3b0362
* Version Independent ID: ce84d0a7-3596-e259-dfc3-a9789efd9948
* Content: [Sharding](https://docs.microsoft.com/en-us/azure/architecture/patterns/sharding)
* Content Source: [docs/patterns/sharding.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/sharding.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @SychevIgor 

Thank you for valuable feedback! We will review and make any necessary changes.

**Comment by doodlemania2** [comment]
Merged to backlog #please-close
