### ISSUE TITLE
Web App instead of Web Role and Function (with dedicated plan) instead of Worker Role

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#900]
For a few years, advises to use Cloud Services sounds like a voice from an prehistoric time. Cloud Services not supports ARM model and as I know, it's not even planned. So for me- it's a clear signal- that wee should not use Cloud Services in a new apps and migrate from Cloud Services already existed apps.
To address the same pattern we can use Web App instead of Web Role and Function instead of Worker Role.

To follow the same logic as already exist in this article- Functions app can use Dedicated hosting plan with a queue trigger. If will be used Consumption based patter- it will be hard to talk about "Consistent Rate"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b2b229-0cae-3ba9-180c-5aab1a5a4897
* Version Independent ID: 85c2c9d6-cef4-9a7c-a512-ecdd69e1b456
* Content: [Queue-Based Load Leveling](https://docs.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling)
* Content Source: [docs/patterns/queue-based-load-leveling.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/queue-based-load-leveling.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
I agree this article should be updated to use Web Apps in the example. Regarding rate, there is still a (possible) issue of overwhelming the backend service. e.g., if functions triggered by a queue are hammering a backend service, the service could throttle them.

**Comment by MikeWasson** [comment]
I updated the doc awhile back but forgot to close this issue 😸
