### ISSUE TITLE
Azure function with queue trigger/output an in example 

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/architecture-center#914]
Worker Roles in 2018 sounds like a "stone axes". Agree, it's still not retired, but Microsoft for a long enough time - advising something like Azure Functions as a handler for events.
I think we should re-implement FinalReceiverRoleEntry and PipeFilterARoleEntry with up-to-date services like Azure Functions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d29123-9d65-3e85-ffbb-5138fdf9dc8f
* Version Independent ID: 2a791138-c59d-8413-71be-84de641dd06f
* Content: [Pipes and Filters](https://docs.microsoft.com/en-us/azure/architecture/patterns/pipes-and-filters)
* Content Source: [docs/patterns/pipes-and-filters.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/pipes-and-filters.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @SychevIgor 

Thank you for reporting this issue! We will investigate and make any necessary changes.

**Comment by doodlemania2** [comment]
Merging to backlog for possible future update! Thanks for this great feedback. #please-close
