### ISSUE TITLE
Virtual network limit has been raised to 1000

### ISSUE THREAD

**Issue by larryms** [MicrosoftDocs/architecture-center#922]
The article says in a number of places "There is a default limit of 50 virtual networks per subscription".  This limit was raised and is now 1000 vnets per subscription.
Can the article be updated with this new number, and perhaps any new guidance since the number of vnets per sub is no longer a scarce resource?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707f371c-3a15-6549-9092-113c0e9acf61
* Version Independent ID: 0b9646c0-b8e5-a402-f1be-2aad76d8ee89
* Content: [Enterprise Cloud Adoption: Governance design in Azure for multiple teams](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/governance-multiple-teams?toc=/azure/governance/toc.json)
* Content Source: [docs/cloud-adoption/governance/governance-multiple-teams.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/governance/governance-multiple-teams.md)
* Service: **guidance**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @larryms 

Thank you for reporting this issue! We will investigate and make any necessary changes.

**Comment by rotycenh** [comment]
This has been updated in the latest version of this page which was published as part of the early February CAF released: https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/resource-consistency/governance-multiple-teams
