### ISSUE TITLE
Provide working example

### ISSUE THREAD

**Issue by Liero** [MicrosoftDocs/architecture-center#927]
Some people are struggling to implement reliable event sourcing using Azure PaaS services. It would be nice to have working example, or even better Event Store as a Service :)

You can vote for it here: https://feedback.azure.com/forums/34192--general-feedback/suggestions/35922208-provide-cloud-native-paas-serverless-solution-for

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d510272-fa5f-07f9-8b06-fb88d45d2464
* Version Independent ID: 578a488f-89a7-92cc-779f-b4906f6d731a
* Content: [Event Sourcing](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing)
* Content Source: [docs/patterns/event-sourcing.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/event-sourcing.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @Liero 

Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by Liero** [comment]
@JasRobe: Any update on this? will this be implemented?

**Comment by doodlemania2** [comment]
This has been added to our backlog. We hope to provide an update soon! #please-close
