### ISSUE TITLE
onprem.json protectedSettings

### ISSUE THREAD

**Issue by fmoserinnl** [MicrosoftDocs/architecture-center#959]
Am i correct to assume that we can just replace the domain settings with our own domain name? "configurationArguments": {
                      "DomainName": "contoso.com",
                      "DomainNetbiosName": "CONTOSO",
                      "SiteName": "Azure-Vnet-Site",
                      "OnpremSiteName": "Default-First-Site-Name",

Also in the 'Deploy the Azurte Vnet' section, should onoprem.json not be azure.json ?: azbb -s <subscription_id> -g <resource group> -l <location> -p onoprem.json --deploy

Thanks
Franz Moser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain#deploy-the-simulated-on-premises-datacenter)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by doodlemania2** [comment]
@fmoserinnl did you get resolution on this item?

**Comment by doodlemania2** [comment]
The typo was corrected (https://github.com/MicrosoftDocs/architecture-center/pull/1233/commits/717dc2c4cf662faa6b876429fa5050f5eac1cb35). Going ahead with #please-close but OP can of course reply back if question still remains.

**Comment by fmoserinnl** [comment]
Thanks

This was a while ago and we went with our assumptions back then and got things working.

 

Franz

**Comment by PRMerger9** [comment]
Only Microsoft employees can manage issues via commenting in this repo.

**Comment by doodlemania2** [comment]
thanks @fmoserinnl for letting us know!
