### ISSUE TITLE
Add AWS Lake formation

### ISSUE THREAD

**Issue by patpicos** [MicrosoftDocs/architecture-center#982]
AWS Lake Formation is not represented/compared

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure and AWS services compared - multicloud](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @patpicos 

Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
I'm not sure there's a directly comparable service in Azure. Looks like Data Factory has some overlap.

**Comment by MikeWasson** [comment]
Closing as I don't think there is a direct comparison
